{{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for bc_plan.
                                                plan_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["raw_layer", "raw_billing_centre", "billing_centre", "business_critical", "bc_plan"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:DaysUntilFirstDunningSent::NUMBER AS daysuntilfirstdunningsent,
                data_payload:DaysFromRefDateToFirstInstall::NUMBER AS daysfromrefdatetofirstinstall,
                data_payload:AutoProcessWhenPaymentMatches::BOOLEAN AS autoprocesswhenpaymentmatches,
                CAST(data_payload:NameDenorm::TEXT AS VARCHAR(255)) AS namedenorm,
                data_payload:PolEnterDelnqThreshold_cur::NUMBER AS polenterdelnqthreshold_cur,
                data_payload:Currency::NUMBER AS currency,
                data_payload:SuppressLowBalInvoices::BOOLEAN AS suppresslowbalinvoices,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:MaximumNumberOfInstallments::NUMBER AS maximumnumberofinstallments,
                data_payload:ID::NUMBER AS id,
                data_payload:CreateUserID::NUMBER AS createuserid,
                data_payload:SkipFeeForDownPayment::BOOLEAN AS skipfeefordownpayment,
                data_payload:PaymentExceptionsSent::BOOLEAN AS paymentexceptionssent,
                data_payload:DelayDisbursement::NUMBER AS delaydisbursement,
                data_payload:ClearCommisionThreshold_cur::NUMBER AS clearcommisionthreshold_cur,
                data_payload:ExceptionForPastDueStatement::BOOLEAN AS exceptionforpastduestatement,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:Reporting::BOOLEAN AS reporting,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                data_payload:CreateOffsetsOnBilledInvoices::BOOLEAN AS createoffsetsonbilledinvoices,
                data_payload:PaymentReversalFee_cur::NUMBER AS paymentreversalfee_cur,
                data_payload:Periodicity::NUMBER AS periodicity,
                CAST(data_payload:ClearGrossThreshold AS NUMBER(18,2)) AS cleargrossthreshold,
                data_payload:PromiseDueInDays::NUMBER AS promisedueindays,
                data_payload:DownPaymentAfter::NUMBER AS downpaymentafter,
                CAST(data_payload:InvoiceFee AS NUMBER(18,2)) AS invoicefee,
                data_payload:InvoiceFee_cur::NUMBER AS invoicefee_cur,
                CAST(data_payload:WriteoffThreshold AS NUMBER(18,2)) AS writeoffthreshold,
                data_payload:OfferingType_icare::NUMBER AS offeringtype_icare,
                data_payload:WriteoffThreshold_cur::NUMBER AS writeoffthreshold_cur,
                data_payload:LowGrossCleared::BOOLEAN AS lowgrosscleared,
                data_payload:AllowModOfManDisb::BOOLEAN AS allowmodofmandisb,
                data_payload:ApplicableSegments::NUMBER AS applicablesegments,
                data_payload:CycleCloseDayOfMonth::NUMBER AS cycleclosedayofmonth,
                data_payload:AlignInstallmentsToInvoices::BOOLEAN AS aligninstallmentstoinvoices,
                data_payload:InUse::BOOLEAN AS inuse,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                data_payload:EquityBuffer::NUMBER AS equitybuffer,
                data_payload:UserVisible::BOOLEAN AS uservisible,
                data_payload:RequestIntervalDayCount::NUMBER AS requestintervaldaycount,
                data_payload:SkipInstallmentFees::BOOLEAN AS skipinstallmentfees,
                data_payload:StatementSentAfterCycleClose::BOOLEAN AS statementsentaftercycleclose,
                data_payload:StatementsWithLowNetSuppressed::BOOLEAN AS statementswithlownetsuppressed,
                data_payload:CancellationThreshold_cur::NUMBER AS cancellationthreshold_cur,
                CAST(data_payload:CancellationTarget_icare::TEXT AS VARCHAR(100)) AS cancellationtarget_icare,
                data_payload:GracePeriodDays::NUMBER AS graceperioddays,
                data_payload:InvoicingBlackoutType::NUMBER AS invoicingblackouttype,
                data_payload:CancellationTarget::NUMBER AS cancellationtarget,
                data_payload:DraftIntervalDayCount::NUMBER AS draftintervaldaycount,
                CAST(data_payload:NetThresholdForSuppressingStmt AS NUMBER(18,2)) AS netthresholdforsuppressingstmt,
                data_payload:SendAutoDisbAwaitingApproval::BOOLEAN AS sendautodisbawaitingapproval,
                data_payload:DaysBeforePlcyExpForInvBlckout::NUMBER AS daysbeforeplcyexpforinvblckout,
                CAST(data_payload:LowBalanceThreshold AS NUMBER(18,2)) AS lowbalancethreshold,
                data_payload:LowBalanceThreshold_cur::NUMBER AS lowbalancethreshold_cur,
                data_payload:ExceptionIfPromiseNotReceived::BOOLEAN AS exceptionifpromisenotreceived,
                CAST(data_payload:ReinstatementFeeAmount AS NUMBER(18,2)) AS reinstatementfeeamount,
                data_payload:CreateApprActForAutoDisb::BOOLEAN AS createappractforautodisb,
                data_payload:SnapshotNonPastDueItems::BOOLEAN AS snapshotnonpastdueitems,
                data_payload:ReinstatementFeeAmount_cur::NUMBER AS reinstatementfeeamount_cur,
                data_payload:WorkflowPlan::NUMBER AS workflowplan,
                data_payload:NetThresholdSuppressStmt_cur::NUMBER AS netthresholdsuppressstmt_cur,
                CAST(data_payload:InstallmentFee AS NUMBER(18,2)) AS installmentfee,
                data_payload:InstallmentFee_cur::NUMBER AS installmentfee_cur,
                data_payload:Statement::NUMBER AS statement,
                data_payload:PaymentDueDayLogic::NUMBER AS paymentduedaylogic,
                data_payload:BillDateOrDueDateBilling::NUMBER AS billdateorduedatebilling,
                CAST(data_payload:DisbursementOver AS NUMBER(18,2)) AS disbursementover,
                CAST(data_payload:ExitDelinquencyThreshold AS NUMBER(18,2)) AS exitdelinquencythreshold,
                data_payload:DisbursementOver_cur::NUMBER AS disbursementover_cur,
                data_payload:SecondInstallmentAfter::NUMBER AS secondinstallmentafter,
                data_payload:PromiseExceptionsSent::BOOLEAN AS promiseexceptionssent,
                CAST(data_payload:LateFeeAmount AS NUMBER(18,2)) AS latefeeamount,
                data_payload:PmntSchdChngOffsetsOnBilled::BOOLEAN AS pmntschdchngoffsetsonbilled,
                data_payload:DaysAfterCycleCloseToSendStmnt::NUMBER AS daysaftercycleclosetosendstmnt,
                data_payload:Subtype::NUMBER AS subtype,
                CAST(data_payload:AcctEnterDelinquencyThreshold AS NUMBER(18,2)) AS acctenterdelinquencythreshold,
                data_payload:PaymentTermsInDays::NUMBER AS paymenttermsindays,
                data_payload:CycleCloseDayOfMonthLogic::NUMBER AS cycleclosedayofmonthlogic,
                CAST(data_payload:PolEnterDelinquencyThreshold AS NUMBER(18,2)) AS polenterdelinquencythreshold,
                data_payload:AcctEnterDelnqThreshold_cur::NUMBER AS acctenterdelnqthreshold_cur,
                data_payload:HoldInvoicingOnDlnqPolicies::BOOLEAN AS holdinvoicingondlnqpolicies,
                data_payload:AvailableDisbAmtType::NUMBER AS availabledisbamttype,
                data_payload:GracePeriodDayUnit::NUMBER AS graceperioddayunit,
                CAST(data_payload:Name::TEXT AS VARCHAR(255)) AS name,
                data_payload:InvoiceItemPlacementCutoffType::NUMBER AS invoiceitemplacementcutofftype,
                data_payload:LowCommissionCleared::BOOLEAN AS lowcommissioncleared,
                data_payload:OneTimeChargeAfter::NUMBER AS onetimechargeafter,
                CAST(data_payload:DownPaymentPercent AS NUMBER(5,2)) AS downpaymentpercent,
                data_payload:EquityWarningsEnabled::BOOLEAN AS equitywarningsenabled,
                CAST(data_payload:ClearCommisionThreshold AS NUMBER(18,2)) AS clearcommisionthreshold,
                data_payload:Retired::NUMBER AS retired,
                data_payload:DaysFromRefDateToDownPayment::NUMBER AS daysfromrefdatetodownpayment,
                data_payload:SecondDunningSentIfNotPaid::BOOLEAN AS seconddunningsentifnotpaid,
                CAST(data_payload:PaymentReversalFee AS NUMBER(18,2)) AS paymentreversalfee,
                data_payload:WesternMethod::BOOLEAN AS westernmethod,
                data_payload:FirstInstallmentAfter::NUMBER AS firstinstallmentafter,
                data_payload:ClearGrossThreshold_cur::NUMBER AS cleargrossthreshold_cur,
                data_payload:ListBillAccountExcessTreatment::NUMBER AS listbillaccountexcesstreatment,
                data_payload:ChargeQualification::NUMBER AS chargequalification,
                data_payload:ChangeDeadlineIntervalDayCount::NUMBER AS changedeadlineintervaldaycount,
                data_payload:PlanOrder::NUMBER AS planorder,
                CAST(data_payload:CancellationThreshold AS NUMBER(18,2)) AS cancellationthreshold,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                CAST(data_payload:ReviewDisbursementOver AS NUMBER(18,2)) AS reviewdisbursementover,
                data_payload:ReviewDisbursementOver_cur::NUMBER AS reviewdisbursementover_cur,
                data_payload:DaysUntilSecondDunningSent::NUMBER AS daysuntilseconddunningsent,
                TO_TIMESTAMP_TZ(data_payload:EffectiveDate::NUMBER/1000) AS effectivedate,
                data_payload:LeadTimeDayUnit::NUMBER AS leadtimedayunit,
                data_payload:ClearingLogicTarget::NUMBER AS clearinglogictarget,
                TO_TIMESTAMP_TZ(data_payload:ExpirationDate::NUMBER/1000) AS expirationdate,
                data_payload:ReminderSentIfPromiseNotRcvd::BOOLEAN AS remindersentifpromisenotrcvd,
                data_payload:DaysUntilPromiseReminderSent::NUMBER AS daysuntilpromiseremindersent,
                data_payload:DownPaymentSecondInstallment::NUMBER AS downpaymentsecondinstallment,
                data_payload:Aggregation::NUMBER AS aggregation,
                data_payload:DraftDayLogic::NUMBER AS draftdaylogic,
                data_payload:UpgradedFromBefore9::BOOLEAN AS upgradedfrombefore9,
                CAST(data_payload:ProducerWriteoffThreshold AS NUMBER(18,2)) AS producerwriteoffthreshold,
                data_payload:LowBalanceMethod::NUMBER AS lowbalancemethod,
                data_payload:FirstDunningSentIfNotPaid::BOOLEAN AS firstdunningsentifnotpaid,
                data_payload:ProducerWriteoffThreshold_cur::NUMBER AS producerwriteoffthreshold_cur,
                data_payload:DaysFromRefDateToOneTimeCharge::NUMBER AS daysfromrefdatetoonetimecharge,
                data_payload:DaysFromRefDateToSecondInstall::NUMBER AS daysfromrefdatetosecondinstall,
                data_payload:PaymentDueInterval::NUMBER AS paymentdueinterval,
                data_payload:NonResponsivePmntDueInterval::NUMBER AS nonresponsivepmntdueinterval,
                data_payload:ExitDelinquencyThreshold_cur::NUMBER AS exitdelinquencythreshold_cur,
                data_payload:LateFeeAmount_cur::NUMBER AS latefeeamount_cur,
                CAST(data_payload:Description::TEXT AS VARCHAR(1333)) AS description,
                data_payload:LOBCode_icare::NUMBER AS lobcode_icare,
                data_payload:IsBackdatedPlan_Ext::BOOLEAN AS isbackdatedplan_ext,
                data_payload:AdjDaysBeforePolExpiry_Ext::NUMBER AS adjdaysbeforepolexpiry_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwbc', 'bc_plan') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:daysuntilfirstdunningsent::NUMBER AS daysuntilfirstdunningsent,
                $1:daysfromrefdatetofirstinstall::NUMBER AS daysfromrefdatetofirstinstall,
                $1:autoprocesswhenpaymentmatches::BOOLEAN AS autoprocesswhenpaymentmatches,
                CAST($1:namedenorm::TEXT AS VARCHAR(255)) AS namedenorm,
                $1:polenterdelnqthreshold_cur::NUMBER AS polenterdelnqthreshold_cur,
                $1:currency::NUMBER AS currency,
                $1:suppresslowbalinvoices::BOOLEAN AS suppresslowbalinvoices,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:maximumnumberofinstallments::NUMBER AS maximumnumberofinstallments,
                $1:id::NUMBER AS id,
                $1:createuserid::NUMBER AS createuserid,
                $1:skipfeefordownpayment::BOOLEAN AS skipfeefordownpayment,
                $1:paymentexceptionssent::BOOLEAN AS paymentexceptionssent,
                $1:delaydisbursement::NUMBER AS delaydisbursement,
                $1:clearcommisionthreshold_cur::NUMBER AS clearcommisionthreshold_cur,
                $1:exceptionforpastduestatement::BOOLEAN AS exceptionforpastduestatement,
                $1:beanversion::NUMBER AS beanversion,
                $1:reporting::BOOLEAN AS reporting,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:createoffsetsonbilledinvoices::BOOLEAN AS createoffsetsonbilledinvoices,
                $1:paymentreversalfee_cur::NUMBER AS paymentreversalfee_cur,
                $1:periodicity::NUMBER AS periodicity,
                CAST($1:cleargrossthreshold AS NUMBER(18,2)) AS cleargrossthreshold,
                $1:promisedueindays::NUMBER AS promisedueindays,
                $1:downpaymentafter::NUMBER AS downpaymentafter,
                CAST($1:invoicefee AS NUMBER(18,2)) AS invoicefee,
                $1:invoicefee_cur::NUMBER AS invoicefee_cur,
                CAST($1:writeoffthreshold AS NUMBER(18,2)) AS writeoffthreshold,
                $1:offeringtype_icare::NUMBER AS offeringtype_icare,
                $1:writeoffthreshold_cur::NUMBER AS writeoffthreshold_cur,
                $1:lowgrosscleared::BOOLEAN AS lowgrosscleared,
                $1:allowmodofmandisb::BOOLEAN AS allowmodofmandisb,
                $1:applicablesegments::NUMBER AS applicablesegments,
                $1:cycleclosedayofmonth::NUMBER AS cycleclosedayofmonth,
                $1:aligninstallmentstoinvoices::BOOLEAN AS aligninstallmentstoinvoices,
                $1:inuse::BOOLEAN AS inuse,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:equitybuffer::NUMBER AS equitybuffer,
                $1:uservisible::BOOLEAN AS uservisible,
                $1:requestintervaldaycount::NUMBER AS requestintervaldaycount,
                $1:skipinstallmentfees::BOOLEAN AS skipinstallmentfees,
                $1:statementsentaftercycleclose::BOOLEAN AS statementsentaftercycleclose,
                $1:statementswithlownetsuppressed::BOOLEAN AS statementswithlownetsuppressed,
                $1:cancellationthreshold_cur::NUMBER AS cancellationthreshold_cur,
                CAST($1:cancellationtarget_icare::TEXT AS VARCHAR(100)) AS cancellationtarget_icare,
                $1:graceperioddays::NUMBER AS graceperioddays,
                $1:invoicingblackouttype::NUMBER AS invoicingblackouttype,
                $1:cancellationtarget::NUMBER AS cancellationtarget,
                $1:draftintervaldaycount::NUMBER AS draftintervaldaycount,
                CAST($1:netthresholdforsuppressingstmt AS NUMBER(18,2)) AS netthresholdforsuppressingstmt,
                $1:sendautodisbawaitingapproval::BOOLEAN AS sendautodisbawaitingapproval,
                $1:daysbeforeplcyexpforinvblckout::NUMBER AS daysbeforeplcyexpforinvblckout,
                CAST($1:lowbalancethreshold AS NUMBER(18,2)) AS lowbalancethreshold,
                $1:lowbalancethreshold_cur::NUMBER AS lowbalancethreshold_cur,
                $1:exceptionifpromisenotreceived::BOOLEAN AS exceptionifpromisenotreceived,
                CAST($1:reinstatementfeeamount AS NUMBER(18,2)) AS reinstatementfeeamount,
                $1:createappractforautodisb::BOOLEAN AS createappractforautodisb,
                $1:snapshotnonpastdueitems::BOOLEAN AS snapshotnonpastdueitems,
                $1:reinstatementfeeamount_cur::NUMBER AS reinstatementfeeamount_cur,
                $1:workflowplan::NUMBER AS workflowplan,
                $1:netthresholdsuppressstmt_cur::NUMBER AS netthresholdsuppressstmt_cur,
                CAST($1:installmentfee AS NUMBER(18,2)) AS installmentfee,
                $1:installmentfee_cur::NUMBER AS installmentfee_cur,
                $1:statement::NUMBER AS statement,
                $1:paymentduedaylogic::NUMBER AS paymentduedaylogic,
                $1:billdateorduedatebilling::NUMBER AS billdateorduedatebilling,
                CAST($1:disbursementover AS NUMBER(18,2)) AS disbursementover,
                CAST($1:exitdelinquencythreshold AS NUMBER(18,2)) AS exitdelinquencythreshold,
                $1:disbursementover_cur::NUMBER AS disbursementover_cur,
                $1:secondinstallmentafter::NUMBER AS secondinstallmentafter,
                $1:promiseexceptionssent::BOOLEAN AS promiseexceptionssent,
                CAST($1:latefeeamount AS NUMBER(18,2)) AS latefeeamount,
                $1:pmntschdchngoffsetsonbilled::BOOLEAN AS pmntschdchngoffsetsonbilled,
                $1:daysaftercycleclosetosendstmnt::NUMBER AS daysaftercycleclosetosendstmnt,
                $1:subtype::NUMBER AS subtype,
                CAST($1:acctenterdelinquencythreshold AS NUMBER(18,2)) AS acctenterdelinquencythreshold,
                $1:paymenttermsindays::NUMBER AS paymenttermsindays,
                $1:cycleclosedayofmonthlogic::NUMBER AS cycleclosedayofmonthlogic,
                CAST($1:polenterdelinquencythreshold AS NUMBER(18,2)) AS polenterdelinquencythreshold,
                $1:acctenterdelnqthreshold_cur::NUMBER AS acctenterdelnqthreshold_cur,
                $1:holdinvoicingondlnqpolicies::BOOLEAN AS holdinvoicingondlnqpolicies,
                $1:availabledisbamttype::NUMBER AS availabledisbamttype,
                $1:graceperioddayunit::NUMBER AS graceperioddayunit,
                CAST($1:name::TEXT AS VARCHAR(255)) AS name,
                $1:invoiceitemplacementcutofftype::NUMBER AS invoiceitemplacementcutofftype,
                $1:lowcommissioncleared::BOOLEAN AS lowcommissioncleared,
                $1:onetimechargeafter::NUMBER AS onetimechargeafter,
                CAST($1:downpaymentpercent AS NUMBER(5,2)) AS downpaymentpercent,
                $1:equitywarningsenabled::BOOLEAN AS equitywarningsenabled,
                CAST($1:clearcommisionthreshold AS NUMBER(18,2)) AS clearcommisionthreshold,
                $1:retired::NUMBER AS retired,
                $1:daysfromrefdatetodownpayment::NUMBER AS daysfromrefdatetodownpayment,
                $1:seconddunningsentifnotpaid::BOOLEAN AS seconddunningsentifnotpaid,
                CAST($1:paymentreversalfee AS NUMBER(18,2)) AS paymentreversalfee,
                $1:westernmethod::BOOLEAN AS westernmethod,
                $1:firstinstallmentafter::NUMBER AS firstinstallmentafter,
                $1:cleargrossthreshold_cur::NUMBER AS cleargrossthreshold_cur,
                $1:listbillaccountexcesstreatment::NUMBER AS listbillaccountexcesstreatment,
                $1:chargequalification::NUMBER AS chargequalification,
                $1:changedeadlineintervaldaycount::NUMBER AS changedeadlineintervaldaycount,
                $1:planorder::NUMBER AS planorder,
                CAST($1:cancellationthreshold AS NUMBER(18,2)) AS cancellationthreshold,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                CAST($1:reviewdisbursementover AS NUMBER(18,2)) AS reviewdisbursementover,
                $1:reviewdisbursementover_cur::NUMBER AS reviewdisbursementover_cur,
                $1:daysuntilseconddunningsent::NUMBER AS daysuntilseconddunningsent,
                $1:effectivedate::TIMESTAMP_TZ AS effectivedate,
                $1:leadtimedayunit::NUMBER AS leadtimedayunit,
                $1:clearinglogictarget::NUMBER AS clearinglogictarget,
                $1:expirationdate::TIMESTAMP_TZ AS expirationdate,
                $1:remindersentifpromisenotrcvd::BOOLEAN AS remindersentifpromisenotrcvd,
                $1:daysuntilpromiseremindersent::NUMBER AS daysuntilpromiseremindersent,
                $1:downpaymentsecondinstallment::NUMBER AS downpaymentsecondinstallment,
                $1:aggregation::NUMBER AS aggregation,
                $1:draftdaylogic::NUMBER AS draftdaylogic,
                $1:upgradedfrombefore9::BOOLEAN AS upgradedfrombefore9,
                CAST($1:producerwriteoffthreshold AS NUMBER(18,2)) AS producerwriteoffthreshold,
                $1:lowbalancemethod::NUMBER AS lowbalancemethod,
                $1:firstdunningsentifnotpaid::BOOLEAN AS firstdunningsentifnotpaid,
                $1:producerwriteoffthreshold_cur::NUMBER AS producerwriteoffthreshold_cur,
                $1:daysfromrefdatetoonetimecharge::NUMBER AS daysfromrefdatetoonetimecharge,
                $1:daysfromrefdatetosecondinstall::NUMBER AS daysfromrefdatetosecondinstall,
                $1:paymentdueinterval::NUMBER AS paymentdueinterval,
                $1:nonresponsivepmntdueinterval::NUMBER AS nonresponsivepmntdueinterval,
                $1:exitdelinquencythreshold_cur::NUMBER AS exitdelinquencythreshold_cur,
                $1:latefeeamount_cur::NUMBER AS latefeeamount_cur,
                CAST($1:description::TEXT AS VARCHAR(1333)) AS description,
                $1:lobcode_icare::NUMBER AS lobcode_icare,
                $1:isbackdatedplan_ext::BOOLEAN AS isbackdatedplan_ext,
                $1:adjdaysbeforepolexpiry_ext::NUMBER AS adjdaysbeforepolexpiry_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwbc', 'bc_plan') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS plan_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'daysuntilfirstdunningsent',
                        'daysfromrefdatetofirstinstall',
                        'autoprocesswhenpaymentmatches',
                        'namedenorm',
                        'polenterdelnqthreshold_cur',
                        'currency',
                        'suppresslowbalinvoices',
                        'updatetime',
                        'maximumnumberofinstallments',
                        'createuserid',
                        'skipfeefordownpayment',
                        'paymentexceptionssent',
                        'delaydisbursement',
                        'clearcommisionthreshold_cur',
                        'exceptionforpastduestatement',
                        'beanversion',
                        'reporting',
                        'updateuserid',
                        'createoffsetsonbilledinvoices',
                        'paymentreversalfee_cur',
                        'periodicity',
                        'cleargrossthreshold',
                        'promisedueindays',
                        'downpaymentafter',
                        'invoicefee',
                        'invoicefee_cur',
                        'writeoffthreshold',
                        'offeringtype_icare',
                        'writeoffthreshold_cur',
                        'lowgrosscleared',
                        'allowmodofmandisb',
                        'applicablesegments',
                        'cycleclosedayofmonth',
                        'aligninstallmentstoinvoices',
                        'inuse',
                        'publicid',
                        'equitybuffer',
                        'uservisible',
                        'requestintervaldaycount',
                        'skipinstallmentfees',
                        'statementsentaftercycleclose',
                        'statementswithlownetsuppressed',
                        'cancellationthreshold_cur',
                        'cancellationtarget_icare',
                        'graceperioddays',
                        'invoicingblackouttype',
                        'cancellationtarget',
                        'draftintervaldaycount',
                        'netthresholdforsuppressingstmt',
                        'sendautodisbawaitingapproval',
                        'daysbeforeplcyexpforinvblckout',
                        'lowbalancethreshold',
                        'lowbalancethreshold_cur',
                        'exceptionifpromisenotreceived',
                        'reinstatementfeeamount',
                        'createappractforautodisb',
                        'snapshotnonpastdueitems',
                        'reinstatementfeeamount_cur',
                        'workflowplan',
                        'netthresholdsuppressstmt_cur',
                        'installmentfee',
                        'installmentfee_cur',
                        'statement',
                        'paymentduedaylogic',
                        'billdateorduedatebilling',
                        'disbursementover',
                        'exitdelinquencythreshold',
                        'disbursementover_cur',
                        'secondinstallmentafter',
                        'promiseexceptionssent',
                        'latefeeamount',
                        'pmntschdchngoffsetsonbilled',
                        'daysaftercycleclosetosendstmnt',
                        'subtype',
                        'acctenterdelinquencythreshold',
                        'paymenttermsindays',
                        'cycleclosedayofmonthlogic',
                        'polenterdelinquencythreshold',
                        'acctenterdelnqthreshold_cur',
                        'holdinvoicingondlnqpolicies',
                        'availabledisbamttype',
                        'graceperioddayunit',
                        'name',
                        'invoiceitemplacementcutofftype',
                        'lowcommissioncleared',
                        'onetimechargeafter',
                        'downpaymentpercent',
                        'equitywarningsenabled',
                        'clearcommisionthreshold',
                        'retired',
                        'daysfromrefdatetodownpayment',
                        'seconddunningsentifnotpaid',
                        'paymentreversalfee',
                        'westernmethod',
                        'firstinstallmentafter',
                        'cleargrossthreshold_cur',
                        'listbillaccountexcesstreatment',
                        'chargequalification',
                        'changedeadlineintervaldaycount',
                        'planorder',
                        'cancellationthreshold',
                        'createtime',
                        'reviewdisbursementover',
                        'reviewdisbursementover_cur',
                        'daysuntilseconddunningsent',
                        'effectivedate',
                        'leadtimedayunit',
                        'clearinglogictarget',
                        'expirationdate',
                        'remindersentifpromisenotrcvd',
                        'daysuntilpromiseremindersent',
                        'downpaymentsecondinstallment',
                        'aggregation',
                        'draftdaylogic',
                        'upgradedfrombefore9',
                        'producerwriteoffthreshold',
                        'lowbalancemethod',
                        'firstdunningsentifnotpaid',
                        'producerwriteoffthreshold_cur',
                        'daysfromrefdatetoonetimecharge',
                        'daysfromrefdatetosecondinstall',
                        'paymentdueinterval',
                        'nonresponsivepmntdueinterval',
                        'exitdelinquencythreshold_cur',
                        'latefeeamount_cur',
                        'description',
                        'lobcode_icare',
                        'isbackdatedplan_ext',
                        'adjdaysbeforepolexpiry_ext'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS dbt_updated_at
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}