{% snapshot pc_account_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026-01-01      0.0                             SCD Type 2 snapshot for pc_account.
                                                Source: ref('stg_raw_pc_account')
                                                unique_key: account_sk (surrogate on PK 'id')
                                                check_cols: ['hash_key'] (surrogate on all business cols excl PK)
                                                hard_deletes: new_record (inserts dbt_is_deleted=True row)
                                                No code change required when PARQUET CDC goes live.
-#}

{{ config(
    target_schema='gwpc',
    unique_key='account_sk',
    strategy='check',
    alias='pc_account',
    check_cols=['hash_key'],
    hard_deletes='new_record',
    tags=['snapshot', 'policy_centre', 'non_business_critical', 'pc_account']
) }}

SELECT
    account_sk,
    hash_key,
    COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS dbt_updated_at,
    trustabnstatus_icare,
    groupnumber_icare,
    busopsdesc,
    publicid,
    groupname_icare,
    acn_icare,
    createtime,
    newaccountreason_icare,
    linkcontacts,
    itcentitlement_icare,
    trustabn_icare,
    accountorgtype,
    locationautonumberseq,
    isparent,
    updatetime,
    abrvalidationstatus_icare,
    servicetier,
    abnstatus_icare,
    primarylanguage,
    id,
    statebureaunum,
    primarylocale,
    groupcommencementdate_icare,
    commencementdate_icare,
    trustname_icare,
    accountstatus,
    frozen,
    createuserid,
    yearbusinessstarted,
    industrycodeid,
    beanversion,
    abn_icare,
    retired,
    trusteetype_icare,
    lockingcolumn,
    otherorgtypedescription,
    updateuserid,
    accountnumberdenorm,
    cluster_icare,
    accountnumber,
    isvedavalidated,
    acnstatus_icare,
    preferredcoveragecurrency,
    preferredsettlementcurrency,
    gstregistration_icare,
    originationdate,
    trusteename_icare,
    anonymous,
    groupnumberdenorm_icare,
    acndenorm_icare,
    abndenorm_icare,
    crmuniqueid_icare,
    sourcesystem_icare,
    crmversion_icare,
    accountstatusupdatetime,
    archivestate,
    archiveschemainfo,
    donotdestroy,
    excludereason,
    archivefailureid,
    excludedfromarchive,
    archivefailuredetailsid,
    archivepartition,
    archivedate,
    insolvency_ext,
    referredtornsw_ext,
    customerrefcode_ext,
    gststatus_ext,
    gststatusfromdate_ext,
    hasuserexercisedchoice_ext,
    policyspecialistcspname_ext,
    exercisecspchoice_ext,
    policygeneralcspname_ext,
    eligibilitytoselectcsp_ext,
    iseligibleforcspconfirmdoc_ext,
    ispolicyinsyncwithgroup_ext,
    creationsource_ext,
    activefrom_ext,
    portfoliocode_ext,
    agencytype_ext,
    tmfcostcentrerequiredflag_ext,
    agencycode_ext,
    activeto_ext,
    ishealthportfolio_ext,
    tmfcostcentrelevelind_ext,
    icp_ext,
    pool_ext,
    isgrouptermrenamed_ext,
    ismigrated_ext,
    sapcustomernumber_ext,
    'GWPC' AS source_system,
    gwcbi_connector_ts_ms,
    gwcbi_lsn,
    gwcbi_operation,
    gwcbi_payload_ts_ms,
    gwcbi_seqval,
    gwcbi_seqval_hex,
    gwcbi_tx_id,
    metadata_file_name,
    file_ingestion_timestamp
FROM {{ ref('stg_raw_pc_account') }}

{% endsnapshot %}