{% snapshot pc_activity_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026-01-01      0.0                             SCD Type 2 snapshot for pc_activity.
                                                Source: ref('stg_raw_pc_activity')
                                                unique_key: activity_sk (surrogate on PK 'id')
                                                check_cols: ['hash_key'] (surrogate on all business cols excl PK)
                                                hard_deletes: new_record (inserts dbt_is_deleted=True row)
                                                No code change required when PARQUET CDC goes live.
-#}

{{ config(
    target_schema='gwpc',
    unique_key='activity_sk',
    strategy='check',
    alias='pc_activity',
    check_cols=['hash_key'],
    hard_deletes='new_record',
    tags=['snapshot', 'policy_centre', 'non_business_critical', 'pc_activity']
) }}

SELECT
    activity_sk,
    hash_key,
    COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS dbt_updated_at,
    loadcommandid,
    previousgroupid,
    accountid,
    enddate,
    assignedbyuserid,
    externallyowned,
    logicalname,
    approvalrationale,
    documenttemplate,
    previousqueueid,
    emailtemplate,
    updatetime,
    jobid,
    workflowid,
    id,
    closeuserid,
    createuserid,
    priority,
    closedate,
    beanversion,
    retired,
    validationlevel,
    subject,
    accountcontactid,
    updateuserid,
    shortsubject,
    approved,
    type,
    targetdate,
    autogenerated,
    escalationdate,
    publicid,
    lastvieweddate,
    activityclass,
    createtime,
    command,
    assignedgroupid,
    policyid,
    contingency,
    mandatory,
    recurring,
    previoususerid,
    assignedqueueid,
    archivepartition,
    escalated,
    status,
    assigneduserid,
    approvalissue,
    subtype,
    assignmentdate,
    activitypatternid,
    description,
    associatedrole,
    assignmentstatus,
    renewaldate,
    contactid,
    'GWPC' AS source_system,
    gwcbi_connector_ts_ms,
    gwcbi_lsn,
    gwcbi_operation,
    gwcbi_payload_ts_ms,
    gwcbi_seqval,
    gwcbi_seqval_hex,
    gwcbi_tx_id,
    metadata_file_name,
    file_ingestion_timestamp
FROM {{ ref('stg_raw_pc_activity') }}

{% endsnapshot %}