{% snapshot pcx_crprojectcov_icare_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026-01-01      0.0                             SCD Type 2 snapshot for pcx_crprojectcov_icare.
                                                Source: ref('stg_raw_pcx_crprojectcov_icare')
                                                unique_key: crprojectcov_icare_sk (surrogate on PK 'id')
                                                check_cols: ['hash_key'] (surrogate on all business cols excl PK)
                                                hard_deletes: new_record (inserts dbt_is_deleted=True row)
                                                No code change required when PARQUET CDC goes live.
-#}

{{ config(
    target_schema='gwpc',
    unique_key='crprojectcov_icare_sk',
    strategy='check',
    alias='pcx_crprojectcov_icare',
    check_cols=['hash_key'],
    hard_deletes='new_record',
    tags=['snapshot', 'policy_centre', 'non_business_critical', 'pcx_crprojectcov_icare']
) }}

SELECT
    crprojectcov_icare_sk,
    hash_key,
    COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS dbt_updated_at,
    directterm5,
    directterm6,
    directterm11avl,
    directterm7,
    directterm8,
    directterm9,
    choiceterm13avl,
    choiceterm9avl,
    fixedid,
    choiceterm5avl,
    currency,
    choiceterm1avl,
    directterm7avl,
    updatetime,
    directterm3avl,
    booleanterm1avl,
    id,
    booleanterm1,
    booleanterm2,
    booleanterm3,
    dateterm1avl,
    createuserid,
    directterm10avl,
    choiceterm16avl,
    beanversion,
    choiceterm12avl,
    choiceterm8avl,
    updateuserid,
    choiceterm4avl,
    directterm10,
    directterm11,
    referencedateinternal,
    directterm6avl,
    directterm2avl,
    branchid,
    publicid,
    choiceterm1,
    choiceterm2,
    choiceterm3,
    choiceterm15avl,
    choiceterm4,
    choiceterm5,
    createtime,
    choiceterm6,
    choiceterm7,
    crproject,
    choiceterm11avl,
    choiceterm8,
    choiceterm9,
    choiceterm7avl,
    choiceterm3avl,
    directterm9avl,
    effectivedate,
    directterm5avl,
    dateterm1,
    booleanterm3avl,
    dateterm2,
    directterm1avl,
    expirationdate,
    choiceterm14avl,
    archivepartition,
    changetype,
    choiceterm10avl,
    choiceterm10,
    basedonid,
    choiceterm11,
    choiceterm12,
    choiceterm6avl,
    choiceterm13,
    choiceterm14,
    choiceterm15,
    choiceterm2avl,
    choiceterm16,
    directterm8avl,
    directterm4avl,
    booleanterm2avl,
    subtype,
    directterm1,
    patterncode,
    directterm2,
    directterm3,
    directterm4,
    dateterm2avl,
    'GWPC' AS source_system,
    gwcbi_connector_ts_ms,
    gwcbi_lsn,
    gwcbi_operation,
    gwcbi_payload_ts_ms,
    gwcbi_seqval,
    gwcbi_seqval_hex,
    gwcbi_tx_id,
    metadata_file_name,
    file_ingestion_timestamp
FROM {{ ref('stg_raw_pcx_crprojectcov_icare') }}

{% endsnapshot %}