{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for cc_contact.
                                                contact_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["raw_layer", "raw_claim_centre", "claim_centre", "business_critical", "cc_contact"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:TrustABNIsActive_icare::BOOLEAN AS trustabnisactive_icare,
                data_payload:SingleRemittancePerDay_icare::BOOLEAN AS singleremittanceperday_icare,
                data_payload:PreferredPaymentMethod_icare::NUMBER AS preferredpaymentmethod_icare,
                data_payload:FaxPhoneCountry::NUMBER AS faxphonecountry,
                CAST(data_payload:TaxID::TEXT AS VARCHAR(60)) AS taxid,
                CAST(data_payload:NameDenorm::TEXT AS VARCHAR(255)) AS namedenorm,
                TO_TIMESTAMP_TZ(data_payload:MedicareValidUntil_icare::NUMBER/1000) AS medicarevaliduntil_icare,
                data_payload:ApprovedPaymentMethod_icare::BOOLEAN AS approvedpaymentmethod_icare,
                data_payload:OrganisationType_icare::NUMBER AS organisationtype_icare,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                CAST(data_payload:AdjudicatorLicense::TEXT AS VARCHAR(30)) AS adjudicatorlicense,
                data_payload:ID::NUMBER AS id,
                data_payload:LawFirmSpecialty::NUMBER AS lawfirmspecialty,
                CAST(data_payload:LastNameDenorm::TEXT AS VARCHAR(80)) AS lastnamedenorm,
                CAST(data_payload:OktaID_icare::TEXT AS VARCHAR(20)) AS oktaid_icare,
                CAST(data_payload:LastName::TEXT AS VARCHAR(80)) AS lastname,
                data_payload:CreateUserID::NUMBER AS createuserid,
                CAST(data_payload:PayInfoUpdUserName_icare::TEXT AS VARCHAR(100)) AS payinfoupdusername_icare,
                CAST(data_payload:TradingName_icare::TEXT AS VARCHAR(100)) AS tradingname_icare,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:VenueType::NUMBER AS venuetype,
                CAST(data_payload:AutoTowingLicense::TEXT AS VARCHAR(30)) AS autotowinglicense,
                data_payload:BlockedVendor_icare::BOOLEAN AS blockedvendor_icare,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                CAST(data_payload:HomePhoneExtension::TEXT AS VARCHAR(60)) AS homephoneextension,
                CAST(data_payload:MedicareNumber_icare::TEXT AS VARCHAR(15)) AS medicarenumber_icare,
                data_payload:TrustRegisteredForGST_icare::BOOLEAN AS trustregisteredforgst_icare,
                data_payload:SpecialtyType::NUMBER AS specialtytype,
                CAST(data_payload:FirstName::TEXT AS VARCHAR(40)) AS firstname,
                CAST(data_payload:TrusteeName_icare::TEXT AS VARCHAR(256)) AS trusteename_icare,
                TO_TIMESTAMP_TZ(data_payload:W9ValidFrom::NUMBER/1000) AS w9validfrom,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                CAST(data_payload:Occupation::TEXT AS VARCHAR(100)) AS occupation,
                CAST(data_payload:CellPhone::TEXT AS VARCHAR(30)) AS cellphone,
                data_payload:HelpSslorTslDebt_icare::BOOLEAN AS helpsslortsldebt_icare,
                data_payload:PrimaryAddressID::NUMBER AS primaryaddressid,
                CAST(data_payload:TrustABN_icare::TEXT AS VARCHAR(60)) AS trustabn_icare,
                data_payload:Suffix::NUMBER AS suffix,
                CAST(data_payload:AddressBookUID::TEXT AS VARCHAR(64)) AS addressbookuid,
                data_payload:InterpreterRequired_icare::BOOLEAN AS interpreterrequired_icare,
                CAST(data_payload:Website_icare::TEXT AS VARCHAR(255)) AS website_icare,
                data_payload:ABNIsActive_icare::BOOLEAN AS abnisactive_icare,
                CAST(data_payload:EmailAddress1::TEXT AS VARCHAR(80)) AS emailaddress1,
                CAST(data_payload:EmailAddress2::TEXT AS VARCHAR(80)) AS emailaddress2,
                data_payload:PrimaryLanguage::NUMBER AS primarylanguage,
                data_payload:NumDependents::NUMBER AS numdependents,
                data_payload:TaxStatus::NUMBER AS taxstatus,
                CAST(data_payload:OtherLanguage_icare::TEXT AS VARCHAR(100)) AS otherlanguage_icare,
                CAST(data_payload:OffsetAmount_icare AS NUMBER(18,2)) AS offsetamount_icare,
                TO_TIMESTAMP_TZ(data_payload:TFNDeclarationDate_icare::NUMBER/1000) AS tfndeclarationdate_icare,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                CAST(data_payload:NameKanji::TEXT AS VARCHAR(255)) AS namekanji,
                CAST(data_payload:ABSLanguageDescription_icare::TEXT AS VARCHAR(80)) AS abslanguagedescription_icare,
                CAST(data_payload:FaxPhone::TEXT AS VARCHAR(30)) AS faxphone,
                data_payload:ABSLanguageCode_icare::NUMBER AS abslanguagecode_icare,
                CAST(data_payload:CellPhoneExtension::TEXT AS VARCHAR(60)) AS cellphoneextension,
                CAST(data_payload:EmployeeNumber::TEXT AS VARCHAR(255)) AS employeenumber,
                data_payload:DoctorSpecialty_icare::NUMBER AS doctorspecialty_icare,
                data_payload:Subtype::NUMBER AS subtype,
                TO_TIMESTAMP_TZ(data_payload:ABNValidated_icare::NUMBER/1000) AS abnvalidated_icare,
                CAST(data_payload:FormerName::TEXT AS VARCHAR(80)) AS formername,
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                data_payload:Preferred::BOOLEAN AS preferred,
                data_payload:ObfuscatedInternal::BOOLEAN AS obfuscatedinternal,
                data_payload:VendorType::NUMBER AS vendortype,
                data_payload:W9Received::BOOLEAN AS w9received,
                CAST(data_payload:SourceSystem_icare::TEXT AS VARCHAR(20)) AS sourcesystem_icare,
                CAST(data_payload:Particle::TEXT AS VARCHAR(40)) AS particle,
                CAST(data_payload:ACN_icare::TEXT AS VARCHAR(60)) AS acn_icare,
                CAST(data_payload:EmployeeSecurityID::TEXT AS VARCHAR(15)) AS employeesecurityid,
                CAST(data_payload:Name::TEXT AS VARCHAR(255)) AS name,
                CAST(data_payload:MedicalLicense::TEXT AS VARCHAR(30)) AS medicallicense,
                CAST(data_payload:VendorNumber::TEXT AS VARCHAR(60)) AS vendornumber,
                data_payload:PreferredCurrency::NUMBER AS preferredcurrency,
                data_payload:Score::NUMBER AS score,
                data_payload:DoNotDestroy::BOOLEAN AS donotdestroy,
                data_payload:Prefix::NUMBER AS prefix,
                data_payload:SSNReleaseAuthorized::BOOLEAN AS ssnreleaseauthorized,
                TO_TIMESTAMP_TZ(data_payload:W9ValidTo::NUMBER/1000) AS w9validto,
                CAST(data_payload:LastNameKanji::TEXT AS VARCHAR(80)) AS lastnamekanji,
                data_payload:AuResidentForTaxPurposes_icare::BOOLEAN AS auresidentfortaxpurposes_icare,
                data_payload:TaxFilingStatus::NUMBER AS taxfilingstatus,
                CAST(data_payload:GreenCardNumber::TEXT AS VARCHAR(15)) AS greencardnumber,
                CAST(data_payload:WithholdingRate AS NUMBER(4,1)) AS withholdingrate,
                TO_TIMESTAMP_TZ(data_payload:CommencementDate_icare::NUMBER/1000) AS commencementdate_icare,
                CAST(data_payload:TrustName_icare::TEXT AS VARCHAR(255)) AS trustname_icare,
                data_payload:LegalSpecialty_icare::NUMBER AS legalspecialty_icare,
                CAST(data_payload:MiddleName::TEXT AS VARCHAR(40)) AS middlename,
                CAST(data_payload:AttorneyLicense::TEXT AS VARCHAR(30)) AS attorneylicense,
                data_payload:EligibleOffset_icare::BOOLEAN AS eligibleoffset_icare,
                CAST(data_payload:ABN_icare::TEXT AS VARCHAR(60)) AS abn_icare,
                data_payload:Retired::NUMBER AS retired,
                CAST(data_payload:JurisdictionAssignedID::TEXT AS VARCHAR(15)) AS jurisdictionassignedid,
                data_payload:TaxExemptionsEntitled::NUMBER AS taxexemptionsentitled,
                data_payload:MedicalOrgSpecialty::NUMBER AS medicalorgspecialty,
                data_payload:ValidationLevel::NUMBER AS validationlevel,
                data_payload:PrimaryPhone::NUMBER AS primaryphone,
                data_payload:TrusteeType_icare::NUMBER AS trusteetype_icare,
                CAST(data_payload:TempCRMUniqueID_icare::TEXT AS VARCHAR(40)) AS tempcrmuniqueid_icare,
                TO_TIMESTAMP_TZ(data_payload:W9ReceivedDate::NUMBER/1000) AS w9receiveddate,
                CAST(data_payload:MedicareIRN_icare::TEXT AS VARCHAR(2)) AS medicareirn_icare,
                CAST(data_payload:CRMVersion_icare::TEXT AS VARCHAR(18)) AS crmversion_icare,
                CAST(data_payload:FirstNameDenorm::TEXT AS VARCHAR(40)) AS firstnamedenorm,
                data_payload:AdjudicativeDomain::NUMBER AS adjudicativedomain,
                CAST(data_payload:FirstNameKanji::TEXT AS VARCHAR(40)) AS firstnamekanji,
                CAST(data_payload:PolicySystemId::TEXT AS VARCHAR(256)) AS policysystemid,
                data_payload:DoctorSpecialty::NUMBER AS doctorspecialty,
                data_payload:SmsNotification_icare::BOOLEAN AS smsnotification_icare,
                data_payload:ClaimantIDType::NUMBER AS claimantidtype,
                CAST(data_payload:Notes::TEXT AS VARCHAR(16777216)) AS notes,
                data_payload:Gender::NUMBER AS gender,
                data_payload:NumDependentsU18::NUMBER AS numdependentsu18,
                CAST(data_payload:AutoRepairLicense::TEXT AS VARCHAR(30)) AS autorepairlicense,
                data_payload:HomePhoneCountry::NUMBER AS homephonecountry,
                data_payload:MedicalSpecialty_icare::NUMBER AS medicalspecialty_icare,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                data_payload:AutoSync::NUMBER AS autosync,
                data_payload:CellPhoneCountry::NUMBER AS cellphonecountry,
                CAST(data_payload:LicenseNumber::TEXT AS VARCHAR(20)) AS licensenumber,
                CAST(data_payload:VisaNumber::TEXT AS VARCHAR(15)) AS visanumber,
                data_payload:FinancialSupplementDebt_icare::BOOLEAN AS financialsupplementdebt_icare,
                TO_TIMESTAMP_TZ(data_payload:TrustABNValidated_icare::NUMBER/1000) AS trustabnvalidated_icare,
                data_payload:PendingLinkMessage::BOOLEAN AS pendinglinkmessage,
                data_payload:LoadRelatedContacts::BOOLEAN AS loadrelatedcontacts,
                data_payload:AggregateRemittance_icare::BOOLEAN AS aggregateremittance_icare,
                TO_TIMESTAMP_TZ(data_payload:DateOfBirth::NUMBER/1000) AS dateofbirth,
                data_payload:AttorneySpecialty_icare::NUMBER AS attorneyspecialty_icare,
                CAST(data_payload:PassportNumber::TEXT AS VARCHAR(15)) AS passportnumber,
                CAST(data_payload:EducationLevel::TEXT AS VARCHAR(2)) AS educationlevel,
                data_payload:RegisteredForGST_icare::BOOLEAN AS registeredforgst_icare,
                data_payload:PrimaryLocale::NUMBER AS primarylocale,
                data_payload:CommunicationPreferences_icare::NUMBER AS communicationpreferences_icare,
                data_payload:NumDependentsU25::NUMBER AS numdependentsu25,
                data_payload:AttorneySpecialty::NUMBER AS attorneyspecialty,
                CAST(data_payload:WorkPhoneExtension::TEXT AS VARCHAR(60)) AS workphoneextension,
                data_payload:MedicareLevyVariation_icare::BOOLEAN AS medicarelevyvariation_icare,
                data_payload:MaritalStatus::NUMBER AS maritalstatus,
                data_payload:ClaimTaxFreeThreshold_icare::BOOLEAN AS claimtaxfreethreshold_icare,
                data_payload:OccupationDetails_icareID::NUMBER AS occupationdetails_icareid,
                data_payload:OrganizationType::NUMBER AS organizationtype,
                CAST(data_payload:FaxPhoneExtension::TEXT AS VARCHAR(60)) AS faxphoneextension,
                CAST(data_payload:HomePhone::TEXT AS VARCHAR(30)) AS homephone,
                data_payload:LicenseState::NUMBER AS licensestate,
                data_payload:WorkPhoneCountry::NUMBER AS workphonecountry,
                CAST(data_payload:WorkPhone::TEXT AS VARCHAR(30)) AS workphone,
                data_payload:NoOfDepChild_icare::NUMBER AS noofdepchild_icare,
                data_payload:SnrPnsnrTaxOffsetStatus_icare::NUMBER AS snrpnsnrtaxoffsetstatus_icare,
                data_payload:MedicareLevyExempt_icare::BOOLEAN AS medicarelevyexempt_icare,
                data_payload:Spouse_icare::BOOLEAN AS spouse_icare,
                data_payload:SnrPensnrTaxOffset_icare::BOOLEAN AS snrpensnrtaxoffset_icare,
                data_payload:MedicareExemptStatus_icare::NUMBER AS medicareexemptstatus_icare,
                data_payload:WageRSA_icare::NUMBER AS wagersa_icare,
                CAST(data_payload:ManagingEntityCodes_icare::TEXT AS VARCHAR(1333)) AS managingentitycodes_icare,
                TO_TIMESTAMP_TZ(data_payload:EffectiveToVariation_icare::NUMBER/1000) AS effectivetovariation_icare,
                CAST(data_payload:UpwardVariationPercent_icare AS NUMBER(10,2)) AS upwardvariationpercent_icare,
                CAST(data_payload:DownwardVariationAmt_icare AS NUMBER(18,2)) AS downwardvariationamt_icare,
                TO_TIMESTAMP_TZ(data_payload:EffectiveFromVariation_icare::NUMBER/1000) AS effectivefromvariation_icare,
                CAST(data_payload:UpwardVariationAmt_icare AS NUMBER(18,2)) AS upwardvariationamt_icare,
                CAST(data_payload:DownwardVariationPercent_icare AS NUMBER(10,2)) AS downwardvariationpercent_icare,
                data_payload:WithholdingVariation_icare::BOOLEAN AS withholdingvariation_icare,
                CAST(data_payload:ProviderID_Ext::TEXT AS VARCHAR(40)) AS providerid_ext,
                data_payload:DPPlatform_Ext::NUMBER AS dpplatform_ext,
                CAST(data_payload:DuplicateCreateReason_Ext::TEXT AS VARCHAR(255)) AS duplicatecreatereason_ext,
                data_payload:ContactSecurityType_Ext::NUMBER AS contactsecuritytype_ext,
                data_payload:CellPhoneCountry_Ext::NUMBER AS cellphonecountry_ext,
                CAST(data_payload:OrganisationPartyID_Ext::TEXT AS VARCHAR(30)) AS organisationpartyid_ext,
                TO_TIMESTAMP_TZ(data_payload:CRMLastModifiedDate_Ext::NUMBER/1000) AS crmlastmodifieddate_ext,
                CAST(data_payload:CRMLastModifiedById_Ext::TEXT AS VARCHAR(80)) AS crmlastmodifiedbyid_ext,
                CAST(data_payload:Status_Ext::TEXT AS VARCHAR(30)) AS status_ext,
                CAST(data_payload:CellPhoneExtension_Ext::TEXT AS VARCHAR(60)) AS cellphoneextension_ext,
                TO_TIMESTAMP_TZ(data_payload:CRMCreatedDate_Ext::NUMBER/1000) AS crmcreateddate_ext,
                CAST(data_payload:RelatedCompanyName_Ext::TEXT AS VARCHAR(255)) AS relatedcompanyname_ext,
                TO_TIMESTAMP_TZ(data_payload:ABNValidationTimestamp_Ext::NUMBER/1000) AS abnvalidationtimestamp_ext,
                CAST(data_payload:CellPhone_Ext::TEXT AS VARCHAR(30)) AS cellphone_ext,
                CAST(data_payload:CRMLastModifiedByName_Ext::TEXT AS VARCHAR(255)) AS crmlastmodifiedbyname_ext,
                data_payload:ProviderCategory_Ext::NUMBER AS providercategory_ext,
                data_payload:ABNExempt_Ext::BOOLEAN AS abnexempt_ext,
                CAST(data_payload:CreationSource_Ext::TEXT AS VARCHAR(20)) AS creationsource_ext,
                data_payload:IsExactMatch_Ext::BOOLEAN AS isexactmatch_ext,
                CAST(data_payload:IsSubrogation_Ext::TEXT AS VARCHAR(30)) AS issubrogation_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwcc', 'cc_contact') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:trustabnisactive_icare::BOOLEAN AS trustabnisactive_icare,
                $1:singleremittanceperday_icare::BOOLEAN AS singleremittanceperday_icare,
                $1:preferredpaymentmethod_icare::NUMBER AS preferredpaymentmethod_icare,
                $1:faxphonecountry::NUMBER AS faxphonecountry,
                CAST($1:taxid::TEXT AS VARCHAR(60)) AS taxid,
                CAST($1:namedenorm::TEXT AS VARCHAR(255)) AS namedenorm,
                $1:medicarevaliduntil_icare::TIMESTAMP_TZ AS medicarevaliduntil_icare,
                $1:approvedpaymentmethod_icare::BOOLEAN AS approvedpaymentmethod_icare,
                $1:organisationtype_icare::NUMBER AS organisationtype_icare,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                CAST($1:adjudicatorlicense::TEXT AS VARCHAR(30)) AS adjudicatorlicense,
                $1:id::NUMBER AS id,
                $1:lawfirmspecialty::NUMBER AS lawfirmspecialty,
                CAST($1:lastnamedenorm::TEXT AS VARCHAR(80)) AS lastnamedenorm,
                CAST($1:oktaid_icare::TEXT AS VARCHAR(20)) AS oktaid_icare,
                CAST($1:lastname::TEXT AS VARCHAR(80)) AS lastname,
                $1:createuserid::NUMBER AS createuserid,
                CAST($1:payinfoupdusername_icare::TEXT AS VARCHAR(100)) AS payinfoupdusername_icare,
                CAST($1:tradingname_icare::TEXT AS VARCHAR(100)) AS tradingname_icare,
                $1:beanversion::NUMBER AS beanversion,
                $1:venuetype::NUMBER AS venuetype,
                CAST($1:autotowinglicense::TEXT AS VARCHAR(30)) AS autotowinglicense,
                $1:blockedvendor_icare::BOOLEAN AS blockedvendor_icare,
                $1:updateuserid::NUMBER AS updateuserid,
                CAST($1:homephoneextension::TEXT AS VARCHAR(60)) AS homephoneextension,
                CAST($1:medicarenumber_icare::TEXT AS VARCHAR(15)) AS medicarenumber_icare,
                $1:trustregisteredforgst_icare::BOOLEAN AS trustregisteredforgst_icare,
                $1:specialtytype::NUMBER AS specialtytype,
                CAST($1:firstname::TEXT AS VARCHAR(40)) AS firstname,
                CAST($1:trusteename_icare::TEXT AS VARCHAR(256)) AS trusteename_icare,
                $1:w9validfrom::TIMESTAMP_TZ AS w9validfrom,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                CAST($1:occupation::TEXT AS VARCHAR(100)) AS occupation,
                CAST($1:cellphone::TEXT AS VARCHAR(30)) AS cellphone,
                $1:helpsslortsldebt_icare::BOOLEAN AS helpsslortsldebt_icare,
                $1:primaryaddressid::NUMBER AS primaryaddressid,
                CAST($1:trustabn_icare::TEXT AS VARCHAR(60)) AS trustabn_icare,
                $1:suffix::NUMBER AS suffix,
                CAST($1:addressbookuid::TEXT AS VARCHAR(64)) AS addressbookuid,
                $1:interpreterrequired_icare::BOOLEAN AS interpreterrequired_icare,
                CAST($1:website_icare::TEXT AS VARCHAR(255)) AS website_icare,
                $1:abnisactive_icare::BOOLEAN AS abnisactive_icare,
                CAST($1:emailaddress1::TEXT AS VARCHAR(80)) AS emailaddress1,
                CAST($1:emailaddress2::TEXT AS VARCHAR(80)) AS emailaddress2,
                $1:primarylanguage::NUMBER AS primarylanguage,
                $1:numdependents::NUMBER AS numdependents,
                $1:taxstatus::NUMBER AS taxstatus,
                CAST($1:otherlanguage_icare::TEXT AS VARCHAR(100)) AS otherlanguage_icare,
                CAST($1:offsetamount_icare AS NUMBER(18,2)) AS offsetamount_icare,
                $1:tfndeclarationdate_icare::TIMESTAMP_TZ AS tfndeclarationdate_icare,
                $1:archivepartition::NUMBER AS archivepartition,
                CAST($1:namekanji::TEXT AS VARCHAR(255)) AS namekanji,
                CAST($1:abslanguagedescription_icare::TEXT AS VARCHAR(80)) AS abslanguagedescription_icare,
                CAST($1:faxphone::TEXT AS VARCHAR(30)) AS faxphone,
                $1:abslanguagecode_icare::NUMBER AS abslanguagecode_icare,
                CAST($1:cellphoneextension::TEXT AS VARCHAR(60)) AS cellphoneextension,
                CAST($1:employeenumber::TEXT AS VARCHAR(255)) AS employeenumber,
                $1:doctorspecialty_icare::NUMBER AS doctorspecialty_icare,
                $1:subtype::NUMBER AS subtype,
                $1:abnvalidated_icare::TIMESTAMP_TZ AS abnvalidated_icare,
                CAST($1:formername::TEXT AS VARCHAR(80)) AS formername,
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:preferred::BOOLEAN AS preferred,
                $1:obfuscatedinternal::BOOLEAN AS obfuscatedinternal,
                $1:vendortype::NUMBER AS vendortype,
                $1:w9received::BOOLEAN AS w9received,
                CAST($1:sourcesystem_icare::TEXT AS VARCHAR(20)) AS sourcesystem_icare,
                CAST($1:particle::TEXT AS VARCHAR(40)) AS particle,
                CAST($1:acn_icare::TEXT AS VARCHAR(60)) AS acn_icare,
                CAST($1:employeesecurityid::TEXT AS VARCHAR(15)) AS employeesecurityid,
                CAST($1:name::TEXT AS VARCHAR(255)) AS name,
                CAST($1:medicallicense::TEXT AS VARCHAR(30)) AS medicallicense,
                CAST($1:vendornumber::TEXT AS VARCHAR(60)) AS vendornumber,
                $1:preferredcurrency::NUMBER AS preferredcurrency,
                $1:score::NUMBER AS score,
                $1:donotdestroy::BOOLEAN AS donotdestroy,
                $1:prefix::NUMBER AS prefix,
                $1:ssnreleaseauthorized::BOOLEAN AS ssnreleaseauthorized,
                $1:w9validto::TIMESTAMP_TZ AS w9validto,
                CAST($1:lastnamekanji::TEXT AS VARCHAR(80)) AS lastnamekanji,
                $1:auresidentfortaxpurposes_icare::BOOLEAN AS auresidentfortaxpurposes_icare,
                $1:taxfilingstatus::NUMBER AS taxfilingstatus,
                CAST($1:greencardnumber::TEXT AS VARCHAR(15)) AS greencardnumber,
                CAST($1:withholdingrate AS NUMBER(4,1)) AS withholdingrate,
                $1:commencementdate_icare::TIMESTAMP_TZ AS commencementdate_icare,
                CAST($1:trustname_icare::TEXT AS VARCHAR(255)) AS trustname_icare,
                $1:legalspecialty_icare::NUMBER AS legalspecialty_icare,
                CAST($1:middlename::TEXT AS VARCHAR(40)) AS middlename,
                CAST($1:attorneylicense::TEXT AS VARCHAR(30)) AS attorneylicense,
                $1:eligibleoffset_icare::BOOLEAN AS eligibleoffset_icare,
                CAST($1:abn_icare::TEXT AS VARCHAR(60)) AS abn_icare,
                $1:retired::NUMBER AS retired,
                CAST($1:jurisdictionassignedid::TEXT AS VARCHAR(15)) AS jurisdictionassignedid,
                $1:taxexemptionsentitled::NUMBER AS taxexemptionsentitled,
                $1:medicalorgspecialty::NUMBER AS medicalorgspecialty,
                $1:validationlevel::NUMBER AS validationlevel,
                $1:primaryphone::NUMBER AS primaryphone,
                $1:trusteetype_icare::NUMBER AS trusteetype_icare,
                CAST($1:tempcrmuniqueid_icare::TEXT AS VARCHAR(40)) AS tempcrmuniqueid_icare,
                $1:w9receiveddate::TIMESTAMP_TZ AS w9receiveddate,
                CAST($1:medicareirn_icare::TEXT AS VARCHAR(2)) AS medicareirn_icare,
                CAST($1:crmversion_icare::TEXT AS VARCHAR(18)) AS crmversion_icare,
                CAST($1:firstnamedenorm::TEXT AS VARCHAR(40)) AS firstnamedenorm,
                $1:adjudicativedomain::NUMBER AS adjudicativedomain,
                CAST($1:firstnamekanji::TEXT AS VARCHAR(40)) AS firstnamekanji,
                CAST($1:policysystemid::TEXT AS VARCHAR(256)) AS policysystemid,
                $1:doctorspecialty::NUMBER AS doctorspecialty,
                $1:smsnotification_icare::BOOLEAN AS smsnotification_icare,
                $1:claimantidtype::NUMBER AS claimantidtype,
                CAST($1:notes::TEXT AS VARCHAR(16777216)) AS notes,
                $1:gender::NUMBER AS gender,
                $1:numdependentsu18::NUMBER AS numdependentsu18,
                CAST($1:autorepairlicense::TEXT AS VARCHAR(30)) AS autorepairlicense,
                $1:homephonecountry::NUMBER AS homephonecountry,
                $1:medicalspecialty_icare::NUMBER AS medicalspecialty_icare,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:autosync::NUMBER AS autosync,
                $1:cellphonecountry::NUMBER AS cellphonecountry,
                CAST($1:licensenumber::TEXT AS VARCHAR(20)) AS licensenumber,
                CAST($1:visanumber::TEXT AS VARCHAR(15)) AS visanumber,
                $1:financialsupplementdebt_icare::BOOLEAN AS financialsupplementdebt_icare,
                $1:trustabnvalidated_icare::TIMESTAMP_TZ AS trustabnvalidated_icare,
                $1:pendinglinkmessage::BOOLEAN AS pendinglinkmessage,
                $1:loadrelatedcontacts::BOOLEAN AS loadrelatedcontacts,
                $1:aggregateremittance_icare::BOOLEAN AS aggregateremittance_icare,
                $1:dateofbirth::TIMESTAMP_TZ AS dateofbirth,
                $1:attorneyspecialty_icare::NUMBER AS attorneyspecialty_icare,
                CAST($1:passportnumber::TEXT AS VARCHAR(15)) AS passportnumber,
                CAST($1:educationlevel::TEXT AS VARCHAR(2)) AS educationlevel,
                $1:registeredforgst_icare::BOOLEAN AS registeredforgst_icare,
                $1:primarylocale::NUMBER AS primarylocale,
                $1:communicationpreferences_icare::NUMBER AS communicationpreferences_icare,
                $1:numdependentsu25::NUMBER AS numdependentsu25,
                $1:attorneyspecialty::NUMBER AS attorneyspecialty,
                CAST($1:workphoneextension::TEXT AS VARCHAR(60)) AS workphoneextension,
                $1:medicarelevyvariation_icare::BOOLEAN AS medicarelevyvariation_icare,
                $1:maritalstatus::NUMBER AS maritalstatus,
                $1:claimtaxfreethreshold_icare::BOOLEAN AS claimtaxfreethreshold_icare,
                $1:occupationdetails_icareid::NUMBER AS occupationdetails_icareid,
                $1:organizationtype::NUMBER AS organizationtype,
                CAST($1:faxphoneextension::TEXT AS VARCHAR(60)) AS faxphoneextension,
                CAST($1:homephone::TEXT AS VARCHAR(30)) AS homephone,
                $1:licensestate::NUMBER AS licensestate,
                $1:workphonecountry::NUMBER AS workphonecountry,
                CAST($1:workphone::TEXT AS VARCHAR(30)) AS workphone,
                $1:noofdepchild_icare::NUMBER AS noofdepchild_icare,
                $1:snrpnsnrtaxoffsetstatus_icare::NUMBER AS snrpnsnrtaxoffsetstatus_icare,
                $1:medicarelevyexempt_icare::BOOLEAN AS medicarelevyexempt_icare,
                $1:spouse_icare::BOOLEAN AS spouse_icare,
                $1:snrpensnrtaxoffset_icare::BOOLEAN AS snrpensnrtaxoffset_icare,
                $1:medicareexemptstatus_icare::NUMBER AS medicareexemptstatus_icare,
                $1:wagersa_icare::NUMBER AS wagersa_icare,
                CAST($1:managingentitycodes_icare::TEXT AS VARCHAR(1333)) AS managingentitycodes_icare,
                $1:effectivetovariation_icare::TIMESTAMP_TZ AS effectivetovariation_icare,
                CAST($1:upwardvariationpercent_icare AS NUMBER(10,2)) AS upwardvariationpercent_icare,
                CAST($1:downwardvariationamt_icare AS NUMBER(18,2)) AS downwardvariationamt_icare,
                $1:effectivefromvariation_icare::TIMESTAMP_TZ AS effectivefromvariation_icare,
                CAST($1:upwardvariationamt_icare AS NUMBER(18,2)) AS upwardvariationamt_icare,
                CAST($1:downwardvariationpercent_icare AS NUMBER(10,2)) AS downwardvariationpercent_icare,
                $1:withholdingvariation_icare::BOOLEAN AS withholdingvariation_icare,
                CAST($1:providerid_ext::TEXT AS VARCHAR(40)) AS providerid_ext,
                $1:dpplatform_ext::NUMBER AS dpplatform_ext,
                CAST($1:duplicatecreatereason_ext::TEXT AS VARCHAR(255)) AS duplicatecreatereason_ext,
                $1:contactsecuritytype_ext::NUMBER AS contactsecuritytype_ext,
                $1:cellphonecountry_ext::NUMBER AS cellphonecountry_ext,
                CAST($1:organisationpartyid_ext::TEXT AS VARCHAR(30)) AS organisationpartyid_ext,
                $1:crmlastmodifieddate_ext::TIMESTAMP_TZ AS crmlastmodifieddate_ext,
                CAST($1:crmlastmodifiedbyid_ext::TEXT AS VARCHAR(80)) AS crmlastmodifiedbyid_ext,
                CAST($1:status_ext::TEXT AS VARCHAR(30)) AS status_ext,
                CAST($1:cellphoneextension_ext::TEXT AS VARCHAR(60)) AS cellphoneextension_ext,
                $1:crmcreateddate_ext::TIMESTAMP_TZ AS crmcreateddate_ext,
                CAST($1:relatedcompanyname_ext::TEXT AS VARCHAR(255)) AS relatedcompanyname_ext,
                $1:abnvalidationtimestamp_ext::TIMESTAMP_TZ AS abnvalidationtimestamp_ext,
                CAST($1:cellphone_ext::TEXT AS VARCHAR(30)) AS cellphone_ext,
                CAST($1:crmlastmodifiedbyname_ext::TEXT AS VARCHAR(255)) AS crmlastmodifiedbyname_ext,
                $1:providercategory_ext::NUMBER AS providercategory_ext,
                $1:abnexempt_ext::BOOLEAN AS abnexempt_ext,
                CAST($1:creationsource_ext::TEXT AS VARCHAR(20)) AS creationsource_ext,
                $1:isexactmatch_ext::BOOLEAN AS isexactmatch_ext,
                CAST($1:issubrogation_ext::TEXT AS VARCHAR(30)) AS issubrogation_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwcc', 'cc_contact') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS contact_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'trustabnisactive_icare',
                        'singleremittanceperday_icare',
                        'preferredpaymentmethod_icare',
                        'faxphonecountry',
                        'taxid',
                        'namedenorm',
                        'medicarevaliduntil_icare',
                        'approvedpaymentmethod_icare',
                        'organisationtype_icare',
                        'updatetime',
                        'adjudicatorlicense',
                        'lawfirmspecialty',
                        'lastnamedenorm',
                        'oktaid_icare',
                        'lastname',
                        'createuserid',
                        'payinfoupdusername_icare',
                        'tradingname_icare',
                        'beanversion',
                        'venuetype',
                        'autotowinglicense',
                        'blockedvendor_icare',
                        'updateuserid',
                        'homephoneextension',
                        'medicarenumber_icare',
                        'trustregisteredforgst_icare',
                        'specialtytype',
                        'firstname',
                        'trusteename_icare',
                        'w9validfrom',
                        'publicid',
                        'occupation',
                        'cellphone',
                        'helpsslortsldebt_icare',
                        'primaryaddressid',
                        'trustabn_icare',
                        'suffix',
                        'addressbookuid',
                        'interpreterrequired_icare',
                        'website_icare',
                        'abnisactive_icare',
                        'emailaddress1',
                        'emailaddress2',
                        'primarylanguage',
                        'numdependents',
                        'taxstatus',
                        'otherlanguage_icare',
                        'offsetamount_icare',
                        'tfndeclarationdate_icare',
                        'archivepartition',
                        'namekanji',
                        'abslanguagedescription_icare',
                        'faxphone',
                        'abslanguagecode_icare',
                        'cellphoneextension',
                        'employeenumber',
                        'doctorspecialty_icare',
                        'subtype',
                        'abnvalidated_icare',
                        'formername',
                        'loadcommandid',
                        'preferred',
                        'obfuscatedinternal',
                        'vendortype',
                        'w9received',
                        'sourcesystem_icare',
                        'particle',
                        'acn_icare',
                        'employeesecurityid',
                        'name',
                        'medicallicense',
                        'vendornumber',
                        'preferredcurrency',
                        'score',
                        'donotdestroy',
                        'prefix',
                        'ssnreleaseauthorized',
                        'w9validto',
                        'lastnamekanji',
                        'auresidentfortaxpurposes_icare',
                        'taxfilingstatus',
                        'greencardnumber',
                        'withholdingrate',
                        'commencementdate_icare',
                        'trustname_icare',
                        'legalspecialty_icare',
                        'middlename',
                        'attorneylicense',
                        'eligibleoffset_icare',
                        'abn_icare',
                        'retired',
                        'jurisdictionassignedid',
                        'taxexemptionsentitled',
                        'medicalorgspecialty',
                        'validationlevel',
                        'primaryphone',
                        'trusteetype_icare',
                        'tempcrmuniqueid_icare',
                        'w9receiveddate',
                        'medicareirn_icare',
                        'crmversion_icare',
                        'firstnamedenorm',
                        'adjudicativedomain',
                        'firstnamekanji',
                        'policysystemid',
                        'doctorspecialty',
                        'smsnotification_icare',
                        'claimantidtype',
                        'notes',
                        'gender',
                        'numdependentsu18',
                        'autorepairlicense',
                        'homephonecountry',
                        'medicalspecialty_icare',
                        'createtime',
                        'autosync',
                        'cellphonecountry',
                        'licensenumber',
                        'visanumber',
                        'financialsupplementdebt_icare',
                        'trustabnvalidated_icare',
                        'pendinglinkmessage',
                        'loadrelatedcontacts',
                        'aggregateremittance_icare',
                        'dateofbirth',
                        'attorneyspecialty_icare',
                        'passportnumber',
                        'educationlevel',
                        'registeredforgst_icare',
                        'primarylocale',
                        'communicationpreferences_icare',
                        'numdependentsu25',
                        'attorneyspecialty',
                        'workphoneextension',
                        'medicarelevyvariation_icare',
                        'maritalstatus',
                        'claimtaxfreethreshold_icare',
                        'occupationdetails_icareid',
                        'organizationtype',
                        'faxphoneextension',
                        'homephone',
                        'licensestate',
                        'workphonecountry',
                        'workphone',
                        'noofdepchild_icare',
                        'snrpnsnrtaxoffsetstatus_icare',
                        'medicarelevyexempt_icare',
                        'spouse_icare',
                        'snrpensnrtaxoffset_icare',
                        'medicareexemptstatus_icare',
                        'wagersa_icare',
                        'managingentitycodes_icare',
                        'effectivetovariation_icare',
                        'upwardvariationpercent_icare',
                        'downwardvariationamt_icare',
                        'effectivefromvariation_icare',
                        'upwardvariationamt_icare',
                        'downwardvariationpercent_icare',
                        'withholdingvariation_icare',
                        'providerid_ext',
                        'dpplatform_ext',
                        'duplicatecreatereason_ext',
                        'contactsecuritytype_ext',
                        'cellphonecountry_ext',
                        'organisationpartyid_ext',
                        'crmlastmodifieddate_ext',
                        'crmlastmodifiedbyid_ext',
                        'status_ext',
                        'cellphoneextension_ext',
                        'crmcreateddate_ext',
                        'relatedcompanyname_ext',
                        'abnvalidationtimestamp_ext',
                        'cellphone_ext',
                        'crmlastmodifiedbyname_ext',
                        'providercategory_ext',
                        'abnexempt_ext',
                        'creationsource_ext',
                        'isexactmatch_ext',
                        'issubrogation_ext'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) as record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}