{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for cc_check.
                                                check_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["raw_layer", "raw_claim_centre", "claim_centre", "business_critical", "cc_check"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                data_payload:OCR_Invoice_icare::NUMBER AS ocr_invoice_icare,
                TO_TIMESTAMP_TZ(data_payload:IssueDate::NUMBER/1000) AS issuedate,
                TO_TIMESTAMP_TZ(data_payload:DateOfService::NUMBER/1000) AS dateofservice,
                TO_TIMESTAMP_TZ(data_payload:LastPostingDate_icare::NUMBER/1000) AS lastpostingdate_icare,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:IsPrimary::BOOLEAN AS isprimary,
                TO_TIMESTAMP_TZ(data_payload:ServicePdStart::NUMBER/1000) AS servicepdstart,
                data_payload:ID::NUMBER AS id,
                data_payload:PendEscalationForBulk::BOOLEAN AS pendescalationforbulk,
                data_payload:DeductionType::NUMBER AS deductiontype,
                CAST(data_payload:PayToDenorm::TEXT AS VARCHAR(255)) AS paytodenorm,
                data_payload:CreateUserID::NUMBER AS createuserid,
                CAST(data_payload:PayTo::TEXT AS VARCHAR(255)) AS payto,
                data_payload:MailingAddressID::NUMBER AS mailingaddressid,
                CAST(data_payload:BankBranchName_icare::TEXT AS VARCHAR(255)) AS bankbranchname_icare,
                data_payload:RecurringCheckID::NUMBER AS recurringcheckid,
                TO_TIMESTAMP_TZ(data_payload:DatePresented_icare::NUMBER/1000) AS datepresented_icare,
                data_payload:BeanVersion::NUMBER AS beanversion,
                CAST(data_payload:ABN_icare::TEXT AS VARCHAR(50)) AS abn_icare,
                data_payload:CommMethod_icare::NUMBER AS commmethod_icare,
                data_payload:Retired::NUMBER AS retired,
                data_payload:BankAccountType::NUMBER AS bankaccounttype,
                data_payload:Recurrence_icare::NUMBER AS recurrence_icare,
                data_payload:CheckInstructions::NUMBER AS checkinstructions,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                CAST(data_payload:DbNetAmount_icare AS NUMBER(10,2)) AS dbnetamount_icare,
                CAST(data_payload:InvoiceNumber::TEXT AS VARCHAR(255)) AS invoicenumber,
                data_payload:BulkInvoiceItemInfoID::NUMBER AS bulkinvoiceiteminfoid,
                CAST(data_payload:AccountName::TEXT AS VARCHAR(100)) AS accountname,
                CAST(data_payload:ForeignCurrencyAmount_icare AS NUMBER(10,2)) AS foreigncurrencyamount_icare,
                data_payload:PayeeWithNoABN_icare::BOOLEAN AS payeewithnoabn_icare,
                CAST(data_payload:Memo::TEXT AS VARCHAR(255)) AS memo,
                data_payload:IsTotalGT82_icare::BOOLEAN AS istotalgt82_icare,
                CAST(data_payload:BankSwiftCode_icare::TEXT AS VARCHAR(20)) AS bankswiftcode_icare,
                data_payload:PortionID::NUMBER AS portionid,
                data_payload:CheckType::NUMBER AS checktype,
                CAST(data_payload:MailToAddress::TEXT AS VARCHAR(255)) AS mailtoaddress,
                CAST(data_payload:TransactionIdentifier_icare::TEXT AS VARCHAR(50)) AS transactionidentifier_icare,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                TO_TIMESTAMP_TZ(data_payload:EnteredTime::NUMBER/1000) AS enteredtime,
                CAST(data_payload:BankName::TEXT AS VARCHAR(100)) AS bankname,
                data_payload:WeeklyBenefitPayeeType_icare::NUMBER AS weeklybenefitpayeetype_icare,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                CAST(data_payload:DeductionIdentifier_icare::TEXT AS VARCHAR(50)) AS deductionidentifier_icare,
                CAST(data_payload:CheckNumber::TEXT AS VARCHAR(255)) AS checknumber,
                TO_TIMESTAMP_TZ(data_payload:ServicePdEnd::NUMBER/1000) AS servicepdend,
                CAST(data_payload:BankRoutingNumber::TEXT AS VARCHAR(20)) AS bankroutingnumber,
                CAST(data_payload:EmailAddress_icare::TEXT AS VARCHAR(60)) AS emailaddress_icare,
                data_payload:ServicesProvidedOverseas_icare::BOOLEAN AS servicesprovidedoverseas_icare,
                data_payload:CurrencyTransacted_icare::NUMBER AS currencytransacted_icare,
                data_payload:DeliveryMethod::NUMBER AS deliverymethod,
                CAST(data_payload:OriginalMigratedStatus_icare::TEXT AS VARCHAR(255)) AS originalmigratedstatus_icare,
                data_payload:ClaimID::NUMBER AS claimid,
                data_payload:AggregateRemittance_icare::BOOLEAN AS aggregateremittance_icare,
                CAST(data_payload:WestpacID_icare::TEXT AS VARCHAR(255)) AS westpacid_icare,
                data_payload:GroupID::NUMBER AS groupid,
                data_payload:RegisteredForGST_icare::BOOLEAN AS registeredforgst_icare,
                TO_TIMESTAMP_TZ(data_payload:DatePaymentTransacted_icare::NUMBER/1000) AS datepaymenttransacted_icare,
                data_payload:Accrued_icare::BOOLEAN AS accrued_icare,
                TO_TIMESTAMP_TZ(data_payload:ScheduledSendDate::NUMBER/1000) AS scheduledsenddate,
                data_payload:IsInvoiceIssuedTo_icare::NUMBER AS isinvoiceissuedto_icare,
                data_payload:PreviousCheckType_icare::NUMBER AS previouschecktype_icare,
                CAST(data_payload:ReportableAmount AS NUMBER(18,2)) AS reportableamount,
                data_payload:PaymentMethod::NUMBER AS paymentmethod,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                data_payload:GSTMethodPEL_Ext::NUMBER AS gstmethodpel_ext,
                data_payload:CheckBatching::NUMBER AS checkbatching,
                data_payload:BankAccount::NUMBER AS bankaccount,
                CAST(data_payload:MailTo::TEXT AS VARCHAR(255)) AS mailto,
                data_payload:Status::NUMBER AS status,
                CAST(data_payload:Comments::TEXT AS VARCHAR(255)) AS comments,
                data_payload:CheckSetID::NUMBER AS checksetid,
                data_payload:Reportability::NUMBER AS reportability,
                CAST(data_payload:VoidedPaymentNumber_icare::TEXT AS VARCHAR(255)) AS voidedpaymentnumber_icare,
                CAST(data_payload:BankAccountNumber::TEXT AS VARCHAR(20)) AS bankaccountnumber,
                data_payload:PrePostPAYG_icare::NUMBER AS prepostpayg_icare,
                data_payload:GSTPaymentClassPEL_Ext::NUMBER AS gstpaymentclasspel_ext,
                data_payload:ClaimContactID::NUMBER AS claimcontactid,
                CAST(data_payload:PaymentSource_icare::TEXT AS VARCHAR(5)) AS paymentsource_icare,
                data_payload:COLPAYGWithholdVariation_icare::BOOLEAN AS colpaygwithholdvariation_icare,
                data_payload:PAYGWithholdVariation_icare::BOOLEAN AS paygwithholdvariation_icare,
                TO_TIMESTAMP_TZ(data_payload:CAMTVoidDate_icare::NUMBER/1000) AS camtvoiddate_icare,
                CAST(data_payload:RejectionReason_Ext::TEXT AS VARCHAR(255)) AS rejectionreason_ext,
                data_payload:IsMspPayment_Ext::BOOLEAN AS ismsppayment_ext,
                data_payload:OverrideAutoWageCalc_Ext::BOOLEAN AS overrideautowagecalc_ext,
                data_payload:RecalculateDeductions_Ext::BOOLEAN AS recalculatedeductions_ext,
                TO_TIMESTAMP_TZ(data_payload:LegacyUpdateTime_Ext::NUMBER/1000) AS legacyupdatetime_ext,
                data_payload:IsMigrated_Ext::BOOLEAN AS ismigrated_ext,
                TO_TIMESTAMP_TZ(data_payload:LegacyCreateTime_Ext::NUMBER/1000) AS legacycreatetime_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwcc', 'cc_check') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:ocr_invoice_icare::NUMBER AS ocr_invoice_icare,
                $1:issuedate::TIMESTAMP_TZ AS issuedate,
                $1:dateofservice::TIMESTAMP_TZ AS dateofservice,
                $1:lastpostingdate_icare::TIMESTAMP_TZ AS lastpostingdate_icare,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:isprimary::BOOLEAN AS isprimary,
                $1:servicepdstart::TIMESTAMP_TZ AS servicepdstart,
                $1:id::NUMBER AS id,
                $1:pendescalationforbulk::BOOLEAN AS pendescalationforbulk,
                $1:deductiontype::NUMBER AS deductiontype,
                CAST($1:paytodenorm::TEXT AS VARCHAR(255)) AS paytodenorm,
                $1:createuserid::NUMBER AS createuserid,
                CAST($1:payto::TEXT AS VARCHAR(255)) AS payto,
                $1:mailingaddressid::NUMBER AS mailingaddressid,
                CAST($1:bankbranchname_icare::TEXT AS VARCHAR(255)) AS bankbranchname_icare,
                $1:recurringcheckid::NUMBER AS recurringcheckid,
                $1:datepresented_icare::TIMESTAMP_TZ AS datepresented_icare,
                $1:beanversion::NUMBER AS beanversion,
                CAST($1:abn_icare::TEXT AS VARCHAR(50)) AS abn_icare,
                $1:commmethod_icare::NUMBER AS commmethod_icare,
                $1:retired::NUMBER AS retired,
                $1:bankaccounttype::NUMBER AS bankaccounttype,
                $1:recurrence_icare::NUMBER AS recurrence_icare,
                $1:checkinstructions::NUMBER AS checkinstructions,
                $1:updateuserid::NUMBER AS updateuserid,
                CAST($1:dbnetamount_icare AS NUMBER(10,2)) AS dbnetamount_icare,
                CAST($1:invoicenumber::TEXT AS VARCHAR(255)) AS invoicenumber,
                $1:bulkinvoiceiteminfoid::NUMBER AS bulkinvoiceiteminfoid,
                CAST($1:accountname::TEXT AS VARCHAR(100)) AS accountname,
                CAST($1:foreigncurrencyamount_icare AS NUMBER(10,2)) AS foreigncurrencyamount_icare,
                $1:payeewithnoabn_icare::BOOLEAN AS payeewithnoabn_icare,
                CAST($1:memo::TEXT AS VARCHAR(255)) AS memo,
                $1:istotalgt82_icare::BOOLEAN AS istotalgt82_icare,
                CAST($1:bankswiftcode_icare::TEXT AS VARCHAR(20)) AS bankswiftcode_icare,
                $1:portionid::NUMBER AS portionid,
                $1:checktype::NUMBER AS checktype,
                CAST($1:mailtoaddress::TEXT AS VARCHAR(255)) AS mailtoaddress,
                CAST($1:transactionidentifier_icare::TEXT AS VARCHAR(50)) AS transactionidentifier_icare,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:enteredtime::TIMESTAMP_TZ AS enteredtime,
                CAST($1:bankname::TEXT AS VARCHAR(100)) AS bankname,
                $1:weeklybenefitpayeetype_icare::NUMBER AS weeklybenefitpayeetype_icare,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                CAST($1:deductionidentifier_icare::TEXT AS VARCHAR(50)) AS deductionidentifier_icare,
                CAST($1:checknumber::TEXT AS VARCHAR(255)) AS checknumber,
                $1:servicepdend::TIMESTAMP_TZ AS servicepdend,
                CAST($1:bankroutingnumber::TEXT AS VARCHAR(20)) AS bankroutingnumber,
                CAST($1:emailaddress_icare::TEXT AS VARCHAR(60)) AS emailaddress_icare,
                $1:servicesprovidedoverseas_icare::BOOLEAN AS servicesprovidedoverseas_icare,
                $1:currencytransacted_icare::NUMBER AS currencytransacted_icare,
                $1:deliverymethod::NUMBER AS deliverymethod,
                CAST($1:originalmigratedstatus_icare::TEXT AS VARCHAR(255)) AS originalmigratedstatus_icare,
                $1:claimid::NUMBER AS claimid,
                $1:aggregateremittance_icare::BOOLEAN AS aggregateremittance_icare,
                CAST($1:westpacid_icare::TEXT AS VARCHAR(255)) AS westpacid_icare,
                $1:groupid::NUMBER AS groupid,
                $1:registeredforgst_icare::BOOLEAN AS registeredforgst_icare,
                $1:datepaymenttransacted_icare::TIMESTAMP_TZ AS datepaymenttransacted_icare,
                $1:accrued_icare::BOOLEAN AS accrued_icare,
                $1:scheduledsenddate::TIMESTAMP_TZ AS scheduledsenddate,
                $1:isinvoiceissuedto_icare::NUMBER AS isinvoiceissuedto_icare,
                $1:previouschecktype_icare::NUMBER AS previouschecktype_icare,
                CAST($1:reportableamount AS NUMBER(18,2)) AS reportableamount,
                $1:paymentmethod::NUMBER AS paymentmethod,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:gstmethodpel_ext::NUMBER AS gstmethodpel_ext,
                $1:checkbatching::NUMBER AS checkbatching,
                $1:bankaccount::NUMBER AS bankaccount,
                CAST($1:mailto::TEXT AS VARCHAR(255)) AS mailto,
                $1:status::NUMBER AS status,
                CAST($1:comments::TEXT AS VARCHAR(255)) AS comments,
                $1:checksetid::NUMBER AS checksetid,
                $1:reportability::NUMBER AS reportability,
                CAST($1:voidedpaymentnumber_icare::TEXT AS VARCHAR(255)) AS voidedpaymentnumber_icare,
                CAST($1:bankaccountnumber::TEXT AS VARCHAR(20)) AS bankaccountnumber,
                $1:prepostpayg_icare::NUMBER AS prepostpayg_icare,
                $1:gstpaymentclasspel_ext::NUMBER AS gstpaymentclasspel_ext,
                $1:claimcontactid::NUMBER AS claimcontactid,
                CAST($1:paymentsource_icare::TEXT AS VARCHAR(5)) AS paymentsource_icare,
                $1:colpaygwithholdvariation_icare::BOOLEAN AS colpaygwithholdvariation_icare,
                $1:paygwithholdvariation_icare::BOOLEAN AS paygwithholdvariation_icare,
                $1:camtvoiddate_icare::TIMESTAMP_TZ AS camtvoiddate_icare,
                CAST($1:rejectionreason_ext::TEXT AS VARCHAR(255)) AS rejectionreason_ext,
                $1:ismsppayment_ext::BOOLEAN AS ismsppayment_ext,
                $1:overrideautowagecalc_ext::BOOLEAN AS overrideautowagecalc_ext,
                $1:recalculatedeductions_ext::BOOLEAN AS recalculatedeductions_ext,
                $1:legacyupdatetime_ext::TIMESTAMP_TZ AS legacyupdatetime_ext,
                $1:ismigrated_ext::BOOLEAN AS ismigrated_ext,
                $1:legacycreatetime_ext::TIMESTAMP_TZ AS legacycreatetime_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwcc', 'cc_check') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS check_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'ocr_invoice_icare',
                        'issuedate',
                        'dateofservice',
                        'lastpostingdate_icare',
                        'updatetime',
                        'isprimary',
                        'servicepdstart',
                        'pendescalationforbulk',
                        'deductiontype',
                        'paytodenorm',
                        'createuserid',
                        'payto',
                        'mailingaddressid',
                        'bankbranchname_icare',
                        'recurringcheckid',
                        'datepresented_icare',
                        'beanversion',
                        'abn_icare',
                        'commmethod_icare',
                        'retired',
                        'bankaccounttype',
                        'recurrence_icare',
                        'checkinstructions',
                        'updateuserid',
                        'dbnetamount_icare',
                        'invoicenumber',
                        'bulkinvoiceiteminfoid',
                        'accountname',
                        'foreigncurrencyamount_icare',
                        'payeewithnoabn_icare',
                        'memo',
                        'istotalgt82_icare',
                        'bankswiftcode_icare',
                        'portionid',
                        'checktype',
                        'mailtoaddress',
                        'transactionidentifier_icare',
                        'publicid',
                        'enteredtime',
                        'bankname',
                        'weeklybenefitpayeetype_icare',
                        'createtime',
                        'deductionidentifier_icare',
                        'checknumber',
                        'servicepdend',
                        'bankroutingnumber',
                        'emailaddress_icare',
                        'servicesprovidedoverseas_icare',
                        'currencytransacted_icare',
                        'deliverymethod',
                        'originalmigratedstatus_icare',
                        'claimid',
                        'aggregateremittance_icare',
                        'westpacid_icare',
                        'groupid',
                        'registeredforgst_icare',
                        'datepaymenttransacted_icare',
                        'accrued_icare',
                        'scheduledsenddate',
                        'isinvoiceissuedto_icare',
                        'previouschecktype_icare',
                        'reportableamount',
                        'paymentmethod',
                        'archivepartition',
                        'gstmethodpel_ext',
                        'checkbatching',
                        'bankaccount',
                        'mailto',
                        'status',
                        'comments',
                        'checksetid',
                        'reportability',
                        'voidedpaymentnumber_icare',
                        'bankaccountnumber',
                        'prepostpayg_icare',
                        'gstpaymentclasspel_ext',
                        'claimcontactid',
                        'paymentsource_icare',
                        'colpaygwithholdvariation_icare',
                        'paygwithholdvariation_icare',
                        'camtvoiddate_icare',
                        'rejectionreason_ext',
                        'ismsppayment_ext',
                        'overrideautowagecalc_ext',
                        'recalculatedeductions_ext',
                        'legacyupdatetime_ext',
                        'ismigrated_ext',
                        'legacycreatetime_ext'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS dbt_updated_at
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}