{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for ccx_ocrinvoice_icare.
                                                ocrinvoice_icare_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["raw_layer", "raw_claim_centre", "claim_centre", "business_critical", "ccx_ocrinvoice_icare"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                CAST(data_payload:InvoiceAddressedTo::TEXT AS VARCHAR(255)) AS invoiceaddressedto,
                data_payload:PayeeMobileNumberCountry::NUMBER AS payeemobilenumbercountry,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                CAST(data_payload:DocumentIdentifier::TEXT AS VARCHAR(20)) AS documentidentifier,
                CAST(data_payload:ClaimNumber::TEXT AS VARCHAR(40)) AS claimnumber,
                CAST(data_payload:InvoiceTotalNet AS NUMBER(18,2)) AS invoicetotalnet,
                data_payload:PayeePhoneNumberCountry::NUMBER AS payeephonenumbercountry,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                CAST(data_payload:Postcode::TEXT AS VARCHAR(20)) AS postcode,
                CAST(data_payload:PayeeAddressLine1::TEXT AS VARCHAR(60)) AS payeeaddressline1,
                data_payload:State::NUMBER AS state,
                CAST(data_payload:PayeeName::TEXT AS VARCHAR(255)) AS payeename,
                CAST(data_payload:ServiceRequestID::TEXT AS VARCHAR(20)) AS servicerequestid,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:ClaimID::NUMBER AS claimid,
                data_payload:ID::NUMBER AS id,
                TO_TIMESTAMP_TZ(data_payload:InvoiceDate::NUMBER/1000) AS invoicedate,
                TO_TIMESTAMP_TZ(data_payload:DateInvoiceReceived::NUMBER/1000) AS dateinvoicereceived,
                data_payload:CreateUserID::NUMBER AS createuserid,
                CAST(data_payload:PayeeTradingName::TEXT AS VARCHAR(255)) AS payeetradingname,
                CAST(data_payload:PayeeABN::TEXT AS VARCHAR(50)) AS payeeabn,
                CAST(data_payload:InvoiceOutstandingAmount AS NUMBER(18,2)) AS invoiceoutstandingamount,
                CAST(data_payload:Suburb::TEXT AS VARCHAR(40)) AS suburb,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                data_payload:Retired::NUMBER AS retired,
                CAST(data_payload:City::TEXT AS VARCHAR(40)) AS city,
                CAST(data_payload:PayeeMobileNumberExtension::TEXT AS VARCHAR(60)) AS payeemobilenumberextension,
                data_payload:CommMethod::NUMBER AS commmethod,
                CAST(data_payload:InvoiceTotalGross AS NUMBER(18,2)) AS invoicetotalgross,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                CAST(data_payload:PayeePhoneNumber::TEXT AS VARCHAR(30)) AS payeephonenumber,
                CAST(data_payload:PayeePhoneNumberExtension::TEXT AS VARCHAR(60)) AS payeephonenumberextension,
                CAST(data_payload:InvoiceTotalGST AS NUMBER(18,2)) AS invoicetotalgst,
                data_payload:Status::NUMBER AS status,
                CAST(data_payload:PayeeMobileNumber::TEXT AS VARCHAR(30)) AS payeemobilenumber,
                CAST(data_payload:InvoiceNumber::TEXT AS VARCHAR(50)) AS invoicenumber,
                CAST(data_payload:AccountNumber::TEXT AS VARCHAR(20)) AS accountnumber,
                CAST(data_payload:AccountName::TEXT AS VARCHAR(90)) AS accountname,
                CAST(data_payload:BSBNumber::TEXT AS VARCHAR(20)) AS bsbnumber,
                data_payload:schemeId::NUMBER AS schemeid,
                data_payload:InvoiceSource::NUMBER AS invoicesource,
                CAST(data_payload:TransactionType::TEXT AS VARCHAR(255)) AS transactiontype,
                CAST(data_payload:ProviderUniqueId::TEXT AS VARCHAR(40)) AS provideruniqueid,
                CAST(data_payload:ServiceNotes::TEXT AS VARCHAR(16777216)) AS servicenotes,
                CAST(data_payload:PayeeCRMId::TEXT AS VARCHAR(255)) AS payeecrmid,
                TO_TIMESTAMP_TZ(data_payload:CancellationDate::NUMBER/1000) AS cancellationdate,
                CAST(data_payload:CancelReason::TEXT AS VARCHAR(16777216)) AS cancelreason,
                CAST(data_payload:BankName::TEXT AS VARCHAR(60)) AS bankname,
                TO_TIMESTAMP_TZ(data_payload:IWDOB::NUMBER/1000) AS iwdob,
                CAST(data_payload:IWFirstName::TEXT AS VARCHAR(300)) AS iwfirstname,
                CAST(data_payload:IWLastName::TEXT AS VARCHAR(300)) AS iwlastname,
                data_payload:InvoiceRejectReason::NUMBER AS invoicerejectreason,
                CAST(data_payload:InvoiceRejectMessage::TEXT AS VARCHAR(16777216)) AS invoicerejectmessage,
                data_payload:InvoiceApproveReason::NUMBER AS invoiceapprovereason,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwcc', 'ccx_ocrinvoice_icare') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                CAST($1:invoiceaddressedto::TEXT AS VARCHAR(255)) AS invoiceaddressedto,
                $1:payeemobilenumbercountry::NUMBER AS payeemobilenumbercountry,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                CAST($1:documentidentifier::TEXT AS VARCHAR(20)) AS documentidentifier,
                CAST($1:claimnumber::TEXT AS VARCHAR(40)) AS claimnumber,
                CAST($1:invoicetotalnet AS NUMBER(18,2)) AS invoicetotalnet,
                $1:payeephonenumbercountry::NUMBER AS payeephonenumbercountry,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                CAST($1:postcode::TEXT AS VARCHAR(20)) AS postcode,
                CAST($1:payeeaddressline1::TEXT AS VARCHAR(60)) AS payeeaddressline1,
                $1:state::NUMBER AS state,
                CAST($1:payeename::TEXT AS VARCHAR(255)) AS payeename,
                CAST($1:servicerequestid::TEXT AS VARCHAR(20)) AS servicerequestid,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:claimid::NUMBER AS claimid,
                $1:id::NUMBER AS id,
                $1:invoicedate::TIMESTAMP_TZ AS invoicedate,
                $1:dateinvoicereceived::TIMESTAMP_TZ AS dateinvoicereceived,
                $1:createuserid::NUMBER AS createuserid,
                CAST($1:payeetradingname::TEXT AS VARCHAR(255)) AS payeetradingname,
                CAST($1:payeeabn::TEXT AS VARCHAR(50)) AS payeeabn,
                CAST($1:invoiceoutstandingamount AS NUMBER(18,2)) AS invoiceoutstandingamount,
                CAST($1:suburb::TEXT AS VARCHAR(40)) AS suburb,
                $1:beanversion::NUMBER AS beanversion,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:retired::NUMBER AS retired,
                CAST($1:city::TEXT AS VARCHAR(40)) AS city,
                CAST($1:payeemobilenumberextension::TEXT AS VARCHAR(60)) AS payeemobilenumberextension,
                $1:commmethod::NUMBER AS commmethod,
                CAST($1:invoicetotalgross AS NUMBER(18,2)) AS invoicetotalgross,
                $1:updateuserid::NUMBER AS updateuserid,
                CAST($1:payeephonenumber::TEXT AS VARCHAR(30)) AS payeephonenumber,
                CAST($1:payeephonenumberextension::TEXT AS VARCHAR(60)) AS payeephonenumberextension,
                CAST($1:invoicetotalgst AS NUMBER(18,2)) AS invoicetotalgst,
                $1:status::NUMBER AS status,
                CAST($1:payeemobilenumber::TEXT AS VARCHAR(30)) AS payeemobilenumber,
                CAST($1:invoicenumber::TEXT AS VARCHAR(50)) AS invoicenumber,
                CAST($1:accountnumber::TEXT AS VARCHAR(20)) AS accountnumber,
                CAST($1:accountname::TEXT AS VARCHAR(90)) AS accountname,
                CAST($1:bsbnumber::TEXT AS VARCHAR(20)) AS bsbnumber,
                $1:schemeid::NUMBER AS schemeid,
                $1:invoicesource::NUMBER AS invoicesource,
                CAST($1:transactiontype::TEXT AS VARCHAR(255)) AS transactiontype,
                CAST($1:provideruniqueid::TEXT AS VARCHAR(40)) AS provideruniqueid,
                CAST($1:servicenotes::TEXT AS VARCHAR(16777216)) AS servicenotes,
                CAST($1:payeecrmid::TEXT AS VARCHAR(255)) AS payeecrmid,
                $1:cancellationdate::TIMESTAMP_TZ AS cancellationdate,
                CAST($1:cancelreason::TEXT AS VARCHAR(16777216)) AS cancelreason,
                CAST($1:bankname::TEXT AS VARCHAR(60)) AS bankname,
                $1:iwdob::TIMESTAMP_TZ AS iwdob,
                CAST($1:iwfirstname::TEXT AS VARCHAR(300)) AS iwfirstname,
                CAST($1:iwlastname::TEXT AS VARCHAR(300)) AS iwlastname,
                $1:invoicerejectreason::NUMBER AS invoicerejectreason,
                CAST($1:invoicerejectmessage::TEXT AS VARCHAR(16777216)) AS invoicerejectmessage,
                $1:invoiceapprovereason::NUMBER AS invoiceapprovereason,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwcc', 'ccx_ocrinvoice_icare') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS ocrinvoice_icare_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'invoiceaddressedto',
                        'payeemobilenumbercountry',
                        'publicid',
                        'documentidentifier',
                        'claimnumber',
                        'invoicetotalnet',
                        'payeephonenumbercountry',
                        'createtime',
                        'postcode',
                        'payeeaddressline1',
                        'state',
                        'payeename',
                        'servicerequestid',
                        'updatetime',
                        'claimid',
                        'invoicedate',
                        'dateinvoicereceived',
                        'createuserid',
                        'payeetradingname',
                        'payeeabn',
                        'invoiceoutstandingamount',
                        'suburb',
                        'beanversion',
                        'archivepartition',
                        'retired',
                        'city',
                        'payeemobilenumberextension',
                        'commmethod',
                        'invoicetotalgross',
                        'updateuserid',
                        'payeephonenumber',
                        'payeephonenumberextension',
                        'invoicetotalgst',
                        'status',
                        'payeemobilenumber',
                        'invoicenumber',
                        'accountnumber',
                        'accountname',
                        'bsbnumber',
                        'schemeid',
                        'invoicesource',
                        'transactiontype',
                        'provideruniqueid',
                        'servicenotes',
                        'payeecrmid',
                        'cancellationdate',
                        'cancelreason',
                        'bankname',
                        'iwdob',
                        'iwfirstname',
                        'iwlastname',
                        'invoicerejectreason',
                        'invoicerejectmessage',
                        'invoiceapprovereason'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) as record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}