{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for ccx_piawe_icare.
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                record_insertion_date: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDA goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    incremental_strategy='append',
    on_schema_change='append_new_columns',
    tags=["landing", "gwcc", "claim_centre", "business_critical"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                CAST(data_payload:UncappedPIAWEPre52 AS NUMBER(18,2)) AS uncappedpiawepre52,
                data_payload:TotalOELeaveWeeks::NUMBER AS totaloeleaveweeks,
                CAST(data_payload:DeflatedPIAWEPre52 AS NUMBER(18,2)) AS deflatedpiawepre52,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                CAST(data_payload:OrdinaryEarnings_icare AS NUMBER(18,2)) AS ordinaryearnings_icare,
                CAST(data_payload:TotalShiftOTAllowanceWeekRP AS NUMBER(18,2)) AS totalshiftotallowanceweekrp,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                CAST(data_payload:PIAWEComment::TEXT AS VARCHAR(16777216)) AS piawecomment,
                data_payload:PartialPIAWELinkID::NUMBER AS partialpiawelinkid,
                CAST(data_payload:TotalOvertimeLeaveAmount AS NUMBER(18,2)) AS totalovertimeleaveamount,
                data_payload:PIAWEType_icare::NUMBER AS piawetype_icare,
                TO_TIMESTAMP_TZ(data_payload:RPEndDate::NUMBER/1000) AS rpenddate,
                CAST(data_payload:TotalOEWeekRP AS NUMBER(18,2)) AS totaloeweekrp,
                CAST(data_payload:PIAWELater52_icare AS NUMBER(18,2)) AS piawelater52_icare,
                data_payload:Schedule3Item::NUMBER AS schedule3item,
                TO_TIMESTAMP_TZ(data_payload:EffectiveDate_icare::NUMBER/1000) AS effectivedate_icare,
                CAST(data_payload:TotalShiftLeaveAmount AS NUMBER(18,2)) AS totalshiftleaveamount,
                TO_TIMESTAMP_TZ(data_payload:RPStartDate::NUMBER/1000) AS rpstartdate,
                CAST(data_payload:OvertimeAllowance_icare AS NUMBER(18,2)) AS overtimeallowance_icare,
                data_payload:PIAWEDeactivated_icare::BOOLEAN AS piawedeactivated_icare,
                CAST(data_payload:PIAWEReason_icare::TEXT AS VARCHAR(200)) AS piawereason_icare,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:LeaveWageRecordsRecd::BOOLEAN AS leavewagerecordsrecd,
                CAST(data_payload:TotalOvertimeWeek AS NUMBER(18,2)) AS totalovertimeweek,
                CAST(data_payload:DeflatedPIAWEPost52 AS NUMBER(18,2)) AS deflatedpiawepost52,
                data_payload:ID::NUMBER AS id,
                data_payload:Schedule3Applicable::BOOLEAN AS schedule3applicable,
                data_payload:RelevantPeriod::NUMBER AS relevantperiod,
                CAST(data_payload:TotalOEWeekOverRP AS NUMBER(18,2)) AS totaloeweekoverrp,
                data_payload:Draft::BOOLEAN AS draft,
                data_payload:CreateUserID::NUMBER AS createuserid,
                data_payload:ExposureID::NUMBER AS exposureid,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                data_payload:Retired::NUMBER AS retired,
                data_payload:TotalLeaveWeeksRP::NUMBER AS totalleaveweeksrp,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                data_payload:EmploymentDataID::NUMBER AS employmentdataid,
                CAST(data_payload:TotalShiftWeek AS NUMBER(18,2)) AS totalshiftweek,
                CAST(data_payload:PIAWEFirst52_icare AS NUMBER(18,2)) AS piawefirst52_icare,
                CAST(data_payload:Comments::TEXT AS VARCHAR(1333)) AS comments,
                CAST(data_payload:TotalOELeaveAmount AS NUMBER(18,2)) AS totaloeleaveamount,
                CAST(data_payload:UncappedPIAWEPost52 AS NUMBER(18,2)) AS uncappedpiawepost52,
                data_payload:StatMinApplied::BOOLEAN AS statminapplied,
                data_payload:HoursWorked::NUMBER AS hoursworked,
                data_payload:NoteID::NUMBER AS noteid,
                CAST(data_payload:RelevantPeriodLegReforms2018 AS NUMBER(10,2)) AS relevantperiodlegreforms2018,
                TO_TIMESTAMP_TZ(data_payload:AgreementReceivedDate::NUMBER/1000) AS agreementreceiveddate,
                data_payload:AgreementApproved::BOOLEAN AS agreementapproved,
                TO_TIMESTAMP_TZ(data_payload:AgreementWithdrawDate::NUMBER/1000) AS agreementwithdrawdate,
                data_payload:DocumentLinkableID::NUMBER AS documentlinkableid,
                data_payload:AutoCreated::BOOLEAN AS autocreated,
                TO_TIMESTAMP_TZ(data_payload:AgreementApprovedDate::NUMBER/1000) AS agreementapproveddate,
                data_payload:NeedPIAWEWorksheet::BOOLEAN AS needpiaweworksheet,
                data_payload:InitialPIAWE::BOOLEAN AS initialpiawe,
                data_payload:WorkCapRefID::NUMBER AS workcaprefid,
                data_payload:IsDocumentUsedForPIAWE_Ext::BOOLEAN AS isdocumentusedforpiawe_ext,
                CAST(data_payload:Reason_Ext::TEXT AS VARCHAR(1333)) AS reason_ext,
                data_payload:IsIndexationDecrOnReopen::BOOLEAN AS isindexationdecronreopen,
                TO_TIMESTAMP_TZ(data_payload:LegacyCreateTime::NUMBER/1000) AS legacycreatetime,
                TO_TIMESTAMP_TZ(data_payload:LegacyUpdateTime::NUMBER/1000) AS legacyupdatetime,
                CAST(data_payload:PIAWEIndexationID::TEXT AS VARCHAR(64)) AS piaweindexationid,
                data_payload:IsInjuredWorkerBelow21::BOOLEAN AS isinjuredworkerbelow21,
                data_payload:IsInjuredWorkerApprentice::BOOLEAN AS isinjuredworkerapprentice,
                CAST(data_payload:WCDPIAWEAmount AS NUMBER(18,2)) AS wcdpiaweamount,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS VARCHAR(300)) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'AVRO' as file_type,
                'GWCC' as source_system
            FROM {{ source('gwcc', 'ccx_piawe_icare') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                CAST($1:uncappedpiawepre52 AS NUMBER(18,2)) AS uncappedpiawepre52,
                $1:totaloeleaveweeks::NUMBER AS totaloeleaveweeks,
                CAST($1:deflatedpiawepre52 AS NUMBER(18,2)) AS deflatedpiawepre52,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                CAST($1:ordinaryearnings_icare AS NUMBER(18,2)) AS ordinaryearnings_icare,
                CAST($1:totalshiftotallowanceweekrp AS NUMBER(18,2)) AS totalshiftotallowanceweekrp,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                CAST($1:piawecomment::TEXT AS VARCHAR(16777216)) AS piawecomment,
                $1:partialpiawelinkid::NUMBER AS partialpiawelinkid,
                CAST($1:totalovertimeleaveamount AS NUMBER(18,2)) AS totalovertimeleaveamount,
                $1:piawetype_icare::NUMBER AS piawetype_icare,
                $1:rpenddate::TIMESTAMP_TZ AS rpenddate,
                CAST($1:totaloeweekrp AS NUMBER(18,2)) AS totaloeweekrp,
                CAST($1:piawelater52_icare AS NUMBER(18,2)) AS piawelater52_icare,
                $1:schedule3item::NUMBER AS schedule3item,
                $1:effectivedate_icare::TIMESTAMP_TZ AS effectivedate_icare,
                CAST($1:totalshiftleaveamount AS NUMBER(18,2)) AS totalshiftleaveamount,
                $1:rpstartdate::TIMESTAMP_TZ AS rpstartdate,
                CAST($1:overtimeallowance_icare AS NUMBER(18,2)) AS overtimeallowance_icare,
                $1:piawedeactivated_icare::BOOLEAN AS piawedeactivated_icare,
                CAST($1:piawereason_icare::TEXT AS VARCHAR(200)) AS piawereason_icare,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:leavewagerecordsrecd::BOOLEAN AS leavewagerecordsrecd,
                CAST($1:totalovertimeweek AS NUMBER(18,2)) AS totalovertimeweek,
                CAST($1:deflatedpiawepost52 AS NUMBER(18,2)) AS deflatedpiawepost52,
                $1:id::NUMBER AS id,
                $1:schedule3applicable::BOOLEAN AS schedule3applicable,
                $1:relevantperiod::NUMBER AS relevantperiod,
                CAST($1:totaloeweekoverrp AS NUMBER(18,2)) AS totaloeweekoverrp,
                $1:draft::BOOLEAN AS draft,
                $1:createuserid::NUMBER AS createuserid,
                $1:exposureid::NUMBER AS exposureid,
                $1:beanversion::NUMBER AS beanversion,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:retired::NUMBER AS retired,
                $1:totalleaveweeksrp::NUMBER AS totalleaveweeksrp,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:employmentdataid::NUMBER AS employmentdataid,
                CAST($1:totalshiftweek AS NUMBER(18,2)) AS totalshiftweek,
                CAST($1:piawefirst52_icare AS NUMBER(18,2)) AS piawefirst52_icare,
                CAST($1:comments::TEXT AS VARCHAR(1333)) AS comments,
                CAST($1:totaloeleaveamount AS NUMBER(18,2)) AS totaloeleaveamount,
                CAST($1:uncappedpiawepost52 AS NUMBER(18,2)) AS uncappedpiawepost52,
                $1:statminapplied::BOOLEAN AS statminapplied,
                $1:hoursworked::NUMBER AS hoursworked,
                $1:noteid::NUMBER AS noteid,
                CAST($1:relevantperiodlegreforms2018 AS NUMBER(10,2)) AS relevantperiodlegreforms2018,
                $1:agreementreceiveddate::TIMESTAMP_TZ AS agreementreceiveddate,
                $1:agreementapproved::BOOLEAN AS agreementapproved,
                $1:agreementwithdrawdate::TIMESTAMP_TZ AS agreementwithdrawdate,
                $1:documentlinkableid::NUMBER AS documentlinkableid,
                $1:autocreated::BOOLEAN AS autocreated,
                $1:agreementapproveddate::TIMESTAMP_TZ AS agreementapproveddate,
                $1:needpiaweworksheet::BOOLEAN AS needpiaweworksheet,
                $1:initialpiawe::BOOLEAN AS initialpiawe,
                $1:workcaprefid::NUMBER AS workcaprefid,
                $1:isdocumentusedforpiawe_ext::BOOLEAN AS isdocumentusedforpiawe_ext,
                CAST($1:reason_ext::TEXT AS VARCHAR(1333)) AS reason_ext,
                $1:isindexationdecronreopen::BOOLEAN AS isindexationdecronreopen,
                $1:legacycreatetime::TIMESTAMP_TZ AS legacycreatetime,
                $1:legacyupdatetime::TIMESTAMP_TZ AS legacyupdatetime,
                CAST($1:piaweindexationid::TEXT AS VARCHAR(64)) AS piaweindexationid,
                $1:isinjuredworkerbelow21::BOOLEAN AS isinjuredworkerbelow21,
                $1:isinjuredworkerapprentice::BOOLEAN AS isinjuredworkerapprentice,
                CAST($1:wcdpiaweamount AS NUMBER(18,2)) AS wcdpiaweamount,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::VARCHAR(300) as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'PARQUET' as file_type,
                'GWCC' as source_system
            FROM {{ source('gwcc', 'ccx_piawe_icare') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS piawe_icare_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'uncappedpiawepre52',
                        'totaloeleaveweeks',
                        'deflatedpiawepre52',
                        'publicid',
                        'ordinaryearnings_icare',
                        'totalshiftotallowanceweekrp',
                        'createtime',
                        'piawecomment',
                        'partialpiawelinkid',
                        'totalovertimeleaveamount',
                        'piawetype_icare',
                        'rpenddate',
                        'totaloeweekrp',
                        'piawelater52_icare',
                        'schedule3item',
                        'effectivedate_icare',
                        'totalshiftleaveamount',
                        'rpstartdate',
                        'overtimeallowance_icare',
                        'piawedeactivated_icare',
                        'piawereason_icare',
                        'updatetime',
                        'leavewagerecordsrecd',
                        'totalovertimeweek',
                        'deflatedpiawepost52',
                        'schedule3applicable',
                        'relevantperiod',
                        'totaloeweekoverrp',
                        'draft',
                        'createuserid',
                        'exposureid',
                        'beanversion',
                        'archivepartition',
                        'retired',
                        'totalleaveweeksrp',
                        'updateuserid',
                        'employmentdataid',
                        'totalshiftweek',
                        'piawefirst52_icare',
                        'comments',
                        'totaloeleaveamount',
                        'uncappedpiawepost52',
                        'statminapplied',
                        'hoursworked',
                        'noteid',
                        'relevantperiodlegreforms2018',
                        'agreementreceiveddate',
                        'agreementapproved',
                        'agreementwithdrawdate',
                        'documentlinkableid',
                        'autocreated',
                        'agreementapproveddate',
                        'needpiaweworksheet',
                        'initialpiawe',
                        'workcaprefid',
                        'isdocumentusedforpiawe_ext',
                        'reason_ext',
                        'isindexationdecronreopen',
                        'legacycreatetime',
                        'legacyupdatetime',
                        'piaweindexationid',
                        'isinjuredworkerbelow21',
                        'isinjuredworkerapprentice',
                        'wcdpiaweamount'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
    WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}
    ORDER BY record_insertion_date
