{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for cc_exposure.
                                                exposure_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["raw_layer", "raw_claim_centre", "claim_centre", "business_critical", "cc_exposure"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:CoverageID::NUMBER AS coverageid,
                data_payload:PreviousGroupID::NUMBER AS previousgroupid,
                data_payload:IncidentLimitReached::BOOLEAN AS incidentlimitreached,
                data_payload:Locked::BOOLEAN AS locked,
                data_payload:AssignedByUserID::NUMBER AS assignedbyuserid,
                data_payload:OtherCovgChoice::NUMBER AS othercovgchoice,
                data_payload:DiagnosticCnsistnt::BOOLEAN AS diagnosticcnsistnt,
                data_payload:PIPClaimAggLimitReached::BOOLEAN AS pipclaimagglimitreached,
                data_payload:PreviousQueueID::NUMBER AS previousqueueid,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:ID::NUMBER AS id,
                TO_TIMESTAMP_TZ(data_payload:ExaminationDate::NUMBER/1000) AS examinationdate,
                data_payload:VocBenefitsID::NUMBER AS vocbenefitsid,
                data_payload:LossCategory::NUMBER AS losscategory,
                data_payload:CreateUserID::NUMBER AS createuserid,
                data_payload:CompBenefitsID::NUMBER AS compbenefitsid,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:LifePensionBenefitsID::NUMBER AS lifepensionbenefitsid,
                TO_TIMESTAMP_TZ(data_payload:ReOpenDate::NUMBER/1000) AS reopendate,
                CAST(data_payload:AverageWeeklyWages AS NUMBER(18,2)) AS averageweeklywages,
                data_payload:Progress::NUMBER AS progress,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                data_payload:Segment::NUMBER AS segment,
                TO_TIMESTAMP_TZ(data_payload:LastDayWorked::NUMBER/1000) AS lastdayworked,
                CAST(data_payload:DepreciatedValue AS NUMBER(18,2)) AS depreciatedvalue,
                data_payload:SSBenefit::BOOLEAN AS ssbenefit,
                data_payload:PPDBenefitsID::NUMBER AS ppdbenefitsid,
                data_payload:TPDBenefitsID::NUMBER AS tpdbenefitsid,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                data_payload:SecurityLevel::NUMBER AS securitylevel,
                data_payload:DeathBenefitsID::NUMBER AS deathbenefitsid,
                data_payload:WCBenefit::BOOLEAN AS wcbenefit,
                data_payload:AssignedGroupID::NUMBER AS assignedgroupid,
                data_payload:FatalityInterest_icare::NUMBER AS fatalityinterest_icare,
                data_payload:SupplementalWorkloadWeight::NUMBER AS supplementalworkloadweight,
                data_payload:WCPreexDisblty::BOOLEAN AS wcpreexdisblty,
                data_payload:ClaimID::NUMBER AS claimid,
                data_payload:AssignedQueueID::NUMBER AS assignedqueueid,
                data_payload:MetricLimitGeneration::NUMBER AS metriclimitgeneration,
                data_payload:StatLineID::NUMBER AS statlineid,
                TO_TIMESTAMP_TZ(data_payload:WorkloadUpdated::NUMBER/1000) AS workloadupdated,
                data_payload:BreakIn::BOOLEAN AS breakin,
                data_payload:TempLocationID::NUMBER AS templocationid,
                data_payload:ClosedOutcome::NUMBER AS closedoutcome,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                data_payload:ExposureTier::NUMBER AS exposuretier,
                TO_TIMESTAMP_TZ(data_payload:ISOReceiveDate::NUMBER/1000) AS isoreceivedate,
                data_payload:IncidentID::NUMBER AS incidentid,
                data_payload:NewEmpDataID::NUMBER AS newempdataid,
                data_payload:WageBenefit::BOOLEAN AS wagebenefit,
                data_payload:Strategy::NUMBER AS strategy,
                data_payload:AssignedUserID::NUMBER AS assigneduserid,
                TO_TIMESTAMP_TZ(data_payload:SettleDate::NUMBER/1000) AS settledate,
                data_payload:SSDIBenefitsID::NUMBER AS ssdibenefitsid,
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                TO_TIMESTAMP_TZ(data_payload:WCCDate_icare::NUMBER/1000) AS wccdate_icare,
                CAST(data_payload:WCPreexDisbltyInfo::TEXT AS VARCHAR(255)) AS wcpreexdisbltyinfo,
                data_payload:TreatedPatientBfr::BOOLEAN AS treatedpatientbfr,
                data_payload:PriorEmpDataID::NUMBER AS priorempdataid,
                data_payload:ExistingWeeklyBenefits_icare::BOOLEAN AS existingweeklybenefits_icare,
                TO_TIMESTAMP_TZ(data_payload:WageStmtSent::NUMBER/1000) AS wagestmtsent,
                data_payload:PIPPersonAggLimitReached::BOOLEAN AS pippersonagglimitreached,
                data_payload:State::NUMBER AS state,
                data_payload:HospitalDays::NUMBER AS hospitaldays,
                data_payload:CoverageSubType::NUMBER AS coveragesubtype,
                data_payload:ClaimOrder::NUMBER AS claimorder,
                CAST(data_payload:ReplacementValue AS NUMBER(18,2)) AS replacementvalue,
                data_payload:ReopenedReason::NUMBER AS reopenedreason,
                data_payload:LossParty::NUMBER AS lossparty,
                data_payload:WCBenefitsID::NUMBER AS wcbenefitsid,
                CAST(data_payload:OtherCoverageInfo::TEXT AS VARCHAR(255)) AS othercoverageinfo,
                TO_TIMESTAMP_TZ(data_payload:CloseDate::NUMBER/1000) AS closedate,
                data_payload:Retired::NUMBER AS retired,
                data_payload:ValidationLevel::NUMBER AS validationlevel,
                data_payload:WorkloadWeight::NUMBER AS workloadweight,
                data_payload:DaysInWeek::NUMBER AS daysinweek,
                data_payload:JurisdictionState::NUMBER AS jurisdictionstate,
                data_payload:LostPropertyType::NUMBER AS lostpropertytype,
                data_payload:ISOStatus::NUMBER AS isostatus,
                data_payload:PTDBenefitsID::NUMBER AS ptdbenefitsid,
                TO_TIMESTAMP_TZ(data_payload:ISOSendDate::NUMBER/1000) AS isosenddate,
                data_payload:TTDBenefitsID::NUMBER AS ttdbenefitsid,
                data_payload:SSDIEligible::BOOLEAN AS ssdieligible,
                data_payload:ExposureLimitReached::BOOLEAN AS exposurelimitreached,
                data_payload:ExposureType::NUMBER AS exposuretype,
                data_payload:PIPNonMedAggLimitReached::BOOLEAN AS pipnonmedagglimitreached,
                data_payload:ClaimantDenormID::NUMBER AS claimantdenormid,
                TO_TIMESTAMP_TZ(data_payload:WageStmtRecd::NUMBER/1000) AS wagestmtrecd,
                data_payload:PIPESSLimitReached::BOOLEAN AS pipesslimitreached,
                data_payload:RIAgreementGroupID::NUMBER AS riagreementgroupid,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                data_payload:FutureCOWEarnings_icare::BOOLEAN AS futurecowearnings_icare,
                data_payload:RIGroupSetExternally::BOOLEAN AS rigroupsetexternally,
                data_payload:FurtherTreatment::BOOLEAN AS furthertreatment,
                data_payload:PIPDeathBenefitsID::NUMBER AS pipdeathbenefitsid,
                data_payload:RSBenefitsID::NUMBER AS rsbenefitsid,
                data_payload:PreviousUserID::NUMBER AS previoususerid,
                data_payload:ISOKnown::BOOLEAN AS isoknown,
                TO_TIMESTAMP_TZ(data_payload:SurgeryDate_icare::NUMBER/1000) AS surgerydate_icare,
                CAST(data_payload:ExcessRecoveryAmount AS NUMBER(18,2)) AS excessrecoveryamount,
                data_payload:ClaimantType::NUMBER AS claimanttype,
                data_payload:DisBenefitsID::NUMBER AS disbenefitsid,
                TO_TIMESTAMP_TZ(data_payload:HospitalDate::NUMBER/1000) AS hospitaldate,
                data_payload:PrimaryCoverage::NUMBER AS primarycoverage,
                data_payload:PIPVocBenefitsID::NUMBER AS pipvocbenefitsid,
                data_payload:SettleMethod::NUMBER AS settlemethod,
                data_payload:CurrentConditions::BOOLEAN AS currentconditions,
                data_payload:OtherCoverage::BOOLEAN AS othercoverage,
                data_payload:ContactPermitted::BOOLEAN AS contactpermitted,
                TO_TIMESTAMP_TZ(data_payload:AssignmentDate::NUMBER/1000) AS assignmentdate,
                data_payload:AssignmentStatus::NUMBER AS assignmentstatus,
                data_payload:WorkerPayer_icare::NUMBER AS workerpayer_icare,
                TO_TIMESTAMP_TZ(data_payload:CurrentSection38EffDate_icare::NUMBER/1000) AS currentsection38effdate_icare,
                data_payload:IsSection41Eligible_icare::BOOLEAN AS issection41eligible_icare,
                TO_TIMESTAMP_TZ(data_payload:MBCD_Ext::NUMBER/1000) AS mbcd_ext,
                data_payload:IsS59A7SecSurgeryType_Ext::BOOLEAN AS iss59a7secsurgerytype_ext,
                data_payload:IsS59A3ReinstatementWBType_Ext::BOOLEAN AS iss59a3reinstatementwbtype_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwcc', 'cc_exposure') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:coverageid::NUMBER AS coverageid,
                $1:previousgroupid::NUMBER AS previousgroupid,
                $1:incidentlimitreached::BOOLEAN AS incidentlimitreached,
                $1:locked::BOOLEAN AS locked,
                $1:assignedbyuserid::NUMBER AS assignedbyuserid,
                $1:othercovgchoice::NUMBER AS othercovgchoice,
                $1:diagnosticcnsistnt::BOOLEAN AS diagnosticcnsistnt,
                $1:pipclaimagglimitreached::BOOLEAN AS pipclaimagglimitreached,
                $1:previousqueueid::NUMBER AS previousqueueid,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:id::NUMBER AS id,
                $1:examinationdate::TIMESTAMP_TZ AS examinationdate,
                $1:vocbenefitsid::NUMBER AS vocbenefitsid,
                $1:losscategory::NUMBER AS losscategory,
                $1:createuserid::NUMBER AS createuserid,
                $1:compbenefitsid::NUMBER AS compbenefitsid,
                $1:beanversion::NUMBER AS beanversion,
                $1:lifepensionbenefitsid::NUMBER AS lifepensionbenefitsid,
                $1:reopendate::TIMESTAMP_TZ AS reopendate,
                CAST($1:averageweeklywages AS NUMBER(18,2)) AS averageweeklywages,
                $1:progress::NUMBER AS progress,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:segment::NUMBER AS segment,
                $1:lastdayworked::TIMESTAMP_TZ AS lastdayworked,
                CAST($1:depreciatedvalue AS NUMBER(18,2)) AS depreciatedvalue,
                $1:ssbenefit::BOOLEAN AS ssbenefit,
                $1:ppdbenefitsid::NUMBER AS ppdbenefitsid,
                $1:tpdbenefitsid::NUMBER AS tpdbenefitsid,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:securitylevel::NUMBER AS securitylevel,
                $1:deathbenefitsid::NUMBER AS deathbenefitsid,
                $1:wcbenefit::BOOLEAN AS wcbenefit,
                $1:assignedgroupid::NUMBER AS assignedgroupid,
                $1:fatalityinterest_icare::NUMBER AS fatalityinterest_icare,
                $1:supplementalworkloadweight::NUMBER AS supplementalworkloadweight,
                $1:wcpreexdisblty::BOOLEAN AS wcpreexdisblty,
                $1:claimid::NUMBER AS claimid,
                $1:assignedqueueid::NUMBER AS assignedqueueid,
                $1:metriclimitgeneration::NUMBER AS metriclimitgeneration,
                $1:statlineid::NUMBER AS statlineid,
                $1:workloadupdated::TIMESTAMP_TZ AS workloadupdated,
                $1:breakin::BOOLEAN AS breakin,
                $1:templocationid::NUMBER AS templocationid,
                $1:closedoutcome::NUMBER AS closedoutcome,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:exposuretier::NUMBER AS exposuretier,
                $1:isoreceivedate::TIMESTAMP_TZ AS isoreceivedate,
                $1:incidentid::NUMBER AS incidentid,
                $1:newempdataid::NUMBER AS newempdataid,
                $1:wagebenefit::BOOLEAN AS wagebenefit,
                $1:strategy::NUMBER AS strategy,
                $1:assigneduserid::NUMBER AS assigneduserid,
                $1:settledate::TIMESTAMP_TZ AS settledate,
                $1:ssdibenefitsid::NUMBER AS ssdibenefitsid,
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:wccdate_icare::TIMESTAMP_TZ AS wccdate_icare,
                CAST($1:wcpreexdisbltyinfo::TEXT AS VARCHAR(255)) AS wcpreexdisbltyinfo,
                $1:treatedpatientbfr::BOOLEAN AS treatedpatientbfr,
                $1:priorempdataid::NUMBER AS priorempdataid,
                $1:existingweeklybenefits_icare::BOOLEAN AS existingweeklybenefits_icare,
                $1:wagestmtsent::TIMESTAMP_TZ AS wagestmtsent,
                $1:pippersonagglimitreached::BOOLEAN AS pippersonagglimitreached,
                $1:state::NUMBER AS state,
                $1:hospitaldays::NUMBER AS hospitaldays,
                $1:coveragesubtype::NUMBER AS coveragesubtype,
                $1:claimorder::NUMBER AS claimorder,
                CAST($1:replacementvalue AS NUMBER(18,2)) AS replacementvalue,
                $1:reopenedreason::NUMBER AS reopenedreason,
                $1:lossparty::NUMBER AS lossparty,
                $1:wcbenefitsid::NUMBER AS wcbenefitsid,
                CAST($1:othercoverageinfo::TEXT AS VARCHAR(255)) AS othercoverageinfo,
                $1:closedate::TIMESTAMP_TZ AS closedate,
                $1:retired::NUMBER AS retired,
                $1:validationlevel::NUMBER AS validationlevel,
                $1:workloadweight::NUMBER AS workloadweight,
                $1:daysinweek::NUMBER AS daysinweek,
                $1:jurisdictionstate::NUMBER AS jurisdictionstate,
                $1:lostpropertytype::NUMBER AS lostpropertytype,
                $1:isostatus::NUMBER AS isostatus,
                $1:ptdbenefitsid::NUMBER AS ptdbenefitsid,
                $1:isosenddate::TIMESTAMP_TZ AS isosenddate,
                $1:ttdbenefitsid::NUMBER AS ttdbenefitsid,
                $1:ssdieligible::BOOLEAN AS ssdieligible,
                $1:exposurelimitreached::BOOLEAN AS exposurelimitreached,
                $1:exposuretype::NUMBER AS exposuretype,
                $1:pipnonmedagglimitreached::BOOLEAN AS pipnonmedagglimitreached,
                $1:claimantdenormid::NUMBER AS claimantdenormid,
                $1:wagestmtrecd::TIMESTAMP_TZ AS wagestmtrecd,
                $1:pipesslimitreached::BOOLEAN AS pipesslimitreached,
                $1:riagreementgroupid::NUMBER AS riagreementgroupid,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:futurecowearnings_icare::BOOLEAN AS futurecowearnings_icare,
                $1:rigroupsetexternally::BOOLEAN AS rigroupsetexternally,
                $1:furthertreatment::BOOLEAN AS furthertreatment,
                $1:pipdeathbenefitsid::NUMBER AS pipdeathbenefitsid,
                $1:rsbenefitsid::NUMBER AS rsbenefitsid,
                $1:previoususerid::NUMBER AS previoususerid,
                $1:isoknown::BOOLEAN AS isoknown,
                $1:surgerydate_icare::TIMESTAMP_TZ AS surgerydate_icare,
                CAST($1:excessrecoveryamount AS NUMBER(18,2)) AS excessrecoveryamount,
                $1:claimanttype::NUMBER AS claimanttype,
                $1:disbenefitsid::NUMBER AS disbenefitsid,
                $1:hospitaldate::TIMESTAMP_TZ AS hospitaldate,
                $1:primarycoverage::NUMBER AS primarycoverage,
                $1:pipvocbenefitsid::NUMBER AS pipvocbenefitsid,
                $1:settlemethod::NUMBER AS settlemethod,
                $1:currentconditions::BOOLEAN AS currentconditions,
                $1:othercoverage::BOOLEAN AS othercoverage,
                $1:contactpermitted::BOOLEAN AS contactpermitted,
                $1:assignmentdate::TIMESTAMP_TZ AS assignmentdate,
                $1:assignmentstatus::NUMBER AS assignmentstatus,
                $1:workerpayer_icare::NUMBER AS workerpayer_icare,
                $1:currentsection38effdate_icare::TIMESTAMP_TZ AS currentsection38effdate_icare,
                $1:issection41eligible_icare::BOOLEAN AS issection41eligible_icare,
                $1:mbcd_ext::TIMESTAMP_TZ AS mbcd_ext,
                $1:iss59a7secsurgerytype_ext::BOOLEAN AS iss59a7secsurgerytype_ext,
                $1:iss59a3reinstatementwbtype_ext::BOOLEAN AS iss59a3reinstatementwbtype_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwcc', 'cc_exposure') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS exposure_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'coverageid',
                        'previousgroupid',
                        'incidentlimitreached',
                        'locked',
                        'assignedbyuserid',
                        'othercovgchoice',
                        'diagnosticcnsistnt',
                        'pipclaimagglimitreached',
                        'previousqueueid',
                        'updatetime',
                        'examinationdate',
                        'vocbenefitsid',
                        'losscategory',
                        'createuserid',
                        'compbenefitsid',
                        'beanversion',
                        'lifepensionbenefitsid',
                        'reopendate',
                        'averageweeklywages',
                        'progress',
                        'updateuserid',
                        'segment',
                        'lastdayworked',
                        'depreciatedvalue',
                        'ssbenefit',
                        'ppdbenefitsid',
                        'tpdbenefitsid',
                        'publicid',
                        'securitylevel',
                        'deathbenefitsid',
                        'wcbenefit',
                        'assignedgroupid',
                        'fatalityinterest_icare',
                        'supplementalworkloadweight',
                        'wcpreexdisblty',
                        'claimid',
                        'assignedqueueid',
                        'metriclimitgeneration',
                        'statlineid',
                        'workloadupdated',
                        'breakin',
                        'templocationid',
                        'closedoutcome',
                        'archivepartition',
                        'exposuretier',
                        'isoreceivedate',
                        'incidentid',
                        'newempdataid',
                        'wagebenefit',
                        'strategy',
                        'assigneduserid',
                        'settledate',
                        'ssdibenefitsid',
                        'loadcommandid',
                        'wccdate_icare',
                        'wcpreexdisbltyinfo',
                        'treatedpatientbfr',
                        'priorempdataid',
                        'existingweeklybenefits_icare',
                        'wagestmtsent',
                        'pippersonagglimitreached',
                        'state',
                        'hospitaldays',
                        'coveragesubtype',
                        'claimorder',
                        'replacementvalue',
                        'reopenedreason',
                        'lossparty',
                        'wcbenefitsid',
                        'othercoverageinfo',
                        'closedate',
                        'retired',
                        'validationlevel',
                        'workloadweight',
                        'daysinweek',
                        'jurisdictionstate',
                        'lostpropertytype',
                        'isostatus',
                        'ptdbenefitsid',
                        'isosenddate',
                        'ttdbenefitsid',
                        'ssdieligible',
                        'exposurelimitreached',
                        'exposuretype',
                        'pipnonmedagglimitreached',
                        'claimantdenormid',
                        'wagestmtrecd',
                        'pipesslimitreached',
                        'riagreementgroupid',
                        'createtime',
                        'futurecowearnings_icare',
                        'rigroupsetexternally',
                        'furthertreatment',
                        'pipdeathbenefitsid',
                        'rsbenefitsid',
                        'previoususerid',
                        'isoknown',
                        'surgerydate_icare',
                        'excessrecoveryamount',
                        'claimanttype',
                        'disbenefitsid',
                        'hospitaldate',
                        'primarycoverage',
                        'pipvocbenefitsid',
                        'settlemethod',
                        'currentconditions',
                        'othercoverage',
                        'contactpermitted',
                        'assignmentdate',
                        'assignmentstatus',
                        'workerpayer_icare',
                        'currentsection38effdate_icare',
                        'issection41eligible_icare',
                        'mbcd_ext',
                        'iss59a7secsurgerytype_ext',
                        'iss59a3reinstatementwbtype_ext'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) as record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}