{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for cc_incident.
                                                incident_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["raw_layer", "raw_claim_centre", "claim_centre", "business_critical", "cc_incident"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:RecovInd::NUMBER AS recovind,
                data_payload:TotalLossPoints::NUMBER AS totallosspoints,
                data_payload:LocationInd::BOOLEAN AS locationind,
                data_payload:NumStories::NUMBER AS numstories,
                CAST(data_payload:BreakdownAgencyCode_icare::TEXT AS VARCHAR(255)) AS breakdownagencycode_icare,
                data_payload:AirbagsMissing::BOOLEAN AS airbagsmissing,
                data_payload:VehicleTitleRecvd::NUMBER AS vehicletitlerecvd,
                data_payload:CarrierCompensated::BOOLEAN AS carriercompensated,
                data_payload:ExtWallMat::NUMBER AS extwallmat,
                data_payload:FireBurnDash::BOOLEAN AS fireburndash,
                data_payload:GeneralInjuryType::NUMBER AS generalinjurytype,
                data_payload:FireProtectionAvailable::BOOLEAN AS fireprotectionavailable,
                data_payload:RecovClassType::NUMBER AS recovclasstype,
                data_payload:CreateUserID::NUMBER AS createuserid,
                data_payload:DriverRelation::NUMBER AS driverrelation,
                CAST(data_payload:RentalAgency::TEXT AS VARCHAR(25)) AS rentalagency,
                CAST(data_payload:SalvageProceeds AS NUMBER(18,2)) AS salvageproceeds,
                data_payload:DebrisRemovalInd::BOOLEAN AS debrisremovalind,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                data_payload:LossArea::NUMBER AS lossarea,
                data_payload:VehicleTitleReqd::NUMBER AS vehicletitlereqd,
                TO_TIMESTAMP_TZ(data_payload:AssessmentTargetCloseDate::NUMBER/1000) AS assessmenttargetclosedate,
                data_payload:FencesDamaged::BOOLEAN AS fencesdamaged,
                data_payload:BodyShopSelected::BOOLEAN AS bodyshopselected,
                CAST(data_payload:LossDesc::TEXT AS VARCHAR(30)) AS lossdesc,
                data_payload:VehicleParked::BOOLEAN AS vehicleparked,
                data_payload:FireBurnWindshield::BOOLEAN AS fireburnwindshield,
                data_payload:VehicleDriveable::BOOLEAN AS vehicledriveable,
                data_payload:EquipmentFailure::BOOLEAN AS equipmentfailure,
                data_payload:ReturnToWorkValid::BOOLEAN AS returntoworkvalid,
                data_payload:NumberOfPeopleOnPolicy::NUMBER AS numberofpeopleonpolicy,
                data_payload:ODGDuration_icare::NUMBER AS odgduration_icare,
                data_payload:RepairOption::NUMBER AS repairoption,
                data_payload:TripRUID::NUMBER AS tripruid,
                data_payload:DutyStatus_icare::NUMBER AS dutystatus_icare,
                data_payload:FloodSaltWater::BOOLEAN AS floodsaltwater,
                data_payload:Speed::NUMBER AS speed,
                CAST(data_payload:AssessmentName::TEXT AS VARCHAR(128)) AS assessmentname,
                data_payload:CitationIssued::NUMBER AS citationissued,
                CAST(data_payload:SalvagePrep AS NUMBER(18,2)) AS salvageprep,
                CAST(data_payload:SalvageTow AS NUMBER(18,2)) AS salvagetow,
                data_payload:ClaimID::NUMBER AS claimid,
                CAST(data_payload:Impairment AS NUMBER(4,1)) AS impairment,
                data_payload:MovePermission::BOOLEAN AS movepermission,
                TO_TIMESTAMP_TZ(data_payload:YearBuilt::NUMBER/1000) AS yearbuilt,
                data_payload:WaterLevelSeats::BOOLEAN AS waterlevelseats,
                data_payload:Mileage100K::BOOLEAN AS mileage100k,
                data_payload:VehicleType::NUMBER AS vehicletype,
                data_payload:TotalLoss::BOOLEAN AS totalloss,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                CAST(data_payload:StorageFclty::TEXT AS VARCHAR(30)) AS storagefclty,
                data_payload:BaggageType::NUMBER AS baggagetype,
                data_payload:RecovState::NUMBER AS recovstate,
                data_payload:AirbagsDeployed::BOOLEAN AS airbagsdeployed,
                data_payload:MinorOnPolicy::NUMBER AS minoronpolicy,
                data_payload:DriverRelToOwner::NUMBER AS driverreltoowner,
                data_payload:OdomRead::NUMBER AS odomread,
                data_payload:Extrication::BOOLEAN AS extrication,
                TO_TIMESTAMP_TZ(data_payload:FatalityLiabDecisionDate_icare::NUMBER/1000) AS fatalityliabdecisiondate_icare,
                data_payload:ReturnToModWorkActual::BOOLEAN AS returntomodworkactual,
                CAST(data_payload:SalvageNet AS NUMBER(18,2)) AS salvagenet,
                data_payload:IncludeContentLineItems::BOOLEAN AS includecontentlineitems,
                data_payload:LocationAddress::NUMBER AS locationaddress,
                data_payload:MultipleInjuries_icare::BOOLEAN AS multipleinjuries_icare,
                data_payload:IncludeLineItems::BOOLEAN AS includelineitems,
                TO_TIMESTAMP_TZ(data_payload:RecovDate::NUMBER/1000) AS recovdate,
                data_payload:HitAndRun::BOOLEAN AS hitandrun,
                CAST(data_payload:CarrierCompensatedAmount AS NUMBER(18,2)) AS carriercompensatedamount,
                data_payload:ClassType::NUMBER AS classtype,
                TO_TIMESTAMP_TZ(data_payload:ReturnToModWorkDate::NUMBER/1000) AS returntomodworkdate,
                data_payload:AntiThftInd::BOOLEAN AS antithftind,
                CAST(data_payload:StorageFeeAmt AS NUMBER(18,2)) AS storagefeeamt,
                data_payload:PercentageDrivenByMinor::NUMBER AS percentagedrivenbyminor,
                data_payload:MedicalTreatmentType::NUMBER AS medicaltreatmenttype,
                data_payload:RentalRequired::BOOLEAN AS rentalrequired,
                TO_TIMESTAMP_TZ(data_payload:BaggageMissingFrom::NUMBER/1000) AS baggagemissingfrom,
                data_payload:VehiclePolStatus::NUMBER AS vehiclepolstatus,
                data_payload:RecovCondType::NUMBER AS recovcondtype,
                data_payload:VehicleAge5Years::BOOLEAN AS vehicleage5years,
                CAST(data_payload:RentalReserveNo::TEXT AS VARCHAR(15)) AS rentalreserveno,
                data_payload:YearsInHome::NUMBER AS yearsinhome,
                data_payload:VehicleUseReason::NUMBER AS vehicleusereason,
                CAST(data_payload:EstRepairCost AS NUMBER(18,2)) AS estrepaircost,
                CAST(data_payload:VehicleLocation::TEXT AS VARCHAR(255)) AS vehiclelocation,
                TO_TIMESTAMP_TZ(data_payload:BaggageRecoveredOn::NUMBER/1000) AS baggagerecoveredon,
                data_payload:RecoveryLocationID::NUMBER AS recoverylocationid,
                data_payload:Appraisal::BOOLEAN AS appraisal,
                TO_TIMESTAMP_TZ(data_payload:ReturnToWorkDate::NUMBER/1000) AS returntoworkdate,
                CAST(data_payload:SalvageStorage AS NUMBER(18,2)) AS salvagestorage,
                data_payload:FatalityLiabDec_icare::NUMBER AS fatalityliabdec_icare,
                CAST(data_payload:SalvageCompany::TEXT AS VARCHAR(30)) AS salvagecompany,
                data_payload:AssessmentType::NUMBER AS assessmenttype,
                data_payload:Severity::NUMBER AS severity,
                data_payload:OwnerRetainingSalvage::BOOLEAN AS ownerretainingsalvage,
                CAST(data_payload:FireProtDetails::TEXT AS VARCHAR(1)) AS fireprotdetails,
                TO_TIMESTAMP_TZ(data_payload:DateVehicleRecovered::NUMBER/1000) AS datevehiclerecovered,
                data_payload:SprinkRetServ::NUMBER AS sprinkretserv,
                data_payload:OccupancyType::NUMBER AS occupancytype,
                TO_TIMESTAMP_TZ(data_payload:DateSalvageAssigned::NUMBER/1000) AS datesalvageassigned,
                data_payload:LossOccured::NUMBER AS lossoccured,
                data_payload:AlarmType::NUMBER AS alarmtype,
                data_payload:LossofUse::BOOLEAN AS lossofuse,
                data_payload:ClaimIncident::BOOLEAN AS claimincident,
                TO_TIMESTAMP_TZ(data_payload:StartDate::NUMBER/1000) AS startdate,
                CAST(data_payload:SalvageTitle AS NUMBER(18,2)) AS salvagetitle,
                data_payload:InspectionRequired::BOOLEAN AS inspectionrequired,
                TO_TIMESTAMP_TZ(data_payload:SignificantInjuryDate_icare::NUMBER/1000) AS significantinjurydate_icare,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:ID::NUMBER AS id,
                data_payload:VehLockInd::BOOLEAN AS vehlockind,
                CAST(data_payload:DescOther::TEXT AS VARCHAR(255)) AS descother,
                CAST(data_payload:AgencyOfInjuryDesc_icare::TEXT AS VARCHAR(255)) AS agencyofinjurydesc_icare,
                data_payload:InternalUserID::NUMBER AS internaluserid,
                TO_TIMESTAMP_TZ(data_payload:AssessmentCloseDate::NUMBER/1000) AS assessmentclosedate,
                data_payload:BeanVersion::NUMBER AS beanversion,
                CAST(data_payload:MaterialsDamaged::TEXT AS VARCHAR(250)) AS materialsdamaged,
                data_payload:EstimatesReceived::NUMBER AS estimatesreceived,
                data_payload:EstDamageType::NUMBER AS estdamagetype,
                data_payload:Collision::BOOLEAN AS collision,
                TO_TIMESTAMP_TZ(data_payload:RentalBeginDate::NUMBER/1000) AS rentalbegindate,
                data_payload:AssessmentStatus::NUMBER AS assessmentstatus,
                data_payload:EMSInd::BOOLEAN AS emsind,
                CAST(data_payload:NatureOfInjuryDesc_icare::TEXT AS VARCHAR(255)) AS natureofinjurydesc_icare,
                TO_TIMESTAMP_TZ(data_payload:ContactCompleteDate_icare::NUMBER/1000) AS contactcompletedate_icare,
                data_payload:AlreadyRepaired::BOOLEAN AS alreadyrepaired,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                data_payload:VehicleID::NUMBER AS vehicleid,
                CAST(data_payload:LossEstimate AS NUMBER(18,2)) AS lossestimate,
                data_payload:StorageAccrInd::NUMBER AS storageaccrind,
                data_payload:PropertySize::NUMBER AS propertysize,
                data_payload:HazardInvolved::NUMBER AS hazardinvolved,
                data_payload:AmbulanceUsed::BOOLEAN AS ambulanceused,
                CAST(data_payload:WhenToView::TEXT AS VARCHAR(255)) AS whentoview,
                CAST(data_payload:AssessmentComment::TEXT AS VARCHAR(255)) AS assessmentcomment,
                data_payload:VehicleAge10Years::BOOLEAN AS vehicleage10years,
                TO_TIMESTAMP_TZ(data_payload:RentalEndDate::NUMBER/1000) AS rentalenddate,
                data_payload:MealsDays::NUMBER AS mealsdays,
                TO_TIMESTAMP_TZ(data_payload:ODGRTWDate_icare::NUMBER/1000) AS odgrtwdate_icare,
                data_payload:RelatedTripRUID::NUMBER AS relatedtripruid,
                CAST(data_payload:MechanismOfInjuryDesc_icare::TEXT AS VARCHAR(255)) AS mechanismofinjurydesc_icare,
                data_payload:Subtype::NUMBER AS subtype,
                CAST(data_payload:AgencyOfInjuryCode_icare::TEXT AS VARCHAR(255)) AS agencyofinjurycode_icare,
                data_payload:RepWhereDisInd::BOOLEAN AS repwheredisind,
                data_payload:PhantomVehicle::BOOLEAN AS phantomvehicle,
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                data_payload:DisabledDueToAccident::NUMBER AS disabledduetoaccident,
                data_payload:FireBurnEngine::BOOLEAN AS fireburnengine,
                data_payload:ComponentsMissing::BOOLEAN AS componentsmissing,
                TO_TIMESTAMP_TZ(data_payload:DateVehicleSold::NUMBER/1000) AS datevehiclesold,
                TO_TIMESTAMP_TZ(data_payload:DeceasedDate_icare::NUMBER/1000) AS deceaseddate_icare,
                CAST(data_payload:NatureOfInjuryCode_icare::TEXT AS VARCHAR(255)) AS natureofinjurycode_icare,
                data_payload:VehTowedInd::BOOLEAN AS vehtowedind,
                data_payload:CollisionPoint::NUMBER AS collisionpoint,
                data_payload:MealsPeople::NUMBER AS mealspeople,
                CAST(data_payload:ExtDamagetxt::TEXT AS VARCHAR(289)) AS extdamagetxt,
                data_payload:NumSprinkler::NUMBER AS numsprinkler,
                data_payload:SprinklerType::NUMBER AS sprinklertype,
                data_payload:AffdvCmplInd::NUMBER AS affdvcmplind,
                data_payload:LostWages::BOOLEAN AS lostwages,
                data_payload:Retired::NUMBER AS retired,
                data_payload:DelayOnly::BOOLEAN AS delayonly,
                data_payload:PropertyID::NUMBER AS propertyid,
                CAST(data_payload:BreakdownAgencyDesc_icare::TEXT AS VARCHAR(255)) AS breakdownagencydesc_icare,
                data_payload:InteriorMissing::BOOLEAN AS interiormissing,
                data_payload:VehicleSubmerged::BOOLEAN AS vehiclesubmerged,
                data_payload:TrafficViolation::NUMBER AS trafficviolation,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                data_payload:ReturnToWorkActual::BOOLEAN AS returntoworkactual,
                CAST(data_payload:MechanismOfInjuryCode_icare::TEXT AS VARCHAR(255)) AS mechanismofinjurycode_icare,
                data_payload:VehicleDirection::NUMBER AS vehicledirection,
                TO_TIMESTAMP_TZ(data_payload:AppraisalFirstAppointment::NUMBER/1000) AS appraisalfirstappointment,
                data_payload:VehicleOperable::BOOLEAN AS vehicleoperable,
                CAST(data_payload:RentalDailyRate AS NUMBER(18,2)) AS rentaldailyrate,
                CAST(data_payload:LotNumber::TEXT AS VARCHAR(20)) AS lotnumber,
                data_payload:WaterLevelDash::BOOLEAN AS waterleveldash,
                data_payload:VehStolenInd::BOOLEAN AS vehstolenind,
                CAST(data_payload:EstRepairTime::TEXT AS VARCHAR(60)) AS estrepairtime,
                data_payload:MoldInvolved::NUMBER AS moldinvolved,
                data_payload:DetailedInjuryType::NUMBER AS detailedinjurytype,
                data_payload:DamagedAreaSize::NUMBER AS damagedareasize,
                data_payload:NumSprinkOper::NUMBER AS numsprinkoper,
                CAST(data_payload:PropertyDesc::TEXT AS VARCHAR(255)) AS propertydesc,
                CAST(data_payload:VehicleACV AS NUMBER(18,2)) AS vehicleacv,
                data_payload:ResultOfSelfHarm_icare::BOOLEAN AS resultofselfharm_icare,
                data_payload:OwnersPermission::BOOLEAN AS ownerspermission,
                CAST(data_payload:MealsRate AS NUMBER(18,2)) AS mealsrate,
                data_payload:ReturnToModWorkValid::BOOLEAN AS returntomodworkvalid,
                data_payload:VehCondType::NUMBER AS vehcondtype,
                data_payload:VehicleLossParty::NUMBER AS vehiclelossparty,
                data_payload:RoofMaterial::NUMBER AS roofmaterial,
                CAST(data_payload:Description::TEXT AS VARCHAR(1333)) AS description,
                data_payload:VehicleRollOver::BOOLEAN AS vehiclerollover,
                TO_TIMESTAMP_TZ(data_payload:FatalityNotificationDate_icare::NUMBER/1000) AS fatalitynotificationdate_icare,
                TO_TIMESTAMP_TZ(data_payload:LegacyUpdateTime_Ext::NUMBER/1000) AS legacyupdatetime_ext,
                TO_TIMESTAMP_TZ(data_payload:LegacyCreateTime_Ext::NUMBER/1000) AS legacycreatetime_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwcc', 'cc_incident') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:recovind::NUMBER AS recovind,
                $1:totallosspoints::NUMBER AS totallosspoints,
                $1:locationind::BOOLEAN AS locationind,
                $1:numstories::NUMBER AS numstories,
                CAST($1:breakdownagencycode_icare::TEXT AS VARCHAR(255)) AS breakdownagencycode_icare,
                $1:airbagsmissing::BOOLEAN AS airbagsmissing,
                $1:vehicletitlerecvd::NUMBER AS vehicletitlerecvd,
                $1:carriercompensated::BOOLEAN AS carriercompensated,
                $1:extwallmat::NUMBER AS extwallmat,
                $1:fireburndash::BOOLEAN AS fireburndash,
                $1:generalinjurytype::NUMBER AS generalinjurytype,
                $1:fireprotectionavailable::BOOLEAN AS fireprotectionavailable,
                $1:recovclasstype::NUMBER AS recovclasstype,
                $1:createuserid::NUMBER AS createuserid,
                $1:driverrelation::NUMBER AS driverrelation,
                CAST($1:rentalagency::TEXT AS VARCHAR(25)) AS rentalagency,
                CAST($1:salvageproceeds AS NUMBER(18,2)) AS salvageproceeds,
                $1:debrisremovalind::BOOLEAN AS debrisremovalind,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:lossarea::NUMBER AS lossarea,
                $1:vehicletitlereqd::NUMBER AS vehicletitlereqd,
                $1:assessmenttargetclosedate::TIMESTAMP_TZ AS assessmenttargetclosedate,
                $1:fencesdamaged::BOOLEAN AS fencesdamaged,
                $1:bodyshopselected::BOOLEAN AS bodyshopselected,
                CAST($1:lossdesc::TEXT AS VARCHAR(30)) AS lossdesc,
                $1:vehicleparked::BOOLEAN AS vehicleparked,
                $1:fireburnwindshield::BOOLEAN AS fireburnwindshield,
                $1:vehicledriveable::BOOLEAN AS vehicledriveable,
                $1:equipmentfailure::BOOLEAN AS equipmentfailure,
                $1:returntoworkvalid::BOOLEAN AS returntoworkvalid,
                $1:numberofpeopleonpolicy::NUMBER AS numberofpeopleonpolicy,
                $1:odgduration_icare::NUMBER AS odgduration_icare,
                $1:repairoption::NUMBER AS repairoption,
                $1:tripruid::NUMBER AS tripruid,
                $1:dutystatus_icare::NUMBER AS dutystatus_icare,
                $1:floodsaltwater::BOOLEAN AS floodsaltwater,
                $1:speed::NUMBER AS speed,
                CAST($1:assessmentname::TEXT AS VARCHAR(128)) AS assessmentname,
                $1:citationissued::NUMBER AS citationissued,
                CAST($1:salvageprep AS NUMBER(18,2)) AS salvageprep,
                CAST($1:salvagetow AS NUMBER(18,2)) AS salvagetow,
                $1:claimid::NUMBER AS claimid,
                CAST($1:impairment AS NUMBER(4,1)) AS impairment,
                $1:movepermission::BOOLEAN AS movepermission,
                $1:yearbuilt::TIMESTAMP_TZ AS yearbuilt,
                $1:waterlevelseats::BOOLEAN AS waterlevelseats,
                $1:mileage100k::BOOLEAN AS mileage100k,
                $1:vehicletype::NUMBER AS vehicletype,
                $1:totalloss::BOOLEAN AS totalloss,
                $1:archivepartition::NUMBER AS archivepartition,
                CAST($1:storagefclty::TEXT AS VARCHAR(30)) AS storagefclty,
                $1:baggagetype::NUMBER AS baggagetype,
                $1:recovstate::NUMBER AS recovstate,
                $1:airbagsdeployed::BOOLEAN AS airbagsdeployed,
                $1:minoronpolicy::NUMBER AS minoronpolicy,
                $1:driverreltoowner::NUMBER AS driverreltoowner,
                $1:odomread::NUMBER AS odomread,
                $1:extrication::BOOLEAN AS extrication,
                $1:fatalityliabdecisiondate_icare::TIMESTAMP_TZ AS fatalityliabdecisiondate_icare,
                $1:returntomodworkactual::BOOLEAN AS returntomodworkactual,
                CAST($1:salvagenet AS NUMBER(18,2)) AS salvagenet,
                $1:includecontentlineitems::BOOLEAN AS includecontentlineitems,
                $1:locationaddress::NUMBER AS locationaddress,
                $1:multipleinjuries_icare::BOOLEAN AS multipleinjuries_icare,
                $1:includelineitems::BOOLEAN AS includelineitems,
                $1:recovdate::TIMESTAMP_TZ AS recovdate,
                $1:hitandrun::BOOLEAN AS hitandrun,
                CAST($1:carriercompensatedamount AS NUMBER(18,2)) AS carriercompensatedamount,
                $1:classtype::NUMBER AS classtype,
                $1:returntomodworkdate::TIMESTAMP_TZ AS returntomodworkdate,
                $1:antithftind::BOOLEAN AS antithftind,
                CAST($1:storagefeeamt AS NUMBER(18,2)) AS storagefeeamt,
                $1:percentagedrivenbyminor::NUMBER AS percentagedrivenbyminor,
                $1:medicaltreatmenttype::NUMBER AS medicaltreatmenttype,
                $1:rentalrequired::BOOLEAN AS rentalrequired,
                $1:baggagemissingfrom::TIMESTAMP_TZ AS baggagemissingfrom,
                $1:vehiclepolstatus::NUMBER AS vehiclepolstatus,
                $1:recovcondtype::NUMBER AS recovcondtype,
                $1:vehicleage5years::BOOLEAN AS vehicleage5years,
                CAST($1:rentalreserveno::TEXT AS VARCHAR(15)) AS rentalreserveno,
                $1:yearsinhome::NUMBER AS yearsinhome,
                $1:vehicleusereason::NUMBER AS vehicleusereason,
                CAST($1:estrepaircost AS NUMBER(18,2)) AS estrepaircost,
                CAST($1:vehiclelocation::TEXT AS VARCHAR(255)) AS vehiclelocation,
                $1:baggagerecoveredon::TIMESTAMP_TZ AS baggagerecoveredon,
                $1:recoverylocationid::NUMBER AS recoverylocationid,
                $1:appraisal::BOOLEAN AS appraisal,
                $1:returntoworkdate::TIMESTAMP_TZ AS returntoworkdate,
                CAST($1:salvagestorage AS NUMBER(18,2)) AS salvagestorage,
                $1:fatalityliabdec_icare::NUMBER AS fatalityliabdec_icare,
                CAST($1:salvagecompany::TEXT AS VARCHAR(30)) AS salvagecompany,
                $1:assessmenttype::NUMBER AS assessmenttype,
                $1:severity::NUMBER AS severity,
                $1:ownerretainingsalvage::BOOLEAN AS ownerretainingsalvage,
                CAST($1:fireprotdetails::TEXT AS VARCHAR(1)) AS fireprotdetails,
                $1:datevehiclerecovered::TIMESTAMP_TZ AS datevehiclerecovered,
                $1:sprinkretserv::NUMBER AS sprinkretserv,
                $1:occupancytype::NUMBER AS occupancytype,
                $1:datesalvageassigned::TIMESTAMP_TZ AS datesalvageassigned,
                $1:lossoccured::NUMBER AS lossoccured,
                $1:alarmtype::NUMBER AS alarmtype,
                $1:lossofuse::BOOLEAN AS lossofuse,
                $1:claimincident::BOOLEAN AS claimincident,
                $1:startdate::TIMESTAMP_TZ AS startdate,
                CAST($1:salvagetitle AS NUMBER(18,2)) AS salvagetitle,
                $1:inspectionrequired::BOOLEAN AS inspectionrequired,
                $1:significantinjurydate_icare::TIMESTAMP_TZ AS significantinjurydate_icare,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:id::NUMBER AS id,
                $1:vehlockind::BOOLEAN AS vehlockind,
                CAST($1:descother::TEXT AS VARCHAR(255)) AS descother,
                CAST($1:agencyofinjurydesc_icare::TEXT AS VARCHAR(255)) AS agencyofinjurydesc_icare,
                $1:internaluserid::NUMBER AS internaluserid,
                $1:assessmentclosedate::TIMESTAMP_TZ AS assessmentclosedate,
                $1:beanversion::NUMBER AS beanversion,
                CAST($1:materialsdamaged::TEXT AS VARCHAR(250)) AS materialsdamaged,
                $1:estimatesreceived::NUMBER AS estimatesreceived,
                $1:estdamagetype::NUMBER AS estdamagetype,
                $1:collision::BOOLEAN AS collision,
                $1:rentalbegindate::TIMESTAMP_TZ AS rentalbegindate,
                $1:assessmentstatus::NUMBER AS assessmentstatus,
                $1:emsind::BOOLEAN AS emsind,
                CAST($1:natureofinjurydesc_icare::TEXT AS VARCHAR(255)) AS natureofinjurydesc_icare,
                $1:contactcompletedate_icare::TIMESTAMP_TZ AS contactcompletedate_icare,
                $1:alreadyrepaired::BOOLEAN AS alreadyrepaired,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:vehicleid::NUMBER AS vehicleid,
                CAST($1:lossestimate AS NUMBER(18,2)) AS lossestimate,
                $1:storageaccrind::NUMBER AS storageaccrind,
                $1:propertysize::NUMBER AS propertysize,
                $1:hazardinvolved::NUMBER AS hazardinvolved,
                $1:ambulanceused::BOOLEAN AS ambulanceused,
                CAST($1:whentoview::TEXT AS VARCHAR(255)) AS whentoview,
                CAST($1:assessmentcomment::TEXT AS VARCHAR(255)) AS assessmentcomment,
                $1:vehicleage10years::BOOLEAN AS vehicleage10years,
                $1:rentalenddate::TIMESTAMP_TZ AS rentalenddate,
                $1:mealsdays::NUMBER AS mealsdays,
                $1:odgrtwdate_icare::TIMESTAMP_TZ AS odgrtwdate_icare,
                $1:relatedtripruid::NUMBER AS relatedtripruid,
                CAST($1:mechanismofinjurydesc_icare::TEXT AS VARCHAR(255)) AS mechanismofinjurydesc_icare,
                $1:subtype::NUMBER AS subtype,
                CAST($1:agencyofinjurycode_icare::TEXT AS VARCHAR(255)) AS agencyofinjurycode_icare,
                $1:repwheredisind::BOOLEAN AS repwheredisind,
                $1:phantomvehicle::BOOLEAN AS phantomvehicle,
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:disabledduetoaccident::NUMBER AS disabledduetoaccident,
                $1:fireburnengine::BOOLEAN AS fireburnengine,
                $1:componentsmissing::BOOLEAN AS componentsmissing,
                $1:datevehiclesold::TIMESTAMP_TZ AS datevehiclesold,
                $1:deceaseddate_icare::TIMESTAMP_TZ AS deceaseddate_icare,
                CAST($1:natureofinjurycode_icare::TEXT AS VARCHAR(255)) AS natureofinjurycode_icare,
                $1:vehtowedind::BOOLEAN AS vehtowedind,
                $1:collisionpoint::NUMBER AS collisionpoint,
                $1:mealspeople::NUMBER AS mealspeople,
                CAST($1:extdamagetxt::TEXT AS VARCHAR(289)) AS extdamagetxt,
                $1:numsprinkler::NUMBER AS numsprinkler,
                $1:sprinklertype::NUMBER AS sprinklertype,
                $1:affdvcmplind::NUMBER AS affdvcmplind,
                $1:lostwages::BOOLEAN AS lostwages,
                $1:retired::NUMBER AS retired,
                $1:delayonly::BOOLEAN AS delayonly,
                $1:propertyid::NUMBER AS propertyid,
                CAST($1:breakdownagencydesc_icare::TEXT AS VARCHAR(255)) AS breakdownagencydesc_icare,
                $1:interiormissing::BOOLEAN AS interiormissing,
                $1:vehiclesubmerged::BOOLEAN AS vehiclesubmerged,
                $1:trafficviolation::NUMBER AS trafficviolation,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:returntoworkactual::BOOLEAN AS returntoworkactual,
                CAST($1:mechanismofinjurycode_icare::TEXT AS VARCHAR(255)) AS mechanismofinjurycode_icare,
                $1:vehicledirection::NUMBER AS vehicledirection,
                $1:appraisalfirstappointment::TIMESTAMP_TZ AS appraisalfirstappointment,
                $1:vehicleoperable::BOOLEAN AS vehicleoperable,
                CAST($1:rentaldailyrate AS NUMBER(18,2)) AS rentaldailyrate,
                CAST($1:lotnumber::TEXT AS VARCHAR(20)) AS lotnumber,
                $1:waterleveldash::BOOLEAN AS waterleveldash,
                $1:vehstolenind::BOOLEAN AS vehstolenind,
                CAST($1:estrepairtime::TEXT AS VARCHAR(60)) AS estrepairtime,
                $1:moldinvolved::NUMBER AS moldinvolved,
                $1:detailedinjurytype::NUMBER AS detailedinjurytype,
                $1:damagedareasize::NUMBER AS damagedareasize,
                $1:numsprinkoper::NUMBER AS numsprinkoper,
                CAST($1:propertydesc::TEXT AS VARCHAR(255)) AS propertydesc,
                CAST($1:vehicleacv AS NUMBER(18,2)) AS vehicleacv,
                $1:resultofselfharm_icare::BOOLEAN AS resultofselfharm_icare,
                $1:ownerspermission::BOOLEAN AS ownerspermission,
                CAST($1:mealsrate AS NUMBER(18,2)) AS mealsrate,
                $1:returntomodworkvalid::BOOLEAN AS returntomodworkvalid,
                $1:vehcondtype::NUMBER AS vehcondtype,
                $1:vehiclelossparty::NUMBER AS vehiclelossparty,
                $1:roofmaterial::NUMBER AS roofmaterial,
                CAST($1:description::TEXT AS VARCHAR(1333)) AS description,
                $1:vehiclerollover::BOOLEAN AS vehiclerollover,
                $1:fatalitynotificationdate_icare::TIMESTAMP_TZ AS fatalitynotificationdate_icare,
                $1:legacyupdatetime_ext::TIMESTAMP_TZ AS legacyupdatetime_ext,
                $1:legacycreatetime_ext::TIMESTAMP_TZ AS legacycreatetime_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwcc', 'cc_incident') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS incident_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'recovind',
                        'totallosspoints',
                        'locationind',
                        'numstories',
                        'breakdownagencycode_icare',
                        'airbagsmissing',
                        'vehicletitlerecvd',
                        'carriercompensated',
                        'extwallmat',
                        'fireburndash',
                        'generalinjurytype',
                        'fireprotectionavailable',
                        'recovclasstype',
                        'createuserid',
                        'driverrelation',
                        'rentalagency',
                        'salvageproceeds',
                        'debrisremovalind',
                        'updateuserid',
                        'lossarea',
                        'vehicletitlereqd',
                        'assessmenttargetclosedate',
                        'fencesdamaged',
                        'bodyshopselected',
                        'lossdesc',
                        'vehicleparked',
                        'fireburnwindshield',
                        'vehicledriveable',
                        'equipmentfailure',
                        'returntoworkvalid',
                        'numberofpeopleonpolicy',
                        'odgduration_icare',
                        'repairoption',
                        'tripruid',
                        'dutystatus_icare',
                        'floodsaltwater',
                        'speed',
                        'assessmentname',
                        'citationissued',
                        'salvageprep',
                        'salvagetow',
                        'claimid',
                        'impairment',
                        'movepermission',
                        'yearbuilt',
                        'waterlevelseats',
                        'mileage100k',
                        'vehicletype',
                        'totalloss',
                        'archivepartition',
                        'storagefclty',
                        'baggagetype',
                        'recovstate',
                        'airbagsdeployed',
                        'minoronpolicy',
                        'driverreltoowner',
                        'odomread',
                        'extrication',
                        'fatalityliabdecisiondate_icare',
                        'returntomodworkactual',
                        'salvagenet',
                        'includecontentlineitems',
                        'locationaddress',
                        'multipleinjuries_icare',
                        'includelineitems',
                        'recovdate',
                        'hitandrun',
                        'carriercompensatedamount',
                        'classtype',
                        'returntomodworkdate',
                        'antithftind',
                        'storagefeeamt',
                        'percentagedrivenbyminor',
                        'medicaltreatmenttype',
                        'rentalrequired',
                        'baggagemissingfrom',
                        'vehiclepolstatus',
                        'recovcondtype',
                        'vehicleage5years',
                        'rentalreserveno',
                        'yearsinhome',
                        'vehicleusereason',
                        'estrepaircost',
                        'vehiclelocation',
                        'baggagerecoveredon',
                        'recoverylocationid',
                        'appraisal',
                        'returntoworkdate',
                        'salvagestorage',
                        'fatalityliabdec_icare',
                        'salvagecompany',
                        'assessmenttype',
                        'severity',
                        'ownerretainingsalvage',
                        'fireprotdetails',
                        'datevehiclerecovered',
                        'sprinkretserv',
                        'occupancytype',
                        'datesalvageassigned',
                        'lossoccured',
                        'alarmtype',
                        'lossofuse',
                        'claimincident',
                        'startdate',
                        'salvagetitle',
                        'inspectionrequired',
                        'significantinjurydate_icare',
                        'updatetime',
                        'vehlockind',
                        'descother',
                        'agencyofinjurydesc_icare',
                        'internaluserid',
                        'assessmentclosedate',
                        'beanversion',
                        'materialsdamaged',
                        'estimatesreceived',
                        'estdamagetype',
                        'collision',
                        'rentalbegindate',
                        'assessmentstatus',
                        'emsind',
                        'natureofinjurydesc_icare',
                        'contactcompletedate_icare',
                        'alreadyrepaired',
                        'publicid',
                        'vehicleid',
                        'lossestimate',
                        'storageaccrind',
                        'propertysize',
                        'hazardinvolved',
                        'ambulanceused',
                        'whentoview',
                        'assessmentcomment',
                        'vehicleage10years',
                        'rentalenddate',
                        'mealsdays',
                        'odgrtwdate_icare',
                        'relatedtripruid',
                        'mechanismofinjurydesc_icare',
                        'subtype',
                        'agencyofinjurycode_icare',
                        'repwheredisind',
                        'phantomvehicle',
                        'loadcommandid',
                        'disabledduetoaccident',
                        'fireburnengine',
                        'componentsmissing',
                        'datevehiclesold',
                        'deceaseddate_icare',
                        'natureofinjurycode_icare',
                        'vehtowedind',
                        'collisionpoint',
                        'mealspeople',
                        'extdamagetxt',
                        'numsprinkler',
                        'sprinklertype',
                        'affdvcmplind',
                        'lostwages',
                        'retired',
                        'delayonly',
                        'propertyid',
                        'breakdownagencydesc_icare',
                        'interiormissing',
                        'vehiclesubmerged',
                        'trafficviolation',
                        'createtime',
                        'returntoworkactual',
                        'mechanismofinjurycode_icare',
                        'vehicledirection',
                        'appraisalfirstappointment',
                        'vehicleoperable',
                        'rentaldailyrate',
                        'lotnumber',
                        'waterleveldash',
                        'vehstolenind',
                        'estrepairtime',
                        'moldinvolved',
                        'detailedinjurytype',
                        'damagedareasize',
                        'numsprinkoper',
                        'propertydesc',
                        'vehicleacv',
                        'resultofselfharm_icare',
                        'ownerspermission',
                        'mealsrate',
                        'returntomodworkvalid',
                        'vehcondtype',
                        'vehiclelossparty',
                        'roofmaterial',
                        'description',
                        'vehiclerollover',
                        'fatalitynotificationdate_icare',
                        'legacyupdatetime_ext',
                        'legacycreatetime_ext'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) as record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}