{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for cc_employmentdata.
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                record_insertion_date: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDA goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    incremental_strategy='append',
    on_schema_change='append_new_columns',
    tags=["landing", "gwcc", "claim_centre", "business_critical"]
) }}


WITH cte_source_data AS 
(

            SELECT
                CAST(data_payload:WageAmount AS NUMBER(18,2)) AS wageamount,
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                TO_TIMESTAMP_TZ(data_payload:VoluntaryReductionDate::NUMBER/1000) AS voluntaryreductiondate,
                CAST(data_payload:OvertimeRate AS NUMBER(18,2)) AS overtimerate,
                data_payload:LatestWorkStatusDenorm_icare::NUMBER AS latestworkstatusdenorm_icare,
                CAST(data_payload:WednesdayWorkHours_icare AS NUMBER(5,2)) AS wednesdayworkhours_icare,
                TO_TIMESTAMP_TZ(data_payload:ScheduledPayIncreaseDate_icare::NUMBER/1000) AS scheduledpayincreasedate_icare,
                CAST(data_payload:AccommodationBenefits_icare AS NUMBER(18,2)) AS accommodationbenefits_icare,
                CAST(data_payload:MondayWorkHours_icare AS NUMBER(5,2)) AS mondayworkhours_icare,
                CAST(data_payload:NumDaysWorked AS NUMBER(2,1)) AS numdaysworked,
                CAST(data_payload:MotorVehicleBenefits_icare AS NUMBER(18,2)) AS motorvehiclebenefits_icare,
                CAST(data_payload:SSBenefitsAmnt AS NUMBER(18,2)) AS ssbenefitsamnt,
                data_payload:WagePaymentCont::BOOLEAN AS wagepaymentcont,
                CAST(data_payload:EducationFeeBenefits_icare AS NUMBER(18,2)) AS educationfeebenefits_icare,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:ChangeEmployment_icare::BOOLEAN AS changeemployment_icare,
                CAST(data_payload:WageAmountPostInjury AS NUMBER(18,2)) AS wageamountpostinjury,
                data_payload:WorkTuesday_icare::BOOLEAN AS worktuesday_icare,
                TO_TIMESTAMP_TZ(data_payload:InjuryStartTime::NUMBER/1000) AS injurystarttime,
                data_payload:ID::NUMBER AS id,
                data_payload:SSBenefits::BOOLEAN AS ssbenefits,
                data_payload:WorkMonday_icare::BOOLEAN AS workmonday_icare,
                data_payload:HireState::NUMBER AS hirestate,
                TO_TIMESTAMP_TZ(data_payload:EmploymentEndDate::NUMBER/1000) AS employmentenddate,
                data_payload:FullTime78WeeksPriorInjury::BOOLEAN AS fulltime78weekspriorinjury,
                data_payload:WorkWednesday_icare::BOOLEAN AS workwednesday_icare,
                data_payload:IndustryCode_icareID::NUMBER AS industrycode_icareid,
                data_payload:CreateUserID::NUMBER AS createuserid,
                data_payload:WorkerPromoted::BOOLEAN AS workerpromoted,
                TO_TIMESTAMP_TZ(data_payload:HireDate::NUMBER/1000) AS hiredate,
                CAST(data_payload:WeekAvgOvertimeEarnings_icare AS NUMBER(18,2)) AS weekavgovertimeearnings_icare,
                data_payload:FirstDayPayCycle_icare::NUMBER AS firstdaypaycycle_icare,
                data_payload:WorkThursday_icare::BOOLEAN AS workthursday_icare,
                data_payload:BeanVersion::NUMBER AS beanversion,
                CAST(data_payload:ScndInjryFndAmnt AS NUMBER(18,2)) AS scndinjryfndamnt,
                data_payload:Retired::NUMBER AS retired,
                data_payload:WorkFriday_icare::BOOLEAN AS workfriday_icare,
                CAST(data_payload:TuesdayWorkHours_icare AS NUMBER(5,2)) AS tuesdayworkhours_icare,
                TO_TIMESTAMP_TZ(data_payload:TerminationDate_icare::NUMBER/1000) AS terminationdate_icare,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                CAST(data_payload:WeekAvgShiftAllowance_icare AS NUMBER(18,2)) AS weekavgshiftallowance_icare,
                TO_TIMESTAMP_TZ(data_payload:WorkerFuturePromotionDate::NUMBER/1000) AS workerfuturepromotiondate,
                TO_TIMESTAMP_TZ(data_payload:LastWorkedDate::NUMBER/1000) AS lastworkeddate,
                CAST(data_payload:HealthInsuranceBenefits_icare AS NUMBER(18,2)) AS healthinsurancebenefits_icare,
                data_payload:ScndInjryFnd::BOOLEAN AS scndinjryfnd,
                TO_TIMESTAMP_TZ(data_payload:AnniversaryDate_icare::NUMBER/1000) AS anniversarydate_icare,
                TO_TIMESTAMP_TZ(data_payload:EmploymentStatusChangeDate::NUMBER/1000) AS employmentstatuschangedate,
                CAST(data_payload:LastYearIncome AS NUMBER(18,2)) AS lastyearincome,
                CAST(data_payload:DepartmentCode::TEXT AS VARCHAR(60)) AS departmentcode,
                data_payload:ClassCodeID::NUMBER AS classcodeid,
                CAST(data_payload:SaturdayWorkHours_icare AS NUMBER(5,2)) AS saturdayworkhours_icare,
                CAST(data_payload:OtherNonMonetaryBenefits_icare AS NUMBER(18,2)) AS othernonmonetarybenefits_icare,
                data_payload:TerminationReason_icare::NUMBER AS terminationreason_icare,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                TO_TIMESTAMP_TZ(data_payload:WorkerPriorPromotionDate::NUMBER/1000) AS workerpriorpromotiondate,
                data_payload:WorkSaturday_icare::BOOLEAN AS worksaturday_icare,
                data_payload:SeekingFullTime::BOOLEAN AS seekingfulltime,
                data_payload:TrainingStatus_icare::NUMBER AS trainingstatus_icare,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                data_payload:AllowancesOvertEarnings_icare::BOOLEAN AS allowancesovertearnings_icare,
                CAST(data_payload:SundayWorkHours_icare AS NUMBER(5,2)) AS sundayworkhours_icare,
                CAST(data_payload:Occupation::TEXT AS VARCHAR(255)) AS occupation,
                data_payload:WorkplaceSize_icare::NUMBER AS workplacesize_icare,
                data_payload:VoluntaryReduction::BOOLEAN AS voluntaryreduction,
                data_payload:ClaimID::NUMBER AS claimid,
                CAST(data_payload:FairWorkInstrument_icare::TEXT AS VARCHAR(120)) AS fairworkinstrument_icare,
                CAST(data_payload:FridayWorkHours_icare AS NUMBER(5,2)) AS fridayworkhours_icare,
                data_payload:WorkerDuePromoted::BOOLEAN AS workerduepromoted,
                data_payload:PaidFull::BOOLEAN AS paidfull,
                data_payload:WorkSunday_icare::BOOLEAN AS worksunday_icare,
                data_payload:EmploymentStatus::NUMBER AS employmentstatus,
                TO_TIMESTAMP_TZ(data_payload:ScndInjryFndDate::NUMBER/1000) AS scndinjryfnddate,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                data_payload:PayPeriod::NUMBER AS payperiod,
                data_payload:PaymentsAligntoPayCycle_icare::BOOLEAN AS paymentsaligntopaycycle_icare,
                CAST(data_payload:HoursWorkedWeek_icare AS NUMBER(5,2)) AS hoursworkedweek_icare,
                CAST(data_payload:NumHoursWorked AS NUMBER(5,2)) AS numhoursworked,
                CAST(data_payload:DaysWorkedWeek::TEXT AS VARCHAR(255)) AS daysworkedweek,
                CAST(data_payload:ThursdayWorkHours_icare AS NUMBER(5,2)) AS thursdayworkhours_icare,
                TO_TIMESTAMP_TZ(data_payload:MVWithDrawnDate_icare::NUMBER/1000) AS mvwithdrawndate_icare,
                TO_TIMESTAMP_TZ(data_payload:EFWithDrawnDate_icare::NUMBER/1000) AS efwithdrawndate_icare,
                TO_TIMESTAMP_TZ(data_payload:AccWithDrawnDate_icare::NUMBER/1000) AS accwithdrawndate_icare,
                TO_TIMESTAMP_TZ(data_payload:HIWithDrawnDate_icare::NUMBER/1000) AS hiwithdrawndate_icare,
                TO_TIMESTAMP_TZ(data_payload:OtherWithDrawnDate_icare::NUMBER/1000) AS otherwithdrawndate_icare,
                data_payload:MVWithDrawnFlag_icare::BOOLEAN AS mvwithdrawnflag_icare,
                data_payload:EFWithDrawnFlag_icare::BOOLEAN AS efwithdrawnflag_icare,
                data_payload:SignedAgreementFlag_icare::BOOLEAN AS signedagreementflag_icare,
                data_payload:AccWithDrawnFlag_icare::BOOLEAN AS accwithdrawnflag_icare,
                data_payload:HIWithDrawnFlag_icare::BOOLEAN AS hiwithdrawnflag_icare,
                data_payload:UnpaidLeaveInLast52Weeks_icare::BOOLEAN AS unpaidleaveinlast52weeks_icare,
                data_payload:OtherWithDrawnFlag_icare::BOOLEAN AS otherwithdrawnflag_icare,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS VARCHAR(300)) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'AVRO' as file_type,
                'GWCC' as source_system
            FROM {{ source('gwcc', 'cc_employmentdata') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                CAST($1:wageamount AS NUMBER(18,2)) AS wageamount,
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:voluntaryreductiondate::TIMESTAMP_TZ AS voluntaryreductiondate,
                CAST($1:overtimerate AS NUMBER(18,2)) AS overtimerate,
                $1:latestworkstatusdenorm_icare::NUMBER AS latestworkstatusdenorm_icare,
                CAST($1:wednesdayworkhours_icare AS NUMBER(5,2)) AS wednesdayworkhours_icare,
                $1:scheduledpayincreasedate_icare::TIMESTAMP_TZ AS scheduledpayincreasedate_icare,
                CAST($1:accommodationbenefits_icare AS NUMBER(18,2)) AS accommodationbenefits_icare,
                CAST($1:mondayworkhours_icare AS NUMBER(5,2)) AS mondayworkhours_icare,
                CAST($1:numdaysworked AS NUMBER(2,1)) AS numdaysworked,
                CAST($1:motorvehiclebenefits_icare AS NUMBER(18,2)) AS motorvehiclebenefits_icare,
                CAST($1:ssbenefitsamnt AS NUMBER(18,2)) AS ssbenefitsamnt,
                $1:wagepaymentcont::BOOLEAN AS wagepaymentcont,
                CAST($1:educationfeebenefits_icare AS NUMBER(18,2)) AS educationfeebenefits_icare,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:changeemployment_icare::BOOLEAN AS changeemployment_icare,
                CAST($1:wageamountpostinjury AS NUMBER(18,2)) AS wageamountpostinjury,
                $1:worktuesday_icare::BOOLEAN AS worktuesday_icare,
                $1:injurystarttime::TIMESTAMP_TZ AS injurystarttime,
                $1:id::NUMBER AS id,
                $1:ssbenefits::BOOLEAN AS ssbenefits,
                $1:workmonday_icare::BOOLEAN AS workmonday_icare,
                $1:hirestate::NUMBER AS hirestate,
                $1:employmentenddate::TIMESTAMP_TZ AS employmentenddate,
                $1:fulltime78weekspriorinjury::BOOLEAN AS fulltime78weekspriorinjury,
                $1:workwednesday_icare::BOOLEAN AS workwednesday_icare,
                $1:industrycode_icareid::NUMBER AS industrycode_icareid,
                $1:createuserid::NUMBER AS createuserid,
                $1:workerpromoted::BOOLEAN AS workerpromoted,
                $1:hiredate::TIMESTAMP_TZ AS hiredate,
                CAST($1:weekavgovertimeearnings_icare AS NUMBER(18,2)) AS weekavgovertimeearnings_icare,
                $1:firstdaypaycycle_icare::NUMBER AS firstdaypaycycle_icare,
                $1:workthursday_icare::BOOLEAN AS workthursday_icare,
                $1:beanversion::NUMBER AS beanversion,
                CAST($1:scndinjryfndamnt AS NUMBER(18,2)) AS scndinjryfndamnt,
                $1:retired::NUMBER AS retired,
                $1:workfriday_icare::BOOLEAN AS workfriday_icare,
                CAST($1:tuesdayworkhours_icare AS NUMBER(5,2)) AS tuesdayworkhours_icare,
                $1:terminationdate_icare::TIMESTAMP_TZ AS terminationdate_icare,
                $1:updateuserid::NUMBER AS updateuserid,
                CAST($1:weekavgshiftallowance_icare AS NUMBER(18,2)) AS weekavgshiftallowance_icare,
                $1:workerfuturepromotiondate::TIMESTAMP_TZ AS workerfuturepromotiondate,
                $1:lastworkeddate::TIMESTAMP_TZ AS lastworkeddate,
                CAST($1:healthinsurancebenefits_icare AS NUMBER(18,2)) AS healthinsurancebenefits_icare,
                $1:scndinjryfnd::BOOLEAN AS scndinjryfnd,
                $1:anniversarydate_icare::TIMESTAMP_TZ AS anniversarydate_icare,
                $1:employmentstatuschangedate::TIMESTAMP_TZ AS employmentstatuschangedate,
                CAST($1:lastyearincome AS NUMBER(18,2)) AS lastyearincome,
                CAST($1:departmentcode::TEXT AS VARCHAR(60)) AS departmentcode,
                $1:classcodeid::NUMBER AS classcodeid,
                CAST($1:saturdayworkhours_icare AS NUMBER(5,2)) AS saturdayworkhours_icare,
                CAST($1:othernonmonetarybenefits_icare AS NUMBER(18,2)) AS othernonmonetarybenefits_icare,
                $1:terminationreason_icare::NUMBER AS terminationreason_icare,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:workerpriorpromotiondate::TIMESTAMP_TZ AS workerpriorpromotiondate,
                $1:worksaturday_icare::BOOLEAN AS worksaturday_icare,
                $1:seekingfulltime::BOOLEAN AS seekingfulltime,
                $1:trainingstatus_icare::NUMBER AS trainingstatus_icare,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:allowancesovertearnings_icare::BOOLEAN AS allowancesovertearnings_icare,
                CAST($1:sundayworkhours_icare AS NUMBER(5,2)) AS sundayworkhours_icare,
                CAST($1:occupation::TEXT AS VARCHAR(255)) AS occupation,
                $1:workplacesize_icare::NUMBER AS workplacesize_icare,
                $1:voluntaryreduction::BOOLEAN AS voluntaryreduction,
                $1:claimid::NUMBER AS claimid,
                CAST($1:fairworkinstrument_icare::TEXT AS VARCHAR(120)) AS fairworkinstrument_icare,
                CAST($1:fridayworkhours_icare AS NUMBER(5,2)) AS fridayworkhours_icare,
                $1:workerduepromoted::BOOLEAN AS workerduepromoted,
                $1:paidfull::BOOLEAN AS paidfull,
                $1:worksunday_icare::BOOLEAN AS worksunday_icare,
                $1:employmentstatus::NUMBER AS employmentstatus,
                $1:scndinjryfnddate::TIMESTAMP_TZ AS scndinjryfnddate,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:payperiod::NUMBER AS payperiod,
                $1:paymentsaligntopaycycle_icare::BOOLEAN AS paymentsaligntopaycycle_icare,
                CAST($1:hoursworkedweek_icare AS NUMBER(5,2)) AS hoursworkedweek_icare,
                CAST($1:numhoursworked AS NUMBER(5,2)) AS numhoursworked,
                CAST($1:daysworkedweek::TEXT AS VARCHAR(255)) AS daysworkedweek,
                CAST($1:thursdayworkhours_icare AS NUMBER(5,2)) AS thursdayworkhours_icare,
                $1:mvwithdrawndate_icare::TIMESTAMP_TZ AS mvwithdrawndate_icare,
                $1:efwithdrawndate_icare::TIMESTAMP_TZ AS efwithdrawndate_icare,
                $1:accwithdrawndate_icare::TIMESTAMP_TZ AS accwithdrawndate_icare,
                $1:hiwithdrawndate_icare::TIMESTAMP_TZ AS hiwithdrawndate_icare,
                $1:otherwithdrawndate_icare::TIMESTAMP_TZ AS otherwithdrawndate_icare,
                $1:mvwithdrawnflag_icare::BOOLEAN AS mvwithdrawnflag_icare,
                $1:efwithdrawnflag_icare::BOOLEAN AS efwithdrawnflag_icare,
                $1:signedagreementflag_icare::BOOLEAN AS signedagreementflag_icare,
                $1:accwithdrawnflag_icare::BOOLEAN AS accwithdrawnflag_icare,
                $1:hiwithdrawnflag_icare::BOOLEAN AS hiwithdrawnflag_icare,
                $1:unpaidleaveinlast52weeks_icare::BOOLEAN AS unpaidleaveinlast52weeks_icare,
                $1:otherwithdrawnflag_icare::BOOLEAN AS otherwithdrawnflag_icare,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::VARCHAR(300) as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'PARQUET' as file_type,
                'GWCC' as source_system
            FROM {{ source('gwcc', 'cc_employmentdata') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS employmentdata_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'wageamount',
                        'loadcommandid',
                        'voluntaryreductiondate',
                        'overtimerate',
                        'latestworkstatusdenorm_icare',
                        'wednesdayworkhours_icare',
                        'scheduledpayincreasedate_icare',
                        'accommodationbenefits_icare',
                        'mondayworkhours_icare',
                        'numdaysworked',
                        'motorvehiclebenefits_icare',
                        'ssbenefitsamnt',
                        'wagepaymentcont',
                        'educationfeebenefits_icare',
                        'updatetime',
                        'changeemployment_icare',
                        'wageamountpostinjury',
                        'worktuesday_icare',
                        'injurystarttime',
                        'ssbenefits',
                        'workmonday_icare',
                        'hirestate',
                        'employmentenddate',
                        'fulltime78weekspriorinjury',
                        'workwednesday_icare',
                        'industrycode_icareid',
                        'createuserid',
                        'workerpromoted',
                        'hiredate',
                        'weekavgovertimeearnings_icare',
                        'firstdaypaycycle_icare',
                        'workthursday_icare',
                        'beanversion',
                        'scndinjryfndamnt',
                        'retired',
                        'workfriday_icare',
                        'tuesdayworkhours_icare',
                        'terminationdate_icare',
                        'updateuserid',
                        'weekavgshiftallowance_icare',
                        'workerfuturepromotiondate',
                        'lastworkeddate',
                        'healthinsurancebenefits_icare',
                        'scndinjryfnd',
                        'anniversarydate_icare',
                        'employmentstatuschangedate',
                        'lastyearincome',
                        'departmentcode',
                        'classcodeid',
                        'saturdayworkhours_icare',
                        'othernonmonetarybenefits_icare',
                        'terminationreason_icare',
                        'publicid',
                        'workerpriorpromotiondate',
                        'worksaturday_icare',
                        'seekingfulltime',
                        'trainingstatus_icare',
                        'createtime',
                        'allowancesovertearnings_icare',
                        'sundayworkhours_icare',
                        'occupation',
                        'workplacesize_icare',
                        'voluntaryreduction',
                        'claimid',
                        'fairworkinstrument_icare',
                        'fridayworkhours_icare',
                        'workerduepromoted',
                        'paidfull',
                        'worksunday_icare',
                        'employmentstatus',
                        'scndinjryfnddate',
                        'archivepartition',
                        'payperiod',
                        'paymentsaligntopaycycle_icare',
                        'hoursworkedweek_icare',
                        'numhoursworked',
                        'daysworkedweek',
                        'thursdayworkhours_icare',
                        'mvwithdrawndate_icare',
                        'efwithdrawndate_icare',
                        'accwithdrawndate_icare',
                        'hiwithdrawndate_icare',
                        'otherwithdrawndate_icare',
                        'mvwithdrawnflag_icare',
                        'efwithdrawnflag_icare',
                        'signedagreementflag_icare',
                        'accwithdrawnflag_icare',
                        'hiwithdrawnflag_icare',
                        'unpaidleaveinlast52weeks_icare',
                        'otherwithdrawnflag_icare'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
    WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}
    ORDER BY record_insertion_date
