{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for ccx_wcdinternalreview_icare.
                                                wcdinternalreview_icare_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["landing", "gwcc", "claim_centre", "business_critical", "ccx_wcdinternalreview_icare"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                data_payload:ReviewDetailsID::NUMBER AS reviewdetailsid,
                data_payload:AssessedAsIndefinitelyUnable::BOOLEAN AS assessedasindefinitelyunable,
                CAST(data_payload:OutcomeReasoning::TEXT AS VARCHAR(16777216)) AS outcomereasoning,
                data_payload:SolicitorID::NUMBER AS solicitorid,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:NewWCDRequired::BOOLEAN AS newwcdrequired,
                data_payload:ID::NUMBER AS id,
                data_payload:FairNoticeRequired::BOOLEAN AS fairnoticerequired,
                CAST(data_payload:Reasoning::TEXT AS VARCHAR(16777216)) AS reasoning,
                data_payload:CreateUserID::NUMBER AS createuserid,
                CAST(data_payload:Working15HourPerWeekText::TEXT AS VARCHAR(255)) AS working15hourperweektext,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:Retired::NUMBER AS retired,
                TO_TIMESTAMP_TZ(data_payload:DecisionIssueDate::NUMBER/1000) AS decisionissuedate,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                data_payload:FurtherInfoImpactsDecision::BOOLEAN AS furtherinfoimpactsdecision,
                data_payload:StayApplicable::BOOLEAN AS stayapplicable,
                TO_TIMESTAMP_TZ(data_payload:DateApplicationReceived::NUMBER/1000) AS dateapplicationreceived,
                data_payload:Section38Eligibility::BOOLEAN AS section38eligibility,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                TO_TIMESTAMP_TZ(data_payload:InternalReviewCompletedDate::NUMBER/1000) AS internalreviewcompleteddate,
                data_payload:EarningPerWeek::BOOLEAN AS earningperweek,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                TO_TIMESTAMP_TZ(data_payload:ReviewDueDate::NUMBER/1000) AS reviewduedate,
                data_payload:WPIPercentage::NUMBER AS wpipercentage,
                data_payload:ApplicationLodgedBy::NUMBER AS applicationlodgedby,
                TO_TIMESTAMP_TZ(data_payload:AcknowledgementLetterDate::NUMBER/1000) AS acknowledgementletterdate,
                CAST(data_payload:AssessedAsUnableText::TEXT AS VARCHAR(255)) AS assessedasunabletext,
                data_payload:EarningsE::NUMBER AS earningse,
                data_payload:ReviewerID::NUMBER AS reviewerid,
                data_payload:MedEntitlement::NUMBER AS medentitlement,
                data_payload:Section38Eligible::BOOLEAN AS section38eligible,
                CAST(data_payload:EarningsCapacity AS NUMBER(18,2)) AS earningscapacity,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                TO_TIMESTAMP_TZ(data_payload:EligibilityEffectiveDate::NUMBER/1000) AS eligibilityeffectivedate,
                data_payload:FurtherInfoSubmitted::BOOLEAN AS furtherinfosubmitted,
                data_payload:Section54StillActive::BOOLEAN AS section54stillactive,
                data_payload:WeeklyPaymentImpact::NUMBER AS weeklypaymentimpact,
                data_payload:AssessedHours::NUMBER AS assessedhours,
                data_payload:DraftDecisionCompleted::BOOLEAN AS draftdecisioncompleted,
                TO_TIMESTAMP_TZ(data_payload:ResponseDate::NUMBER/1000) AS responsedate,
                CAST(data_payload:EarningPerWeekText::TEXT AS VARCHAR(255)) AS earningperweektext,
                data_payload:ReviewRequestedWithin30Days::BOOLEAN AS reviewrequestedwithin30days,
                data_payload:FollowUpFlag::BOOLEAN AS followupflag,
                data_payload:Working15HourPerWeek::BOOLEAN AS working15hourperweek,
                CAST(data_payload:CaseNumber::TEXT AS VARCHAR(255)) AS casenumber,
                TO_TIMESTAMP_TZ(data_payload:DecisionEffectiveDate::NUMBER/1000) AS decisioneffectivedate,
                data_payload:ReviewOutcome::NUMBER AS reviewoutcome,
                TO_TIMESTAMP_TZ(data_payload:StayExpiryDate::NUMBER/1000) AS stayexpirydate,
                data_payload:SectionS80StillActive::BOOLEAN AS sections80stillactive,
                CAST(data_payload:PIAWE AS NUMBER(18,2)) AS piawe,
                data_payload:WithinS80NoticePeriod::BOOLEAN AS withins80noticeperiod,
                data_payload:InternalReviewStatus::NUMBER AS internalreviewstatus,
                TO_TIMESTAMP_TZ(data_payload:DecisionEndDate_Ext::NUMBER/1000) AS decisionenddate_ext,
                CAST(data_payload:CWWRSuitableEmployment AS NUMBER(18,2)) AS cwwrsuitableemployment,
                data_payload:DiscretionaryEntitlement::NUMBER AS discretionaryentitlement,
                CAST(data_payload:AbilityToEarn AS NUMBER(18,2)) AS abilitytoearn,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwcc', 'ccx_wcdinternalreview_icare') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:reviewdetailsid::NUMBER AS reviewdetailsid,
                $1:assessedasindefinitelyunable::BOOLEAN AS assessedasindefinitelyunable,
                CAST($1:outcomereasoning::TEXT AS VARCHAR(16777216)) AS outcomereasoning,
                $1:solicitorid::NUMBER AS solicitorid,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:newwcdrequired::BOOLEAN AS newwcdrequired,
                $1:id::NUMBER AS id,
                $1:fairnoticerequired::BOOLEAN AS fairnoticerequired,
                CAST($1:reasoning::TEXT AS VARCHAR(16777216)) AS reasoning,
                $1:createuserid::NUMBER AS createuserid,
                CAST($1:working15hourperweektext::TEXT AS VARCHAR(255)) AS working15hourperweektext,
                $1:beanversion::NUMBER AS beanversion,
                $1:retired::NUMBER AS retired,
                $1:decisionissuedate::TIMESTAMP_TZ AS decisionissuedate,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:furtherinfoimpactsdecision::BOOLEAN AS furtherinfoimpactsdecision,
                $1:stayapplicable::BOOLEAN AS stayapplicable,
                $1:dateapplicationreceived::TIMESTAMP_TZ AS dateapplicationreceived,
                $1:section38eligibility::BOOLEAN AS section38eligibility,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:internalreviewcompleteddate::TIMESTAMP_TZ AS internalreviewcompleteddate,
                $1:earningperweek::BOOLEAN AS earningperweek,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:reviewduedate::TIMESTAMP_TZ AS reviewduedate,
                $1:wpipercentage::NUMBER AS wpipercentage,
                $1:applicationlodgedby::NUMBER AS applicationlodgedby,
                $1:acknowledgementletterdate::TIMESTAMP_TZ AS acknowledgementletterdate,
                CAST($1:assessedasunabletext::TEXT AS VARCHAR(255)) AS assessedasunabletext,
                $1:earningse::NUMBER AS earningse,
                $1:reviewerid::NUMBER AS reviewerid,
                $1:medentitlement::NUMBER AS medentitlement,
                $1:section38eligible::BOOLEAN AS section38eligible,
                CAST($1:earningscapacity AS NUMBER(18,2)) AS earningscapacity,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:eligibilityeffectivedate::TIMESTAMP_TZ AS eligibilityeffectivedate,
                $1:furtherinfosubmitted::BOOLEAN AS furtherinfosubmitted,
                $1:section54stillactive::BOOLEAN AS section54stillactive,
                $1:weeklypaymentimpact::NUMBER AS weeklypaymentimpact,
                $1:assessedhours::NUMBER AS assessedhours,
                $1:draftdecisioncompleted::BOOLEAN AS draftdecisioncompleted,
                $1:responsedate::TIMESTAMP_TZ AS responsedate,
                CAST($1:earningperweektext::TEXT AS VARCHAR(255)) AS earningperweektext,
                $1:reviewrequestedwithin30days::BOOLEAN AS reviewrequestedwithin30days,
                $1:followupflag::BOOLEAN AS followupflag,
                $1:working15hourperweek::BOOLEAN AS working15hourperweek,
                CAST($1:casenumber::TEXT AS VARCHAR(255)) AS casenumber,
                $1:decisioneffectivedate::TIMESTAMP_TZ AS decisioneffectivedate,
                $1:reviewoutcome::NUMBER AS reviewoutcome,
                $1:stayexpirydate::TIMESTAMP_TZ AS stayexpirydate,
                $1:sections80stillactive::BOOLEAN AS sections80stillactive,
                CAST($1:piawe AS NUMBER(18,2)) AS piawe,
                $1:withins80noticeperiod::BOOLEAN AS withins80noticeperiod,
                $1:internalreviewstatus::NUMBER AS internalreviewstatus,
                $1:decisionenddate_ext::TIMESTAMP_TZ AS decisionenddate_ext,
                CAST($1:cwwrsuitableemployment AS NUMBER(18,2)) AS cwwrsuitableemployment,
                $1:discretionaryentitlement::NUMBER AS discretionaryentitlement,
                CAST($1:abilitytoearn AS NUMBER(18,2)) AS abilitytoearn,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwcc', 'ccx_wcdinternalreview_icare') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS wcdinternalreview_icare_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'reviewdetailsid',
                        'assessedasindefinitelyunable',
                        'outcomereasoning',
                        'solicitorid',
                        'updatetime',
                        'newwcdrequired',
                        'fairnoticerequired',
                        'reasoning',
                        'createuserid',
                        'working15hourperweektext',
                        'beanversion',
                        'retired',
                        'decisionissuedate',
                        'updateuserid',
                        'furtherinfoimpactsdecision',
                        'stayapplicable',
                        'dateapplicationreceived',
                        'section38eligibility',
                        'publicid',
                        'internalreviewcompleteddate',
                        'earningperweek',
                        'createtime',
                        'reviewduedate',
                        'wpipercentage',
                        'applicationlodgedby',
                        'acknowledgementletterdate',
                        'assessedasunabletext',
                        'earningse',
                        'reviewerid',
                        'medentitlement',
                        'section38eligible',
                        'earningscapacity',
                        'archivepartition',
                        'eligibilityeffectivedate',
                        'furtherinfosubmitted',
                        'section54stillactive',
                        'weeklypaymentimpact',
                        'assessedhours',
                        'draftdecisioncompleted',
                        'responsedate',
                        'earningperweektext',
                        'reviewrequestedwithin30days',
                        'followupflag',
                        'working15hourperweek',
                        'casenumber',
                        'decisioneffectivedate',
                        'reviewoutcome',
                        'stayexpirydate',
                        'sections80stillactive',
                        'piawe',
                        'withins80noticeperiod',
                        'internalreviewstatus',
                        'decisionenddate_ext',
                        'cwwrsuitableemployment',
                        'discretionaryentitlement',
                        'abilitytoearn'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) as record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}