{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for cc_matter.
                                                matter_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["raw_layer", "raw_claim_centre", "claim_centre", "business_critical", "cc_matter"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:PunitiveDamages::BOOLEAN AS punitivedamages,
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                data_payload:PreviousGroupID::NUMBER AS previousgroupid,
                data_payload:FirstNotice::BOOLEAN AS firstnotice,
                data_payload:RiskType::NUMBER AS risktype,
                data_payload:AssignedByUserID::NUMBER AS assignedbyuserid,
                CAST(data_payload:Name::TEXT AS VARCHAR(128)) AS name,
                data_payload:DeclaratoryJgmt::BOOLEAN AS declaratoryjgmt,
                CAST(data_payload:FinalSettleCost AS NUMBER(18,2)) AS finalsettlecost,
                data_payload:SubroRelated::BOOLEAN AS subrorelated,
                CAST(data_payload:HearingRoom::TEXT AS VARCHAR(32)) AS hearingroom,
                TO_TIMESTAMP_TZ(data_payload:ResponseDue::NUMBER/1000) AS responsedue,
                CAST(data_payload:KeyIssues_icare::TEXT AS VARCHAR(16777216)) AS keyissues_icare,
                data_payload:PreviousQueueID::NUMBER AS previousqueueid,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:CourtDistrict::NUMBER AS courtdistrict,
                data_payload:ID::NUMBER AS id,
                data_payload:ReopenedReason::NUMBER AS reopenedreason,
                TO_TIMESTAMP_TZ(data_payload:RaisedDate_icare::NUMBER/1000) AS raiseddate_icare,
                data_payload:CreateUserID::NUMBER AS createuserid,
                TO_TIMESTAMP_TZ(data_payload:CloseDate::NUMBER/1000) AS closedate,
                TO_TIMESTAMP_TZ(data_payload:MediationDate::NUMBER/1000) AS mediationdate,
                data_payload:PrimaryCause::NUMBER AS primarycause,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:Retired::NUMBER AS retired,
                TO_TIMESTAMP_TZ(data_payload:FileDate::NUMBER/1000) AS filedate,
                data_payload:WPI_icare::BOOLEAN AS wpi_icare,
                data_payload:ValidationLevel::NUMBER AS validationlevel,
                data_payload:Resolution::NUMBER AS resolution,
                TO_TIMESTAMP_TZ(data_payload:ArbitrationDate::NUMBER/1000) AS arbitrationdate,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                CAST(data_payload:OtherMatterSubtypeText_icare::TEXT AS VARCHAR(16777216)) AS othermattersubtypetext_icare,
                data_payload:CommonLawID::NUMBER AS commonlawid,
                CAST(data_payload:PunitiveAmount AS NUMBER(18,2)) AS punitiveamount,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                TO_TIMESTAMP_TZ(data_payload:TrialDate::NUMBER/1000) AS trialdate,
                data_payload:CourtType::NUMBER AS courttype,
                data_payload:SuitType::NUMBER AS suittype,
                TO_TIMESTAMP_TZ(data_payload:ResponseFiled::NUMBER/1000) AS responsefiled,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                data_payload:DocumentLinkableID::NUMBER AS documentlinkableid,
                data_payload:AssignedGroupID::NUMBER AS assignedgroupid,
                data_payload:VenueRating::NUMBER AS venuerating,
                data_payload:SignificantLitigation_icare::NUMBER AS significantlitigation_icare,
                CAST(data_payload:LitigationStrategy_icare::TEXT AS VARCHAR(16777216)) AS litigationstrategy_icare,
                data_payload:EventType_icare::NUMBER AS eventtype_icare,
                CAST(data_payload:FinalLegalCost AS NUMBER(18,2)) AS finallegalcost,
                CAST(data_payload:MediationRoom::TEXT AS VARCHAR(32)) AS mediationroom,
                data_payload:MotionSummaryJgmt::BOOLEAN AS motionsummaryjgmt,
                data_payload:MethodServed::NUMBER AS methodserved,
                data_payload:ClaimID::NUMBER AS claimid,
                CAST(data_payload:ArbitrationRoom::TEXT AS VARCHAR(32)) AS arbitrationroom,
                CAST(data_payload:Room::TEXT AS VARCHAR(32)) AS room,
                data_payload:StructuredSettle::BOOLEAN AS structuredsettle,
                data_payload:PreviousUserID::NUMBER AS previoususerid,
                data_payload:AssignedQueueID::NUMBER AS assignedqueueid,
                TO_TIMESTAMP_TZ(data_payload:DefenseApptDate::NUMBER/1000) AS defenseapptdate,
                TO_TIMESTAMP_TZ(data_payload:HearingDate::NUMBER/1000) AS hearingdate,
                TO_TIMESTAMP_TZ(data_payload:ServiceDate::NUMBER/1000) AS servicedate,
                data_payload:LegalSpecialty::NUMBER AS legalspecialty,
                TO_TIMESTAMP_TZ(data_payload:FilingDate::NUMBER/1000) AS filingdate,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                CAST(data_payload:DocketNumber::TEXT AS VARCHAR(20)) AS docketnumber,
                TO_TIMESTAMP_TZ(data_payload:FinalSettleDate::NUMBER/1000) AS finalsettledate,
                TO_TIMESTAMP_TZ(data_payload:TeleconferenceDate_icare::NUMBER/1000) AS teleconferencedate_icare,
                CAST(data_payload:AdDamnumAmount AS NUMBER(18,2)) AS addamnumamount,
                data_payload:AssignedUserID::NUMBER AS assigneduserid,
                CAST(data_payload:NewLitStraNote_icare::TEXT AS VARCHAR(16777216)) AS newlitstranote_icare,
                TO_TIMESTAMP_TZ(data_payload:StatemantOfClaim_icare::NUMBER/1000) AS statemantofclaim_icare,
                data_payload:SubrogationSummaryID::NUMBER AS subrogationsummaryid,
                data_payload:AdDamnumSpecified::BOOLEAN AS addamnumspecified,
                CAST(data_payload:CaseNumber::TEXT AS VARCHAR(128)) AS casenumber,
                CAST(data_payload:MatterCaseNumber::TEXT AS VARCHAR(20)) AS mattercasenumber,
                TO_TIMESTAMP_TZ(data_payload:AssignmentDate::NUMBER/1000) AS assignmentdate,
                TO_TIMESTAMP_TZ(data_payload:SentToDefenseDate::NUMBER/1000) AS senttodefensedate,
                data_payload:MatterType::NUMBER AS mattertype,
                data_payload:AssignmentStatus::NUMBER AS assignmentstatus,
                data_payload:Arbitration::BOOLEAN AS arbitration,
                data_payload:WorkCapcityDecision_icareID::NUMBER AS workcapcitydecision_icareid,
                TO_TIMESTAMP_TZ(data_payload:LegacyUpdateTime_Ext::NUMBER/1000) AS legacyupdatetime_ext,
                TO_TIMESTAMP_TZ(data_payload:LegacyCreateTime_Ext::NUMBER/1000) AS legacycreatetime_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwcc', 'cc_matter') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:punitivedamages::BOOLEAN AS punitivedamages,
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:previousgroupid::NUMBER AS previousgroupid,
                $1:firstnotice::BOOLEAN AS firstnotice,
                $1:risktype::NUMBER AS risktype,
                $1:assignedbyuserid::NUMBER AS assignedbyuserid,
                CAST($1:name::TEXT AS VARCHAR(128)) AS name,
                $1:declaratoryjgmt::BOOLEAN AS declaratoryjgmt,
                CAST($1:finalsettlecost AS NUMBER(18,2)) AS finalsettlecost,
                $1:subrorelated::BOOLEAN AS subrorelated,
                CAST($1:hearingroom::TEXT AS VARCHAR(32)) AS hearingroom,
                $1:responsedue::TIMESTAMP_TZ AS responsedue,
                CAST($1:keyissues_icare::TEXT AS VARCHAR(16777216)) AS keyissues_icare,
                $1:previousqueueid::NUMBER AS previousqueueid,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:courtdistrict::NUMBER AS courtdistrict,
                $1:id::NUMBER AS id,
                $1:reopenedreason::NUMBER AS reopenedreason,
                $1:raiseddate_icare::TIMESTAMP_TZ AS raiseddate_icare,
                $1:createuserid::NUMBER AS createuserid,
                $1:closedate::TIMESTAMP_TZ AS closedate,
                $1:mediationdate::TIMESTAMP_TZ AS mediationdate,
                $1:primarycause::NUMBER AS primarycause,
                $1:beanversion::NUMBER AS beanversion,
                $1:retired::NUMBER AS retired,
                $1:filedate::TIMESTAMP_TZ AS filedate,
                $1:wpi_icare::BOOLEAN AS wpi_icare,
                $1:validationlevel::NUMBER AS validationlevel,
                $1:resolution::NUMBER AS resolution,
                $1:arbitrationdate::TIMESTAMP_TZ AS arbitrationdate,
                $1:updateuserid::NUMBER AS updateuserid,
                CAST($1:othermattersubtypetext_icare::TEXT AS VARCHAR(16777216)) AS othermattersubtypetext_icare,
                $1:commonlawid::NUMBER AS commonlawid,
                CAST($1:punitiveamount AS NUMBER(18,2)) AS punitiveamount,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:trialdate::TIMESTAMP_TZ AS trialdate,
                $1:courttype::NUMBER AS courttype,
                $1:suittype::NUMBER AS suittype,
                $1:responsefiled::TIMESTAMP_TZ AS responsefiled,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:documentlinkableid::NUMBER AS documentlinkableid,
                $1:assignedgroupid::NUMBER AS assignedgroupid,
                $1:venuerating::NUMBER AS venuerating,
                $1:significantlitigation_icare::NUMBER AS significantlitigation_icare,
                CAST($1:litigationstrategy_icare::TEXT AS VARCHAR(16777216)) AS litigationstrategy_icare,
                $1:eventtype_icare::NUMBER AS eventtype_icare,
                CAST($1:finallegalcost AS NUMBER(18,2)) AS finallegalcost,
                CAST($1:mediationroom::TEXT AS VARCHAR(32)) AS mediationroom,
                $1:motionsummaryjgmt::BOOLEAN AS motionsummaryjgmt,
                $1:methodserved::NUMBER AS methodserved,
                $1:claimid::NUMBER AS claimid,
                CAST($1:arbitrationroom::TEXT AS VARCHAR(32)) AS arbitrationroom,
                CAST($1:room::TEXT AS VARCHAR(32)) AS room,
                $1:structuredsettle::BOOLEAN AS structuredsettle,
                $1:previoususerid::NUMBER AS previoususerid,
                $1:assignedqueueid::NUMBER AS assignedqueueid,
                $1:defenseapptdate::TIMESTAMP_TZ AS defenseapptdate,
                $1:hearingdate::TIMESTAMP_TZ AS hearingdate,
                $1:servicedate::TIMESTAMP_TZ AS servicedate,
                $1:legalspecialty::NUMBER AS legalspecialty,
                $1:filingdate::TIMESTAMP_TZ AS filingdate,
                $1:archivepartition::NUMBER AS archivepartition,
                CAST($1:docketnumber::TEXT AS VARCHAR(20)) AS docketnumber,
                $1:finalsettledate::TIMESTAMP_TZ AS finalsettledate,
                $1:teleconferencedate_icare::TIMESTAMP_TZ AS teleconferencedate_icare,
                CAST($1:addamnumamount AS NUMBER(18,2)) AS addamnumamount,
                $1:assigneduserid::NUMBER AS assigneduserid,
                CAST($1:newlitstranote_icare::TEXT AS VARCHAR(16777216)) AS newlitstranote_icare,
                $1:statemantofclaim_icare::TIMESTAMP_TZ AS statemantofclaim_icare,
                $1:subrogationsummaryid::NUMBER AS subrogationsummaryid,
                $1:addamnumspecified::BOOLEAN AS addamnumspecified,
                CAST($1:casenumber::TEXT AS VARCHAR(128)) AS casenumber,
                CAST($1:mattercasenumber::TEXT AS VARCHAR(20)) AS mattercasenumber,
                $1:assignmentdate::TIMESTAMP_TZ AS assignmentdate,
                $1:senttodefensedate::TIMESTAMP_TZ AS senttodefensedate,
                $1:mattertype::NUMBER AS mattertype,
                $1:assignmentstatus::NUMBER AS assignmentstatus,
                $1:arbitration::BOOLEAN AS arbitration,
                $1:workcapcitydecision_icareid::NUMBER AS workcapcitydecision_icareid,
                $1:legacyupdatetime_ext::TIMESTAMP_TZ AS legacyupdatetime_ext,
                $1:legacycreatetime_ext::TIMESTAMP_TZ AS legacycreatetime_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwcc', 'cc_matter') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS matter_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'punitivedamages',
                        'loadcommandid',
                        'previousgroupid',
                        'firstnotice',
                        'risktype',
                        'assignedbyuserid',
                        'name',
                        'declaratoryjgmt',
                        'finalsettlecost',
                        'subrorelated',
                        'hearingroom',
                        'responsedue',
                        'keyissues_icare',
                        'previousqueueid',
                        'updatetime',
                        'courtdistrict',
                        'reopenedreason',
                        'raiseddate_icare',
                        'createuserid',
                        'closedate',
                        'mediationdate',
                        'primarycause',
                        'beanversion',
                        'retired',
                        'filedate',
                        'wpi_icare',
                        'validationlevel',
                        'resolution',
                        'arbitrationdate',
                        'updateuserid',
                        'othermattersubtypetext_icare',
                        'commonlawid',
                        'punitiveamount',
                        'publicid',
                        'trialdate',
                        'courttype',
                        'suittype',
                        'responsefiled',
                        'createtime',
                        'documentlinkableid',
                        'assignedgroupid',
                        'venuerating',
                        'significantlitigation_icare',
                        'litigationstrategy_icare',
                        'eventtype_icare',
                        'finallegalcost',
                        'mediationroom',
                        'motionsummaryjgmt',
                        'methodserved',
                        'claimid',
                        'arbitrationroom',
                        'room',
                        'structuredsettle',
                        'previoususerid',
                        'assignedqueueid',
                        'defenseapptdate',
                        'hearingdate',
                        'servicedate',
                        'legalspecialty',
                        'filingdate',
                        'archivepartition',
                        'docketnumber',
                        'finalsettledate',
                        'teleconferencedate_icare',
                        'addamnumamount',
                        'assigneduserid',
                        'newlitstranote_icare',
                        'statemantofclaim_icare',
                        'subrogationsummaryid',
                        'addamnumspecified',
                        'casenumber',
                        'mattercasenumber',
                        'assignmentdate',
                        'senttodefensedate',
                        'mattertype',
                        'assignmentstatus',
                        'arbitration',
                        'workcapcitydecision_icareid',
                        'legacyupdatetime_ext',
                        'legacycreatetime_ext'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS dbt_updated_at
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}