{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for cc_document.
                                                document_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["landing", "gwcc", "claim_centre", "business_critical", "cc_document"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                CAST(data_payload:Approver_icare::TEXT AS VARCHAR(60)) AS approver_icare,
                CAST(data_payload:PeerReviewNotes_icare::TEXT AS VARCHAR(16777216)) AS peerreviewnotes_icare,
                data_payload:DocumentChannel_icare::NUMBER AS documentchannel_icare,
                CAST(data_payload:DocumentIdentifier::TEXT AS VARCHAR(60)) AS documentidentifier,
                CAST(data_payload:PhysicalLocation_icare::TEXT AS VARCHAR(250)) AS physicallocation_icare,
                CAST(data_payload:AuthorDenorm::TEXT AS VARCHAR(60)) AS authordenorm,
                CAST(data_payload:NameDenorm::TEXT AS VARCHAR(250)) AS namedenorm,
                CAST(data_payload:DocumentPackID_icare::TEXT AS VARCHAR(255)) AS documentpackid_icare,
                data_payload:DMS::BOOLEAN AS dms,
                CAST(data_payload:Name::TEXT AS VARCHAR(250)) AS name,
                CAST(data_payload:Author::TEXT AS VARCHAR(60)) AS author,
                data_payload:DeliveryMethod_icare::NUMBER AS deliverymethod_icare,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:TemplateXML_icare::BINARY AS templatexml_icare,
                CAST(data_payload:DocUID::TEXT AS VARCHAR(255)) AS docuid,
                CAST(data_payload:Recipient::TEXT AS VARCHAR(60)) AS recipient,
                data_payload:Obsolete::BOOLEAN AS obsolete,
                data_payload:ID::NUMBER AS id,
                data_payload:MatterID::NUMBER AS matterid,
                data_payload:WorkCapacity_icareID::NUMBER AS workcapacity_icareid,
                data_payload:CreateUserID::NUMBER AS createuserid,
                data_payload:SharedWithWorker_icare::BOOLEAN AS sharedwithworker_icare,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:Retired::NUMBER AS retired,
                CAST(data_payload:ResendPackID_icare::TEXT AS VARCHAR(15)) AS resendpackid_icare,
                data_payload:PortalUserType_icare::NUMBER AS portalusertype_icare,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                data_payload:Direction_icare::NUMBER AS direction_icare,
                data_payload:Type::NUMBER AS type,
                data_payload:Redacted_icare::BOOLEAN AS redacted_icare,
                CAST(data_payload:UploadFileKey_icare::TEXT AS VARCHAR(255)) AS uploadfilekey_icare,
                CAST(data_payload:DocumentIdentifierDenorm::TEXT AS VARCHAR(60)) AS documentidentifierdenorm,
                CAST(data_payload:FileName_icare::TEXT AS VARCHAR(250)) AS filename_icare,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                CAST(data_payload:ProcessID_icare::TEXT AS VARCHAR(255)) AS processid_icare,
                CAST(data_payload:PortalSecurityRealm_Ext::TEXT AS VARCHAR(60)) AS portalsecurityrealm_ext,
                data_payload:LineOfBusiness_icare::NUMBER AS lineofbusiness_icare,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                data_payload:InteractiveStatus_icare::NUMBER AS interactivestatus_icare,
                data_payload:DPSXML_PSC::BINARY AS dpsxml_psc,
                data_payload:PortalClaimUpdate_icare::NUMBER AS portalclaimupdate_icare,
                data_payload:CreationType_icare::NUMBER AS creationtype_icare,
                data_payload:ClaimID::NUMBER AS claimid,
                data_payload:Language::NUMBER AS language,
                data_payload:ApprovalRequired_icare::BOOLEAN AS approvalrequired_icare,
                data_payload:SharedWithEmployer_icare::BOOLEAN AS sharedwithemployer_icare,
                CAST(data_payload:AuthorID_icare::TEXT AS VARCHAR(255)) AS authorid_icare,
                data_payload:ExposureID::NUMBER AS exposureid,
                TO_TIMESTAMP_TZ(data_payload:DateSentReceived_icare::NUMBER/1000) AS datesentreceived_icare,
                data_payload:Section::NUMBER AS section,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                CAST(data_payload:InboundPackID_icare::TEXT AS VARCHAR(100)) AS inboundpackid_icare,
                CAST(data_payload:MimeType::TEXT AS VARCHAR(80)) AS mimetype,
                CAST(data_payload:PendingDocUID::TEXT AS VARCHAR(255)) AS pendingdocuid,
                data_payload:Status::NUMBER AS status,
                data_payload:primaryrecipient_pscid::NUMBER AS primaryrecipient_pscid,
                TO_TIMESTAMP_TZ(data_payload:DateModified::NUMBER/1000) AS datemodified,
                data_payload:Inbound::BOOLEAN AS inbound,
                data_payload:SecurityType::NUMBER AS securitytype,
                TO_TIMESTAMP_TZ(data_payload:DateCreated::NUMBER/1000) AS datecreated,
                data_payload:SchemeAgent_icare::NUMBER AS schemeagent_icare,
                data_payload:DocumentSubSection_icare::NUMBER AS documentsubsection_icare,
                TO_TIMESTAMP_TZ(data_payload:DateLastSaved_icare::NUMBER/1000) AS datelastsaved_icare,
                data_payload:ClaimContactID::NUMBER AS claimcontactid,
                CAST(data_payload:NewClaimNumber_icare::TEXT AS VARCHAR(40)) AS newclaimnumber_icare,
                CAST(data_payload:BatchID_Ext::TEXT AS VARCHAR(20)) AS batchid_ext,
                data_payload:PriorityLevel_Ext::NUMBER AS prioritylevel_ext,
                data_payload:DocGenerationType_Ext::NUMBER AS docgenerationtype_ext,
                CAST(data_payload:Description::TEXT AS VARCHAR(250)) AS description,
                TO_TIMESTAMP_TZ(data_payload:LegacyCreateTime_Ext::NUMBER/1000) AS legacycreatetime_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwcc', 'cc_document') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                CAST($1:approver_icare::TEXT AS VARCHAR(60)) AS approver_icare,
                CAST($1:peerreviewnotes_icare::TEXT AS VARCHAR(16777216)) AS peerreviewnotes_icare,
                $1:documentchannel_icare::NUMBER AS documentchannel_icare,
                CAST($1:documentidentifier::TEXT AS VARCHAR(60)) AS documentidentifier,
                CAST($1:physicallocation_icare::TEXT AS VARCHAR(250)) AS physicallocation_icare,
                CAST($1:authordenorm::TEXT AS VARCHAR(60)) AS authordenorm,
                CAST($1:namedenorm::TEXT AS VARCHAR(250)) AS namedenorm,
                CAST($1:documentpackid_icare::TEXT AS VARCHAR(255)) AS documentpackid_icare,
                $1:dms::BOOLEAN AS dms,
                CAST($1:name::TEXT AS VARCHAR(250)) AS name,
                CAST($1:author::TEXT AS VARCHAR(60)) AS author,
                $1:deliverymethod_icare::NUMBER AS deliverymethod_icare,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:templatexml_icare::BINARY AS templatexml_icare,
                CAST($1:docuid::TEXT AS VARCHAR(255)) AS docuid,
                CAST($1:recipient::TEXT AS VARCHAR(60)) AS recipient,
                $1:obsolete::BOOLEAN AS obsolete,
                $1:id::NUMBER AS id,
                $1:matterid::NUMBER AS matterid,
                $1:workcapacity_icareid::NUMBER AS workcapacity_icareid,
                $1:createuserid::NUMBER AS createuserid,
                $1:sharedwithworker_icare::BOOLEAN AS sharedwithworker_icare,
                $1:beanversion::NUMBER AS beanversion,
                $1:retired::NUMBER AS retired,
                CAST($1:resendpackid_icare::TEXT AS VARCHAR(15)) AS resendpackid_icare,
                $1:portalusertype_icare::NUMBER AS portalusertype_icare,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:direction_icare::NUMBER AS direction_icare,
                $1:type::NUMBER AS type,
                $1:redacted_icare::BOOLEAN AS redacted_icare,
                CAST($1:uploadfilekey_icare::TEXT AS VARCHAR(255)) AS uploadfilekey_icare,
                CAST($1:documentidentifierdenorm::TEXT AS VARCHAR(60)) AS documentidentifierdenorm,
                CAST($1:filename_icare::TEXT AS VARCHAR(250)) AS filename_icare,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                CAST($1:processid_icare::TEXT AS VARCHAR(255)) AS processid_icare,
                CAST($1:portalsecurityrealm_ext::TEXT AS VARCHAR(60)) AS portalsecurityrealm_ext,
                $1:lineofbusiness_icare::NUMBER AS lineofbusiness_icare,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:interactivestatus_icare::NUMBER AS interactivestatus_icare,
                $1:dpsxml_psc::BINARY AS dpsxml_psc,
                $1:portalclaimupdate_icare::NUMBER AS portalclaimupdate_icare,
                $1:creationtype_icare::NUMBER AS creationtype_icare,
                $1:claimid::NUMBER AS claimid,
                $1:language::NUMBER AS language,
                $1:approvalrequired_icare::BOOLEAN AS approvalrequired_icare,
                $1:sharedwithemployer_icare::BOOLEAN AS sharedwithemployer_icare,
                CAST($1:authorid_icare::TEXT AS VARCHAR(255)) AS authorid_icare,
                $1:exposureid::NUMBER AS exposureid,
                $1:datesentreceived_icare::TIMESTAMP_TZ AS datesentreceived_icare,
                $1:section::NUMBER AS section,
                $1:archivepartition::NUMBER AS archivepartition,
                CAST($1:inboundpackid_icare::TEXT AS VARCHAR(100)) AS inboundpackid_icare,
                CAST($1:mimetype::TEXT AS VARCHAR(80)) AS mimetype,
                CAST($1:pendingdocuid::TEXT AS VARCHAR(255)) AS pendingdocuid,
                $1:status::NUMBER AS status,
                $1:primaryrecipient_pscid::NUMBER AS primaryrecipient_pscid,
                $1:datemodified::TIMESTAMP_TZ AS datemodified,
                $1:inbound::BOOLEAN AS inbound,
                $1:securitytype::NUMBER AS securitytype,
                $1:datecreated::TIMESTAMP_TZ AS datecreated,
                $1:schemeagent_icare::NUMBER AS schemeagent_icare,
                $1:documentsubsection_icare::NUMBER AS documentsubsection_icare,
                $1:datelastsaved_icare::TIMESTAMP_TZ AS datelastsaved_icare,
                $1:claimcontactid::NUMBER AS claimcontactid,
                CAST($1:newclaimnumber_icare::TEXT AS VARCHAR(40)) AS newclaimnumber_icare,
                CAST($1:batchid_ext::TEXT AS VARCHAR(20)) AS batchid_ext,
                $1:prioritylevel_ext::NUMBER AS prioritylevel_ext,
                $1:docgenerationtype_ext::NUMBER AS docgenerationtype_ext,
                CAST($1:description::TEXT AS VARCHAR(250)) AS description,
                $1:legacycreatetime_ext::TIMESTAMP_TZ AS legacycreatetime_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwcc', 'cc_document') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS document_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'approver_icare',
                        'peerreviewnotes_icare',
                        'documentchannel_icare',
                        'documentidentifier',
                        'physicallocation_icare',
                        'authordenorm',
                        'namedenorm',
                        'documentpackid_icare',
                        'dms',
                        'name',
                        'author',
                        'deliverymethod_icare',
                        'updatetime',
                        'templatexml_icare',
                        'docuid',
                        'recipient',
                        'obsolete',
                        'matterid',
                        'workcapacity_icareid',
                        'createuserid',
                        'sharedwithworker_icare',
                        'beanversion',
                        'retired',
                        'resendpackid_icare',
                        'portalusertype_icare',
                        'updateuserid',
                        'direction_icare',
                        'type',
                        'redacted_icare',
                        'uploadfilekey_icare',
                        'documentidentifierdenorm',
                        'filename_icare',
                        'publicid',
                        'processid_icare',
                        'portalsecurityrealm_ext',
                        'lineofbusiness_icare',
                        'createtime',
                        'interactivestatus_icare',
                        'dpsxml_psc',
                        'portalclaimupdate_icare',
                        'creationtype_icare',
                        'claimid',
                        'language',
                        'approvalrequired_icare',
                        'sharedwithemployer_icare',
                        'authorid_icare',
                        'exposureid',
                        'datesentreceived_icare',
                        'section',
                        'archivepartition',
                        'inboundpackid_icare',
                        'mimetype',
                        'pendingdocuid',
                        'status',
                        'primaryrecipient_pscid',
                        'datemodified',
                        'inbound',
                        'securitytype',
                        'datecreated',
                        'schemeagent_icare',
                        'documentsubsection_icare',
                        'datelastsaved_icare',
                        'claimcontactid',
                        'newclaimnumber_icare',
                        'batchid_ext',
                        'prioritylevel_ext',
                        'docgenerationtype_ext',
                        'description',
                        'legacycreatetime_ext'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) as record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}