{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for cc_policy.
                                                policy_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["raw_layer", "raw_claim_centre", "claim_centre", "business_critical", "cc_policy"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                CAST(data_payload:GroupNumber_icare::TEXT AS VARCHAR(255)) AS groupnumber_icare,
                CAST(data_payload:PolicySuffix::TEXT AS VARCHAR(255)) AS policysuffix,
                CAST(data_payload:ACN_icare::TEXT AS VARCHAR(16777216)) AS acn_icare,
                CAST(data_payload:PolicyID_icare::TEXT AS VARCHAR(64)) AS policyid_icare,
                data_payload:TotalVehicles::NUMBER AS totalvehicles,
                CAST(data_payload:OtherInsInfo::TEXT AS VARCHAR(255)) AS otherinsinfo,
                CAST(data_payload:InsuredSICCode::TEXT AS VARCHAR(6)) AS insuredsiccode,
                data_payload:Currency::NUMBER AS currency,
                CAST(data_payload:TotalBTP_icare AS NUMBER(18,2)) AS totalbtp_icare,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:ID::NUMBER AS id,
                data_payload:AssignedRisk::BOOLEAN AS assignedrisk,
                CAST(data_payload:FinancialInterests::TEXT AS VARCHAR(255)) AS financialinterests,
                data_payload:CreateUserID::NUMBER AS createuserid,
                data_payload:ReturnToWorkPrgm::BOOLEAN AS returntoworkprgm,
                data_payload:ITCPercentagePEL::NUMBER AS itcpercentagepel,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:Retired::NUMBER AS retired,
                data_payload:ValidationLevel::NUMBER AS validationlevel,
                data_payload:CoverageForm::NUMBER AS coverageform,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                TO_TIMESTAMP_TZ(data_payload:CancellationDate::NUMBER/1000) AS cancellationdate,
                TO_TIMESTAMP_TZ(data_payload:OrigEffectiveDate::NUMBER/1000) AS origeffectivedate,
                CAST(data_payload:AccountNumber::TEXT AS VARCHAR(40)) AS accountnumber,
                CAST(data_payload:BusinessDescription_icare::TEXT AS VARCHAR(255)) AS businessdescription_icare,
                data_payload:ForeignCoverage::BOOLEAN AS foreigncoverage,
                data_payload:BusinessGSTRegistration_icare::BOOLEAN AS businessgstregistration_icare,
                CAST(data_payload:LegacyPolicyNumber_icare::TEXT AS VARCHAR(40)) AS legacypolicynumber_icare,
                CAST(data_payload:Notes::TEXT AS VARCHAR(255)) AS notes,
                CAST(data_payload:Participation AS NUMBER(4,1)) AS participation,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                CAST(data_payload:WCOtherStates::TEXT AS VARCHAR(255)) AS wcotherstates,
                data_payload:Verified::BOOLEAN AS verified,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                CAST(data_payload:PolicyPeriodID_icare::TEXT AS VARCHAR(64)) AS policyperiodid_icare,
                data_payload:OtherInsurance::BOOLEAN AS otherinsurance,
                data_payload:PolicySource::NUMBER AS policysource,
                CAST(data_payload:WCStates::TEXT AS VARCHAR(255)) AS wcstates,
                data_payload:LabourHire_icare::NUMBER AS labourhire_icare,
                data_payload:BusinessOrganisationType_icare::NUMBER AS businessorganisationtype_icare,
                TO_TIMESTAMP_TZ(data_payload:RetroactiveDate::NUMBER/1000) AS retroactivedate,
                TO_TIMESTAMP_TZ(data_payload:EffectiveDate::NUMBER/1000) AS effectivedate,
                CAST(data_payload:ProducerName_icare::TEXT AS VARCHAR(255)) AS producername_icare,
                TO_TIMESTAMP_TZ(data_payload:ReportingDate::NUMBER/1000) AS reportingdate,
                TO_TIMESTAMP_TZ(data_payload:ExpirationDate::NUMBER/1000) AS expirationdate,
                CAST(data_payload:BusinessYearStarted_icare::TEXT AS VARCHAR(4)) AS businessyearstarted_icare,
                data_payload:PolicyType_icare::NUMBER AS policytype_icare,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                data_payload:PolicyType::NUMBER AS policytype,
                data_payload:UnderwritingCo::NUMBER AS underwritingco,
                data_payload:Status::NUMBER AS status,
                data_payload:EmployerCategory_icare::NUMBER AS employercategory_icare,
                data_payload:TotalProperties::NUMBER AS totalproperties,
                data_payload:PolicyRatingPlan::NUMBER AS policyratingplan,
                data_payload:CustomerServiceTier::NUMBER AS customerservicetier,
                data_payload:ManualVerify_icare::BOOLEAN AS manualverify_icare,
                CAST(data_payload:PolicyNumber::TEXT AS VARCHAR(40)) AS policynumber,
                data_payload:UnderwritingGroup::NUMBER AS underwritinggroup,
                data_payload:PolicySystemPeriodID::NUMBER AS policysystemperiodid,
                CAST(data_payload:ProducerCode::TEXT AS VARCHAR(255)) AS producercode,
                CAST(data_payload:TariffRate_icare::TEXT AS VARCHAR(3)) AS tariffrate_icare,
                data_payload:SpecialistCSP_ExtID::NUMBER AS specialistcsp_extid,
                data_payload:GeneralistCSP_ExtID::NUMBER AS generalistcsp_extid,
                data_payload:TMFCostCentreRequiredFlag_Ext::BOOLEAN AS tmfcostcentrerequiredflag_ext,
                CAST(data_payload:AgencyCode_Ext::TEXT AS VARCHAR(10)) AS agencycode_ext,
                CAST(data_payload:Offering_Ext::TEXT AS VARCHAR(10)) AS offering_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwcc', 'cc_policy') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                CAST($1:groupnumber_icare::TEXT AS VARCHAR(255)) AS groupnumber_icare,
                CAST($1:policysuffix::TEXT AS VARCHAR(255)) AS policysuffix,
                CAST($1:acn_icare::TEXT AS VARCHAR(16777216)) AS acn_icare,
                CAST($1:policyid_icare::TEXT AS VARCHAR(64)) AS policyid_icare,
                $1:totalvehicles::NUMBER AS totalvehicles,
                CAST($1:otherinsinfo::TEXT AS VARCHAR(255)) AS otherinsinfo,
                CAST($1:insuredsiccode::TEXT AS VARCHAR(6)) AS insuredsiccode,
                $1:currency::NUMBER AS currency,
                CAST($1:totalbtp_icare AS NUMBER(18,2)) AS totalbtp_icare,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:id::NUMBER AS id,
                $1:assignedrisk::BOOLEAN AS assignedrisk,
                CAST($1:financialinterests::TEXT AS VARCHAR(255)) AS financialinterests,
                $1:createuserid::NUMBER AS createuserid,
                $1:returntoworkprgm::BOOLEAN AS returntoworkprgm,
                $1:itcpercentagepel::NUMBER AS itcpercentagepel,
                $1:beanversion::NUMBER AS beanversion,
                $1:retired::NUMBER AS retired,
                $1:validationlevel::NUMBER AS validationlevel,
                $1:coverageform::NUMBER AS coverageform,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:cancellationdate::TIMESTAMP_TZ AS cancellationdate,
                $1:origeffectivedate::TIMESTAMP_TZ AS origeffectivedate,
                CAST($1:accountnumber::TEXT AS VARCHAR(40)) AS accountnumber,
                CAST($1:businessdescription_icare::TEXT AS VARCHAR(255)) AS businessdescription_icare,
                $1:foreigncoverage::BOOLEAN AS foreigncoverage,
                $1:businessgstregistration_icare::BOOLEAN AS businessgstregistration_icare,
                CAST($1:legacypolicynumber_icare::TEXT AS VARCHAR(40)) AS legacypolicynumber_icare,
                CAST($1:notes::TEXT AS VARCHAR(255)) AS notes,
                CAST($1:participation AS NUMBER(4,1)) AS participation,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                CAST($1:wcotherstates::TEXT AS VARCHAR(255)) AS wcotherstates,
                $1:verified::BOOLEAN AS verified,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                CAST($1:policyperiodid_icare::TEXT AS VARCHAR(64)) AS policyperiodid_icare,
                $1:otherinsurance::BOOLEAN AS otherinsurance,
                $1:policysource::NUMBER AS policysource,
                CAST($1:wcstates::TEXT AS VARCHAR(255)) AS wcstates,
                $1:labourhire_icare::NUMBER AS labourhire_icare,
                $1:businessorganisationtype_icare::NUMBER AS businessorganisationtype_icare,
                $1:retroactivedate::TIMESTAMP_TZ AS retroactivedate,
                $1:effectivedate::TIMESTAMP_TZ AS effectivedate,
                CAST($1:producername_icare::TEXT AS VARCHAR(255)) AS producername_icare,
                $1:reportingdate::TIMESTAMP_TZ AS reportingdate,
                $1:expirationdate::TIMESTAMP_TZ AS expirationdate,
                CAST($1:businessyearstarted_icare::TEXT AS VARCHAR(4)) AS businessyearstarted_icare,
                $1:policytype_icare::NUMBER AS policytype_icare,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:policytype::NUMBER AS policytype,
                $1:underwritingco::NUMBER AS underwritingco,
                $1:status::NUMBER AS status,
                $1:employercategory_icare::NUMBER AS employercategory_icare,
                $1:totalproperties::NUMBER AS totalproperties,
                $1:policyratingplan::NUMBER AS policyratingplan,
                $1:customerservicetier::NUMBER AS customerservicetier,
                $1:manualverify_icare::BOOLEAN AS manualverify_icare,
                CAST($1:policynumber::TEXT AS VARCHAR(40)) AS policynumber,
                $1:underwritinggroup::NUMBER AS underwritinggroup,
                $1:policysystemperiodid::NUMBER AS policysystemperiodid,
                CAST($1:producercode::TEXT AS VARCHAR(255)) AS producercode,
                CAST($1:tariffrate_icare::TEXT AS VARCHAR(3)) AS tariffrate_icare,
                $1:specialistcsp_extid::NUMBER AS specialistcsp_extid,
                $1:generalistcsp_extid::NUMBER AS generalistcsp_extid,
                $1:tmfcostcentrerequiredflag_ext::BOOLEAN AS tmfcostcentrerequiredflag_ext,
                CAST($1:agencycode_ext::TEXT AS VARCHAR(10)) AS agencycode_ext,
                CAST($1:offering_ext::TEXT AS VARCHAR(10)) AS offering_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwcc', 'cc_policy') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS policy_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'groupnumber_icare',
                        'policysuffix',
                        'acn_icare',
                        'policyid_icare',
                        'totalvehicles',
                        'otherinsinfo',
                        'insuredsiccode',
                        'currency',
                        'totalbtp_icare',
                        'updatetime',
                        'assignedrisk',
                        'financialinterests',
                        'createuserid',
                        'returntoworkprgm',
                        'itcpercentagepel',
                        'beanversion',
                        'retired',
                        'validationlevel',
                        'coverageform',
                        'updateuserid',
                        'cancellationdate',
                        'origeffectivedate',
                        'accountnumber',
                        'businessdescription_icare',
                        'foreigncoverage',
                        'businessgstregistration_icare',
                        'legacypolicynumber_icare',
                        'notes',
                        'participation',
                        'publicid',
                        'wcotherstates',
                        'verified',
                        'createtime',
                        'policyperiodid_icare',
                        'otherinsurance',
                        'policysource',
                        'wcstates',
                        'labourhire_icare',
                        'businessorganisationtype_icare',
                        'retroactivedate',
                        'effectivedate',
                        'producername_icare',
                        'reportingdate',
                        'expirationdate',
                        'businessyearstarted_icare',
                        'policytype_icare',
                        'archivepartition',
                        'policytype',
                        'underwritingco',
                        'status',
                        'employercategory_icare',
                        'totalproperties',
                        'policyratingplan',
                        'customerservicetier',
                        'manualverify_icare',
                        'policynumber',
                        'underwritinggroup',
                        'policysystemperiodid',
                        'producercode',
                        'tariffrate_icare',
                        'specialistcsp_extid',
                        'generalistcsp_extid',
                        'tmfcostcentrerequiredflag_ext',
                        'agencycode_ext',
                        'offering_ext'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS dbt_updated_at
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}