{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for cc_transactionlineitem.
                                                transactionlineitem_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["raw_layer", "raw_claim_centre", "claim_centre", "business_critical", "cc_transactionlineitem"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                CAST(data_payload:NonPecuniaryBenefitD_icare AS NUMBER(18,2)) AS nonpecuniarybenefitd_icare,
                CAST(data_payload:ReportingAmount AS NUMBER(18,2)) AS reportingamount,
                CAST(data_payload:ITCAAAmountPEL AS NUMBER(18,2)) AS itcaaamountpel,
                CAST(data_payload:PAYGTax_icare AS NUMBER(18,2)) AS paygtax_icare,
                CAST(data_payload:GrossWeeklyWageRate_icare AS NUMBER(18,2)) AS grossweeklywagerate_icare,
                TO_TIMESTAMP_TZ(data_payload:DateOfService_icare::NUMBER/1000) AS dateofservice_icare,
                data_payload:PaymentVariationReason_icare::NUMBER AS paymentvariationreason_icare,
                CAST(data_payload:ReservingAmount AS NUMBER(18,2)) AS reservingamount,
                CAST(data_payload:ClaimAmount AS NUMBER(18,2)) AS claimamount,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                CAST(data_payload:HoursPaid_icare AS NUMBER(6,2)) AS hourspaid_icare,
                CAST(data_payload:AmountWithoutGST AS NUMBER(18,2)) AS amountwithoutgst,
                data_payload:ID::NUMBER AS id,
                CAST(data_payload:PaycodeName_icare::TEXT AS VARCHAR(20)) AS paycodename_icare,
                data_payload:DefaultDecision::BOOLEAN AS defaultdecision,
                data_payload:BenefitSuspended_icare::BOOLEAN AS benefitsuspended_icare,
                data_payload:CreateUserID::NUMBER AS createuserid,
                CAST(data_payload:ReportingForExAmount AS NUMBER(18,2)) AS reportingforexamount,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:Retired::NUMBER AS retired,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                CAST(data_payload:TransactionAmount AS NUMBER(18,2)) AS transactionamount,
                CAST(data_payload:GSTAmountPEL AS NUMBER(18,2)) AS gstamountpel,
                data_payload:GSTOverchargedFlag::BOOLEAN AS gstoverchargedflag,
                data_payload:FinancialYear_icare::NUMBER AS financialyear_icare,
                CAST(data_payload:Garnishee_icare AS NUMBER(18,2)) AS garnishee_icare,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                CAST(data_payload:WeeklyBenefitRate_icare AS NUMBER(18,2)) AS weeklybenefitrate_icare,
                TO_TIMESTAMP_TZ(data_payload:DateFrom_icare::NUMBER/1000) AS datefrom_icare,
                data_payload:GSTExemptFlag::BOOLEAN AS gstexemptflag,
                data_payload:CountOfWeeks_icare::NUMBER AS countofweeks_icare,
                CAST(data_payload:EarningsE_icare AS NUMBER(18,2)) AS earningse_icare,
                CAST(data_payload:ClaimForExAmount AS NUMBER(18,2)) AS claimforexamount,
                data_payload:LumpSumE_icare::BOOLEAN AS lumpsume_icare,
                data_payload:GSTApplicable_icare::NUMBER AS gstapplicable_icare,
                TO_TIMESTAMP_TZ(data_payload:DateTo_icare::NUMBER/1000) AS dateto_icare,
                data_payload:GSTDecision::NUMBER AS gstdecision,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                data_payload:PaycodeGLAggregation::NUMBER AS paycodeglaggregation,
                data_payload:PayeeRegisteredForGST::BOOLEAN AS payeeregisteredforgst,
                data_payload:Paycode_icareID::NUMBER AS paycode_icareid,
                CAST(data_payload:HoursLost_icare AS NUMBER(6,2)) AS hourslost_icare,
                data_payload:PaycodeReportAttribute_icare::NUMBER AS paycodereportattribute_icare,
                data_payload:GSTMethodPEL_Ext::NUMBER AS gstmethodpel_ext,
                data_payload:DeductibleID::NUMBER AS deductibleid,
                CAST(data_payload:PaymentCategoryCode::TEXT AS VARCHAR(30)) AS paymentcategorycode,
                data_payload:LineCategory::NUMBER AS linecategory,
                data_payload:ITCApplicable_icare::NUMBER AS itcapplicable_icare,
                CAST(data_payload:Comments::TEXT AS VARCHAR(255)) AS comments,
                data_payload:ITCDecision::NUMBER AS itcdecision,
                CAST(data_payload:GazettedAmount_icare AS NUMBER(18,2)) AS gazettedamount_icare,
                CAST(data_payload:GSTCalcRate_icare AS NUMBER(12,2)) AS gstcalcrate_icare,
                data_payload:TransactionID::NUMBER AS transactionid,
                CAST(data_payload:ReservingForExAmount AS NUMBER(18,2)) AS reservingforexamount,
                CAST(data_payload:DeemedEarningsPerWeek_icare AS NUMBER(18,2)) AS deemedearningsperweek_icare,
                CAST(data_payload:ServiceProviderID_icare::TEXT AS VARCHAR(12)) AS serviceproviderid_icare,
                CAST(data_payload:PostGarnishee_icare AS NUMBER(18,2)) AS postgarnishee_icare,
                CAST(data_payload:NoCapPAYGTax_icare AS NUMBER(18,2)) AS nocappaygtax_icare,
                data_payload:MedProviderTreatment_ExtID::NUMBER AS medprovidertreatment_extid,
                data_payload:Provider_ExtID::NUMBER AS provider_extid,
                TO_TIMESTAMP_TZ(data_payload:DateOfSurgery_Ext::NUMBER/1000) AS dateofsurgery_ext,
                data_payload:RecalculatePAYGForReissue_Ext::BOOLEAN AS recalculatepaygforreissue_ext,
                data_payload:RehabService_ExtID::NUMBER AS rehabservice_extid,
                data_payload:MaxOdgCaa_Ext::NUMBER AS maxodgcaa_ext,
                CAST(data_payload:DraftAmount_Ext AS NUMBER(18,2)) AS draftamount_ext,
                data_payload:MedDomAssist_ExtID::NUMBER AS meddomassist_extid,
                data_payload:MedTreatment_ExtID::NUMBER AS medtreatment_extid,
                CAST(data_payload:MedicationName_Ext::TEXT AS VARCHAR(256)) AS medicationname_ext,
                data_payload:DrugPrescribed_ExtID::NUMBER AS drugprescribed_extid,
                CAST(data_payload:WeeklyActualRate_Ext AS NUMBER(18,2)) AS weeklyactualrate_ext,
                CAST(data_payload:PreviousWithheldPAYG_Ext AS NUMBER(18,2)) AS previouswithheldpayg_ext,
                CAST(data_payload:PreviousPaidPreGarnishee_Ext AS NUMBER(18,2)) AS previouspaidpregarnishee_ext,
                CAST(data_payload:PreviouslyProcessedPAYCode_Ext::TEXT AS VARCHAR(10)) AS previouslyprocessedpaycode_ext,
                CAST(data_payload:CWWR_Ext AS NUMBER(18,2)) AS cwwr_ext,
                CAST(data_payload:PreviousPaidAmount_Ext AS NUMBER(18,2)) AS previouspaidamount_ext,
                CAST(data_payload:PercentageOfWeek_Ext AS NUMBER(5,2)) AS percentageofweek_ext,
                data_payload:DeductibleDM_Ext::NUMBER AS deductibledm_ext,
                data_payload:AdjustmentFlag_Ext::BOOLEAN AS adjustmentflag_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwcc', 'cc_transactionlineitem') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                CAST($1:nonpecuniarybenefitd_icare AS NUMBER(18,2)) AS nonpecuniarybenefitd_icare,
                CAST($1:reportingamount AS NUMBER(18,2)) AS reportingamount,
                CAST($1:itcaaamountpel AS NUMBER(18,2)) AS itcaaamountpel,
                CAST($1:paygtax_icare AS NUMBER(18,2)) AS paygtax_icare,
                CAST($1:grossweeklywagerate_icare AS NUMBER(18,2)) AS grossweeklywagerate_icare,
                $1:dateofservice_icare::TIMESTAMP_TZ AS dateofservice_icare,
                $1:paymentvariationreason_icare::NUMBER AS paymentvariationreason_icare,
                CAST($1:reservingamount AS NUMBER(18,2)) AS reservingamount,
                CAST($1:claimamount AS NUMBER(18,2)) AS claimamount,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                CAST($1:hourspaid_icare AS NUMBER(6,2)) AS hourspaid_icare,
                CAST($1:amountwithoutgst AS NUMBER(18,2)) AS amountwithoutgst,
                $1:id::NUMBER AS id,
                CAST($1:paycodename_icare::TEXT AS VARCHAR(20)) AS paycodename_icare,
                $1:defaultdecision::BOOLEAN AS defaultdecision,
                $1:benefitsuspended_icare::BOOLEAN AS benefitsuspended_icare,
                $1:createuserid::NUMBER AS createuserid,
                CAST($1:reportingforexamount AS NUMBER(18,2)) AS reportingforexamount,
                $1:beanversion::NUMBER AS beanversion,
                $1:retired::NUMBER AS retired,
                $1:updateuserid::NUMBER AS updateuserid,
                CAST($1:transactionamount AS NUMBER(18,2)) AS transactionamount,
                CAST($1:gstamountpel AS NUMBER(18,2)) AS gstamountpel,
                $1:gstoverchargedflag::BOOLEAN AS gstoverchargedflag,
                $1:financialyear_icare::NUMBER AS financialyear_icare,
                CAST($1:garnishee_icare AS NUMBER(18,2)) AS garnishee_icare,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                CAST($1:weeklybenefitrate_icare AS NUMBER(18,2)) AS weeklybenefitrate_icare,
                $1:datefrom_icare::TIMESTAMP_TZ AS datefrom_icare,
                $1:gstexemptflag::BOOLEAN AS gstexemptflag,
                $1:countofweeks_icare::NUMBER AS countofweeks_icare,
                CAST($1:earningse_icare AS NUMBER(18,2)) AS earningse_icare,
                CAST($1:claimforexamount AS NUMBER(18,2)) AS claimforexamount,
                $1:lumpsume_icare::BOOLEAN AS lumpsume_icare,
                $1:gstapplicable_icare::NUMBER AS gstapplicable_icare,
                $1:dateto_icare::TIMESTAMP_TZ AS dateto_icare,
                $1:gstdecision::NUMBER AS gstdecision,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:paycodeglaggregation::NUMBER AS paycodeglaggregation,
                $1:payeeregisteredforgst::BOOLEAN AS payeeregisteredforgst,
                $1:paycode_icareid::NUMBER AS paycode_icareid,
                CAST($1:hourslost_icare AS NUMBER(6,2)) AS hourslost_icare,
                $1:paycodereportattribute_icare::NUMBER AS paycodereportattribute_icare,
                $1:gstmethodpel_ext::NUMBER AS gstmethodpel_ext,
                $1:deductibleid::NUMBER AS deductibleid,
                CAST($1:paymentcategorycode::TEXT AS VARCHAR(30)) AS paymentcategorycode,
                $1:linecategory::NUMBER AS linecategory,
                $1:itcapplicable_icare::NUMBER AS itcapplicable_icare,
                CAST($1:comments::TEXT AS VARCHAR(255)) AS comments,
                $1:itcdecision::NUMBER AS itcdecision,
                CAST($1:gazettedamount_icare AS NUMBER(18,2)) AS gazettedamount_icare,
                CAST($1:gstcalcrate_icare AS NUMBER(12,2)) AS gstcalcrate_icare,
                $1:transactionid::NUMBER AS transactionid,
                CAST($1:reservingforexamount AS NUMBER(18,2)) AS reservingforexamount,
                CAST($1:deemedearningsperweek_icare AS NUMBER(18,2)) AS deemedearningsperweek_icare,
                CAST($1:serviceproviderid_icare::TEXT AS VARCHAR(12)) AS serviceproviderid_icare,
                CAST($1:postgarnishee_icare AS NUMBER(18,2)) AS postgarnishee_icare,
                CAST($1:nocappaygtax_icare AS NUMBER(18,2)) AS nocappaygtax_icare,
                $1:medprovidertreatment_extid::NUMBER AS medprovidertreatment_extid,
                $1:provider_extid::NUMBER AS provider_extid,
                $1:dateofsurgery_ext::TIMESTAMP_TZ AS dateofsurgery_ext,
                $1:recalculatepaygforreissue_ext::BOOLEAN AS recalculatepaygforreissue_ext,
                $1:rehabservice_extid::NUMBER AS rehabservice_extid,
                $1:maxodgcaa_ext::NUMBER AS maxodgcaa_ext,
                CAST($1:draftamount_ext AS NUMBER(18,2)) AS draftamount_ext,
                $1:meddomassist_extid::NUMBER AS meddomassist_extid,
                $1:medtreatment_extid::NUMBER AS medtreatment_extid,
                CAST($1:medicationname_ext::TEXT AS VARCHAR(256)) AS medicationname_ext,
                $1:drugprescribed_extid::NUMBER AS drugprescribed_extid,
                CAST($1:weeklyactualrate_ext AS NUMBER(18,2)) AS weeklyactualrate_ext,
                CAST($1:previouswithheldpayg_ext AS NUMBER(18,2)) AS previouswithheldpayg_ext,
                CAST($1:previouspaidpregarnishee_ext AS NUMBER(18,2)) AS previouspaidpregarnishee_ext,
                CAST($1:previouslyprocessedpaycode_ext::TEXT AS VARCHAR(10)) AS previouslyprocessedpaycode_ext,
                CAST($1:cwwr_ext AS NUMBER(18,2)) AS cwwr_ext,
                CAST($1:previouspaidamount_ext AS NUMBER(18,2)) AS previouspaidamount_ext,
                CAST($1:percentageofweek_ext AS NUMBER(5,2)) AS percentageofweek_ext,
                $1:deductibledm_ext::NUMBER AS deductibledm_ext,
                $1:adjustmentflag_ext::BOOLEAN AS adjustmentflag_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwcc', 'cc_transactionlineitem') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS transactionlineitem_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'nonpecuniarybenefitd_icare',
                        'reportingamount',
                        'itcaaamountpel',
                        'paygtax_icare',
                        'grossweeklywagerate_icare',
                        'dateofservice_icare',
                        'paymentvariationreason_icare',
                        'reservingamount',
                        'claimamount',
                        'updatetime',
                        'hourspaid_icare',
                        'amountwithoutgst',
                        'paycodename_icare',
                        'defaultdecision',
                        'benefitsuspended_icare',
                        'createuserid',
                        'reportingforexamount',
                        'beanversion',
                        'retired',
                        'updateuserid',
                        'transactionamount',
                        'gstamountpel',
                        'gstoverchargedflag',
                        'financialyear_icare',
                        'garnishee_icare',
                        'publicid',
                        'createtime',
                        'weeklybenefitrate_icare',
                        'datefrom_icare',
                        'gstexemptflag',
                        'countofweeks_icare',
                        'earningse_icare',
                        'claimforexamount',
                        'lumpsume_icare',
                        'gstapplicable_icare',
                        'dateto_icare',
                        'gstdecision',
                        'archivepartition',
                        'paycodeglaggregation',
                        'payeeregisteredforgst',
                        'paycode_icareid',
                        'hourslost_icare',
                        'paycodereportattribute_icare',
                        'gstmethodpel_ext',
                        'deductibleid',
                        'paymentcategorycode',
                        'linecategory',
                        'itcapplicable_icare',
                        'comments',
                        'itcdecision',
                        'gazettedamount_icare',
                        'gstcalcrate_icare',
                        'transactionid',
                        'reservingforexamount',
                        'deemedearningsperweek_icare',
                        'serviceproviderid_icare',
                        'postgarnishee_icare',
                        'nocappaygtax_icare',
                        'medprovidertreatment_extid',
                        'provider_extid',
                        'dateofsurgery_ext',
                        'recalculatepaygforreissue_ext',
                        'rehabservice_extid',
                        'maxodgcaa_ext',
                        'draftamount_ext',
                        'meddomassist_extid',
                        'medtreatment_extid',
                        'medicationname_ext',
                        'drugprescribed_extid',
                        'weeklyactualrate_ext',
                        'previouswithheldpayg_ext',
                        'previouspaidpregarnishee_ext',
                        'previouslyprocessedpaycode_ext',
                        'cwwr_ext',
                        'previouspaidamount_ext',
                        'percentageofweek_ext',
                        'deductibledm_ext',
                        'adjustmentflag_ext'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS dbt_updated_at
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}