
{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             This Converts Parquet or AVRO Data Loaded in the Variant Column in the RAW DB into Flattend Views
                                                This also creates a HASH_KEY for Incremental Tables for the Curated Layer 
                                                Additional CDA Files are Null in the AVRO but not in CDA .
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    tags=["raw_gwcc","raw_layer"]
) }}


WITH cte_source_data AS 
(

            SELECT
                TO_TIMESTAMP_TZ(data_payload:FinDocsCloseTrigger_icare::NUMBER/1000) AS findocsclosetrigger_icare,
                TO_TIMESTAMP_TZ(data_payload:ReportedDate::NUMBER/1000) AS reporteddate,
                data_payload:MainContactType::NUMBER AS maincontacttype,
                TO_TIMESTAMP_TZ(data_payload:DateFormGivenToEmp::NUMBER/1000) AS dateformgiventoemp,
                data_payload:PreviousGroupID::NUMBER AS previousgroupid,
                data_payload:SIULifeCycleState::NUMBER AS siulifecyclestate,
                data_payload:SafetyEquipProv::BOOLEAN AS safetyequipprov,
                TO_TIMESTAMP_TZ(data_payload:FlaggedDate::NUMBER/1000) AS flaggeddate,
                TO_TIMESTAMP_TZ(data_payload:ExposureBegan::NUMBER/1000) AS exposurebegan,
                data_payload:AssignedByUserID::NUMBER AS assignedbyuserid,
                data_payload:CallbackTime_icare::NUMBER AS callbacktime_icare,
                TO_TIMESTAMP_TZ(data_payload:DateRptdToAgent::NUMBER/1000) AS daterptdtoagent,
                data_payload:DiagnosticCnsistnt::BOOLEAN AS diagnosticcnsistnt,
                data_payload:Currency::NUMBER AS currency,
                TO_TIMESTAMP_TZ(data_payload:DateRptdToEmployer::NUMBER/1000) AS daterptdtoemployer,
                data_payload:LitigationStatus::NUMBER AS litigationstatus,
                TO_TIMESTAMP_TZ(data_payload:ExposureEnded::NUMBER/1000) AS exposureended,
                data_payload:PreviousQueueID::NUMBER AS previousqueueid,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                CAST(data_payload:StorageBoxNum::TEXT AS VARCHAR(10)) AS storageboxnum,
                CAST(data_payload:StateFileNumber::TEXT AS VARCHAR(20)) AS statefilenumber,
                data_payload:NextReserveWeek_icare::NUMBER AS nextreserveweek_icare,
                data_payload:OtherRecovStatus::NUMBER AS otherrecovstatus,
                data_payload:DrugsInvolved::NUMBER AS drugsinvolved,
                data_payload:ID::NUMBER AS id,
                data_payload:ISOEnabled::BOOLEAN AS isoenabled,
                TO_TIMESTAMP_TZ(data_payload:DateEligibleForArchive::NUMBER/1000) AS dateeligibleforarchive,
                CAST(data_payload:FlaggedReason::TEXT AS VARCHAR(1333)) AS flaggedreason,
                data_payload:ClaimTier::NUMBER AS claimtier,
                TO_TIMESTAMP_TZ(data_payload:ExaminationDate::NUMBER/1000) AS examinationdate,
                TO_TIMESTAMP_TZ(data_payload:CloseDate_icare::NUMBER/1000) AS closedate_icare,
                data_payload:CreateUserID::NUMBER AS createuserid,
                TO_TIMESTAMP_TZ(data_payload:DeathDate::NUMBER/1000) AS deathdate,
                CAST(data_payload:Fault AS NUMBER(4,1)) AS fault,
                TO_TIMESTAMP_TZ(data_payload:FinalisationDocsTrigger_icare::NUMBER/1000) AS finalisationdocstrigger_icare,
                data_payload:HowReported::NUMBER AS howreported,
                data_payload:ReinsuranceFlaggedStatus::NUMBER AS reinsuranceflaggedstatus,
                data_payload:IsClaimMigrated_icare::BOOLEAN AS isclaimmigrated_icare,
                data_payload:LossCause::NUMBER AS losscause,
                data_payload:TriggerTriage_icare::BOOLEAN AS triggertriage_icare,
                data_payload:BeanVersion::NUMBER AS beanversion,
                CAST(data_payload:FnolGuid_icare::TEXT AS VARCHAR(30)) AS fnolguid_icare,
                data_payload:ClaimsAgent_icare::NUMBER AS claimsagent_icare,
                TO_TIMESTAMP_TZ(data_payload:ReOpenDate::NUMBER/1000) AS reopendate,
                data_payload:Progress::NUMBER AS progress,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                data_payload:ModifiedDutyAvail::BOOLEAN AS modifieddutyavail,
                TO_TIMESTAMP_TZ(data_payload:InsurerSentMPNNotice::NUMBER/1000) AS insurersentmpnnotice,
                data_payload:Segment::NUMBER AS segment,
                data_payload:LocationOfTheft::NUMBER AS locationoftheft,
                data_payload:StorageType::NUMBER AS storagetype,
                data_payload:EmployerSize_icare::NUMBER AS employersize_icare,
                data_payload:EmpQusValidity::NUMBER AS empqusvalidity,
                TO_TIMESTAMP_TZ(data_payload:TriggerAssessReminderDate::NUMBER/1000) AS triggerassessreminderdate,
                TO_TIMESTAMP_TZ(data_payload:DateCompDcsnDue::NUMBER/1000) AS datecompdcsndue,
                data_payload:FaultRating::NUMBER AS faultrating,
                TO_TIMESTAMP_TZ(data_payload:NewDateofLoss_icare::NUMBER/1000) AS newdateofloss_icare,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                CAST(data_payload:WICDescription_icare::TEXT AS VARCHAR(255)) AS wicdescription_icare,
                TO_TIMESTAMP_TZ(data_payload:ClaimantRprtdDate::NUMBER/1000) AS claimantrprtddate,
                CAST(data_payload:NavigatorClaimNumber_icare::TEXT AS VARCHAR(19)) AS navigatorclaimnumber_icare,
                TO_TIMESTAMP_TZ(data_payload:CommonLawDateFlaged_icare::NUMBER/1000) AS commonlawdateflaged_icare,
                data_payload:AssignedGroupID::NUMBER AS assignedgroupid,
                data_payload:IsEditableByPortal_icare::BOOLEAN AS iseditablebyportal_icare,
                TO_TIMESTAMP_TZ(data_payload:LossDate::NUMBER/1000) AS lossdate,
                data_payload:SupplementalWorkloadWeight::NUMBER AS supplementalworkloadweight,
                TO_TIMESTAMP_TZ(data_payload:TriggerTriageDate_icare::NUMBER/1000) AS triggertriagedate_icare,
                data_payload:ClaimSource::NUMBER AS claimsource,
                data_payload:SIEscalateSIU::NUMBER AS siescalatesiu,
                data_payload:SalvageStatus::NUMBER AS salvagestatus,
                data_payload:Flagged::NUMBER AS flagged,
                data_payload:ComputerSecurity::BOOLEAN AS computersecurity,
                data_payload:SafetyEquipUsed::BOOLEAN AS safetyequipused,
                data_payload:AssignedQueueID::NUMBER AS assignedqueueid,
                data_payload:StorageLocationState::NUMBER AS storagelocationstate,
                TO_TIMESTAMP_TZ(data_payload:EmpSentMPNNotice::NUMBER/1000) AS empsentmpnnotice,
                data_payload:EmploymentInjury::BOOLEAN AS employmentinjury,
                TO_TIMESTAMP_TZ(data_payload:WorkloadUpdated::NUMBER/1000) AS workloadupdated,
                data_payload:ClosedOutcome::NUMBER AS closedoutcome,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                TO_TIMESTAMP_TZ(data_payload:ISOReceiveDate::NUMBER/1000) AS isoreceivedate,
                CAST(data_payload:TempClaimNumber_icare::TEXT AS VARCHAR(40)) AS tempclaimnumber_icare,
                data_payload:InsuredPremises::BOOLEAN AS insuredpremises,
                TO_TIMESTAMP_TZ(data_payload:InjWkrInMPN::NUMBER/1000) AS injwkrinmpn,
                data_payload:PermissionRequired::NUMBER AS permissionrequired,
                CAST(data_payload:EmployerValidityReason::TEXT AS VARCHAR(255)) AS employervalidityreason,
                data_payload:Strategy::NUMBER AS strategy,
                data_payload:AssignedUserID::NUMBER AS assigneduserid,
                data_payload:StorageCategory::NUMBER AS storagecategory,
                data_payload:PTPinMPN::BOOLEAN AS ptpinmpn,
                TO_TIMESTAMP_TZ(data_payload:DateMade_icare::NUMBER/1000) AS datemade_icare,
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                TO_TIMESTAMP_TZ(data_payload:StatuteDate::NUMBER/1000) AS statutedate,
                data_payload:InjuredOnPremises::BOOLEAN AS injuredonpremises,
                TO_TIMESTAMP_TZ(data_payload:DateFormRetByEmp::NUMBER/1000) AS dateformretbyemp,
                data_payload:InsuredDenormID::NUMBER AS insureddenormid,
                data_payload:TreatedPatientBfr::BOOLEAN AS treatedpatientbfr,
                CAST(data_payload:ClaimNumber::TEXT AS VARCHAR(40)) AS claimnumber,
                TO_TIMESTAMP_TZ(data_payload:SIEscalateSIUdate::NUMBER/1000) AS siescalatesiudate,
                data_payload:IncidentReport::BOOLEAN AS incidentreport,
                data_payload:PreexDisblty::BOOLEAN AS preexdisblty,
                data_payload:TriggerAssessReminder::BOOLEAN AS triggerassessreminder,
                data_payload:ITCChangedFlagPEL::BOOLEAN AS itcchangedflagpel,
                data_payload:BranchInsurer_icare::NUMBER AS branchinsurer_icare,
                data_payload:HospitalDays::NUMBER AS hospitaldays,
                CAST(data_payload:PoliceDeptInfo::TEXT AS VARCHAR(255)) AS policedeptinfo,
                data_payload:State::NUMBER AS state,
                data_payload:SIUStatus::NUMBER AS siustatus,
                data_payload:DoNotDestroy::BOOLEAN AS donotdestroy,
                data_payload:FirstNoticeSuit::BOOLEAN AS firstnoticesuit,
                data_payload:Mold::BOOLEAN AS mold,
                data_payload:ReopenedReason::NUMBER AS reopenedreason,
                CAST(data_payload:StateAckNumber::TEXT AS VARCHAR(20)) AS stateacknumber,
                CAST(data_payload:TotalITCAAPEL AS NUMBER(18,2)) AS totalitcaapel,
                data_payload:ReportedByType::NUMBER AS reportedbytype,
                TO_TIMESTAMP_TZ(data_payload:CloseDate::NUMBER/1000) AS closedate,
                data_payload:Retired::NUMBER AS retired,
                TO_TIMESTAMP_TZ(data_payload:StorageDate::NUMBER/1000) AS storagedate,
                CAST(data_payload:FireDeptInfo::TEXT AS VARCHAR(255)) AS firedeptinfo,
                data_payload:ValidationLevel::NUMBER AS validationlevel,
                data_payload:LOBCode::NUMBER AS lobcode,
                data_payload:WorkloadWeight::NUMBER AS workloadweight,
                data_payload:JurisdictionState::NUMBER AS jurisdictionstate,
                data_payload:ConcurrentEmp::NUMBER AS concurrentemp,
                data_payload:SharedClaim_icare::NUMBER AS sharedclaim_icare,
                TO_TIMESTAMP_TZ(data_payload:DateRptdToInsured::NUMBER/1000) AS daterptdtoinsured,
                data_payload:ISOStatus::NUMBER AS isostatus,
                data_payload:LiabilityStatusDenorm_icare::NUMBER AS liabilitystatusdenorm_icare,
                data_payload:WeatherRelated::BOOLEAN AS weatherrelated,
                TO_TIMESTAMP_TZ(data_payload:ISOSendDate::NUMBER/1000) AS isosenddate,
                data_payload:LocationCodeID::NUMBER AS locationcodeid,
                CAST(data_payload:StorageVolumes::TEXT AS VARCHAR(10)) AS storagevolumes,
                data_payload:CatastropheID::NUMBER AS catastropheid,
                CAST(data_payload:StorageBarCodeNum::TEXT AS VARCHAR(10)) AS storagebarcodenum,
                data_payload:InjuredRegularJob::BOOLEAN AS injuredregularjob,
                data_payload:ClaimantDenormID::NUMBER AS claimantdenormid,
                CAST(data_payload:ClaimHash_icare::TEXT AS VARCHAR(30)) AS claimhash_icare,
                CAST(data_payload:LossLocationCode::TEXT AS VARCHAR(5)) AS losslocationcode,
                data_payload:BenefitsStatusDcsn::BOOLEAN AS benefitsstatusdcsn,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                data_payload:AccidentType::NUMBER AS accidenttype,
                data_payload:PolicyID::NUMBER AS policyid,
                TO_TIMESTAMP_TZ(data_payload:ManifestationDate::NUMBER/1000) AS manifestationdate,
                data_payload:FurtherTreatment::BOOLEAN AS furthertreatment,
                data_payload:ReinsuranceReportable::BOOLEAN AS reinsurancereportable,
                data_payload:ODGMedDiagnosis::NUMBER AS odgmeddiagnosis,
                TO_TIMESTAMP_TZ(data_payload:PurgeDate::NUMBER/1000) AS purgedate,
                data_payload:PreviousUserID::NUMBER AS previoususerid,
                data_payload:LossType::NUMBER AS losstype,
                data_payload:ISOKnown::BOOLEAN AS isoknown,
                CAST(data_payload:AgencyId::TEXT AS VARCHAR(9)) AS agencyid,
                TO_TIMESTAMP_TZ(data_payload:HospitalDate::NUMBER/1000) AS hospitaldate,
                CAST(data_payload:LossLocationSpatialDenorm::TEXT AS VARCHAR(16777216)) AS losslocationspatialdenorm,
                CAST(data_payload:TriageRiskScore_icare::TEXT AS VARCHAR(255)) AS triageriskscore_icare,
                data_payload:ShowMedicalFirstInfo::NUMBER AS showmedicalfirstinfo,
                TO_TIMESTAMP_TZ(data_payload:DateCompDcsnMade::NUMBER/1000) AS datecompdcsnmade,
                data_payload:LockingColumn::NUMBER AS lockingcolumn,
                data_payload:CurrentConditions::BOOLEAN AS currentconditions,
                data_payload:CoverageInQuestion::BOOLEAN AS coverageinquestion,
                data_payload:LossLocationID::NUMBER AS losslocationid,
                data_payload:Weather::NUMBER AS weather,
                TO_TIMESTAMP_TZ(data_payload:MMIdate::NUMBER/1000) AS mmidate,
                data_payload:ClaimWorkCompID::NUMBER AS claimworkcompid,
                TO_TIMESTAMP_TZ(data_payload:AssignmentDate::NUMBER/1000) AS assignmentdate,
                data_payload:LargeLossNotificationStatus::NUMBER AS largelossnotificationstatus,
                CAST(data_payload:Description::TEXT AS VARCHAR(1333)) AS description,
                data_payload:SIScore::NUMBER AS siscore,
                data_payload:AssignmentStatus::NUMBER AS assignmentstatus,
                data_payload:HazardousWaste::BOOLEAN AS hazardouswaste,
                data_payload:LodgingAgent_icare::NUMBER AS lodgingagent_icare,
                data_payload:ReimbSchAgrmnt_icare::NUMBER AS reimbschagrmnt_icare,
                data_payload:Funding_icare::NUMBER AS funding_icare,
                data_payload:ManagingEntity_icare::NUMBER AS managingentity_icare,
                data_payload:ExternalIdentifier_icareID::NUMBER AS externalidentifier_icareid,
                data_payload:GenerateIMPFlag_Ext::BOOLEAN AS generateimpflag_ext,
                CAST(data_payload:SIRAClaimNumber_Ext::TEXT AS VARCHAR(40)) AS siraclaimnumber_ext,
                CAST(data_payload:OtherCostCenter_Ext::TEXT AS VARCHAR(500)) AS othercostcenter_ext,
                data_payload:ReopenExpOnClosedClaim_Ext::BOOLEAN AS reopenexponclosedclaim_ext,
                data_payload:IsCovidClaim_Ext::BOOLEAN AS iscovidclaim_ext,
                CAST(data_payload:ExternalFactorsImpact_Ext::TEXT AS VARCHAR(40)) AS externalfactorsimpact_ext,
                CAST(data_payload:ExternalFactorsEvent_Ext::TEXT AS VARCHAR(40)) AS externalfactorsevent_ext,
                data_payload:ClaimSLM_ExtID::NUMBER AS claimslm_extid,
                data_payload:NulledClaim_Ext::BOOLEAN AS nulledclaim_ext,
                data_payload:Organization_ExtID::NUMBER AS organization_extid,
                data_payload:IsConflictOfInterest_Ext::BOOLEAN AS isconflictofinterest_ext,
                data_payload:ClaimTransferDetails_ExtID::NUMBER AS claimtransferdetails_extid,
                TO_TIMESTAMP_TZ(data_payload:PoliceAttestationDate_Ext::NUMBER/1000) AS policeattestationdate_ext,
                data_payload:ReasonForExempt_Ext::NUMBER AS reasonforexempt_ext,
                data_payload:ClaimType_Ext::NUMBER AS claimtype_ext,
                data_payload:AppendSIRASuffix_Ext::BOOLEAN AS appendsirasuffix_ext,
                TO_TIMESTAMP_TZ(data_payload:LegacyCreateTime_Ext::NUMBER/1000) AS legacycreatetime_ext,
                data_payload:TransitionOutcome_Ext::NUMBER AS transitionoutcome_ext,
                TO_TIMESTAMP_TZ(data_payload:TransitionDecisionDate_Ext::NUMBER/1000) AS transitiondecisiondate_ext,
                data_payload:IsClaimImported_Ext::BOOLEAN AS isclaimimported_ext,
                TO_TIMESTAMP_TZ(data_payload:ImportDate_Ext::NUMBER/1000) AS importdate_ext,
                data_payload:IsStaffClaim_Ext::BOOLEAN AS isstaffclaim_ext,
                CAST(data_payload:ReferenceCostCentreName_Ext::TEXT AS VARCHAR(255)) AS referencecostcentrename_ext,
                CAST(data_payload:AgencyCostCentreName_Ext::TEXT AS VARCHAR(255)) AS agencycostcentrename_ext,
                CAST(data_payload:ReferenceCostCentreCode_Ext::TEXT AS VARCHAR(255)) AS referencecostcentrecode_ext,
                CAST(data_payload:AgencyCostCentreCode_Ext::TEXT AS VARCHAR(255)) AS agencycostcentrecode_ext,
                CAST(data_payload:SecRefCostCentreCode_Ext::TEXT AS VARCHAR(255)) AS secrefcostcentrecode_ext,
                CAST(data_payload:SecRefCostCentreName_Ext::TEXT AS VARCHAR(255)) AS secrefcostcentrename_ext,
                CAST(data_payload:SecAgencyCostCentreCode_Ext::TEXT AS VARCHAR(255)) AS secagencycostcentrecode_ext,
                CAST(data_payload:SecAgencyCostCentreName_Ext::TEXT AS VARCHAR(255)) AS secagencycostcentrename_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwcc', 'cc_claim') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:findocsclosetrigger_icare::TIMESTAMP_TZ AS findocsclosetrigger_icare,
                $1:reporteddate::TIMESTAMP_TZ AS reporteddate,
                $1:maincontacttype::NUMBER AS maincontacttype,
                $1:dateformgiventoemp::TIMESTAMP_TZ AS dateformgiventoemp,
                $1:previousgroupid::NUMBER AS previousgroupid,
                $1:siulifecyclestate::NUMBER AS siulifecyclestate,
                $1:safetyequipprov::BOOLEAN AS safetyequipprov,
                $1:flaggeddate::TIMESTAMP_TZ AS flaggeddate,
                $1:exposurebegan::TIMESTAMP_TZ AS exposurebegan,
                $1:assignedbyuserid::NUMBER AS assignedbyuserid,
                $1:callbacktime_icare::NUMBER AS callbacktime_icare,
                $1:daterptdtoagent::TIMESTAMP_TZ AS daterptdtoagent,
                $1:diagnosticcnsistnt::BOOLEAN AS diagnosticcnsistnt,
                $1:currency::NUMBER AS currency,
                $1:daterptdtoemployer::TIMESTAMP_TZ AS daterptdtoemployer,
                $1:litigationstatus::NUMBER AS litigationstatus,
                $1:exposureended::TIMESTAMP_TZ AS exposureended,
                $1:previousqueueid::NUMBER AS previousqueueid,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                CAST($1:storageboxnum::TEXT AS VARCHAR(10)) AS storageboxnum,
                CAST($1:statefilenumber::TEXT AS VARCHAR(20)) AS statefilenumber,
                $1:nextreserveweek_icare::NUMBER AS nextreserveweek_icare,
                $1:otherrecovstatus::NUMBER AS otherrecovstatus,
                $1:drugsinvolved::NUMBER AS drugsinvolved,
                $1:id::NUMBER AS id,
                $1:isoenabled::BOOLEAN AS isoenabled,
                $1:dateeligibleforarchive::TIMESTAMP_TZ AS dateeligibleforarchive,
                CAST($1:flaggedreason::TEXT AS VARCHAR(1333)) AS flaggedreason,
                $1:claimtier::NUMBER AS claimtier,
                $1:examinationdate::TIMESTAMP_TZ AS examinationdate,
                $1:closedate_icare::TIMESTAMP_TZ AS closedate_icare,
                $1:createuserid::NUMBER AS createuserid,
                $1:deathdate::TIMESTAMP_TZ AS deathdate,
                CAST($1:fault AS NUMBER(4,1)) AS fault,
                $1:finalisationdocstrigger_icare::TIMESTAMP_TZ AS finalisationdocstrigger_icare,
                $1:howreported::NUMBER AS howreported,
                $1:reinsuranceflaggedstatus::NUMBER AS reinsuranceflaggedstatus,
                $1:isclaimmigrated_icare::BOOLEAN AS isclaimmigrated_icare,
                $1:losscause::NUMBER AS losscause,
                $1:triggertriage_icare::BOOLEAN AS triggertriage_icare,
                $1:beanversion::NUMBER AS beanversion,
                CAST($1:fnolguid_icare::TEXT AS VARCHAR(30)) AS fnolguid_icare,
                $1:claimsagent_icare::NUMBER AS claimsagent_icare,
                $1:reopendate::TIMESTAMP_TZ AS reopendate,
                $1:progress::NUMBER AS progress,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:modifieddutyavail::BOOLEAN AS modifieddutyavail,
                $1:insurersentmpnnotice::TIMESTAMP_TZ AS insurersentmpnnotice,
                $1:segment::NUMBER AS segment,
                $1:locationoftheft::NUMBER AS locationoftheft,
                $1:storagetype::NUMBER AS storagetype,
                $1:employersize_icare::NUMBER AS employersize_icare,
                $1:empqusvalidity::NUMBER AS empqusvalidity,
                $1:triggerassessreminderdate::TIMESTAMP_TZ AS triggerassessreminderdate,
                $1:datecompdcsndue::TIMESTAMP_TZ AS datecompdcsndue,
                $1:faultrating::NUMBER AS faultrating,
                $1:newdateofloss_icare::TIMESTAMP_TZ AS newdateofloss_icare,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                CAST($1:wicdescription_icare::TEXT AS VARCHAR(255)) AS wicdescription_icare,
                $1:claimantrprtddate::TIMESTAMP_TZ AS claimantrprtddate,
                CAST($1:navigatorclaimnumber_icare::TEXT AS VARCHAR(19)) AS navigatorclaimnumber_icare,
                $1:commonlawdateflaged_icare::TIMESTAMP_TZ AS commonlawdateflaged_icare,
                $1:assignedgroupid::NUMBER AS assignedgroupid,
                $1:iseditablebyportal_icare::BOOLEAN AS iseditablebyportal_icare,
                $1:lossdate::TIMESTAMP_TZ AS lossdate,
                $1:supplementalworkloadweight::NUMBER AS supplementalworkloadweight,
                $1:triggertriagedate_icare::TIMESTAMP_TZ AS triggertriagedate_icare,
                $1:claimsource::NUMBER AS claimsource,
                $1:siescalatesiu::NUMBER AS siescalatesiu,
                $1:salvagestatus::NUMBER AS salvagestatus,
                $1:flagged::NUMBER AS flagged,
                $1:computersecurity::BOOLEAN AS computersecurity,
                $1:safetyequipused::BOOLEAN AS safetyequipused,
                $1:assignedqueueid::NUMBER AS assignedqueueid,
                $1:storagelocationstate::NUMBER AS storagelocationstate,
                $1:empsentmpnnotice::TIMESTAMP_TZ AS empsentmpnnotice,
                $1:employmentinjury::BOOLEAN AS employmentinjury,
                $1:workloadupdated::TIMESTAMP_TZ AS workloadupdated,
                $1:closedoutcome::NUMBER AS closedoutcome,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:isoreceivedate::TIMESTAMP_TZ AS isoreceivedate,
                CAST($1:tempclaimnumber_icare::TEXT AS VARCHAR(40)) AS tempclaimnumber_icare,
                $1:insuredpremises::BOOLEAN AS insuredpremises,
                $1:injwkrinmpn::TIMESTAMP_TZ AS injwkrinmpn,
                $1:permissionrequired::NUMBER AS permissionrequired,
                CAST($1:employervalidityreason::TEXT AS VARCHAR(255)) AS employervalidityreason,
                $1:strategy::NUMBER AS strategy,
                $1:assigneduserid::NUMBER AS assigneduserid,
                $1:storagecategory::NUMBER AS storagecategory,
                $1:ptpinmpn::BOOLEAN AS ptpinmpn,
                $1:datemade_icare::TIMESTAMP_TZ AS datemade_icare,
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:statutedate::TIMESTAMP_TZ AS statutedate,
                $1:injuredonpremises::BOOLEAN AS injuredonpremises,
                $1:dateformretbyemp::TIMESTAMP_TZ AS dateformretbyemp,
                $1:insureddenormid::NUMBER AS insureddenormid,
                $1:treatedpatientbfr::BOOLEAN AS treatedpatientbfr,
                CAST($1:claimnumber::TEXT AS VARCHAR(40)) AS claimnumber,
                $1:siescalatesiudate::TIMESTAMP_TZ AS siescalatesiudate,
                $1:incidentreport::BOOLEAN AS incidentreport,
                $1:preexdisblty::BOOLEAN AS preexdisblty,
                $1:triggerassessreminder::BOOLEAN AS triggerassessreminder,
                $1:itcchangedflagpel::BOOLEAN AS itcchangedflagpel,
                $1:branchinsurer_icare::NUMBER AS branchinsurer_icare,
                $1:hospitaldays::NUMBER AS hospitaldays,
                CAST($1:policedeptinfo::TEXT AS VARCHAR(255)) AS policedeptinfo,
                $1:state::NUMBER AS state,
                $1:siustatus::NUMBER AS siustatus,
                $1:donotdestroy::BOOLEAN AS donotdestroy,
                $1:firstnoticesuit::BOOLEAN AS firstnoticesuit,
                $1:mold::BOOLEAN AS mold,
                $1:reopenedreason::NUMBER AS reopenedreason,
                CAST($1:stateacknumber::TEXT AS VARCHAR(20)) AS stateacknumber,
                CAST($1:totalitcaapel AS NUMBER(18,2)) AS totalitcaapel,
                $1:reportedbytype::NUMBER AS reportedbytype,
                $1:closedate::TIMESTAMP_TZ AS closedate,
                $1:retired::NUMBER AS retired,
                $1:storagedate::TIMESTAMP_TZ AS storagedate,
                CAST($1:firedeptinfo::TEXT AS VARCHAR(255)) AS firedeptinfo,
                $1:validationlevel::NUMBER AS validationlevel,
                $1:lobcode::NUMBER AS lobcode,
                $1:workloadweight::NUMBER AS workloadweight,
                $1:jurisdictionstate::NUMBER AS jurisdictionstate,
                $1:concurrentemp::NUMBER AS concurrentemp,
                $1:sharedclaim_icare::NUMBER AS sharedclaim_icare,
                $1:daterptdtoinsured::TIMESTAMP_TZ AS daterptdtoinsured,
                $1:isostatus::NUMBER AS isostatus,
                $1:liabilitystatusdenorm_icare::NUMBER AS liabilitystatusdenorm_icare,
                $1:weatherrelated::BOOLEAN AS weatherrelated,
                $1:isosenddate::TIMESTAMP_TZ AS isosenddate,
                $1:locationcodeid::NUMBER AS locationcodeid,
                CAST($1:storagevolumes::TEXT AS VARCHAR(10)) AS storagevolumes,
                $1:catastropheid::NUMBER AS catastropheid,
                CAST($1:storagebarcodenum::TEXT AS VARCHAR(10)) AS storagebarcodenum,
                $1:injuredregularjob::BOOLEAN AS injuredregularjob,
                $1:claimantdenormid::NUMBER AS claimantdenormid,
                CAST($1:claimhash_icare::TEXT AS VARCHAR(30)) AS claimhash_icare,
                CAST($1:losslocationcode::TEXT AS VARCHAR(5)) AS losslocationcode,
                $1:benefitsstatusdcsn::BOOLEAN AS benefitsstatusdcsn,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:accidenttype::NUMBER AS accidenttype,
                $1:policyid::NUMBER AS policyid,
                $1:manifestationdate::TIMESTAMP_TZ AS manifestationdate,
                $1:furthertreatment::BOOLEAN AS furthertreatment,
                $1:reinsurancereportable::BOOLEAN AS reinsurancereportable,
                $1:odgmeddiagnosis::NUMBER AS odgmeddiagnosis,
                $1:purgedate::TIMESTAMP_TZ AS purgedate,
                $1:previoususerid::NUMBER AS previoususerid,
                $1:losstype::NUMBER AS losstype,
                $1:isoknown::BOOLEAN AS isoknown,
                CAST($1:agencyid::TEXT AS VARCHAR(9)) AS agencyid,
                $1:hospitaldate::TIMESTAMP_TZ AS hospitaldate,
                CAST($1:losslocationspatialdenorm::TEXT AS VARCHAR(16777216)) AS losslocationspatialdenorm,
                CAST($1:triageriskscore_icare::TEXT AS VARCHAR(255)) AS triageriskscore_icare,
                $1:showmedicalfirstinfo::NUMBER AS showmedicalfirstinfo,
                $1:datecompdcsnmade::TIMESTAMP_TZ AS datecompdcsnmade,
                $1:lockingcolumn::NUMBER AS lockingcolumn,
                $1:currentconditions::BOOLEAN AS currentconditions,
                $1:coverageinquestion::BOOLEAN AS coverageinquestion,
                $1:losslocationid::NUMBER AS losslocationid,
                $1:weather::NUMBER AS weather,
                $1:mmidate::TIMESTAMP_TZ AS mmidate,
                $1:claimworkcompid::NUMBER AS claimworkcompid,
                $1:assignmentdate::TIMESTAMP_TZ AS assignmentdate,
                $1:largelossnotificationstatus::NUMBER AS largelossnotificationstatus,
                CAST($1:description::TEXT AS VARCHAR(1333)) AS description,
                $1:siscore::NUMBER AS siscore,
                $1:assignmentstatus::NUMBER AS assignmentstatus,
                $1:hazardouswaste::BOOLEAN AS hazardouswaste,
                $1:lodgingagent_icare::NUMBER AS lodgingagent_icare,
                $1:reimbschagrmnt_icare::NUMBER AS reimbschagrmnt_icare,
                $1:funding_icare::NUMBER AS funding_icare,
                $1:managingentity_icare::NUMBER AS managingentity_icare,
                $1:externalidentifier_icareid::NUMBER AS externalidentifier_icareid,
                $1:generateimpflag_ext::BOOLEAN AS generateimpflag_ext,
                CAST($1:siraclaimnumber_ext::TEXT AS VARCHAR(40)) AS siraclaimnumber_ext,
                CAST($1:othercostcenter_ext::TEXT AS VARCHAR(500)) AS othercostcenter_ext,
                $1:reopenexponclosedclaim_ext::BOOLEAN AS reopenexponclosedclaim_ext,
                $1:iscovidclaim_ext::BOOLEAN AS iscovidclaim_ext,
                CAST($1:externalfactorsimpact_ext::TEXT AS VARCHAR(40)) AS externalfactorsimpact_ext,
                CAST($1:externalfactorsevent_ext::TEXT AS VARCHAR(40)) AS externalfactorsevent_ext,
                $1:claimslm_extid::NUMBER AS claimslm_extid,
                $1:nulledclaim_ext::BOOLEAN AS nulledclaim_ext,
                $1:organization_extid::NUMBER AS organization_extid,
                $1:isconflictofinterest_ext::BOOLEAN AS isconflictofinterest_ext,
                $1:claimtransferdetails_extid::NUMBER AS claimtransferdetails_extid,
                $1:policeattestationdate_ext::TIMESTAMP_TZ AS policeattestationdate_ext,
                $1:reasonforexempt_ext::NUMBER AS reasonforexempt_ext,
                $1:claimtype_ext::NUMBER AS claimtype_ext,
                $1:appendsirasuffix_ext::BOOLEAN AS appendsirasuffix_ext,
                $1:legacycreatetime_ext::TIMESTAMP_TZ AS legacycreatetime_ext,
                $1:transitionoutcome_ext::NUMBER AS transitionoutcome_ext,
                $1:transitiondecisiondate_ext::TIMESTAMP_TZ AS transitiondecisiondate_ext,
                $1:isclaimimported_ext::BOOLEAN AS isclaimimported_ext,
                $1:importdate_ext::TIMESTAMP_TZ AS importdate_ext,
                $1:isstaffclaim_ext::BOOLEAN AS isstaffclaim_ext,
                CAST($1:referencecostcentrename_ext::TEXT AS VARCHAR(255)) AS referencecostcentrename_ext,
                CAST($1:agencycostcentrename_ext::TEXT AS VARCHAR(255)) AS agencycostcentrename_ext,
                CAST($1:referencecostcentrecode_ext::TEXT AS VARCHAR(255)) AS referencecostcentrecode_ext,
                CAST($1:agencycostcentrecode_ext::TEXT AS VARCHAR(255)) AS agencycostcentrecode_ext,
                CAST($1:secrefcostcentrecode_ext::TEXT AS VARCHAR(255)) AS secrefcostcentrecode_ext,
                CAST($1:secrefcostcentrename_ext::TEXT AS VARCHAR(255)) AS secrefcostcentrename_ext,
                CAST($1:secagencycostcentrecode_ext::TEXT AS VARCHAR(255)) AS secagencycostcentrecode_ext,
                CAST($1:secagencycostcentrename_ext::TEXT AS VARCHAR(255)) AS secagencycostcentrename_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwcc', 'cc_claim') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),
{#-
    Driving CTE Over 
    Transformed CTE is To Create the HASH_KEY Based on the Right Combination
-#}   
cte_transformed AS (
    SELECT
        *,
        CASE
             WHEN file_type = 'AVRO' THEN
                {{ dbt_utils.generate_surrogate_key([
                                'findocsclosetrigger_icare',
                        'reporteddate',
                        'maincontacttype',
                        'dateformgiventoemp',
                        'previousgroupid',
                        'siulifecyclestate',
                        'safetyequipprov',
                        'flaggeddate',
                        'exposurebegan',
                        'assignedbyuserid',
                        'callbacktime_icare',
                        'daterptdtoagent',
                        'diagnosticcnsistnt',
                        'currency',
                        'daterptdtoemployer',
                        'litigationstatus',
                        'exposureended',
                        'previousqueueid',
                        'updatetime',
                        'storageboxnum',
                        'statefilenumber',
                        'nextreserveweek_icare',
                        'otherrecovstatus',
                        'drugsinvolved',
                        'id',
                        'isoenabled',
                        'dateeligibleforarchive',
                        'flaggedreason',
                        'claimtier',
                        'examinationdate',
                        'closedate_icare',
                        'createuserid',
                        'deathdate',
                        'fault',
                        'finalisationdocstrigger_icare',
                        'howreported',
                        'reinsuranceflaggedstatus',
                        'isclaimmigrated_icare',
                        'losscause',
                        'triggertriage_icare',
                        'beanversion',
                        'fnolguid_icare',
                        'claimsagent_icare',
                        'reopendate',
                        'progress',
                        'updateuserid',
                        'modifieddutyavail',
                        'insurersentmpnnotice',
                        'segment',
                        'locationoftheft',
                        'storagetype',
                        'employersize_icare',
                        'empqusvalidity',
                        'triggerassessreminderdate',
                        'datecompdcsndue',
                        'faultrating',
                        'newdateofloss_icare',
                        'publicid',
                        'wicdescription_icare',
                        'claimantrprtddate',
                        'navigatorclaimnumber_icare',
                        'commonlawdateflaged_icare',
                        'assignedgroupid',
                        'iseditablebyportal_icare',
                        'lossdate',
                        'supplementalworkloadweight',
                        'triggertriagedate_icare',
                        'claimsource',
                        'siescalatesiu',
                        'salvagestatus',
                        'flagged',
                        'computersecurity',
                        'safetyequipused',
                        'assignedqueueid',
                        'storagelocationstate',
                        'empsentmpnnotice',
                        'employmentinjury',
                        'workloadupdated',
                        'closedoutcome',
                        'archivepartition',
                        'isoreceivedate',
                        'tempclaimnumber_icare',
                        'insuredpremises',
                        'injwkrinmpn',
                        'permissionrequired',
                        'employervalidityreason',
                        'strategy',
                        'assigneduserid',
                        'storagecategory',
                        'ptpinmpn',
                        'datemade_icare',
                        'loadcommandid',
                        'statutedate',
                        'injuredonpremises',
                        'dateformretbyemp',
                        'insureddenormid',
                        'treatedpatientbfr',
                        'claimnumber',
                        'siescalatesiudate',
                        'incidentreport',
                        'preexdisblty',
                        'triggerassessreminder',
                        'itcchangedflagpel',
                        'branchinsurer_icare',
                        'hospitaldays',
                        'policedeptinfo',
                        'state',
                        'siustatus',
                        'donotdestroy',
                        'firstnoticesuit',
                        'mold',
                        'reopenedreason',
                        'stateacknumber',
                        'totalitcaapel',
                        'reportedbytype',
                        'closedate',
                        'retired',
                        'storagedate',
                        'firedeptinfo',
                        'validationlevel',
                        'lobcode',
                        'workloadweight',
                        'jurisdictionstate',
                        'concurrentemp',
                        'sharedclaim_icare',
                        'daterptdtoinsured',
                        'isostatus',
                        'liabilitystatusdenorm_icare',
                        'weatherrelated',
                        'isosenddate',
                        'locationcodeid',
                        'storagevolumes',
                        'catastropheid',
                        'storagebarcodenum',
                        'injuredregularjob',
                        'claimantdenormid',
                        'claimhash_icare',
                        'losslocationcode',
                        'benefitsstatusdcsn',
                        'createtime',
                        'accidenttype',
                        'policyid',
                        'manifestationdate',
                        'furthertreatment',
                        'reinsurancereportable',
                        'odgmeddiagnosis',
                        'purgedate',
                        'previoususerid',
                        'losstype',
                        'isoknown',
                        'agencyid',
                        'hospitaldate',
                        'losslocationspatialdenorm',
                        'triageriskscore_icare',
                        'showmedicalfirstinfo',
                        'datecompdcsnmade',
                        'lockingcolumn',
                        'currentconditions',
                        'coverageinquestion',
                        'losslocationid',
                        'weather',
                        'mmidate',
                        'claimworkcompid',
                        'assignmentdate',
                        'largelossnotificationstatus',
                        'description',
                        'siscore',
                        'assignmentstatus',
                        'hazardouswaste',
                        'lodgingagent_icare',
                        'reimbschagrmnt_icare',
                        'funding_icare',
                        'managingentity_icare',
                        'externalidentifier_icareid',
                        'generateimpflag_ext',
                        'siraclaimnumber_ext',
                        'othercostcenter_ext',
                        'reopenexponclosedclaim_ext',
                        'iscovidclaim_ext',
                        'externalfactorsimpact_ext',
                        'externalfactorsevent_ext',
                        'claimslm_extid',
                        'nulledclaim_ext',
                        'organization_extid',
                        'isconflictofinterest_ext',
                        'claimtransferdetails_extid',
                        'policeattestationdate_ext',
                        'reasonforexempt_ext',
                        'claimtype_ext',
                        'appendsirasuffix_ext',
                        'legacycreatetime_ext',
                        'transitionoutcome_ext',
                        'transitiondecisiondate_ext',
                        'isclaimimported_ext',
                        'importdate_ext',
                        'isstaffclaim_ext',
                        'referencecostcentrename_ext',
                        'agencycostcentrename_ext',
                        'referencecostcentrecode_ext',
                        'agencycostcentrecode_ext',
                        'secrefcostcentrecode_ext',
                        'secrefcostcentrename_ext',
                        'secagencycostcentrecode_ext',
                        'secagencycostcentrename_ext'
                        ]) }}
            WHEN file_type = 'PARQUET' THEN
                {{ dbt_utils.generate_surrogate_key([
                                'id',
                        'gwcbi_seqval'
                        ]) }}
        END AS hash_key    
    FROM cte_source_data
)
SELECT * FROM cte_transformed
        