
{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             This Converts Parquet or AVRO Data Loaded in the Variant Column in the RAW DB into Flattend Views
                                                This also creates a HASH_KEY for Incremental Tables for the Curated Layer 
                                                Additional CDA Files are Null in the AVRO but not in CDA .
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    tags=["raw_gwcc","raw_layer"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                data_payload:EvaluationProbableOutcome::NUMBER AS evaluationprobableoutcome,
                data_payload:AssessedAsIndefinitelyUnable::BOOLEAN AS assessedasindefinitelyunable,
                data_payload:PaymentReductionReminderFlag::BOOLEAN AS paymentreductionreminderflag,
                CAST(data_payload:FurtherInfoReasoning::TEXT AS VARCHAR(1333)) AS furtherinforeasoning,
                TO_TIMESTAMP_TZ(data_payload:EffectiveDateFairNotice::NUMBER/1000) AS effectivedatefairnotice,
                data_payload:ReviewType::NUMBER AS reviewtype,
                data_payload:CurrentWeeklyHours::NUMBER AS currentweeklyhours,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:ReviewPeriod::NUMBER AS reviewperiod,
                data_payload:ID::NUMBER AS id,
                data_payload:FairNoticeRequired::BOOLEAN AS fairnoticerequired,
                data_payload:AssessmentReminderFlag::BOOLEAN AS assessmentreminderflag,
                data_payload:CreateUserID::NUMBER AS createuserid,
                CAST(data_payload:Working15HourPerWeekText::TEXT AS VARCHAR(255)) AS working15hourperweektext,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:Retired::NUMBER AS retired,
                CAST(data_payload:HoursPerDay AS NUMBER(5,2)) AS hoursperday,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                TO_TIMESTAMP_TZ(data_payload:EffectiveDateDecision::NUMBER/1000) AS effectivedatedecision,
                data_payload:FurtherInfoImpactsDecision::BOOLEAN AS furtherinfoimpactsdecision,
                CAST(data_payload:DecisionReasoning::TEXT AS VARCHAR(1333)) AS decisionreasoning,
                TO_TIMESTAMP_TZ(data_payload:IssueDateFairNotice::NUMBER/1000) AS issuedatefairnotice,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                data_payload:CurrentWorkCapacity::NUMBER AS currentworkcapacity,
                data_payload:EarningPerWeek::BOOLEAN AS earningperweek,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                data_payload:DocumentLinkableID::NUMBER AS documentlinkableid,
                data_payload:WPIPercentage::NUMBER AS wpipercentage,
                CAST(data_payload:ReferenceNumber::TEXT AS VARCHAR(255)) AS referencenumber,
                CAST(data_payload:AssessedAsUnableText::TEXT AS VARCHAR(255)) AS assessedasunabletext,
                data_payload:ClaimID::NUMBER AS claimid,
                CAST(data_payload:DaysPerWeek AS NUMBER(2,1)) AS daysperweek,
                data_payload:EarningsE::NUMBER AS earningse,
                data_payload:MedEntitlement::NUMBER AS medentitlement,
                data_payload:Section38Eligible::BOOLEAN AS section38eligible,
                CAST(data_payload:CurrentWeeklyEarnings AS NUMBER(18,2)) AS currentweeklyearnings,
                TO_TIMESTAMP_TZ(data_payload:IssueDateDecision::NUMBER/1000) AS issuedatedecision,
                CAST(data_payload:EarningsCapacity AS NUMBER(18,2)) AS earningscapacity,
                data_payload:IssueDateFollowFlag::BOOLEAN AS issuedatefollowflag,
                data_payload:IssueDateReminderFlag::BOOLEAN AS issuedatereminderflag,
                CAST(data_payload:RelatedTo::TEXT AS VARCHAR(255)) AS relatedto,
                data_payload:DraftFairNoticeReady::BOOLEAN AS draftfairnoticeready,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                TO_TIMESTAMP_TZ(data_payload:EligibilityEffectiveDate::NUMBER/1000) AS eligibilityeffectivedate,
                data_payload:FurtherInfoSubmitted::BOOLEAN AS furtherinfosubmitted,
                data_payload:WeeklyPaymentImpact::NUMBER AS weeklypaymentimpact,
                data_payload:AssessedHours::NUMBER AS assessedhours,
                data_payload:DraftDecisionCompleted::BOOLEAN AS draftdecisioncompleted,
                data_payload:Status::NUMBER AS status,
                CAST(data_payload:EarningPerWeekText::TEXT AS VARCHAR(255)) AS earningperweektext,
                data_payload:Working15HourPerWeek::BOOLEAN AS working15hourperweek,
                data_payload:CurrentWorkStatus::NUMBER AS currentworkstatus,
                data_payload:EffectiveDateFairNoticeFlag::BOOLEAN AS effectivedatefairnoticeflag,
                CAST(data_payload:WCDPIAWE AS NUMBER(18,2)) AS wcdpiawe,
                data_payload:AssessmentReminderWeeksCount::NUMBER AS assessmentreminderweekscount,
                data_payload:ScheduleAssessmentReminderFlag::BOOLEAN AS scheduleassessmentreminderflag,
                TO_TIMESTAMP_TZ(data_payload:S38EligibilityIssueDate::NUMBER/1000) AS s38eligibilityissuedate,
                data_payload:RejectedSuitableEmployment::BOOLEAN AS rejectedsuitableemployment,
                CAST(data_payload:CWWRSuitableEmployment AS NUMBER(18,2)) AS cwwrsuitableemployment,
                data_payload:AcceptedOfferEmployment::BOOLEAN AS acceptedofferemployment,
                data_payload:DiscretionaryEntitlement::NUMBER AS discretionaryentitlement,
                CAST(data_payload:AbilityToEarn AS NUMBER(18,2)) AS abilitytoearn,
                TO_TIMESTAMP_TZ(data_payload:LegacyCreateTime::NUMBER/1000) AS legacycreatetime,
                TO_TIMESTAMP_TZ(data_payload:LegacyUpdateTime::NUMBER/1000) AS legacyupdatetime,
                TO_TIMESTAMP_TZ(data_payload:DecisionEndDate_Ext::NUMBER/1000) AS decisionenddate_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwcc', 'ccx_workcapdecision_icare') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:evaluationprobableoutcome::NUMBER AS evaluationprobableoutcome,
                $1:assessedasindefinitelyunable::BOOLEAN AS assessedasindefinitelyunable,
                $1:paymentreductionreminderflag::BOOLEAN AS paymentreductionreminderflag,
                CAST($1:furtherinforeasoning::TEXT AS VARCHAR(1333)) AS furtherinforeasoning,
                $1:effectivedatefairnotice::TIMESTAMP_TZ AS effectivedatefairnotice,
                $1:reviewtype::NUMBER AS reviewtype,
                $1:currentweeklyhours::NUMBER AS currentweeklyhours,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:reviewperiod::NUMBER AS reviewperiod,
                $1:id::NUMBER AS id,
                $1:fairnoticerequired::BOOLEAN AS fairnoticerequired,
                $1:assessmentreminderflag::BOOLEAN AS assessmentreminderflag,
                $1:createuserid::NUMBER AS createuserid,
                CAST($1:working15hourperweektext::TEXT AS VARCHAR(255)) AS working15hourperweektext,
                $1:beanversion::NUMBER AS beanversion,
                $1:retired::NUMBER AS retired,
                CAST($1:hoursperday AS NUMBER(5,2)) AS hoursperday,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:effectivedatedecision::TIMESTAMP_TZ AS effectivedatedecision,
                $1:furtherinfoimpactsdecision::BOOLEAN AS furtherinfoimpactsdecision,
                CAST($1:decisionreasoning::TEXT AS VARCHAR(1333)) AS decisionreasoning,
                $1:issuedatefairnotice::TIMESTAMP_TZ AS issuedatefairnotice,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:currentworkcapacity::NUMBER AS currentworkcapacity,
                $1:earningperweek::BOOLEAN AS earningperweek,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:documentlinkableid::NUMBER AS documentlinkableid,
                $1:wpipercentage::NUMBER AS wpipercentage,
                CAST($1:referencenumber::TEXT AS VARCHAR(255)) AS referencenumber,
                CAST($1:assessedasunabletext::TEXT AS VARCHAR(255)) AS assessedasunabletext,
                $1:claimid::NUMBER AS claimid,
                CAST($1:daysperweek AS NUMBER(2,1)) AS daysperweek,
                $1:earningse::NUMBER AS earningse,
                $1:medentitlement::NUMBER AS medentitlement,
                $1:section38eligible::BOOLEAN AS section38eligible,
                CAST($1:currentweeklyearnings AS NUMBER(18,2)) AS currentweeklyearnings,
                $1:issuedatedecision::TIMESTAMP_TZ AS issuedatedecision,
                CAST($1:earningscapacity AS NUMBER(18,2)) AS earningscapacity,
                $1:issuedatefollowflag::BOOLEAN AS issuedatefollowflag,
                $1:issuedatereminderflag::BOOLEAN AS issuedatereminderflag,
                CAST($1:relatedto::TEXT AS VARCHAR(255)) AS relatedto,
                $1:draftfairnoticeready::BOOLEAN AS draftfairnoticeready,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:eligibilityeffectivedate::TIMESTAMP_TZ AS eligibilityeffectivedate,
                $1:furtherinfosubmitted::BOOLEAN AS furtherinfosubmitted,
                $1:weeklypaymentimpact::NUMBER AS weeklypaymentimpact,
                $1:assessedhours::NUMBER AS assessedhours,
                $1:draftdecisioncompleted::BOOLEAN AS draftdecisioncompleted,
                $1:status::NUMBER AS status,
                CAST($1:earningperweektext::TEXT AS VARCHAR(255)) AS earningperweektext,
                $1:working15hourperweek::BOOLEAN AS working15hourperweek,
                $1:currentworkstatus::NUMBER AS currentworkstatus,
                $1:effectivedatefairnoticeflag::BOOLEAN AS effectivedatefairnoticeflag,
                CAST($1:wcdpiawe AS NUMBER(18,2)) AS wcdpiawe,
                $1:assessmentreminderweekscount::NUMBER AS assessmentreminderweekscount,
                $1:scheduleassessmentreminderflag::BOOLEAN AS scheduleassessmentreminderflag,
                $1:s38eligibilityissuedate::TIMESTAMP_TZ AS s38eligibilityissuedate,
                $1:rejectedsuitableemployment::BOOLEAN AS rejectedsuitableemployment,
                CAST($1:cwwrsuitableemployment AS NUMBER(18,2)) AS cwwrsuitableemployment,
                $1:acceptedofferemployment::BOOLEAN AS acceptedofferemployment,
                $1:discretionaryentitlement::NUMBER AS discretionaryentitlement,
                CAST($1:abilitytoearn AS NUMBER(18,2)) AS abilitytoearn,
                $1:legacycreatetime::TIMESTAMP_TZ AS legacycreatetime,
                $1:legacyupdatetime::TIMESTAMP_TZ AS legacyupdatetime,
                $1:decisionenddate_ext::TIMESTAMP_TZ AS decisionenddate_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwcc', 'ccx_workcapdecision_icare') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),
{#-
    Driving CTE Over 
    Transformed CTE is To Create the HASH_KEY Based on the Right Combination
-#}   
cte_transformed AS (
    SELECT
        *,
        CASE
             WHEN file_type = 'AVRO' THEN
                {{ dbt_utils.generate_surrogate_key([
                                'loadcommandid',
                        'evaluationprobableoutcome',
                        'assessedasindefinitelyunable',
                        'paymentreductionreminderflag',
                        'furtherinforeasoning',
                        'effectivedatefairnotice',
                        'reviewtype',
                        'currentweeklyhours',
                        'updatetime',
                        'reviewperiod',
                        'id',
                        'fairnoticerequired',
                        'assessmentreminderflag',
                        'createuserid',
                        'working15hourperweektext',
                        'beanversion',
                        'retired',
                        'hoursperday',
                        'updateuserid',
                        'effectivedatedecision',
                        'furtherinfoimpactsdecision',
                        'decisionreasoning',
                        'issuedatefairnotice',
                        'publicid',
                        'currentworkcapacity',
                        'earningperweek',
                        'createtime',
                        'documentlinkableid',
                        'wpipercentage',
                        'referencenumber',
                        'assessedasunabletext',
                        'claimid',
                        'daysperweek',
                        'earningse',
                        'medentitlement',
                        'section38eligible',
                        'currentweeklyearnings',
                        'issuedatedecision',
                        'earningscapacity',
                        'issuedatefollowflag',
                        'issuedatereminderflag',
                        'relatedto',
                        'draftfairnoticeready',
                        'archivepartition',
                        'eligibilityeffectivedate',
                        'furtherinfosubmitted',
                        'weeklypaymentimpact',
                        'assessedhours',
                        'draftdecisioncompleted',
                        'status',
                        'earningperweektext',
                        'working15hourperweek',
                        'currentworkstatus',
                        'effectivedatefairnoticeflag',
                        'wcdpiawe',
                        'assessmentreminderweekscount',
                        'scheduleassessmentreminderflag',
                        's38eligibilityissuedate',
                        'rejectedsuitableemployment',
                        'cwwrsuitableemployment',
                        'acceptedofferemployment',
                        'discretionaryentitlement',
                        'abilitytoearn',
                        'legacycreatetime',
                        'legacyupdatetime',
                        'decisionenddate_ext'
                        ]) }}
            WHEN file_type = 'PARQUET' THEN
                {{ dbt_utils.generate_surrogate_key([
                                'id',
                        'gwcbi_seqval'
                        ]) }}
        END AS hash_key    
    FROM cte_source_data
)
SELECT * FROM cte_transformed
        