
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'bro'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'bro'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  # The `start_date` variable will be accessible in all resources

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
    bro:
      +transient: false
      +sql_header: "alter SESSION set QUOTED_IDENTIFIERS_IGNORE_CASE = TRUE;"
      raw:
        +transient: false
        +enabled: true
        +database: DEV_RAW_DB
        gwpc:
         +schema: gwpc 
        gwcc:
         +schema: gwcc 
      curated:
        +schema : gwpc
        +database: DEV_CURATED_DB
        +transient: true
