dbtdemo:
  outputs:
    dev:
      account: qhrbbxp-qub80682
      database: DEV_LANDING_DB
      password: "{{ env_var('SNOWFLAKE_KEY_PASS') }}"
      role: SF_DEV_DATA_ENGINEER
      schema: GWPC
      threads: 8
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: DEV_LOAD_WH
  target: dev