icare_dbt_transformations_fndn:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: qcb41218
      user: AFSHIN
      role: SFG_DEV_DATA_ENGINEER
      database: DEV_RAW_DB
      warehouse: ICARE_DEV_ANALYTICS_WH
      schema: GWCC
      threads: 8