{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for pcx_micost_ext.
                                                micost_ext_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["raw_layer", "raw_policy_centre", "policy_centre", "non_business_critical", "pcx_micost_ext"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                data_payload:FXRateConversionUsed::BOOLEAN AS fxrateconversionused,
                CAST(data_payload:StandardAmountBilling AS NUMBER(18,2)) AS standardamountbilling,
                data_payload:StandardAmountBilling_cur::NUMBER AS standardamountbilling_cur,
                data_payload:FixedID::NUMBER AS fixedid,
                CAST(data_payload:OverrideReason::TEXT AS VARCHAR(255)) AS overridereason,
                CAST(data_payload:OverrideTermAmount AS NUMBER(18,2)) AS overridetermamount,
                data_payload:OverrideTermAmount_cur::NUMBER AS overridetermamount_cur,
                data_payload:ProrationMethod::NUMBER AS prorationmethod,
                data_payload:Overridable::BOOLEAN AS overridable,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                CAST(data_payload:StandardTermAmountBilling AS NUMBER(18,2)) AS standardtermamountbilling,
                data_payload:ID::NUMBER AS id,
                data_payload:StandardTermAmountBilling_cur::NUMBER AS standardtermamountbilling_cur,
                data_payload:CreateUserID::NUMBER AS createuserid,
                CAST(data_payload:OverrideAmount AS NUMBER(18,2)) AS overrideamount,
                data_payload:OverrideAmount_cur::NUMBER AS overrideamount_cur,
                data_payload:BeanVersion::NUMBER AS beanversion,
                CAST(data_payload:StandardAdjRate AS NUMBER(18,8)) AS standardadjrate,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                data_payload:RoundingMode::NUMBER AS roundingmode,
                CAST(data_payload:ActualAdjRate AS NUMBER(18,8)) AS actualadjrate,
                CAST(data_payload:OverrideAdjRate AS NUMBER(18,8)) AS overrideadjrate,
                data_payload:BranchID::NUMBER AS branchid,
                CAST(data_payload:Basis AS NUMBER(22,2)) AS basis,
                CAST(data_payload:ActualBaseRate AS NUMBER(18,8)) AS actualbaserate,
                CAST(data_payload:StandardTermAmount AS NUMBER(18,2)) AS standardtermamount,
                data_payload:StandardTermAmount_cur::NUMBER AS standardtermamount_cur,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                data_payload:RateBook::NUMBER AS ratebook,
                CAST(data_payload:ChargeGroup::TEXT AS VARCHAR(255)) AS chargegroup,
                CAST(data_payload:ActualTermAmount AS NUMBER(18,2)) AS actualtermamount,
                data_payload:ActualTermAmount_cur::NUMBER AS actualtermamount_cur,
                TO_TIMESTAMP_TZ(data_payload:EffectiveDate::NUMBER/1000) AS effectivedate,
                CAST(data_payload:ActualAmountBilling AS NUMBER(18,2)) AS actualamountbilling,
                CAST(data_payload:StandardAmount AS NUMBER(18,2)) AS standardamount,
                data_payload:ActualAmountBilling_cur::NUMBER AS actualamountbilling_cur,
                data_payload:StandardAmount_cur::NUMBER AS standardamount_cur,
                CAST(data_payload:OverrideAmountBilling AS NUMBER(18,2)) AS overrideamountbilling,
                data_payload:OverrideAmountBilling_cur::NUMBER AS overrideamountbilling_cur,
                data_payload:ChargePattern::NUMBER AS chargepattern,
                TO_TIMESTAMP_TZ(data_payload:ExpirationDate::NUMBER/1000) AS expirationdate,
                data_payload:PolicyFXRate::NUMBER AS policyfxrate,
                CAST(data_payload:ActualAmount AS NUMBER(18,2)) AS actualamount,
                data_payload:SubjectToReporting::BOOLEAN AS subjecttoreporting,
                data_payload:OverrideSource::NUMBER AS overridesource,
                data_payload:ActualAmount_cur::NUMBER AS actualamount_cur,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                CAST(data_payload:ActualTermAmountBilling AS NUMBER(18,2)) AS actualtermamountbilling,
                data_payload:ChangeType::NUMBER AS changetype,
                data_payload:ActualTermAmountBilling_cur::NUMBER AS actualtermamountbilling_cur,
                CAST(data_payload:OverrideTermAmountBilling AS NUMBER(18,2)) AS overridetermamountbilling,
                data_payload:OverrideTermAmountBilling_cur::NUMBER AS overridetermamountbilling_cur,
                data_payload:BasedOnID::NUMBER AS basedonid,
                data_payload:NumDaysInRatedTerm::NUMBER AS numdaysinratedterm,
                CAST(data_payload:StandardBaseRate AS NUMBER(18,8)) AS standardbaserate,
                data_payload:RoundingLevel::NUMBER AS roundinglevel,
                data_payload:RateAmountType::NUMBER AS rateamounttype,
                data_payload:Subtype::NUMBER AS subtype,
                CAST(data_payload:OverrideBaseRate AS NUMBER(18,8)) AS overridebaserate,
                data_payload:MiscellaneousLineID::NUMBER AS miscellaneouslineid,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwpc', 'pcx_micost_ext') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:fxrateconversionused::BOOLEAN AS fxrateconversionused,
                CAST($1:standardamountbilling AS NUMBER(18,2)) AS standardamountbilling,
                $1:standardamountbilling_cur::NUMBER AS standardamountbilling_cur,
                $1:fixedid::NUMBER AS fixedid,
                CAST($1:overridereason::TEXT AS VARCHAR(255)) AS overridereason,
                CAST($1:overridetermamount AS NUMBER(18,2)) AS overridetermamount,
                $1:overridetermamount_cur::NUMBER AS overridetermamount_cur,
                $1:prorationmethod::NUMBER AS prorationmethod,
                $1:overridable::BOOLEAN AS overridable,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                CAST($1:standardtermamountbilling AS NUMBER(18,2)) AS standardtermamountbilling,
                $1:id::NUMBER AS id,
                $1:standardtermamountbilling_cur::NUMBER AS standardtermamountbilling_cur,
                $1:createuserid::NUMBER AS createuserid,
                CAST($1:overrideamount AS NUMBER(18,2)) AS overrideamount,
                $1:overrideamount_cur::NUMBER AS overrideamount_cur,
                $1:beanversion::NUMBER AS beanversion,
                CAST($1:standardadjrate AS NUMBER(18,8)) AS standardadjrate,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:roundingmode::NUMBER AS roundingmode,
                CAST($1:actualadjrate AS NUMBER(18,8)) AS actualadjrate,
                CAST($1:overrideadjrate AS NUMBER(18,8)) AS overrideadjrate,
                $1:branchid::NUMBER AS branchid,
                CAST($1:basis AS NUMBER(22,2)) AS basis,
                CAST($1:actualbaserate AS NUMBER(18,8)) AS actualbaserate,
                CAST($1:standardtermamount AS NUMBER(18,2)) AS standardtermamount,
                $1:standardtermamount_cur::NUMBER AS standardtermamount_cur,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:ratebook::NUMBER AS ratebook,
                CAST($1:chargegroup::TEXT AS VARCHAR(255)) AS chargegroup,
                CAST($1:actualtermamount AS NUMBER(18,2)) AS actualtermamount,
                $1:actualtermamount_cur::NUMBER AS actualtermamount_cur,
                $1:effectivedate::TIMESTAMP_TZ AS effectivedate,
                CAST($1:actualamountbilling AS NUMBER(18,2)) AS actualamountbilling,
                CAST($1:standardamount AS NUMBER(18,2)) AS standardamount,
                $1:actualamountbilling_cur::NUMBER AS actualamountbilling_cur,
                $1:standardamount_cur::NUMBER AS standardamount_cur,
                CAST($1:overrideamountbilling AS NUMBER(18,2)) AS overrideamountbilling,
                $1:overrideamountbilling_cur::NUMBER AS overrideamountbilling_cur,
                $1:chargepattern::NUMBER AS chargepattern,
                $1:expirationdate::TIMESTAMP_TZ AS expirationdate,
                $1:policyfxrate::NUMBER AS policyfxrate,
                CAST($1:actualamount AS NUMBER(18,2)) AS actualamount,
                $1:subjecttoreporting::BOOLEAN AS subjecttoreporting,
                $1:overridesource::NUMBER AS overridesource,
                $1:actualamount_cur::NUMBER AS actualamount_cur,
                $1:archivepartition::NUMBER AS archivepartition,
                CAST($1:actualtermamountbilling AS NUMBER(18,2)) AS actualtermamountbilling,
                $1:changetype::NUMBER AS changetype,
                $1:actualtermamountbilling_cur::NUMBER AS actualtermamountbilling_cur,
                CAST($1:overridetermamountbilling AS NUMBER(18,2)) AS overridetermamountbilling,
                $1:overridetermamountbilling_cur::NUMBER AS overridetermamountbilling_cur,
                $1:basedonid::NUMBER AS basedonid,
                $1:numdaysinratedterm::NUMBER AS numdaysinratedterm,
                CAST($1:standardbaserate AS NUMBER(18,8)) AS standardbaserate,
                $1:roundinglevel::NUMBER AS roundinglevel,
                $1:rateamounttype::NUMBER AS rateamounttype,
                $1:subtype::NUMBER AS subtype,
                CAST($1:overridebaserate AS NUMBER(18,8)) AS overridebaserate,
                $1:miscellaneouslineid::NUMBER AS miscellaneouslineid,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwpc', 'pcx_micost_ext') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS micost_ext_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'fxrateconversionused',
                        'standardamountbilling',
                        'standardamountbilling_cur',
                        'fixedid',
                        'overridereason',
                        'overridetermamount',
                        'overridetermamount_cur',
                        'prorationmethod',
                        'overridable',
                        'updatetime',
                        'standardtermamountbilling',
                        'standardtermamountbilling_cur',
                        'createuserid',
                        'overrideamount',
                        'overrideamount_cur',
                        'beanversion',
                        'standardadjrate',
                        'updateuserid',
                        'roundingmode',
                        'actualadjrate',
                        'overrideadjrate',
                        'branchid',
                        'basis',
                        'actualbaserate',
                        'standardtermamount',
                        'standardtermamount_cur',
                        'publicid',
                        'createtime',
                        'ratebook',
                        'chargegroup',
                        'actualtermamount',
                        'actualtermamount_cur',
                        'effectivedate',
                        'actualamountbilling',
                        'standardamount',
                        'actualamountbilling_cur',
                        'standardamount_cur',
                        'overrideamountbilling',
                        'overrideamountbilling_cur',
                        'chargepattern',
                        'expirationdate',
                        'policyfxrate',
                        'actualamount',
                        'subjecttoreporting',
                        'overridesource',
                        'actualamount_cur',
                        'archivepartition',
                        'actualtermamountbilling',
                        'changetype',
                        'actualtermamountbilling_cur',
                        'overridetermamountbilling',
                        'overridetermamountbilling_cur',
                        'basedonid',
                        'numdaysinratedterm',
                        'standardbaserate',
                        'roundinglevel',
                        'rateamounttype',
                        'subtype',
                        'overridebaserate',
                        'miscellaneouslineid'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS dbt_updated_at
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}