
{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             This Converts Parquet or AVRO Data Loaded in the Variant Column in the RAW DB into Flattend Views
                                                This also creates a HASH_KEY for Incremental Tables for the Curated Layer 
                                                Additional CDA Files are Null in the AVRO but not in CDA .
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    tags=["raw_gwpc","raw_layer"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                data_payload:PreviousGroupID::NUMBER AS previousgroupid,
                data_payload:AccountID::NUMBER AS accountid,
                TO_TIMESTAMP_TZ(data_payload:EndDate::NUMBER/1000) AS enddate,
                data_payload:AssignedByUserID::NUMBER AS assignedbyuserid,
                data_payload:ExternallyOwned::BOOLEAN AS externallyowned,
                CAST(data_payload:LogicalName::TEXT AS VARCHAR(255)) AS logicalname,
                CAST(data_payload:ApprovalRationale::TEXT AS VARCHAR(255)) AS approvalrationale,
                CAST(data_payload:DocumentTemplate::TEXT AS VARCHAR(255)) AS documenttemplate,
                data_payload:PreviousQueueID::NUMBER AS previousqueueid,
                CAST(data_payload:EmailTemplate::TEXT AS VARCHAR(255)) AS emailtemplate,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:JobID::NUMBER AS jobid,
                data_payload:WorkflowID::NUMBER AS workflowid,
                data_payload:ID::NUMBER AS id,
                data_payload:CloseUserID::NUMBER AS closeuserid,
                data_payload:CreateUserID::NUMBER AS createuserid,
                data_payload:Priority::NUMBER AS priority,
                TO_TIMESTAMP_TZ(data_payload:CloseDate::NUMBER/1000) AS closedate,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:Retired::NUMBER AS retired,
                data_payload:ValidationLevel::NUMBER AS validationlevel,
                CAST(data_payload:Subject::TEXT AS VARCHAR(255)) AS subject,
                data_payload:AccountContactID::NUMBER AS accountcontactid,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                CAST(data_payload:ShortSubject::TEXT AS VARCHAR(10)) AS shortsubject,
                data_payload:Approved::BOOLEAN AS approved,
                data_payload:Type::NUMBER AS type,
                TO_TIMESTAMP_TZ(data_payload:TargetDate::NUMBER/1000) AS targetdate,
                data_payload:AutoGenerated::BOOLEAN AS autogenerated,
                TO_TIMESTAMP_TZ(data_payload:EscalationDate::NUMBER/1000) AS escalationdate,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                TO_TIMESTAMP_TZ(data_payload:LastViewedDate::NUMBER/1000) AS lastvieweddate,
                data_payload:ActivityClass::NUMBER AS activityclass,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                CAST(data_payload:Command::TEXT AS VARCHAR(1333)) AS command,
                data_payload:AssignedGroupID::NUMBER AS assignedgroupid,
                data_payload:PolicyID::NUMBER AS policyid,
                data_payload:Contingency::NUMBER AS contingency,
                data_payload:Mandatory::BOOLEAN AS mandatory,
                data_payload:Recurring::BOOLEAN AS recurring,
                data_payload:PreviousUserID::NUMBER AS previoususerid,
                data_payload:AssignedQueueID::NUMBER AS assignedqueueid,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                data_payload:Escalated::BOOLEAN AS escalated,
                data_payload:Status::NUMBER AS status,
                data_payload:AssignedUserID::NUMBER AS assigneduserid,
                CAST(data_payload:ApprovalIssue::TEXT AS VARCHAR(255)) AS approvalissue,
                data_payload:Subtype::NUMBER AS subtype,
                TO_TIMESTAMP_TZ(data_payload:AssignmentDate::NUMBER/1000) AS assignmentdate,
                data_payload:ActivityPatternID::NUMBER AS activitypatternid,
                CAST(data_payload:Description::TEXT AS VARCHAR(1333)) AS description,
                data_payload:AssociatedRole::NUMBER AS associatedrole,
                data_payload:AssignmentStatus::NUMBER AS assignmentstatus,
                TO_TIMESTAMP_TZ(data_payload:RenewalDate::NUMBER/1000) AS renewaldate,
                data_payload:ContactID::NUMBER AS contactid,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwpc', 'pc_activity') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:previousgroupid::NUMBER AS previousgroupid,
                $1:accountid::NUMBER AS accountid,
                $1:enddate::TIMESTAMP_TZ AS enddate,
                $1:assignedbyuserid::NUMBER AS assignedbyuserid,
                $1:externallyowned::BOOLEAN AS externallyowned,
                CAST($1:logicalname::TEXT AS VARCHAR(255)) AS logicalname,
                CAST($1:approvalrationale::TEXT AS VARCHAR(255)) AS approvalrationale,
                CAST($1:documenttemplate::TEXT AS VARCHAR(255)) AS documenttemplate,
                $1:previousqueueid::NUMBER AS previousqueueid,
                CAST($1:emailtemplate::TEXT AS VARCHAR(255)) AS emailtemplate,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:jobid::NUMBER AS jobid,
                $1:workflowid::NUMBER AS workflowid,
                $1:id::NUMBER AS id,
                $1:closeuserid::NUMBER AS closeuserid,
                $1:createuserid::NUMBER AS createuserid,
                $1:priority::NUMBER AS priority,
                $1:closedate::TIMESTAMP_TZ AS closedate,
                $1:beanversion::NUMBER AS beanversion,
                $1:retired::NUMBER AS retired,
                $1:validationlevel::NUMBER AS validationlevel,
                CAST($1:subject::TEXT AS VARCHAR(255)) AS subject,
                $1:accountcontactid::NUMBER AS accountcontactid,
                $1:updateuserid::NUMBER AS updateuserid,
                CAST($1:shortsubject::TEXT AS VARCHAR(10)) AS shortsubject,
                $1:approved::BOOLEAN AS approved,
                $1:type::NUMBER AS type,
                $1:targetdate::TIMESTAMP_TZ AS targetdate,
                $1:autogenerated::BOOLEAN AS autogenerated,
                $1:escalationdate::TIMESTAMP_TZ AS escalationdate,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:lastvieweddate::TIMESTAMP_TZ AS lastvieweddate,
                $1:activityclass::NUMBER AS activityclass,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                CAST($1:command::TEXT AS VARCHAR(1333)) AS command,
                $1:assignedgroupid::NUMBER AS assignedgroupid,
                $1:policyid::NUMBER AS policyid,
                $1:contingency::NUMBER AS contingency,
                $1:mandatory::BOOLEAN AS mandatory,
                $1:recurring::BOOLEAN AS recurring,
                $1:previoususerid::NUMBER AS previoususerid,
                $1:assignedqueueid::NUMBER AS assignedqueueid,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:escalated::BOOLEAN AS escalated,
                $1:status::NUMBER AS status,
                $1:assigneduserid::NUMBER AS assigneduserid,
                CAST($1:approvalissue::TEXT AS VARCHAR(255)) AS approvalissue,
                $1:subtype::NUMBER AS subtype,
                $1:assignmentdate::TIMESTAMP_TZ AS assignmentdate,
                $1:activitypatternid::NUMBER AS activitypatternid,
                CAST($1:description::TEXT AS VARCHAR(1333)) AS description,
                $1:associatedrole::NUMBER AS associatedrole,
                $1:assignmentstatus::NUMBER AS assignmentstatus,
                $1:renewaldate::TIMESTAMP_TZ AS renewaldate,
                $1:contactid::NUMBER AS contactid,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwpc', 'pc_activity') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),
{#-
    Driving CTE Over 
    Transformed CTE is To Create the HASH_KEY Based on the Right Combination
-#}   
cte_transformed AS (
    SELECT
        *,
        CASE
             WHEN file_type = 'AVRO' THEN
                {{ dbt_utils.generate_surrogate_key([
                                'loadcommandid',
                        'previousgroupid',
                        'accountid',
                        'enddate',
                        'assignedbyuserid',
                        'externallyowned',
                        'logicalname',
                        'approvalrationale',
                        'documenttemplate',
                        'previousqueueid',
                        'emailtemplate',
                        'updatetime',
                        'jobid',
                        'workflowid',
                        'id',
                        'closeuserid',
                        'createuserid',
                        'priority',
                        'closedate',
                        'beanversion',
                        'retired',
                        'validationlevel',
                        'subject',
                        'accountcontactid',
                        'updateuserid',
                        'shortsubject',
                        'approved',
                        'type',
                        'targetdate',
                        'autogenerated',
                        'escalationdate',
                        'publicid',
                        'lastvieweddate',
                        'activityclass',
                        'createtime',
                        'command',
                        'assignedgroupid',
                        'policyid',
                        'contingency',
                        'mandatory',
                        'recurring',
                        'previoususerid',
                        'assignedqueueid',
                        'archivepartition',
                        'escalated',
                        'status',
                        'assigneduserid',
                        'approvalissue',
                        'subtype',
                        'assignmentdate',
                        'activitypatternid',
                        'description',
                        'associatedrole',
                        'assignmentstatus',
                        'renewaldate',
                        'contactid'
                        ]) }}
            WHEN file_type = 'PARQUET' THEN
                {{ dbt_utils.generate_surrogate_key([
                                'id',
                        'gwcbi_seqval'
                        ]) }}
        END AS hash_key    
    FROM cte_source_data
)
SELECT * FROM cte_transformed
        