{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for ccx_stpcocdata_icare.
                                                stpcocdata_icare_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["raw_layer", "raw_claim_centre", "claim_centre", "non_business_critical", "ccx_stpcocdata_icare"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                CAST(data_payload:DrivingAbility::TEXT AS VARCHAR(255)) AS drivingability,
                CAST(data_payload:ClaimNumber::TEXT AS VARCHAR(19)) AS claimnumber,
                CAST(data_payload:Postcode::TEXT AS VARCHAR(4)) AS postcode,
                CAST(data_payload:EmploymentDeclaration::TEXT AS VARCHAR(5)) AS employmentdeclaration,
                CAST(data_payload:ReferralToRehabProvider::TEXT AS VARCHAR(5)) AS referraltorehabprovider,
                CAST(data_payload:RequestForPositionDesc::TEXT AS VARCHAR(5)) AS requestforpositiondesc,
                TO_TIMESTAMP_TZ(data_payload:CWEndDate::NUMBER/1000) AS cwenddate,
                CAST(data_payload:PushingPullingAbility::TEXT AS VARCHAR(255)) AS pushingpullingability,
                CAST(data_payload:SignatureOfPatient::TEXT AS VARCHAR(5)) AS signatureofpatient,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                CAST(data_payload:LiftingCarryingCapacity::TEXT AS VARCHAR(255)) AS liftingcarryingcapacity,
                CAST(data_payload:FactorsDelayingRecovery::TEXT AS VARCHAR(255)) AS factorsdelayingrecovery,
                CAST(data_payload:DocUID::TEXT AS VARCHAR(255)) AS docuid,
                data_payload:ID::NUMBER AS id,
                TO_TIMESTAMP_TZ(data_payload:CWStartDate::NUMBER/1000) AS cwstartdate,
                CAST(data_payload:AddressState::TEXT AS VARCHAR(3)) AS addressstate,
                CAST(data_payload:LastName::TEXT AS VARCHAR(20)) AS lastname,
                CAST(data_payload:TreatmentPlan::TEXT AS VARCHAR(255)) AS treatmentplan,
                data_payload:CreateUserID::NUMBER AS createuserid,
                CAST(data_payload:OtherConsiderations::TEXT AS VARCHAR(255)) AS otherconsiderations,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:Retired::NUMBER AS retired,
                CAST(data_payload:AddressStreetLocation::TEXT AS VARCHAR(255)) AS addressstreetlocation,
                CAST(data_payload:HoursPerDay AS NUMBER(5,2)) AS hoursperday,
                TO_TIMESTAMP_TZ(data_payload:Date::NUMBER/1000) AS date,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                CAST(data_payload:FitForPreinjuryDuties::TEXT AS VARCHAR(5)) AS fitforpreinjuryduties,
                TO_TIMESTAMP_TZ(data_payload:NextReviewDate::NUMBER/1000) AS nextreviewdate,
                CAST(data_payload:FirstName::TEXT AS VARCHAR(20)) AS firstname,
                TO_TIMESTAMP_TZ(data_payload:DateOfInjury::NUMBER/1000) AS dateofinjury,
                CAST(data_payload:StandingTolerance::TEXT AS VARCHAR(255)) AS standingtolerance,
                CAST(data_payload:SittingTolerance::TEXT AS VARCHAR(255)) AS sittingtolerance,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                CAST(data_payload:TelephoneNumber::TEXT AS VARCHAR(14)) AS telephonenumber,
                CAST(data_payload:InitialCertificate::TEXT AS VARCHAR(5)) AS initialcertificate,
                CAST(data_payload:BendingTwistingSquatting::TEXT AS VARCHAR(255)) AS bendingtwistingsquatting,
                CAST(data_payload:EstimatedDateToReturn::TEXT AS VARCHAR(255)) AS estimateddatetoreturn,
                CAST(data_payload:EmploymentDetails::TEXT AS VARCHAR(255)) AS employmentdetails,
                CAST(data_payload:AddressLocality::TEXT AS VARCHAR(30)) AS addresslocality,
                data_payload:DaysPerWeek::NUMBER AS daysperweek,
                TO_TIMESTAMP_TZ(data_payload:DateOfBirth::NUMBER/1000) AS dateofbirth,
                CAST(data_payload:CapacityForWork::TEXT AS VARCHAR(5)) AS capacityforwork,
                CAST(data_payload:PreExistingConditions::TEXT AS VARCHAR(255)) AS preexistingconditions,
                CAST(data_payload:OtherReferrals::TEXT AS VARCHAR(255)) AS otherreferrals,
                TO_TIMESTAMP_TZ(data_payload:NCWEndDate::NUMBER/1000) AS ncwenddate,
                TO_TIMESTAMP_TZ(data_payload:NCWStartDate::NUMBER/1000) AS ncwstartdate,
                CAST(data_payload:Diagnosis::TEXT AS VARCHAR(255)) AS diagnosis,
                data_payload:MedicareNumber::NUMBER AS medicarenumber,
                CAST(data_payload:NoCapacityForWork::TEXT AS VARCHAR(5)) AS nocapacityforwork,
                TO_TIMESTAMP_TZ(data_payload:PreInjFitnessStartDate::NUMBER/1000) AS preinjfitnessstartdate,
                CAST(data_payload:TreatingMedPractSign::TEXT AS VARCHAR(5)) AS treatingmedpractsign,
                CAST(data_payload:Comment::TEXT AS VARCHAR(255)) AS comment,
                CAST(data_payload:InjuryConsistentWithCause::TEXT AS VARCHAR(5)) AS injuryconsistentwithcause,
                CAST(data_payload:AdditionalInjury::TEXT AS VARCHAR(5)) AS additionalinjury,
                CAST(data_payload:TreatmentComments1::TEXT AS VARCHAR(255)) AS treatmentcomments1,
                CAST(data_payload:TreatmentComments2::TEXT AS VARCHAR(255)) AS treatmentcomments2,
                CAST(data_payload:TreatmentComments3::TEXT AS VARCHAR(255)) AS treatmentcomments3,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwcc', 'ccx_stpcocdata_icare') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                CAST($1:drivingability::TEXT AS VARCHAR(255)) AS drivingability,
                CAST($1:claimnumber::TEXT AS VARCHAR(19)) AS claimnumber,
                CAST($1:postcode::TEXT AS VARCHAR(4)) AS postcode,
                CAST($1:employmentdeclaration::TEXT AS VARCHAR(5)) AS employmentdeclaration,
                CAST($1:referraltorehabprovider::TEXT AS VARCHAR(5)) AS referraltorehabprovider,
                CAST($1:requestforpositiondesc::TEXT AS VARCHAR(5)) AS requestforpositiondesc,
                $1:cwenddate::TIMESTAMP_TZ AS cwenddate,
                CAST($1:pushingpullingability::TEXT AS VARCHAR(255)) AS pushingpullingability,
                CAST($1:signatureofpatient::TEXT AS VARCHAR(5)) AS signatureofpatient,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                CAST($1:liftingcarryingcapacity::TEXT AS VARCHAR(255)) AS liftingcarryingcapacity,
                CAST($1:factorsdelayingrecovery::TEXT AS VARCHAR(255)) AS factorsdelayingrecovery,
                CAST($1:docuid::TEXT AS VARCHAR(255)) AS docuid,
                $1:id::NUMBER AS id,
                $1:cwstartdate::TIMESTAMP_TZ AS cwstartdate,
                CAST($1:addressstate::TEXT AS VARCHAR(3)) AS addressstate,
                CAST($1:lastname::TEXT AS VARCHAR(20)) AS lastname,
                CAST($1:treatmentplan::TEXT AS VARCHAR(255)) AS treatmentplan,
                $1:createuserid::NUMBER AS createuserid,
                CAST($1:otherconsiderations::TEXT AS VARCHAR(255)) AS otherconsiderations,
                $1:beanversion::NUMBER AS beanversion,
                $1:retired::NUMBER AS retired,
                CAST($1:addressstreetlocation::TEXT AS VARCHAR(255)) AS addressstreetlocation,
                CAST($1:hoursperday AS NUMBER(5,2)) AS hoursperday,
                $1:date::TIMESTAMP_TZ AS date,
                $1:updateuserid::NUMBER AS updateuserid,
                CAST($1:fitforpreinjuryduties::TEXT AS VARCHAR(5)) AS fitforpreinjuryduties,
                $1:nextreviewdate::TIMESTAMP_TZ AS nextreviewdate,
                CAST($1:firstname::TEXT AS VARCHAR(20)) AS firstname,
                $1:dateofinjury::TIMESTAMP_TZ AS dateofinjury,
                CAST($1:standingtolerance::TEXT AS VARCHAR(255)) AS standingtolerance,
                CAST($1:sittingtolerance::TEXT AS VARCHAR(255)) AS sittingtolerance,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                CAST($1:telephonenumber::TEXT AS VARCHAR(14)) AS telephonenumber,
                CAST($1:initialcertificate::TEXT AS VARCHAR(5)) AS initialcertificate,
                CAST($1:bendingtwistingsquatting::TEXT AS VARCHAR(255)) AS bendingtwistingsquatting,
                CAST($1:estimateddatetoreturn::TEXT AS VARCHAR(255)) AS estimateddatetoreturn,
                CAST($1:employmentdetails::TEXT AS VARCHAR(255)) AS employmentdetails,
                CAST($1:addresslocality::TEXT AS VARCHAR(30)) AS addresslocality,
                $1:daysperweek::NUMBER AS daysperweek,
                $1:dateofbirth::TIMESTAMP_TZ AS dateofbirth,
                CAST($1:capacityforwork::TEXT AS VARCHAR(5)) AS capacityforwork,
                CAST($1:preexistingconditions::TEXT AS VARCHAR(255)) AS preexistingconditions,
                CAST($1:otherreferrals::TEXT AS VARCHAR(255)) AS otherreferrals,
                $1:ncwenddate::TIMESTAMP_TZ AS ncwenddate,
                $1:ncwstartdate::TIMESTAMP_TZ AS ncwstartdate,
                CAST($1:diagnosis::TEXT AS VARCHAR(255)) AS diagnosis,
                $1:medicarenumber::NUMBER AS medicarenumber,
                CAST($1:nocapacityforwork::TEXT AS VARCHAR(5)) AS nocapacityforwork,
                $1:preinjfitnessstartdate::TIMESTAMP_TZ AS preinjfitnessstartdate,
                CAST($1:treatingmedpractsign::TEXT AS VARCHAR(5)) AS treatingmedpractsign,
                CAST($1:comment::TEXT AS VARCHAR(255)) AS comment,
                CAST($1:injuryconsistentwithcause::TEXT AS VARCHAR(5)) AS injuryconsistentwithcause,
                CAST($1:additionalinjury::TEXT AS VARCHAR(5)) AS additionalinjury,
                CAST($1:treatmentcomments1::TEXT AS VARCHAR(255)) AS treatmentcomments1,
                CAST($1:treatmentcomments2::TEXT AS VARCHAR(255)) AS treatmentcomments2,
                CAST($1:treatmentcomments3::TEXT AS VARCHAR(255)) AS treatmentcomments3,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwcc', 'ccx_stpcocdata_icare') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS stpcocdata_icare_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'drivingability',
                        'claimnumber',
                        'postcode',
                        'employmentdeclaration',
                        'referraltorehabprovider',
                        'requestforpositiondesc',
                        'cwenddate',
                        'pushingpullingability',
                        'signatureofpatient',
                        'updatetime',
                        'liftingcarryingcapacity',
                        'factorsdelayingrecovery',
                        'docuid',
                        'cwstartdate',
                        'addressstate',
                        'lastname',
                        'treatmentplan',
                        'createuserid',
                        'otherconsiderations',
                        'beanversion',
                        'retired',
                        'addressstreetlocation',
                        'hoursperday',
                        'date',
                        'updateuserid',
                        'fitforpreinjuryduties',
                        'nextreviewdate',
                        'firstname',
                        'dateofinjury',
                        'standingtolerance',
                        'sittingtolerance',
                        'publicid',
                        'createtime',
                        'telephonenumber',
                        'initialcertificate',
                        'bendingtwistingsquatting',
                        'estimateddatetoreturn',
                        'employmentdetails',
                        'addresslocality',
                        'daysperweek',
                        'dateofbirth',
                        'capacityforwork',
                        'preexistingconditions',
                        'otherreferrals',
                        'ncwenddate',
                        'ncwstartdate',
                        'diagnosis',
                        'medicarenumber',
                        'nocapacityforwork',
                        'preinjfitnessstartdate',
                        'treatingmedpractsign',
                        'comment',
                        'injuryconsistentwithcause',
                        'additionalinjury',
                        'treatmentcomments1',
                        'treatmentcomments2',
                        'treatmentcomments3'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) as record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}