{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for ccx_paygsummaryhistory_icare.
                                                paygsummaryhistory_icare_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["raw_layer", "raw_claim_centre", "claim_centre", "non_business_critical", "ccx_paygsummaryhistory_icare"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                CAST(data_payload:FBTAmount AS NUMBER(18,2)) AS fbtamount,
                CAST(data_payload:PayeeSurname::TEXT AS VARCHAR(80)) AS payeesurname,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                CAST(data_payload:PayeeAddr1::TEXT AS VARCHAR(60)) AS payeeaddr1,
                CAST(data_payload:PayeeAddr2::TEXT AS VARCHAR(60)) AS payeeaddr2,
                CAST(data_payload:PayeeAddr3::TEXT AS VARCHAR(60)) AS payeeaddr3,
                data_payload:ID::NUMBER AS id,
                CAST(data_payload:SecondLatestYearLumpSumE AS NUMBER(18,2)) AS secondlatestyearlumpsume,
                CAST(data_payload:SecondLatestLumpSumEYear::TEXT AS VARCHAR(32)) AS secondlatestlumpsumeyear,
                CAST(data_payload:TotalAllowances AS NUMBER(18,2)) AS totalallowances,
                data_payload:CreateUserID::NUMBER AS createuserid,
                data_payload:AmendmentIndicator::BOOLEAN AS amendmentindicator,
                CAST(data_payload:WorkplaceGivingAmt AS NUMBER(18,2)) AS workplacegivingamt,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:Retired::NUMBER AS retired,
                CAST(data_payload:LatestYearLumpSumE AS NUMBER(18,2)) AS latestyearlumpsume,
                CAST(data_payload:LatestLumpSumEYear::TEXT AS VARCHAR(32)) AS latestlumpsumeyear,
                CAST(data_payload:TotTaxWithheld AS NUMBER(18,2)) AS tottaxwithheld,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                data_payload:PayerID::NUMBER AS payerid,
                TO_TIMESTAMP_TZ(data_payload:DateProduced::NUMBER/1000) AS dateproduced,
                data_payload:PAYGSummaryStatus::NUMBER AS paygsummarystatus,
                CAST(data_payload:TFN::TEXT AS VARCHAR(30)) AS tfn,
                data_payload:PAYGSnapShot_icare::NUMBER AS paygsnapshot_icare,
                data_payload:PAYGSummary_icare::NUMBER AS paygsummary_icare,
                TO_TIMESTAMP_TZ(data_payload:PmtPeriodEnd::NUMBER/1000) AS pmtperiodend,
                CAST(data_payload:LumpSumPmtAType::TEXT AS VARCHAR(128)) AS lumpsumpmtatype,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                CAST(data_payload:FinancialYear::TEXT AS VARCHAR(32)) AS financialyear,
                data_payload:Payee::NUMBER AS payee,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                data_payload:PayeeState::NUMBER AS payeestate,
                TO_TIMESTAMP_TZ(data_payload:PmtPeriodStart::NUMBER/1000) AS pmtperiodstart,
                CAST(data_payload:CDEP AS NUMBER(18,2)) AS cdep,
                data_payload:PAYGSummaryChanged::BOOLEAN AS paygsummarychanged,
                data_payload:PayeeCountry::NUMBER AS payeecountry,
                CAST(data_payload:PayeePostCode::TEXT AS VARCHAR(20)) AS payeepostcode,
                data_payload:ClaimID::NUMBER AS claimid,
                data_payload:OutboundPack_icareID::NUMBER AS outboundpack_icareid,
                CAST(data_payload:LumpSumA AS NUMBER(18,2)) AS lumpsuma,
                CAST(data_payload:LumpSumB AS NUMBER(18,2)) AS lumpsumb,
                CAST(data_payload:LumpSumD AS NUMBER(18,2)) AS lumpsumd,
                CAST(data_payload:LumpSumE AS NUMBER(18,2)) AS lumpsume,
                CAST(data_payload:PayeeMiddleName::TEXT AS VARCHAR(40)) AS payeemiddlename,
                CAST(data_payload:PriorSecondLatestYearLumpSumE AS NUMBER(18,2)) AS priorsecondlatestyearlumpsume,
                CAST(data_payload:PriorSecondLatestLumpSumEYear::TEXT AS VARCHAR(128)) AS priorsecondlatestlumpsumeyear,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                CAST(data_payload:PayeeSuburb::TEXT AS VARCHAR(128)) AS payeesuburb,
                TO_TIMESTAMP_TZ(data_payload:PayeeDOB::NUMBER/1000) AS payeedob,
                CAST(data_payload:GrossPayments AS NUMBER(18,2)) AS grosspayments,
                CAST(data_payload:PayeeFirstName::TEXT AS VARCHAR(40)) AS payeefirstname,
                CAST(data_payload:ErrorDescription::TEXT AS VARCHAR(16777216)) AS errordescription,
                data_payload:Subtype::NUMBER AS subtype,
                CAST(data_payload:ReportableSuperAmt AS NUMBER(18,2)) AS reportablesuperamt,
                CAST(data_payload:HoldReason::TEXT AS VARCHAR(16777216)) AS holdreason,
                TO_TIMESTAMP_TZ(data_payload:HoldDate::NUMBER/1000) AS holddate,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwcc', 'ccx_paygsummaryhistory_icare') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                CAST($1:fbtamount AS NUMBER(18,2)) AS fbtamount,
                CAST($1:payeesurname::TEXT AS VARCHAR(80)) AS payeesurname,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                CAST($1:payeeaddr1::TEXT AS VARCHAR(60)) AS payeeaddr1,
                CAST($1:payeeaddr2::TEXT AS VARCHAR(60)) AS payeeaddr2,
                CAST($1:payeeaddr3::TEXT AS VARCHAR(60)) AS payeeaddr3,
                $1:id::NUMBER AS id,
                CAST($1:secondlatestyearlumpsume AS NUMBER(18,2)) AS secondlatestyearlumpsume,
                CAST($1:secondlatestlumpsumeyear::TEXT AS VARCHAR(32)) AS secondlatestlumpsumeyear,
                CAST($1:totalallowances AS NUMBER(18,2)) AS totalallowances,
                $1:createuserid::NUMBER AS createuserid,
                $1:amendmentindicator::BOOLEAN AS amendmentindicator,
                CAST($1:workplacegivingamt AS NUMBER(18,2)) AS workplacegivingamt,
                $1:beanversion::NUMBER AS beanversion,
                $1:retired::NUMBER AS retired,
                CAST($1:latestyearlumpsume AS NUMBER(18,2)) AS latestyearlumpsume,
                CAST($1:latestlumpsumeyear::TEXT AS VARCHAR(32)) AS latestlumpsumeyear,
                CAST($1:tottaxwithheld AS NUMBER(18,2)) AS tottaxwithheld,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:payerid::NUMBER AS payerid,
                $1:dateproduced::TIMESTAMP_TZ AS dateproduced,
                $1:paygsummarystatus::NUMBER AS paygsummarystatus,
                CAST($1:tfn::TEXT AS VARCHAR(30)) AS tfn,
                $1:paygsnapshot_icare::NUMBER AS paygsnapshot_icare,
                $1:paygsummary_icare::NUMBER AS paygsummary_icare,
                $1:pmtperiodend::TIMESTAMP_TZ AS pmtperiodend,
                CAST($1:lumpsumpmtatype::TEXT AS VARCHAR(128)) AS lumpsumpmtatype,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                CAST($1:financialyear::TEXT AS VARCHAR(32)) AS financialyear,
                $1:payee::NUMBER AS payee,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:payeestate::NUMBER AS payeestate,
                $1:pmtperiodstart::TIMESTAMP_TZ AS pmtperiodstart,
                CAST($1:cdep AS NUMBER(18,2)) AS cdep,
                $1:paygsummarychanged::BOOLEAN AS paygsummarychanged,
                $1:payeecountry::NUMBER AS payeecountry,
                CAST($1:payeepostcode::TEXT AS VARCHAR(20)) AS payeepostcode,
                $1:claimid::NUMBER AS claimid,
                $1:outboundpack_icareid::NUMBER AS outboundpack_icareid,
                CAST($1:lumpsuma AS NUMBER(18,2)) AS lumpsuma,
                CAST($1:lumpsumb AS NUMBER(18,2)) AS lumpsumb,
                CAST($1:lumpsumd AS NUMBER(18,2)) AS lumpsumd,
                CAST($1:lumpsume AS NUMBER(18,2)) AS lumpsume,
                CAST($1:payeemiddlename::TEXT AS VARCHAR(40)) AS payeemiddlename,
                CAST($1:priorsecondlatestyearlumpsume AS NUMBER(18,2)) AS priorsecondlatestyearlumpsume,
                CAST($1:priorsecondlatestlumpsumeyear::TEXT AS VARCHAR(128)) AS priorsecondlatestlumpsumeyear,
                $1:archivepartition::NUMBER AS archivepartition,
                CAST($1:payeesuburb::TEXT AS VARCHAR(128)) AS payeesuburb,
                $1:payeedob::TIMESTAMP_TZ AS payeedob,
                CAST($1:grosspayments AS NUMBER(18,2)) AS grosspayments,
                CAST($1:payeefirstname::TEXT AS VARCHAR(40)) AS payeefirstname,
                CAST($1:errordescription::TEXT AS VARCHAR(16777216)) AS errordescription,
                $1:subtype::NUMBER AS subtype,
                CAST($1:reportablesuperamt AS NUMBER(18,2)) AS reportablesuperamt,
                CAST($1:holdreason::TEXT AS VARCHAR(16777216)) AS holdreason,
                $1:holddate::TIMESTAMP_TZ AS holddate,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwcc', 'ccx_paygsummaryhistory_icare') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS paygsummaryhistory_icare_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'fbtamount',
                        'payeesurname',
                        'updatetime',
                        'payeeaddr1',
                        'payeeaddr2',
                        'payeeaddr3',
                        'secondlatestyearlumpsume',
                        'secondlatestlumpsumeyear',
                        'totalallowances',
                        'createuserid',
                        'amendmentindicator',
                        'workplacegivingamt',
                        'beanversion',
                        'retired',
                        'latestyearlumpsume',
                        'latestlumpsumeyear',
                        'tottaxwithheld',
                        'updateuserid',
                        'payerid',
                        'dateproduced',
                        'paygsummarystatus',
                        'tfn',
                        'paygsnapshot_icare',
                        'paygsummary_icare',
                        'pmtperiodend',
                        'lumpsumpmtatype',
                        'publicid',
                        'financialyear',
                        'payee',
                        'createtime',
                        'payeestate',
                        'pmtperiodstart',
                        'cdep',
                        'paygsummarychanged',
                        'payeecountry',
                        'payeepostcode',
                        'claimid',
                        'outboundpack_icareid',
                        'lumpsuma',
                        'lumpsumb',
                        'lumpsumd',
                        'lumpsume',
                        'payeemiddlename',
                        'priorsecondlatestyearlumpsume',
                        'priorsecondlatestlumpsumeyear',
                        'archivepartition',
                        'payeesuburb',
                        'payeedob',
                        'grosspayments',
                        'payeefirstname',
                        'errordescription',
                        'subtype',
                        'reportablesuperamt',
                        'holdreason',
                        'holddate'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS dbt_updated_at
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}