{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for pc_effectivedatedfields.
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                record_insertion_date: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDA goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    incremental_strategy='append',
    on_schema_change='append_new_columns',
    tags=["landing", "gwpc", "policy_centre", "business_critical"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:PolicyAddress::NUMBER AS policyaddress,
                data_payload:SecondaryNamedInsured::NUMBER AS secondarynamedinsured,
                data_payload:isESRFlag::BOOLEAN AS isesrflag,
                data_payload:FixedID::NUMBER AS fixedid,
                data_payload:PrimaryNamedInsured::NUMBER AS primarynamedinsured,
                data_payload:ExpPremium_icare_cur::NUMBER AS exppremium_icare_cur,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                CAST(data_payload:WCSIDDLevy_icare AS NUMBER(18,2)) AS wcsiddlevy_icare,
                data_payload:ID::NUMBER AS id,
                CAST(data_payload:ExpPremium_icare_amt AS NUMBER(18,2)) AS exppremium_icare_amt,
                data_payload:CreateUserID::NUMBER AS createuserid,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:isRTWIFlag::BOOLEAN AS isrtwiflag,
                data_payload:IsLegacy_icare::BOOLEAN AS islegacy_icare,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                data_payload:WCLegacyTotalPrem_icare_cur::NUMBER AS wclegacytotalprem_icare_cur,
                data_payload:PrimaryLocation::NUMBER AS primarylocation,
                data_payload:BranchID::NUMBER AS branchid,
                CAST(data_payload:WCLegacyTotalPrem_icare_amt AS NUMBER(18,2)) AS wclegacytotalprem_icare_amt,
                CAST(data_payload:WCSIEXContLevy_icare AS NUMBER(18,2)) AS wcsiexcontlevy_icare,
                CAST(data_payload:WCExpAdjFactor_icare AS NUMBER(18,8)) AS wcexpadjfactor_icare,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                data_payload:BillingContact::NUMBER AS billingcontact,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                CAST(data_payload:WCSIContLevy_icare AS NUMBER(18,2)) AS wcsicontlevy_icare,
                data_payload:IsImmediateCover_icare::BOOLEAN AS isimmediatecover_icare,
                CAST(data_payload:WCSIEXDDLevy_icare AS NUMBER(18,2)) AS wcsiexddlevy_icare,
                CAST(data_payload:WCSIEXWorkesInslevy_icare AS NUMBER(18,2)) AS wcsiexworkesinslevy_icare,
                data_payload:WCLegacyGSTAmt_icare_cur::NUMBER AS wclegacygstamt_icare_cur,
                TO_TIMESTAMP_TZ(data_payload:EffectiveDate::NUMBER/1000) AS effectivedate,
                CAST(data_payload:WCLegacyGSTAmt_icare_amt AS NUMBER(18,2)) AS wclegacygstamt_icare_amt,
                data_payload:ProducerCodeID::NUMBER AS producercodeid,
                TO_TIMESTAMP_TZ(data_payload:ExpirationDate::NUMBER/1000) AS expirationdate,
                data_payload:GroupPeriodBTP_cur::NUMBER AS groupperiodbtp_cur,
                data_payload:WCExpPremium_icare_cur::NUMBER AS wcexppremium_icare_cur,
                data_payload:IsExempted_icare::BOOLEAN AS isexempted_icare,
                CAST(data_payload:WCSIWorkesInslevy_icare AS NUMBER(18,2)) AS wcsiworkesinslevy_icare,
                CAST(data_payload:GroupPeriodBTP_amt AS NUMBER(18,2)) AS groupperiodbtp_amt,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                CAST(data_payload:WCExpPremium_icare_amt AS NUMBER(18,2)) AS wcexppremium_icare_amt,
                data_payload:WCInputTaxAdjAmt_icare_cur::NUMBER AS wcinputtaxadjamt_icare_cur,
                data_payload:ChangeType::NUMBER AS changetype,
                data_payload:ITCAmount_icare_cur::NUMBER AS itcamount_icare_cur,
                data_payload:BasedOnID::NUMBER AS basedonid,
                CAST(data_payload:WCInputTaxAdjAmt_icare_amt AS NUMBER(18,2)) AS wcinputtaxadjamt_icare_amt,
                CAST(data_payload:OfferingCode::TEXT AS VARCHAR(64)) AS offeringcode,
                CAST(data_payload:ITCAmount_icare_amt AS NUMBER(18,2)) AS itcamount_icare_amt,
                CAST(data_payload:ReasonLowWages_icare::TEXT AS VARCHAR(60)) AS reasonlowwages_icare,
                CAST(data_payload:PeriodCategory_icare::TEXT AS VARCHAR(255)) AS periodcategory_icare,
                data_payload:isESIFlag::BOOLEAN AS isesiflag,
                CAST(data_payload:SFactor_icare AS NUMBER(12,8)) AS sfactor_icare,
                CAST(data_payload:WCLegacyGroupBTP_icare AS NUMBER(18,2)) AS wclegacygroupbtp_icare,
                CAST(data_payload:WCLegacyGroupWages_icare AS NUMBER(18,2)) AS wclegacygroupwages_icare,
                CAST(data_payload:WCLegacyFullPaidDiscount_icare AS NUMBER(18,2)) AS wclegacyfullpaiddiscount_icare,
                data_payload:ClaimSchemeAgent_icare::NUMBER AS claimschemeagent_icare,
                CAST(data_payload:LegacyGrpSFactor_icare AS NUMBER(7,4)) AS legacygrpsfactor_icare,
                data_payload:LegacyRPAAmt_icare_cur::NUMBER AS legacyrpaamt_icare_cur,
                CAST(data_payload:LegacyRPAAmt_icare_amt AS NUMBER(18,2)) AS legacyrpaamt_icare_amt,
                data_payload:GroupCostOfClaims_icare_cur::NUMBER AS groupcostofclaims_icare_cur,
                CAST(data_payload:LPRMaxPremium_icare AS NUMBER(18,2)) AS lprmaxpremium_icare,
                CAST(data_payload:GroupCostOfClaims_icare_amt AS NUMBER(18,2)) AS groupcostofclaims_icare_amt,
                CAST(data_payload:LPRGRPMinPremium_icare AS NUMBER(18,2)) AS lprgrpminpremium_icare,
                data_payload:LegacyGrpSecurity_icare_cur::NUMBER AS legacygrpsecurity_icare_cur,
                data_payload:GroupDepositPremium_cur::NUMBER AS groupdepositpremium_cur,
                data_payload:LegacyGrpRPAAmt_icare_cur::NUMBER AS legacygrprpaamt_icare_cur,
                CAST(data_payload:CoreSFactor_icare AS NUMBER(7,4)) AS coresfactor_icare,
                CAST(data_payload:LegacyGrpSecurity_icare_amt AS NUMBER(18,2)) AS legacygrpsecurity_icare_amt,
                CAST(data_payload:GroupDepositPremium_amt AS NUMBER(18,2)) AS groupdepositpremium_amt,
                CAST(data_payload:LegacyGrpRPAAmt_icare_amt AS NUMBER(18,2)) AS legacygrprpaamt_icare_amt,
                data_payload:LegacySecurity_icare_cur::NUMBER AS legacysecurity_icare_cur,
                CAST(data_payload:LegacySecurity_icare_amt AS NUMBER(18,2)) AS legacysecurity_icare_amt,
                CAST(data_payload:LPRSecurityAmt_icare AS NUMBER(18,2)) AS lprsecurityamt_icare,
                CAST(data_payload:LPRGRPMaxPremium_icare AS NUMBER(18,2)) AS lprgrpmaxpremium_icare,
                CAST(data_payload:LPRMinPremium_icare AS NUMBER(18,2)) AS lprminpremium_icare,
                data_payload:CRIFBillingOption_icare::NUMBER AS crifbillingoption_icare,
                data_payload:CRIFClaim::BOOLEAN AS crifclaim,
                data_payload:PolicyPriorLossStatus_icare::NUMBER AS policypriorlossstatus_icare,
                data_payload:ESIFlagNew_Ext::BOOLEAN AS esiflagnew_ext,
                data_payload:IsCovidLevyFlag_Ext::BOOLEAN AS iscovidlevyflag_ext,
                data_payload:GrpBasePremForLPRPlus_Ext_cur::NUMBER AS grpbasepremforlprplus_ext_cur,
                CAST(data_payload:GrpBasePremForLPRPlus_Ext_amt AS NUMBER(18,2)) AS grpbasepremforlprplus_ext_amt,
                data_payload:GroupBTP_Ext_cur::NUMBER AS groupbtp_ext_cur,
                CAST(data_payload:GroupBTP_Ext_amt AS NUMBER(18,2)) AS groupbtp_ext_amt,
                data_payload:IsSEROverriden_Ext::BOOLEAN AS isseroverriden_ext,
                data_payload:TotalGroupCostOfClaim_Ext_cur::NUMBER AS totalgroupcostofclaim_ext_cur,
                CAST(data_payload:TotalGroupCostOfClaim_Ext_amt AS NUMBER(18,2)) AS totalgroupcostofclaim_ext_amt,
                CAST(data_payload:LPRPLUSMinPremium_Ext AS NUMBER(18,2)) AS lprplusminpremium_ext,
                CAST(data_payload:LPRPLUSGRPMinPremium_Ext AS NUMBER(18,2)) AS lprplusgrpminpremium_ext,
                data_payload:OpenClaimsGroupCost_Ext_cur::NUMBER AS openclaimsgroupcost_ext_cur,
                CAST(data_payload:OpenClaimsGroupCost_Ext_amt AS NUMBER(18,2)) AS openclaimsgroupcost_ext_amt,
                CAST(data_payload:LPRPLUSMaxPremium_Ext AS NUMBER(18,2)) AS lprplusmaxpremium_ext,
                data_payload:ClosedClaimsGroupCost_Ext_cur::NUMBER AS closedclaimsgroupcost_ext_cur,
                CAST(data_payload:LPRPLUSGRPMaxPremium_Ext AS NUMBER(18,2)) AS lprplusgrpmaxpremium_ext,
                CAST(data_payload:ClosedClaimsGroupCost_Ext_amt AS NUMBER(18,2)) AS closedclaimsgroupcost_ext_amt,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS VARCHAR(300)) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'AVRO' as file_type,
                'GWPC' as source_system
            FROM {{ source('gwpc', 'pc_effectivedatedfields') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:policyaddress::NUMBER AS policyaddress,
                $1:secondarynamedinsured::NUMBER AS secondarynamedinsured,
                $1:isesrflag::BOOLEAN AS isesrflag,
                $1:fixedid::NUMBER AS fixedid,
                $1:primarynamedinsured::NUMBER AS primarynamedinsured,
                $1:exppremium_icare_cur::NUMBER AS exppremium_icare_cur,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                CAST($1:wcsiddlevy_icare AS NUMBER(18,2)) AS wcsiddlevy_icare,
                $1:id::NUMBER AS id,
                CAST($1:exppremium_icare_amt AS NUMBER(18,2)) AS exppremium_icare_amt,
                $1:createuserid::NUMBER AS createuserid,
                $1:beanversion::NUMBER AS beanversion,
                $1:isrtwiflag::BOOLEAN AS isrtwiflag,
                $1:islegacy_icare::BOOLEAN AS islegacy_icare,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:wclegacytotalprem_icare_cur::NUMBER AS wclegacytotalprem_icare_cur,
                $1:primarylocation::NUMBER AS primarylocation,
                $1:branchid::NUMBER AS branchid,
                CAST($1:wclegacytotalprem_icare_amt AS NUMBER(18,2)) AS wclegacytotalprem_icare_amt,
                CAST($1:wcsiexcontlevy_icare AS NUMBER(18,2)) AS wcsiexcontlevy_icare,
                CAST($1:wcexpadjfactor_icare AS NUMBER(18,8)) AS wcexpadjfactor_icare,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:billingcontact::NUMBER AS billingcontact,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                CAST($1:wcsicontlevy_icare AS NUMBER(18,2)) AS wcsicontlevy_icare,
                $1:isimmediatecover_icare::BOOLEAN AS isimmediatecover_icare,
                CAST($1:wcsiexddlevy_icare AS NUMBER(18,2)) AS wcsiexddlevy_icare,
                CAST($1:wcsiexworkesinslevy_icare AS NUMBER(18,2)) AS wcsiexworkesinslevy_icare,
                $1:wclegacygstamt_icare_cur::NUMBER AS wclegacygstamt_icare_cur,
                $1:effectivedate::TIMESTAMP_TZ AS effectivedate,
                CAST($1:wclegacygstamt_icare_amt AS NUMBER(18,2)) AS wclegacygstamt_icare_amt,
                $1:producercodeid::NUMBER AS producercodeid,
                $1:expirationdate::TIMESTAMP_TZ AS expirationdate,
                $1:groupperiodbtp_cur::NUMBER AS groupperiodbtp_cur,
                $1:wcexppremium_icare_cur::NUMBER AS wcexppremium_icare_cur,
                $1:isexempted_icare::BOOLEAN AS isexempted_icare,
                CAST($1:wcsiworkesinslevy_icare AS NUMBER(18,2)) AS wcsiworkesinslevy_icare,
                CAST($1:groupperiodbtp_amt AS NUMBER(18,2)) AS groupperiodbtp_amt,
                $1:archivepartition::NUMBER AS archivepartition,
                CAST($1:wcexppremium_icare_amt AS NUMBER(18,2)) AS wcexppremium_icare_amt,
                $1:wcinputtaxadjamt_icare_cur::NUMBER AS wcinputtaxadjamt_icare_cur,
                $1:changetype::NUMBER AS changetype,
                $1:itcamount_icare_cur::NUMBER AS itcamount_icare_cur,
                $1:basedonid::NUMBER AS basedonid,
                CAST($1:wcinputtaxadjamt_icare_amt AS NUMBER(18,2)) AS wcinputtaxadjamt_icare_amt,
                CAST($1:offeringcode::TEXT AS VARCHAR(64)) AS offeringcode,
                CAST($1:itcamount_icare_amt AS NUMBER(18,2)) AS itcamount_icare_amt,
                CAST($1:reasonlowwages_icare::TEXT AS VARCHAR(60)) AS reasonlowwages_icare,
                CAST($1:periodcategory_icare::TEXT AS VARCHAR(255)) AS periodcategory_icare,
                $1:isesiflag::BOOLEAN AS isesiflag,
                CAST($1:sfactor_icare AS NUMBER(12,8)) AS sfactor_icare,
                CAST($1:wclegacygroupbtp_icare AS NUMBER(18,2)) AS wclegacygroupbtp_icare,
                CAST($1:wclegacygroupwages_icare AS NUMBER(18,2)) AS wclegacygroupwages_icare,
                CAST($1:wclegacyfullpaiddiscount_icare AS NUMBER(18,2)) AS wclegacyfullpaiddiscount_icare,
                $1:claimschemeagent_icare::NUMBER AS claimschemeagent_icare,
                CAST($1:legacygrpsfactor_icare AS NUMBER(7,4)) AS legacygrpsfactor_icare,
                $1:legacyrpaamt_icare_cur::NUMBER AS legacyrpaamt_icare_cur,
                CAST($1:legacyrpaamt_icare_amt AS NUMBER(18,2)) AS legacyrpaamt_icare_amt,
                $1:groupcostofclaims_icare_cur::NUMBER AS groupcostofclaims_icare_cur,
                CAST($1:lprmaxpremium_icare AS NUMBER(18,2)) AS lprmaxpremium_icare,
                CAST($1:groupcostofclaims_icare_amt AS NUMBER(18,2)) AS groupcostofclaims_icare_amt,
                CAST($1:lprgrpminpremium_icare AS NUMBER(18,2)) AS lprgrpminpremium_icare,
                $1:legacygrpsecurity_icare_cur::NUMBER AS legacygrpsecurity_icare_cur,
                $1:groupdepositpremium_cur::NUMBER AS groupdepositpremium_cur,
                $1:legacygrprpaamt_icare_cur::NUMBER AS legacygrprpaamt_icare_cur,
                CAST($1:coresfactor_icare AS NUMBER(7,4)) AS coresfactor_icare,
                CAST($1:legacygrpsecurity_icare_amt AS NUMBER(18,2)) AS legacygrpsecurity_icare_amt,
                CAST($1:groupdepositpremium_amt AS NUMBER(18,2)) AS groupdepositpremium_amt,
                CAST($1:legacygrprpaamt_icare_amt AS NUMBER(18,2)) AS legacygrprpaamt_icare_amt,
                $1:legacysecurity_icare_cur::NUMBER AS legacysecurity_icare_cur,
                CAST($1:legacysecurity_icare_amt AS NUMBER(18,2)) AS legacysecurity_icare_amt,
                CAST($1:lprsecurityamt_icare AS NUMBER(18,2)) AS lprsecurityamt_icare,
                CAST($1:lprgrpmaxpremium_icare AS NUMBER(18,2)) AS lprgrpmaxpremium_icare,
                CAST($1:lprminpremium_icare AS NUMBER(18,2)) AS lprminpremium_icare,
                $1:crifbillingoption_icare::NUMBER AS crifbillingoption_icare,
                $1:crifclaim::BOOLEAN AS crifclaim,
                $1:policypriorlossstatus_icare::NUMBER AS policypriorlossstatus_icare,
                $1:esiflagnew_ext::BOOLEAN AS esiflagnew_ext,
                $1:iscovidlevyflag_ext::BOOLEAN AS iscovidlevyflag_ext,
                $1:grpbasepremforlprplus_ext_cur::NUMBER AS grpbasepremforlprplus_ext_cur,
                CAST($1:grpbasepremforlprplus_ext_amt AS NUMBER(18,2)) AS grpbasepremforlprplus_ext_amt,
                $1:groupbtp_ext_cur::NUMBER AS groupbtp_ext_cur,
                CAST($1:groupbtp_ext_amt AS NUMBER(18,2)) AS groupbtp_ext_amt,
                $1:isseroverriden_ext::BOOLEAN AS isseroverriden_ext,
                $1:totalgroupcostofclaim_ext_cur::NUMBER AS totalgroupcostofclaim_ext_cur,
                CAST($1:totalgroupcostofclaim_ext_amt AS NUMBER(18,2)) AS totalgroupcostofclaim_ext_amt,
                CAST($1:lprplusminpremium_ext AS NUMBER(18,2)) AS lprplusminpremium_ext,
                CAST($1:lprplusgrpminpremium_ext AS NUMBER(18,2)) AS lprplusgrpminpremium_ext,
                $1:openclaimsgroupcost_ext_cur::NUMBER AS openclaimsgroupcost_ext_cur,
                CAST($1:openclaimsgroupcost_ext_amt AS NUMBER(18,2)) AS openclaimsgroupcost_ext_amt,
                CAST($1:lprplusmaxpremium_ext AS NUMBER(18,2)) AS lprplusmaxpremium_ext,
                $1:closedclaimsgroupcost_ext_cur::NUMBER AS closedclaimsgroupcost_ext_cur,
                CAST($1:lprplusgrpmaxpremium_ext AS NUMBER(18,2)) AS lprplusgrpmaxpremium_ext,
                CAST($1:closedclaimsgroupcost_ext_amt AS NUMBER(18,2)) AS closedclaimsgroupcost_ext_amt,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::VARCHAR(300) as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'PARQUET' as file_type,
                'GWPC' as source_system
            FROM {{ source('gwpc', 'pc_effectivedatedfields') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS effectivedatedfields_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'policyaddress',
                        'secondarynamedinsured',
                        'isesrflag',
                        'fixedid',
                        'primarynamedinsured',
                        'exppremium_icare_cur',
                        'updatetime',
                        'wcsiddlevy_icare',
                        'exppremium_icare_amt',
                        'createuserid',
                        'beanversion',
                        'isrtwiflag',
                        'islegacy_icare',
                        'updateuserid',
                        'wclegacytotalprem_icare_cur',
                        'primarylocation',
                        'branchid',
                        'wclegacytotalprem_icare_amt',
                        'wcsiexcontlevy_icare',
                        'wcexpadjfactor_icare',
                        'publicid',
                        'billingcontact',
                        'createtime',
                        'wcsicontlevy_icare',
                        'isimmediatecover_icare',
                        'wcsiexddlevy_icare',
                        'wcsiexworkesinslevy_icare',
                        'wclegacygstamt_icare_cur',
                        'effectivedate',
                        'wclegacygstamt_icare_amt',
                        'producercodeid',
                        'expirationdate',
                        'groupperiodbtp_cur',
                        'wcexppremium_icare_cur',
                        'isexempted_icare',
                        'wcsiworkesinslevy_icare',
                        'groupperiodbtp_amt',
                        'archivepartition',
                        'wcexppremium_icare_amt',
                        'wcinputtaxadjamt_icare_cur',
                        'changetype',
                        'itcamount_icare_cur',
                        'basedonid',
                        'wcinputtaxadjamt_icare_amt',
                        'offeringcode',
                        'itcamount_icare_amt',
                        'reasonlowwages_icare',
                        'periodcategory_icare',
                        'isesiflag',
                        'sfactor_icare',
                        'wclegacygroupbtp_icare',
                        'wclegacygroupwages_icare',
                        'wclegacyfullpaiddiscount_icare',
                        'claimschemeagent_icare',
                        'legacygrpsfactor_icare',
                        'legacyrpaamt_icare_cur',
                        'legacyrpaamt_icare_amt',
                        'groupcostofclaims_icare_cur',
                        'lprmaxpremium_icare',
                        'groupcostofclaims_icare_amt',
                        'lprgrpminpremium_icare',
                        'legacygrpsecurity_icare_cur',
                        'groupdepositpremium_cur',
                        'legacygrprpaamt_icare_cur',
                        'coresfactor_icare',
                        'legacygrpsecurity_icare_amt',
                        'groupdepositpremium_amt',
                        'legacygrprpaamt_icare_amt',
                        'legacysecurity_icare_cur',
                        'legacysecurity_icare_amt',
                        'lprsecurityamt_icare',
                        'lprgrpmaxpremium_icare',
                        'lprminpremium_icare',
                        'crifbillingoption_icare',
                        'crifclaim',
                        'policypriorlossstatus_icare',
                        'esiflagnew_ext',
                        'iscovidlevyflag_ext',
                        'grpbasepremforlprplus_ext_cur',
                        'grpbasepremforlprplus_ext_amt',
                        'groupbtp_ext_cur',
                        'groupbtp_ext_amt',
                        'isseroverriden_ext',
                        'totalgroupcostofclaim_ext_cur',
                        'totalgroupcostofclaim_ext_amt',
                        'lprplusminpremium_ext',
                        'lprplusgrpminpremium_ext',
                        'openclaimsgroupcost_ext_cur',
                        'openclaimsgroupcost_ext_amt',
                        'lprplusmaxpremium_ext',
                        'closedclaimsgroupcost_ext_cur',
                        'lprplusgrpmaxpremium_ext',
                        'closedclaimsgroupcost_ext_amt'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
    WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}
    ORDER BY record_insertion_date
