{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for pc_job.
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                record_insertion_date: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDA goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    incremental_strategy='append',
    on_schema_change='append_new_columns',
    tags=["landing", "gwpc", "policy_centre", "business_critical"]
) }}


WITH cte_source_data AS 
(

            SELECT
                TO_TIMESTAMP_TZ(data_payload:NotTakenNotifDate::NUMBER/1000) AS nottakennotifdate,
                data_payload:ArchiveState::NUMBER AS archivestate,
                data_payload:ArchiveSchemaInfo::NUMBER AS archiveschemainfo,
                TO_TIMESTAMP_TZ(data_payload:QuotedDate_icare::NUMBER/1000) AS quoteddate_icare,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                TO_TIMESTAMP_TZ(data_payload:NotificationDate::NUMBER/1000) AS notificationdate,
                data_payload:ID::NUMBER AS id,
                data_payload:Source::NUMBER AS source,
                CAST(data_payload:ExcludeReason::TEXT AS VARCHAR(255)) AS excludereason,
                TO_TIMESTAMP_TZ(data_payload:NextPurgeCheckDate::NUMBER/1000) AS nextpurgecheckdate,
                data_payload:CreateUserID::NUMBER AS createuserid,
                data_payload:ArchiveFailureID::NUMBER AS archivefailureid,
                data_payload:RejectReason::NUMBER AS rejectreason,
                TO_TIMESTAMP_TZ(data_payload:CloseDate::NUMBER/1000) AS closedate,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:Retired::NUMBER AS retired,
                data_payload:CancelReasonCode::NUMBER AS cancelreasoncode,
                data_payload:ChangePolicyNumber::BOOLEAN AS changepolicynumber,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                CAST(data_payload:PrimaryInsuredNameDenorm::TEXT AS VARCHAR(255)) AS primaryinsurednamedenorm,
                TO_TIMESTAMP_TZ(data_payload:NonRenewalNotifDate::NUMBER/1000) AS nonrenewalnotifdate,
                CAST(data_payload:PrimaryInsuredName::TEXT AS VARCHAR(255)) AS primaryinsuredname,
                data_payload:QuoteType::NUMBER AS quotetype,
                TO_TIMESTAMP_TZ(data_payload:DateQuoteNeeded::NUMBER/1000) AS datequoteneeded,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                data_payload:SideBySide::BOOLEAN AS sidebyside,
                CAST(data_payload:JobNumber::TEXT AS VARCHAR(60)) AS jobnumber,
                data_payload:RewriteType::NUMBER AS rewritetype,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                data_payload:AuditInformationID::NUMBER AS auditinformationid,
                data_payload:PolicyID::NUMBER AS policyid,
                data_payload:ExcludedFromArchive::BOOLEAN AS excludedfromarchive,
                CAST(data_payload:RejectReasonText::TEXT AS VARCHAR(16777216)) AS rejectreasontext,
                data_payload:ArchiveFailureDetailsID::NUMBER AS archivefailuredetailsid,
                TO_TIMESTAMP_TZ(data_payload:RescindNotificationDate::NUMBER/1000) AS rescindnotificationdate,
                data_payload:PurgeStatus::NUMBER AS purgestatus,
                TO_TIMESTAMP_TZ(data_payload:InitialNotificationDate::NUMBER/1000) AS initialnotificationdate,
                TO_TIMESTAMP_TZ(data_payload:LastNotifiedCancellationDate::NUMBER/1000) AS lastnotifiedcancellationdate,
                data_payload:JobGroup::NUMBER AS jobgroup,
                TO_TIMESTAMP_TZ(data_payload:CancelProcessDate::NUMBER/1000) AS cancelprocessdate,
                data_payload:RenewalCode::NUMBER AS renewalcode,
                data_payload:EscalateAfterHoldReleased::BOOLEAN AS escalateafterholdreleased,
                TO_TIMESTAMP_TZ(data_payload:RenewalNotifDate::NUMBER/1000) AS renewalnotifdate,
                data_payload:ReinstateCode::NUMBER AS reinstatecode,
                CAST(data_payload:PaymentReceived AS NUMBER(18,2)) AS paymentreceived,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                data_payload:PaymentReceived_cur::NUMBER AS paymentreceived_cur,
                TO_TIMESTAMP_TZ(data_payload:NotificationAckDate::NUMBER/1000) AS notificationackdate,
                TO_TIMESTAMP_TZ(data_payload:ArchiveDate::NUMBER/1000) AS archivedate,
                data_payload:BindOption::NUMBER AS bindoption,
                data_payload:NonRenewalCode::NUMBER AS nonrenewalcode,
                data_payload:Subtype::NUMBER AS subtype,
                TO_TIMESTAMP_TZ(data_payload:SubmissionDate::NUMBER/1000) AS submissiondate,
                CAST(data_payload:Description::TEXT AS VARCHAR(1333)) AS description,
                data_payload:ContributedToNIGroup_icare::BOOLEAN AS contributedtonigroup_icare,
                data_payload:IsABNChanged_icare::BOOLEAN AS isabnchanged_icare,
                data_payload:PriorAnonymous_icare::BOOLEAN AS prioranonymous_icare,
                data_payload:PolicyChangeReason_icare::NUMBER AS policychangereason_icare,
                data_payload:SchemeAgentChange_icare::NUMBER AS schemeagentchange_icare,
                data_payload:Forecast_icare::BOOLEAN AS forecast_icare,
                data_payload:ProducerChangeSource_Ext::NUMBER AS producerchangesource_ext,
                data_payload:ChangeType_icare::NUMBER AS changetype_icare,
                data_payload:ForecastCalculation_icare::NUMBER AS forecastcalculation_icare,
                data_payload:ReasonCodeForCancel_icare::NUMBER AS reasoncodeforcancel_icare,
                CAST(data_payload:RequestedBy_icare::TEXT AS VARCHAR(1333)) AS requestedby_icare,
                data_payload:CancelOnExpiryReason_icare::NUMBER AS cancelonexpiryreason_icare,
                data_payload:SuppressDocuments_icare::BOOLEAN AS suppressdocuments_icare,
                data_payload:IsGroupStructureChanged_icare::BOOLEAN AS isgroupstructurechanged_icare,
                data_payload:GotBussInLast12Mons_icare::BOOLEAN AS gotbussinlast12mons_icare,
                data_payload:isLoadingApplied_icare::BOOLEAN AS isloadingapplied_icare,
                data_payload:PolicyTerm::NUMBER AS policyterm,
                CAST(data_payload:JobNumberDenorm::TEXT AS VARCHAR(60)) AS jobnumberdenorm,
                data_payload:IsCSSPortal_Ext::BOOLEAN AS iscssportal_ext,
                data_payload:IsCRIFReminderEmailSent_Ext::BOOLEAN AS iscrifreminderemailsent_ext,
                data_payload:WageAuditType_Ext::NUMBER AS wageaudittype_ext,
                data_payload:IsBulkPolicyCancel_Ext::BOOLEAN AS isbulkpolicycancel_ext,
                data_payload:IsSelectedFromGroup_Ext::BOOLEAN AS isselectedfromgroup_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS VARCHAR(300)) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'AVRO' as file_type,
                'GWPC' as source_system
            FROM {{ source('gwpc', 'pc_job') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:nottakennotifdate::TIMESTAMP_TZ AS nottakennotifdate,
                $1:archivestate::NUMBER AS archivestate,
                $1:archiveschemainfo::NUMBER AS archiveschemainfo,
                $1:quoteddate_icare::TIMESTAMP_TZ AS quoteddate_icare,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:notificationdate::TIMESTAMP_TZ AS notificationdate,
                $1:id::NUMBER AS id,
                $1:source::NUMBER AS source,
                CAST($1:excludereason::TEXT AS VARCHAR(255)) AS excludereason,
                $1:nextpurgecheckdate::TIMESTAMP_TZ AS nextpurgecheckdate,
                $1:createuserid::NUMBER AS createuserid,
                $1:archivefailureid::NUMBER AS archivefailureid,
                $1:rejectreason::NUMBER AS rejectreason,
                $1:closedate::TIMESTAMP_TZ AS closedate,
                $1:beanversion::NUMBER AS beanversion,
                $1:retired::NUMBER AS retired,
                $1:cancelreasoncode::NUMBER AS cancelreasoncode,
                $1:changepolicynumber::BOOLEAN AS changepolicynumber,
                $1:updateuserid::NUMBER AS updateuserid,
                CAST($1:primaryinsurednamedenorm::TEXT AS VARCHAR(255)) AS primaryinsurednamedenorm,
                $1:nonrenewalnotifdate::TIMESTAMP_TZ AS nonrenewalnotifdate,
                CAST($1:primaryinsuredname::TEXT AS VARCHAR(255)) AS primaryinsuredname,
                $1:quotetype::NUMBER AS quotetype,
                $1:datequoteneeded::TIMESTAMP_TZ AS datequoteneeded,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:sidebyside::BOOLEAN AS sidebyside,
                CAST($1:jobnumber::TEXT AS VARCHAR(60)) AS jobnumber,
                $1:rewritetype::NUMBER AS rewritetype,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:auditinformationid::NUMBER AS auditinformationid,
                $1:policyid::NUMBER AS policyid,
                $1:excludedfromarchive::BOOLEAN AS excludedfromarchive,
                CAST($1:rejectreasontext::TEXT AS VARCHAR(16777216)) AS rejectreasontext,
                $1:archivefailuredetailsid::NUMBER AS archivefailuredetailsid,
                $1:rescindnotificationdate::TIMESTAMP_TZ AS rescindnotificationdate,
                $1:purgestatus::NUMBER AS purgestatus,
                $1:initialnotificationdate::TIMESTAMP_TZ AS initialnotificationdate,
                $1:lastnotifiedcancellationdate::TIMESTAMP_TZ AS lastnotifiedcancellationdate,
                $1:jobgroup::NUMBER AS jobgroup,
                $1:cancelprocessdate::TIMESTAMP_TZ AS cancelprocessdate,
                $1:renewalcode::NUMBER AS renewalcode,
                $1:escalateafterholdreleased::BOOLEAN AS escalateafterholdreleased,
                $1:renewalnotifdate::TIMESTAMP_TZ AS renewalnotifdate,
                $1:reinstatecode::NUMBER AS reinstatecode,
                CAST($1:paymentreceived AS NUMBER(18,2)) AS paymentreceived,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:paymentreceived_cur::NUMBER AS paymentreceived_cur,
                $1:notificationackdate::TIMESTAMP_TZ AS notificationackdate,
                $1:archivedate::TIMESTAMP_TZ AS archivedate,
                $1:bindoption::NUMBER AS bindoption,
                $1:nonrenewalcode::NUMBER AS nonrenewalcode,
                $1:subtype::NUMBER AS subtype,
                $1:submissiondate::TIMESTAMP_TZ AS submissiondate,
                CAST($1:description::TEXT AS VARCHAR(1333)) AS description,
                $1:contributedtonigroup_icare::BOOLEAN AS contributedtonigroup_icare,
                $1:isabnchanged_icare::BOOLEAN AS isabnchanged_icare,
                $1:prioranonymous_icare::BOOLEAN AS prioranonymous_icare,
                $1:policychangereason_icare::NUMBER AS policychangereason_icare,
                $1:schemeagentchange_icare::NUMBER AS schemeagentchange_icare,
                $1:forecast_icare::BOOLEAN AS forecast_icare,
                $1:producerchangesource_ext::NUMBER AS producerchangesource_ext,
                $1:changetype_icare::NUMBER AS changetype_icare,
                $1:forecastcalculation_icare::NUMBER AS forecastcalculation_icare,
                $1:reasoncodeforcancel_icare::NUMBER AS reasoncodeforcancel_icare,
                CAST($1:requestedby_icare::TEXT AS VARCHAR(1333)) AS requestedby_icare,
                $1:cancelonexpiryreason_icare::NUMBER AS cancelonexpiryreason_icare,
                $1:suppressdocuments_icare::BOOLEAN AS suppressdocuments_icare,
                $1:isgroupstructurechanged_icare::BOOLEAN AS isgroupstructurechanged_icare,
                $1:gotbussinlast12mons_icare::BOOLEAN AS gotbussinlast12mons_icare,
                $1:isloadingapplied_icare::BOOLEAN AS isloadingapplied_icare,
                $1:policyterm::NUMBER AS policyterm,
                CAST($1:jobnumberdenorm::TEXT AS VARCHAR(60)) AS jobnumberdenorm,
                $1:iscssportal_ext::BOOLEAN AS iscssportal_ext,
                $1:iscrifreminderemailsent_ext::BOOLEAN AS iscrifreminderemailsent_ext,
                $1:wageaudittype_ext::NUMBER AS wageaudittype_ext,
                $1:isbulkpolicycancel_ext::BOOLEAN AS isbulkpolicycancel_ext,
                $1:isselectedfromgroup_ext::BOOLEAN AS isselectedfromgroup_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::VARCHAR(300) as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'PARQUET' as file_type,
                'GWPC' as source_system
            FROM {{ source('gwpc', 'pc_job') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS job_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'nottakennotifdate',
                        'archivestate',
                        'archiveschemainfo',
                        'quoteddate_icare',
                        'updatetime',
                        'notificationdate',
                        'source',
                        'excludereason',
                        'nextpurgecheckdate',
                        'createuserid',
                        'archivefailureid',
                        'rejectreason',
                        'closedate',
                        'beanversion',
                        'retired',
                        'cancelreasoncode',
                        'changepolicynumber',
                        'updateuserid',
                        'primaryinsurednamedenorm',
                        'nonrenewalnotifdate',
                        'primaryinsuredname',
                        'quotetype',
                        'datequoteneeded',
                        'publicid',
                        'sidebyside',
                        'jobnumber',
                        'rewritetype',
                        'createtime',
                        'auditinformationid',
                        'policyid',
                        'excludedfromarchive',
                        'rejectreasontext',
                        'archivefailuredetailsid',
                        'rescindnotificationdate',
                        'purgestatus',
                        'initialnotificationdate',
                        'lastnotifiedcancellationdate',
                        'jobgroup',
                        'cancelprocessdate',
                        'renewalcode',
                        'escalateafterholdreleased',
                        'renewalnotifdate',
                        'reinstatecode',
                        'paymentreceived',
                        'archivepartition',
                        'paymentreceived_cur',
                        'notificationackdate',
                        'archivedate',
                        'bindoption',
                        'nonrenewalcode',
                        'subtype',
                        'submissiondate',
                        'description',
                        'contributedtonigroup_icare',
                        'isabnchanged_icare',
                        'prioranonymous_icare',
                        'policychangereason_icare',
                        'schemeagentchange_icare',
                        'forecast_icare',
                        'producerchangesource_ext',
                        'changetype_icare',
                        'forecastcalculation_icare',
                        'reasoncodeforcancel_icare',
                        'requestedby_icare',
                        'cancelonexpiryreason_icare',
                        'suppressdocuments_icare',
                        'isgroupstructurechanged_icare',
                        'gotbussinlast12mons_icare',
                        'isloadingapplied_icare',
                        'policyterm',
                        'jobnumberdenorm',
                        'iscssportal_ext',
                        'iscrifreminderemailsent_ext',
                        'wageaudittype_ext',
                        'isbulkpolicycancel_ext',
                        'isselectedfromgroup_ext'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
    WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}
    ORDER BY record_insertion_date
