{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for pc_contact.
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                record_insertion_date: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDA goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    incremental_strategy='append',
    on_schema_change='append_new_columns',
    tags=["landing", "gwpc", "policy_centre", "business_critical"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                data_payload:Preferred::BOOLEAN AS preferred,
                data_payload:VendorType::NUMBER AS vendortype,
                data_payload:FaxPhoneCountry::NUMBER AS faxphonecountry,
                CAST(data_payload:Particle::TEXT AS VARCHAR(250)) AS particle,
                CAST(data_payload:TaxID::TEXT AS VARCHAR(30)) AS taxid,
                CAST(data_payload:NameDenorm::TEXT AS VARCHAR(255)) AS namedenorm,
                data_payload:MobilePhoneCountry::NUMBER AS mobilephonecountry,
                CAST(data_payload:Name::TEXT AS VARCHAR(255)) AS name,
                CAST(data_payload:VendorNumber::TEXT AS VARCHAR(60)) AS vendornumber,
                data_payload:State::NUMBER AS state,
                data_payload:Prefix::NUMBER AS prefix,
                data_payload:Score::NUMBER AS score,
                data_payload:PreferredCurrency::NUMBER AS preferredcurrency,
                CAST(data_payload:LastNameKanji::TEXT AS VARCHAR(250)) AS lastnamekanji,
                data_payload:TaxFilingStatus::NUMBER AS taxfilingstatus,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:AccountHolderCount::NUMBER AS accountholdercount,
                data_payload:Country::NUMBER AS country,
                CAST(data_payload:AdjudicatorLicense::TEXT AS VARCHAR(30)) AS adjudicatorlicense,
                data_payload:ID::NUMBER AS id,
                CAST(data_payload:WithholdingRate AS NUMBER(4,1)) AS withholdingrate,
                CAST(data_payload:LastNameDenorm::TEXT AS VARCHAR(250)) AS lastnamedenorm,
                CAST(data_payload:MiddleName::TEXT AS VARCHAR(250)) AS middlename,
                CAST(data_payload:LastName::TEXT AS VARCHAR(250)) AS lastname,
                data_payload:CreateUserID::NUMBER AS createuserid,
                CAST(data_payload:ExternalID::TEXT AS VARCHAR(255)) AS externalid,
                CAST(data_payload:MobileNumber_icare::TEXT AS VARCHAR(30)) AS mobilenumber_icare,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:VenueType::NUMBER AS venuetype,
                data_payload:Retired::NUMBER AS retired,
                data_payload:ValidationLevel::NUMBER AS validationlevel,
                data_payload:PrimaryPhone::NUMBER AS primaryphone,
                TO_TIMESTAMP_TZ(data_payload:LastUpdateTime::NUMBER/1000) AS lastupdatetime,
                data_payload:ExternalVersion::NUMBER AS externalversion,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                CAST(data_payload:HomePhoneExtension::TEXT AS VARCHAR(60)) AS homephoneextension,
                CAST(data_payload:ContactPerson_icare::TEXT AS VARCHAR(60)) AS contactperson_icare,
                CAST(data_payload:MobilePhoneExtension::TEXT AS VARCHAR(60)) AS mobilephoneextension,
                CAST(data_payload:FirstNameDenorm::TEXT AS VARCHAR(250)) AS firstnamedenorm,
                CAST(data_payload:FirstName::TEXT AS VARCHAR(250)) AS firstname,
                CAST(data_payload:FirstNameKanji::TEXT AS VARCHAR(250)) AS firstnamekanji,
                TO_TIMESTAMP_TZ(data_payload:TemporaryLastUpdateTime::NUMBER/1000) AS temporarylastupdatetime,
                data_payload:Gender::NUMBER AS gender,
                CAST(data_payload:Notes::TEXT AS VARCHAR(16777216)) AS notes,
                data_payload:NumDependentsU18::NUMBER AS numdependentsu18,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                data_payload:HomePhoneCountry::NUMBER AS homephonecountry,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                CAST(data_payload:LicenseNumber::TEXT AS VARCHAR(20)) AS licensenumber,
                data_payload:CellPhoneCountry::NUMBER AS cellphonecountry,
                data_payload:AutoSync::NUMBER AS autosync,
                CAST(data_payload:Occupation::TEXT AS VARCHAR(80)) AS occupation,
                CAST(data_payload:CellPhone::TEXT AS VARCHAR(30)) AS cellphone,
                data_payload:PrimaryAddressID::NUMBER AS primaryaddressid,
                data_payload:Suffix::NUMBER AS suffix,
                CAST(data_payload:AddressBookUID::TEXT AS VARCHAR(64)) AS addressbookuid,
                CAST(data_payload:Website_icare::TEXT AS VARCHAR(255)) AS website_icare,
                data_payload:LoadRelatedContacts::BOOLEAN AS loadrelatedcontacts,
                CAST(data_payload:EmailAddress1::TEXT AS VARCHAR(60)) AS emailaddress1,
                data_payload:NumDependents::NUMBER AS numdependents,
                TO_TIMESTAMP_TZ(data_payload:DateOfBirth::NUMBER/1000) AS dateofbirth,
                data_payload:PrimaryLanguage::NUMBER AS primarylanguage,
                CAST(data_payload:EmailAddress2::TEXT AS VARCHAR(60)) AS emailaddress2,
                data_payload:PrimaryLocale::NUMBER AS primarylocale,
                data_payload:TaxStatus::NUMBER AS taxstatus,
                data_payload:NumDependentsU25::NUMBER AS numdependentsu25,
                CAST(data_payload:WorkPhoneExtension::TEXT AS VARCHAR(60)) AS workphoneextension,
                data_payload:MaritalStatus::NUMBER AS maritalstatus,
                CAST(data_payload:CityDenorm::TEXT AS VARCHAR(60)) AS citydenorm,
                CAST(data_payload:NameKanji::TEXT AS VARCHAR(255)) AS namekanji,
                CAST(data_payload:FaxPhoneExtension::TEXT AS VARCHAR(60)) AS faxphoneextension,
                CAST(data_payload:HomePhone::TEXT AS VARCHAR(30)) AS homephone,
                data_payload:LicenseState::NUMBER AS licensestate,
                CAST(data_payload:FaxPhone::TEXT AS VARCHAR(30)) AS faxphone,
                CAST(data_payload:CellPhoneExtension::TEXT AS VARCHAR(60)) AS cellphoneextension,
                CAST(data_payload:PostalCodeDenorm::TEXT AS VARCHAR(60)) AS postalcodedenorm,
                data_payload:ComunicatnPrfrnce_icare::NUMBER AS comunicatnprfrnce_icare,
                CAST(data_payload:EmployeeNumber::TEXT AS VARCHAR(255)) AS employeenumber,
                data_payload:WorkPhoneCountry::NUMBER AS workphonecountry,
                data_payload:Subtype::NUMBER AS subtype,
                data_payload:PreferredSettlementCurrency::NUMBER AS preferredsettlementcurrency,
                CAST(data_payload:FormerName::TEXT AS VARCHAR(250)) AS formername,
                CAST(data_payload:WorkPhone::TEXT AS VARCHAR(30)) AS workphone,
                data_payload:NotificationStatus_icare::BOOLEAN AS notificationstatus_icare,
                data_payload:TrustABNIsActive_icare::BOOLEAN AS trustabnisactive_icare,
                data_payload:OrganisationType_icare::NUMBER AS organisationtype_icare,
                CAST(data_payload:TradingName_icare::TEXT AS VARCHAR(100)) AS tradingname_icare,
                data_payload:TrustRegisteredForGST_icare::BOOLEAN AS trustregisteredforgst_icare,
                CAST(data_payload:TrustABN_icare::TEXT AS VARCHAR(60)) AS trustabn_icare,
                data_payload:ABNIsActive_icare::BOOLEAN AS abnisactive_icare,
                TO_TIMESTAMP_TZ(data_payload:ABNValidated_icare::NUMBER/1000) AS abnvalidated_icare,
                CAST(data_payload:SourceSystem_icare::TEXT AS VARCHAR(20)) AS sourcesystem_icare,
                CAST(data_payload:ACN_icare::TEXT AS VARCHAR(60)) AS acn_icare,
                TO_TIMESTAMP_TZ(data_payload:CommencementDate_icare::NUMBER/1000) AS commencementdate_icare,
                CAST(data_payload:TrustName_icare::TEXT AS VARCHAR(255)) AS trustname_icare,
                CAST(data_payload:ABN_icare::TEXT AS VARCHAR(60)) AS abn_icare,
                data_payload:TrusteeType_icare::NUMBER AS trusteetype_icare,
                CAST(data_payload:CRMVersion_icare::TEXT AS VARCHAR(18)) AS crmversion_icare,
                TO_TIMESTAMP_TZ(data_payload:TrustABNValidated_icare::NUMBER/1000) AS trustabnvalidated_icare,
                data_payload:RegisteredForGST_icare::BOOLEAN AS registeredforgst_icare,
                data_payload:WageRSA_icare::NUMBER AS wagersa_icare,
                data_payload:ArchiveState::NUMBER AS archivestate,
                data_payload:ArchiveSchemaInfo::NUMBER AS archiveschemainfo,
                data_payload:ArchiveFailureDetailsID::NUMBER AS archivefailuredetailsid,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                TO_TIMESTAMP_TZ(data_payload:ArchiveDate::NUMBER/1000) AS archivedate,
                data_payload:ObfuscatedInternal::BOOLEAN AS obfuscatedinternal,
                data_payload:DoNotDestroy::BOOLEAN AS donotdestroy,
                CAST(data_payload:ExcludeReason::TEXT AS VARCHAR(255)) AS excludereason,
                data_payload:ArchiveFailureID::NUMBER AS archivefailureid,
                data_payload:ExcludedFromArchive::BOOLEAN AS excludedfromarchive,
                CAST(data_payload:DuplicateCreateReason_Ext::TEXT AS VARCHAR(255)) AS duplicatecreatereason_ext,
                CAST(data_payload:CreationSource_Ext::TEXT AS VARCHAR(20)) AS creationsource_ext,
                CAST(data_payload:Status_Ext::TEXT AS VARCHAR(30)) AS status_ext,
                data_payload:CanBeSentToCRM_Ext::BOOLEAN AS canbesenttocrm_ext,
                data_payload:Scheme_Ext::NUMBER AS scheme_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS VARCHAR(300)) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'AVRO' as file_type,
                'GWPC' as source_system
            FROM {{ source('gwpc', 'pc_contact') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:preferred::BOOLEAN AS preferred,
                $1:vendortype::NUMBER AS vendortype,
                $1:faxphonecountry::NUMBER AS faxphonecountry,
                CAST($1:particle::TEXT AS VARCHAR(250)) AS particle,
                CAST($1:taxid::TEXT AS VARCHAR(30)) AS taxid,
                CAST($1:namedenorm::TEXT AS VARCHAR(255)) AS namedenorm,
                $1:mobilephonecountry::NUMBER AS mobilephonecountry,
                CAST($1:name::TEXT AS VARCHAR(255)) AS name,
                CAST($1:vendornumber::TEXT AS VARCHAR(60)) AS vendornumber,
                $1:state::NUMBER AS state,
                $1:prefix::NUMBER AS prefix,
                $1:score::NUMBER AS score,
                $1:preferredcurrency::NUMBER AS preferredcurrency,
                CAST($1:lastnamekanji::TEXT AS VARCHAR(250)) AS lastnamekanji,
                $1:taxfilingstatus::NUMBER AS taxfilingstatus,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:accountholdercount::NUMBER AS accountholdercount,
                $1:country::NUMBER AS country,
                CAST($1:adjudicatorlicense::TEXT AS VARCHAR(30)) AS adjudicatorlicense,
                $1:id::NUMBER AS id,
                CAST($1:withholdingrate AS NUMBER(4,1)) AS withholdingrate,
                CAST($1:lastnamedenorm::TEXT AS VARCHAR(250)) AS lastnamedenorm,
                CAST($1:middlename::TEXT AS VARCHAR(250)) AS middlename,
                CAST($1:lastname::TEXT AS VARCHAR(250)) AS lastname,
                $1:createuserid::NUMBER AS createuserid,
                CAST($1:externalid::TEXT AS VARCHAR(255)) AS externalid,
                CAST($1:mobilenumber_icare::TEXT AS VARCHAR(30)) AS mobilenumber_icare,
                $1:beanversion::NUMBER AS beanversion,
                $1:venuetype::NUMBER AS venuetype,
                $1:retired::NUMBER AS retired,
                $1:validationlevel::NUMBER AS validationlevel,
                $1:primaryphone::NUMBER AS primaryphone,
                $1:lastupdatetime::TIMESTAMP_TZ AS lastupdatetime,
                $1:externalversion::NUMBER AS externalversion,
                $1:updateuserid::NUMBER AS updateuserid,
                CAST($1:homephoneextension::TEXT AS VARCHAR(60)) AS homephoneextension,
                CAST($1:contactperson_icare::TEXT AS VARCHAR(60)) AS contactperson_icare,
                CAST($1:mobilephoneextension::TEXT AS VARCHAR(60)) AS mobilephoneextension,
                CAST($1:firstnamedenorm::TEXT AS VARCHAR(250)) AS firstnamedenorm,
                CAST($1:firstname::TEXT AS VARCHAR(250)) AS firstname,
                CAST($1:firstnamekanji::TEXT AS VARCHAR(250)) AS firstnamekanji,
                $1:temporarylastupdatetime::TIMESTAMP_TZ AS temporarylastupdatetime,
                $1:gender::NUMBER AS gender,
                CAST($1:notes::TEXT AS VARCHAR(16777216)) AS notes,
                $1:numdependentsu18::NUMBER AS numdependentsu18,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:homephonecountry::NUMBER AS homephonecountry,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                CAST($1:licensenumber::TEXT AS VARCHAR(20)) AS licensenumber,
                $1:cellphonecountry::NUMBER AS cellphonecountry,
                $1:autosync::NUMBER AS autosync,
                CAST($1:occupation::TEXT AS VARCHAR(80)) AS occupation,
                CAST($1:cellphone::TEXT AS VARCHAR(30)) AS cellphone,
                $1:primaryaddressid::NUMBER AS primaryaddressid,
                $1:suffix::NUMBER AS suffix,
                CAST($1:addressbookuid::TEXT AS VARCHAR(64)) AS addressbookuid,
                CAST($1:website_icare::TEXT AS VARCHAR(255)) AS website_icare,
                $1:loadrelatedcontacts::BOOLEAN AS loadrelatedcontacts,
                CAST($1:emailaddress1::TEXT AS VARCHAR(60)) AS emailaddress1,
                $1:numdependents::NUMBER AS numdependents,
                $1:dateofbirth::TIMESTAMP_TZ AS dateofbirth,
                $1:primarylanguage::NUMBER AS primarylanguage,
                CAST($1:emailaddress2::TEXT AS VARCHAR(60)) AS emailaddress2,
                $1:primarylocale::NUMBER AS primarylocale,
                $1:taxstatus::NUMBER AS taxstatus,
                $1:numdependentsu25::NUMBER AS numdependentsu25,
                CAST($1:workphoneextension::TEXT AS VARCHAR(60)) AS workphoneextension,
                $1:maritalstatus::NUMBER AS maritalstatus,
                CAST($1:citydenorm::TEXT AS VARCHAR(60)) AS citydenorm,
                CAST($1:namekanji::TEXT AS VARCHAR(255)) AS namekanji,
                CAST($1:faxphoneextension::TEXT AS VARCHAR(60)) AS faxphoneextension,
                CAST($1:homephone::TEXT AS VARCHAR(30)) AS homephone,
                $1:licensestate::NUMBER AS licensestate,
                CAST($1:faxphone::TEXT AS VARCHAR(30)) AS faxphone,
                CAST($1:cellphoneextension::TEXT AS VARCHAR(60)) AS cellphoneextension,
                CAST($1:postalcodedenorm::TEXT AS VARCHAR(60)) AS postalcodedenorm,
                $1:comunicatnprfrnce_icare::NUMBER AS comunicatnprfrnce_icare,
                CAST($1:employeenumber::TEXT AS VARCHAR(255)) AS employeenumber,
                $1:workphonecountry::NUMBER AS workphonecountry,
                $1:subtype::NUMBER AS subtype,
                $1:preferredsettlementcurrency::NUMBER AS preferredsettlementcurrency,
                CAST($1:formername::TEXT AS VARCHAR(250)) AS formername,
                CAST($1:workphone::TEXT AS VARCHAR(30)) AS workphone,
                $1:notificationstatus_icare::BOOLEAN AS notificationstatus_icare,
                $1:trustabnisactive_icare::BOOLEAN AS trustabnisactive_icare,
                $1:organisationtype_icare::NUMBER AS organisationtype_icare,
                CAST($1:tradingname_icare::TEXT AS VARCHAR(100)) AS tradingname_icare,
                $1:trustregisteredforgst_icare::BOOLEAN AS trustregisteredforgst_icare,
                CAST($1:trustabn_icare::TEXT AS VARCHAR(60)) AS trustabn_icare,
                $1:abnisactive_icare::BOOLEAN AS abnisactive_icare,
                $1:abnvalidated_icare::TIMESTAMP_TZ AS abnvalidated_icare,
                CAST($1:sourcesystem_icare::TEXT AS VARCHAR(20)) AS sourcesystem_icare,
                CAST($1:acn_icare::TEXT AS VARCHAR(60)) AS acn_icare,
                $1:commencementdate_icare::TIMESTAMP_TZ AS commencementdate_icare,
                CAST($1:trustname_icare::TEXT AS VARCHAR(255)) AS trustname_icare,
                CAST($1:abn_icare::TEXT AS VARCHAR(60)) AS abn_icare,
                $1:trusteetype_icare::NUMBER AS trusteetype_icare,
                CAST($1:crmversion_icare::TEXT AS VARCHAR(18)) AS crmversion_icare,
                $1:trustabnvalidated_icare::TIMESTAMP_TZ AS trustabnvalidated_icare,
                $1:registeredforgst_icare::BOOLEAN AS registeredforgst_icare,
                $1:wagersa_icare::NUMBER AS wagersa_icare,
                $1:archivestate::NUMBER AS archivestate,
                $1:archiveschemainfo::NUMBER AS archiveschemainfo,
                $1:archivefailuredetailsid::NUMBER AS archivefailuredetailsid,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:archivedate::TIMESTAMP_TZ AS archivedate,
                $1:obfuscatedinternal::BOOLEAN AS obfuscatedinternal,
                $1:donotdestroy::BOOLEAN AS donotdestroy,
                CAST($1:excludereason::TEXT AS VARCHAR(255)) AS excludereason,
                $1:archivefailureid::NUMBER AS archivefailureid,
                $1:excludedfromarchive::BOOLEAN AS excludedfromarchive,
                CAST($1:duplicatecreatereason_ext::TEXT AS VARCHAR(255)) AS duplicatecreatereason_ext,
                CAST($1:creationsource_ext::TEXT AS VARCHAR(20)) AS creationsource_ext,
                CAST($1:status_ext::TEXT AS VARCHAR(30)) AS status_ext,
                $1:canbesenttocrm_ext::BOOLEAN AS canbesenttocrm_ext,
                $1:scheme_ext::NUMBER AS scheme_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::VARCHAR(300) as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'PARQUET' as file_type,
                'GWPC' as source_system
            FROM {{ source('gwpc', 'pc_contact') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS contact_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'preferred',
                        'vendortype',
                        'faxphonecountry',
                        'particle',
                        'taxid',
                        'namedenorm',
                        'mobilephonecountry',
                        'name',
                        'vendornumber',
                        'state',
                        'prefix',
                        'score',
                        'preferredcurrency',
                        'lastnamekanji',
                        'taxfilingstatus',
                        'updatetime',
                        'accountholdercount',
                        'country',
                        'adjudicatorlicense',
                        'withholdingrate',
                        'lastnamedenorm',
                        'middlename',
                        'lastname',
                        'createuserid',
                        'externalid',
                        'mobilenumber_icare',
                        'beanversion',
                        'venuetype',
                        'retired',
                        'validationlevel',
                        'primaryphone',
                        'lastupdatetime',
                        'externalversion',
                        'updateuserid',
                        'homephoneextension',
                        'contactperson_icare',
                        'mobilephoneextension',
                        'firstnamedenorm',
                        'firstname',
                        'firstnamekanji',
                        'temporarylastupdatetime',
                        'gender',
                        'notes',
                        'numdependentsu18',
                        'publicid',
                        'homephonecountry',
                        'createtime',
                        'licensenumber',
                        'cellphonecountry',
                        'autosync',
                        'occupation',
                        'cellphone',
                        'primaryaddressid',
                        'suffix',
                        'addressbookuid',
                        'website_icare',
                        'loadrelatedcontacts',
                        'emailaddress1',
                        'numdependents',
                        'dateofbirth',
                        'primarylanguage',
                        'emailaddress2',
                        'primarylocale',
                        'taxstatus',
                        'numdependentsu25',
                        'workphoneextension',
                        'maritalstatus',
                        'citydenorm',
                        'namekanji',
                        'faxphoneextension',
                        'homephone',
                        'licensestate',
                        'faxphone',
                        'cellphoneextension',
                        'postalcodedenorm',
                        'comunicatnprfrnce_icare',
                        'employeenumber',
                        'workphonecountry',
                        'subtype',
                        'preferredsettlementcurrency',
                        'formername',
                        'workphone',
                        'notificationstatus_icare',
                        'trustabnisactive_icare',
                        'organisationtype_icare',
                        'tradingname_icare',
                        'trustregisteredforgst_icare',
                        'trustabn_icare',
                        'abnisactive_icare',
                        'abnvalidated_icare',
                        'sourcesystem_icare',
                        'acn_icare',
                        'commencementdate_icare',
                        'trustname_icare',
                        'abn_icare',
                        'trusteetype_icare',
                        'crmversion_icare',
                        'trustabnvalidated_icare',
                        'registeredforgst_icare',
                        'wagersa_icare',
                        'archivestate',
                        'archiveschemainfo',
                        'archivefailuredetailsid',
                        'archivepartition',
                        'archivedate',
                        'obfuscatedinternal',
                        'donotdestroy',
                        'excludereason',
                        'archivefailureid',
                        'excludedfromarchive',
                        'duplicatecreatereason_ext',
                        'creationsource_ext',
                        'status_ext',
                        'canbesenttocrm_ext',
                        'scheme_ext'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
    WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}
    ORDER BY record_insertion_date
