{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for pc_account.
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                record_insertion_date: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDA goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    incremental_strategy='append',
    on_schema_change='append_new_columns',
    tags=["landing", "gwpc", "policy_centre", "business_critical"]
) }}


WITH cte_source_data AS 
(

            SELECT
                CAST(data_payload:TrustABNStatus_icare::TEXT AS VARCHAR(255)) AS trustabnstatus_icare,
                data_payload:GroupNumber_icare::NUMBER AS groupnumber_icare,
                CAST(data_payload:BusOpsDesc::TEXT AS VARCHAR(240)) AS busopsdesc,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                CAST(data_payload:GroupName_icare::TEXT AS VARCHAR(255)) AS groupname_icare,
                CAST(data_payload:ACN_icare::TEXT AS VARCHAR(60)) AS acn_icare,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                data_payload:NewAccountReason_icare::NUMBER AS newaccountreason_icare,
                data_payload:LinkContacts::BOOLEAN AS linkcontacts,
                CAST(data_payload:ITCEntitlement_icare::TEXT AS VARCHAR(60)) AS itcentitlement_icare,
                CAST(data_payload:TrustABN_icare::TEXT AS VARCHAR(60)) AS trustabn_icare,
                data_payload:AccountOrgType::NUMBER AS accountorgtype,
                data_payload:LocationAutoNumberSeq::NUMBER AS locationautonumberseq,
                data_payload:isParent::BOOLEAN AS isparent,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:ABRValidationStatus_icare::BOOLEAN AS abrvalidationstatus_icare,
                data_payload:ServiceTier::NUMBER AS servicetier,
                CAST(data_payload:ABNStatus_icare::TEXT AS VARCHAR(255)) AS abnstatus_icare,
                data_payload:PrimaryLanguage::NUMBER AS primarylanguage,
                data_payload:ID::NUMBER AS id,
                CAST(data_payload:StateBureauNum::TEXT AS VARCHAR(255)) AS statebureaunum,
                data_payload:PrimaryLocale::NUMBER AS primarylocale,
                TO_TIMESTAMP_TZ(data_payload:GroupCommencementDate_icare::NUMBER/1000) AS groupcommencementdate_icare,
                TO_TIMESTAMP_TZ(data_payload:CommencementDate_icare::NUMBER/1000) AS commencementdate_icare,
                CAST(data_payload:TrustName_icare::TEXT AS VARCHAR(255)) AS trustname_icare,
                data_payload:AccountStatus::NUMBER AS accountstatus,
                data_payload:Frozen::BOOLEAN AS frozen,
                data_payload:CreateUserID::NUMBER AS createuserid,
                data_payload:YearBusinessStarted::NUMBER AS yearbusinessstarted,
                data_payload:IndustryCodeID::NUMBER AS industrycodeid,
                data_payload:BeanVersion::NUMBER AS beanversion,
                CAST(data_payload:ABN_icare::TEXT AS VARCHAR(60)) AS abn_icare,
                data_payload:Retired::NUMBER AS retired,
                data_payload:TrusteeType_icare::NUMBER AS trusteetype_icare,
                data_payload:LockingColumn::NUMBER AS lockingcolumn,
                CAST(data_payload:OtherOrgTypeDescription::TEXT AS VARCHAR(40)) AS otherorgtypedescription,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                CAST(data_payload:AccountNumberDenorm::TEXT AS VARCHAR(255)) AS accountnumberdenorm,
                CAST(data_payload:Cluster_icare::TEXT AS VARCHAR(100)) AS cluster_icare,
                CAST(data_payload:AccountNumber::TEXT AS VARCHAR(255)) AS accountnumber,
                data_payload:isVedaValidated::BOOLEAN AS isvedavalidated,
                CAST(data_payload:ACNStatus_icare::TEXT AS VARCHAR(255)) AS acnstatus_icare,
                data_payload:PreferredCoverageCurrency::NUMBER AS preferredcoveragecurrency,
                data_payload:PreferredSettlementCurrency::NUMBER AS preferredsettlementcurrency,
                data_payload:GSTRegistration_icare::BOOLEAN AS gstregistration_icare,
                TO_TIMESTAMP_TZ(data_payload:OriginationDate::NUMBER/1000) AS originationdate,
                CAST(data_payload:TrusteeName_icare::TEXT AS VARCHAR(256)) AS trusteename_icare,
                data_payload:Anonymous::BOOLEAN AS anonymous,
                CAST(data_payload:GroupNumberDenorm_icare::TEXT AS VARCHAR(60)) AS groupnumberdenorm_icare,
                CAST(data_payload:ACNDenorm_icare::TEXT AS VARCHAR(60)) AS acndenorm_icare,
                CAST(data_payload:ABNDenorm_icare::TEXT AS VARCHAR(60)) AS abndenorm_icare,
                CAST(data_payload:CRMUniqueID_icare::TEXT AS VARCHAR(255)) AS crmuniqueid_icare,
                CAST(data_payload:SourceSystem_icare::TEXT AS VARCHAR(20)) AS sourcesystem_icare,
                data_payload:CRMVersion_icare::NUMBER AS crmversion_icare,
                TO_TIMESTAMP_TZ(data_payload:AccountStatusUpdateTime::NUMBER/1000) AS accountstatusupdatetime,
                data_payload:ArchiveState::NUMBER AS archivestate,
                data_payload:ArchiveSchemaInfo::NUMBER AS archiveschemainfo,
                data_payload:DoNotDestroy::BOOLEAN AS donotdestroy,
                CAST(data_payload:ExcludeReason::TEXT AS VARCHAR(255)) AS excludereason,
                data_payload:ArchiveFailureID::NUMBER AS archivefailureid,
                data_payload:ExcludedFromArchive::BOOLEAN AS excludedfromarchive,
                data_payload:ArchiveFailureDetailsID::NUMBER AS archivefailuredetailsid,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                TO_TIMESTAMP_TZ(data_payload:ArchiveDate::NUMBER/1000) AS archivedate,
                data_payload:Insolvency_Ext::BOOLEAN AS insolvency_ext,
                data_payload:ReferredToRNSW_Ext::BOOLEAN AS referredtornsw_ext,
                CAST(data_payload:CustomerRefCode_Ext::TEXT AS VARCHAR(8)) AS customerrefcode_ext,
                CAST(data_payload:GSTStatus_Ext::TEXT AS VARCHAR(255)) AS gststatus_ext,
                TO_TIMESTAMP_TZ(data_payload:GSTStatusFromDate_Ext::NUMBER/1000) AS gststatusfromdate_ext,
                data_payload:HasUserExercisedChoice_Ext::BOOLEAN AS hasuserexercisedchoice_ext,
                CAST(data_payload:PolicySpecialistCSPName_Ext::TEXT AS VARCHAR(85)) AS policyspecialistcspname_ext,
                data_payload:ExerciseCSPChoice_Ext::BOOLEAN AS exercisecspchoice_ext,
                CAST(data_payload:PolicyGeneralCSPName_Ext::TEXT AS VARCHAR(85)) AS policygeneralcspname_ext,
                data_payload:EligibilityToSelectCSP_Ext::BOOLEAN AS eligibilitytoselectcsp_ext,
                data_payload:IsEligibleForCSPConfirmDoc_Ext::BOOLEAN AS iseligibleforcspconfirmdoc_ext,
                data_payload:IsPolicyInSyncWithGroup_Ext::BOOLEAN AS ispolicyinsyncwithgroup_ext,
                CAST(data_payload:CreationSource_Ext::TEXT AS VARCHAR(20)) AS creationsource_ext,
                TO_TIMESTAMP_TZ(data_payload:Activefrom_Ext::NUMBER/1000) AS activefrom_ext,
                data_payload:PortfolioCode_Ext::NUMBER AS portfoliocode_ext,
                data_payload:AgencyType_Ext::NUMBER AS agencytype_ext,
                data_payload:TMFCostCentreRequiredFlag_Ext::BOOLEAN AS tmfcostcentrerequiredflag_ext,
                CAST(data_payload:AgencyCode_Ext::TEXT AS VARCHAR(60)) AS agencycode_ext,
                TO_TIMESTAMP_TZ(data_payload:ActiveTo_Ext::NUMBER/1000) AS activeto_ext,
                data_payload:IsHealthPortfolio_Ext::BOOLEAN AS ishealthportfolio_ext,
                data_payload:TMFCostCentreLevelInd_Ext::NUMBER AS tmfcostcentrelevelind_ext,
                CAST(data_payload:ICP_Ext::TEXT AS VARCHAR(15)) AS icp_ext,
                data_payload:Pool_Ext::NUMBER AS pool_ext,
                data_payload:IsGroupTermRenamed_Ext::BOOLEAN AS isgrouptermrenamed_ext,
                data_payload:IsMigrated_Ext::BOOLEAN AS ismigrated_ext,
                CAST(data_payload:SAPCustomerNumber_Ext::TEXT AS VARCHAR(60)) AS sapcustomernumber_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS VARCHAR(300)) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'AVRO' as file_type,
                'GWPC' as source_system
            FROM {{ source('gwpc', 'pc_account') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                CAST($1:trustabnstatus_icare::TEXT AS VARCHAR(255)) AS trustabnstatus_icare,
                $1:groupnumber_icare::NUMBER AS groupnumber_icare,
                CAST($1:busopsdesc::TEXT AS VARCHAR(240)) AS busopsdesc,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                CAST($1:groupname_icare::TEXT AS VARCHAR(255)) AS groupname_icare,
                CAST($1:acn_icare::TEXT AS VARCHAR(60)) AS acn_icare,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:newaccountreason_icare::NUMBER AS newaccountreason_icare,
                $1:linkcontacts::BOOLEAN AS linkcontacts,
                CAST($1:itcentitlement_icare::TEXT AS VARCHAR(60)) AS itcentitlement_icare,
                CAST($1:trustabn_icare::TEXT AS VARCHAR(60)) AS trustabn_icare,
                $1:accountorgtype::NUMBER AS accountorgtype,
                $1:locationautonumberseq::NUMBER AS locationautonumberseq,
                $1:isparent::BOOLEAN AS isparent,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:abrvalidationstatus_icare::BOOLEAN AS abrvalidationstatus_icare,
                $1:servicetier::NUMBER AS servicetier,
                CAST($1:abnstatus_icare::TEXT AS VARCHAR(255)) AS abnstatus_icare,
                $1:primarylanguage::NUMBER AS primarylanguage,
                $1:id::NUMBER AS id,
                CAST($1:statebureaunum::TEXT AS VARCHAR(255)) AS statebureaunum,
                $1:primarylocale::NUMBER AS primarylocale,
                $1:groupcommencementdate_icare::TIMESTAMP_TZ AS groupcommencementdate_icare,
                $1:commencementdate_icare::TIMESTAMP_TZ AS commencementdate_icare,
                CAST($1:trustname_icare::TEXT AS VARCHAR(255)) AS trustname_icare,
                $1:accountstatus::NUMBER AS accountstatus,
                $1:frozen::BOOLEAN AS frozen,
                $1:createuserid::NUMBER AS createuserid,
                $1:yearbusinessstarted::NUMBER AS yearbusinessstarted,
                $1:industrycodeid::NUMBER AS industrycodeid,
                $1:beanversion::NUMBER AS beanversion,
                CAST($1:abn_icare::TEXT AS VARCHAR(60)) AS abn_icare,
                $1:retired::NUMBER AS retired,
                $1:trusteetype_icare::NUMBER AS trusteetype_icare,
                $1:lockingcolumn::NUMBER AS lockingcolumn,
                CAST($1:otherorgtypedescription::TEXT AS VARCHAR(40)) AS otherorgtypedescription,
                $1:updateuserid::NUMBER AS updateuserid,
                CAST($1:accountnumberdenorm::TEXT AS VARCHAR(255)) AS accountnumberdenorm,
                CAST($1:cluster_icare::TEXT AS VARCHAR(100)) AS cluster_icare,
                CAST($1:accountnumber::TEXT AS VARCHAR(255)) AS accountnumber,
                $1:isvedavalidated::BOOLEAN AS isvedavalidated,
                CAST($1:acnstatus_icare::TEXT AS VARCHAR(255)) AS acnstatus_icare,
                $1:preferredcoveragecurrency::NUMBER AS preferredcoveragecurrency,
                $1:preferredsettlementcurrency::NUMBER AS preferredsettlementcurrency,
                $1:gstregistration_icare::BOOLEAN AS gstregistration_icare,
                $1:originationdate::TIMESTAMP_TZ AS originationdate,
                CAST($1:trusteename_icare::TEXT AS VARCHAR(256)) AS trusteename_icare,
                $1:anonymous::BOOLEAN AS anonymous,
                CAST($1:groupnumberdenorm_icare::TEXT AS VARCHAR(60)) AS groupnumberdenorm_icare,
                CAST($1:acndenorm_icare::TEXT AS VARCHAR(60)) AS acndenorm_icare,
                CAST($1:abndenorm_icare::TEXT AS VARCHAR(60)) AS abndenorm_icare,
                CAST($1:crmuniqueid_icare::TEXT AS VARCHAR(255)) AS crmuniqueid_icare,
                CAST($1:sourcesystem_icare::TEXT AS VARCHAR(20)) AS sourcesystem_icare,
                $1:crmversion_icare::NUMBER AS crmversion_icare,
                $1:accountstatusupdatetime::TIMESTAMP_TZ AS accountstatusupdatetime,
                $1:archivestate::NUMBER AS archivestate,
                $1:archiveschemainfo::NUMBER AS archiveschemainfo,
                $1:donotdestroy::BOOLEAN AS donotdestroy,
                CAST($1:excludereason::TEXT AS VARCHAR(255)) AS excludereason,
                $1:archivefailureid::NUMBER AS archivefailureid,
                $1:excludedfromarchive::BOOLEAN AS excludedfromarchive,
                $1:archivefailuredetailsid::NUMBER AS archivefailuredetailsid,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:archivedate::TIMESTAMP_TZ AS archivedate,
                $1:insolvency_ext::BOOLEAN AS insolvency_ext,
                $1:referredtornsw_ext::BOOLEAN AS referredtornsw_ext,
                CAST($1:customerrefcode_ext::TEXT AS VARCHAR(8)) AS customerrefcode_ext,
                CAST($1:gststatus_ext::TEXT AS VARCHAR(255)) AS gststatus_ext,
                $1:gststatusfromdate_ext::TIMESTAMP_TZ AS gststatusfromdate_ext,
                $1:hasuserexercisedchoice_ext::BOOLEAN AS hasuserexercisedchoice_ext,
                CAST($1:policyspecialistcspname_ext::TEXT AS VARCHAR(85)) AS policyspecialistcspname_ext,
                $1:exercisecspchoice_ext::BOOLEAN AS exercisecspchoice_ext,
                CAST($1:policygeneralcspname_ext::TEXT AS VARCHAR(85)) AS policygeneralcspname_ext,
                $1:eligibilitytoselectcsp_ext::BOOLEAN AS eligibilitytoselectcsp_ext,
                $1:iseligibleforcspconfirmdoc_ext::BOOLEAN AS iseligibleforcspconfirmdoc_ext,
                $1:ispolicyinsyncwithgroup_ext::BOOLEAN AS ispolicyinsyncwithgroup_ext,
                CAST($1:creationsource_ext::TEXT AS VARCHAR(20)) AS creationsource_ext,
                $1:activefrom_ext::TIMESTAMP_TZ AS activefrom_ext,
                $1:portfoliocode_ext::NUMBER AS portfoliocode_ext,
                $1:agencytype_ext::NUMBER AS agencytype_ext,
                $1:tmfcostcentrerequiredflag_ext::BOOLEAN AS tmfcostcentrerequiredflag_ext,
                CAST($1:agencycode_ext::TEXT AS VARCHAR(60)) AS agencycode_ext,
                $1:activeto_ext::TIMESTAMP_TZ AS activeto_ext,
                $1:ishealthportfolio_ext::BOOLEAN AS ishealthportfolio_ext,
                $1:tmfcostcentrelevelind_ext::NUMBER AS tmfcostcentrelevelind_ext,
                CAST($1:icp_ext::TEXT AS VARCHAR(15)) AS icp_ext,
                $1:pool_ext::NUMBER AS pool_ext,
                $1:isgrouptermrenamed_ext::BOOLEAN AS isgrouptermrenamed_ext,
                $1:ismigrated_ext::BOOLEAN AS ismigrated_ext,
                CAST($1:sapcustomernumber_ext::TEXT AS VARCHAR(60)) AS sapcustomernumber_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::VARCHAR(300) as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'PARQUET' as file_type,
                'GWPC' as source_system
            FROM {{ source('gwpc', 'pc_account') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS account_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'trustabnstatus_icare',
                        'groupnumber_icare',
                        'busopsdesc',
                        'publicid',
                        'groupname_icare',
                        'acn_icare',
                        'createtime',
                        'newaccountreason_icare',
                        'linkcontacts',
                        'itcentitlement_icare',
                        'trustabn_icare',
                        'accountorgtype',
                        'locationautonumberseq',
                        'isparent',
                        'updatetime',
                        'abrvalidationstatus_icare',
                        'servicetier',
                        'abnstatus_icare',
                        'primarylanguage',
                        'statebureaunum',
                        'primarylocale',
                        'groupcommencementdate_icare',
                        'commencementdate_icare',
                        'trustname_icare',
                        'accountstatus',
                        'frozen',
                        'createuserid',
                        'yearbusinessstarted',
                        'industrycodeid',
                        'beanversion',
                        'abn_icare',
                        'retired',
                        'trusteetype_icare',
                        'lockingcolumn',
                        'otherorgtypedescription',
                        'updateuserid',
                        'accountnumberdenorm',
                        'cluster_icare',
                        'accountnumber',
                        'isvedavalidated',
                        'acnstatus_icare',
                        'preferredcoveragecurrency',
                        'preferredsettlementcurrency',
                        'gstregistration_icare',
                        'originationdate',
                        'trusteename_icare',
                        'anonymous',
                        'groupnumberdenorm_icare',
                        'acndenorm_icare',
                        'abndenorm_icare',
                        'crmuniqueid_icare',
                        'sourcesystem_icare',
                        'crmversion_icare',
                        'accountstatusupdatetime',
                        'archivestate',
                        'archiveschemainfo',
                        'donotdestroy',
                        'excludereason',
                        'archivefailureid',
                        'excludedfromarchive',
                        'archivefailuredetailsid',
                        'archivepartition',
                        'archivedate',
                        'insolvency_ext',
                        'referredtornsw_ext',
                        'customerrefcode_ext',
                        'gststatus_ext',
                        'gststatusfromdate_ext',
                        'hasuserexercisedchoice_ext',
                        'policyspecialistcspname_ext',
                        'exercisecspchoice_ext',
                        'policygeneralcspname_ext',
                        'eligibilitytoselectcsp_ext',
                        'iseligibleforcspconfirmdoc_ext',
                        'ispolicyinsyncwithgroup_ext',
                        'creationsource_ext',
                        'activefrom_ext',
                        'portfoliocode_ext',
                        'agencytype_ext',
                        'tmfcostcentrerequiredflag_ext',
                        'agencycode_ext',
                        'activeto_ext',
                        'ishealthportfolio_ext',
                        'tmfcostcentrelevelind_ext',
                        'icp_ext',
                        'pool_ext',
                        'isgrouptermrenamed_ext',
                        'ismigrated_ext',
                        'sapcustomernumber_ext'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
    WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}
    ORDER BY record_insertion_date
