{% snapshot mi_gbs_claim_snapshot %}

{{ config(
    target_schema='ifnsw_claim_interface',
    unique_key='mi_gbs_claim_sk',
    strategy='check',
    check_cols=['claims_manager', 'agency', 'line_of_business', 'extract_date', 'record_number', 'policy_number', 'claim_number', 'claim_lodged', 'claim_status', 'claim_type', 'clmnt_surname', 'clmnt_first_name', 'claims_officer', 'cost_centre', 'date_reported', 'date_entered', 'date_finalised', 'date_occurred', 'date_received', 'incident_number', 'litigation_claim_status', 'time_occurred', 'recovery_claim_status', 'incident_narrative', 'salvage_action', 'event_code', 'accident_cause', 'result_code', 'claimant_gender', 'accident_location_postcode', 'country_code', 'assessor', 'incident_code', 'previous_policy_number', 'claimants_date_of_birth', 'bodily_location_code', 'nature_of_injury_code', 'area_health_service', 'claim_sensitivity_code', 'claim_sensitivity_desc'],
    tags=['snapshot_tmf','snapshot_curated','snapshot','mi_gbs_claim']
) }}

WITH source_data AS (
    SELECT
        {{ dbt_utils.generate_surrogate_key([
            'claims_manager',
            'agency',
            'line_of_business',
            'extract_date',
            'record_number',
            'policy_number',
            'claim_number',
            'claim_lodged',
            'claim_status',
            'claim_type',
            'clmnt_surname',
            'clmnt_first_name',
            'claims_officer',
            'cost_centre',
            'date_reported',
            'date_entered',
            'date_finalised',
            'date_occurred',
            'date_received',
            'incident_number',
            'litigation_claim_status',
            'time_occurred',
            'recovery_claim_status',
            'incident_narrative',
            'salvage_action',
            'event_code',
            'accident_cause',
            'result_code',
            'claimant_gender',
            'accident_location_postcode',
            'country_code',
            'assessor',
            'incident_code',
            'previous_policy_number',
            'claimants_date_of_birth',
            'bodily_location_code',
            'nature_of_injury_code',
            'area_health_service',
            'claim_sensitivity_code',
            'claim_sensitivity_desc'
    ]) }} AS mi_gbs_claim_sk,
        CURRENT_TIMESTAMP() AS dbt_updated_at,
        claims_manager,
        agency,
        line_of_business,
        extract_date,
        record_number,
        policy_number,
        claim_number,
        claim_lodged,
        claim_status,
        claim_type,
        clmnt_surname,
        clmnt_first_name,
        claims_officer,
        cost_centre,
        date_reported,
        date_entered,
        date_finalised,
        date_occurred,
        date_received,
        incident_number,
        litigation_claim_status,
        time_occurred,
        recovery_claim_status,
        incident_narrative,
        salvage_action,
        event_code,
        accident_cause,
        result_code,
        claimant_gender,
        accident_location_postcode,
        country_code,
        assessor,
        incident_code,
        previous_policy_number,
        claimants_date_of_birth,
        bodily_location_code,
        nature_of_injury_code,
        area_health_service,
        claim_sensitivity_code,
        claim_sensitivity_desc,
        metadata_file_name,
        metadata_file_last_modified,
        metadata_scan_time,
        metadata_row_number,
        file_ingestion_timestamp
    FROM {{ source('ifnsw_claim_interface', 'mi_gbs_claim') }}
)

SELECT * FROM source_data

{% endsnapshot %}