{% snapshot ab_abcontact_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026-01-01      0.0                             SCD Type 2 snapshot for ab_abcontact.
                                                Source: ref('stg_raw_ab_abcontact')
                                                unique_key: abcontact_sk (surrogate on PK 'id')
                                                check_cols: ['hash_key'] (surrogate on all business cols excl PK)
                                                hard_deletes: new_record (inserts dbt_is_deleted=True row)
                                                No code change required when PARQUET CDC goes live.
-#}

{{ config(
    target_schema='gwab',
    unique_key='abcontact_sk',
    strategy='check',
    alias='ab_abcontact',
    check_cols=['hash_key'],
    hard_deletes='new_record',
    tags=['snapshot', 'contact_manager', 'non_business_critical', 'ab_abcontact']
) }}

SELECT
    abcontact_sk,
    hash_key,
    trustabnisactive_icare,
    singleremittanceperday_icare,
    preferredpaymentmethod_icare,
    faxphonecountry,
    taxid,
    namedenorm,
    medicarevaliduntil_icare,
    approvedpaymentmethod_icare,
    organisationtype_icare,
    archivestate,
    archiveschemainfo,
    updatetime,
    adjudicatorlicense,
    id,
    lawfirmspecialty,
    lastnamedenorm,
    oktaid_icare,
    lastname,
    createuserid,
    payinfoupdusername_icare,
    tradingname_icare,
    beanversion,
    venuetype,
    autotowinglicense,
    blockedvendor_icare,
    updateuserid,
    homephoneextension,
    medicarenumber_icare,
    trustregisteredforgst_icare,
    minimumcriteriaverified,
    firstname,
    trusteename_icare,
    w9validfrom,
    publicid,
    occupation,
    cellphone,
    primaryaddressid,
    trustabn_icare,
    suffix,
    interpreterrequired_icare,
    archivefailuredetailsid,
    website_icare,
    abnisactive_icare,
    emailaddress1,
    emailaddress2,
    numdependents,
    taxstatus,
    tfndeclarationdate_icare,
    archivepartition,
    updatescore,
    namekanji,
    abslanguagedescription_icare,
    archivedate,
    faxphone,
    abslanguagecode_icare,
    cellphoneextension,
    employeenumber,
    doctorspecialty_icare,
    subtype,
    abnvalidated_icare,
    formername,
    vendorservicesloadstatus,
    loadcommandid,
    preferred,
    vendortype,
    w9received,
    sourcesystem_icare,
    particle,
    acn_icare,
    name,
    statedenorm,
    medicallicense,
    vendornumber,
    prefix,
    preferredcurrency,
    score,
    donotdestroy,
    w9validto,
    linkid,
    lastnamekanji,
    taxfilingstatus,
    withholdingrate,
    commencementdate_icare,
    trustname_icare,
    excludereason,
    legalspecialty_icare,
    middlename,
    attorneylicense,
    vendoravailability,
    archivefailureid,
    abn_icare,
    retired,
    medicalorgspecialty,
    validationlevel,
    primaryphone,
    trusteetype_icare,
    w9receiveddate,
    medicareirn_icare,
    crmversion_icare,
    firstnamedenorm,
    adjudicativedomain,
    firstnamekanji,
    doctorspecialty,
    smsnotification_icare,
    notes,
    gender,
    numdependentsu18,
    autorepairlicense,
    crmsharedfieldshash_icare,
    homephonecountry,
    medicalspecialty_icare,
    spatialpointdenorm,
    createtime,
    cellphonecountry,
    licensenumber,
    keywordkanji,
    excludedfromarchive,
    countrydenorm,
    trustabnvalidated_icare,
    aggregateremittance_icare,
    dateofbirth,
    attorneyspecialty_icare,
    registeredforgst_icare,
    communicationpreferences_icare,
    numdependentsu25,
    attorneyspecialty,
    workphoneextension,
    maritalstatus,
    keyworddenorm,
    citydenorm,
    keyword,
    faxphoneextension,
    createstatus,
    homephone,
    licensestate,
    postalcodedenorm,
    workphonecountry,
    workphone,
    vendorunavailablemessage,
    coresharedfieldshash_icare,
    wagersa_icare,
    providerid_ext,
    bankapprovewithedit_ext,
    dpplatform_ext,
    contactsecuritytype_ext,
    cellphonecountry_ext,
    organisationpartyid_ext,
    crmlastmodifieddate_ext,
    crmlastmodifiedbyid_ext,
    status_ext,
    cellphoneextension_ext,
    crmcreateddate_ext,
    partyid_ext,
    abnvalidationtimestamp_ext,
    cellphone_ext,
    crmlastmodifiedbyname_ext,
    providercategory_ext,
    abnexempt_ext,
    creationsource_ext,
    'GWAB' AS source_system,
    gwcbi_connector_ts_ms,
    gwcbi_lsn,
    gwcbi_operation,
    gwcbi_payload_ts_ms,
    gwcbi_seqval,
    gwcbi_seqval_hex,
    gwcbi_tx_id,
    metadata_file_name,
    file_ingestion_timestamp
FROM {{ ref('stg_raw_ab_abcontact') }}

{% endsnapshot %}