{% snapshot pc_contact_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026-01-01      0.0                             SCD Type 2 snapshot for pc_contact.
                                                Source: ref('stg_raw_pc_contact')
                                                unique_key: contact_sk (surrogate on PK 'id')
                                                check_cols: ['hash_key'] (surrogate on all business cols excl PK)
                                                hard_deletes: new_record (inserts dbt_is_deleted=True row)
                                                No code change required when PARQUET CDC goes live.
-#}

{{ config(
    target_schema='gwpc',
    unique_key='contact_sk',
    strategy='check',
    alias='pc_contact',
    check_cols=['hash_key'],
    hard_deletes='new_record',
    tags=['snapshot', 'policy_centre', 'business_critical', 'pc_contact']
) }}

SELECT
    contact_sk,
    hash_key,
    loadcommandid,
    preferred,
    vendortype,
    faxphonecountry,
    particle,
    taxid,
    namedenorm,
    mobilephonecountry,
    name,
    vendornumber,
    state,
    prefix,
    score,
    preferredcurrency,
    lastnamekanji,
    taxfilingstatus,
    updatetime,
    accountholdercount,
    country,
    adjudicatorlicense,
    id,
    withholdingrate,
    lastnamedenorm,
    middlename,
    lastname,
    createuserid,
    externalid,
    mobilenumber_icare,
    beanversion,
    venuetype,
    retired,
    validationlevel,
    primaryphone,
    lastupdatetime,
    externalversion,
    updateuserid,
    homephoneextension,
    contactperson_icare,
    mobilephoneextension,
    firstnamedenorm,
    firstname,
    firstnamekanji,
    temporarylastupdatetime,
    gender,
    notes,
    numdependentsu18,
    publicid,
    homephonecountry,
    createtime,
    licensenumber,
    cellphonecountry,
    autosync,
    occupation,
    cellphone,
    primaryaddressid,
    suffix,
    addressbookuid,
    website_icare,
    loadrelatedcontacts,
    emailaddress1,
    numdependents,
    dateofbirth,
    primarylanguage,
    emailaddress2,
    primarylocale,
    taxstatus,
    numdependentsu25,
    workphoneextension,
    maritalstatus,
    citydenorm,
    namekanji,
    faxphoneextension,
    homephone,
    licensestate,
    faxphone,
    cellphoneextension,
    postalcodedenorm,
    comunicatnprfrnce_icare,
    employeenumber,
    workphonecountry,
    subtype,
    preferredsettlementcurrency,
    formername,
    workphone,
    notificationstatus_icare,
    trustabnisactive_icare,
    organisationtype_icare,
    tradingname_icare,
    trustregisteredforgst_icare,
    trustabn_icare,
    abnisactive_icare,
    abnvalidated_icare,
    sourcesystem_icare,
    acn_icare,
    commencementdate_icare,
    trustname_icare,
    abn_icare,
    trusteetype_icare,
    crmversion_icare,
    trustabnvalidated_icare,
    registeredforgst_icare,
    wagersa_icare,
    archivestate,
    archiveschemainfo,
    archivefailuredetailsid,
    archivepartition,
    archivedate,
    obfuscatedinternal,
    donotdestroy,
    excludereason,
    archivefailureid,
    excludedfromarchive,
    duplicatecreatereason_ext,
    creationsource_ext,
    status_ext,
    canbesenttocrm_ext,
    scheme_ext,
    'GWPC' AS source_system,
    gwcbi_connector_ts_ms,
    gwcbi_lsn,
    gwcbi_operation,
    gwcbi_payload_ts_ms,
    gwcbi_seqval,
    gwcbi_seqval_hex,
    gwcbi_tx_id,
    metadata_file_name,
    file_ingestion_timestamp
FROM {{ ref('stg_raw_pc_contact') }}

{% endsnapshot %}