{% snapshot pc_effectivedatedfields_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026-01-01      0.0                             SCD Type 2 snapshot for pc_effectivedatedfields.
                                                Source: ref('stg_raw_pc_effectivedatedfields')
                                                unique_key: effectivedatedfields_sk (surrogate on PK 'id')
                                                check_cols: ['hash_key'] (surrogate on all business cols excl PK)
                                                hard_deletes: new_record (inserts dbt_is_deleted=True row)
                                                No code change required when PARQUET CDC goes live.
-#}

{{ config(
    target_schema='gwpc',
    unique_key='effectivedatedfields_sk',
    strategy='check',
    alias='pc_effectivedatedfields',
    check_cols=['hash_key'],
    hard_deletes='new_record',
    tags=['snapshot', 'policy_centre', 'business_critical', 'pc_effectivedatedfields']
) }}

SELECT
    effectivedatedfields_sk,
    hash_key,
    COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS dbt_updated_at,
    policyaddress,
    secondarynamedinsured,
    isesrflag,
    fixedid,
    primarynamedinsured,
    exppremium_icare_cur,
    updatetime,
    wcsiddlevy_icare,
    id,
    exppremium_icare_amt,
    createuserid,
    beanversion,
    isrtwiflag,
    islegacy_icare,
    updateuserid,
    wclegacytotalprem_icare_cur,
    primarylocation,
    branchid,
    wclegacytotalprem_icare_amt,
    wcsiexcontlevy_icare,
    wcexpadjfactor_icare,
    publicid,
    billingcontact,
    createtime,
    wcsicontlevy_icare,
    isimmediatecover_icare,
    wcsiexddlevy_icare,
    wcsiexworkesinslevy_icare,
    wclegacygstamt_icare_cur,
    effectivedate,
    wclegacygstamt_icare_amt,
    producercodeid,
    expirationdate,
    groupperiodbtp_cur,
    wcexppremium_icare_cur,
    isexempted_icare,
    wcsiworkesinslevy_icare,
    groupperiodbtp_amt,
    archivepartition,
    wcexppremium_icare_amt,
    wcinputtaxadjamt_icare_cur,
    changetype,
    itcamount_icare_cur,
    basedonid,
    wcinputtaxadjamt_icare_amt,
    offeringcode,
    itcamount_icare_amt,
    reasonlowwages_icare,
    periodcategory_icare,
    isesiflag,
    sfactor_icare,
    wclegacygroupbtp_icare,
    wclegacygroupwages_icare,
    wclegacyfullpaiddiscount_icare,
    claimschemeagent_icare,
    legacygrpsfactor_icare,
    legacyrpaamt_icare_cur,
    legacyrpaamt_icare_amt,
    groupcostofclaims_icare_cur,
    lprmaxpremium_icare,
    groupcostofclaims_icare_amt,
    lprgrpminpremium_icare,
    legacygrpsecurity_icare_cur,
    groupdepositpremium_cur,
    legacygrprpaamt_icare_cur,
    coresfactor_icare,
    legacygrpsecurity_icare_amt,
    groupdepositpremium_amt,
    legacygrprpaamt_icare_amt,
    legacysecurity_icare_cur,
    legacysecurity_icare_amt,
    lprsecurityamt_icare,
    lprgrpmaxpremium_icare,
    lprminpremium_icare,
    crifbillingoption_icare,
    crifclaim,
    policypriorlossstatus_icare,
    esiflagnew_ext,
    iscovidlevyflag_ext,
    grpbasepremforlprplus_ext_cur,
    grpbasepremforlprplus_ext_amt,
    groupbtp_ext_cur,
    groupbtp_ext_amt,
    'GWPC' AS source_system,
    gwcbi_connector_ts_ms,
    gwcbi_lsn,
    gwcbi_operation,
    gwcbi_payload_ts_ms,
    gwcbi_seqval,
    gwcbi_seqval_hex,
    gwcbi_tx_id,
    metadata_file_name,
    file_ingestion_timestamp
FROM {{ ref('stg_raw_pc_effectivedatedfields') }}

{% endsnapshot %}