{% snapshot pc_policyperiod_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026-01-01      0.0                             SCD Type 2 snapshot for pc_policyperiod.
                                                Source: ref('stg_raw_pc_policyperiod')
                                                unique_key: policyperiod_sk (surrogate on PK 'id')
                                                check_cols: ['hash_key'] (surrogate on all business cols excl PK)
                                                hard_deletes: new_record (inserts dbt_is_deleted=True row)
                                                No code change required when PARQUET CDC goes live.
-#}

{{ config(
    target_schema='gwpc',
    unique_key='policyperiod_sk',
    strategy='check',
    alias='pc_policyperiod',
    check_cols=['hash_key'],
    hard_deletes='new_record',
    tags=['snapshot', 'policy_centre', 'business_critical', 'pc_policyperiod']
) }}

SELECT
    policyperiod_sk,
    hash_key,
    validquote,
    locked,
    editeffectivedate,
    cpacategory_icare,
    archivestate,
    archiveschemainfo,
    locationautonumberseq,
    updatetime,
    id,
    singlecheckingpatterncode,
    billingmethod,
    createuserid,
    allowgapsbefore,
    quotehidden,
    beanversion,
    branchname,
    islegacy_icare,
    updateuserid,
    cancellationdate,
    segment,
    primaryinsuredname,
    temporarybranch,
    depositoverridepct,
    islegacymaxterm_icare,
    policytermid,
    legacypolicynumber_icare,
    occupationtype_icare,
    selectedtermtype,
    periodstart,
    donotdestroy,
    publicid,
    altbillingaccountnumber,
    writtendate,
    totalcostrpt,
    totalcostrpt_cur,
    wclabourhirecode_icare,
    premiumadjustmentreason,
    mostrecentmodel,
    wcpremiumcalcode_icare,
    allocationofremainder,
    overridebillingallocation,
    wclegacyprempaymentcode_icare,
    archivefailuredetailsid,
    modeldate,
    invoicestreamcode,
    modelnumberindex,
    basestate,
    mostrecentmodelindex,
    policytype_icare,
    archivepartition,
    failedooseevaluation,
    branchnumber,
    transactioncostrpt,
    depositcollected,
    transactioncostrpt_cur,
    depositcollected_cur,
    basedonid,
    archivedate,
    billimmediatelypercentage,
    quotecloneoriginalperiod,
    depositamount,
    reasonlowwages_icare,
    preferredcoveragecurrency,
    periodend,
    preferredsettlementcurrency,
    basedondate,
    totalpremiumrpt,
    totalpremiumrpt_cur,
    validreinsurance,
    seriescheckingpatterncode,
    pnicontactdenorm,
    editlocked,
    rateasofdate,
    jobid,
    uwcompany,
    estimatedpremium,
    periodid,
    estimatedpremium_cur,
    assignedrisk,
    transactionpremiumrpt,
    commencementdate_icare,
    temporaryclonestatus,
    transactionpremiumrpt_cur,
    excludereason,
    archivefailureid,
    failedoosevalidation,
    retired,
    preempted,
    futureperiods,
    primaryinsurednamedenorm,
    modelnumber,
    termnumber,
    claimsmgr_schemeagent_icare,
    waivedepositchange,
    producercodeofrecordid,
    createtime,
    isofferingselected,
    policyid,
    excludedfromarchive,
    itcentitlement_icare,
    sifund_icare,
    custombilling,
    quoteclonesequencenumber,
    lockingcolumn,
    wctermtype_icare,
    refundcalcmethod,
    status,
    employercategory_icare,
    depositamount_cur,
    policynumber,
    gstregistration_icare,
    lprlargeclaimlimit_icare,
    securitypercentage_icare,
    isrecalculate_icare,
    externaltransaction_icare,
    lprproductoption_icare,
    cancelonexpiry_icare,
    brokeragename_icare,
    brokerageid_icare,
    generatedquotedoc_icare,
    initbygrouprenewalwf_icare,
    requotedeltafields_icare,
    confirmationdate_icare,
    renewalstate_icare,
    taxsurchargesrpt_cur,
    taxsurchargesrpt,
    niladjustloadingapplied_icare,
    externaltransactioncss_ext,
    draftrenewaldoctrigger_ext,
    cssrenewalupdatecount_ext,
    cssupdatecount_ext,
    csserrorcorrectioncount_ext,
    refundrpa_ext,
    franchisedeductible_ext,
    contribution_ext,
    budgetnonbudget_ext,
    policycategory_ext,
    policyname_ext,
    declarationform_ext,
    franchisedeductiblelimit_ext,
    currentcontributionamount_ext,
    'GWPC' AS source_system,
    gwcbi_connector_ts_ms,
    gwcbi_lsn,
    gwcbi_operation,
    gwcbi_payload_ts_ms,
    gwcbi_seqval,
    gwcbi_seqval_hex,
    gwcbi_tx_id,
    metadata_file_name,
    file_ingestion_timestamp
FROM {{ ref('stg_raw_pc_policyperiod') }}

{% endsnapshot %}