{% snapshot cc_activity_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026-01-01      0.0                             SCD Type 2 snapshot for cc_activity.
                                                Source: ref('stg_raw_cc_activity')
                                                unique_key: activity_sk (surrogate on PK 'id')
                                                check_cols: ['hash_key'] (surrogate on all business cols excl PK)
                                                hard_deletes: new_record (inserts dbt_is_deleted=True row)
                                                No code change required when PARQUET CDC goes live.
-#}

{{ config(
    target_schema='gwcc',
    unique_key='activity_sk',
    strategy='check',
    alias='cc_activity',
    check_cols=['hash_key'],
    hard_deletes='new_record',
    tags=['snapshot', 'claim_centre', 'non_business_critical', 'cc_activity']
) }}

SELECT
    activity_sk,
    hash_key,
    loadcommandid,
    previousgroupid,
    enddate,
    assignedbyuserid,
    externallyowned,
    logicalname,
    approvalrationale,
    previousqueueid,
    documenttemplate,
    updatetime,
    emailtemplate,
    workflowid,
    dispute_icareid,
    id,
    matterid,
    closeuserid,
    wpiassessrecord_icare,
    workcapacity_icareid,
    createuserid,
    priority,
    closedate,
    beanversion,
    retired,
    validationlevel,
    subject,
    updateuserid,
    shortsubject,
    bulkinvoiceid,
    approved,
    type,
    targetdate,
    autogenerated,
    escalationdate,
    externalownerccid,
    publicid,
    lastvieweddate,
    createtime,
    activityclass,
    command,
    assignedgroupid,
    ocrinvoice,
    servicerequestid,
    claimid,
    reminderactivity_icareid,
    mandatory,
    rehabplanid_ext,
    previoususerid,
    recurring,
    assignedqueueid,
    transactionsetid,
    exposureid,
    archivepartition,
    escalated,
    status,
    importance,
    assigneduserid,
    approvalissue,
    subtype,
    assignmentdate,
    activitypatternid,
    description,
    assignmentstatus,
    claimcontactid,
    employmentcapacity_icareid,
    referencedate_ext,
    mspreferral_extid,
    recurrenceenddate_ext,
    recurrencestartdate_ext,
    isrecurring_ext,
    recurringfrequency_ext,
    wpiactpeerreview_extid,
    customstatus_ext,
    withdrawreason_ext,
    approvalstatus_ext,
    'GWCC' AS source_system,
    gwcbi_connector_ts_ms,
    gwcbi_lsn,
    gwcbi_operation,
    gwcbi_payload_ts_ms,
    gwcbi_seqval,
    gwcbi_seqval_hex,
    gwcbi_tx_id,
    metadata_file_name,
    file_ingestion_timestamp
FROM {{ ref('stg_raw_cc_activity') }}

{% endsnapshot %}