{% snapshot bc_plan_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026-01-01      0.0                             SCD Type 2 snapshot for bc_plan.
                                                Source: ref('stg_raw_bc_plan')
                                                unique_key: plan_sk (surrogate on PK 'id')
                                                check_cols: ['hash_key'] (surrogate on all business cols excl PK)
                                                hard_deletes: new_record (inserts dbt_is_deleted=True row)
                                                No code change required when PARQUET CDC goes live.
-#}

{{ config(
    target_schema='gwbc',
    unique_key='plan_sk',
    strategy='check',
    alias='bc_plan',
    check_cols=['hash_key'],
    hard_deletes='new_record',
    tags=['snapshot', 'billing_centre', 'business_critical', 'bc_plan']
) }}

SELECT
    plan_sk,
    hash_key,
    daysuntilfirstdunningsent,
    daysfromrefdatetofirstinstall,
    autoprocesswhenpaymentmatches,
    namedenorm,
    polenterdelnqthreshold_cur,
    currency,
    suppresslowbalinvoices,
    updatetime,
    maximumnumberofinstallments,
    id,
    createuserid,
    skipfeefordownpayment,
    paymentexceptionssent,
    delaydisbursement,
    clearcommisionthreshold_cur,
    exceptionforpastduestatement,
    beanversion,
    reporting,
    updateuserid,
    createoffsetsonbilledinvoices,
    paymentreversalfee_cur,
    periodicity,
    cleargrossthreshold,
    promisedueindays,
    downpaymentafter,
    invoicefee,
    invoicefee_cur,
    writeoffthreshold,
    offeringtype_icare,
    writeoffthreshold_cur,
    lowgrosscleared,
    allowmodofmandisb,
    applicablesegments,
    cycleclosedayofmonth,
    aligninstallmentstoinvoices,
    inuse,
    publicid,
    equitybuffer,
    uservisible,
    requestintervaldaycount,
    skipinstallmentfees,
    statementsentaftercycleclose,
    statementswithlownetsuppressed,
    cancellationthreshold_cur,
    cancellationtarget_icare,
    graceperioddays,
    invoicingblackouttype,
    cancellationtarget,
    draftintervaldaycount,
    netthresholdforsuppressingstmt,
    sendautodisbawaitingapproval,
    daysbeforeplcyexpforinvblckout,
    lowbalancethreshold,
    lowbalancethreshold_cur,
    exceptionifpromisenotreceived,
    reinstatementfeeamount,
    createappractforautodisb,
    snapshotnonpastdueitems,
    reinstatementfeeamount_cur,
    workflowplan,
    netthresholdsuppressstmt_cur,
    installmentfee,
    installmentfee_cur,
    statement,
    paymentduedaylogic,
    billdateorduedatebilling,
    disbursementover,
    exitdelinquencythreshold,
    disbursementover_cur,
    secondinstallmentafter,
    promiseexceptionssent,
    latefeeamount,
    pmntschdchngoffsetsonbilled,
    daysaftercycleclosetosendstmnt,
    subtype,
    acctenterdelinquencythreshold,
    paymenttermsindays,
    cycleclosedayofmonthlogic,
    polenterdelinquencythreshold,
    acctenterdelnqthreshold_cur,
    holdinvoicingondlnqpolicies,
    availabledisbamttype,
    graceperioddayunit,
    name,
    invoiceitemplacementcutofftype,
    lowcommissioncleared,
    onetimechargeafter,
    downpaymentpercent,
    equitywarningsenabled,
    clearcommisionthreshold,
    retired,
    daysfromrefdatetodownpayment,
    seconddunningsentifnotpaid,
    paymentreversalfee,
    westernmethod,
    firstinstallmentafter,
    cleargrossthreshold_cur,
    listbillaccountexcesstreatment,
    chargequalification,
    changedeadlineintervaldaycount,
    planorder,
    cancellationthreshold,
    createtime,
    reviewdisbursementover,
    reviewdisbursementover_cur,
    daysuntilseconddunningsent,
    effectivedate,
    leadtimedayunit,
    clearinglogictarget,
    expirationdate,
    remindersentifpromisenotrcvd,
    daysuntilpromiseremindersent,
    downpaymentsecondinstallment,
    aggregation,
    draftdaylogic,
    upgradedfrombefore9,
    producerwriteoffthreshold,
    lowbalancemethod,
    firstdunningsentifnotpaid,
    producerwriteoffthreshold_cur,
    daysfromrefdatetoonetimecharge,
    daysfromrefdatetosecondinstall,
    paymentdueinterval,
    nonresponsivepmntdueinterval,
    exitdelinquencythreshold_cur,
    latefeeamount_cur,
    description,
    lobcode_icare,
    isbackdatedplan_ext,
    adjdaysbeforepolexpiry_ext,
    'GWBC' AS source_system,
    gwcbi_connector_ts_ms,
    gwcbi_lsn,
    gwcbi_operation,
    gwcbi_payload_ts_ms,
    gwcbi_seqval,
    gwcbi_seqval_hex,
    gwcbi_tx_id,
    metadata_file_name,
    file_ingestion_timestamp
FROM {{ ref('stg_raw_bc_plan') }}

{% endsnapshot %}