{% snapshot bc_policyperiod_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026-01-01      0.0                             SCD Type 2 snapshot for bc_policyperiod.
                                                Source: ref('stg_raw_bc_policyperiod')
                                                unique_key: policyperiod_sk (surrogate on PK 'id')
                                                check_cols: ['hash_key'] (surrogate on all business cols excl PK)
                                                hard_deletes: new_record (inserts dbt_is_deleted=True row)
                                                No code change required when PARQUET CDC goes live.
-#}

{{ config(
    target_schema='gwbc',
    unique_key='policyperiod_sk',
    strategy='check',
    alias='bc_policyperiod',
    check_cols=['hash_key'],
    hard_deletes='new_record',
    tags=['snapshot', 'billing_centre', 'business_critical', 'bc_policyperiod']
) }}

SELECT
    policyperiod_sk,
    hash_key,
    loadcommandid,
    heldforinvoicesending,
    underaudit,
    securityzoneid,
    policypereffdate,
    paymentplanid,
    archivestate,
    archiveschemainfo,
    currency,
    updatetime,
    hiddentaccountcontainerid,
    id,
    uwcompany,
    holdinvoicingwhendelinquent,
    billingmethod,
    overridingpayeraccountid,
    assignedrisk,
    excludereason,
    minpremiumapplicable_icare,
    overridinginvoicestreamid,
    createuserid,
    archivefailureid,
    dba,
    fullpaydiscountuntil,
    policyperioddelinquencyplanid,
    offernumber,
    equitywarningsenabled,
    closedate,
    nextarchivecheckdate,
    beanversion,
    eligibleforfullpaydiscount,
    retrieved,
    retired,
    bounddate,
    islegacy_icare,
    updateuserid,
    employertype_icare,
    fullpaydiscountevaluated,
    btpamount_icare_cur,
    westernmethod,
    termnumber,
    archivetacctcontainerid,
    pendingremainingbalancefix,
    btpamount_icare_amt,
    offeringtype_icare,
    cancellationtype,
    cancelreason,
    legacypolicynumber_icare,
    publicid,
    priorpolicynumber,
    equitybuffer,
    discountedpaymentthreshold,
    discountedpaymentthreshold_cur,
    createtime,
    underwriter,
    policyid,
    excludedfromarchive,
    totalpremium_icare_cur,
    riskjurisdiction,
    submissionnumber_icare,
    archivefailuredetailsid,
    totalpremium_icare_amt,
    subtermtype_icare,
    archivepartition,
    policyperexpirdate,
    chargeheld,
    returnpremiumplanid,
    cancelstatus,
    closurestatus,
    archivedate,
    confirmationnotificationstate,
    termconfirmed,
    policynumberlongdenorm,
    policygroupinfo_icare,
    policynumberlong,
    paymentdistributionenabled,
    policynumberdenorm,
    policynumber,
    paymentprofile_icare,
    referredtolegal_icare,
    isrolledupdelin_icare,
    reinstatecount_icare,
    islprapplication_icare,
    delinquencyriskprofile_icare,
    paymentplan_icare,
    updatedpaymentplan_icare,
    doubtfuldebittotal_icare_cur,
    doubtfuldebittotal_icare_amt,
    claimsmgr_schemeagent_icare,
    issmsevent_icare,
    policytype_icare,
    lprproductoption_icare,
    iscancelonexpiry_icare,
    crifbillingoption_icare,
    confirmationdate_icare,
    renewalstate_icare,
    fpdeligibletodate_icare,
    isplanchangedatdel_icare,
    eligiblefpdamount_icare,
    eligiblefpdamount_icare_cur,
    holdlpf_ext,
    collapseinstalmentcount_ext,
    instalmentcollapseddate_ext,
    instalmentreinstateddate_ext,
    instalmentdefaulteddate_ext,
    franchisedeductible_ext,
    contribution_ext,
    itcentitlement_ext,
    budgetnonbudget_ext,
    policycategory_ext,
    policyname_ext,
    declarationform_ext,
    gstregistration_ext,
    wclabourhirecode_ext,
    commencementdate_ext,
    franchisedeductiblelimit_ext,
    'GWBC' AS source_system,
    gwcbi_connector_ts_ms,
    gwcbi_lsn,
    gwcbi_operation,
    gwcbi_payload_ts_ms,
    gwcbi_seqval,
    gwcbi_seqval_hex,
    gwcbi_tx_id,
    metadata_file_name,
    file_ingestion_timestamp
FROM {{ ref('stg_raw_bc_policyperiod') }}

{% endsnapshot %}