
{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             This Converts Parquet or AVRO Data Loaded in the Variant Column in the RAW DB into Flattend Views
                                                This also creates a HASH_KEY for Incremental Tables for the Curated Layer 
                                                Additional CDA Files are Null in the AVRO but not in CDA .
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    tags=["raw_gwpc","raw_layer"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:ValidQuote::BOOLEAN AS validquote,
                data_payload:Locked::BOOLEAN AS locked,
                TO_TIMESTAMP_TZ(data_payload:EditEffectiveDate::NUMBER/1000) AS editeffectivedate,
                data_payload:CPACategory_icare::NUMBER AS cpacategory_icare,
                data_payload:ArchiveState::NUMBER AS archivestate,
                data_payload:ArchiveSchemaInfo::NUMBER AS archiveschemainfo,
                data_payload:LocationAutoNumberSeq::NUMBER AS locationautonumberseq,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:ID::NUMBER AS id,
                CAST(data_payload:SingleCheckingPatternCode::TEXT AS VARCHAR(64)) AS singlecheckingpatterncode,
                data_payload:BillingMethod::NUMBER AS billingmethod,
                data_payload:CreateUserID::NUMBER AS createuserid,
                data_payload:AllowGapsBefore::BOOLEAN AS allowgapsbefore,
                data_payload:QuoteHidden::BOOLEAN AS quotehidden,
                data_payload:BeanVersion::NUMBER AS beanversion,
                CAST(data_payload:BranchName::TEXT AS VARCHAR(255)) AS branchname,
                data_payload:IsLegacy_icare::BOOLEAN AS islegacy_icare,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                TO_TIMESTAMP_TZ(data_payload:CancellationDate::NUMBER/1000) AS cancellationdate,
                data_payload:Segment::NUMBER AS segment,
                CAST(data_payload:PrimaryInsuredName::TEXT AS VARCHAR(255)) AS primaryinsuredname,
                data_payload:TemporaryBranch::BOOLEAN AS temporarybranch,
                CAST(data_payload:DepositOverridePct AS NUMBER(12,3)) AS depositoverridepct,
                data_payload:IsLegacyMaxTerm_icare::BOOLEAN AS islegacymaxterm_icare,
                data_payload:PolicyTermID::NUMBER AS policytermid,
                CAST(data_payload:LegacyPolicyNumber_icare::TEXT AS VARCHAR(60)) AS legacypolicynumber_icare,
                data_payload:OccupationType_icare::NUMBER AS occupationtype_icare,
                data_payload:SelectedTermType::NUMBER AS selectedtermtype,
                TO_TIMESTAMP_TZ(data_payload:PeriodStart::NUMBER/1000) AS periodstart,
                data_payload:DoNotDestroy::BOOLEAN AS donotdestroy,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                CAST(data_payload:AltBillingAccountNumber::TEXT AS VARCHAR(255)) AS altbillingaccountnumber,
                TO_TIMESTAMP_TZ(data_payload:WrittenDate::NUMBER/1000) AS writtendate,
                CAST(data_payload:TotalCostRPT AS NUMBER(18,2)) AS totalcostrpt,
                data_payload:TotalCostRPT_cur::NUMBER AS totalcostrpt_cur,
                data_payload:WCLabourHireCode_icare::NUMBER AS wclabourhirecode_icare,
                CAST(data_payload:PremiumAdjustmentReason::TEXT AS VARCHAR(255)) AS premiumadjustmentreason,
                data_payload:MostRecentModel::BOOLEAN AS mostrecentmodel,
                data_payload:WCPremiumCalCode_icare::NUMBER AS wcpremiumcalcode_icare,
                data_payload:AllocationOfRemainder::NUMBER AS allocationofremainder,
                data_payload:OverrideBillingAllocation::BOOLEAN AS overridebillingallocation,
                data_payload:WCLegacyPremPaymentCode_icare::NUMBER AS wclegacyprempaymentcode_icare,
                data_payload:ArchiveFailureDetailsID::NUMBER AS archivefailuredetailsid,
                TO_TIMESTAMP_TZ(data_payload:ModelDate::NUMBER/1000) AS modeldate,
                CAST(data_payload:InvoiceStreamCode::TEXT AS VARCHAR(255)) AS invoicestreamcode,
                CAST(data_payload:ModelNumberIndex::TEXT AS VARCHAR(64)) AS modelnumberindex,
                data_payload:BaseState::NUMBER AS basestate,
                CAST(data_payload:MostRecentModelIndex::TEXT AS VARCHAR(64)) AS mostrecentmodelindex,
                data_payload:PolicyType_icare::NUMBER AS policytype_icare,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                data_payload:FailedOOSEEvaluation::BOOLEAN AS failedooseevaluation,
                data_payload:BranchNumber::NUMBER AS branchnumber,
                CAST(data_payload:TransactionCostRPT AS NUMBER(18,2)) AS transactioncostrpt,
                CAST(data_payload:DepositCollected AS NUMBER(18,2)) AS depositcollected,
                data_payload:TransactionCostRPT_cur::NUMBER AS transactioncostrpt_cur,
                data_payload:DepositCollected_cur::NUMBER AS depositcollected_cur,
                data_payload:BasedOnID::NUMBER AS basedonid,
                TO_TIMESTAMP_TZ(data_payload:ArchiveDate::NUMBER/1000) AS archivedate,
                CAST(data_payload:BillImmediatelyPercentage AS NUMBER(4,1)) AS billimmediatelypercentage,
                CAST(data_payload:QuoteCloneOriginalPeriod::TEXT AS VARCHAR(255)) AS quotecloneoriginalperiod,
                CAST(data_payload:DepositAmount AS NUMBER(18,2)) AS depositamount,
                CAST(data_payload:ReasonLowWages_icare::TEXT AS VARCHAR(60)) AS reasonlowwages_icare,
                data_payload:PreferredCoverageCurrency::NUMBER AS preferredcoveragecurrency,
                TO_TIMESTAMP_TZ(data_payload:PeriodEnd::NUMBER/1000) AS periodend,
                data_payload:PreferredSettlementCurrency::NUMBER AS preferredsettlementcurrency,
                TO_TIMESTAMP_TZ(data_payload:BasedOnDate::NUMBER/1000) AS basedondate,
                CAST(data_payload:TotalPremiumRPT AS NUMBER(18,2)) AS totalpremiumrpt,
                data_payload:TotalPremiumRPT_cur::NUMBER AS totalpremiumrpt_cur,
                data_payload:ValidReinsurance::BOOLEAN AS validreinsurance,
                CAST(data_payload:SeriesCheckingPatternCode::TEXT AS VARCHAR(64)) AS seriescheckingpatterncode,
                data_payload:PNIContactDenorm::NUMBER AS pnicontactdenorm,
                data_payload:EditLocked::BOOLEAN AS editlocked,
                TO_TIMESTAMP_TZ(data_payload:RateAsOfDate::NUMBER/1000) AS rateasofdate,
                data_payload:JobID::NUMBER AS jobid,
                data_payload:UWCompany::NUMBER AS uwcompany,
                CAST(data_payload:EstimatedPremium AS NUMBER(18,2)) AS estimatedpremium,
                data_payload:PeriodID::NUMBER AS periodid,
                data_payload:EstimatedPremium_cur::NUMBER AS estimatedpremium_cur,
                data_payload:AssignedRisk::BOOLEAN AS assignedrisk,
                CAST(data_payload:TransactionPremiumRPT AS NUMBER(18,2)) AS transactionpremiumrpt,
                TO_TIMESTAMP_TZ(data_payload:CommencementDate_icare::NUMBER/1000) AS commencementdate_icare,
                data_payload:TemporaryCloneStatus::NUMBER AS temporaryclonestatus,
                data_payload:TransactionPremiumRPT_cur::NUMBER AS transactionpremiumrpt_cur,
                CAST(data_payload:ExcludeReason::TEXT AS VARCHAR(255)) AS excludereason,
                data_payload:ArchiveFailureID::NUMBER AS archivefailureid,
                data_payload:FailedOOSEValidation::BOOLEAN AS failedoosevalidation,
                data_payload:Retired::NUMBER AS retired,
                data_payload:Preempted::BOOLEAN AS preempted,
                data_payload:FuturePeriods::BOOLEAN AS futureperiods,
                CAST(data_payload:PrimaryInsuredNameDenorm::TEXT AS VARCHAR(255)) AS primaryinsurednamedenorm,
                data_payload:ModelNumber::NUMBER AS modelnumber,
                data_payload:TermNumber::NUMBER AS termnumber,
                data_payload:ClaimsMgr_SchemeAgent_icare::NUMBER AS claimsmgr_schemeagent_icare,
                data_payload:WaiveDepositChange::BOOLEAN AS waivedepositchange,
                data_payload:ProducerCodeOfRecordID::NUMBER AS producercodeofrecordid,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                data_payload:isOfferingSelected::BOOLEAN AS isofferingselected,
                data_payload:PolicyID::NUMBER AS policyid,
                data_payload:ExcludedFromArchive::BOOLEAN AS excludedfromarchive,
                CAST(data_payload:ITCEntitlement_icare::TEXT AS VARCHAR(60)) AS itcentitlement_icare,
                data_payload:SIFund_icare::NUMBER AS sifund_icare,
                data_payload:CustomBilling::BOOLEAN AS custombilling,
                data_payload:QuoteCloneSequenceNumber::NUMBER AS quoteclonesequencenumber,
                data_payload:LockingColumn::NUMBER AS lockingcolumn,
                data_payload:WCTermType_icare::NUMBER AS wctermtype_icare,
                data_payload:RefundCalcMethod::NUMBER AS refundcalcmethod,
                data_payload:Status::NUMBER AS status,
                data_payload:EmployerCategory_icare::NUMBER AS employercategory_icare,
                data_payload:DepositAmount_cur::NUMBER AS depositamount_cur,
                CAST(data_payload:PolicyNumber::TEXT AS VARCHAR(40)) AS policynumber,
                data_payload:GSTRegistration_icare::BOOLEAN AS gstregistration_icare,
                data_payload:LPRLargeClaimLimit_icare::NUMBER AS lprlargeclaimlimit_icare,
                data_payload:SecurityPercentage_icare::NUMBER AS securitypercentage_icare,
                data_payload:IsRecalculate_icare::BOOLEAN AS isrecalculate_icare,
                data_payload:ExternalTransaction_icare::BOOLEAN AS externaltransaction_icare,
                data_payload:LPRProductOption_icare::NUMBER AS lprproductoption_icare,
                data_payload:CancelOnExpiry_icare::BOOLEAN AS cancelonexpiry_icare,
                CAST(data_payload:BrokerageName_icare::TEXT AS VARCHAR(255)) AS brokeragename_icare,
                CAST(data_payload:BrokerageID_icare::TEXT AS VARCHAR(255)) AS brokerageid_icare,
                data_payload:GeneratedQuoteDoc_icare::BOOLEAN AS generatedquotedoc_icare,
                data_payload:InitByGroupRenewalWF_icare::BOOLEAN AS initbygrouprenewalwf_icare,
                data_payload:RequoteDeltaFields_icare::NUMBER AS requotedeltafields_icare,
                TO_TIMESTAMP_TZ(data_payload:ConfirmationDate_icare::NUMBER/1000) AS confirmationdate_icare,
                data_payload:RenewalState_icare::NUMBER AS renewalstate_icare,
                data_payload:TaxSurchargesRPT_cur::NUMBER AS taxsurchargesrpt_cur,
                CAST(data_payload:TaxSurchargesRPT AS NUMBER(18,2)) AS taxsurchargesrpt,
                data_payload:NilAdjustLoadingApplied_icare::BOOLEAN AS niladjustloadingapplied_icare,
                data_payload:ExternalTransactionCSS_Ext::BOOLEAN AS externaltransactioncss_ext,
                data_payload:DraftRenewalDocTrigger_Ext::BOOLEAN AS draftrenewaldoctrigger_ext,
                data_payload:CSSRenewalUpdateCount_Ext::NUMBER AS cssrenewalupdatecount_ext,
                data_payload:CSSUpdateCount_EXt::NUMBER AS cssupdatecount_ext,
                data_payload:CSSErrorCorrectionCount_Ext::NUMBER AS csserrorcorrectioncount_ext,
                data_payload:RefundRPA_Ext::BOOLEAN AS refundrpa_ext,
                data_payload:FranchiseDeductible_Ext::NUMBER AS franchisedeductible_ext,
                data_payload:Contribution_Ext::NUMBER AS contribution_ext,
                data_payload:BudgetNonBudget_Ext::BOOLEAN AS budgetnonbudget_ext,
                data_payload:PolicyCategory_Ext::NUMBER AS policycategory_ext,
                CAST(data_payload:PolicyName_Ext::TEXT AS VARCHAR(255)) AS policyname_ext,
                data_payload:DeclarationForm_Ext::NUMBER AS declarationform_ext,
                CAST(data_payload:FranchiseDeductibleLimit_Ext AS NUMBER(18,2)) AS franchisedeductiblelimit_ext,
                CAST(data_payload:CurrentContributionAmount_Ext AS NUMBER(18,2)) AS currentcontributionamount_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwpc', 'pc_policyperiod') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:validquote::BOOLEAN AS validquote,
                $1:locked::BOOLEAN AS locked,
                $1:editeffectivedate::TIMESTAMP_TZ AS editeffectivedate,
                $1:cpacategory_icare::NUMBER AS cpacategory_icare,
                $1:archivestate::NUMBER AS archivestate,
                $1:archiveschemainfo::NUMBER AS archiveschemainfo,
                $1:locationautonumberseq::NUMBER AS locationautonumberseq,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:id::NUMBER AS id,
                CAST($1:singlecheckingpatterncode::TEXT AS VARCHAR(64)) AS singlecheckingpatterncode,
                $1:billingmethod::NUMBER AS billingmethod,
                $1:createuserid::NUMBER AS createuserid,
                $1:allowgapsbefore::BOOLEAN AS allowgapsbefore,
                $1:quotehidden::BOOLEAN AS quotehidden,
                $1:beanversion::NUMBER AS beanversion,
                CAST($1:branchname::TEXT AS VARCHAR(255)) AS branchname,
                $1:islegacy_icare::BOOLEAN AS islegacy_icare,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:cancellationdate::TIMESTAMP_TZ AS cancellationdate,
                $1:segment::NUMBER AS segment,
                CAST($1:primaryinsuredname::TEXT AS VARCHAR(255)) AS primaryinsuredname,
                $1:temporarybranch::BOOLEAN AS temporarybranch,
                CAST($1:depositoverridepct AS NUMBER(12,3)) AS depositoverridepct,
                $1:islegacymaxterm_icare::BOOLEAN AS islegacymaxterm_icare,
                $1:policytermid::NUMBER AS policytermid,
                CAST($1:legacypolicynumber_icare::TEXT AS VARCHAR(60)) AS legacypolicynumber_icare,
                $1:occupationtype_icare::NUMBER AS occupationtype_icare,
                $1:selectedtermtype::NUMBER AS selectedtermtype,
                $1:periodstart::TIMESTAMP_TZ AS periodstart,
                $1:donotdestroy::BOOLEAN AS donotdestroy,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                CAST($1:altbillingaccountnumber::TEXT AS VARCHAR(255)) AS altbillingaccountnumber,
                $1:writtendate::TIMESTAMP_TZ AS writtendate,
                CAST($1:totalcostrpt AS NUMBER(18,2)) AS totalcostrpt,
                $1:totalcostrpt_cur::NUMBER AS totalcostrpt_cur,
                $1:wclabourhirecode_icare::NUMBER AS wclabourhirecode_icare,
                CAST($1:premiumadjustmentreason::TEXT AS VARCHAR(255)) AS premiumadjustmentreason,
                $1:mostrecentmodel::BOOLEAN AS mostrecentmodel,
                $1:wcpremiumcalcode_icare::NUMBER AS wcpremiumcalcode_icare,
                $1:allocationofremainder::NUMBER AS allocationofremainder,
                $1:overridebillingallocation::BOOLEAN AS overridebillingallocation,
                $1:wclegacyprempaymentcode_icare::NUMBER AS wclegacyprempaymentcode_icare,
                $1:archivefailuredetailsid::NUMBER AS archivefailuredetailsid,
                $1:modeldate::TIMESTAMP_TZ AS modeldate,
                CAST($1:invoicestreamcode::TEXT AS VARCHAR(255)) AS invoicestreamcode,
                CAST($1:modelnumberindex::TEXT AS VARCHAR(64)) AS modelnumberindex,
                $1:basestate::NUMBER AS basestate,
                CAST($1:mostrecentmodelindex::TEXT AS VARCHAR(64)) AS mostrecentmodelindex,
                $1:policytype_icare::NUMBER AS policytype_icare,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:failedooseevaluation::BOOLEAN AS failedooseevaluation,
                $1:branchnumber::NUMBER AS branchnumber,
                CAST($1:transactioncostrpt AS NUMBER(18,2)) AS transactioncostrpt,
                CAST($1:depositcollected AS NUMBER(18,2)) AS depositcollected,
                $1:transactioncostrpt_cur::NUMBER AS transactioncostrpt_cur,
                $1:depositcollected_cur::NUMBER AS depositcollected_cur,
                $1:basedonid::NUMBER AS basedonid,
                $1:archivedate::TIMESTAMP_TZ AS archivedate,
                CAST($1:billimmediatelypercentage AS NUMBER(4,1)) AS billimmediatelypercentage,
                CAST($1:quotecloneoriginalperiod::TEXT AS VARCHAR(255)) AS quotecloneoriginalperiod,
                CAST($1:depositamount AS NUMBER(18,2)) AS depositamount,
                CAST($1:reasonlowwages_icare::TEXT AS VARCHAR(60)) AS reasonlowwages_icare,
                $1:preferredcoveragecurrency::NUMBER AS preferredcoveragecurrency,
                $1:periodend::TIMESTAMP_TZ AS periodend,
                $1:preferredsettlementcurrency::NUMBER AS preferredsettlementcurrency,
                $1:basedondate::TIMESTAMP_TZ AS basedondate,
                CAST($1:totalpremiumrpt AS NUMBER(18,2)) AS totalpremiumrpt,
                $1:totalpremiumrpt_cur::NUMBER AS totalpremiumrpt_cur,
                $1:validreinsurance::BOOLEAN AS validreinsurance,
                CAST($1:seriescheckingpatterncode::TEXT AS VARCHAR(64)) AS seriescheckingpatterncode,
                $1:pnicontactdenorm::NUMBER AS pnicontactdenorm,
                $1:editlocked::BOOLEAN AS editlocked,
                $1:rateasofdate::TIMESTAMP_TZ AS rateasofdate,
                $1:jobid::NUMBER AS jobid,
                $1:uwcompany::NUMBER AS uwcompany,
                CAST($1:estimatedpremium AS NUMBER(18,2)) AS estimatedpremium,
                $1:periodid::NUMBER AS periodid,
                $1:estimatedpremium_cur::NUMBER AS estimatedpremium_cur,
                $1:assignedrisk::BOOLEAN AS assignedrisk,
                CAST($1:transactionpremiumrpt AS NUMBER(18,2)) AS transactionpremiumrpt,
                $1:commencementdate_icare::TIMESTAMP_TZ AS commencementdate_icare,
                $1:temporaryclonestatus::NUMBER AS temporaryclonestatus,
                $1:transactionpremiumrpt_cur::NUMBER AS transactionpremiumrpt_cur,
                CAST($1:excludereason::TEXT AS VARCHAR(255)) AS excludereason,
                $1:archivefailureid::NUMBER AS archivefailureid,
                $1:failedoosevalidation::BOOLEAN AS failedoosevalidation,
                $1:retired::NUMBER AS retired,
                $1:preempted::BOOLEAN AS preempted,
                $1:futureperiods::BOOLEAN AS futureperiods,
                CAST($1:primaryinsurednamedenorm::TEXT AS VARCHAR(255)) AS primaryinsurednamedenorm,
                $1:modelnumber::NUMBER AS modelnumber,
                $1:termnumber::NUMBER AS termnumber,
                $1:claimsmgr_schemeagent_icare::NUMBER AS claimsmgr_schemeagent_icare,
                $1:waivedepositchange::BOOLEAN AS waivedepositchange,
                $1:producercodeofrecordid::NUMBER AS producercodeofrecordid,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:isofferingselected::BOOLEAN AS isofferingselected,
                $1:policyid::NUMBER AS policyid,
                $1:excludedfromarchive::BOOLEAN AS excludedfromarchive,
                CAST($1:itcentitlement_icare::TEXT AS VARCHAR(60)) AS itcentitlement_icare,
                $1:sifund_icare::NUMBER AS sifund_icare,
                $1:custombilling::BOOLEAN AS custombilling,
                $1:quoteclonesequencenumber::NUMBER AS quoteclonesequencenumber,
                $1:lockingcolumn::NUMBER AS lockingcolumn,
                $1:wctermtype_icare::NUMBER AS wctermtype_icare,
                $1:refundcalcmethod::NUMBER AS refundcalcmethod,
                $1:status::NUMBER AS status,
                $1:employercategory_icare::NUMBER AS employercategory_icare,
                $1:depositamount_cur::NUMBER AS depositamount_cur,
                CAST($1:policynumber::TEXT AS VARCHAR(40)) AS policynumber,
                $1:gstregistration_icare::BOOLEAN AS gstregistration_icare,
                $1:lprlargeclaimlimit_icare::NUMBER AS lprlargeclaimlimit_icare,
                $1:securitypercentage_icare::NUMBER AS securitypercentage_icare,
                $1:isrecalculate_icare::BOOLEAN AS isrecalculate_icare,
                $1:externaltransaction_icare::BOOLEAN AS externaltransaction_icare,
                $1:lprproductoption_icare::NUMBER AS lprproductoption_icare,
                $1:cancelonexpiry_icare::BOOLEAN AS cancelonexpiry_icare,
                CAST($1:brokeragename_icare::TEXT AS VARCHAR(255)) AS brokeragename_icare,
                CAST($1:brokerageid_icare::TEXT AS VARCHAR(255)) AS brokerageid_icare,
                $1:generatedquotedoc_icare::BOOLEAN AS generatedquotedoc_icare,
                $1:initbygrouprenewalwf_icare::BOOLEAN AS initbygrouprenewalwf_icare,
                $1:requotedeltafields_icare::NUMBER AS requotedeltafields_icare,
                $1:confirmationdate_icare::TIMESTAMP_TZ AS confirmationdate_icare,
                $1:renewalstate_icare::NUMBER AS renewalstate_icare,
                $1:taxsurchargesrpt_cur::NUMBER AS taxsurchargesrpt_cur,
                CAST($1:taxsurchargesrpt AS NUMBER(18,2)) AS taxsurchargesrpt,
                $1:niladjustloadingapplied_icare::BOOLEAN AS niladjustloadingapplied_icare,
                $1:externaltransactioncss_ext::BOOLEAN AS externaltransactioncss_ext,
                $1:draftrenewaldoctrigger_ext::BOOLEAN AS draftrenewaldoctrigger_ext,
                $1:cssrenewalupdatecount_ext::NUMBER AS cssrenewalupdatecount_ext,
                $1:cssupdatecount_ext::NUMBER AS cssupdatecount_ext,
                $1:csserrorcorrectioncount_ext::NUMBER AS csserrorcorrectioncount_ext,
                $1:refundrpa_ext::BOOLEAN AS refundrpa_ext,
                $1:franchisedeductible_ext::NUMBER AS franchisedeductible_ext,
                $1:contribution_ext::NUMBER AS contribution_ext,
                $1:budgetnonbudget_ext::BOOLEAN AS budgetnonbudget_ext,
                $1:policycategory_ext::NUMBER AS policycategory_ext,
                CAST($1:policyname_ext::TEXT AS VARCHAR(255)) AS policyname_ext,
                $1:declarationform_ext::NUMBER AS declarationform_ext,
                CAST($1:franchisedeductiblelimit_ext AS NUMBER(18,2)) AS franchisedeductiblelimit_ext,
                CAST($1:currentcontributionamount_ext AS NUMBER(18,2)) AS currentcontributionamount_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwpc', 'pc_policyperiod') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),
{#-
    Driving CTE Over 
    Transformed CTE is To Create the HASH_KEY Based on the Right Combination
-#}   
cte_transformed AS (
    SELECT
        *,
        CASE
             WHEN file_type = 'AVRO' THEN
                {{ dbt_utils.generate_surrogate_key([
                                'validquote',
                        'locked',
                        'editeffectivedate',
                        'cpacategory_icare',
                        'archivestate',
                        'archiveschemainfo',
                        'locationautonumberseq',
                        'updatetime',
                        'id',
                        'singlecheckingpatterncode',
                        'billingmethod',
                        'createuserid',
                        'allowgapsbefore',
                        'quotehidden',
                        'beanversion',
                        'branchname',
                        'islegacy_icare',
                        'updateuserid',
                        'cancellationdate',
                        'segment',
                        'primaryinsuredname',
                        'temporarybranch',
                        'depositoverridepct',
                        'islegacymaxterm_icare',
                        'policytermid',
                        'legacypolicynumber_icare',
                        'occupationtype_icare',
                        'selectedtermtype',
                        'periodstart',
                        'donotdestroy',
                        'publicid',
                        'altbillingaccountnumber',
                        'writtendate',
                        'totalcostrpt',
                        'totalcostrpt_cur',
                        'wclabourhirecode_icare',
                        'premiumadjustmentreason',
                        'mostrecentmodel',
                        'wcpremiumcalcode_icare',
                        'allocationofremainder',
                        'overridebillingallocation',
                        'wclegacyprempaymentcode_icare',
                        'archivefailuredetailsid',
                        'modeldate',
                        'invoicestreamcode',
                        'modelnumberindex',
                        'basestate',
                        'mostrecentmodelindex',
                        'policytype_icare',
                        'archivepartition',
                        'failedooseevaluation',
                        'branchnumber',
                        'transactioncostrpt',
                        'depositcollected',
                        'transactioncostrpt_cur',
                        'depositcollected_cur',
                        'basedonid',
                        'archivedate',
                        'billimmediatelypercentage',
                        'quotecloneoriginalperiod',
                        'depositamount',
                        'reasonlowwages_icare',
                        'preferredcoveragecurrency',
                        'periodend',
                        'preferredsettlementcurrency',
                        'basedondate',
                        'totalpremiumrpt',
                        'totalpremiumrpt_cur',
                        'validreinsurance',
                        'seriescheckingpatterncode',
                        'pnicontactdenorm',
                        'editlocked',
                        'rateasofdate',
                        'jobid',
                        'uwcompany',
                        'estimatedpremium',
                        'periodid',
                        'estimatedpremium_cur',
                        'assignedrisk',
                        'transactionpremiumrpt',
                        'commencementdate_icare',
                        'temporaryclonestatus',
                        'transactionpremiumrpt_cur',
                        'excludereason',
                        'archivefailureid',
                        'failedoosevalidation',
                        'retired',
                        'preempted',
                        'futureperiods',
                        'primaryinsurednamedenorm',
                        'modelnumber',
                        'termnumber',
                        'claimsmgr_schemeagent_icare',
                        'waivedepositchange',
                        'producercodeofrecordid',
                        'createtime',
                        'isofferingselected',
                        'policyid',
                        'excludedfromarchive',
                        'itcentitlement_icare',
                        'sifund_icare',
                        'custombilling',
                        'quoteclonesequencenumber',
                        'lockingcolumn',
                        'wctermtype_icare',
                        'refundcalcmethod',
                        'status',
                        'employercategory_icare',
                        'depositamount_cur',
                        'policynumber',
                        'gstregistration_icare',
                        'lprlargeclaimlimit_icare',
                        'securitypercentage_icare',
                        'isrecalculate_icare',
                        'externaltransaction_icare',
                        'lprproductoption_icare',
                        'cancelonexpiry_icare',
                        'brokeragename_icare',
                        'brokerageid_icare',
                        'generatedquotedoc_icare',
                        'initbygrouprenewalwf_icare',
                        'requotedeltafields_icare',
                        'confirmationdate_icare',
                        'renewalstate_icare',
                        'taxsurchargesrpt_cur',
                        'taxsurchargesrpt',
                        'niladjustloadingapplied_icare',
                        'externaltransactioncss_ext',
                        'draftrenewaldoctrigger_ext',
                        'cssrenewalupdatecount_ext',
                        'cssupdatecount_ext',
                        'csserrorcorrectioncount_ext',
                        'refundrpa_ext',
                        'franchisedeductible_ext',
                        'contribution_ext',
                        'budgetnonbudget_ext',
                        'policycategory_ext',
                        'policyname_ext',
                        'declarationform_ext',
                        'franchisedeductiblelimit_ext',
                        'currentcontributionamount_ext'
                        ]) }}
            WHEN file_type = 'PARQUET' THEN
                {{ dbt_utils.generate_surrogate_key([
                                'id',
                        'gwcbi_seqval'
                        ]) }}
        END AS hash_key    
    FROM cte_source_data
)
SELECT * FROM cte_transformed
        