{#-

Project: Data Uplift Progran 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2025-11-18      0.0                             This Converts Parquet or AVRO Data in Variant Column in the RAW DB into Flattend Views

-#}   

{{ config(
    tags=["raw_gwpc"]
) }}

{%- set source_system_code = 'GWPC' -%}

WITH source_data AS 
(

            SELECT
                data_payload:VALIDQUOTE::BOOLEAN AS VALIDQUOTE,
                data_payload:LOCKED::BOOLEAN AS LOCKED,
                TO_TIMESTAMP_NTZ(data_payload:EDITEFFECTIVEDATE::NUMBER/1000) AS EDITEFFECTIVEDATE,
                data_payload:CPACATEGORY_ICARE::NUMBER AS CPACATEGORY_ICARE,
                data_payload:ARCHIVESTATE::NUMBER AS ARCHIVESTATE,
                data_payload:ARCHIVESCHEMAINFO::NUMBER AS ARCHIVESCHEMAINFO,
                data_payload:LOCATIONAUTONUMBERSEQ::NUMBER AS LOCATIONAUTONUMBERSEQ,
                TO_TIMESTAMP_NTZ(data_payload:UPDATETIME::NUMBER/1000) AS UPDATETIME,
                data_payload:ID::NUMBER AS ID,
                CAST(data_payload:SINGLECHECKINGPATTERNCODE::TEXT AS VARCHAR(64)) AS SINGLECHECKINGPATTERNCODE,
                data_payload:BILLINGMETHOD::NUMBER AS BILLINGMETHOD,
                data_payload:CREATEUSERID::NUMBER AS CREATEUSERID,
                data_payload:ALLOWGAPSBEFORE::BOOLEAN AS ALLOWGAPSBEFORE,
                data_payload:QUOTEHIDDEN::BOOLEAN AS QUOTEHIDDEN,
                data_payload:BEANVERSION::NUMBER AS BEANVERSION,
                CAST(data_payload:BRANCHNAME::TEXT AS VARCHAR(255)) AS BRANCHNAME,
                data_payload:ISLEGACY_ICARE::BOOLEAN AS ISLEGACY_ICARE,
                data_payload:UPDATEUSERID::NUMBER AS UPDATEUSERID,
                TO_TIMESTAMP_NTZ(data_payload:CANCELLATIONDATE::NUMBER/1000) AS CANCELLATIONDATE,
                data_payload:SEGMENT::NUMBER AS SEGMENT,
                CAST(data_payload:PRIMARYINSUREDNAME::TEXT AS VARCHAR(255)) AS PRIMARYINSUREDNAME,
                data_payload:TEMPORARYBRANCH::BOOLEAN AS TEMPORARYBRANCH,
                data_payload:DEPOSITOVERRIDEPCT::NUMBER AS DEPOSITOVERRIDEPCT,
                data_payload:ISLEGACYMAXTERM_ICARE::BOOLEAN AS ISLEGACYMAXTERM_ICARE,
                data_payload:POLICYTERMID::NUMBER AS POLICYTERMID,
                CAST(data_payload:LEGACYPOLICYNUMBER_ICARE::TEXT AS VARCHAR(60)) AS LEGACYPOLICYNUMBER_ICARE,
                data_payload:OCCUPATIONTYPE_ICARE::NUMBER AS OCCUPATIONTYPE_ICARE,
                data_payload:SELECTEDTERMTYPE::NUMBER AS SELECTEDTERMTYPE,
                TO_TIMESTAMP_NTZ(data_payload:PERIODSTART::NUMBER/1000) AS PERIODSTART,
                data_payload:DONOTDESTROY::BOOLEAN AS DONOTDESTROY,
                CAST(data_payload:PUBLICID::TEXT AS VARCHAR(64)) AS PUBLICID,
                CAST(data_payload:ALTBILLINGACCOUNTNUMBER::TEXT AS VARCHAR(255)) AS ALTBILLINGACCOUNTNUMBER,
                TO_TIMESTAMP_NTZ(data_payload:WRITTENDATE::NUMBER/1000) AS WRITTENDATE,
                data_payload:TOTALCOSTRPT::NUMBER AS TOTALCOSTRPT,
                data_payload:TOTALCOSTRPT_CUR::NUMBER AS TOTALCOSTRPT_CUR,
                data_payload:WCLABOURHIRECODE_ICARE::NUMBER AS WCLABOURHIRECODE_ICARE,
                CAST(data_payload:PREMIUMADJUSTMENTREASON::TEXT AS VARCHAR(255)) AS PREMIUMADJUSTMENTREASON,
                data_payload:MOSTRECENTMODEL::BOOLEAN AS MOSTRECENTMODEL,
                data_payload:WCPREMIUMCALCODE_ICARE::NUMBER AS WCPREMIUMCALCODE_ICARE,
                data_payload:ALLOCATIONOFREMAINDER::NUMBER AS ALLOCATIONOFREMAINDER,
                data_payload:OVERRIDEBILLINGALLOCATION::BOOLEAN AS OVERRIDEBILLINGALLOCATION,
                data_payload:WCLEGACYPREMPAYMENTCODE_ICARE::NUMBER AS WCLEGACYPREMPAYMENTCODE_ICARE,
                data_payload:ARCHIVEFAILUREDETAILSID::NUMBER AS ARCHIVEFAILUREDETAILSID,
                TO_TIMESTAMP_NTZ(data_payload:MODELDATE::NUMBER/1000) AS MODELDATE,
                CAST(data_payload:INVOICESTREAMCODE::TEXT AS VARCHAR(255)) AS INVOICESTREAMCODE,
                CAST(data_payload:MODELNUMBERINDEX::TEXT AS VARCHAR(64)) AS MODELNUMBERINDEX,
                data_payload:BASESTATE::NUMBER AS BASESTATE,
                CAST(data_payload:MOSTRECENTMODELINDEX::TEXT AS VARCHAR(64)) AS MOSTRECENTMODELINDEX,
                data_payload:POLICYTYPE_ICARE::NUMBER AS POLICYTYPE_ICARE,
                data_payload:ARCHIVEPARTITION::NUMBER AS ARCHIVEPARTITION,
                data_payload:FAILEDOOSEEVALUATION::BOOLEAN AS FAILEDOOSEEVALUATION,
                data_payload:BRANCHNUMBER::NUMBER AS BRANCHNUMBER,
                data_payload:TRANSACTIONCOSTRPT::NUMBER AS TRANSACTIONCOSTRPT,
                data_payload:DEPOSITCOLLECTED::NUMBER AS DEPOSITCOLLECTED,
                data_payload:TRANSACTIONCOSTRPT_CUR::NUMBER AS TRANSACTIONCOSTRPT_CUR,
                data_payload:DEPOSITCOLLECTED_CUR::NUMBER AS DEPOSITCOLLECTED_CUR,
                data_payload:BASEDONID::NUMBER AS BASEDONID,
                TO_TIMESTAMP_NTZ(data_payload:ARCHIVEDATE::NUMBER/1000) AS ARCHIVEDATE,
                data_payload:BILLIMMEDIATELYPERCENTAGE::NUMBER AS BILLIMMEDIATELYPERCENTAGE,
                CAST(data_payload:QUOTECLONEORIGINALPERIOD::TEXT AS VARCHAR(255)) AS QUOTECLONEORIGINALPERIOD,
                data_payload:DEPOSITAMOUNT::NUMBER AS DEPOSITAMOUNT,
                CAST(data_payload:REASONLOWWAGES_ICARE::TEXT AS VARCHAR(60)) AS REASONLOWWAGES_ICARE,
                data_payload:PREFERREDCOVERAGECURRENCY::NUMBER AS PREFERREDCOVERAGECURRENCY,
                TO_TIMESTAMP_NTZ(data_payload:PERIODEND::NUMBER/1000) AS PERIODEND,
                data_payload:PREFERREDSETTLEMENTCURRENCY::NUMBER AS PREFERREDSETTLEMENTCURRENCY,
                TO_TIMESTAMP_NTZ(data_payload:BASEDONDATE::NUMBER/1000) AS BASEDONDATE,
                data_payload:TOTALPREMIUMRPT::NUMBER AS TOTALPREMIUMRPT,
                data_payload:TOTALPREMIUMRPT_CUR::NUMBER AS TOTALPREMIUMRPT_CUR,
                data_payload:VALIDREINSURANCE::BOOLEAN AS VALIDREINSURANCE,
                CAST(data_payload:SERIESCHECKINGPATTERNCODE::TEXT AS VARCHAR(64)) AS SERIESCHECKINGPATTERNCODE,
                data_payload:PNICONTACTDENORM::NUMBER AS PNICONTACTDENORM,
                data_payload:EDITLOCKED::BOOLEAN AS EDITLOCKED,
                TO_TIMESTAMP_NTZ(data_payload:RATEASOFDATE::NUMBER/1000) AS RATEASOFDATE,
                data_payload:JOBID::NUMBER AS JOBID,
                data_payload:UWCOMPANY::NUMBER AS UWCOMPANY,
                data_payload:ESTIMATEDPREMIUM::NUMBER AS ESTIMATEDPREMIUM,
                data_payload:PERIODID::NUMBER AS PERIODID,
                data_payload:ESTIMATEDPREMIUM_CUR::NUMBER AS ESTIMATEDPREMIUM_CUR,
                data_payload:ASSIGNEDRISK::BOOLEAN AS ASSIGNEDRISK,
                data_payload:TRANSACTIONPREMIUMRPT::NUMBER AS TRANSACTIONPREMIUMRPT,
                TO_TIMESTAMP_NTZ(data_payload:COMMENCEMENTDATE_ICARE::NUMBER/1000) AS COMMENCEMENTDATE_ICARE,
                data_payload:TEMPORARYCLONESTATUS::NUMBER AS TEMPORARYCLONESTATUS,
                data_payload:TRANSACTIONPREMIUMRPT_CUR::NUMBER AS TRANSACTIONPREMIUMRPT_CUR,
                CAST(data_payload:EXCLUDEREASON::TEXT AS VARCHAR(255)) AS EXCLUDEREASON,
                data_payload:ARCHIVEFAILUREID::NUMBER AS ARCHIVEFAILUREID,
                data_payload:FAILEDOOSEVALIDATION::BOOLEAN AS FAILEDOOSEVALIDATION,
                data_payload:RETIRED::NUMBER AS RETIRED,
                data_payload:PREEMPTED::BOOLEAN AS PREEMPTED,
                data_payload:FUTUREPERIODS::BOOLEAN AS FUTUREPERIODS,
                CAST(data_payload:PRIMARYINSUREDNAMEDENORM::TEXT AS VARCHAR(255)) AS PRIMARYINSUREDNAMEDENORM,
                data_payload:MODELNUMBER::NUMBER AS MODELNUMBER,
                data_payload:TERMNUMBER::NUMBER AS TERMNUMBER,
                data_payload:CLAIMSMGR_SCHEMEAGENT_ICARE::NUMBER AS CLAIMSMGR_SCHEMEAGENT_ICARE,
                data_payload:WAIVEDEPOSITCHANGE::BOOLEAN AS WAIVEDEPOSITCHANGE,
                data_payload:PRODUCERCODEOFRECORDID::NUMBER AS PRODUCERCODEOFRECORDID,
                TO_TIMESTAMP_NTZ(data_payload:CREATETIME::NUMBER/1000) AS CREATETIME,
                data_payload:ISOFFERINGSELECTED::BOOLEAN AS ISOFFERINGSELECTED,
                data_payload:POLICYID::NUMBER AS POLICYID,
                data_payload:EXCLUDEDFROMARCHIVE::BOOLEAN AS EXCLUDEDFROMARCHIVE,
                CAST(data_payload:ITCENTITLEMENT_ICARE::TEXT AS VARCHAR(60)) AS ITCENTITLEMENT_ICARE,
                data_payload:SIFUND_ICARE::NUMBER AS SIFUND_ICARE,
                data_payload:CUSTOMBILLING::BOOLEAN AS CUSTOMBILLING,
                data_payload:QUOTECLONESEQUENCENUMBER::NUMBER AS QUOTECLONESEQUENCENUMBER,
                data_payload:LOCKINGCOLUMN::NUMBER AS LOCKINGCOLUMN,
                data_payload:WCTERMTYPE_ICARE::NUMBER AS WCTERMTYPE_ICARE,
                data_payload:REFUNDCALCMETHOD::NUMBER AS REFUNDCALCMETHOD,
                data_payload:STATUS::NUMBER AS STATUS,
                data_payload:EMPLOYERCATEGORY_ICARE::NUMBER AS EMPLOYERCATEGORY_ICARE,
                data_payload:DEPOSITAMOUNT_CUR::NUMBER AS DEPOSITAMOUNT_CUR,
                CAST(data_payload:POLICYNUMBER::TEXT AS VARCHAR(40)) AS POLICYNUMBER,
                data_payload:GSTREGISTRATION_ICARE::BOOLEAN AS GSTREGISTRATION_ICARE,
                data_payload:LPRLARGECLAIMLIMIT_ICARE::NUMBER AS LPRLARGECLAIMLIMIT_ICARE,
                data_payload:SECURITYPERCENTAGE_ICARE::NUMBER AS SECURITYPERCENTAGE_ICARE,
                data_payload:ISRECALCULATE_ICARE::BOOLEAN AS ISRECALCULATE_ICARE,
                data_payload:EXTERNALTRANSACTION_ICARE::BOOLEAN AS EXTERNALTRANSACTION_ICARE,
                data_payload:LPRPRODUCTOPTION_ICARE::NUMBER AS LPRPRODUCTOPTION_ICARE,
                data_payload:CANCELONEXPIRY_ICARE::BOOLEAN AS CANCELONEXPIRY_ICARE,
                CAST(data_payload:BROKERAGENAME_ICARE::TEXT AS VARCHAR(255)) AS BROKERAGENAME_ICARE,
                CAST(data_payload:BROKERAGEID_ICARE::TEXT AS VARCHAR(255)) AS BROKERAGEID_ICARE,
                data_payload:GENERATEDQUOTEDOC_ICARE::BOOLEAN AS GENERATEDQUOTEDOC_ICARE,
                data_payload:INITBYGROUPRENEWALWF_ICARE::BOOLEAN AS INITBYGROUPRENEWALWF_ICARE,
                data_payload:REQUOTEDELTAFIELDS_ICARE::NUMBER AS REQUOTEDELTAFIELDS_ICARE,
                TO_TIMESTAMP_NTZ(data_payload:CONFIRMATIONDATE_ICARE::NUMBER/1000) AS CONFIRMATIONDATE_ICARE,
                data_payload:RENEWALSTATE_ICARE::NUMBER AS RENEWALSTATE_ICARE,
                data_payload:TAXSURCHARGESRPT_CUR::NUMBER AS TAXSURCHARGESRPT_CUR,
                data_payload:TAXSURCHARGESRPT::NUMBER AS TAXSURCHARGESRPT,
                data_payload:NILADJUSTLOADINGAPPLIED_ICARE::BOOLEAN AS NILADJUSTLOADINGAPPLIED_ICARE,
                data_payload:EXTERNALTRANSACTIONCSS_EXT::BOOLEAN AS EXTERNALTRANSACTIONCSS_EXT,
                data_payload:DRAFTRENEWALDOCTRIGGER_EXT::BOOLEAN AS DRAFTRENEWALDOCTRIGGER_EXT,
                data_payload:CSSRENEWALUPDATECOUNT_EXT::NUMBER AS CSSRENEWALUPDATECOUNT_EXT,
                data_payload:CSSUPDATECOUNT_EXT::NUMBER AS CSSUPDATECOUNT_EXT,
                data_payload:CSSERRORCORRECTIONCOUNT_EXT::NUMBER AS CSSERRORCORRECTIONCOUNT_EXT,
                data_payload:REFUNDRPA_EXT::BOOLEAN AS REFUNDRPA_EXT,
                data_payload:FRANCHISEDEDUCTIBLE_EXT::NUMBER AS FRANCHISEDEDUCTIBLE_EXT,
                data_payload:CONTRIBUTION_EXT::NUMBER AS CONTRIBUTION_EXT,
                data_payload:BUDGETNONBUDGET_EXT::BOOLEAN AS BUDGETNONBUDGET_EXT,
                data_payload:POLICYCATEGORY_EXT::NUMBER AS POLICYCATEGORY_EXT,
                CAST(data_payload:POLICYNAME_EXT::TEXT AS VARCHAR(255)) AS POLICYNAME_EXT,
                data_payload:DECLARATIONFORM_EXT::NUMBER AS DECLARATIONFORM_EXT,
                data_payload:FRANCHISEDEDUCTIBLELIMIT_EXT::NUMBER AS FRANCHISEDEDUCTIBLELIMIT_EXT,
                data_payload:CURRENTCONTRIBUTIONAMOUNT_EXT::NUMBER AS CURRENTCONTRIBUTIONAMOUNT_EXT,
                metadata_file_name,
                file_ingestion_timestamp
            FROM {{ source('gwpc', 'pc_policyperiod') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:validquote::BOOLEAN AS validquote,
                $1:locked::BOOLEAN AS locked,
                $1:editeffectivedate::TIMESTAMP_NTZ AS editeffectivedate,
                $1:cpacategory_icare::NUMBER AS cpacategory_icare,
                $1:archivestate::NUMBER AS archivestate,
                $1:archiveschemainfo::NUMBER AS archiveschemainfo,
                $1:locationautonumberseq::NUMBER AS locationautonumberseq,
                $1:updatetime::TIMESTAMP_NTZ AS updatetime,
                $1:id::NUMBER AS id,
                CAST($1:singlecheckingpatterncode::TEXT AS VARCHAR(64)) AS singlecheckingpatterncode,
                $1:billingmethod::NUMBER AS billingmethod,
                $1:createuserid::NUMBER AS createuserid,
                $1:allowgapsbefore::BOOLEAN AS allowgapsbefore,
                $1:quotehidden::BOOLEAN AS quotehidden,
                $1:beanversion::NUMBER AS beanversion,
                CAST($1:branchname::TEXT AS VARCHAR(255)) AS branchname,
                $1:islegacy_icare::BOOLEAN AS islegacy_icare,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:cancellationdate::TIMESTAMP_NTZ AS cancellationdate,
                $1:segment::NUMBER AS segment,
                CAST($1:primaryinsuredname::TEXT AS VARCHAR(255)) AS primaryinsuredname,
                $1:temporarybranch::BOOLEAN AS temporarybranch,
                $1:depositoverridepct::NUMBER AS depositoverridepct,
                $1:islegacymaxterm_icare::BOOLEAN AS islegacymaxterm_icare,
                $1:policytermid::NUMBER AS policytermid,
                CAST($1:legacypolicynumber_icare::TEXT AS VARCHAR(60)) AS legacypolicynumber_icare,
                $1:occupationtype_icare::NUMBER AS occupationtype_icare,
                $1:selectedtermtype::NUMBER AS selectedtermtype,
                $1:periodstart::TIMESTAMP_NTZ AS periodstart,
                $1:donotdestroy::BOOLEAN AS donotdestroy,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                CAST($1:altbillingaccountnumber::TEXT AS VARCHAR(255)) AS altbillingaccountnumber,
                $1:writtendate::TIMESTAMP_NTZ AS writtendate,
                $1:totalcostrpt::NUMBER AS totalcostrpt,
                $1:totalcostrpt_cur::NUMBER AS totalcostrpt_cur,
                $1:wclabourhirecode_icare::NUMBER AS wclabourhirecode_icare,
                CAST($1:premiumadjustmentreason::TEXT AS VARCHAR(255)) AS premiumadjustmentreason,
                $1:mostrecentmodel::BOOLEAN AS mostrecentmodel,
                $1:wcpremiumcalcode_icare::NUMBER AS wcpremiumcalcode_icare,
                $1:allocationofremainder::NUMBER AS allocationofremainder,
                $1:overridebillingallocation::BOOLEAN AS overridebillingallocation,
                $1:wclegacyprempaymentcode_icare::NUMBER AS wclegacyprempaymentcode_icare,
                $1:archivefailuredetailsid::NUMBER AS archivefailuredetailsid,
                $1:modeldate::TIMESTAMP_NTZ AS modeldate,
                CAST($1:invoicestreamcode::TEXT AS VARCHAR(255)) AS invoicestreamcode,
                CAST($1:modelnumberindex::TEXT AS VARCHAR(64)) AS modelnumberindex,
                $1:basestate::NUMBER AS basestate,
                CAST($1:mostrecentmodelindex::TEXT AS VARCHAR(64)) AS mostrecentmodelindex,
                $1:policytype_icare::NUMBER AS policytype_icare,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:failedooseevaluation::BOOLEAN AS failedooseevaluation,
                $1:branchnumber::NUMBER AS branchnumber,
                $1:transactioncostrpt::NUMBER AS transactioncostrpt,
                $1:depositcollected::NUMBER AS depositcollected,
                $1:transactioncostrpt_cur::NUMBER AS transactioncostrpt_cur,
                $1:depositcollected_cur::NUMBER AS depositcollected_cur,
                $1:basedonid::NUMBER AS basedonid,
                $1:archivedate::TIMESTAMP_NTZ AS archivedate,
                $1:billimmediatelypercentage::NUMBER AS billimmediatelypercentage,
                CAST($1:quotecloneoriginalperiod::TEXT AS VARCHAR(255)) AS quotecloneoriginalperiod,
                $1:depositamount::NUMBER AS depositamount,
                CAST($1:reasonlowwages_icare::TEXT AS VARCHAR(60)) AS reasonlowwages_icare,
                $1:preferredcoveragecurrency::NUMBER AS preferredcoveragecurrency,
                $1:periodend::TIMESTAMP_NTZ AS periodend,
                $1:preferredsettlementcurrency::NUMBER AS preferredsettlementcurrency,
                $1:basedondate::TIMESTAMP_NTZ AS basedondate,
                $1:totalpremiumrpt::NUMBER AS totalpremiumrpt,
                $1:totalpremiumrpt_cur::NUMBER AS totalpremiumrpt_cur,
                $1:validreinsurance::BOOLEAN AS validreinsurance,
                CAST($1:seriescheckingpatterncode::TEXT AS VARCHAR(64)) AS seriescheckingpatterncode,
                $1:pnicontactdenorm::NUMBER AS pnicontactdenorm,
                $1:editlocked::BOOLEAN AS editlocked,
                $1:rateasofdate::TIMESTAMP_NTZ AS rateasofdate,
                $1:jobid::NUMBER AS jobid,
                $1:uwcompany::NUMBER AS uwcompany,
                $1:estimatedpremium::NUMBER AS estimatedpremium,
                $1:periodid::NUMBER AS periodid,
                $1:estimatedpremium_cur::NUMBER AS estimatedpremium_cur,
                $1:assignedrisk::BOOLEAN AS assignedrisk,
                $1:transactionpremiumrpt::NUMBER AS transactionpremiumrpt,
                $1:commencementdate_icare::TIMESTAMP_NTZ AS commencementdate_icare,
                $1:temporaryclonestatus::NUMBER AS temporaryclonestatus,
                $1:transactionpremiumrpt_cur::NUMBER AS transactionpremiumrpt_cur,
                CAST($1:excludereason::TEXT AS VARCHAR(255)) AS excludereason,
                $1:archivefailureid::NUMBER AS archivefailureid,
                $1:failedoosevalidation::BOOLEAN AS failedoosevalidation,
                $1:retired::NUMBER AS retired,
                $1:preempted::BOOLEAN AS preempted,
                $1:futureperiods::BOOLEAN AS futureperiods,
                CAST($1:primaryinsurednamedenorm::TEXT AS VARCHAR(255)) AS primaryinsurednamedenorm,
                $1:modelnumber::NUMBER AS modelnumber,
                $1:termnumber::NUMBER AS termnumber,
                $1:claimsmgr_schemeagent_icare::NUMBER AS claimsmgr_schemeagent_icare,
                $1:waivedepositchange::BOOLEAN AS waivedepositchange,
                $1:producercodeofrecordid::NUMBER AS producercodeofrecordid,
                $1:createtime::TIMESTAMP_NTZ AS createtime,
                $1:isofferingselected::BOOLEAN AS isofferingselected,
                $1:policyid::NUMBER AS policyid,
                $1:excludedfromarchive::BOOLEAN AS excludedfromarchive,
                CAST($1:itcentitlement_icare::TEXT AS VARCHAR(60)) AS itcentitlement_icare,
                $1:sifund_icare::NUMBER AS sifund_icare,
                $1:custombilling::BOOLEAN AS custombilling,
                $1:quoteclonesequencenumber::NUMBER AS quoteclonesequencenumber,
                $1:lockingcolumn::NUMBER AS lockingcolumn,
                $1:wctermtype_icare::NUMBER AS wctermtype_icare,
                $1:refundcalcmethod::NUMBER AS refundcalcmethod,
                $1:status::NUMBER AS status,
                $1:employercategory_icare::NUMBER AS employercategory_icare,
                $1:depositamount_cur::NUMBER AS depositamount_cur,
                CAST($1:policynumber::TEXT AS VARCHAR(40)) AS policynumber,
                $1:gstregistration_icare::BOOLEAN AS gstregistration_icare,
                $1:lprlargeclaimlimit_icare::NUMBER AS lprlargeclaimlimit_icare,
                $1:securitypercentage_icare::NUMBER AS securitypercentage_icare,
                $1:isrecalculate_icare::BOOLEAN AS isrecalculate_icare,
                $1:externaltransaction_icare::BOOLEAN AS externaltransaction_icare,
                $1:lprproductoption_icare::NUMBER AS lprproductoption_icare,
                $1:cancelonexpiry_icare::BOOLEAN AS cancelonexpiry_icare,
                CAST($1:brokeragename_icare::TEXT AS VARCHAR(255)) AS brokeragename_icare,
                CAST($1:brokerageid_icare::TEXT AS VARCHAR(255)) AS brokerageid_icare,
                $1:generatedquotedoc_icare::BOOLEAN AS generatedquotedoc_icare,
                $1:initbygrouprenewalwf_icare::BOOLEAN AS initbygrouprenewalwf_icare,
                $1:requotedeltafields_icare::NUMBER AS requotedeltafields_icare,
                $1:confirmationdate_icare::TIMESTAMP_NTZ AS confirmationdate_icare,
                $1:renewalstate_icare::NUMBER AS renewalstate_icare,
                $1:taxsurchargesrpt_cur::NUMBER AS taxsurchargesrpt_cur,
                $1:taxsurchargesrpt::NUMBER AS taxsurchargesrpt,
                $1:niladjustloadingapplied_icare::BOOLEAN AS niladjustloadingapplied_icare,
                $1:externaltransactioncss_ext::BOOLEAN AS externaltransactioncss_ext,
                $1:draftrenewaldoctrigger_ext::BOOLEAN AS draftrenewaldoctrigger_ext,
                $1:cssrenewalupdatecount_ext::NUMBER AS cssrenewalupdatecount_ext,
                $1:cssupdatecount_ext::NUMBER AS cssupdatecount_ext,
                $1:csserrorcorrectioncount_ext::NUMBER AS csserrorcorrectioncount_ext,
                $1:refundrpa_ext::BOOLEAN AS refundrpa_ext,
                $1:franchisedeductible_ext::NUMBER AS franchisedeductible_ext,
                $1:contribution_ext::NUMBER AS contribution_ext,
                $1:budgetnonbudget_ext::BOOLEAN AS budgetnonbudget_ext,
                $1:policycategory_ext::NUMBER AS policycategory_ext,
                CAST($1:policyname_ext::TEXT AS VARCHAR(255)) AS policyname_ext,
                $1:declarationform_ext::NUMBER AS declarationform_ext,
                $1:franchisedeductiblelimit_ext::NUMBER AS franchisedeductiblelimit_ext,
                $1:currentcontributionamount_ext::NUMBER AS currentcontributionamount_ext,
                metadata_file_name,
                file_ingestion_timestamp
            FROM {{ source('gwpc', 'pc_policyperiod') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),
{#-
    Driving CTE Over 
-#}   
transformed AS (
    SELECT
        *
    FROM source_data
)
SELECT * FROM transformed