{#-

Project: Data Uplift Progran 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2025-11-18      0.0                             This Converts Parquet or AVRO Data in Variant Column in the RAW DB into Flattend Views

-#}   

{{ config(
    tags=["raw_gwcc"]
) }}


WITH source_data AS 
(

            SELECT
                $1:loadcommandid::TEXT AS loadcommandid,
                $1:previousgroupid::TEXT AS previousgroupid,
                $1:enddate::TIMESTAMP_NTZ AS enddate,
                $1:assignedbyuserid::TEXT AS assignedbyuserid,
                $1:externallyowned::BOOLEAN AS externallyowned,
                CAST($1:logicalname::TEXT AS VARCHAR(255)) AS logicalname,
                CAST($1:approvalrationale::TEXT AS VARCHAR(255)) AS approvalrationale,
                $1:previousqueueid::TEXT AS previousqueueid,
                CAST($1:documenttemplate::TEXT AS VARCHAR(255)) AS documenttemplate,
                $1:updatetime::TIMESTAMP_NTZ AS updatetime,
                CAST($1:emailtemplate::TEXT AS VARCHAR(255)) AS emailtemplate,
                $1:workflowid::TEXT AS workflowid,
                $1:dispute_icareid::TEXT AS dispute_icareid,
                $1:id::TEXT AS id,
                $1:matterid::TEXT AS matterid,
                $1:closeuserid::TEXT AS closeuserid,
                $1:wpiassessrecord_icare::TEXT AS wpiassessrecord_icare,
                $1:workcapacity_icareid::TEXT AS workcapacity_icareid,
                $1:createuserid::TEXT AS createuserid,
                $1:priority::TEXT AS priority,
                $1:closedate::TIMESTAMP_NTZ AS closedate,
                $1:beanversion::TEXT AS beanversion,
                $1:retired::TEXT AS retired,
                $1:validationlevel::TEXT AS validationlevel,
                CAST($1:subject::TEXT AS VARCHAR(255)) AS subject,
                $1:updateuserid::TEXT AS updateuserid,
                CAST($1:shortsubject::TEXT AS VARCHAR(10)) AS shortsubject,
                $1:bulkinvoiceid::TEXT AS bulkinvoiceid,
                $1:approved::BOOLEAN AS approved,
                $1:type::TEXT AS type,
                $1:targetdate::TIMESTAMP_NTZ AS targetdate,
                $1:autogenerated::BOOLEAN AS autogenerated,
                $1:escalationdate::TIMESTAMP_NTZ AS escalationdate,
                $1:externalownerccid::TEXT AS externalownerccid,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:lastvieweddate::TIMESTAMP_NTZ AS lastvieweddate,
                $1:createtime::TIMESTAMP_NTZ AS createtime,
                $1:activityclass::TEXT AS activityclass,
                CAST($1:command::TEXT AS VARCHAR(1333)) AS command,
                $1:assignedgroupid::TEXT AS assignedgroupid,
                $1:ocrinvoice::TEXT AS ocrinvoice,
                $1:servicerequestid::TEXT AS servicerequestid,
                $1:claimid::TEXT AS claimid,
                $1:reminderactivity_icareid::TEXT AS reminderactivity_icareid,
                $1:mandatory::BOOLEAN AS mandatory,
                $1:rehabplanid_ext::TEXT AS rehabplanid_ext,
                $1:previoususerid::TEXT AS previoususerid,
                $1:recurring::BOOLEAN AS recurring,
                $1:assignedqueueid::TEXT AS assignedqueueid,
                $1:transactionsetid::TEXT AS transactionsetid,
                $1:exposureid::TEXT AS exposureid,
                $1:archivepartition::TEXT AS archivepartition,
                $1:escalated::BOOLEAN AS escalated,
                $1:status::TEXT AS status,
                $1:importance::TEXT AS importance,
                $1:assigneduserid::TEXT AS assigneduserid,
                CAST($1:approvalissue::TEXT AS VARCHAR(5000)) AS approvalissue,
                $1:subtype::TEXT AS subtype,
                $1:assignmentdate::TIMESTAMP_NTZ AS assignmentdate,
                $1:activitypatternid::TEXT AS activitypatternid,
                CAST($1:description::TEXT AS VARCHAR(1333)) AS description,
                $1:assignmentstatus::TEXT AS assignmentstatus,
                $1:claimcontactid::TEXT AS claimcontactid,
                $1:employmentcapacity_icareid::TEXT AS employmentcapacity_icareid,
                $1:referencedate_ext::TIMESTAMP_NTZ AS referencedate_ext,
                $1:mspreferral_extid::TEXT AS mspreferral_extid,
                $1:recurrenceenddate_ext::TIMESTAMP_NTZ AS recurrenceenddate_ext,
                $1:recurrencestartdate_ext::TIMESTAMP_NTZ AS recurrencestartdate_ext,
                $1:isrecurring_ext::BOOLEAN AS isrecurring_ext,
                $1:recurringfrequency_ext::TEXT AS recurringfrequency_ext,
                $1:wpiactpeerreview_extid::TEXT AS wpiactpeerreview_extid,
                $1:customstatus_ext::TEXT AS customstatus_ext,
                CAST($1:withdrawreason_ext::TEXT AS VARCHAR(256)) AS withdrawreason_ext,
                $1:approvalstatus_ext::TEXT AS approvalstatus_ext,
                CAST($1:gwcbi___lsn::STRING AS VARCHAR(120)) as lsn,
                CAST($1:gwcbi___operation::STRING AS VARCHAR(2)) as row_operation,
                $1:gwcbi___cdc_tx_date::TIMESTAMP_LTZ as cdc_txn_date,
                $1:gwcbi___tx_id::TEXT  as txn_id,
                CAST($1:gwcbi___seqval_hex::STRING AS VARCHAR(120))  as seqval_hex,
                TO_TIMESTAMP($1:gwcbi___cdc_tx_date::TEXT / 1000) as update_timestamp,
                {{ dbt_utils.generate_surrogate_key([
                                'ID',
                        'seqval_hex'
                        ]) }} AS id_hash,
                metadata_file_name,
                file_ingestion_timestamp
            FROM {{ source('gwcc', 'cc_activity') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),
{#-
    Driving CTE Over 
-#}   
transformed AS (
    SELECT
        *
    FROM source_data
)
SELECT * FROM transformed