{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for ab_abcontact.
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                record_insertion_date: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDA goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    incremental_strategy='append',
    on_schema_change='append_new_columns',
    tags=["landing", "gwab", "contact_manager", "non_business_critical"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:TrustABNIsActive_icare::BOOLEAN AS trustabnisactive_icare,
                data_payload:SingleRemittancePerDay_icare::BOOLEAN AS singleremittanceperday_icare,
                data_payload:PreferredPaymentMethod_icare::NUMBER AS preferredpaymentmethod_icare,
                data_payload:FaxPhoneCountry::NUMBER AS faxphonecountry,
                CAST(data_payload:TaxID::TEXT AS VARCHAR(60)) AS taxid,
                CAST(data_payload:NameDenorm::TEXT AS VARCHAR(255)) AS namedenorm,
                TO_TIMESTAMP_TZ(data_payload:MedicareValidUntil_icare::NUMBER/1000) AS medicarevaliduntil_icare,
                data_payload:ApprovedPaymentMethod_icare::BOOLEAN AS approvedpaymentmethod_icare,
                data_payload:OrganisationType_icare::NUMBER AS organisationtype_icare,
                data_payload:ArchiveState::NUMBER AS archivestate,
                data_payload:ArchiveSchemaInfo::NUMBER AS archiveschemainfo,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                CAST(data_payload:AdjudicatorLicense::TEXT AS VARCHAR(30)) AS adjudicatorlicense,
                data_payload:ID::NUMBER AS id,
                data_payload:LawFirmSpecialty::NUMBER AS lawfirmspecialty,
                CAST(data_payload:LastNameDenorm::TEXT AS VARCHAR(80)) AS lastnamedenorm,
                CAST(data_payload:OktaID_icare::TEXT AS VARCHAR(20)) AS oktaid_icare,
                CAST(data_payload:LastName::TEXT AS VARCHAR(80)) AS lastname,
                data_payload:CreateUserID::NUMBER AS createuserid,
                CAST(data_payload:PayInfoUpdUserName_icare::TEXT AS VARCHAR(100)) AS payinfoupdusername_icare,
                CAST(data_payload:TradingName_icare::TEXT AS VARCHAR(100)) AS tradingname_icare,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:VenueType::NUMBER AS venuetype,
                CAST(data_payload:AutoTowingLicense::TEXT AS VARCHAR(30)) AS autotowinglicense,
                data_payload:BlockedVendor_icare::BOOLEAN AS blockedvendor_icare,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                CAST(data_payload:HomePhoneExtension::TEXT AS VARCHAR(60)) AS homephoneextension,
                CAST(data_payload:MedicareNumber_icare::TEXT AS VARCHAR(15)) AS medicarenumber_icare,
                data_payload:TrustRegisteredForGST_icare::BOOLEAN AS trustregisteredforgst_icare,
                data_payload:MinimumCriteriaVerified::BOOLEAN AS minimumcriteriaverified,
                CAST(data_payload:FirstName::TEXT AS VARCHAR(40)) AS firstname,
                CAST(data_payload:TrusteeName_icare::TEXT AS VARCHAR(256)) AS trusteename_icare,
                TO_TIMESTAMP_TZ(data_payload:W9ValidFrom::NUMBER/1000) AS w9validfrom,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                CAST(data_payload:Occupation::TEXT AS VARCHAR(100)) AS occupation,
                CAST(data_payload:CellPhone::TEXT AS VARCHAR(30)) AS cellphone,
                data_payload:PrimaryAddressID::NUMBER AS primaryaddressid,
                CAST(data_payload:TrustABN_icare::TEXT AS VARCHAR(60)) AS trustabn_icare,
                data_payload:Suffix::NUMBER AS suffix,
                data_payload:InterpreterRequired_icare::BOOLEAN AS interpreterrequired_icare,
                data_payload:ArchiveFailureDetailsID::NUMBER AS archivefailuredetailsid,
                CAST(data_payload:Website_icare::TEXT AS VARCHAR(255)) AS website_icare,
                data_payload:ABNIsActive_icare::BOOLEAN AS abnisactive_icare,
                CAST(data_payload:EmailAddress1::TEXT AS VARCHAR(80)) AS emailaddress1,
                CAST(data_payload:EmailAddress2::TEXT AS VARCHAR(80)) AS emailaddress2,
                data_payload:NumDependents::NUMBER AS numdependents,
                data_payload:TaxStatus::NUMBER AS taxstatus,
                TO_TIMESTAMP_TZ(data_payload:TFNDeclarationDate_icare::NUMBER/1000) AS tfndeclarationdate_icare,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                data_payload:UpdateScore::BOOLEAN AS updatescore,
                CAST(data_payload:NameKanji::TEXT AS VARCHAR(255)) AS namekanji,
                CAST(data_payload:ABSLanguageDescription_icare::TEXT AS VARCHAR(80)) AS abslanguagedescription_icare,
                TO_TIMESTAMP_TZ(data_payload:ArchiveDate::NUMBER/1000) AS archivedate,
                CAST(data_payload:FaxPhone::TEXT AS VARCHAR(30)) AS faxphone,
                data_payload:ABSLanguageCode_icare::NUMBER AS abslanguagecode_icare,
                CAST(data_payload:CellPhoneExtension::TEXT AS VARCHAR(60)) AS cellphoneextension,
                CAST(data_payload:EmployeeNumber::TEXT AS VARCHAR(255)) AS employeenumber,
                data_payload:DoctorSpecialty_icare::NUMBER AS doctorspecialty_icare,
                data_payload:Subtype::NUMBER AS subtype,
                TO_TIMESTAMP_TZ(data_payload:ABNValidated_icare::NUMBER/1000) AS abnvalidated_icare,
                CAST(data_payload:FormerName::TEXT AS VARCHAR(80)) AS formername,
                data_payload:VendorServicesLoadStatus::NUMBER AS vendorservicesloadstatus,
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                data_payload:Preferred::BOOLEAN AS preferred,
                data_payload:VendorType::NUMBER AS vendortype,
                data_payload:W9Received::BOOLEAN AS w9received,
                CAST(data_payload:SourceSystem_icare::TEXT AS VARCHAR(20)) AS sourcesystem_icare,
                CAST(data_payload:Particle::TEXT AS VARCHAR(40)) AS particle,
                CAST(data_payload:ACN_icare::TEXT AS VARCHAR(60)) AS acn_icare,
                CAST(data_payload:Name::TEXT AS VARCHAR(255)) AS name,
                data_payload:StateDenorm::NUMBER AS statedenorm,
                CAST(data_payload:MedicalLicense::TEXT AS VARCHAR(30)) AS medicallicense,
                CAST(data_payload:VendorNumber::TEXT AS VARCHAR(60)) AS vendornumber,
                data_payload:Prefix::NUMBER AS prefix,
                data_payload:PreferredCurrency::NUMBER AS preferredcurrency,
                data_payload:Score::NUMBER AS score,
                data_payload:DoNotDestroy::BOOLEAN AS donotdestroy,
                TO_TIMESTAMP_TZ(data_payload:W9ValidTo::NUMBER/1000) AS w9validto,
                CAST(data_payload:LinkID::TEXT AS VARCHAR(64)) AS linkid,
                CAST(data_payload:LastNameKanji::TEXT AS VARCHAR(80)) AS lastnamekanji,
                data_payload:TaxFilingStatus::NUMBER AS taxfilingstatus,
                CAST(data_payload:WithholdingRate AS NUMBER(4,1)) AS withholdingrate,
                TO_TIMESTAMP_TZ(data_payload:CommencementDate_icare::NUMBER/1000) AS commencementdate_icare,
                CAST(data_payload:TrustName_icare::TEXT AS VARCHAR(255)) AS trustname_icare,
                CAST(data_payload:ExcludeReason::TEXT AS VARCHAR(255)) AS excludereason,
                data_payload:LegalSpecialty_icare::NUMBER AS legalspecialty_icare,
                CAST(data_payload:MiddleName::TEXT AS VARCHAR(40)) AS middlename,
                CAST(data_payload:AttorneyLicense::TEXT AS VARCHAR(30)) AS attorneylicense,
                data_payload:VendorAvailability::NUMBER AS vendoravailability,
                data_payload:ArchiveFailureID::NUMBER AS archivefailureid,
                CAST(data_payload:ABN_icare::TEXT AS VARCHAR(60)) AS abn_icare,
                data_payload:Retired::NUMBER AS retired,
                data_payload:MedicalOrgSpecialty::NUMBER AS medicalorgspecialty,
                data_payload:ValidationLevel::NUMBER AS validationlevel,
                data_payload:PrimaryPhone::NUMBER AS primaryphone,
                data_payload:TrusteeType_icare::NUMBER AS trusteetype_icare,
                TO_TIMESTAMP_TZ(data_payload:W9ReceivedDate::NUMBER/1000) AS w9receiveddate,
                CAST(data_payload:MedicareIRN_icare::TEXT AS VARCHAR(2)) AS medicareirn_icare,
                CAST(data_payload:CRMVersion_icare::TEXT AS VARCHAR(18)) AS crmversion_icare,
                CAST(data_payload:FirstNameDenorm::TEXT AS VARCHAR(40)) AS firstnamedenorm,
                data_payload:AdjudicativeDomain::NUMBER AS adjudicativedomain,
                CAST(data_payload:FirstNameKanji::TEXT AS VARCHAR(40)) AS firstnamekanji,
                data_payload:DoctorSpecialty::NUMBER AS doctorspecialty,
                data_payload:SmsNotification_icare::BOOLEAN AS smsnotification_icare,
                CAST(data_payload:Notes::TEXT AS VARCHAR(16777216)) AS notes,
                data_payload:Gender::NUMBER AS gender,
                data_payload:NumDependentsU18::NUMBER AS numdependentsu18,
                CAST(data_payload:AutoRepairLicense::TEXT AS VARCHAR(30)) AS autorepairlicense,
                CAST(data_payload:CRMSharedFieldsHash_icare::TEXT AS VARCHAR(64)) AS crmsharedfieldshash_icare,
                data_payload:HomePhoneCountry::NUMBER AS homephonecountry,
                data_payload:MedicalSpecialty_icare::NUMBER AS medicalspecialty_icare,
                CAST(data_payload:SpatialPointDenorm::TEXT AS VARCHAR(16777216)) AS spatialpointdenorm,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                data_payload:CellPhoneCountry::NUMBER AS cellphonecountry,
                CAST(data_payload:LicenseNumber::TEXT AS VARCHAR(20)) AS licensenumber,
                CAST(data_payload:KeywordKanji::TEXT AS VARCHAR(255)) AS keywordkanji,
                data_payload:ExcludedFromArchive::BOOLEAN AS excludedfromarchive,
                data_payload:CountryDenorm::NUMBER AS countrydenorm,
                TO_TIMESTAMP_TZ(data_payload:TrustABNValidated_icare::NUMBER/1000) AS trustabnvalidated_icare,
                data_payload:AggregateRemittance_icare::BOOLEAN AS aggregateremittance_icare,
                TO_TIMESTAMP_TZ(data_payload:DateOfBirth::NUMBER/1000) AS dateofbirth,
                data_payload:AttorneySpecialty_icare::NUMBER AS attorneyspecialty_icare,
                data_payload:RegisteredForGST_icare::BOOLEAN AS registeredforgst_icare,
                data_payload:CommunicationPreferences_icare::NUMBER AS communicationpreferences_icare,
                data_payload:NumDependentsU25::NUMBER AS numdependentsu25,
                data_payload:AttorneySpecialty::NUMBER AS attorneyspecialty,
                CAST(data_payload:WorkPhoneExtension::TEXT AS VARCHAR(60)) AS workphoneextension,
                data_payload:MaritalStatus::NUMBER AS maritalstatus,
                CAST(data_payload:KeywordDenorm::TEXT AS VARCHAR(255)) AS keyworddenorm,
                CAST(data_payload:CityDenorm::TEXT AS VARCHAR(40)) AS citydenorm,
                CAST(data_payload:Keyword::TEXT AS VARCHAR(255)) AS keyword,
                CAST(data_payload:FaxPhoneExtension::TEXT AS VARCHAR(60)) AS faxphoneextension,
                data_payload:CreateStatus::NUMBER AS createstatus,
                CAST(data_payload:HomePhone::TEXT AS VARCHAR(30)) AS homephone,
                data_payload:LicenseState::NUMBER AS licensestate,
                CAST(data_payload:PostalCodeDenorm::TEXT AS VARCHAR(20)) AS postalcodedenorm,
                data_payload:WorkPhoneCountry::NUMBER AS workphonecountry,
                CAST(data_payload:WorkPhone::TEXT AS VARCHAR(30)) AS workphone,
                CAST(data_payload:VendorUnavailableMessage::TEXT AS VARCHAR(255)) AS vendorunavailablemessage,
                CAST(data_payload:CoreSharedFieldsHash_icare::TEXT AS VARCHAR(64)) AS coresharedfieldshash_icare,
                data_payload:WageRSA_icare::NUMBER AS wagersa_icare,
                CAST(data_payload:ProviderID_Ext::TEXT AS VARCHAR(40)) AS providerid_ext,
                data_payload:BankApproveWithEdit_Ext::BOOLEAN AS bankapprovewithedit_ext,
                data_payload:DPPlatform_Ext::NUMBER AS dpplatform_ext,
                data_payload:ContactSecurityType_Ext::NUMBER AS contactsecuritytype_ext,
                data_payload:CellPhoneCountry_Ext::NUMBER AS cellphonecountry_ext,
                CAST(data_payload:OrganisationPartyID_Ext::TEXT AS VARCHAR(30)) AS organisationpartyid_ext,
                TO_TIMESTAMP_TZ(data_payload:CRMLastModifiedDate_Ext::NUMBER/1000) AS crmlastmodifieddate_ext,
                CAST(data_payload:CRMLastModifiedById_Ext::TEXT AS VARCHAR(80)) AS crmlastmodifiedbyid_ext,
                CAST(data_payload:Status_Ext::TEXT AS VARCHAR(30)) AS status_ext,
                CAST(data_payload:CellPhoneExtension_Ext::TEXT AS VARCHAR(60)) AS cellphoneextension_ext,
                TO_TIMESTAMP_TZ(data_payload:CRMCreatedDate_Ext::NUMBER/1000) AS crmcreateddate_ext,
                CAST(data_payload:PartyID_Ext::TEXT AS VARCHAR(30)) AS partyid_ext,
                TO_TIMESTAMP_TZ(data_payload:ABNValidationTimestamp_Ext::NUMBER/1000) AS abnvalidationtimestamp_ext,
                CAST(data_payload:CellPhone_Ext::TEXT AS VARCHAR(30)) AS cellphone_ext,
                CAST(data_payload:CRMLastModifiedByName_Ext::TEXT AS VARCHAR(255)) AS crmlastmodifiedbyname_ext,
                data_payload:ProviderCategory_Ext::NUMBER AS providercategory_ext,
                data_payload:ABNExempt_Ext::BOOLEAN AS abnexempt_ext,
                CAST(data_payload:CreationSource_Ext::TEXT AS VARCHAR(20)) AS creationsource_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS VARCHAR(300)) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'AVRO' as file_type,
                'GWAB' as source_system
            FROM {{ source('gwab', 'ab_abcontact') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:trustabnisactive_icare::BOOLEAN AS trustabnisactive_icare,
                $1:singleremittanceperday_icare::BOOLEAN AS singleremittanceperday_icare,
                $1:preferredpaymentmethod_icare::NUMBER AS preferredpaymentmethod_icare,
                $1:faxphonecountry::NUMBER AS faxphonecountry,
                CAST($1:taxid::TEXT AS VARCHAR(60)) AS taxid,
                CAST($1:namedenorm::TEXT AS VARCHAR(255)) AS namedenorm,
                $1:medicarevaliduntil_icare::TIMESTAMP_TZ AS medicarevaliduntil_icare,
                $1:approvedpaymentmethod_icare::BOOLEAN AS approvedpaymentmethod_icare,
                $1:organisationtype_icare::NUMBER AS organisationtype_icare,
                $1:archivestate::NUMBER AS archivestate,
                $1:archiveschemainfo::NUMBER AS archiveschemainfo,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                CAST($1:adjudicatorlicense::TEXT AS VARCHAR(30)) AS adjudicatorlicense,
                $1:id::NUMBER AS id,
                $1:lawfirmspecialty::NUMBER AS lawfirmspecialty,
                CAST($1:lastnamedenorm::TEXT AS VARCHAR(80)) AS lastnamedenorm,
                CAST($1:oktaid_icare::TEXT AS VARCHAR(20)) AS oktaid_icare,
                CAST($1:lastname::TEXT AS VARCHAR(80)) AS lastname,
                $1:createuserid::NUMBER AS createuserid,
                CAST($1:payinfoupdusername_icare::TEXT AS VARCHAR(100)) AS payinfoupdusername_icare,
                CAST($1:tradingname_icare::TEXT AS VARCHAR(100)) AS tradingname_icare,
                $1:beanversion::NUMBER AS beanversion,
                $1:venuetype::NUMBER AS venuetype,
                CAST($1:autotowinglicense::TEXT AS VARCHAR(30)) AS autotowinglicense,
                $1:blockedvendor_icare::BOOLEAN AS blockedvendor_icare,
                $1:updateuserid::NUMBER AS updateuserid,
                CAST($1:homephoneextension::TEXT AS VARCHAR(60)) AS homephoneextension,
                CAST($1:medicarenumber_icare::TEXT AS VARCHAR(15)) AS medicarenumber_icare,
                $1:trustregisteredforgst_icare::BOOLEAN AS trustregisteredforgst_icare,
                $1:minimumcriteriaverified::BOOLEAN AS minimumcriteriaverified,
                CAST($1:firstname::TEXT AS VARCHAR(40)) AS firstname,
                CAST($1:trusteename_icare::TEXT AS VARCHAR(256)) AS trusteename_icare,
                $1:w9validfrom::TIMESTAMP_TZ AS w9validfrom,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                CAST($1:occupation::TEXT AS VARCHAR(100)) AS occupation,
                CAST($1:cellphone::TEXT AS VARCHAR(30)) AS cellphone,
                $1:primaryaddressid::NUMBER AS primaryaddressid,
                CAST($1:trustabn_icare::TEXT AS VARCHAR(60)) AS trustabn_icare,
                $1:suffix::NUMBER AS suffix,
                $1:interpreterrequired_icare::BOOLEAN AS interpreterrequired_icare,
                $1:archivefailuredetailsid::NUMBER AS archivefailuredetailsid,
                CAST($1:website_icare::TEXT AS VARCHAR(255)) AS website_icare,
                $1:abnisactive_icare::BOOLEAN AS abnisactive_icare,
                CAST($1:emailaddress1::TEXT AS VARCHAR(80)) AS emailaddress1,
                CAST($1:emailaddress2::TEXT AS VARCHAR(80)) AS emailaddress2,
                $1:numdependents::NUMBER AS numdependents,
                $1:taxstatus::NUMBER AS taxstatus,
                $1:tfndeclarationdate_icare::TIMESTAMP_TZ AS tfndeclarationdate_icare,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:updatescore::BOOLEAN AS updatescore,
                CAST($1:namekanji::TEXT AS VARCHAR(255)) AS namekanji,
                CAST($1:abslanguagedescription_icare::TEXT AS VARCHAR(80)) AS abslanguagedescription_icare,
                $1:archivedate::TIMESTAMP_TZ AS archivedate,
                CAST($1:faxphone::TEXT AS VARCHAR(30)) AS faxphone,
                $1:abslanguagecode_icare::NUMBER AS abslanguagecode_icare,
                CAST($1:cellphoneextension::TEXT AS VARCHAR(60)) AS cellphoneextension,
                CAST($1:employeenumber::TEXT AS VARCHAR(255)) AS employeenumber,
                $1:doctorspecialty_icare::NUMBER AS doctorspecialty_icare,
                $1:subtype::NUMBER AS subtype,
                $1:abnvalidated_icare::TIMESTAMP_TZ AS abnvalidated_icare,
                CAST($1:formername::TEXT AS VARCHAR(80)) AS formername,
                $1:vendorservicesloadstatus::NUMBER AS vendorservicesloadstatus,
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:preferred::BOOLEAN AS preferred,
                $1:vendortype::NUMBER AS vendortype,
                $1:w9received::BOOLEAN AS w9received,
                CAST($1:sourcesystem_icare::TEXT AS VARCHAR(20)) AS sourcesystem_icare,
                CAST($1:particle::TEXT AS VARCHAR(40)) AS particle,
                CAST($1:acn_icare::TEXT AS VARCHAR(60)) AS acn_icare,
                CAST($1:name::TEXT AS VARCHAR(255)) AS name,
                $1:statedenorm::NUMBER AS statedenorm,
                CAST($1:medicallicense::TEXT AS VARCHAR(30)) AS medicallicense,
                CAST($1:vendornumber::TEXT AS VARCHAR(60)) AS vendornumber,
                $1:prefix::NUMBER AS prefix,
                $1:preferredcurrency::NUMBER AS preferredcurrency,
                $1:score::NUMBER AS score,
                $1:donotdestroy::BOOLEAN AS donotdestroy,
                $1:w9validto::TIMESTAMP_TZ AS w9validto,
                CAST($1:linkid::TEXT AS VARCHAR(64)) AS linkid,
                CAST($1:lastnamekanji::TEXT AS VARCHAR(80)) AS lastnamekanji,
                $1:taxfilingstatus::NUMBER AS taxfilingstatus,
                CAST($1:withholdingrate AS NUMBER(4,1)) AS withholdingrate,
                $1:commencementdate_icare::TIMESTAMP_TZ AS commencementdate_icare,
                CAST($1:trustname_icare::TEXT AS VARCHAR(255)) AS trustname_icare,
                CAST($1:excludereason::TEXT AS VARCHAR(255)) AS excludereason,
                $1:legalspecialty_icare::NUMBER AS legalspecialty_icare,
                CAST($1:middlename::TEXT AS VARCHAR(40)) AS middlename,
                CAST($1:attorneylicense::TEXT AS VARCHAR(30)) AS attorneylicense,
                $1:vendoravailability::NUMBER AS vendoravailability,
                $1:archivefailureid::NUMBER AS archivefailureid,
                CAST($1:abn_icare::TEXT AS VARCHAR(60)) AS abn_icare,
                $1:retired::NUMBER AS retired,
                $1:medicalorgspecialty::NUMBER AS medicalorgspecialty,
                $1:validationlevel::NUMBER AS validationlevel,
                $1:primaryphone::NUMBER AS primaryphone,
                $1:trusteetype_icare::NUMBER AS trusteetype_icare,
                $1:w9receiveddate::TIMESTAMP_TZ AS w9receiveddate,
                CAST($1:medicareirn_icare::TEXT AS VARCHAR(2)) AS medicareirn_icare,
                CAST($1:crmversion_icare::TEXT AS VARCHAR(18)) AS crmversion_icare,
                CAST($1:firstnamedenorm::TEXT AS VARCHAR(40)) AS firstnamedenorm,
                $1:adjudicativedomain::NUMBER AS adjudicativedomain,
                CAST($1:firstnamekanji::TEXT AS VARCHAR(40)) AS firstnamekanji,
                $1:doctorspecialty::NUMBER AS doctorspecialty,
                $1:smsnotification_icare::BOOLEAN AS smsnotification_icare,
                CAST($1:notes::TEXT AS VARCHAR(16777216)) AS notes,
                $1:gender::NUMBER AS gender,
                $1:numdependentsu18::NUMBER AS numdependentsu18,
                CAST($1:autorepairlicense::TEXT AS VARCHAR(30)) AS autorepairlicense,
                CAST($1:crmsharedfieldshash_icare::TEXT AS VARCHAR(64)) AS crmsharedfieldshash_icare,
                $1:homephonecountry::NUMBER AS homephonecountry,
                $1:medicalspecialty_icare::NUMBER AS medicalspecialty_icare,
                CAST($1:spatialpointdenorm::TEXT AS VARCHAR(16777216)) AS spatialpointdenorm,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:cellphonecountry::NUMBER AS cellphonecountry,
                CAST($1:licensenumber::TEXT AS VARCHAR(20)) AS licensenumber,
                CAST($1:keywordkanji::TEXT AS VARCHAR(255)) AS keywordkanji,
                $1:excludedfromarchive::BOOLEAN AS excludedfromarchive,
                $1:countrydenorm::NUMBER AS countrydenorm,
                $1:trustabnvalidated_icare::TIMESTAMP_TZ AS trustabnvalidated_icare,
                $1:aggregateremittance_icare::BOOLEAN AS aggregateremittance_icare,
                $1:dateofbirth::TIMESTAMP_TZ AS dateofbirth,
                $1:attorneyspecialty_icare::NUMBER AS attorneyspecialty_icare,
                $1:registeredforgst_icare::BOOLEAN AS registeredforgst_icare,
                $1:communicationpreferences_icare::NUMBER AS communicationpreferences_icare,
                $1:numdependentsu25::NUMBER AS numdependentsu25,
                $1:attorneyspecialty::NUMBER AS attorneyspecialty,
                CAST($1:workphoneextension::TEXT AS VARCHAR(60)) AS workphoneextension,
                $1:maritalstatus::NUMBER AS maritalstatus,
                CAST($1:keyworddenorm::TEXT AS VARCHAR(255)) AS keyworddenorm,
                CAST($1:citydenorm::TEXT AS VARCHAR(40)) AS citydenorm,
                CAST($1:keyword::TEXT AS VARCHAR(255)) AS keyword,
                CAST($1:faxphoneextension::TEXT AS VARCHAR(60)) AS faxphoneextension,
                $1:createstatus::NUMBER AS createstatus,
                CAST($1:homephone::TEXT AS VARCHAR(30)) AS homephone,
                $1:licensestate::NUMBER AS licensestate,
                CAST($1:postalcodedenorm::TEXT AS VARCHAR(20)) AS postalcodedenorm,
                $1:workphonecountry::NUMBER AS workphonecountry,
                CAST($1:workphone::TEXT AS VARCHAR(30)) AS workphone,
                CAST($1:vendorunavailablemessage::TEXT AS VARCHAR(255)) AS vendorunavailablemessage,
                CAST($1:coresharedfieldshash_icare::TEXT AS VARCHAR(64)) AS coresharedfieldshash_icare,
                $1:wagersa_icare::NUMBER AS wagersa_icare,
                CAST($1:providerid_ext::TEXT AS VARCHAR(40)) AS providerid_ext,
                $1:bankapprovewithedit_ext::BOOLEAN AS bankapprovewithedit_ext,
                $1:dpplatform_ext::NUMBER AS dpplatform_ext,
                $1:contactsecuritytype_ext::NUMBER AS contactsecuritytype_ext,
                $1:cellphonecountry_ext::NUMBER AS cellphonecountry_ext,
                CAST($1:organisationpartyid_ext::TEXT AS VARCHAR(30)) AS organisationpartyid_ext,
                $1:crmlastmodifieddate_ext::TIMESTAMP_TZ AS crmlastmodifieddate_ext,
                CAST($1:crmlastmodifiedbyid_ext::TEXT AS VARCHAR(80)) AS crmlastmodifiedbyid_ext,
                CAST($1:status_ext::TEXT AS VARCHAR(30)) AS status_ext,
                CAST($1:cellphoneextension_ext::TEXT AS VARCHAR(60)) AS cellphoneextension_ext,
                $1:crmcreateddate_ext::TIMESTAMP_TZ AS crmcreateddate_ext,
                CAST($1:partyid_ext::TEXT AS VARCHAR(30)) AS partyid_ext,
                $1:abnvalidationtimestamp_ext::TIMESTAMP_TZ AS abnvalidationtimestamp_ext,
                CAST($1:cellphone_ext::TEXT AS VARCHAR(30)) AS cellphone_ext,
                CAST($1:crmlastmodifiedbyname_ext::TEXT AS VARCHAR(255)) AS crmlastmodifiedbyname_ext,
                $1:providercategory_ext::NUMBER AS providercategory_ext,
                $1:abnexempt_ext::BOOLEAN AS abnexempt_ext,
                CAST($1:creationsource_ext::TEXT AS VARCHAR(20)) AS creationsource_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::VARCHAR(300) as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'PARQUET' as file_type,
                'GWAB' as source_system
            FROM {{ source('gwab', 'ab_abcontact') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS abcontact_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'trustabnisactive_icare',
                        'singleremittanceperday_icare',
                        'preferredpaymentmethod_icare',
                        'faxphonecountry',
                        'taxid',
                        'namedenorm',
                        'medicarevaliduntil_icare',
                        'approvedpaymentmethod_icare',
                        'organisationtype_icare',
                        'archivestate',
                        'archiveschemainfo',
                        'updatetime',
                        'adjudicatorlicense',
                        'lawfirmspecialty',
                        'lastnamedenorm',
                        'oktaid_icare',
                        'lastname',
                        'createuserid',
                        'payinfoupdusername_icare',
                        'tradingname_icare',
                        'beanversion',
                        'venuetype',
                        'autotowinglicense',
                        'blockedvendor_icare',
                        'updateuserid',
                        'homephoneextension',
                        'medicarenumber_icare',
                        'trustregisteredforgst_icare',
                        'minimumcriteriaverified',
                        'firstname',
                        'trusteename_icare',
                        'w9validfrom',
                        'publicid',
                        'occupation',
                        'cellphone',
                        'primaryaddressid',
                        'trustabn_icare',
                        'suffix',
                        'interpreterrequired_icare',
                        'archivefailuredetailsid',
                        'website_icare',
                        'abnisactive_icare',
                        'emailaddress1',
                        'emailaddress2',
                        'numdependents',
                        'taxstatus',
                        'tfndeclarationdate_icare',
                        'archivepartition',
                        'updatescore',
                        'namekanji',
                        'abslanguagedescription_icare',
                        'archivedate',
                        'faxphone',
                        'abslanguagecode_icare',
                        'cellphoneextension',
                        'employeenumber',
                        'doctorspecialty_icare',
                        'subtype',
                        'abnvalidated_icare',
                        'formername',
                        'vendorservicesloadstatus',
                        'loadcommandid',
                        'preferred',
                        'vendortype',
                        'w9received',
                        'sourcesystem_icare',
                        'particle',
                        'acn_icare',
                        'name',
                        'statedenorm',
                        'medicallicense',
                        'vendornumber',
                        'prefix',
                        'preferredcurrency',
                        'score',
                        'donotdestroy',
                        'w9validto',
                        'linkid',
                        'lastnamekanji',
                        'taxfilingstatus',
                        'withholdingrate',
                        'commencementdate_icare',
                        'trustname_icare',
                        'excludereason',
                        'legalspecialty_icare',
                        'middlename',
                        'attorneylicense',
                        'vendoravailability',
                        'archivefailureid',
                        'abn_icare',
                        'retired',
                        'medicalorgspecialty',
                        'validationlevel',
                        'primaryphone',
                        'trusteetype_icare',
                        'w9receiveddate',
                        'medicareirn_icare',
                        'crmversion_icare',
                        'firstnamedenorm',
                        'adjudicativedomain',
                        'firstnamekanji',
                        'doctorspecialty',
                        'smsnotification_icare',
                        'notes',
                        'gender',
                        'numdependentsu18',
                        'autorepairlicense',
                        'crmsharedfieldshash_icare',
                        'homephonecountry',
                        'medicalspecialty_icare',
                        'spatialpointdenorm',
                        'createtime',
                        'cellphonecountry',
                        'licensenumber',
                        'keywordkanji',
                        'excludedfromarchive',
                        'countrydenorm',
                        'trustabnvalidated_icare',
                        'aggregateremittance_icare',
                        'dateofbirth',
                        'attorneyspecialty_icare',
                        'registeredforgst_icare',
                        'communicationpreferences_icare',
                        'numdependentsu25',
                        'attorneyspecialty',
                        'workphoneextension',
                        'maritalstatus',
                        'keyworddenorm',
                        'citydenorm',
                        'keyword',
                        'faxphoneextension',
                        'createstatus',
                        'homephone',
                        'licensestate',
                        'postalcodedenorm',
                        'workphonecountry',
                        'workphone',
                        'vendorunavailablemessage',
                        'coresharedfieldshash_icare',
                        'wagersa_icare',
                        'providerid_ext',
                        'bankapprovewithedit_ext',
                        'dpplatform_ext',
                        'contactsecuritytype_ext',
                        'cellphonecountry_ext',
                        'organisationpartyid_ext',
                        'crmlastmodifieddate_ext',
                        'crmlastmodifiedbyid_ext',
                        'status_ext',
                        'cellphoneextension_ext',
                        'crmcreateddate_ext',
                        'partyid_ext',
                        'abnvalidationtimestamp_ext',
                        'cellphone_ext',
                        'crmlastmodifiedbyname_ext',
                        'providercategory_ext',
                        'abnexempt_ext',
                        'creationsource_ext'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
    WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}
    ORDER BY record_insertion_date
