{% snapshot bc_activity_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026-01-01      0.0                             SCD Type 2 snapshot for bc_activity.
                                                Source: ref('stg_raw_bc_activity')
                                                unique_key: activity_sk (surrogate on PK 'id')
                                                check_cols: ['hash_key'] (surrogate on all business cols excl PK)
                                                hard_deletes: new_record (inserts dbt_is_deleted=True row)
                                                No code change required when PARQUET CDC goes live.
-#}

{{ config(
    target_schema='gwbc',
    unique_key='activity_sk',
    strategy='check',
    alias='bc_activity',
    check_cols=['hash_key'],
    hard_deletes='new_record',
    tags=['snapshot', 'billing_centre', 'non_business_critical', 'bc_activity']
) }}

SELECT
    activity_sk,
    hash_key,
    loadcommandid,
    previousgroupid,
    accountid,
    enddate,
    assignedbyuserid,
    externallyowned,
    fundstransferid,
    logicalname,
    approvalrationale,
    documenttemplate,
    previousqueueid,
    emailtemplate,
    updatetime,
    writeoffreversalid,
    workflowid,
    id,
    chargereversalid,
    closeuserid,
    troubleticketid,
    creditreversalid,
    createuserid,
    priority,
    closedate,
    beanversion,
    retired,
    validationlevel,
    subject,
    accountcontactid,
    updateuserid,
    shortsubject,
    approved,
    delinquencyprocessid,
    negativewriteoffrevid,
    advancecmsnpaymentid,
    type,
    bonuscmsnpaymentid,
    targetdate,
    negativewriteoffid,
    autogenerated,
    escalationdate,
    publicid,
    lastvieweddate,
    activityclass,
    createtime,
    writeoffid,
    command,
    assignedgroupid,
    policyperiodid,
    creditid,
    mandatory,
    recurring,
    previoususerid,
    assignedqueueid,
    fundstransferreversalid,
    archivepartition,
    escalated,
    status,
    assigneduserid,
    producerpayabletransferid,
    approvalissue,
    subtype,
    assignmentdate,
    disbursementid,
    activitypatternid,
    description,
    assignmentstatus,
    producerid,
    waiverchargepatterns_icare,
    contactid,
    'GWBC' AS source_system,
    gwcbi_connector_ts_ms,
    gwcbi_lsn,
    gwcbi_operation,
    gwcbi_payload_ts_ms,
    gwcbi_seqval,
    gwcbi_seqval_hex,
    gwcbi_tx_id,
    metadata_file_name,
    file_ingestion_timestamp
FROM {{ ref('stg_raw_bc_activity') }}

{% endsnapshot %}