{% snapshot bc_contact_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026-01-01      0.0                             SCD Type 2 snapshot for bc_contact.
                                                Source: ref('stg_raw_bc_contact')
                                                unique_key: contact_sk (surrogate on PK 'id')
                                                check_cols: ['hash_key'] (surrogate on all business cols excl PK)
                                                hard_deletes: new_record (inserts dbt_is_deleted=True row)
                                                No code change required when PARQUET CDC goes live.
-#}

{{ config(
    target_schema='gwbc',
    unique_key='contact_sk',
    strategy='check',
    alias='bc_contact',
    check_cols=['hash_key'],
    hard_deletes='new_record',
    tags=['snapshot', 'billing_centre', 'non_business_critical', 'bc_contact']
) }}

SELECT
    contact_sk,
    hash_key,
    loadcommandid,
    preferred,
    vendortype,
    faxphonecountry,
    particle,
    taxid,
    namedenorm,
    name,
    startdate_icare,
    vendornumber,
    prefix,
    score,
    preferredcurrency,
    lastnamekanji,
    taxfilingstatus,
    updatetime,
    id,
    withholdingrate,
    lastnamedenorm,
    middlename,
    lastname,
    createuserid,
    externalid,
    beanversion,
    venuetype,
    retired,
    validationlevel,
    primaryphone,
    updateuserid,
    homephoneextension,
    firstnamedenorm,
    firstname,
    firstnamekanji,
    gender,
    notes,
    numdependentsu18,
    enddate_icare,
    publicid,
    homephonecountry,
    createtime,
    licensenumber,
    autosync,
    cellphonecountry,
    occupation,
    cellphone,
    primaryaddressid,
    suffix,
    addressbookuid,
    loadrelatedcontacts,
    emailaddress1,
    numdependents,
    primarylanguage,
    emailaddress2,
    dateofbirth,
    primarylocale,
    taxstatus,
    numdependentsu25,
    workphoneextension,
    maritalstatus,
    namekanji,
    faxphoneextension,
    homephone,
    licensestate,
    faxphone,
    cellphoneextension,
    employeenumber,
    workphonecountry,
    subtype,
    formername,
    workphone,
    communicationpref_icare,
    notificationstatus_icare,
    trustabnisactive_icare,
    sourcesystem_icare,
    acn_icare,
    organisationtype_icare,
    trustname_icare,
    commencementdate_icare,
    tradingname_icare,
    abn_icare,
    trusteetype_icare,
    trustregisteredforgst_icare,
    crmversion_icare,
    trusteename_icare,
    trustabn_icare,
    trustabnvalidated_icare,
    abnisactive_icare,
    registeredforgst_icare,
    abnvalidated_icare,
    obfuscatedinternal,
    donotdestroy,
    creationsource_ext,
    status_ext,
    'GWBC' AS source_system,
    gwcbi_connector_ts_ms,
    gwcbi_lsn,
    gwcbi_operation,
    gwcbi_payload_ts_ms,
    gwcbi_seqval,
    gwcbi_seqval_hex,
    gwcbi_tx_id,
    metadata_file_name,
    file_ingestion_timestamp
FROM {{ ref('stg_raw_bc_contact') }}

{% endsnapshot %}