{% snapshot mv_gbs_claim_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026.01.11      0.0                             This Creates a  View for the Snapshot for the Table mv_gbs_claim_snapshot . 
                                                dbt snapshot is SCD Type 2 .
                                                
-#}


{{ config(
    target_schema='ifnsw_claim_interface',
    unique_key='mv_gbs_claim_sk',
    strategy='check',
    alias='mv_gbs_claim',
    check_cols=['claims_manager', 'agency', 'line_of_business', 'extract_date', 'record_number', 'policy_number', 'claim_number', 'abandoned_excess', 'accident_cause', 'accident_cause_dsc', 'accident_lighting', 'accident_location_dsc', 'accident_loss_result', 'accident_location_postcode', 'accident_road_surface', 'accident_location_state', 'accident_location_suburb', 'accident_type', 'accident_vehicle_speed', 'accident_weather', 'assessor', 'assessor_report', 'asset_number', 'catastrophe_code', 'catastrophe_dsc', 'claim_lodged', 'clmnt_first_name', 'clmnt_occupation_code', 'clmnt_occupation_code_dsc', 'clmnt_surname', 'claims_officer', 'cost_centre', 'date_reported', 'date_entered', 'date_finalised', 'date_of_repair', 'date_received', 'date_occurred', 'driver_admit_fault', 'driver_breath_test', 'driver_breath_test_reading', 'driver_consumed_alcohol', 'driver_dob', 'driver_employee_id', 'driver_experience', 'driver_first_name', 'driver_gender', 'driver_hours_on_duty', 'driver_licence_expiry', 'driver_licence_number', 'driver_postcode', 'driver_surname', 'incident_number', 'insured', 'litigation_claim_status', 'mias', 'narrative', 'number_vehicles_involved', 'oic_vehicle', 'people_injured', 'police_action', 'police_action_against', 'police_attended', 'police_blamed', 'police_investigating', 'police_reported_to', 'police_station', 'recovery_claim_status', 'repairer', 'salvage_action', 'time_occurred', 'vehicle_body', 'vehicle_chassis_number', 'vehicle_colour', 'vehicle_duty', 'vehicle_home_postcode', 'vehicle_insurance_type', 'vehicle_make', 'vehicle_markings', 'vehicle_model', 'vehicle_occupant_count', 'vehicle_odometer', 'vehicle_owner', 'vehicle_registration', 'vehicle_responding', 'vehicle_type', 'vehicle_vin', 'vehicle_work_postcode', 'vehicle_year', 'witnesses', 'driver_present', 'party_at_fault', 'country_code', 'event_code', 'previous_policy_number', 'accident_claim_type', 'jurisdiction_status', 'claim_sensitivity_code', 'claim_sensitivity_desc'],
    tags=['snapshot_tmf','snapshot_curated','snapshot','mv_gbs_claim']
) }}

WITH source_data AS (
    SELECT
        {{ dbt_utils.generate_surrogate_key([
            'claims_manager',
            'agency',
            'line_of_business',
            'extract_date',
            'record_number',
            'policy_number',
            'claim_number',
            'abandoned_excess',
            'accident_cause',
            'accident_cause_dsc',
            'accident_lighting',
            'accident_location_dsc',
            'accident_loss_result',
            'accident_location_postcode',
            'accident_road_surface',
            'accident_location_state',
            'accident_location_suburb',
            'accident_type',
            'accident_vehicle_speed',
            'accident_weather',
            'assessor',
            'assessor_report',
            'asset_number',
            'catastrophe_code',
            'catastrophe_dsc',
            'claim_lodged',
            'clmnt_first_name',
            'clmnt_occupation_code',
            'clmnt_occupation_code_dsc',
            'clmnt_surname',
            'claims_officer',
            'cost_centre',
            'date_reported',
            'date_entered',
            'date_finalised',
            'date_of_repair',
            'date_received',
            'date_occurred',
            'driver_admit_fault',
            'driver_breath_test',
            'driver_breath_test_reading',
            'driver_consumed_alcohol',
            'driver_dob',
            'driver_employee_id',
            'driver_experience',
            'driver_first_name',
            'driver_gender',
            'driver_hours_on_duty',
            'driver_licence_expiry',
            'driver_licence_number',
            'driver_postcode',
            'driver_surname',
            'incident_number',
            'insured',
            'litigation_claim_status',
            'mias',
            'narrative',
            'number_vehicles_involved',
            'oic_vehicle',
            'people_injured',
            'police_action',
            'police_action_against',
            'police_attended',
            'police_blamed',
            'police_investigating',
            'police_reported_to',
            'police_station',
            'recovery_claim_status',
            'repairer',
            'salvage_action',
            'time_occurred',
            'vehicle_body',
            'vehicle_chassis_number',
            'vehicle_colour',
            'vehicle_duty',
            'vehicle_home_postcode',
            'vehicle_insurance_type',
            'vehicle_make',
            'vehicle_markings',
            'vehicle_model',
            'vehicle_occupant_count',
            'vehicle_odometer',
            'vehicle_owner',
            'vehicle_registration',
            'vehicle_responding',
            'vehicle_type',
            'vehicle_vin',
            'vehicle_work_postcode',
            'vehicle_year',
            'witnesses',
            'driver_present',
            'party_at_fault',
            'country_code',
            'event_code',
            'previous_policy_number',
            'accident_claim_type',
            'jurisdiction_status',
            'claim_sensitivity_code',
            'claim_sensitivity_desc'
    ]) }} AS mv_gbs_claim_sk,
        CURRENT_TIMESTAMP() AS dbt_updated_at,
        claims_manager,
        agency,
        line_of_business,
        extract_date,
        record_number,
        policy_number,
        claim_number,
        abandoned_excess,
        accident_cause,
        accident_cause_dsc,
        accident_lighting,
        accident_location_dsc,
        accident_loss_result,
        accident_location_postcode,
        accident_road_surface,
        accident_location_state,
        accident_location_suburb,
        accident_type,
        accident_vehicle_speed,
        accident_weather,
        assessor,
        assessor_report,
        asset_number,
        catastrophe_code,
        catastrophe_dsc,
        claim_lodged,
        clmnt_first_name,
        clmnt_occupation_code,
        clmnt_occupation_code_dsc,
        clmnt_surname,
        claims_officer,
        cost_centre,
        date_reported,
        date_entered,
        date_finalised,
        date_of_repair,
        date_received,
        date_occurred,
        driver_admit_fault,
        driver_breath_test,
        driver_breath_test_reading,
        driver_consumed_alcohol,
        driver_dob,
        driver_employee_id,
        driver_experience,
        driver_first_name,
        driver_gender,
        driver_hours_on_duty,
        driver_licence_expiry,
        driver_licence_number,
        driver_postcode,
        driver_surname,
        incident_number,
        insured,
        litigation_claim_status,
        mias,
        narrative,
        number_vehicles_involved,
        oic_vehicle,
        people_injured,
        police_action,
        police_action_against,
        police_attended,
        police_blamed,
        police_investigating,
        police_reported_to,
        police_station,
        recovery_claim_status,
        repairer,
        salvage_action,
        time_occurred,
        vehicle_body,
        vehicle_chassis_number,
        vehicle_colour,
        vehicle_duty,
        vehicle_home_postcode,
        vehicle_insurance_type,
        vehicle_make,
        vehicle_markings,
        vehicle_model,
        vehicle_occupant_count,
        vehicle_odometer,
        vehicle_owner,
        vehicle_registration,
        vehicle_responding,
        vehicle_type,
        vehicle_vin,
        vehicle_work_postcode,
        vehicle_year,
        witnesses,
        driver_present,
        party_at_fault,
        country_code,
        event_code,
        previous_policy_number,
        accident_claim_type,
        jurisdiction_status,
        claim_sensitivity_code,
        claim_sensitivity_desc,
        metadata_file_name,
        metadata_file_last_modified,
        metadata_scan_time,
        metadata_row_number,
        file_ingestion_timestamp
    FROM {{ source('ifnsw_claim_interface', 'mv_gbs_claim') }}
)

SELECT * FROM source_data

{% endsnapshot %}