{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for pcx_crifpolicydm_icare.
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                record_insertion_date: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDA goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    incremental_strategy='append',
    on_schema_change='append_new_columns',
    tags=["landing", "gwpc", "policy_centre", "non_business_critical"]
) }}


WITH cte_source_data AS 
(

            SELECT
                CAST(data_payload:CROther::TEXT AS VARCHAR(100)) AS crother,
                CAST(data_payload:CRLiabExcess::TEXT AS VARCHAR(100)) AS crliabexcess,
                CAST(data_payload:CRMDGST::TEXT AS VARCHAR(100)) AS crmdgst,
                CAST(data_payload:GeoLocation::TEXT AS VARCHAR(100)) AS geolocation,
                CAST(data_payload:CRMDSearchLocateCosts::TEXT AS VARCHAR(100)) AS crmdsearchlocatecosts,
                CAST(data_payload:AcctPayEmail::TEXT AS VARCHAR(100)) AS acctpayemail,
                CAST(data_payload:CRMDConPlantEquipQuestion::TEXT AS VARCHAR(100)) AS crmdconplantequipquestion,
                CAST(data_payload:WBS::TEXT AS VARCHAR(100)) AS wbs,
                CAST(data_payload:CRMCDSExcess::TEXT AS VARCHAR(100)) AS crmcdsexcess,
                CAST(data_payload:CRDSGST::TEXT AS VARCHAR(100)) AS crdsgst,
                CAST(data_payload:CRDelayedStartup::TEXT AS VARCHAR(100)) AS crdelayedstartup,
                CAST(data_payload:CRMDPropTransit::TEXT AS VARCHAR(100)) AS crmdproptransit,
                CAST(data_payload:CRMLSumInsured::TEXT AS VARCHAR(100)) AS crmlsuminsured,
                CAST(data_payload:CRPILimit::TEXT AS VARCHAR(100)) AS crpilimit,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                CAST(data_payload:CRLiabTotal::TEXT AS VARCHAR(100)) AS crliabtotal,
                CAST(data_payload:CRMDWetWorksExcess::TEXT AS VARCHAR(100)) AS crmdwetworksexcess,
                CAST(data_payload:ConstructionEndDate::TEXT AS VARCHAR(100)) AS constructionenddate,
                data_payload:ID::NUMBER AS id,
                CAST(data_payload:ContactFirstName::TEXT AS VARCHAR(100)) AS contactfirstname,
                CAST(data_payload:CRCPETotal::TEXT AS VARCHAR(100)) AS crcpetotal,
                CAST(data_payload:CRPIExcess::TEXT AS VARCHAR(100)) AS crpiexcess,
                CAST(data_payload:BilledTotal::TEXT AS VARCHAR(100)) AS billedtotal,
                CAST(data_payload:CROSumInsured::TEXT AS VARCHAR(100)) AS crosuminsured,
                CAST(data_payload:CRMCTotal::TEXT AS VARCHAR(100)) AS crmctotal,
                CAST(data_payload:CRMDMitigationExpenses::TEXT AS VARCHAR(100)) AS crmdmitigationexpenses,
                CAST(data_payload:CRMDConPlantEquip::TEXT AS VARCHAR(100)) AS crmdconplantequip,
                data_payload:CreateUserID::NUMBER AS createuserid,
                CAST(data_payload:ProjectName::TEXT AS VARCHAR(500)) AS projectname,
                data_payload:BeanVersion::NUMBER AS beanversion,
                CAST(data_payload:CROGST::TEXT AS VARCHAR(100)) AS crogst,
                CAST(data_payload:CRMDContractWorks::TEXT AS VARCHAR(100)) AS crmdcontractworks,
                CAST(data_payload:ResultDesc::TEXT AS VARCHAR(500)) AS resultdesc,
                CAST(data_payload:CREILExcess::TEXT AS VARCHAR(100)) AS creilexcess,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                CAST(data_payload:CRMCDSTotal::TEXT AS VARCHAR(100)) AS crmcdstotal,
                CAST(data_payload:CRDSExcess::TEXT AS VARCHAR(100)) AS crdsexcess,
                CAST(data_payload:PostalCode::TEXT AS VARCHAR(100)) AS postalcode,
                CAST(data_payload:CRMDStandardExcess::TEXT AS VARCHAR(100)) AS crmdstandardexcess,
                CAST(data_payload:CRPILostDocsExcess::TEXT AS VARCHAR(100)) AS crpilostdocsexcess,
                CAST(data_payload:CRMarineLiability::TEXT AS VARCHAR(100)) AS crmarineliability,
                CAST(data_payload:PostCompletionPeriod::TEXT AS VARCHAR(100)) AS postcompletionperiod,
                CAST(data_payload:CRMDOffsiteFabrication::TEXT AS VARCHAR(100)) AS crmdoffsitefabrication,
                CAST(data_payload:PeriodStart::TEXT AS VARCHAR(100)) AS periodstart,
                CAST(data_payload:ContactLastName::TEXT AS VARCHAR(100)) AS contactlastname,
                CAST(data_payload:CRMLExcess::TEXT AS VARCHAR(100)) AS crmlexcess,
                CAST(data_payload:InsuredABN::TEXT AS VARCHAR(500)) AS insuredabn,
                CAST(data_payload:CRMCDSPremium::TEXT AS VARCHAR(100)) AS crmcdspremium,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                CAST(data_payload:LegacyPolicyNumber::TEXT AS VARCHAR(100)) AS legacypolicynumber,
                CAST(data_payload:CRMCSumInsured::TEXT AS VARCHAR(100)) AS crmcsuminsured,
                CAST(data_payload:WrittenDate::TEXT AS VARCHAR(100)) AS writtendate,
                CAST(data_payload:CRMDRemoveDebris::TEXT AS VARCHAR(100)) AS crmdremovedebris,
                CAST(data_payload:CRMLPremium::TEXT AS VARCHAR(100)) AS crmlpremium,
                CAST(data_payload:AddressLine1::TEXT AS VARCHAR(100)) AS addressline1,
                CAST(data_payload:AddressLine2::TEXT AS VARCHAR(100)) AS addressline2,
                CAST(data_payload:CRMDOffsiteStorage::TEXT AS VARCHAR(100)) AS crmdoffsitestorage,
                CAST(data_payload:CREnvImpLiab::TEXT AS VARCHAR(100)) AS crenvimpliab,
                CAST(data_payload:ContactPhone::TEXT AS VARCHAR(100)) AS contactphone,
                CAST(data_payload:CRLiabEnvImpairLiability::TEXT AS VARCHAR(100)) AS crliabenvimpairliability,
                CAST(data_payload:CRLiabEnvImpairmentExcess::TEXT AS VARCHAR(100)) AS crliabenvimpairmentexcess,
                CAST(data_payload:CRMDPremium::TEXT AS VARCHAR(100)) AS crmdpremium,
                CAST(data_payload:CROExcess::TEXT AS VARCHAR(100)) AS croexcess,
                CAST(data_payload:CRDSPremium::TEXT AS VARCHAR(100)) AS crdspremium,
                CAST(data_payload:CRMDEscalation::TEXT AS VARCHAR(100)) AS crmdescalation,
                CAST(data_payload:CRMDClaimsPrepCosts::TEXT AS VARCHAR(100)) AS crmdclaimsprepcosts,
                data_payload:Seq::NUMBER AS seq,
                CAST(data_payload:ConstructionStartDate::TEXT AS VARCHAR(100)) AS constructionstartdate,
                CAST(data_payload:CRPIGST::TEXT AS VARCHAR(100)) AS crpigst,
                CAST(data_payload:CRMDLeg3Excess::TEXT AS VARCHAR(100)) AS crmdleg3excess,
                CAST(data_payload:CROTotal::TEXT AS VARCHAR(100)) AS crototal,
                CAST(data_payload:CRLiabProductsExcess::TEXT AS VARCHAR(100)) AS crliabproductsexcess,
                CAST(data_payload:CRLiabPremium::TEXT AS VARCHAR(100)) AS crliabpremium,
                CAST(data_payload:City::TEXT AS VARCHAR(100)) AS city,
                CAST(data_payload:CREILTotal::TEXT AS VARCHAR(100)) AS creiltotal,
                CAST(data_payload:CRMarineCargo::TEXT AS VARCHAR(100)) AS crmarinecargo,
                CAST(data_payload:Latitude::TEXT AS VARCHAR(100)) AS latitude,
                CAST(data_payload:CRCPEPremium::TEXT AS VARCHAR(100)) AS crcpepremium,
                CAST(data_payload:CRProfessionalIndemnity::TEXT AS VARCHAR(100)) AS crprofessionalindemnity,
                CAST(data_payload:CRMCPremium::TEXT AS VARCHAR(100)) AS crmcpremium,
                CAST(data_payload:InsuredName::TEXT AS VARCHAR(500)) AS insuredname,
                CAST(data_payload:CROPremium::TEXT AS VARCHAR(100)) AS cropremium,
                CAST(data_payload:PolicyCostPremium::TEXT AS VARCHAR(100)) AS policycostpremium,
                CAST(data_payload:CREILSumInsured::TEXT AS VARCHAR(100)) AS creilsuminsured,
                CAST(data_payload:PeriodEnd::TEXT AS VARCHAR(100)) AS periodend,
                CAST(data_payload:CRLiabProductsLiability::TEXT AS VARCHAR(100)) AS crliabproductsliability,
                CAST(data_payload:ContactEmail::TEXT AS VARCHAR(100)) AS contactemail,
                CAST(data_payload:CRMDInflationProtection::TEXT AS VARCHAR(100)) AS crmdinflationprotection,
                CAST(data_payload:CRCPEExcess::TEXT AS VARCHAR(100)) AS crcpeexcess,
                CAST(data_payload:CRLiability::TEXT AS VARCHAR(100)) AS crliability,
                CAST(data_payload:CRMLLiability::TEXT AS VARCHAR(100)) AS crmlliability,
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                CAST(data_payload:CRMaterialDamage::TEXT AS VARCHAR(100)) AS crmaterialdamage,
                CAST(data_payload:CRMarineCargoDelayStartup::TEXT AS VARCHAR(100)) AS crmarinecargodelaystartup,
                CAST(data_payload:ResultCode::TEXT AS VARCHAR(255)) AS resultcode,
                CAST(data_payload:CRMDExistingPropertyQuestion::TEXT AS VARCHAR(100)) AS crmdexistingpropertyquestion,
                CAST(data_payload:CRPIBridgeTunnelExcess::TEXT AS VARCHAR(100)) AS crpibridgetunnelexcess,
                CAST(data_payload:State::TEXT AS VARCHAR(100)) AS state,
                CAST(data_payload:Country::TEXT AS VARCHAR(100)) AS country,
                CAST(data_payload:CRConPlantEquip::TEXT AS VARCHAR(100)) AS crconplantequip,
                CAST(data_payload:CRMDTunnellingExcess::TEXT AS VARCHAR(100)) AS crmdtunnellingexcess,
                CAST(data_payload:CRMDProfessionalFees::TEXT AS VARCHAR(100)) AS crmdprofessionalfees,
                CAST(data_payload:CRLiabGST::TEXT AS VARCHAR(100)) AS crliabgst,
                CAST(data_payload:CRPITotal::TEXT AS VARCHAR(100)) AS crpitotal,
                CAST(data_payload:CRCPEGST::TEXT AS VARCHAR(100)) AS crcpegst,
                CAST(data_payload:CRMCGST::TEXT AS VARCHAR(100)) AS crmcgst,
                CAST(data_payload:PolicyCostTotal::TEXT AS VARCHAR(100)) AS policycosttotal,
                CAST(data_payload:TermType::TEXT AS VARCHAR(100)) AS termtype,
                CAST(data_payload:CRMDExistingProperty::TEXT AS VARCHAR(100)) AS crmdexistingproperty,
                data_payload:Retired::NUMBER AS retired,
                CAST(data_payload:PolicyCostGST::TEXT AS VARCHAR(100)) AS policycostgst,
                CAST(data_payload:CRPIPremium::TEXT AS VARCHAR(100)) AS crpipremium,
                CAST(data_payload:Longitude::TEXT AS VARCHAR(100)) AS longitude,
                CAST(data_payload:CRMDWaterDamageExcess::TEXT AS VARCHAR(100)) AS crmdwaterdamageexcess,
                CAST(data_payload:CRMLTotal::TEXT AS VARCHAR(100)) AS crmltotal,
                CAST(data_payload:AccountNumber::TEXT AS VARCHAR(100)) AS accountnumber,
                CAST(data_payload:CRMDTotal::TEXT AS VARCHAR(100)) AS crmdtotal,
                CAST(data_payload:CREILPremium::TEXT AS VARCHAR(100)) AS creilpremium,
                CAST(data_payload:CRDSTotal::TEXT AS VARCHAR(100)) AS crdstotal,
                CAST(data_payload:TypeOfCover::TEXT AS VARCHAR(100)) AS typeofcover,
                CAST(data_payload:CRCPESumInsured::TEXT AS VARCHAR(100)) AS crcpesuminsured,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                CAST(data_payload:TestingPeriod::TEXT AS VARCHAR(100)) AS testingperiod,
                CAST(data_payload:ProjectType::TEXT AS VARCHAR(100)) AS projecttype,
                CAST(data_payload:CRMCDSSumInsured::TEXT AS VARCHAR(100)) AS crmcdssuminsured,
                data_payload:BatchId::NUMBER AS batchid,
                CAST(data_payload:CRPIUnderlyingLimit::TEXT AS VARCHAR(100)) AS crpiunderlyinglimit,
                CAST(data_payload:CRLiabPublicLiability::TEXT AS VARCHAR(100)) AS crliabpublicliability,
                CAST(data_payload:CRMDGovtCosts::TEXT AS VARCHAR(100)) AS crmdgovtcosts,
                CAST(data_payload:ContractNumber::TEXT AS VARCHAR(100)) AS contractnumber,
                CAST(data_payload:ContaminatedSite::TEXT AS VARCHAR(100)) AS contaminatedsite,
                CAST(data_payload:CRLiabUnderSrvExcess::TEXT AS VARCHAR(100)) AS crliabundersrvexcess,
                CAST(data_payload:PurchaseOrder::TEXT AS VARCHAR(100)) AS purchaseorder,
                CAST(data_payload:CREILGST::TEXT AS VARCHAR(100)) AS creilgst,
                CAST(data_payload:AdditionalInsureds::TEXT AS VARCHAR(500)) AS additionalinsureds,
                CAST(data_payload:Status::TEXT AS VARCHAR(255)) AS status,
                CAST(data_payload:BilledOutstanding::TEXT AS VARCHAR(100)) AS billedoutstanding,
                CAST(data_payload:CRMCDSGST::TEXT AS VARCHAR(100)) AS crmcdsgst,
                CAST(data_payload:CRMDCombinedLimit21ai::TEXT AS VARCHAR(100)) AS crmdcombinedlimit21ai,
                CAST(data_payload:ProjectValue::TEXT AS VARCHAR(100)) AS projectvalue,
                CAST(data_payload:CRMLGST::TEXT AS VARCHAR(100)) AS crmlgst,
                CAST(data_payload:CRMCExcess::TEXT AS VARCHAR(100)) AS crmcexcess,
                CAST(data_payload:CRDSSumInsured::TEXT AS VARCHAR(100)) AS crdssuminsured,
                CAST(data_payload:CRLiabWorkerWorkerExcess::TEXT AS VARCHAR(100)) AS crliabworkerworkerexcess,
                CAST(data_payload:CRMDExpediteExpenses::TEXT AS VARCHAR(100)) AS crmdexpediteexpenses,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS VARCHAR(300)) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'AVRO' as file_type,
                'GWPC' as source_system
            FROM {{ source('gwpc', 'pcx_crifpolicydm_icare') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                CAST($1:crother::TEXT AS VARCHAR(100)) AS crother,
                CAST($1:crliabexcess::TEXT AS VARCHAR(100)) AS crliabexcess,
                CAST($1:crmdgst::TEXT AS VARCHAR(100)) AS crmdgst,
                CAST($1:geolocation::TEXT AS VARCHAR(100)) AS geolocation,
                CAST($1:crmdsearchlocatecosts::TEXT AS VARCHAR(100)) AS crmdsearchlocatecosts,
                CAST($1:acctpayemail::TEXT AS VARCHAR(100)) AS acctpayemail,
                CAST($1:crmdconplantequipquestion::TEXT AS VARCHAR(100)) AS crmdconplantequipquestion,
                CAST($1:wbs::TEXT AS VARCHAR(100)) AS wbs,
                CAST($1:crmcdsexcess::TEXT AS VARCHAR(100)) AS crmcdsexcess,
                CAST($1:crdsgst::TEXT AS VARCHAR(100)) AS crdsgst,
                CAST($1:crdelayedstartup::TEXT AS VARCHAR(100)) AS crdelayedstartup,
                CAST($1:crmdproptransit::TEXT AS VARCHAR(100)) AS crmdproptransit,
                CAST($1:crmlsuminsured::TEXT AS VARCHAR(100)) AS crmlsuminsured,
                CAST($1:crpilimit::TEXT AS VARCHAR(100)) AS crpilimit,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                CAST($1:crliabtotal::TEXT AS VARCHAR(100)) AS crliabtotal,
                CAST($1:crmdwetworksexcess::TEXT AS VARCHAR(100)) AS crmdwetworksexcess,
                CAST($1:constructionenddate::TEXT AS VARCHAR(100)) AS constructionenddate,
                $1:id::NUMBER AS id,
                CAST($1:contactfirstname::TEXT AS VARCHAR(100)) AS contactfirstname,
                CAST($1:crcpetotal::TEXT AS VARCHAR(100)) AS crcpetotal,
                CAST($1:crpiexcess::TEXT AS VARCHAR(100)) AS crpiexcess,
                CAST($1:billedtotal::TEXT AS VARCHAR(100)) AS billedtotal,
                CAST($1:crosuminsured::TEXT AS VARCHAR(100)) AS crosuminsured,
                CAST($1:crmctotal::TEXT AS VARCHAR(100)) AS crmctotal,
                CAST($1:crmdmitigationexpenses::TEXT AS VARCHAR(100)) AS crmdmitigationexpenses,
                CAST($1:crmdconplantequip::TEXT AS VARCHAR(100)) AS crmdconplantequip,
                $1:createuserid::NUMBER AS createuserid,
                CAST($1:projectname::TEXT AS VARCHAR(500)) AS projectname,
                $1:beanversion::NUMBER AS beanversion,
                CAST($1:crogst::TEXT AS VARCHAR(100)) AS crogst,
                CAST($1:crmdcontractworks::TEXT AS VARCHAR(100)) AS crmdcontractworks,
                CAST($1:resultdesc::TEXT AS VARCHAR(500)) AS resultdesc,
                CAST($1:creilexcess::TEXT AS VARCHAR(100)) AS creilexcess,
                $1:updateuserid::NUMBER AS updateuserid,
                CAST($1:crmcdstotal::TEXT AS VARCHAR(100)) AS crmcdstotal,
                CAST($1:crdsexcess::TEXT AS VARCHAR(100)) AS crdsexcess,
                CAST($1:postalcode::TEXT AS VARCHAR(100)) AS postalcode,
                CAST($1:crmdstandardexcess::TEXT AS VARCHAR(100)) AS crmdstandardexcess,
                CAST($1:crpilostdocsexcess::TEXT AS VARCHAR(100)) AS crpilostdocsexcess,
                CAST($1:crmarineliability::TEXT AS VARCHAR(100)) AS crmarineliability,
                CAST($1:postcompletionperiod::TEXT AS VARCHAR(100)) AS postcompletionperiod,
                CAST($1:crmdoffsitefabrication::TEXT AS VARCHAR(100)) AS crmdoffsitefabrication,
                CAST($1:periodstart::TEXT AS VARCHAR(100)) AS periodstart,
                CAST($1:contactlastname::TEXT AS VARCHAR(100)) AS contactlastname,
                CAST($1:crmlexcess::TEXT AS VARCHAR(100)) AS crmlexcess,
                CAST($1:insuredabn::TEXT AS VARCHAR(500)) AS insuredabn,
                CAST($1:crmcdspremium::TEXT AS VARCHAR(100)) AS crmcdspremium,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                CAST($1:legacypolicynumber::TEXT AS VARCHAR(100)) AS legacypolicynumber,
                CAST($1:crmcsuminsured::TEXT AS VARCHAR(100)) AS crmcsuminsured,
                CAST($1:writtendate::TEXT AS VARCHAR(100)) AS writtendate,
                CAST($1:crmdremovedebris::TEXT AS VARCHAR(100)) AS crmdremovedebris,
                CAST($1:crmlpremium::TEXT AS VARCHAR(100)) AS crmlpremium,
                CAST($1:addressline1::TEXT AS VARCHAR(100)) AS addressline1,
                CAST($1:addressline2::TEXT AS VARCHAR(100)) AS addressline2,
                CAST($1:crmdoffsitestorage::TEXT AS VARCHAR(100)) AS crmdoffsitestorage,
                CAST($1:crenvimpliab::TEXT AS VARCHAR(100)) AS crenvimpliab,
                CAST($1:contactphone::TEXT AS VARCHAR(100)) AS contactphone,
                CAST($1:crliabenvimpairliability::TEXT AS VARCHAR(100)) AS crliabenvimpairliability,
                CAST($1:crliabenvimpairmentexcess::TEXT AS VARCHAR(100)) AS crliabenvimpairmentexcess,
                CAST($1:crmdpremium::TEXT AS VARCHAR(100)) AS crmdpremium,
                CAST($1:croexcess::TEXT AS VARCHAR(100)) AS croexcess,
                CAST($1:crdspremium::TEXT AS VARCHAR(100)) AS crdspremium,
                CAST($1:crmdescalation::TEXT AS VARCHAR(100)) AS crmdescalation,
                CAST($1:crmdclaimsprepcosts::TEXT AS VARCHAR(100)) AS crmdclaimsprepcosts,
                $1:seq::NUMBER AS seq,
                CAST($1:constructionstartdate::TEXT AS VARCHAR(100)) AS constructionstartdate,
                CAST($1:crpigst::TEXT AS VARCHAR(100)) AS crpigst,
                CAST($1:crmdleg3excess::TEXT AS VARCHAR(100)) AS crmdleg3excess,
                CAST($1:crototal::TEXT AS VARCHAR(100)) AS crototal,
                CAST($1:crliabproductsexcess::TEXT AS VARCHAR(100)) AS crliabproductsexcess,
                CAST($1:crliabpremium::TEXT AS VARCHAR(100)) AS crliabpremium,
                CAST($1:city::TEXT AS VARCHAR(100)) AS city,
                CAST($1:creiltotal::TEXT AS VARCHAR(100)) AS creiltotal,
                CAST($1:crmarinecargo::TEXT AS VARCHAR(100)) AS crmarinecargo,
                CAST($1:latitude::TEXT AS VARCHAR(100)) AS latitude,
                CAST($1:crcpepremium::TEXT AS VARCHAR(100)) AS crcpepremium,
                CAST($1:crprofessionalindemnity::TEXT AS VARCHAR(100)) AS crprofessionalindemnity,
                CAST($1:crmcpremium::TEXT AS VARCHAR(100)) AS crmcpremium,
                CAST($1:insuredname::TEXT AS VARCHAR(500)) AS insuredname,
                CAST($1:cropremium::TEXT AS VARCHAR(100)) AS cropremium,
                CAST($1:policycostpremium::TEXT AS VARCHAR(100)) AS policycostpremium,
                CAST($1:creilsuminsured::TEXT AS VARCHAR(100)) AS creilsuminsured,
                CAST($1:periodend::TEXT AS VARCHAR(100)) AS periodend,
                CAST($1:crliabproductsliability::TEXT AS VARCHAR(100)) AS crliabproductsliability,
                CAST($1:contactemail::TEXT AS VARCHAR(100)) AS contactemail,
                CAST($1:crmdinflationprotection::TEXT AS VARCHAR(100)) AS crmdinflationprotection,
                CAST($1:crcpeexcess::TEXT AS VARCHAR(100)) AS crcpeexcess,
                CAST($1:crliability::TEXT AS VARCHAR(100)) AS crliability,
                CAST($1:crmlliability::TEXT AS VARCHAR(100)) AS crmlliability,
                $1:loadcommandid::NUMBER AS loadcommandid,
                CAST($1:crmaterialdamage::TEXT AS VARCHAR(100)) AS crmaterialdamage,
                CAST($1:crmarinecargodelaystartup::TEXT AS VARCHAR(100)) AS crmarinecargodelaystartup,
                CAST($1:resultcode::TEXT AS VARCHAR(255)) AS resultcode,
                CAST($1:crmdexistingpropertyquestion::TEXT AS VARCHAR(100)) AS crmdexistingpropertyquestion,
                CAST($1:crpibridgetunnelexcess::TEXT AS VARCHAR(100)) AS crpibridgetunnelexcess,
                CAST($1:state::TEXT AS VARCHAR(100)) AS state,
                CAST($1:country::TEXT AS VARCHAR(100)) AS country,
                CAST($1:crconplantequip::TEXT AS VARCHAR(100)) AS crconplantequip,
                CAST($1:crmdtunnellingexcess::TEXT AS VARCHAR(100)) AS crmdtunnellingexcess,
                CAST($1:crmdprofessionalfees::TEXT AS VARCHAR(100)) AS crmdprofessionalfees,
                CAST($1:crliabgst::TEXT AS VARCHAR(100)) AS crliabgst,
                CAST($1:crpitotal::TEXT AS VARCHAR(100)) AS crpitotal,
                CAST($1:crcpegst::TEXT AS VARCHAR(100)) AS crcpegst,
                CAST($1:crmcgst::TEXT AS VARCHAR(100)) AS crmcgst,
                CAST($1:policycosttotal::TEXT AS VARCHAR(100)) AS policycosttotal,
                CAST($1:termtype::TEXT AS VARCHAR(100)) AS termtype,
                CAST($1:crmdexistingproperty::TEXT AS VARCHAR(100)) AS crmdexistingproperty,
                $1:retired::NUMBER AS retired,
                CAST($1:policycostgst::TEXT AS VARCHAR(100)) AS policycostgst,
                CAST($1:crpipremium::TEXT AS VARCHAR(100)) AS crpipremium,
                CAST($1:longitude::TEXT AS VARCHAR(100)) AS longitude,
                CAST($1:crmdwaterdamageexcess::TEXT AS VARCHAR(100)) AS crmdwaterdamageexcess,
                CAST($1:crmltotal::TEXT AS VARCHAR(100)) AS crmltotal,
                CAST($1:accountnumber::TEXT AS VARCHAR(100)) AS accountnumber,
                CAST($1:crmdtotal::TEXT AS VARCHAR(100)) AS crmdtotal,
                CAST($1:creilpremium::TEXT AS VARCHAR(100)) AS creilpremium,
                CAST($1:crdstotal::TEXT AS VARCHAR(100)) AS crdstotal,
                CAST($1:typeofcover::TEXT AS VARCHAR(100)) AS typeofcover,
                CAST($1:crcpesuminsured::TEXT AS VARCHAR(100)) AS crcpesuminsured,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                CAST($1:testingperiod::TEXT AS VARCHAR(100)) AS testingperiod,
                CAST($1:projecttype::TEXT AS VARCHAR(100)) AS projecttype,
                CAST($1:crmcdssuminsured::TEXT AS VARCHAR(100)) AS crmcdssuminsured,
                $1:batchid::NUMBER AS batchid,
                CAST($1:crpiunderlyinglimit::TEXT AS VARCHAR(100)) AS crpiunderlyinglimit,
                CAST($1:crliabpublicliability::TEXT AS VARCHAR(100)) AS crliabpublicliability,
                CAST($1:crmdgovtcosts::TEXT AS VARCHAR(100)) AS crmdgovtcosts,
                CAST($1:contractnumber::TEXT AS VARCHAR(100)) AS contractnumber,
                CAST($1:contaminatedsite::TEXT AS VARCHAR(100)) AS contaminatedsite,
                CAST($1:crliabundersrvexcess::TEXT AS VARCHAR(100)) AS crliabundersrvexcess,
                CAST($1:purchaseorder::TEXT AS VARCHAR(100)) AS purchaseorder,
                CAST($1:creilgst::TEXT AS VARCHAR(100)) AS creilgst,
                CAST($1:additionalinsureds::TEXT AS VARCHAR(500)) AS additionalinsureds,
                CAST($1:status::TEXT AS VARCHAR(255)) AS status,
                CAST($1:billedoutstanding::TEXT AS VARCHAR(100)) AS billedoutstanding,
                CAST($1:crmcdsgst::TEXT AS VARCHAR(100)) AS crmcdsgst,
                CAST($1:crmdcombinedlimit21ai::TEXT AS VARCHAR(100)) AS crmdcombinedlimit21ai,
                CAST($1:projectvalue::TEXT AS VARCHAR(100)) AS projectvalue,
                CAST($1:crmlgst::TEXT AS VARCHAR(100)) AS crmlgst,
                CAST($1:crmcexcess::TEXT AS VARCHAR(100)) AS crmcexcess,
                CAST($1:crdssuminsured::TEXT AS VARCHAR(100)) AS crdssuminsured,
                CAST($1:crliabworkerworkerexcess::TEXT AS VARCHAR(100)) AS crliabworkerworkerexcess,
                CAST($1:crmdexpediteexpenses::TEXT AS VARCHAR(100)) AS crmdexpediteexpenses,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::VARCHAR(300) as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'PARQUET' as file_type,
                'GWPC' as source_system
            FROM {{ source('gwpc', 'pcx_crifpolicydm_icare') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS crifpolicydm_icare_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'crother',
                        'crliabexcess',
                        'crmdgst',
                        'geolocation',
                        'crmdsearchlocatecosts',
                        'acctpayemail',
                        'crmdconplantequipquestion',
                        'wbs',
                        'crmcdsexcess',
                        'crdsgst',
                        'crdelayedstartup',
                        'crmdproptransit',
                        'crmlsuminsured',
                        'crpilimit',
                        'updatetime',
                        'crliabtotal',
                        'crmdwetworksexcess',
                        'constructionenddate',
                        'contactfirstname',
                        'crcpetotal',
                        'crpiexcess',
                        'billedtotal',
                        'crosuminsured',
                        'crmctotal',
                        'crmdmitigationexpenses',
                        'crmdconplantequip',
                        'createuserid',
                        'projectname',
                        'beanversion',
                        'crogst',
                        'crmdcontractworks',
                        'resultdesc',
                        'creilexcess',
                        'updateuserid',
                        'crmcdstotal',
                        'crdsexcess',
                        'postalcode',
                        'crmdstandardexcess',
                        'crpilostdocsexcess',
                        'crmarineliability',
                        'postcompletionperiod',
                        'crmdoffsitefabrication',
                        'periodstart',
                        'contactlastname',
                        'crmlexcess',
                        'insuredabn',
                        'crmcdspremium',
                        'publicid',
                        'legacypolicynumber',
                        'crmcsuminsured',
                        'writtendate',
                        'crmdremovedebris',
                        'crmlpremium',
                        'addressline1',
                        'addressline2',
                        'crmdoffsitestorage',
                        'crenvimpliab',
                        'contactphone',
                        'crliabenvimpairliability',
                        'crliabenvimpairmentexcess',
                        'crmdpremium',
                        'croexcess',
                        'crdspremium',
                        'crmdescalation',
                        'crmdclaimsprepcosts',
                        'seq',
                        'constructionstartdate',
                        'crpigst',
                        'crmdleg3excess',
                        'crototal',
                        'crliabproductsexcess',
                        'crliabpremium',
                        'city',
                        'creiltotal',
                        'crmarinecargo',
                        'latitude',
                        'crcpepremium',
                        'crprofessionalindemnity',
                        'crmcpremium',
                        'insuredname',
                        'cropremium',
                        'policycostpremium',
                        'creilsuminsured',
                        'periodend',
                        'crliabproductsliability',
                        'contactemail',
                        'crmdinflationprotection',
                        'crcpeexcess',
                        'crliability',
                        'crmlliability',
                        'loadcommandid',
                        'crmaterialdamage',
                        'crmarinecargodelaystartup',
                        'resultcode',
                        'crmdexistingpropertyquestion',
                        'crpibridgetunnelexcess',
                        'state',
                        'country',
                        'crconplantequip',
                        'crmdtunnellingexcess',
                        'crmdprofessionalfees',
                        'crliabgst',
                        'crpitotal',
                        'crcpegst',
                        'crmcgst',
                        'policycosttotal',
                        'termtype',
                        'crmdexistingproperty',
                        'retired',
                        'policycostgst',
                        'crpipremium',
                        'longitude',
                        'crmdwaterdamageexcess',
                        'crmltotal',
                        'accountnumber',
                        'crmdtotal',
                        'creilpremium',
                        'crdstotal',
                        'typeofcover',
                        'crcpesuminsured',
                        'createtime',
                        'testingperiod',
                        'projecttype',
                        'crmcdssuminsured',
                        'batchid',
                        'crpiunderlyinglimit',
                        'crliabpublicliability',
                        'crmdgovtcosts',
                        'contractnumber',
                        'contaminatedsite',
                        'crliabundersrvexcess',
                        'purchaseorder',
                        'creilgst',
                        'additionalinsureds',
                        'status',
                        'billedoutstanding',
                        'crmcdsgst',
                        'crmdcombinedlimit21ai',
                        'projectvalue',
                        'crmlgst',
                        'crmcexcess',
                        'crdssuminsured',
                        'crliabworkerworkerexcess',
                        'crmdexpediteexpenses'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
    WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}
    ORDER BY record_insertion_date
