{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for pc_policyline.
                                                policyline_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["landing", "gwpc", "policy_centre", "non_business_critical", "pc_policyline"]
) }}


WITH cte_source_data AS 
(

            SELECT
                CAST(data_payload:LegacyAppIncentiveCost AS NUMBER(18,2)) AS legacyappincentivecost,
                data_payload:SmallBusinessType::NUMBER AS smallbusinesstype,
                data_payload:LegacyAppIncentiveCost_cur::NUMBER AS legacyappincentivecost_cur,
                data_payload:LocationLimits::BOOLEAN AS locationlimits,
                data_payload:FixedID::NUMBER AS fixedid,
                data_payload:GLCoverageForm::NUMBER AS glcoverageform,
                CAST(data_payload:PremiumAdjustmentContribution AS NUMBER(18,2)) AS premiumadjustmentcontribution,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:ID::NUMBER AS id,
                data_payload:InitialExclusionsCreated::BOOLEAN AS initialexclusionscreated,
                data_payload:CreateUserID::NUMBER AS createuserid,
                data_payload:PollutionCleanupExp::BOOLEAN AS pollutioncleanupexp,
                data_payload:BeanVersion::NUMBER AS beanversion,
                CAST(data_payload:LegacyRTWICost AS NUMBER(18,2)) AS legacyrtwicost,
                CAST(data_payload:LegacyClaimsPerfAdjCost AS NUMBER(18,2)) AS legacyclaimsperfadjcost,
                data_payload:LegacyRTWICost_cur::NUMBER AS legacyrtwicost_cur,
                data_payload:LegacyClaimsPerfAdjCost_cur::NUMBER AS legacyclaimsperfadjcost_cur,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                data_payload:NumAddInsured::NUMBER AS numaddinsured,
                CAST(data_payload:ManuscriptPremium AS NUMBER(18,2)) AS manuscriptpremium,
                data_payload:ManuscriptPremium_cur::NUMBER AS manuscriptpremium_cur,
                data_payload:SplitLimits::BOOLEAN AS splitlimits,
                TO_TIMESTAMP_TZ(data_payload:ReferenceDateInternal::NUMBER/1000) AS referencedateinternal,
                CAST(data_payload:LegacyBasicTariffCost AS NUMBER(18,2)) AS legacybasictariffcost,
                data_payload:LegacyBasicTariffCost_cur::NUMBER AS legacybasictariffcost_cur,
                data_payload:BusinessVehicleAutoNumberSeq::NUMBER AS businessvehicleautonumberseq,
                data_payload:PersonalVehicleAutoNumberSeq::NUMBER AS personalvehicleautonumberseq,
                CAST(data_payload:LegacyMineSafetyCost AS NUMBER(18,2)) AS legacyminesafetycost,
                data_payload:LegacyMineSafetyCost_cur::NUMBER AS legacyminesafetycost_cur,
                data_payload:BlanketType::NUMBER AS blankettype,
                data_payload:BranchID::NUMBER AS branchid,
                data_payload:isExemptEmployer_icare::BOOLEAN AS isexemptemployer_icare,
                CAST(data_payload:TotalPremiumAdjustment AS NUMBER(18,2)) AS totalpremiumadjustment,
                CAST(data_payload:LegacyClaimPerMeasureCost AS NUMBER(18,2)) AS legacyclaimpermeasurecost,
                data_payload:InitialCoveragesCreated::BOOLEAN AS initialcoveragescreated,
                data_payload:LegacyClaimPerMeasureCost_cur::NUMBER AS legacyclaimpermeasurecost_cur,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                CAST(data_payload:CustomAutoSymbolDesc::TEXT AS VARCHAR(255)) AS customautosymboldesc,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                TO_TIMESTAMP_TZ(data_payload:AutoSymbolsManualEditDate::NUMBER/1000) AS autosymbolsmanualeditdate,
                CAST(data_payload:LegacyPDCost AS NUMBER(18,2)) AS legacypdcost,
                data_payload:LegacyPDCost_cur::NUMBER AS legacypdcost_cur,
                data_payload:Fleet::NUMBER AS fleet,
                data_payload:ViewBundledCoverages::BOOLEAN AS viewbundledcoverages,
                TO_TIMESTAMP_TZ(data_payload:RetroactiveDate::NUMBER/1000) AS retroactivedate,
                CAST(data_payload:LegacyPremAdjContCost AS NUMBER(18,2)) AS legacypremadjcontcost,
                data_payload:LegacyPremAdjContCost_cur::NUMBER AS legacypremadjcontcost_cur,
                TO_TIMESTAMP_TZ(data_payload:EffectiveDate::NUMBER/1000) AS effectivedate,
                CAST(data_payload:LegacyClaimsPerfRateCost AS NUMBER(18,2)) AS legacyclaimsperfratecost,
                data_payload:LegacyClaimsPerfRateCost_cur::NUMBER AS legacyclaimsperfratecost_cur,
                data_payload:EquipmentAutoNumberSeq::NUMBER AS equipmentautonumberseq,
                TO_TIMESTAMP_TZ(data_payload:ExpirationDate::NUMBER/1000) AS expirationdate,
                CAST(data_payload:LegacyESICost AS NUMBER(18,2)) AS legacyesicost,
                data_payload:LegacyESICost_cur::NUMBER AS legacyesicost_cur,
                TO_TIMESTAMP_TZ(data_payload:ClaimsMadeOrigEffDate::NUMBER/1000) AS claimsmadeorigeffdate,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                CAST(data_payload:LegacyESRCost AS NUMBER(18,2)) AS legacyesrcost,
                data_payload:GoverningClass::NUMBER AS governingclass,
                data_payload:LegacyESRCost_cur::NUMBER AS legacyesrcost_cur,
                data_payload:ChangeType::NUMBER AS changetype,
                CAST(data_payload:ManuscriptOptionDesc::TEXT AS VARCHAR(16777216)) AS manuscriptoptiondesc,
                data_payload:PolicyType::NUMBER AS policytype,
                data_payload:InitialConditionsCreated::BOOLEAN AS initialconditionscreated,
                data_payload:BasedOnID::NUMBER AS basedonid,
                CAST(data_payload:LegacyDustDiseaseCost AS NUMBER(18,2)) AS legacydustdiseasecost,
                data_payload:LegacyDustDiseaseCost_cur::NUMBER AS legacydustdiseasecost_cur,
                data_payload:CPBlanketAutoNumberSeq::NUMBER AS cpblanketautonumberseq,
                data_payload:Subtype::NUMBER AS subtype,
                data_payload:PreferredCoverageCurrency::NUMBER AS preferredcoveragecurrency,
                CAST(data_payload:PatternCode::TEXT AS VARCHAR(64)) AS patterncode,
                data_payload:CRMigrated::BOOLEAN AS crmigrated,
                data_payload:PremiumCapped_icare::BOOLEAN AS premiumcapped_icare,
                data_payload:OverrideReason::NUMBER AS overridereason,
                CAST(data_payload:AdjPremiumPercRate_icare AS NUMBER(18,8)) AS adjpremiumpercrate_icare,
                CAST(data_payload:FinalPremiumPercRate_icare AS NUMBER(18,8)) AS finalpremiumpercrate_icare,
                CAST(data_payload:MixedWICPremiumPercRate_icare AS NUMBER(18,8)) AS mixedwicpremiumpercrate_icare,
                CAST(data_payload:PremiumPercRate_icare AS NUMBER(18,8)) AS premiumpercrate_icare,
                data_payload:NotCappedForUWReason_icare::BOOLEAN AS notcappedforuwreason_icare,
                CAST(data_payload:CappingThreshold_icare AS NUMBER(12,3)) AS cappingthreshold_icare,
                CAST(data_payload:ManAdjPremiumPercRate_icare AS NUMBER(18,8)) AS manadjpremiumpercrate_icare,
                data_payload:isAdaptiveMaxApplied_icare::BOOLEAN AS isadaptivemaxapplied_icare,
                data_payload:CappingType_icare::NUMBER AS cappingtype_icare,
                data_payload:ChangesInPPRAndCPR::BOOLEAN AS changesinpprandcpr,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwpc', 'pc_policyline') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                CAST($1:legacyappincentivecost AS NUMBER(18,2)) AS legacyappincentivecost,
                $1:smallbusinesstype::NUMBER AS smallbusinesstype,
                $1:legacyappincentivecost_cur::NUMBER AS legacyappincentivecost_cur,
                $1:locationlimits::BOOLEAN AS locationlimits,
                $1:fixedid::NUMBER AS fixedid,
                $1:glcoverageform::NUMBER AS glcoverageform,
                CAST($1:premiumadjustmentcontribution AS NUMBER(18,2)) AS premiumadjustmentcontribution,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:id::NUMBER AS id,
                $1:initialexclusionscreated::BOOLEAN AS initialexclusionscreated,
                $1:createuserid::NUMBER AS createuserid,
                $1:pollutioncleanupexp::BOOLEAN AS pollutioncleanupexp,
                $1:beanversion::NUMBER AS beanversion,
                CAST($1:legacyrtwicost AS NUMBER(18,2)) AS legacyrtwicost,
                CAST($1:legacyclaimsperfadjcost AS NUMBER(18,2)) AS legacyclaimsperfadjcost,
                $1:legacyrtwicost_cur::NUMBER AS legacyrtwicost_cur,
                $1:legacyclaimsperfadjcost_cur::NUMBER AS legacyclaimsperfadjcost_cur,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:numaddinsured::NUMBER AS numaddinsured,
                CAST($1:manuscriptpremium AS NUMBER(18,2)) AS manuscriptpremium,
                $1:manuscriptpremium_cur::NUMBER AS manuscriptpremium_cur,
                $1:splitlimits::BOOLEAN AS splitlimits,
                $1:referencedateinternal::TIMESTAMP_TZ AS referencedateinternal,
                CAST($1:legacybasictariffcost AS NUMBER(18,2)) AS legacybasictariffcost,
                $1:legacybasictariffcost_cur::NUMBER AS legacybasictariffcost_cur,
                $1:businessvehicleautonumberseq::NUMBER AS businessvehicleautonumberseq,
                $1:personalvehicleautonumberseq::NUMBER AS personalvehicleautonumberseq,
                CAST($1:legacyminesafetycost AS NUMBER(18,2)) AS legacyminesafetycost,
                $1:legacyminesafetycost_cur::NUMBER AS legacyminesafetycost_cur,
                $1:blankettype::NUMBER AS blankettype,
                $1:branchid::NUMBER AS branchid,
                $1:isexemptemployer_icare::BOOLEAN AS isexemptemployer_icare,
                CAST($1:totalpremiumadjustment AS NUMBER(18,2)) AS totalpremiumadjustment,
                CAST($1:legacyclaimpermeasurecost AS NUMBER(18,2)) AS legacyclaimpermeasurecost,
                $1:initialcoveragescreated::BOOLEAN AS initialcoveragescreated,
                $1:legacyclaimpermeasurecost_cur::NUMBER AS legacyclaimpermeasurecost_cur,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                CAST($1:customautosymboldesc::TEXT AS VARCHAR(255)) AS customautosymboldesc,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:autosymbolsmanualeditdate::TIMESTAMP_TZ AS autosymbolsmanualeditdate,
                CAST($1:legacypdcost AS NUMBER(18,2)) AS legacypdcost,
                $1:legacypdcost_cur::NUMBER AS legacypdcost_cur,
                $1:fleet::NUMBER AS fleet,
                $1:viewbundledcoverages::BOOLEAN AS viewbundledcoverages,
                $1:retroactivedate::TIMESTAMP_TZ AS retroactivedate,
                CAST($1:legacypremadjcontcost AS NUMBER(18,2)) AS legacypremadjcontcost,
                $1:legacypremadjcontcost_cur::NUMBER AS legacypremadjcontcost_cur,
                $1:effectivedate::TIMESTAMP_TZ AS effectivedate,
                CAST($1:legacyclaimsperfratecost AS NUMBER(18,2)) AS legacyclaimsperfratecost,
                $1:legacyclaimsperfratecost_cur::NUMBER AS legacyclaimsperfratecost_cur,
                $1:equipmentautonumberseq::NUMBER AS equipmentautonumberseq,
                $1:expirationdate::TIMESTAMP_TZ AS expirationdate,
                CAST($1:legacyesicost AS NUMBER(18,2)) AS legacyesicost,
                $1:legacyesicost_cur::NUMBER AS legacyesicost_cur,
                $1:claimsmadeorigeffdate::TIMESTAMP_TZ AS claimsmadeorigeffdate,
                $1:archivepartition::NUMBER AS archivepartition,
                CAST($1:legacyesrcost AS NUMBER(18,2)) AS legacyesrcost,
                $1:governingclass::NUMBER AS governingclass,
                $1:legacyesrcost_cur::NUMBER AS legacyesrcost_cur,
                $1:changetype::NUMBER AS changetype,
                CAST($1:manuscriptoptiondesc::TEXT AS VARCHAR(16777216)) AS manuscriptoptiondesc,
                $1:policytype::NUMBER AS policytype,
                $1:initialconditionscreated::BOOLEAN AS initialconditionscreated,
                $1:basedonid::NUMBER AS basedonid,
                CAST($1:legacydustdiseasecost AS NUMBER(18,2)) AS legacydustdiseasecost,
                $1:legacydustdiseasecost_cur::NUMBER AS legacydustdiseasecost_cur,
                $1:cpblanketautonumberseq::NUMBER AS cpblanketautonumberseq,
                $1:subtype::NUMBER AS subtype,
                $1:preferredcoveragecurrency::NUMBER AS preferredcoveragecurrency,
                CAST($1:patterncode::TEXT AS VARCHAR(64)) AS patterncode,
                $1:crmigrated::BOOLEAN AS crmigrated,
                $1:premiumcapped_icare::BOOLEAN AS premiumcapped_icare,
                $1:overridereason::NUMBER AS overridereason,
                CAST($1:adjpremiumpercrate_icare AS NUMBER(18,8)) AS adjpremiumpercrate_icare,
                CAST($1:finalpremiumpercrate_icare AS NUMBER(18,8)) AS finalpremiumpercrate_icare,
                CAST($1:mixedwicpremiumpercrate_icare AS NUMBER(18,8)) AS mixedwicpremiumpercrate_icare,
                CAST($1:premiumpercrate_icare AS NUMBER(18,8)) AS premiumpercrate_icare,
                $1:notcappedforuwreason_icare::BOOLEAN AS notcappedforuwreason_icare,
                CAST($1:cappingthreshold_icare AS NUMBER(12,3)) AS cappingthreshold_icare,
                CAST($1:manadjpremiumpercrate_icare AS NUMBER(18,8)) AS manadjpremiumpercrate_icare,
                $1:isadaptivemaxapplied_icare::BOOLEAN AS isadaptivemaxapplied_icare,
                $1:cappingtype_icare::NUMBER AS cappingtype_icare,
                $1:changesinpprandcpr::BOOLEAN AS changesinpprandcpr,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwpc', 'pc_policyline') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS policyline_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'legacyappincentivecost',
                        'smallbusinesstype',
                        'legacyappincentivecost_cur',
                        'locationlimits',
                        'fixedid',
                        'glcoverageform',
                        'premiumadjustmentcontribution',
                        'updatetime',
                        'initialexclusionscreated',
                        'createuserid',
                        'pollutioncleanupexp',
                        'beanversion',
                        'legacyrtwicost',
                        'legacyclaimsperfadjcost',
                        'legacyrtwicost_cur',
                        'legacyclaimsperfadjcost_cur',
                        'updateuserid',
                        'numaddinsured',
                        'manuscriptpremium',
                        'manuscriptpremium_cur',
                        'splitlimits',
                        'referencedateinternal',
                        'legacybasictariffcost',
                        'legacybasictariffcost_cur',
                        'businessvehicleautonumberseq',
                        'personalvehicleautonumberseq',
                        'legacyminesafetycost',
                        'legacyminesafetycost_cur',
                        'blankettype',
                        'branchid',
                        'isexemptemployer_icare',
                        'totalpremiumadjustment',
                        'legacyclaimpermeasurecost',
                        'initialcoveragescreated',
                        'legacyclaimpermeasurecost_cur',
                        'publicid',
                        'customautosymboldesc',
                        'createtime',
                        'autosymbolsmanualeditdate',
                        'legacypdcost',
                        'legacypdcost_cur',
                        'fleet',
                        'viewbundledcoverages',
                        'retroactivedate',
                        'legacypremadjcontcost',
                        'legacypremadjcontcost_cur',
                        'effectivedate',
                        'legacyclaimsperfratecost',
                        'legacyclaimsperfratecost_cur',
                        'equipmentautonumberseq',
                        'expirationdate',
                        'legacyesicost',
                        'legacyesicost_cur',
                        'claimsmadeorigeffdate',
                        'archivepartition',
                        'legacyesrcost',
                        'governingclass',
                        'legacyesrcost_cur',
                        'changetype',
                        'manuscriptoptiondesc',
                        'policytype',
                        'initialconditionscreated',
                        'basedonid',
                        'legacydustdiseasecost',
                        'legacydustdiseasecost_cur',
                        'cpblanketautonumberseq',
                        'subtype',
                        'preferredcoveragecurrency',
                        'patterncode',
                        'crmigrated',
                        'premiumcapped_icare',
                        'overridereason',
                        'adjpremiumpercrate_icare',
                        'finalpremiumpercrate_icare',
                        'mixedwicpremiumpercrate_icare',
                        'premiumpercrate_icare',
                        'notcappedforuwreason_icare',
                        'cappingthreshold_icare',
                        'manadjpremiumpercrate_icare',
                        'isadaptivemaxapplied_icare',
                        'cappingtype_icare',
                        'changesinpprandcpr'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) as record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}