{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for pcx_crprojectcov_icare.
                                                crprojectcov_icare_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["landing", "gwpc", "policy_centre", "non_business_critical", "pcx_crprojectcov_icare"]
) }}


WITH cte_source_data AS 
(

            SELECT
                CAST(data_payload:DirectTerm5 AS NUMBER(20,4)) AS directterm5,
                CAST(data_payload:DirectTerm6 AS NUMBER(20,4)) AS directterm6,
                data_payload:DirectTerm11Avl::BOOLEAN AS directterm11avl,
                CAST(data_payload:DirectTerm7 AS NUMBER(20,4)) AS directterm7,
                CAST(data_payload:DirectTerm8 AS NUMBER(20,4)) AS directterm8,
                CAST(data_payload:DirectTerm9 AS NUMBER(20,4)) AS directterm9,
                data_payload:ChoiceTerm13Avl::BOOLEAN AS choiceterm13avl,
                data_payload:ChoiceTerm9Avl::BOOLEAN AS choiceterm9avl,
                data_payload:FixedID::NUMBER AS fixedid,
                data_payload:ChoiceTerm5Avl::BOOLEAN AS choiceterm5avl,
                data_payload:Currency::NUMBER AS currency,
                data_payload:ChoiceTerm1Avl::BOOLEAN AS choiceterm1avl,
                data_payload:DirectTerm7Avl::BOOLEAN AS directterm7avl,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:DirectTerm3Avl::BOOLEAN AS directterm3avl,
                data_payload:BooleanTerm1Avl::BOOLEAN AS booleanterm1avl,
                data_payload:ID::NUMBER AS id,
                data_payload:BooleanTerm1::BOOLEAN AS booleanterm1,
                data_payload:BooleanTerm2::BOOLEAN AS booleanterm2,
                data_payload:BooleanTerm3::BOOLEAN AS booleanterm3,
                data_payload:DateTerm1Avl::BOOLEAN AS dateterm1avl,
                data_payload:CreateUserID::NUMBER AS createuserid,
                data_payload:DirectTerm10Avl::BOOLEAN AS directterm10avl,
                data_payload:ChoiceTerm16Avl::BOOLEAN AS choiceterm16avl,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:ChoiceTerm12Avl::BOOLEAN AS choiceterm12avl,
                data_payload:ChoiceTerm8Avl::BOOLEAN AS choiceterm8avl,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                data_payload:ChoiceTerm4Avl::BOOLEAN AS choiceterm4avl,
                CAST(data_payload:DirectTerm10 AS NUMBER(20,4)) AS directterm10,
                CAST(data_payload:DirectTerm11 AS NUMBER(20,4)) AS directterm11,
                TO_TIMESTAMP_TZ(data_payload:ReferenceDateInternal::NUMBER/1000) AS referencedateinternal,
                data_payload:DirectTerm6Avl::BOOLEAN AS directterm6avl,
                data_payload:DirectTerm2Avl::BOOLEAN AS directterm2avl,
                data_payload:BranchID::NUMBER AS branchid,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                CAST(data_payload:ChoiceTerm1::TEXT AS VARCHAR(64)) AS choiceterm1,
                CAST(data_payload:ChoiceTerm2::TEXT AS VARCHAR(64)) AS choiceterm2,
                CAST(data_payload:ChoiceTerm3::TEXT AS VARCHAR(64)) AS choiceterm3,
                data_payload:ChoiceTerm15Avl::BOOLEAN AS choiceterm15avl,
                CAST(data_payload:ChoiceTerm4::TEXT AS VARCHAR(64)) AS choiceterm4,
                CAST(data_payload:ChoiceTerm5::TEXT AS VARCHAR(64)) AS choiceterm5,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                CAST(data_payload:ChoiceTerm6::TEXT AS VARCHAR(64)) AS choiceterm6,
                CAST(data_payload:ChoiceTerm7::TEXT AS VARCHAR(64)) AS choiceterm7,
                data_payload:CRProject::NUMBER AS crproject,
                data_payload:ChoiceTerm11Avl::BOOLEAN AS choiceterm11avl,
                CAST(data_payload:ChoiceTerm8::TEXT AS VARCHAR(64)) AS choiceterm8,
                CAST(data_payload:ChoiceTerm9::TEXT AS VARCHAR(64)) AS choiceterm9,
                data_payload:ChoiceTerm7Avl::BOOLEAN AS choiceterm7avl,
                data_payload:ChoiceTerm3Avl::BOOLEAN AS choiceterm3avl,
                data_payload:DirectTerm9Avl::BOOLEAN AS directterm9avl,
                TO_TIMESTAMP_TZ(data_payload:EffectiveDate::NUMBER/1000) AS effectivedate,
                data_payload:DirectTerm5Avl::BOOLEAN AS directterm5avl,
                TO_TIMESTAMP_TZ(data_payload:DateTerm1::NUMBER/1000) AS dateterm1,
                data_payload:BooleanTerm3Avl::BOOLEAN AS booleanterm3avl,
                TO_TIMESTAMP_TZ(data_payload:DateTerm2::NUMBER/1000) AS dateterm2,
                data_payload:DirectTerm1Avl::BOOLEAN AS directterm1avl,
                TO_TIMESTAMP_TZ(data_payload:ExpirationDate::NUMBER/1000) AS expirationdate,
                data_payload:ChoiceTerm14Avl::BOOLEAN AS choiceterm14avl,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                data_payload:ChangeType::NUMBER AS changetype,
                data_payload:ChoiceTerm10Avl::BOOLEAN AS choiceterm10avl,
                CAST(data_payload:ChoiceTerm10::TEXT AS VARCHAR(64)) AS choiceterm10,
                data_payload:BasedOnID::NUMBER AS basedonid,
                CAST(data_payload:ChoiceTerm11::TEXT AS VARCHAR(64)) AS choiceterm11,
                CAST(data_payload:ChoiceTerm12::TEXT AS VARCHAR(64)) AS choiceterm12,
                data_payload:ChoiceTerm6Avl::BOOLEAN AS choiceterm6avl,
                CAST(data_payload:ChoiceTerm13::TEXT AS VARCHAR(64)) AS choiceterm13,
                CAST(data_payload:ChoiceTerm14::TEXT AS VARCHAR(64)) AS choiceterm14,
                CAST(data_payload:ChoiceTerm15::TEXT AS VARCHAR(64)) AS choiceterm15,
                data_payload:ChoiceTerm2Avl::BOOLEAN AS choiceterm2avl,
                CAST(data_payload:ChoiceTerm16::TEXT AS VARCHAR(64)) AS choiceterm16,
                data_payload:DirectTerm8Avl::BOOLEAN AS directterm8avl,
                data_payload:DirectTerm4Avl::BOOLEAN AS directterm4avl,
                data_payload:BooleanTerm2Avl::BOOLEAN AS booleanterm2avl,
                data_payload:Subtype::NUMBER AS subtype,
                CAST(data_payload:DirectTerm1 AS NUMBER(20,4)) AS directterm1,
                CAST(data_payload:PatternCode::TEXT AS VARCHAR(64)) AS patterncode,
                CAST(data_payload:DirectTerm2 AS NUMBER(20,4)) AS directterm2,
                CAST(data_payload:DirectTerm3 AS NUMBER(20,4)) AS directterm3,
                CAST(data_payload:DirectTerm4 AS NUMBER(20,4)) AS directterm4,
                data_payload:DateTerm2Avl::BOOLEAN AS dateterm2avl,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwpc', 'pcx_crprojectcov_icare') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                CAST($1:directterm5 AS NUMBER(20,4)) AS directterm5,
                CAST($1:directterm6 AS NUMBER(20,4)) AS directterm6,
                $1:directterm11avl::BOOLEAN AS directterm11avl,
                CAST($1:directterm7 AS NUMBER(20,4)) AS directterm7,
                CAST($1:directterm8 AS NUMBER(20,4)) AS directterm8,
                CAST($1:directterm9 AS NUMBER(20,4)) AS directterm9,
                $1:choiceterm13avl::BOOLEAN AS choiceterm13avl,
                $1:choiceterm9avl::BOOLEAN AS choiceterm9avl,
                $1:fixedid::NUMBER AS fixedid,
                $1:choiceterm5avl::BOOLEAN AS choiceterm5avl,
                $1:currency::NUMBER AS currency,
                $1:choiceterm1avl::BOOLEAN AS choiceterm1avl,
                $1:directterm7avl::BOOLEAN AS directterm7avl,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:directterm3avl::BOOLEAN AS directterm3avl,
                $1:booleanterm1avl::BOOLEAN AS booleanterm1avl,
                $1:id::NUMBER AS id,
                $1:booleanterm1::BOOLEAN AS booleanterm1,
                $1:booleanterm2::BOOLEAN AS booleanterm2,
                $1:booleanterm3::BOOLEAN AS booleanterm3,
                $1:dateterm1avl::BOOLEAN AS dateterm1avl,
                $1:createuserid::NUMBER AS createuserid,
                $1:directterm10avl::BOOLEAN AS directterm10avl,
                $1:choiceterm16avl::BOOLEAN AS choiceterm16avl,
                $1:beanversion::NUMBER AS beanversion,
                $1:choiceterm12avl::BOOLEAN AS choiceterm12avl,
                $1:choiceterm8avl::BOOLEAN AS choiceterm8avl,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:choiceterm4avl::BOOLEAN AS choiceterm4avl,
                CAST($1:directterm10 AS NUMBER(20,4)) AS directterm10,
                CAST($1:directterm11 AS NUMBER(20,4)) AS directterm11,
                $1:referencedateinternal::TIMESTAMP_TZ AS referencedateinternal,
                $1:directterm6avl::BOOLEAN AS directterm6avl,
                $1:directterm2avl::BOOLEAN AS directterm2avl,
                $1:branchid::NUMBER AS branchid,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                CAST($1:choiceterm1::TEXT AS VARCHAR(64)) AS choiceterm1,
                CAST($1:choiceterm2::TEXT AS VARCHAR(64)) AS choiceterm2,
                CAST($1:choiceterm3::TEXT AS VARCHAR(64)) AS choiceterm3,
                $1:choiceterm15avl::BOOLEAN AS choiceterm15avl,
                CAST($1:choiceterm4::TEXT AS VARCHAR(64)) AS choiceterm4,
                CAST($1:choiceterm5::TEXT AS VARCHAR(64)) AS choiceterm5,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                CAST($1:choiceterm6::TEXT AS VARCHAR(64)) AS choiceterm6,
                CAST($1:choiceterm7::TEXT AS VARCHAR(64)) AS choiceterm7,
                $1:crproject::NUMBER AS crproject,
                $1:choiceterm11avl::BOOLEAN AS choiceterm11avl,
                CAST($1:choiceterm8::TEXT AS VARCHAR(64)) AS choiceterm8,
                CAST($1:choiceterm9::TEXT AS VARCHAR(64)) AS choiceterm9,
                $1:choiceterm7avl::BOOLEAN AS choiceterm7avl,
                $1:choiceterm3avl::BOOLEAN AS choiceterm3avl,
                $1:directterm9avl::BOOLEAN AS directterm9avl,
                $1:effectivedate::TIMESTAMP_TZ AS effectivedate,
                $1:directterm5avl::BOOLEAN AS directterm5avl,
                $1:dateterm1::TIMESTAMP_TZ AS dateterm1,
                $1:booleanterm3avl::BOOLEAN AS booleanterm3avl,
                $1:dateterm2::TIMESTAMP_TZ AS dateterm2,
                $1:directterm1avl::BOOLEAN AS directterm1avl,
                $1:expirationdate::TIMESTAMP_TZ AS expirationdate,
                $1:choiceterm14avl::BOOLEAN AS choiceterm14avl,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:changetype::NUMBER AS changetype,
                $1:choiceterm10avl::BOOLEAN AS choiceterm10avl,
                CAST($1:choiceterm10::TEXT AS VARCHAR(64)) AS choiceterm10,
                $1:basedonid::NUMBER AS basedonid,
                CAST($1:choiceterm11::TEXT AS VARCHAR(64)) AS choiceterm11,
                CAST($1:choiceterm12::TEXT AS VARCHAR(64)) AS choiceterm12,
                $1:choiceterm6avl::BOOLEAN AS choiceterm6avl,
                CAST($1:choiceterm13::TEXT AS VARCHAR(64)) AS choiceterm13,
                CAST($1:choiceterm14::TEXT AS VARCHAR(64)) AS choiceterm14,
                CAST($1:choiceterm15::TEXT AS VARCHAR(64)) AS choiceterm15,
                $1:choiceterm2avl::BOOLEAN AS choiceterm2avl,
                CAST($1:choiceterm16::TEXT AS VARCHAR(64)) AS choiceterm16,
                $1:directterm8avl::BOOLEAN AS directterm8avl,
                $1:directterm4avl::BOOLEAN AS directterm4avl,
                $1:booleanterm2avl::BOOLEAN AS booleanterm2avl,
                $1:subtype::NUMBER AS subtype,
                CAST($1:directterm1 AS NUMBER(20,4)) AS directterm1,
                CAST($1:patterncode::TEXT AS VARCHAR(64)) AS patterncode,
                CAST($1:directterm2 AS NUMBER(20,4)) AS directterm2,
                CAST($1:directterm3 AS NUMBER(20,4)) AS directterm3,
                CAST($1:directterm4 AS NUMBER(20,4)) AS directterm4,
                $1:dateterm2avl::BOOLEAN AS dateterm2avl,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwpc', 'pcx_crprojectcov_icare') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS crprojectcov_icare_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'directterm5',
                        'directterm6',
                        'directterm11avl',
                        'directterm7',
                        'directterm8',
                        'directterm9',
                        'choiceterm13avl',
                        'choiceterm9avl',
                        'fixedid',
                        'choiceterm5avl',
                        'currency',
                        'choiceterm1avl',
                        'directterm7avl',
                        'updatetime',
                        'directterm3avl',
                        'booleanterm1avl',
                        'booleanterm1',
                        'booleanterm2',
                        'booleanterm3',
                        'dateterm1avl',
                        'createuserid',
                        'directterm10avl',
                        'choiceterm16avl',
                        'beanversion',
                        'choiceterm12avl',
                        'choiceterm8avl',
                        'updateuserid',
                        'choiceterm4avl',
                        'directterm10',
                        'directterm11',
                        'referencedateinternal',
                        'directterm6avl',
                        'directterm2avl',
                        'branchid',
                        'publicid',
                        'choiceterm1',
                        'choiceterm2',
                        'choiceterm3',
                        'choiceterm15avl',
                        'choiceterm4',
                        'choiceterm5',
                        'createtime',
                        'choiceterm6',
                        'choiceterm7',
                        'crproject',
                        'choiceterm11avl',
                        'choiceterm8',
                        'choiceterm9',
                        'choiceterm7avl',
                        'choiceterm3avl',
                        'directterm9avl',
                        'effectivedate',
                        'directterm5avl',
                        'dateterm1',
                        'booleanterm3avl',
                        'dateterm2',
                        'directterm1avl',
                        'expirationdate',
                        'choiceterm14avl',
                        'archivepartition',
                        'changetype',
                        'choiceterm10avl',
                        'choiceterm10',
                        'basedonid',
                        'choiceterm11',
                        'choiceterm12',
                        'choiceterm6avl',
                        'choiceterm13',
                        'choiceterm14',
                        'choiceterm15',
                        'choiceterm2avl',
                        'choiceterm16',
                        'directterm8avl',
                        'directterm4avl',
                        'booleanterm2avl',
                        'subtype',
                        'directterm1',
                        'patterncode',
                        'directterm2',
                        'directterm3',
                        'directterm4',
                        'dateterm2avl'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) as record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}