{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for bc_invoiceitem.
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                record_insertion_date: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDA goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    incremental_strategy='append',
    on_schema_change='append_new_columns',
    tags=["landing", "gwbc", "billing_centre", "non_business_critical"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                data_payload:InstallmentNumber::NUMBER AS installmentnumber,
                CAST(data_payload:PrimaryCommissionAmount AS NUMBER(18,2)) AS primarycommissionamount,
                data_payload:PrimaryCommissionAmount_cur::NUMBER AS primarycommissionamount_cur,
                data_payload:InvoiceID::NUMBER AS invoiceid,
                data_payload:LineItemNumber::NUMBER AS lineitemnumber,
                data_payload:Currency::NUMBER AS currency,
                CAST(data_payload:GrossAmountWrittenOff AS NUMBER(18,2)) AS grossamountwrittenoff,
                data_payload:GrossAmountWrittenOff_cur::NUMBER AS grossamountwrittenoff_cur,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:ID::NUMBER AS id,
                data_payload:CreateUserID::NUMBER AS createuserid,
                CAST(data_payload:PaidAmount AS NUMBER(18,2)) AS paidamount,
                data_payload:PaidAmount_cur::NUMBER AS paidamount_cur,
                data_payload:InvoiceDateOverride::NUMBER AS invoicedateoverride,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:Retired::NUMBER AS retired,
                data_payload:HasChargeBilledTransaction::BOOLEAN AS haschargebilledtransaction,
                CAST(data_payload:CustomPaymentGroup::TEXT AS VARCHAR(1333)) AS custompaymentgroup,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                CAST(data_payload:PromisedAndPaidAmount AS NUMBER(18,2)) AS promisedandpaidamount,
                data_payload:PromisedAndPaidAmount_cur::NUMBER AS promisedandpaidamount_cur,
                data_payload:CanBePromisedMoreByAgencyBill::BOOLEAN AS canbepromisedmorebyagencybill,
                data_payload:PaymentExceptionLock::NUMBER AS paymentexceptionlock,
                data_payload:GrossSettled::BOOLEAN AS grosssettled,
                TO_TIMESTAMP_TZ(data_payload:PaymentExceptionDate::NUMBER/1000) AS paymentexceptiondate,
                data_payload:HasChargeDueTransaction::BOOLEAN AS haschargeduetransaction,
                data_payload:Type::NUMBER AS type,
                data_payload:PromiseExceptionLock::NUMBER AS promiseexceptionlock,
                data_payload:PrimaryWrittenOffCmsn_cur::NUMBER AS primarywrittenoffcmsn_cur,
                TO_TIMESTAMP_TZ(data_payload:PromiseExceptionDate::NUMBER/1000) AS promiseexceptiondate,
                data_payload:Reversed::BOOLEAN AS reversed,
                CAST(data_payload:ExceptionComments::TEXT AS VARCHAR(1333)) AS exceptioncomments,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                TO_TIMESTAMP_TZ(data_payload:EventDate::NUMBER/1000) AS eventdate,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                data_payload:PolicyPeriodID::NUMBER AS policyperiodid,
                data_payload:ChargeID::NUMBER AS chargeid,
                data_payload:HasBeenPaymentException::BOOLEAN AS hasbeenpaymentexception,
                CAST(data_payload:PromisedCommission AS NUMBER(18,2)) AS promisedcommission,
                data_payload:PromisedCommission_cur::NUMBER AS promisedcommission_cur,
                data_payload:CanBePaidMoreByAgencyBill::BOOLEAN AS canbepaidmorebyagencybill,
                CAST(data_payload:Amount AS NUMBER(18,2)) AS amount,
                data_payload:Amount_cur::NUMBER AS amount_cur,
                TO_TIMESTAMP_TZ(data_payload:PaymentExceptionLockDate::NUMBER/1000) AS paymentexceptionlockdate,
                CAST(data_payload:PrimaryWrittenOffCommission AS NUMBER(18,2)) AS primarywrittenoffcommission,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                CAST(data_payload:PrimaryDirectBillEarned AS NUMBER(18,2)) AS primarydirectbillearned,
                data_payload:PrimaryDirectBillEarned_cur::NUMBER AS primarydirectbillearned_cur,
                TO_TIMESTAMP_TZ(data_payload:PromiseExceptionLockDate::NUMBER/1000) AS promiseexceptionlockdate,
                CAST(data_payload:PrimaryAgencyBillRetained AS NUMBER(18,2)) AS primaryagencybillretained,
                data_payload:PrimaryAgencyBillRetained_cur::NUMBER AS primaryagencybillretained_cur,
                CAST(data_payload:Comments::TEXT AS VARCHAR(1333)) AS comments,
                CAST(data_payload:Description::TEXT AS VARCHAR(1333)) AS description,
                data_payload:RCWaivedAmount_icare_cur::NUMBER AS rcwaivedamount_icare_cur,
                CAST(data_payload:WaivedAmount AS NUMBER(18,2)) AS waivedamount,
                CAST(data_payload:RCCreditNoteAmount_icare AS NUMBER(18,2)) AS rccreditnoteamount_icare,
                data_payload:RCCreditNoteAmount_icare_cur::NUMBER AS rccreditnoteamount_icare_cur,
                CAST(data_payload:RCPaymentArrangementRef_icare::TEXT AS VARCHAR(255)) AS rcpaymentarrangementref_icare,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS VARCHAR(300)) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'AVRO' as file_type,
                'GWBC' as source_system
            FROM {{ source('gwbc', 'bc_invoiceitem') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:installmentnumber::NUMBER AS installmentnumber,
                CAST($1:primarycommissionamount AS NUMBER(18,2)) AS primarycommissionamount,
                $1:primarycommissionamount_cur::NUMBER AS primarycommissionamount_cur,
                $1:invoiceid::NUMBER AS invoiceid,
                $1:lineitemnumber::NUMBER AS lineitemnumber,
                $1:currency::NUMBER AS currency,
                CAST($1:grossamountwrittenoff AS NUMBER(18,2)) AS grossamountwrittenoff,
                $1:grossamountwrittenoff_cur::NUMBER AS grossamountwrittenoff_cur,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:id::NUMBER AS id,
                $1:createuserid::NUMBER AS createuserid,
                CAST($1:paidamount AS NUMBER(18,2)) AS paidamount,
                $1:paidamount_cur::NUMBER AS paidamount_cur,
                $1:invoicedateoverride::NUMBER AS invoicedateoverride,
                $1:beanversion::NUMBER AS beanversion,
                $1:retired::NUMBER AS retired,
                $1:haschargebilledtransaction::BOOLEAN AS haschargebilledtransaction,
                CAST($1:custompaymentgroup::TEXT AS VARCHAR(1333)) AS custompaymentgroup,
                $1:updateuserid::NUMBER AS updateuserid,
                CAST($1:promisedandpaidamount AS NUMBER(18,2)) AS promisedandpaidamount,
                $1:promisedandpaidamount_cur::NUMBER AS promisedandpaidamount_cur,
                $1:canbepromisedmorebyagencybill::BOOLEAN AS canbepromisedmorebyagencybill,
                $1:paymentexceptionlock::NUMBER AS paymentexceptionlock,
                $1:grosssettled::BOOLEAN AS grosssettled,
                $1:paymentexceptiondate::TIMESTAMP_TZ AS paymentexceptiondate,
                $1:haschargeduetransaction::BOOLEAN AS haschargeduetransaction,
                $1:type::NUMBER AS type,
                $1:promiseexceptionlock::NUMBER AS promiseexceptionlock,
                $1:primarywrittenoffcmsn_cur::NUMBER AS primarywrittenoffcmsn_cur,
                $1:promiseexceptiondate::TIMESTAMP_TZ AS promiseexceptiondate,
                $1:reversed::BOOLEAN AS reversed,
                CAST($1:exceptioncomments::TEXT AS VARCHAR(1333)) AS exceptioncomments,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:eventdate::TIMESTAMP_TZ AS eventdate,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:policyperiodid::NUMBER AS policyperiodid,
                $1:chargeid::NUMBER AS chargeid,
                $1:hasbeenpaymentexception::BOOLEAN AS hasbeenpaymentexception,
                CAST($1:promisedcommission AS NUMBER(18,2)) AS promisedcommission,
                $1:promisedcommission_cur::NUMBER AS promisedcommission_cur,
                $1:canbepaidmorebyagencybill::BOOLEAN AS canbepaidmorebyagencybill,
                CAST($1:amount AS NUMBER(18,2)) AS amount,
                $1:amount_cur::NUMBER AS amount_cur,
                $1:paymentexceptionlockdate::TIMESTAMP_TZ AS paymentexceptionlockdate,
                CAST($1:primarywrittenoffcommission AS NUMBER(18,2)) AS primarywrittenoffcommission,
                $1:archivepartition::NUMBER AS archivepartition,
                CAST($1:primarydirectbillearned AS NUMBER(18,2)) AS primarydirectbillearned,
                $1:primarydirectbillearned_cur::NUMBER AS primarydirectbillearned_cur,
                $1:promiseexceptionlockdate::TIMESTAMP_TZ AS promiseexceptionlockdate,
                CAST($1:primaryagencybillretained AS NUMBER(18,2)) AS primaryagencybillretained,
                $1:primaryagencybillretained_cur::NUMBER AS primaryagencybillretained_cur,
                CAST($1:comments::TEXT AS VARCHAR(1333)) AS comments,
                CAST($1:description::TEXT AS VARCHAR(1333)) AS description,
                $1:rcwaivedamount_icare_cur::NUMBER AS rcwaivedamount_icare_cur,
                CAST($1:waivedamount AS NUMBER(18,2)) AS waivedamount,
                CAST($1:rccreditnoteamount_icare AS NUMBER(18,2)) AS rccreditnoteamount_icare,
                $1:rccreditnoteamount_icare_cur::NUMBER AS rccreditnoteamount_icare_cur,
                CAST($1:rcpaymentarrangementref_icare::TEXT AS VARCHAR(255)) AS rcpaymentarrangementref_icare,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::VARCHAR(300) as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'PARQUET' as file_type,
                'GWBC' as source_system
            FROM {{ source('gwbc', 'bc_invoiceitem') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS invoiceitem_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'installmentnumber',
                        'primarycommissionamount',
                        'primarycommissionamount_cur',
                        'invoiceid',
                        'lineitemnumber',
                        'currency',
                        'grossamountwrittenoff',
                        'grossamountwrittenoff_cur',
                        'updatetime',
                        'createuserid',
                        'paidamount',
                        'paidamount_cur',
                        'invoicedateoverride',
                        'beanversion',
                        'retired',
                        'haschargebilledtransaction',
                        'custompaymentgroup',
                        'updateuserid',
                        'promisedandpaidamount',
                        'promisedandpaidamount_cur',
                        'canbepromisedmorebyagencybill',
                        'paymentexceptionlock',
                        'grosssettled',
                        'paymentexceptiondate',
                        'haschargeduetransaction',
                        'type',
                        'promiseexceptionlock',
                        'primarywrittenoffcmsn_cur',
                        'promiseexceptiondate',
                        'reversed',
                        'exceptioncomments',
                        'publicid',
                        'eventdate',
                        'createtime',
                        'policyperiodid',
                        'chargeid',
                        'hasbeenpaymentexception',
                        'promisedcommission',
                        'promisedcommission_cur',
                        'canbepaidmorebyagencybill',
                        'amount',
                        'amount_cur',
                        'paymentexceptionlockdate',
                        'primarywrittenoffcommission',
                        'archivepartition',
                        'primarydirectbillearned',
                        'primarydirectbillearned_cur',
                        'promiseexceptionlockdate',
                        'primaryagencybillretained',
                        'primaryagencybillretained_cur',
                        'comments',
                        'description',
                        'rcwaivedamount_icare_cur',
                        'waivedamount',
                        'rccreditnoteamount_icare',
                        'rccreditnoteamount_icare_cur',
                        'rcpaymentarrangementref_icare'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
    WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}
    ORDER BY record_insertion_date
