{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for bc_billinginstruction.
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                record_insertion_date: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDA goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    incremental_strategy='append',
    on_schema_change='append_new_columns',
    tags=["landing", "gwbc", "billing_centre", "non_business_critical"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                data_payload:HoldUnbilledPremiumCharges::BOOLEAN AS holdunbilledpremiumcharges,
                CAST(data_payload:CancellationReason::TEXT AS VARCHAR(255)) AS cancellationreason,
                data_payload:AccountID::NUMBER AS accountid,
                data_payload:PaymentPlanID::NUMBER AS paymentplanid,
                data_payload:IssuanceAccountID::NUMBER AS issuanceaccountid,
                data_payload:Executed::BOOLEAN AS executed,
                data_payload:RenewalAccountID::NUMBER AS renewalaccountid,
                data_payload:Currency::NUMBER AS currency,
                data_payload:TotalPremium::BOOLEAN AS totalpremium,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:PolicyPaymentPlanID::NUMBER AS policypaymentplanid,
                data_payload:PriorPolicyPeriodID::NUMBER AS priorpolicyperiodid,
                data_payload:ID::NUMBER AS id,
                data_payload:SpecialHandling::NUMBER AS specialhandling,
                data_payload:CreateUserID::NUMBER AS createuserid,
                CAST(data_payload:OfferNumber::TEXT AS VARCHAR(255)) AS offernumber,
                data_payload:totalpremium_ha::BOOLEAN AS totalpremium_ha,
                data_payload:FinalAudit::BOOLEAN AS finalaudit,
                data_payload:BeanVersion::NUMBER AS beanversion,
                TO_TIMESTAMP_TZ(data_payload:PeriodEndDate::NUMBER/1000) AS periodenddate,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                data_payload:NewRenewalAccountID::NUMBER AS newrenewalaccountid,
                data_payload:SegregatedCollReqID::NUMBER AS segregatedcollreqid,
                data_payload:CancellationType::NUMBER AS cancellationtype,
                data_payload:totalpremium_awa::BOOLEAN AS totalpremium_awa,
                CAST(data_payload:JobNumber_icare::TEXT AS VARCHAR(255)) AS jobnumber_icare,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                data_payload:PolicyBoundOrIssue_icare::NUMBER AS policyboundorissue_icare,
                data_payload:CollateralRequirementID::NUMBER AS collateralrequirementid,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                TO_TIMESTAMP_TZ(data_payload:ModificationDate::NUMBER/1000) AS modificationdate,
                data_payload:PolicyID::NUMBER AS policyid,
                data_payload:finalaudit_awa::BOOLEAN AS finalaudit_awa,
                data_payload:IsLegacyTxn_icare::BOOLEAN AS islegacytxn_icare,
                data_payload:PremiumReportDueDateID::NUMBER AS premiumreportduedateid,
                data_payload:finalaudit_ha::BOOLEAN AS finalaudit_ha,
                data_payload:AssociatedPolicyPeriodID::NUMBER AS associatedpolicyperiodid,
                TO_TIMESTAMP_TZ(data_payload:PaymentDueDate::NUMBER/1000) AS paymentduedate,
                TO_TIMESTAMP_TZ(data_payload:BillingInstructionDate::NUMBER/1000) AS billinginstructiondate,
                CAST(data_payload:DepositRequirement AS NUMBER(18,2)) AS depositrequirement,
                data_payload:DepositRequirement_cur::NUMBER AS depositrequirement_cur,
                data_payload:PaymentReceived::BOOLEAN AS paymentreceived,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                data_payload:NewPolicyPeriodID::NUMBER AS newpolicyperiodid,
                TO_TIMESTAMP_TZ(data_payload:PeriodStartDate::NUMBER/1000) AS periodstartdate,
                data_payload:Subtype::NUMBER AS subtype,
                CAST(data_payload:Description::TEXT AS VARCHAR(255)) AS description,
                data_payload:RewriteAccountID::NUMBER AS rewriteaccountid,
                data_payload:PolicyChangeType_icare::NUMBER AS policychangetype_icare,
                CAST(data_payload:OriginalJobNumber_icare::TEXT AS VARCHAR(255)) AS originaljobnumber_icare,
                TO_TIMESTAMP_TZ(data_payload:IssuedDate_icare::NUMBER/1000) AS issueddate_icare,
                data_payload:RewriteType::NUMBER AS rewritetype,
                CAST(data_payload:FPDRevBIPublicID_icare::TEXT AS VARCHAR(255)) AS fpdrevbipublicid_icare,
                TO_TIMESTAMP_TZ(data_payload:ConfirmationDate_icare::NUMBER/1000) AS confirmationdate_icare,
                data_payload:RenewalState_icare::NUMBER AS renewalstate_icare,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS VARCHAR(300)) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'AVRO' as file_type,
                'GWBC' as source_system
            FROM {{ source('gwbc', 'bc_billinginstruction') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:holdunbilledpremiumcharges::BOOLEAN AS holdunbilledpremiumcharges,
                CAST($1:cancellationreason::TEXT AS VARCHAR(255)) AS cancellationreason,
                $1:accountid::NUMBER AS accountid,
                $1:paymentplanid::NUMBER AS paymentplanid,
                $1:issuanceaccountid::NUMBER AS issuanceaccountid,
                $1:executed::BOOLEAN AS executed,
                $1:renewalaccountid::NUMBER AS renewalaccountid,
                $1:currency::NUMBER AS currency,
                $1:totalpremium::BOOLEAN AS totalpremium,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:policypaymentplanid::NUMBER AS policypaymentplanid,
                $1:priorpolicyperiodid::NUMBER AS priorpolicyperiodid,
                $1:id::NUMBER AS id,
                $1:specialhandling::NUMBER AS specialhandling,
                $1:createuserid::NUMBER AS createuserid,
                CAST($1:offernumber::TEXT AS VARCHAR(255)) AS offernumber,
                $1:totalpremium_ha::BOOLEAN AS totalpremium_ha,
                $1:finalaudit::BOOLEAN AS finalaudit,
                $1:beanversion::NUMBER AS beanversion,
                $1:periodenddate::TIMESTAMP_TZ AS periodenddate,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:newrenewalaccountid::NUMBER AS newrenewalaccountid,
                $1:segregatedcollreqid::NUMBER AS segregatedcollreqid,
                $1:cancellationtype::NUMBER AS cancellationtype,
                $1:totalpremium_awa::BOOLEAN AS totalpremium_awa,
                CAST($1:jobnumber_icare::TEXT AS VARCHAR(255)) AS jobnumber_icare,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:policyboundorissue_icare::NUMBER AS policyboundorissue_icare,
                $1:collateralrequirementid::NUMBER AS collateralrequirementid,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:modificationdate::TIMESTAMP_TZ AS modificationdate,
                $1:policyid::NUMBER AS policyid,
                $1:finalaudit_awa::BOOLEAN AS finalaudit_awa,
                $1:islegacytxn_icare::BOOLEAN AS islegacytxn_icare,
                $1:premiumreportduedateid::NUMBER AS premiumreportduedateid,
                $1:finalaudit_ha::BOOLEAN AS finalaudit_ha,
                $1:associatedpolicyperiodid::NUMBER AS associatedpolicyperiodid,
                $1:paymentduedate::TIMESTAMP_TZ AS paymentduedate,
                $1:billinginstructiondate::TIMESTAMP_TZ AS billinginstructiondate,
                CAST($1:depositrequirement AS NUMBER(18,2)) AS depositrequirement,
                $1:depositrequirement_cur::NUMBER AS depositrequirement_cur,
                $1:paymentreceived::BOOLEAN AS paymentreceived,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:newpolicyperiodid::NUMBER AS newpolicyperiodid,
                $1:periodstartdate::TIMESTAMP_TZ AS periodstartdate,
                $1:subtype::NUMBER AS subtype,
                CAST($1:description::TEXT AS VARCHAR(255)) AS description,
                $1:rewriteaccountid::NUMBER AS rewriteaccountid,
                $1:policychangetype_icare::NUMBER AS policychangetype_icare,
                CAST($1:originaljobnumber_icare::TEXT AS VARCHAR(255)) AS originaljobnumber_icare,
                $1:issueddate_icare::TIMESTAMP_TZ AS issueddate_icare,
                $1:rewritetype::NUMBER AS rewritetype,
                CAST($1:fpdrevbipublicid_icare::TEXT AS VARCHAR(255)) AS fpdrevbipublicid_icare,
                $1:confirmationdate_icare::TIMESTAMP_TZ AS confirmationdate_icare,
                $1:renewalstate_icare::NUMBER AS renewalstate_icare,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::VARCHAR(300) as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'PARQUET' as file_type,
                'GWBC' as source_system
            FROM {{ source('gwbc', 'bc_billinginstruction') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS billinginstruction_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'holdunbilledpremiumcharges',
                        'cancellationreason',
                        'accountid',
                        'paymentplanid',
                        'issuanceaccountid',
                        'executed',
                        'renewalaccountid',
                        'currency',
                        'totalpremium',
                        'updatetime',
                        'policypaymentplanid',
                        'priorpolicyperiodid',
                        'specialhandling',
                        'createuserid',
                        'offernumber',
                        'totalpremium_ha',
                        'finalaudit',
                        'beanversion',
                        'periodenddate',
                        'updateuserid',
                        'newrenewalaccountid',
                        'segregatedcollreqid',
                        'cancellationtype',
                        'totalpremium_awa',
                        'jobnumber_icare',
                        'publicid',
                        'policyboundorissue_icare',
                        'collateralrequirementid',
                        'createtime',
                        'modificationdate',
                        'policyid',
                        'finalaudit_awa',
                        'islegacytxn_icare',
                        'premiumreportduedateid',
                        'finalaudit_ha',
                        'associatedpolicyperiodid',
                        'paymentduedate',
                        'billinginstructiondate',
                        'depositrequirement',
                        'depositrequirement_cur',
                        'paymentreceived',
                        'archivepartition',
                        'newpolicyperiodid',
                        'periodstartdate',
                        'subtype',
                        'description',
                        'rewriteaccountid',
                        'policychangetype_icare',
                        'originaljobnumber_icare',
                        'issueddate_icare',
                        'rewritetype',
                        'fpdrevbipublicid_icare',
                        'confirmationdate_icare',
                        'renewalstate_icare'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
    WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}
    ORDER BY record_insertion_date
