{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for bc_account.
                                                account_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["raw_layer", "raw_billing_centre", "billing_centre", "non_business_critical", "bc_account"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                data_payload:HeldForInvoiceSending::BOOLEAN AS heldforinvoicesending,
                data_payload:SecurityZoneID::NUMBER AS securityzoneid,
                CAST(data_payload:ACN_icare::TEXT AS VARCHAR(60)) AS acn_icare,
                data_payload:SecondTwicePerMthInvoiceDOM::NUMBER AS secondtwicepermthinvoicedom,
                data_payload:Currency::NUMBER AS currency,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:ServiceTier::NUMBER AS servicetier,
                data_payload:HiddenTAccountContainerID::NUMBER AS hiddentaccountcontainerid,
                data_payload:ID::NUMBER AS id,
                CAST(data_payload:TrustName_icare::TEXT AS VARCHAR(200)) AS trustname_icare,
                data_payload:CreateUserID::NUMBER AS createuserid,
                CAST(data_payload:DBA::TEXT AS VARCHAR(255)) AS dba,
                CAST(data_payload:FEIN::TEXT AS VARCHAR(255)) AS fein,
                data_payload:DelinquencyStatus::NUMBER AS delinquencystatus,
                TO_TIMESTAMP_TZ(data_payload:CloseDate::NUMBER/1000) AS closedate,
                CAST(data_payload:ABN_icare::TEXT AS VARCHAR(60)) AS abn_icare,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:Retired::NUMBER AS retired,
                data_payload:TrusteeType_icare::NUMBER AS trusteetype_icare,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                data_payload:Segment::NUMBER AS segment,
                CAST(data_payload:AccountNumber::TEXT AS VARCHAR(255)) AS accountnumber,
                data_payload:DelinquencyPlanID::NUMBER AS delinquencyplanid,
                CAST(data_payload:AccountName::TEXT AS VARCHAR(255)) AS accountname,
                data_payload:BillingPlanID::NUMBER AS billingplanid,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                CAST(data_payload:TrustABN_icare::TEXT AS VARCHAR(60)) AS trustabn_icare,
                data_payload:FirstTwicePerMthInvoiceDOM::NUMBER AS firsttwicepermthinvoicedom,
                data_payload:InvoiceDayOfMonth::NUMBER AS invoicedayofmonth,
                data_payload:InvoiceDayOfWeek::NUMBER AS invoicedayofweek,
                data_payload:InvoiceDeliveryType::NUMBER AS invoicedeliverytype,
                CAST(data_payload:AccountNameKanji::TEXT AS VARCHAR(255)) AS accountnamekanji,
                CAST(data_payload:FEINDenorm::TEXT AS VARCHAR(255)) AS feindenorm,
                data_payload:AllocationPlanID::NUMBER AS allocationplanid,
                data_payload:AccountType::NUMBER AS accounttype,
                data_payload:ChargeHeld::BOOLEAN AS chargeheld,
                data_payload:BillingLevel::NUMBER AS billinglevel,
                data_payload:NewPolicyPaymentDistributable::BOOLEAN AS newpolicypaymentdistributable,
                CAST(data_payload:OrganizationTypeDenorm::TEXT AS VARCHAR(255)) AS organizationtypedenorm,
                CAST(data_payload:OrganizationType::TEXT AS VARCHAR(255)) AS organizationtype,
                data_payload:DistributionLimitType::NUMBER AS distributionlimittype,
                data_payload:BillDateOrDueDateBilling::NUMBER AS billdateorduedatebilling,
                CAST(data_payload:AccountNumberDenorm::TEXT AS VARCHAR(255)) AS accountnumberdenorm,
                CAST(data_payload:AccountNameDenorm::TEXT AS VARCHAR(255)) AS accountnamedenorm,
                data_payload:Collecting::BOOLEAN AS collecting,
                TO_TIMESTAMP_TZ(data_payload:EveryOtherWeekInvoiceAnchor::NUMBER/1000) AS everyotherweekinvoiceanchor,
                data_payload:CollectionAgencyID::NUMBER AS collectionagencyid,
                CAST(data_payload:CRMUniqueID_icare::TEXT AS VARCHAR(255)) AS crmuniqueid_icare,
                CAST(data_payload:SourceSystem_icare::TEXT AS VARCHAR(20)) AS sourcesystem_icare,
                CAST(data_payload:CRN_icare::TEXT AS VARCHAR(255)) AS crn_icare,
                data_payload:CRMVersion_icare::NUMBER AS crmversion_icare,
                data_payload:OfferingType_icare::NUMBER AS offeringtype_icare,
                data_payload:LOBAccountType_icare::NUMBER AS lobaccounttype_icare,
                CAST(data_payload:TreasuryPrimeNumber_icare::TEXT AS VARCHAR(50)) AS treasuryprimenumber_icare,
                data_payload:ExcludeForReferral_Ext::BOOLEAN AS excludeforreferral_ext,
                data_payload:RNSWClosureStatus_Ext::NUMBER AS rnswclosurestatus_ext,
                data_payload:Insolvency_Ext::BOOLEAN AS insolvency_ext,
                data_payload:DisableBrokerCopy_Ext::BOOLEAN AS disablebrokercopy_ext,
                CAST(data_payload:CreationSource_Ext::TEXT AS VARCHAR(20)) AS creationsource_ext,
                data_payload:IsULAccount_Ext::BOOLEAN AS isulaccount_ext,
                data_payload:AccountStatus_Ext::NUMBER AS accountstatus_ext,
                CAST(data_payload:ABNStatus_Ext::TEXT AS VARCHAR(255)) AS abnstatus_ext,
                CAST(data_payload:ClientEngagementManager_Ext::TEXT AS VARCHAR(255)) AS clientengagementmanager_ext,
                data_payload:IsTMFAccount_Ext::BOOLEAN AS istmfaccount_ext,
                TO_TIMESTAMP_TZ(data_payload:ActiveFrom_Ext::NUMBER/1000) AS activefrom_ext,
                CAST(data_payload:IntermediaryCode_Ext::TEXT AS VARCHAR(255)) AS intermediarycode_ext,
                data_payload:AgencyType_Ext::NUMBER AS agencytype_ext,
                CAST(data_payload:BusOpsDesc_Ext::TEXT AS VARCHAR(240)) AS busopsdesc_ext,
                CAST(data_payload:Portfolio_Ext::TEXT AS VARCHAR(255)) AS portfolio_ext,
                data_payload:AccountOrgType_Ext::NUMBER AS accountorgtype_ext,
                data_payload:YearBusinessStarted_Ext::NUMBER AS yearbusinessstarted_ext,
                CAST(data_payload:AgencyCode_Ext::TEXT AS VARCHAR(60)) AS agencycode_ext,
                TO_TIMESTAMP_TZ(data_payload:ActiveTo_Ext::NUMBER/1000) AS activeto_ext,
                data_payload:AccountGroup_ExtID::NUMBER AS accountgroup_extid,
                CAST(data_payload:ICP_Ext::TEXT AS VARCHAR(15)) AS icp_ext,
                data_payload:Pool_Ext::NUMBER AS pool_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwbc', 'bc_account') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:heldforinvoicesending::BOOLEAN AS heldforinvoicesending,
                $1:securityzoneid::NUMBER AS securityzoneid,
                CAST($1:acn_icare::TEXT AS VARCHAR(60)) AS acn_icare,
                $1:secondtwicepermthinvoicedom::NUMBER AS secondtwicepermthinvoicedom,
                $1:currency::NUMBER AS currency,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:servicetier::NUMBER AS servicetier,
                $1:hiddentaccountcontainerid::NUMBER AS hiddentaccountcontainerid,
                $1:id::NUMBER AS id,
                CAST($1:trustname_icare::TEXT AS VARCHAR(200)) AS trustname_icare,
                $1:createuserid::NUMBER AS createuserid,
                CAST($1:dba::TEXT AS VARCHAR(255)) AS dba,
                CAST($1:fein::TEXT AS VARCHAR(255)) AS fein,
                $1:delinquencystatus::NUMBER AS delinquencystatus,
                $1:closedate::TIMESTAMP_TZ AS closedate,
                CAST($1:abn_icare::TEXT AS VARCHAR(60)) AS abn_icare,
                $1:beanversion::NUMBER AS beanversion,
                $1:retired::NUMBER AS retired,
                $1:trusteetype_icare::NUMBER AS trusteetype_icare,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:segment::NUMBER AS segment,
                CAST($1:accountnumber::TEXT AS VARCHAR(255)) AS accountnumber,
                $1:delinquencyplanid::NUMBER AS delinquencyplanid,
                CAST($1:accountname::TEXT AS VARCHAR(255)) AS accountname,
                $1:billingplanid::NUMBER AS billingplanid,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                CAST($1:trustabn_icare::TEXT AS VARCHAR(60)) AS trustabn_icare,
                $1:firsttwicepermthinvoicedom::NUMBER AS firsttwicepermthinvoicedom,
                $1:invoicedayofmonth::NUMBER AS invoicedayofmonth,
                $1:invoicedayofweek::NUMBER AS invoicedayofweek,
                $1:invoicedeliverytype::NUMBER AS invoicedeliverytype,
                CAST($1:accountnamekanji::TEXT AS VARCHAR(255)) AS accountnamekanji,
                CAST($1:feindenorm::TEXT AS VARCHAR(255)) AS feindenorm,
                $1:allocationplanid::NUMBER AS allocationplanid,
                $1:accounttype::NUMBER AS accounttype,
                $1:chargeheld::BOOLEAN AS chargeheld,
                $1:billinglevel::NUMBER AS billinglevel,
                $1:newpolicypaymentdistributable::BOOLEAN AS newpolicypaymentdistributable,
                CAST($1:organizationtypedenorm::TEXT AS VARCHAR(255)) AS organizationtypedenorm,
                CAST($1:organizationtype::TEXT AS VARCHAR(255)) AS organizationtype,
                $1:distributionlimittype::NUMBER AS distributionlimittype,
                $1:billdateorduedatebilling::NUMBER AS billdateorduedatebilling,
                CAST($1:accountnumberdenorm::TEXT AS VARCHAR(255)) AS accountnumberdenorm,
                CAST($1:accountnamedenorm::TEXT AS VARCHAR(255)) AS accountnamedenorm,
                $1:collecting::BOOLEAN AS collecting,
                $1:everyotherweekinvoiceanchor::TIMESTAMP_TZ AS everyotherweekinvoiceanchor,
                $1:collectionagencyid::NUMBER AS collectionagencyid,
                CAST($1:crmuniqueid_icare::TEXT AS VARCHAR(255)) AS crmuniqueid_icare,
                CAST($1:sourcesystem_icare::TEXT AS VARCHAR(20)) AS sourcesystem_icare,
                CAST($1:crn_icare::TEXT AS VARCHAR(255)) AS crn_icare,
                $1:crmversion_icare::NUMBER AS crmversion_icare,
                $1:offeringtype_icare::NUMBER AS offeringtype_icare,
                $1:lobaccounttype_icare::NUMBER AS lobaccounttype_icare,
                CAST($1:treasuryprimenumber_icare::TEXT AS VARCHAR(50)) AS treasuryprimenumber_icare,
                $1:excludeforreferral_ext::BOOLEAN AS excludeforreferral_ext,
                $1:rnswclosurestatus_ext::NUMBER AS rnswclosurestatus_ext,
                $1:insolvency_ext::BOOLEAN AS insolvency_ext,
                $1:disablebrokercopy_ext::BOOLEAN AS disablebrokercopy_ext,
                CAST($1:creationsource_ext::TEXT AS VARCHAR(20)) AS creationsource_ext,
                $1:isulaccount_ext::BOOLEAN AS isulaccount_ext,
                $1:accountstatus_ext::NUMBER AS accountstatus_ext,
                CAST($1:abnstatus_ext::TEXT AS VARCHAR(255)) AS abnstatus_ext,
                CAST($1:clientengagementmanager_ext::TEXT AS VARCHAR(255)) AS clientengagementmanager_ext,
                $1:istmfaccount_ext::BOOLEAN AS istmfaccount_ext,
                $1:activefrom_ext::TIMESTAMP_TZ AS activefrom_ext,
                CAST($1:intermediarycode_ext::TEXT AS VARCHAR(255)) AS intermediarycode_ext,
                $1:agencytype_ext::NUMBER AS agencytype_ext,
                CAST($1:busopsdesc_ext::TEXT AS VARCHAR(240)) AS busopsdesc_ext,
                CAST($1:portfolio_ext::TEXT AS VARCHAR(255)) AS portfolio_ext,
                $1:accountorgtype_ext::NUMBER AS accountorgtype_ext,
                $1:yearbusinessstarted_ext::NUMBER AS yearbusinessstarted_ext,
                CAST($1:agencycode_ext::TEXT AS VARCHAR(60)) AS agencycode_ext,
                $1:activeto_ext::TIMESTAMP_TZ AS activeto_ext,
                $1:accountgroup_extid::NUMBER AS accountgroup_extid,
                CAST($1:icp_ext::TEXT AS VARCHAR(15)) AS icp_ext,
                $1:pool_ext::NUMBER AS pool_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwbc', 'bc_account') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS account_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'heldforinvoicesending',
                        'securityzoneid',
                        'acn_icare',
                        'secondtwicepermthinvoicedom',
                        'currency',
                        'updatetime',
                        'servicetier',
                        'hiddentaccountcontainerid',
                        'trustname_icare',
                        'createuserid',
                        'dba',
                        'fein',
                        'delinquencystatus',
                        'closedate',
                        'abn_icare',
                        'beanversion',
                        'retired',
                        'trusteetype_icare',
                        'updateuserid',
                        'segment',
                        'accountnumber',
                        'delinquencyplanid',
                        'accountname',
                        'billingplanid',
                        'publicid',
                        'createtime',
                        'trustabn_icare',
                        'firsttwicepermthinvoicedom',
                        'invoicedayofmonth',
                        'invoicedayofweek',
                        'invoicedeliverytype',
                        'accountnamekanji',
                        'feindenorm',
                        'allocationplanid',
                        'accounttype',
                        'chargeheld',
                        'billinglevel',
                        'newpolicypaymentdistributable',
                        'organizationtypedenorm',
                        'organizationtype',
                        'distributionlimittype',
                        'billdateorduedatebilling',
                        'accountnumberdenorm',
                        'accountnamedenorm',
                        'collecting',
                        'everyotherweekinvoiceanchor',
                        'collectionagencyid',
                        'crmuniqueid_icare',
                        'sourcesystem_icare',
                        'crn_icare',
                        'crmversion_icare',
                        'offeringtype_icare',
                        'lobaccounttype_icare',
                        'treasuryprimenumber_icare',
                        'excludeforreferral_ext',
                        'rnswclosurestatus_ext',
                        'insolvency_ext',
                        'disablebrokercopy_ext',
                        'creationsource_ext',
                        'isulaccount_ext',
                        'accountstatus_ext',
                        'abnstatus_ext',
                        'clientengagementmanager_ext',
                        'istmfaccount_ext',
                        'activefrom_ext',
                        'intermediarycode_ext',
                        'agencytype_ext',
                        'busopsdesc_ext',
                        'portfolio_ext',
                        'accountorgtype_ext',
                        'yearbusinessstarted_ext',
                        'agencycode_ext',
                        'activeto_ext',
                        'accountgroup_extid',
                        'icp_ext',
                        'pool_ext'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) as record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}