{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for bc_invoice.
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                record_insertion_date: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDA goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    incremental_strategy='append',
    on_schema_change='append_new_columns',
    tags=["landing", "gwbc", "billing_centre", "non_business_critical"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                CAST(data_payload:NetAmountPaid AS NUMBER(18,2)) AS netamountpaid,
                data_payload:NetAmountPaid_cur::NUMBER AS netamountpaid_cur,
                data_payload:AccountID::NUMBER AS accountid,
                data_payload:Currency::NUMBER AS currency,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:ID::NUMBER AS id,
                CAST(data_payload:AmountDue AS NUMBER(18,2)) AS amountdue,
                CAST(data_payload:ColUnappliedAmount AS NUMBER(18,2)) AS colunappliedamount,
                CAST(data_payload:UnappliedAmount AS NUMBER(18,2)) AS unappliedamount,
                data_payload:AmountDue_cur::NUMBER AS amountdue_cur,
                data_payload:ColUnappliedAmount_cur::NUMBER AS colunappliedamount_cur,
                data_payload:UnappliedAmount_cur::NUMBER AS unappliedamount_cur,
                data_payload:CreateUserID::NUMBER AS createuserid,
                CAST(data_payload:ColRemainingBalance AS NUMBER(18,2)) AS colremainingbalance,
                CAST(data_payload:RemainingBalance AS NUMBER(18,2)) AS remainingbalance,
                data_payload:ColRemainingBalance_cur::NUMBER AS colremainingbalance_cur,
                data_payload:RemainingBalance_cur::NUMBER AS remainingbalance_cur,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:Retired::NUMBER AS retired,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                CAST(data_payload:NetAmount AS NUMBER(18,2)) AS netamount,
                CAST(data_payload:InvoiceNumber::TEXT AS VARCHAR(255)) AS invoicenumber,
                data_payload:NetAmount_cur::NUMBER AS netamount_cur,
                data_payload:AdHoc::BOOLEAN AS adhoc,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                data_payload:AllInvoiceItemsExactlyPaid::BOOLEAN AS allinvoiceitemsexactlypaid,
                TO_TIMESTAMP_TZ(data_payload:EventDate::NUMBER/1000) AS eventdate,
                data_payload:InvoiceStreamID::NUMBER AS invoicestreamid,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                data_payload:NumResends::NUMBER AS numresends,
                CAST(data_payload:Amount AS NUMBER(18,2)) AS amount,
                data_payload:Amount_cur::NUMBER AS amount_cur,
                TO_TIMESTAMP_TZ(data_payload:PaymentDueDate::NUMBER/1000) AS paymentduedate,
                data_payload:FrozenByArchiving::BOOLEAN AS frozenbyarchiving,
                CAST(data_payload:PrimaryDirectBillEarned AS NUMBER(18,2)) AS primarydirectbillearned,
                data_payload:PrimaryDirectBillEarned_cur::NUMBER AS primarydirectbillearned_cur,
                CAST(data_payload:NetAmountWrittenOff AS NUMBER(18,2)) AS netamountwrittenoff,
                data_payload:NetAmountWrittenOff_cur::NUMBER AS netamountwrittenoff_cur,
                data_payload:PaymentReminderEvaluator_icare::BOOLEAN AS paymentreminderevaluator_icare,
                data_payload:Status::NUMBER AS status,
                CAST(data_payload:ColOutstandingAmount AS NUMBER(18,2)) AS coloutstandingamount,
                CAST(data_payload:OutstandingAmount AS NUMBER(18,2)) AS outstandingamount,
                CAST(data_payload:InvoiceNumberDenorm::TEXT AS VARCHAR(255)) AS invoicenumberdenorm,
                data_payload:ColOutstandingAmount_cur::NUMBER AS coloutstandingamount_cur,
                data_payload:OutstandingAmount_cur::NUMBER AS outstandingamount_cur,
                data_payload:Subtype::NUMBER AS subtype,
                CAST(data_payload:Description::TEXT AS VARCHAR(1333)) AS description,
                data_payload:isCollapsedInvoice_icare::BOOLEAN AS iscollapsedinvoice_icare,
                CAST(data_payload:RecoveryInvoiceType_icare::TEXT AS VARCHAR(150)) AS recoveryinvoicetype_icare,
                CAST(data_payload:EFTRefNumber_icare::TEXT AS VARCHAR(18)) AS eftrefnumber_icare,
                CAST(data_payload:UserInputRef_icare::TEXT AS VARCHAR(255)) AS userinputref_icare,
                data_payload:initialRNQuarterly::BOOLEAN AS initialrnquarterly,
                data_payload:IncludeForReferral_Ext::BOOLEAN AS includeforreferral_ext,
                data_payload:RNSWInvoiceStatus_Ext::NUMBER AS rnswinvoicestatus_ext,
                TO_TIMESTAMP_TZ(data_payload:RNSWReferralAckDate_Ext::NUMBER/1000) AS rnswreferralackdate_ext,
                TO_TIMESTAMP_TZ(data_payload:RNSWReferralDate_Ext::NUMBER/1000) AS rnswreferraldate_ext,
                data_payload:RNSWReferralStatus_Ext::NUMBER AS rnswreferralstatus_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS VARCHAR(300)) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'AVRO' as file_type,
                'GWBC' as source_system
            FROM {{ source('gwbc', 'bc_invoice') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                CAST($1:netamountpaid AS NUMBER(18,2)) AS netamountpaid,
                $1:netamountpaid_cur::NUMBER AS netamountpaid_cur,
                $1:accountid::NUMBER AS accountid,
                $1:currency::NUMBER AS currency,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:id::NUMBER AS id,
                CAST($1:amountdue AS NUMBER(18,2)) AS amountdue,
                CAST($1:colunappliedamount AS NUMBER(18,2)) AS colunappliedamount,
                CAST($1:unappliedamount AS NUMBER(18,2)) AS unappliedamount,
                $1:amountdue_cur::NUMBER AS amountdue_cur,
                $1:colunappliedamount_cur::NUMBER AS colunappliedamount_cur,
                $1:unappliedamount_cur::NUMBER AS unappliedamount_cur,
                $1:createuserid::NUMBER AS createuserid,
                CAST($1:colremainingbalance AS NUMBER(18,2)) AS colremainingbalance,
                CAST($1:remainingbalance AS NUMBER(18,2)) AS remainingbalance,
                $1:colremainingbalance_cur::NUMBER AS colremainingbalance_cur,
                $1:remainingbalance_cur::NUMBER AS remainingbalance_cur,
                $1:beanversion::NUMBER AS beanversion,
                $1:retired::NUMBER AS retired,
                $1:updateuserid::NUMBER AS updateuserid,
                CAST($1:netamount AS NUMBER(18,2)) AS netamount,
                CAST($1:invoicenumber::TEXT AS VARCHAR(255)) AS invoicenumber,
                $1:netamount_cur::NUMBER AS netamount_cur,
                $1:adhoc::BOOLEAN AS adhoc,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:allinvoiceitemsexactlypaid::BOOLEAN AS allinvoiceitemsexactlypaid,
                $1:eventdate::TIMESTAMP_TZ AS eventdate,
                $1:invoicestreamid::NUMBER AS invoicestreamid,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                $1:numresends::NUMBER AS numresends,
                CAST($1:amount AS NUMBER(18,2)) AS amount,
                $1:amount_cur::NUMBER AS amount_cur,
                $1:paymentduedate::TIMESTAMP_TZ AS paymentduedate,
                $1:frozenbyarchiving::BOOLEAN AS frozenbyarchiving,
                CAST($1:primarydirectbillearned AS NUMBER(18,2)) AS primarydirectbillearned,
                $1:primarydirectbillearned_cur::NUMBER AS primarydirectbillearned_cur,
                CAST($1:netamountwrittenoff AS NUMBER(18,2)) AS netamountwrittenoff,
                $1:netamountwrittenoff_cur::NUMBER AS netamountwrittenoff_cur,
                $1:paymentreminderevaluator_icare::BOOLEAN AS paymentreminderevaluator_icare,
                $1:status::NUMBER AS status,
                CAST($1:coloutstandingamount AS NUMBER(18,2)) AS coloutstandingamount,
                CAST($1:outstandingamount AS NUMBER(18,2)) AS outstandingamount,
                CAST($1:invoicenumberdenorm::TEXT AS VARCHAR(255)) AS invoicenumberdenorm,
                $1:coloutstandingamount_cur::NUMBER AS coloutstandingamount_cur,
                $1:outstandingamount_cur::NUMBER AS outstandingamount_cur,
                $1:subtype::NUMBER AS subtype,
                CAST($1:description::TEXT AS VARCHAR(1333)) AS description,
                $1:iscollapsedinvoice_icare::BOOLEAN AS iscollapsedinvoice_icare,
                CAST($1:recoveryinvoicetype_icare::TEXT AS VARCHAR(150)) AS recoveryinvoicetype_icare,
                CAST($1:eftrefnumber_icare::TEXT AS VARCHAR(18)) AS eftrefnumber_icare,
                CAST($1:userinputref_icare::TEXT AS VARCHAR(255)) AS userinputref_icare,
                $1:initialrnquarterly::BOOLEAN AS initialrnquarterly,
                $1:includeforreferral_ext::BOOLEAN AS includeforreferral_ext,
                $1:rnswinvoicestatus_ext::NUMBER AS rnswinvoicestatus_ext,
                $1:rnswreferralackdate_ext::TIMESTAMP_TZ AS rnswreferralackdate_ext,
                $1:rnswreferraldate_ext::TIMESTAMP_TZ AS rnswreferraldate_ext,
                $1:rnswreferralstatus_ext::NUMBER AS rnswreferralstatus_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::VARCHAR(300) as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                metadata_row_number,
                file_ingestion_timestamp,
                'PARQUET' as file_type,
                'GWBC' as source_system
            FROM {{ source('gwbc', 'bc_invoice') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS invoice_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'netamountpaid',
                        'netamountpaid_cur',
                        'accountid',
                        'currency',
                        'updatetime',
                        'amountdue',
                        'colunappliedamount',
                        'unappliedamount',
                        'amountdue_cur',
                        'colunappliedamount_cur',
                        'unappliedamount_cur',
                        'createuserid',
                        'colremainingbalance',
                        'remainingbalance',
                        'colremainingbalance_cur',
                        'remainingbalance_cur',
                        'beanversion',
                        'retired',
                        'updateuserid',
                        'netamount',
                        'invoicenumber',
                        'netamount_cur',
                        'adhoc',
                        'publicid',
                        'allinvoiceitemsexactlypaid',
                        'eventdate',
                        'invoicestreamid',
                        'createtime',
                        'numresends',
                        'amount',
                        'amount_cur',
                        'paymentduedate',
                        'frozenbyarchiving',
                        'primarydirectbillearned',
                        'primarydirectbillearned_cur',
                        'netamountwrittenoff',
                        'netamountwrittenoff_cur',
                        'paymentreminderevaluator_icare',
                        'status',
                        'coloutstandingamount',
                        'outstandingamount',
                        'invoicenumberdenorm',
                        'coloutstandingamount_cur',
                        'outstandingamount_cur',
                        'subtype',
                        'description',
                        'iscollapsedinvoice_icare',
                        'recoveryinvoicetype_icare',
                        'eftrefnumber_icare',
                        'userinputref_icare',
                        'initialrnquarterly',
                        'includeforreferral_ext',
                        'rnswinvoicestatus_ext',
                        'rnswreferralackdate_ext',
                        'rnswreferraldate_ext',
                        'rnswreferralstatus_ext'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
    WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}
    ORDER BY record_insertion_date
