{% snapshot cc_check_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026-01-01      0.0                             SCD Type 2 snapshot for cc_check.
                                                Source: ref('stg_raw_cc_check')
                                                unique_key: check_sk (surrogate on PK 'id')
                                                check_cols: ['hash_key'] (surrogate on all business cols excl PK)
                                                hard_deletes: new_record (inserts dbt_is_deleted=True row)
                                                No code change required when PARQUET CDC goes live.
-#}

{{ config(
    target_schema='gwcc',
    unique_key='check_sk',
    strategy='check',
    alias='cc_check',
    check_cols=['hash_key'],
    hard_deletes='new_record',
    tags=['snapshot', 'claim_centre', 'business_critical', 'cc_check']
) }}

SELECT
    check_sk,
    hash_key,
    loadcommandid,
    ocr_invoice_icare,
    issuedate,
    dateofservice,
    lastpostingdate_icare,
    updatetime,
    isprimary,
    servicepdstart,
    id,
    pendescalationforbulk,
    deductiontype,
    paytodenorm,
    createuserid,
    payto,
    mailingaddressid,
    bankbranchname_icare,
    recurringcheckid,
    datepresented_icare,
    beanversion,
    abn_icare,
    commmethod_icare,
    retired,
    bankaccounttype,
    recurrence_icare,
    checkinstructions,
    updateuserid,
    dbnetamount_icare,
    invoicenumber,
    bulkinvoiceiteminfoid,
    accountname,
    foreigncurrencyamount_icare,
    payeewithnoabn_icare,
    memo,
    istotalgt82_icare,
    bankswiftcode_icare,
    portionid,
    checktype,
    mailtoaddress,
    transactionidentifier_icare,
    publicid,
    enteredtime,
    bankname,
    weeklybenefitpayeetype_icare,
    createtime,
    deductionidentifier_icare,
    checknumber,
    servicepdend,
    bankroutingnumber,
    emailaddress_icare,
    servicesprovidedoverseas_icare,
    currencytransacted_icare,
    deliverymethod,
    originalmigratedstatus_icare,
    claimid,
    aggregateremittance_icare,
    westpacid_icare,
    groupid,
    registeredforgst_icare,
    datepaymenttransacted_icare,
    accrued_icare,
    scheduledsenddate,
    isinvoiceissuedto_icare,
    previouschecktype_icare,
    reportableamount,
    paymentmethod,
    archivepartition,
    gstmethodpel_ext,
    checkbatching,
    bankaccount,
    mailto,
    status,
    comments,
    checksetid,
    reportability,
    voidedpaymentnumber_icare,
    bankaccountnumber,
    prepostpayg_icare,
    gstpaymentclasspel_ext,
    claimcontactid,
    paymentsource_icare,
    colpaygwithholdvariation_icare,
    paygwithholdvariation_icare,
    camtvoiddate_icare,
    rejectionreason_ext,
    ismsppayment_ext,
    overrideautowagecalc_ext,
    recalculatedeductions_ext,
    legacyupdatetime_ext,
    ismigrated_ext,
    legacycreatetime_ext,
    'GWCC' AS source_system,
    gwcbi_connector_ts_ms,
    gwcbi_lsn,
    gwcbi_operation,
    gwcbi_payload_ts_ms,
    gwcbi_seqval,
    gwcbi_seqval_hex,
    gwcbi_tx_id,
    metadata_file_name,
    file_ingestion_timestamp
FROM {{ ref('stg_raw_cc_check') }}

{% endsnapshot %}