{% snapshot cc_contact_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026-01-01      0.0                             SCD Type 2 snapshot for cc_contact.
                                                Source: ref('stg_raw_cc_contact')
                                                unique_key: contact_sk (surrogate on PK 'id')
                                                check_cols: ['hash_key'] (surrogate on all business cols excl PK)
                                                hard_deletes: new_record (inserts dbt_is_deleted=True row)
                                                No code change required when PARQUET CDC goes live.
-#}

{{ config(
    target_schema='gwcc',
    unique_key='contact_sk',
    strategy='check',
    alias='cc_contact',
    check_cols=['hash_key'],
    hard_deletes='new_record',
    tags=['snapshot', 'claim_centre', 'business_critical', 'cc_contact']
) }}

SELECT
    contact_sk,
    hash_key,
    COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS dbt_updated_at,
    trustabnisactive_icare,
    singleremittanceperday_icare,
    preferredpaymentmethod_icare,
    faxphonecountry,
    taxid,
    namedenorm,
    medicarevaliduntil_icare,
    approvedpaymentmethod_icare,
    organisationtype_icare,
    updatetime,
    adjudicatorlicense,
    id,
    lawfirmspecialty,
    lastnamedenorm,
    oktaid_icare,
    lastname,
    createuserid,
    payinfoupdusername_icare,
    tradingname_icare,
    beanversion,
    venuetype,
    autotowinglicense,
    blockedvendor_icare,
    updateuserid,
    homephoneextension,
    medicarenumber_icare,
    trustregisteredforgst_icare,
    specialtytype,
    firstname,
    trusteename_icare,
    w9validfrom,
    publicid,
    occupation,
    cellphone,
    helpsslortsldebt_icare,
    primaryaddressid,
    trustabn_icare,
    suffix,
    addressbookuid,
    interpreterrequired_icare,
    website_icare,
    abnisactive_icare,
    emailaddress1,
    emailaddress2,
    primarylanguage,
    numdependents,
    taxstatus,
    otherlanguage_icare,
    offsetamount_icare,
    tfndeclarationdate_icare,
    archivepartition,
    namekanji,
    abslanguagedescription_icare,
    faxphone,
    abslanguagecode_icare,
    cellphoneextension,
    employeenumber,
    doctorspecialty_icare,
    subtype,
    abnvalidated_icare,
    formername,
    loadcommandid,
    preferred,
    obfuscatedinternal,
    vendortype,
    w9received,
    sourcesystem_icare,
    particle,
    acn_icare,
    employeesecurityid,
    name,
    medicallicense,
    vendornumber,
    preferredcurrency,
    score,
    donotdestroy,
    prefix,
    ssnreleaseauthorized,
    w9validto,
    lastnamekanji,
    auresidentfortaxpurposes_icare,
    taxfilingstatus,
    greencardnumber,
    withholdingrate,
    commencementdate_icare,
    trustname_icare,
    legalspecialty_icare,
    middlename,
    attorneylicense,
    eligibleoffset_icare,
    abn_icare,
    retired,
    jurisdictionassignedid,
    taxexemptionsentitled,
    medicalorgspecialty,
    validationlevel,
    primaryphone,
    trusteetype_icare,
    tempcrmuniqueid_icare,
    w9receiveddate,
    medicareirn_icare,
    crmversion_icare,
    firstnamedenorm,
    adjudicativedomain,
    firstnamekanji,
    policysystemid,
    doctorspecialty,
    smsnotification_icare,
    claimantidtype,
    notes,
    gender,
    numdependentsu18,
    autorepairlicense,
    homephonecountry,
    medicalspecialty_icare,
    createtime,
    autosync,
    cellphonecountry,
    licensenumber,
    visanumber,
    financialsupplementdebt_icare,
    trustabnvalidated_icare,
    pendinglinkmessage,
    loadrelatedcontacts,
    aggregateremittance_icare,
    dateofbirth,
    attorneyspecialty_icare,
    passportnumber,
    educationlevel,
    registeredforgst_icare,
    primarylocale,
    communicationpreferences_icare,
    numdependentsu25,
    attorneyspecialty,
    workphoneextension,
    medicarelevyvariation_icare,
    maritalstatus,
    claimtaxfreethreshold_icare,
    occupationdetails_icareid,
    organizationtype,
    faxphoneextension,
    homephone,
    licensestate,
    workphonecountry,
    workphone,
    noofdepchild_icare,
    snrpnsnrtaxoffsetstatus_icare,
    medicarelevyexempt_icare,
    spouse_icare,
    snrpensnrtaxoffset_icare,
    medicareexemptstatus_icare,
    wagersa_icare,
    managingentitycodes_icare,
    effectivetovariation_icare,
    upwardvariationpercent_icare,
    downwardvariationamt_icare,
    effectivefromvariation_icare,
    upwardvariationamt_icare,
    downwardvariationpercent_icare,
    withholdingvariation_icare,
    providerid_ext,
    dpplatform_ext,
    duplicatecreatereason_ext,
    contactsecuritytype_ext,
    cellphonecountry_ext,
    organisationpartyid_ext,
    crmlastmodifieddate_ext,
    crmlastmodifiedbyid_ext,
    status_ext,
    cellphoneextension_ext,
    crmcreateddate_ext,
    relatedcompanyname_ext,
    abnvalidationtimestamp_ext,
    cellphone_ext,
    crmlastmodifiedbyname_ext,
    providercategory_ext,
    abnexempt_ext,
    creationsource_ext,
    isexactmatch_ext,
    issubrogation_ext,
    'GWCC' AS source_system,
    gwcbi_connector_ts_ms,
    gwcbi_lsn,
    gwcbi_operation,
    gwcbi_payload_ts_ms,
    gwcbi_seqval,
    gwcbi_seqval_hex,
    gwcbi_tx_id,
    metadata_file_name,
    file_ingestion_timestamp
FROM {{ ref('stg_raw_cc_contact') }}

{% endsnapshot %}