{% snapshot cc_employmentdata_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026-01-01      0.0                             SCD Type 2 snapshot for cc_employmentdata.
                                                Source: ref('stg_raw_cc_employmentdata')
                                                unique_key: employmentdata_sk (surrogate on PK 'id')
                                                check_cols: ['hash_key'] (surrogate on all business cols excl PK)
                                                hard_deletes: new_record (inserts dbt_is_deleted=True row)
                                                No code change required when PARQUET CDC goes live.
-#}

{{ config(
    target_schema='gwcc',
    unique_key='employmentdata_sk',
    strategy='check',
    alias='cc_employmentdata',
    check_cols=['hash_key'],
    hard_deletes='new_record',
    tags=['snapshot', 'claim_centre', 'business_critical', 'cc_employmentdata']
) }}

SELECT
    employmentdata_sk,
    hash_key,
    wageamount,
    loadcommandid,
    voluntaryreductiondate,
    overtimerate,
    latestworkstatusdenorm_icare,
    wednesdayworkhours_icare,
    scheduledpayincreasedate_icare,
    accommodationbenefits_icare,
    mondayworkhours_icare,
    numdaysworked,
    motorvehiclebenefits_icare,
    ssbenefitsamnt,
    wagepaymentcont,
    educationfeebenefits_icare,
    updatetime,
    changeemployment_icare,
    wageamountpostinjury,
    worktuesday_icare,
    injurystarttime,
    id,
    ssbenefits,
    workmonday_icare,
    hirestate,
    employmentenddate,
    fulltime78weekspriorinjury,
    workwednesday_icare,
    industrycode_icareid,
    createuserid,
    workerpromoted,
    hiredate,
    weekavgovertimeearnings_icare,
    firstdaypaycycle_icare,
    workthursday_icare,
    beanversion,
    scndinjryfndamnt,
    retired,
    workfriday_icare,
    tuesdayworkhours_icare,
    terminationdate_icare,
    updateuserid,
    weekavgshiftallowance_icare,
    workerfuturepromotiondate,
    lastworkeddate,
    healthinsurancebenefits_icare,
    scndinjryfnd,
    anniversarydate_icare,
    employmentstatuschangedate,
    lastyearincome,
    departmentcode,
    classcodeid,
    saturdayworkhours_icare,
    othernonmonetarybenefits_icare,
    terminationreason_icare,
    publicid,
    workerpriorpromotiondate,
    worksaturday_icare,
    seekingfulltime,
    trainingstatus_icare,
    createtime,
    allowancesovertearnings_icare,
    sundayworkhours_icare,
    occupation,
    workplacesize_icare,
    voluntaryreduction,
    claimid,
    fairworkinstrument_icare,
    fridayworkhours_icare,
    workerduepromoted,
    paidfull,
    worksunday_icare,
    employmentstatus,
    scndinjryfnddate,
    archivepartition,
    payperiod,
    paymentsaligntopaycycle_icare,
    hoursworkedweek_icare,
    numhoursworked,
    daysworkedweek,
    thursdayworkhours_icare,
    mvwithdrawndate_icare,
    efwithdrawndate_icare,
    accwithdrawndate_icare,
    hiwithdrawndate_icare,
    otherwithdrawndate_icare,
    mvwithdrawnflag_icare,
    efwithdrawnflag_icare,
    signedagreementflag_icare,
    accwithdrawnflag_icare,
    hiwithdrawnflag_icare,
    unpaidleaveinlast52weeks_icare,
    otherwithdrawnflag_icare,
    'GWCC' AS source_system,
    gwcbi_connector_ts_ms,
    gwcbi_lsn,
    gwcbi_operation,
    gwcbi_payload_ts_ms,
    gwcbi_seqval,
    gwcbi_seqval_hex,
    gwcbi_tx_id,
    metadata_file_name,
    file_ingestion_timestamp
FROM {{ ref('stg_raw_cc_employmentdata') }}

{% endsnapshot %}