{% snapshot cc_exposure_snapshot %}

{#-
Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change           
2026-01-01      0.0                             SCD Type 2 snapshot for cc_exposure.
                                                Source: ref('stg_raw_cc_exposure')
                                                unique_key: exposure_sk (surrogate on PK 'id')
                                                check_cols: ['hash_key'] (surrogate on all business cols excl PK)
                                                hard_deletes: new_record (inserts dbt_is_deleted=True row)
                                                No code change required when PARQUET CDC goes live.
-#}

{{ config(
    target_schema='gwcc',
    unique_key='exposure_sk',
    strategy='check',
    alias='cc_exposure',
    check_cols=['hash_key'],
    hard_deletes='new_record',
    tags=['snapshot', 'claim_centre', 'business_critical', 'cc_exposure']
) }}

SELECT
    exposure_sk,
    hash_key,
    COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS dbt_updated_at,
    coverageid,
    previousgroupid,
    incidentlimitreached,
    locked,
    assignedbyuserid,
    othercovgchoice,
    diagnosticcnsistnt,
    pipclaimagglimitreached,
    previousqueueid,
    updatetime,
    id,
    examinationdate,
    vocbenefitsid,
    losscategory,
    createuserid,
    compbenefitsid,
    beanversion,
    lifepensionbenefitsid,
    reopendate,
    averageweeklywages,
    progress,
    updateuserid,
    segment,
    lastdayworked,
    depreciatedvalue,
    ssbenefit,
    ppdbenefitsid,
    tpdbenefitsid,
    publicid,
    securitylevel,
    deathbenefitsid,
    wcbenefit,
    assignedgroupid,
    fatalityinterest_icare,
    supplementalworkloadweight,
    wcpreexdisblty,
    claimid,
    assignedqueueid,
    metriclimitgeneration,
    statlineid,
    workloadupdated,
    breakin,
    templocationid,
    closedoutcome,
    archivepartition,
    exposuretier,
    isoreceivedate,
    incidentid,
    newempdataid,
    wagebenefit,
    strategy,
    assigneduserid,
    settledate,
    ssdibenefitsid,
    loadcommandid,
    wccdate_icare,
    wcpreexdisbltyinfo,
    treatedpatientbfr,
    priorempdataid,
    existingweeklybenefits_icare,
    wagestmtsent,
    pippersonagglimitreached,
    state,
    hospitaldays,
    coveragesubtype,
    claimorder,
    replacementvalue,
    reopenedreason,
    lossparty,
    wcbenefitsid,
    othercoverageinfo,
    closedate,
    retired,
    validationlevel,
    workloadweight,
    daysinweek,
    jurisdictionstate,
    lostpropertytype,
    isostatus,
    ptdbenefitsid,
    isosenddate,
    ttdbenefitsid,
    ssdieligible,
    exposurelimitreached,
    exposuretype,
    pipnonmedagglimitreached,
    claimantdenormid,
    wagestmtrecd,
    pipesslimitreached,
    riagreementgroupid,
    createtime,
    futurecowearnings_icare,
    rigroupsetexternally,
    furthertreatment,
    pipdeathbenefitsid,
    rsbenefitsid,
    previoususerid,
    isoknown,
    surgerydate_icare,
    excessrecoveryamount,
    claimanttype,
    disbenefitsid,
    hospitaldate,
    primarycoverage,
    pipvocbenefitsid,
    settlemethod,
    currentconditions,
    othercoverage,
    contactpermitted,
    assignmentdate,
    assignmentstatus,
    workerpayer_icare,
    currentsection38effdate_icare,
    issection41eligible_icare,
    mbcd_ext,
    iss59a7secsurgerytype_ext,
    iss59a3reinstatementwbtype_ext,
    'GWCC' AS source_system,
    gwcbi_connector_ts_ms,
    gwcbi_lsn,
    gwcbi_operation,
    gwcbi_payload_ts_ms,
    gwcbi_seqval,
    gwcbi_seqval_hex,
    gwcbi_tx_id,
    metadata_file_name,
    file_ingestion_timestamp
FROM {{ ref('stg_raw_cc_exposure') }}

{% endsnapshot %}