{#-

Project: Data Uplift Progran 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2025-11-18      0.0                             This Converts Parquet or AVRO Data in Variant Column in the RAW DB into Flattend Views

-#}   

{{ config(
    tags=["raw_gwcc"]
) }}


WITH source_data AS 
(

            SELECT
                TO_TIMESTAMP_NTZ(data_payload:FINDOCSCLOSETRIGGER_ICARE::TEXT/1000) AS FINDOCSCLOSETRIGGER_ICARE,
                TO_TIMESTAMP_NTZ(data_payload:REPORTEDDATE::TEXT/1000) AS REPORTEDDATE,
                data_payload:MAINCONTACTTYPE::TEXT AS MAINCONTACTTYPE,
                TO_TIMESTAMP_NTZ(data_payload:DATEFORMGIVENTOEMP::TEXT/1000) AS DATEFORMGIVENTOEMP,
                data_payload:PREVIOUSGROUPID::TEXT AS PREVIOUSGROUPID,
                data_payload:SIULIFECYCLESTATE::TEXT AS SIULIFECYCLESTATE,
                data_payload:SAFETYEQUIPPROV::BOOLEAN AS SAFETYEQUIPPROV,
                TO_TIMESTAMP_NTZ(data_payload:FLAGGEDDATE::TEXT/1000) AS FLAGGEDDATE,
                TO_TIMESTAMP_NTZ(data_payload:EXPOSUREBEGAN::TEXT/1000) AS EXPOSUREBEGAN,
                data_payload:ASSIGNEDBYUSERID::TEXT AS ASSIGNEDBYUSERID,
                data_payload:CALLBACKTIME_ICARE::TEXT AS CALLBACKTIME_ICARE,
                TO_TIMESTAMP_NTZ(data_payload:DATERPTDTOAGENT::TEXT/1000) AS DATERPTDTOAGENT,
                data_payload:DIAGNOSTICCNSISTNT::BOOLEAN AS DIAGNOSTICCNSISTNT,
                data_payload:CURRENCY::TEXT AS CURRENCY,
                TO_TIMESTAMP_NTZ(data_payload:DATERPTDTOEMPLOYER::TEXT/1000) AS DATERPTDTOEMPLOYER,
                data_payload:LITIGATIONSTATUS::TEXT AS LITIGATIONSTATUS,
                TO_TIMESTAMP_NTZ(data_payload:EXPOSUREENDED::TEXT/1000) AS EXPOSUREENDED,
                data_payload:PREVIOUSQUEUEID::TEXT AS PREVIOUSQUEUEID,
                TO_TIMESTAMP_NTZ(data_payload:UPDATETIME::TEXT/1000) AS UPDATETIME,
                CAST(data_payload:STORAGEBOXNUM::TEXT AS VARCHAR(10)) AS STORAGEBOXNUM,
                CAST(data_payload:STATEFILETEXT::TEXT AS VARCHAR(20)) AS STATEFILETEXT,
                data_payload:NEXTRESERVEWEEK_ICARE::TEXT AS NEXTRESERVEWEEK_ICARE,
                data_payload:OTHERRECOVSTATUS::TEXT AS OTHERRECOVSTATUS,
                data_payload:DRUGSINVOLVED::TEXT AS DRUGSINVOLVED,
                data_payload:ID::TEXT AS ID,
                data_payload:ISOENABLED::BOOLEAN AS ISOENABLED,
                TO_TIMESTAMP_NTZ(data_payload:DATEELIGIBLEFORARCHIVE::TEXT/1000) AS DATEELIGIBLEFORARCHIVE,
                CAST(data_payload:FLAGGEDREASON::TEXT AS VARCHAR(1333)) AS FLAGGEDREASON,
                data_payload:CLAIMTIER::TEXT AS CLAIMTIER,
                TO_TIMESTAMP_NTZ(data_payload:EXAMINATIONDATE::TEXT/1000) AS EXAMINATIONDATE,
                TO_TIMESTAMP_NTZ(data_payload:CLOSEDATE_ICARE::TEXT/1000) AS CLOSEDATE_ICARE,
                data_payload:CREATEUSERID::TEXT AS CREATEUSERID,
                TO_TIMESTAMP_NTZ(data_payload:DEATHDATE::TEXT/1000) AS DEATHDATE,
                data_payload:FAULT::TEXT AS FAULT,
                TO_TIMESTAMP_NTZ(data_payload:FINALISATIONDOCSTRIGGER_ICARE::TEXT/1000) AS FINALISATIONDOCSTRIGGER_ICARE,
                data_payload:HOWREPORTED::TEXT AS HOWREPORTED,
                data_payload:REINSURANCEFLAGGEDSTATUS::TEXT AS REINSURANCEFLAGGEDSTATUS,
                data_payload:ISCLAIMMIGRATED_ICARE::BOOLEAN AS ISCLAIMMIGRATED_ICARE,
                data_payload:LOSSCAUSE::TEXT AS LOSSCAUSE,
                data_payload:TRIGGERTRIAGE_ICARE::BOOLEAN AS TRIGGERTRIAGE_ICARE,
                data_payload:BEANVERSION::TEXT AS BEANVERSION,
                CAST(data_payload:FNOLGUID_ICARE::TEXT AS VARCHAR(30)) AS FNOLGUID_ICARE,
                data_payload:CLAIMSAGENT_ICARE::TEXT AS CLAIMSAGENT_ICARE,
                TO_TIMESTAMP_NTZ(data_payload:REOPENDATE::TEXT/1000) AS REOPENDATE,
                data_payload:PROGRESS::TEXT AS PROGRESS,
                data_payload:UPDATEUSERID::TEXT AS UPDATEUSERID,
                data_payload:MODIFIEDDUTYAVAIL::BOOLEAN AS MODIFIEDDUTYAVAIL,
                TO_TIMESTAMP_NTZ(data_payload:INSURERSENTMPNNOTICE::TEXT/1000) AS INSURERSENTMPNNOTICE,
                data_payload:SEGMENT::TEXT AS SEGMENT,
                data_payload:LOCATIONOFTHEFT::TEXT AS LOCATIONOFTHEFT,
                data_payload:STORAGETYPE::TEXT AS STORAGETYPE,
                data_payload:EMPLOYERSIZE_ICARE::TEXT AS EMPLOYERSIZE_ICARE,
                data_payload:EMPQUSVALIDITY::TEXT AS EMPQUSVALIDITY,
                TO_TIMESTAMP_NTZ(data_payload:TRIGGERASSESSREMINDERDATE::TEXT/1000) AS TRIGGERASSESSREMINDERDATE,
                TO_TIMESTAMP_NTZ(data_payload:DATECOMPDCSNDUE::TEXT/1000) AS DATECOMPDCSNDUE,
                data_payload:FAULTRATING::TEXT AS FAULTRATING,
                TO_TIMESTAMP_NTZ(data_payload:NEWDATEOFLOSS_ICARE::TEXT/1000) AS NEWDATEOFLOSS_ICARE,
                CAST(data_payload:PUBLICID::TEXT AS VARCHAR(64)) AS PUBLICID,
                CAST(data_payload:WICDESCRIPTION_ICARE::TEXT AS VARCHAR(255)) AS WICDESCRIPTION_ICARE,
                TO_TIMESTAMP_NTZ(data_payload:CLAIMANTRPRTDDATE::TEXT/1000) AS CLAIMANTRPRTDDATE,
                CAST(data_payload:NAVIGATORCLAIMTEXT_ICARE::TEXT AS VARCHAR(19)) AS NAVIGATORCLAIMTEXT_ICARE,
                TO_TIMESTAMP_NTZ(data_payload:COMMONLAWDATEFLAGED_ICARE::TEXT/1000) AS COMMONLAWDATEFLAGED_ICARE,
                data_payload:ASSIGNEDGROUPID::TEXT AS ASSIGNEDGROUPID,
                data_payload:ISEDITABLEBYPORTAL_ICARE::BOOLEAN AS ISEDITABLEBYPORTAL_ICARE,
                TO_TIMESTAMP_NTZ(data_payload:LOSSDATE::TEXT/1000) AS LOSSDATE,
                data_payload:SUPPLEMENTALWORKLOADWEIGHT::TEXT AS SUPPLEMENTALWORKLOADWEIGHT,
                TO_TIMESTAMP_NTZ(data_payload:TRIGGERTRIAGEDATE_ICARE::TEXT/1000) AS TRIGGERTRIAGEDATE_ICARE,
                data_payload:CLAIMSOURCE::TEXT AS CLAIMSOURCE,
                data_payload:SIESCALATESIU::TEXT AS SIESCALATESIU,
                data_payload:SALVAGESTATUS::TEXT AS SALVAGESTATUS,
                data_payload:FLAGGED::TEXT AS FLAGGED,
                data_payload:COMPUTERSECURITY::BOOLEAN AS COMPUTERSECURITY,
                data_payload:SAFETYEQUIPUSED::BOOLEAN AS SAFETYEQUIPUSED,
                data_payload:ASSIGNEDQUEUEID::TEXT AS ASSIGNEDQUEUEID,
                data_payload:STORAGELOCATIONSTATE::TEXT AS STORAGELOCATIONSTATE,
                TO_TIMESTAMP_NTZ(data_payload:EMPSENTMPNNOTICE::TEXT/1000) AS EMPSENTMPNNOTICE,
                data_payload:EMPLOYMENTINJURY::BOOLEAN AS EMPLOYMENTINJURY,
                TO_TIMESTAMP_NTZ(data_payload:WORKLOADUPDATED::TEXT/1000) AS WORKLOADUPDATED,
                data_payload:CLOSEDOUTCOME::TEXT AS CLOSEDOUTCOME,
                data_payload:ARCHIVEPARTITION::TEXT AS ARCHIVEPARTITION,
                TO_TIMESTAMP_NTZ(data_payload:ISORECEIVEDATE::TEXT/1000) AS ISORECEIVEDATE,
                CAST(data_payload:TEMPCLAIMTEXT_ICARE::TEXT AS VARCHAR(40)) AS TEMPCLAIMTEXT_ICARE,
                data_payload:INSUREDPREMISES::BOOLEAN AS INSUREDPREMISES,
                TO_TIMESTAMP_NTZ(data_payload:INJWKRINMPN::TEXT/1000) AS INJWKRINMPN,
                data_payload:PERMISSIONREQUIRED::TEXT AS PERMISSIONREQUIRED,
                CAST(data_payload:EMPLOYERVALIDITYREASON::TEXT AS VARCHAR(255)) AS EMPLOYERVALIDITYREASON,
                data_payload:STRATEGY::TEXT AS STRATEGY,
                data_payload:ASSIGNEDUSERID::TEXT AS ASSIGNEDUSERID,
                data_payload:STORAGECATEGORY::TEXT AS STORAGECATEGORY,
                data_payload:PTPINMPN::BOOLEAN AS PTPINMPN,
                TO_TIMESTAMP_NTZ(data_payload:DATEMADE_ICARE::TEXT/1000) AS DATEMADE_ICARE,
                data_payload:LOADCOMMANDID::TEXT AS LOADCOMMANDID,
                TO_TIMESTAMP_NTZ(data_payload:STATUTEDATE::TEXT/1000) AS STATUTEDATE,
                data_payload:INJUREDONPREMISES::BOOLEAN AS INJUREDONPREMISES,
                TO_TIMESTAMP_NTZ(data_payload:DATEFORMRETBYEMP::TEXT/1000) AS DATEFORMRETBYEMP,
                data_payload:INSUREDDENORMID::TEXT AS INSUREDDENORMID,
                data_payload:TREATEDPATIENTBFR::BOOLEAN AS TREATEDPATIENTBFR,
                CAST(data_payload:CLAIMTEXT::TEXT AS VARCHAR(40)) AS CLAIMTEXT,
                TO_TIMESTAMP_NTZ(data_payload:SIESCALATESIUDATE::TEXT/1000) AS SIESCALATESIUDATE,
                data_payload:INCIDENTREPORT::BOOLEAN AS INCIDENTREPORT,
                data_payload:PREEXDISBLTY::BOOLEAN AS PREEXDISBLTY,
                data_payload:TRIGGERASSESSREMINDER::BOOLEAN AS TRIGGERASSESSREMINDER,
                data_payload:ITCCHANGEDFLAGPEL::BOOLEAN AS ITCCHANGEDFLAGPEL,
                data_payload:BRANCHINSURER_ICARE::TEXT AS BRANCHINSURER_ICARE,
                data_payload:HOSPITALDAYS::TEXT AS HOSPITALDAYS,
                CAST(data_payload:POLICEDEPTINFO::TEXT AS VARCHAR(255)) AS POLICEDEPTINFO,
                data_payload:STATE::TEXT AS STATE,
                data_payload:SIUSTATUS::TEXT AS SIUSTATUS,
                data_payload:DONOTDESTROY::BOOLEAN AS DONOTDESTROY,
                data_payload:FIRSTNOTICESUIT::BOOLEAN AS FIRSTNOTICESUIT,
                data_payload:MOLD::BOOLEAN AS MOLD,
                data_payload:REOPENEDREASON::TEXT AS REOPENEDREASON,
                CAST(data_payload:STATEACKTEXT::TEXT AS VARCHAR(20)) AS STATEACKTEXT,
                data_payload:TOTALITCAAPEL::TEXT AS TOTALITCAAPEL,
                data_payload:REPORTEDBYTYPE::TEXT AS REPORTEDBYTYPE,
                TO_TIMESTAMP_NTZ(data_payload:CLOSEDATE::TEXT/1000) AS CLOSEDATE,
                data_payload:RETIRED::TEXT AS RETIRED,
                TO_TIMESTAMP_NTZ(data_payload:STORAGEDATE::TEXT/1000) AS STORAGEDATE,
                CAST(data_payload:FIREDEPTINFO::TEXT AS VARCHAR(255)) AS FIREDEPTINFO,
                data_payload:VALIDATIONLEVEL::TEXT AS VALIDATIONLEVEL,
                data_payload:LOBCODE::TEXT AS LOBCODE,
                data_payload:WORKLOADWEIGHT::TEXT AS WORKLOADWEIGHT,
                data_payload:JURISDICTIONSTATE::TEXT AS JURISDICTIONSTATE,
                data_payload:CONCURRENTEMP::TEXT AS CONCURRENTEMP,
                data_payload:SHAREDCLAIM_ICARE::TEXT AS SHAREDCLAIM_ICARE,
                TO_TIMESTAMP_NTZ(data_payload:DATERPTDTOINSURED::TEXT/1000) AS DATERPTDTOINSURED,
                data_payload:ISOSTATUS::TEXT AS ISOSTATUS,
                data_payload:LIABILITYSTATUSDENORM_ICARE::TEXT AS LIABILITYSTATUSDENORM_ICARE,
                data_payload:WEATHERRELATED::BOOLEAN AS WEATHERRELATED,
                TO_TIMESTAMP_NTZ(data_payload:ISOSENDDATE::TEXT/1000) AS ISOSENDDATE,
                data_payload:LOCATIONCODEID::TEXT AS LOCATIONCODEID,
                CAST(data_payload:STORAGEVOLUMES::TEXT AS VARCHAR(10)) AS STORAGEVOLUMES,
                data_payload:CATASTROPHEID::TEXT AS CATASTROPHEID,
                CAST(data_payload:STORAGEBARCODENUM::TEXT AS VARCHAR(10)) AS STORAGEBARCODENUM,
                data_payload:INJUREDREGULARJOB::BOOLEAN AS INJUREDREGULARJOB,
                data_payload:CLAIMANTDENORMID::TEXT AS CLAIMANTDENORMID,
                CAST(data_payload:CLAIMHASH_ICARE::TEXT AS VARCHAR(30)) AS CLAIMHASH_ICARE,
                CAST(data_payload:LOSSLOCATIONCODE::TEXT AS VARCHAR(5)) AS LOSSLOCATIONCODE,
                data_payload:BENEFITSSTATUSDCSN::BOOLEAN AS BENEFITSSTATUSDCSN,
                TO_TIMESTAMP_NTZ(data_payload:CREATETIME::TEXT/1000) AS CREATETIME,
                data_payload:ACCIDENTTYPE::TEXT AS ACCIDENTTYPE,
                data_payload:POLICYID::TEXT AS POLICYID,
                TO_TIMESTAMP_NTZ(data_payload:MANIFESTATIONDATE::TEXT/1000) AS MANIFESTATIONDATE,
                data_payload:FURTHERTREATMENT::BOOLEAN AS FURTHERTREATMENT,
                data_payload:REINSURANCEREPORTABLE::BOOLEAN AS REINSURANCEREPORTABLE,
                data_payload:ODGMEDDIAGNOSIS::TEXT AS ODGMEDDIAGNOSIS,
                TO_TIMESTAMP_NTZ(data_payload:PURGEDATE::TEXT/1000) AS PURGEDATE,
                data_payload:PREVIOUSUSERID::TEXT AS PREVIOUSUSERID,
                data_payload:LOSSTYPE::TEXT AS LOSSTYPE,
                data_payload:ISOKNOWN::BOOLEAN AS ISOKNOWN,
                CAST(data_payload:AGENCYID::TEXT AS VARCHAR(9)) AS AGENCYID,
                TO_TIMESTAMP_NTZ(data_payload:HOSPITALDATE::TEXT/1000) AS HOSPITALDATE,
                CAST(data_payload:LOSSLOCATIONSPATIALDENORM::TEXT AS VARCHAR(16777216)) AS LOSSLOCATIONSPATIALDENORM,
                CAST(data_payload:TRIAGERISKSCORE_ICARE::TEXT AS VARCHAR(255)) AS TRIAGERISKSCORE_ICARE,
                data_payload:SHOWMEDICALFIRSTINFO::TEXT AS SHOWMEDICALFIRSTINFO,
                TO_TIMESTAMP_NTZ(data_payload:DATECOMPDCSNMADE::TEXT/1000) AS DATECOMPDCSNMADE,
                data_payload:LOCKINGCOLUMN::TEXT AS LOCKINGCOLUMN,
                data_payload:CURRENTCONDITIONS::BOOLEAN AS CURRENTCONDITIONS,
                data_payload:COVERAGEINQUESTION::BOOLEAN AS COVERAGEINQUESTION,
                data_payload:LOSSLOCATIONID::TEXT AS LOSSLOCATIONID,
                data_payload:WEATHER::TEXT AS WEATHER,
                TO_TIMESTAMP_NTZ(data_payload:MMIDATE::TEXT/1000) AS MMIDATE,
                data_payload:CLAIMWORKCOMPID::TEXT AS CLAIMWORKCOMPID,
                TO_TIMESTAMP_NTZ(data_payload:ASSIGNMENTDATE::TEXT/1000) AS ASSIGNMENTDATE,
                data_payload:LARGELOSSNOTIFICATIONSTATUS::TEXT AS LARGELOSSNOTIFICATIONSTATUS,
                CAST(data_payload:DESCRIPTION::TEXT AS VARCHAR(1333)) AS DESCRIPTION,
                data_payload:SISCORE::TEXT AS SISCORE,
                data_payload:ASSIGNMENTSTATUS::TEXT AS ASSIGNMENTSTATUS,
                data_payload:HAZARDOUSWASTE::BOOLEAN AS HAZARDOUSWASTE,
                data_payload:LODGINGAGENT_ICARE::TEXT AS LODGINGAGENT_ICARE,
                data_payload:REIMBSCHAGRMNT_ICARE::TEXT AS REIMBSCHAGRMNT_ICARE,
                data_payload:FUNDING_ICARE::TEXT AS FUNDING_ICARE,
                data_payload:MANAGINGENTITY_ICARE::TEXT AS MANAGINGENTITY_ICARE,
                data_payload:EXTERNALIDENTIFIER_ICAREID::TEXT AS EXTERNALIDENTIFIER_ICAREID,
                data_payload:GENERATEIMPFLAG_EXT::BOOLEAN AS GENERATEIMPFLAG_EXT,
                CAST(data_payload:SIRACLAIMTEXT_EXT::TEXT AS VARCHAR(40)) AS SIRACLAIMTEXT_EXT,
                CAST(data_payload:OTHERCOSTCENTER_EXT::TEXT AS VARCHAR(500)) AS OTHERCOSTCENTER_EXT,
                data_payload:REOPENEXPONCLOSEDCLAIM_EXT::BOOLEAN AS REOPENEXPONCLOSEDCLAIM_EXT,
                data_payload:ISCOVIDCLAIM_EXT::BOOLEAN AS ISCOVIDCLAIM_EXT,
                CAST(data_payload:EXTERNALFACTORSIMPACT_EXT::TEXT AS VARCHAR(40)) AS EXTERNALFACTORSIMPACT_EXT,
                CAST(data_payload:EXTERNALFACTORSEVENT_EXT::TEXT AS VARCHAR(40)) AS EXTERNALFACTORSEVENT_EXT,
                data_payload:CLAIMSLM_EXTID::TEXT AS CLAIMSLM_EXTID,
                data_payload:NULLEDCLAIM_EXT::BOOLEAN AS NULLEDCLAIM_EXT,
                data_payload:ORGANIZATION_EXTID::TEXT AS ORGANIZATION_EXTID,
                data_payload:ISCONFLICTOFINTEREST_EXT::BOOLEAN AS ISCONFLICTOFINTEREST_EXT,
                data_payload:CLAIMTRANSFERDETAILS_EXTID::TEXT AS CLAIMTRANSFERDETAILS_EXTID,
                TO_TIMESTAMP_NTZ(data_payload:POLICEATTESTATIONDATE_EXT::TEXT/1000) AS POLICEATTESTATIONDATE_EXT,
                data_payload:REASONFOREXEMPT_EXT::TEXT AS REASONFOREXEMPT_EXT,
                data_payload:CLAIMTYPE_EXT::TEXT AS CLAIMTYPE_EXT,
                data_payload:APPENDSIRASUFFIX_EXT::BOOLEAN AS APPENDSIRASUFFIX_EXT,
                TO_TIMESTAMP_NTZ(data_payload:LEGACYCREATETIME_EXT::TEXT/1000) AS LEGACYCREATETIME_EXT,
                data_payload:TRANSITIONOUTCOME_EXT::TEXT AS TRANSITIONOUTCOME_EXT,
                TO_TIMESTAMP_NTZ(data_payload:TRANSITIONDECISIONDATE_EXT::TEXT/1000) AS TRANSITIONDECISIONDATE_EXT,
                data_payload:ISCLAIMIMPORTED_EXT::BOOLEAN AS ISCLAIMIMPORTED_EXT,
                TO_TIMESTAMP_NTZ(data_payload:IMPORTDATE_EXT::TEXT/1000) AS IMPORTDATE_EXT,
                data_payload:ISSTAFFCLAIM_EXT::BOOLEAN AS ISSTAFFCLAIM_EXT,
                CAST(data_payload:REFERENCECOSTCENTRENAME_EXT::TEXT AS VARCHAR(255)) AS REFERENCECOSTCENTRENAME_EXT,
                CAST(data_payload:AGENCYCOSTCENTRENAME_EXT::TEXT AS VARCHAR(255)) AS AGENCYCOSTCENTRENAME_EXT,
                CAST(data_payload:REFERENCECOSTCENTRECODE_EXT::TEXT AS VARCHAR(255)) AS REFERENCECOSTCENTRECODE_EXT,
                CAST(data_payload:AGENCYCOSTCENTRECODE_EXT::TEXT AS VARCHAR(255)) AS AGENCYCOSTCENTRECODE_EXT,
                CAST(data_payload:SECREFCOSTCENTRECODE_EXT::TEXT AS VARCHAR(255)) AS SECREFCOSTCENTRECODE_EXT,
                CAST(data_payload:SECREFCOSTCENTRENAME_EXT::TEXT AS VARCHAR(255)) AS SECREFCOSTCENTRENAME_EXT,
                CAST(data_payload:SECAGENCYCOSTCENTRECODE_EXT::TEXT AS VARCHAR(255)) AS SECAGENCYCOSTCENTRECODE_EXT,
                CAST(data_payload:SECAGENCYCOSTCENTRENAME_EXT::TEXT AS VARCHAR(255)) AS SECAGENCYCOSTCENTRENAME_EXT,
                CAST(NULL AS VARCHAR(120)) as lsn,
                CAST(NULL AS VARCHAR(2)) as row_operation,
                CAST(NULL AS TEXT) as seqval_hex,
                CAST(NULL AS TIMESTAMP_LTZ) as update_timestamp,
                {{ dbt_utils.generate_surrogate_key([
                                'findocsclosetrigger_icare',
                        'reporteddate',
                        'maincontacttype',
                        'dateformgiventoemp',
                        'previousgroupid',
                        'siulifecyclestate',
                        'safetyequipprov',
                        'flaggeddate',
                        'exposurebegan',
                        'assignedbyuserid',
                        'callbacktime_icare',
                        'daterptdtoagent',
                        'diagnosticcnsistnt',
                        'currency',
                        'daterptdtoemployer',
                        'litigationstatus',
                        'exposureended',
                        'previousqueueid',
                        'updatetime',
                        'storageboxnum',
                        'statefileTEXT',
                        'nextreserveweek_icare',
                        'otherrecovstatus',
                        'drugsinvolved',
                        'id',
                        'isoenabled',
                        'dateeligibleforarchive',
                        'flaggedreason',
                        'claimtier',
                        'examinationdate',
                        'closedate_icare',
                        'createuserid',
                        'deathdate',
                        'fault',
                        'finalisationdocstrigger_icare',
                        'howreported',
                        'reinsuranceflaggedstatus',
                        'isclaimmigrated_icare',
                        'losscause',
                        'triggertriage_icare',
                        'beanversion',
                        'fnolguid_icare',
                        'claimsagent_icare',
                        'reopendate',
                        'progress',
                        'updateuserid',
                        'modifieddutyavail',
                        'insurersentmpnnotice',
                        'segment',
                        'locationoftheft',
                        'storagetype',
                        'employersize_icare',
                        'empqusvalidity',
                        'triggerassessreminderdate',
                        'datecompdcsndue',
                        'faultrating',
                        'newdateofloss_icare',
                        'publicid',
                        'wicdescription_icare',
                        'claimantrprtddate',
                        'navigatorclaimTEXT_icare',
                        'commonlawdateflaged_icare',
                        'assignedgroupid',
                        'iseditablebyportal_icare',
                        'lossdate',
                        'supplementalworkloadweight',
                        'triggertriagedate_icare',
                        'claimsource',
                        'siescalatesiu',
                        'salvagestatus',
                        'flagged',
                        'computersecurity',
                        'safetyequipused',
                        'assignedqueueid',
                        'storagelocationstate',
                        'empsentmpnnotice',
                        'employmentinjury',
                        'workloadupdated',
                        'closedoutcome',
                        'archivepartition',
                        'isoreceivedate',
                        'tempclaimTEXT_icare',
                        'insuredpremises',
                        'injwkrinmpn',
                        'permissionrequired',
                        'employervalidityreason',
                        'strategy',
                        'assigneduserid',
                        'storagecategory',
                        'ptpinmpn',
                        'datemade_icare',
                        'loadcommandid',
                        'statutedate',
                        'injuredonpremises',
                        'dateformretbyemp',
                        'insureddenormid',
                        'treatedpatientbfr',
                        'claimTEXT',
                        'siescalatesiudate',
                        'incidentreport',
                        'preexdisblty',
                        'triggerassessreminder',
                        'itcchangedflagpel',
                        'branchinsurer_icare',
                        'hospitaldays',
                        'policedeptinfo',
                        'state',
                        'siustatus',
                        'donotdestroy',
                        'firstnoticesuit',
                        'mold',
                        'reopenedreason',
                        'stateackTEXT',
                        'totalitcaapel',
                        'reportedbytype',
                        'closedate',
                        'retired',
                        'storagedate',
                        'firedeptinfo',
                        'validationlevel',
                        'lobcode',
                        'workloadweight',
                        'jurisdictionstate',
                        'concurrentemp',
                        'sharedclaim_icare',
                        'daterptdtoinsured',
                        'isostatus',
                        'liabilitystatusdenorm_icare',
                        'weatherrelated',
                        'isosenddate',
                        'locationcodeid',
                        'storagevolumes',
                        'catastropheid',
                        'storagebarcodenum',
                        'injuredregularjob',
                        'claimantdenormid',
                        'claimhash_icare',
                        'losslocationcode',
                        'benefitsstatusdcsn',
                        'createtime',
                        'accidenttype',
                        'policyid',
                        'manifestationdate',
                        'furthertreatment',
                        'reinsurancereportable',
                        'odgmeddiagnosis',
                        'purgedate',
                        'previoususerid',
                        'losstype',
                        'isoknown',
                        'agencyid',
                        'hospitaldate',
                        'losslocationspatialdenorm',
                        'triageriskscore_icare',
                        'showmedicalfirstinfo',
                        'datecompdcsnmade',
                        'lockingcolumn',
                        'currentconditions',
                        'coverageinquestion',
                        'losslocationid',
                        'weather',
                        'mmidate',
                        'claimworkcompid',
                        'assignmentdate',
                        'largelossnotificationstatus',
                        'description',
                        'siscore',
                        'assignmentstatus',
                        'hazardouswaste',
                        'lodgingagent_icare',
                        'reimbschagrmnt_icare',
                        'funding_icare',
                        'managingentity_icare',
                        'externalidentifier_icareid',
                        'generateimpflag_ext',
                        'siraclaimTEXT_ext',
                        'othercostcenter_ext',
                        'reopenexponclosedclaim_ext',
                        'iscovidclaim_ext',
                        'externalfactorsimpact_ext',
                        'externalfactorsevent_ext',
                        'claimslm_extid',
                        'nulledclaim_ext',
                        'organization_extid',
                        'isconflictofinterest_ext',
                        'claimtransferdetails_extid',
                        'policeattestationdate_ext',
                        'reasonforexempt_ext',
                        'claimtype_ext',
                        'appendsirasuffix_ext',
                        'legacycreatetime_ext',
                        'transitionoutcome_ext',
                        'transitiondecisiondate_ext',
                        'isclaimimported_ext',
                        'importdate_ext',
                        'isstaffclaim_ext',
                        'referencecostcentrename_ext',
                        'agencycostcentrename_ext',
                        'referencecostcentrecode_ext',
                        'agencycostcentrecode_ext',
                        'secrefcostcentrecode_ext',
                        'secrefcostcentrename_ext',
                        'secagencycostcentrecode_ext',
                        'secagencycostcentrename_ext'
                        ]) }} AS id_hash,
                metadata_file_name,
                file_ingestion_timestamp
            FROM {{ source('gwcc', 'cc_claim') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:findocsclosetrigger_icare::TIMESTAMP_NTZ AS findocsclosetrigger_icare,
                $1:reporteddate::TIMESTAMP_NTZ AS reporteddate,
                $1:maincontacttype::TEXT AS maincontacttype,
                $1:dateformgiventoemp::TIMESTAMP_NTZ AS dateformgiventoemp,
                $1:previousgroupid::TEXT AS previousgroupid,
                $1:siulifecyclestate::TEXT AS siulifecyclestate,
                $1:safetyequipprov::BOOLEAN AS safetyequipprov,
                $1:flaggeddate::TIMESTAMP_NTZ AS flaggeddate,
                $1:exposurebegan::TIMESTAMP_NTZ AS exposurebegan,
                $1:assignedbyuserid::TEXT AS assignedbyuserid,
                $1:callbacktime_icare::TEXT AS callbacktime_icare,
                $1:daterptdtoagent::TIMESTAMP_NTZ AS daterptdtoagent,
                $1:diagnosticcnsistnt::BOOLEAN AS diagnosticcnsistnt,
                $1:currency::TEXT AS currency,
                $1:daterptdtoemployer::TIMESTAMP_NTZ AS daterptdtoemployer,
                $1:litigationstatus::TEXT AS litigationstatus,
                $1:exposureended::TIMESTAMP_NTZ AS exposureended,
                $1:previousqueueid::TEXT AS previousqueueid,
                $1:updatetime::TIMESTAMP_NTZ AS updatetime,
                CAST($1:storageboxnum::TEXT AS VARCHAR(10)) AS storageboxnum,
                CAST($1:statefileTEXT::TEXT AS VARCHAR(20)) AS statefileTEXT,
                $1:nextreserveweek_icare::TEXT AS nextreserveweek_icare,
                $1:otherrecovstatus::TEXT AS otherrecovstatus,
                $1:drugsinvolved::TEXT AS drugsinvolved,
                $1:id::TEXT AS id,
                $1:isoenabled::BOOLEAN AS isoenabled,
                $1:dateeligibleforarchive::TIMESTAMP_NTZ AS dateeligibleforarchive,
                CAST($1:flaggedreason::TEXT AS VARCHAR(1333)) AS flaggedreason,
                $1:claimtier::TEXT AS claimtier,
                $1:examinationdate::TIMESTAMP_NTZ AS examinationdate,
                $1:closedate_icare::TIMESTAMP_NTZ AS closedate_icare,
                $1:createuserid::TEXT AS createuserid,
                $1:deathdate::TIMESTAMP_NTZ AS deathdate,
                $1:fault::TEXT AS fault,
                $1:finalisationdocstrigger_icare::TIMESTAMP_NTZ AS finalisationdocstrigger_icare,
                $1:howreported::TEXT AS howreported,
                $1:reinsuranceflaggedstatus::TEXT AS reinsuranceflaggedstatus,
                $1:isclaimmigrated_icare::BOOLEAN AS isclaimmigrated_icare,
                $1:losscause::TEXT AS losscause,
                $1:triggertriage_icare::BOOLEAN AS triggertriage_icare,
                $1:beanversion::TEXT AS beanversion,
                CAST($1:fnolguid_icare::TEXT AS VARCHAR(30)) AS fnolguid_icare,
                $1:claimsagent_icare::TEXT AS claimsagent_icare,
                $1:reopendate::TIMESTAMP_NTZ AS reopendate,
                $1:progress::TEXT AS progress,
                $1:updateuserid::TEXT AS updateuserid,
                $1:modifieddutyavail::BOOLEAN AS modifieddutyavail,
                $1:insurersentmpnnotice::TIMESTAMP_NTZ AS insurersentmpnnotice,
                $1:segment::TEXT AS segment,
                $1:locationoftheft::TEXT AS locationoftheft,
                $1:storagetype::TEXT AS storagetype,
                $1:employersize_icare::TEXT AS employersize_icare,
                $1:empqusvalidity::TEXT AS empqusvalidity,
                $1:triggerassessreminderdate::TIMESTAMP_NTZ AS triggerassessreminderdate,
                $1:datecompdcsndue::TIMESTAMP_NTZ AS datecompdcsndue,
                $1:faultrating::TEXT AS faultrating,
                $1:newdateofloss_icare::TIMESTAMP_NTZ AS newdateofloss_icare,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                CAST($1:wicdescription_icare::TEXT AS VARCHAR(255)) AS wicdescription_icare,
                $1:claimantrprtddate::TIMESTAMP_NTZ AS claimantrprtddate,
                CAST($1:navigatorclaimTEXT_icare::TEXT AS VARCHAR(19)) AS navigatorclaimTEXT_icare,
                $1:commonlawdateflaged_icare::TIMESTAMP_NTZ AS commonlawdateflaged_icare,
                $1:assignedgroupid::TEXT AS assignedgroupid,
                $1:iseditablebyportal_icare::BOOLEAN AS iseditablebyportal_icare,
                $1:lossdate::TIMESTAMP_NTZ AS lossdate,
                $1:supplementalworkloadweight::TEXT AS supplementalworkloadweight,
                $1:triggertriagedate_icare::TIMESTAMP_NTZ AS triggertriagedate_icare,
                $1:claimsource::TEXT AS claimsource,
                $1:siescalatesiu::TEXT AS siescalatesiu,
                $1:salvagestatus::TEXT AS salvagestatus,
                $1:flagged::TEXT AS flagged,
                $1:computersecurity::BOOLEAN AS computersecurity,
                $1:safetyequipused::BOOLEAN AS safetyequipused,
                $1:assignedqueueid::TEXT AS assignedqueueid,
                $1:storagelocationstate::TEXT AS storagelocationstate,
                $1:empsentmpnnotice::TIMESTAMP_NTZ AS empsentmpnnotice,
                $1:employmentinjury::BOOLEAN AS employmentinjury,
                $1:workloadupdated::TIMESTAMP_NTZ AS workloadupdated,
                $1:closedoutcome::TEXT AS closedoutcome,
                $1:archivepartition::TEXT AS archivepartition,
                $1:isoreceivedate::TIMESTAMP_NTZ AS isoreceivedate,
                CAST($1:tempclaimTEXT_icare::TEXT AS VARCHAR(40)) AS tempclaimTEXT_icare,
                $1:insuredpremises::BOOLEAN AS insuredpremises,
                $1:injwkrinmpn::TIMESTAMP_NTZ AS injwkrinmpn,
                $1:permissionrequired::TEXT AS permissionrequired,
                CAST($1:employervalidityreason::TEXT AS VARCHAR(255)) AS employervalidityreason,
                $1:strategy::TEXT AS strategy,
                $1:assigneduserid::TEXT AS assigneduserid,
                $1:storagecategory::TEXT AS storagecategory,
                $1:ptpinmpn::BOOLEAN AS ptpinmpn,
                $1:datemade_icare::TIMESTAMP_NTZ AS datemade_icare,
                $1:loadcommandid::TEXT AS loadcommandid,
                $1:statutedate::TIMESTAMP_NTZ AS statutedate,
                $1:injuredonpremises::BOOLEAN AS injuredonpremises,
                $1:dateformretbyemp::TIMESTAMP_NTZ AS dateformretbyemp,
                $1:insureddenormid::TEXT AS insureddenormid,
                $1:treatedpatientbfr::BOOLEAN AS treatedpatientbfr,
                CAST($1:claimTEXT::TEXT AS VARCHAR(40)) AS claimTEXT,
                $1:siescalatesiudate::TIMESTAMP_NTZ AS siescalatesiudate,
                $1:incidentreport::BOOLEAN AS incidentreport,
                $1:preexdisblty::BOOLEAN AS preexdisblty,
                $1:triggerassessreminder::BOOLEAN AS triggerassessreminder,
                $1:itcchangedflagpel::BOOLEAN AS itcchangedflagpel,
                $1:branchinsurer_icare::TEXT AS branchinsurer_icare,
                $1:hospitaldays::TEXT AS hospitaldays,
                CAST($1:policedeptinfo::TEXT AS VARCHAR(255)) AS policedeptinfo,
                $1:state::TEXT AS state,
                $1:siustatus::TEXT AS siustatus,
                $1:donotdestroy::BOOLEAN AS donotdestroy,
                $1:firstnoticesuit::BOOLEAN AS firstnoticesuit,
                $1:mold::BOOLEAN AS mold,
                $1:reopenedreason::TEXT AS reopenedreason,
                CAST($1:stateackTEXT::TEXT AS VARCHAR(20)) AS stateackTEXT,
                $1:totalitcaapel::TEXT AS totalitcaapel,
                $1:reportedbytype::TEXT AS reportedbytype,
                $1:closedate::TIMESTAMP_NTZ AS closedate,
                $1:retired::TEXT AS retired,
                $1:storagedate::TIMESTAMP_NTZ AS storagedate,
                CAST($1:firedeptinfo::TEXT AS VARCHAR(255)) AS firedeptinfo,
                $1:validationlevel::TEXT AS validationlevel,
                $1:lobcode::TEXT AS lobcode,
                $1:workloadweight::TEXT AS workloadweight,
                $1:jurisdictionstate::TEXT AS jurisdictionstate,
                $1:concurrentemp::TEXT AS concurrentemp,
                $1:sharedclaim_icare::TEXT AS sharedclaim_icare,
                $1:daterptdtoinsured::TIMESTAMP_NTZ AS daterptdtoinsured,
                $1:isostatus::TEXT AS isostatus,
                $1:liabilitystatusdenorm_icare::TEXT AS liabilitystatusdenorm_icare,
                $1:weatherrelated::BOOLEAN AS weatherrelated,
                $1:isosenddate::TIMESTAMP_NTZ AS isosenddate,
                $1:locationcodeid::TEXT AS locationcodeid,
                CAST($1:storagevolumes::TEXT AS VARCHAR(10)) AS storagevolumes,
                $1:catastropheid::TEXT AS catastropheid,
                CAST($1:storagebarcodenum::TEXT AS VARCHAR(10)) AS storagebarcodenum,
                $1:injuredregularjob::BOOLEAN AS injuredregularjob,
                $1:claimantdenormid::TEXT AS claimantdenormid,
                CAST($1:claimhash_icare::TEXT AS VARCHAR(30)) AS claimhash_icare,
                CAST($1:losslocationcode::TEXT AS VARCHAR(5)) AS losslocationcode,
                $1:benefitsstatusdcsn::BOOLEAN AS benefitsstatusdcsn,
                $1:createtime::TIMESTAMP_NTZ AS createtime,
                $1:accidenttype::TEXT AS accidenttype,
                $1:policyid::TEXT AS policyid,
                $1:manifestationdate::TIMESTAMP_NTZ AS manifestationdate,
                $1:furthertreatment::BOOLEAN AS furthertreatment,
                $1:reinsurancereportable::BOOLEAN AS reinsurancereportable,
                $1:odgmeddiagnosis::TEXT AS odgmeddiagnosis,
                $1:purgedate::TIMESTAMP_NTZ AS purgedate,
                $1:previoususerid::TEXT AS previoususerid,
                $1:losstype::TEXT AS losstype,
                $1:isoknown::BOOLEAN AS isoknown,
                CAST($1:agencyid::TEXT AS VARCHAR(9)) AS agencyid,
                $1:hospitaldate::TIMESTAMP_NTZ AS hospitaldate,
                CAST($1:losslocationspatialdenorm::TEXT AS VARCHAR(16777216)) AS losslocationspatialdenorm,
                CAST($1:triageriskscore_icare::TEXT AS VARCHAR(255)) AS triageriskscore_icare,
                $1:showmedicalfirstinfo::TEXT AS showmedicalfirstinfo,
                $1:datecompdcsnmade::TIMESTAMP_NTZ AS datecompdcsnmade,
                $1:lockingcolumn::TEXT AS lockingcolumn,
                $1:currentconditions::BOOLEAN AS currentconditions,
                $1:coverageinquestion::BOOLEAN AS coverageinquestion,
                $1:losslocationid::TEXT AS losslocationid,
                $1:weather::TEXT AS weather,
                $1:mmidate::TIMESTAMP_NTZ AS mmidate,
                $1:claimworkcompid::TEXT AS claimworkcompid,
                $1:assignmentdate::TIMESTAMP_NTZ AS assignmentdate,
                $1:largelossnotificationstatus::TEXT AS largelossnotificationstatus,
                CAST($1:description::TEXT AS VARCHAR(1333)) AS description,
                $1:siscore::TEXT AS siscore,
                $1:assignmentstatus::TEXT AS assignmentstatus,
                $1:hazardouswaste::BOOLEAN AS hazardouswaste,
                $1:lodgingagent_icare::TEXT AS lodgingagent_icare,
                $1:reimbschagrmnt_icare::TEXT AS reimbschagrmnt_icare,
                $1:funding_icare::TEXT AS funding_icare,
                $1:managingentity_icare::TEXT AS managingentity_icare,
                $1:externalidentifier_icareid::TEXT AS externalidentifier_icareid,
                $1:generateimpflag_ext::BOOLEAN AS generateimpflag_ext,
                CAST($1:siraclaimTEXT_ext::TEXT AS VARCHAR(40)) AS siraclaimTEXT_ext,
                CAST($1:othercostcenter_ext::TEXT AS VARCHAR(500)) AS othercostcenter_ext,
                $1:reopenexponclosedclaim_ext::BOOLEAN AS reopenexponclosedclaim_ext,
                $1:iscovidclaim_ext::BOOLEAN AS iscovidclaim_ext,
                CAST($1:externalfactorsimpact_ext::TEXT AS VARCHAR(40)) AS externalfactorsimpact_ext,
                CAST($1:externalfactorsevent_ext::TEXT AS VARCHAR(40)) AS externalfactorsevent_ext,
                $1:claimslm_extid::TEXT AS claimslm_extid,
                $1:nulledclaim_ext::BOOLEAN AS nulledclaim_ext,
                $1:organization_extid::TEXT AS organization_extid,
                $1:isconflictofinterest_ext::BOOLEAN AS isconflictofinterest_ext,
                $1:claimtransferdetails_extid::TEXT AS claimtransferdetails_extid,
                $1:policeattestationdate_ext::TIMESTAMP_NTZ AS policeattestationdate_ext,
                $1:reasonforexempt_ext::TEXT AS reasonforexempt_ext,
                $1:claimtype_ext::TEXT AS claimtype_ext,
                $1:appendsirasuffix_ext::BOOLEAN AS appendsirasuffix_ext,
                $1:legacycreatetime_ext::TIMESTAMP_NTZ AS legacycreatetime_ext,
                $1:transitionoutcome_ext::TEXT AS transitionoutcome_ext,
                $1:transitiondecisiondate_ext::TIMESTAMP_NTZ AS transitiondecisiondate_ext,
                $1:isclaimimported_ext::BOOLEAN AS isclaimimported_ext,
                $1:importdate_ext::TIMESTAMP_NTZ AS importdate_ext,
                $1:isstaffclaim_ext::BOOLEAN AS isstaffclaim_ext,
                CAST($1:referencecostcentrename_ext::TEXT AS VARCHAR(255)) AS referencecostcentrename_ext,
                CAST($1:agencycostcentrename_ext::TEXT AS VARCHAR(255)) AS agencycostcentrename_ext,
                CAST($1:referencecostcentrecode_ext::TEXT AS VARCHAR(255)) AS referencecostcentrecode_ext,
                CAST($1:agencycostcentrecode_ext::TEXT AS VARCHAR(255)) AS agencycostcentrecode_ext,
                CAST($1:secrefcostcentrecode_ext::TEXT AS VARCHAR(255)) AS secrefcostcentrecode_ext,
                CAST($1:secrefcostcentrename_ext::TEXT AS VARCHAR(255)) AS secrefcostcentrename_ext,
                CAST($1:secagencycostcentrecode_ext::TEXT AS VARCHAR(255)) AS secagencycostcentrecode_ext,
                CAST($1:secagencycostcentrename_ext::TEXT AS VARCHAR(255)) AS secagencycostcentrename_ext,
                CAST($1:gwcbi___lsn::STRING AS VARCHAR(120)) as lsn,
                CAST($1:gwcbi___operation::STRING AS VARCHAR(2)) as row_operation,
                CAST($1:gwcbi___seqval_hex::STRING AS VARCHAR(120))  as seqval_hex,
                TO_TIMESTAMP($1:gwcbi___cdc_tx_date::TEXT / 1000) as update_timestamp,
                {{ dbt_utils.generate_surrogate_key([
                                'ID',
                        'seqval_hex'
                        ]) }} AS id_hash,
                metadata_file_name,
                file_ingestion_timestamp
            FROM {{ source('gwcc', 'cc_claim') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),
{#-
    Driving CTE Over 
-#}   
transformed AS (
    SELECT
        *
    FROM source_data
)
SELECT * FROM transformed