{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for ccx_piaweindexremreport_ext.
                                                piaweindexremreport_ext_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["raw_layer", "raw_claim_centre", "claim_centre", "non_business_critical", "ccx_piaweindexremreport_ext"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                CAST(data_payload:LatestWQ3IndexedPeriod::TEXT AS VARCHAR(255)) AS latestwq3indexedperiod,
                TO_TIMESTAMP_TZ(data_payload:S38EligibilityEffectiveDate::NUMBER/1000) AS s38eligibilityeffectivedate,
                TO_TIMESTAMP_TZ(data_payload:EarliestWBPaidFromDate::NUMBER/1000) AS earliestwbpaidfromdate,
                TO_TIMESTAMP_TZ(data_payload:WeeklyBenefitsCessationDate::NUMBER/1000) AS weeklybenefitscessationdate,
                CAST(data_payload:ClaimNumber::TEXT AS VARCHAR(255)) AS claimnumber,
                CAST(data_payload:CaseOwnerName::TEXT AS VARCHAR(255)) AS caseownername,
                CAST(data_payload:PIAWEType::TEXT AS VARCHAR(255)) AS piawetype,
                CAST(data_payload:COCFitness::TEXT AS VARCHAR(255)) AS cocfitness,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:ID::NUMBER AS id,
                data_payload:CreateUserID::NUMBER AS createuserid,
                CAST(data_payload:IRWeeklyPaymentImpact::TEXT AS VARCHAR(255)) AS irweeklypaymentimpact,
                CAST(data_payload:MEName::TEXT AS VARCHAR(255)) AS mename,
                TO_TIMESTAMP_TZ(data_payload:RetirementDate::NUMBER/1000) AS retirementdate,
                data_payload:BeanVersion::NUMBER AS beanversion,
                TO_TIMESTAMP_TZ(data_payload:DateOfLoss::NUMBER/1000) AS dateofloss,
                data_payload:Retired::NUMBER AS retired,
                CAST(data_payload:WCDDetails::TEXT AS VARCHAR(16777216)) AS wcddetails,
                CAST(data_payload:Claimant::TEXT AS VARCHAR(255)) AS claimant,
                CAST(data_payload:ResultOfInjury::TEXT AS VARCHAR(255)) AS resultofinjury,
                CAST(data_payload:DidTheClaimIndexInWQ3::TEXT AS VARCHAR(255)) AS didtheclaimindexinwq3,
                TO_TIMESTAMP_TZ(data_payload:WorkStatusStartDate::NUMBER/1000) AS workstatusstartdate,
                TO_TIMESTAMP_TZ(data_payload:NonComplianceEffectiveDate::NUMBER/1000) AS noncomplianceeffectivedate,
                CAST(data_payload:PIAWEAmount::TEXT AS VARCHAR(255)) AS piaweamount,
                TO_TIMESTAMP_TZ(data_payload:COCConsultationDate::NUMBER/1000) AS cocconsultationdate,
                CAST(data_payload:ClaimStatus::TEXT AS VARCHAR(255)) AS claimstatus,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                CAST(data_payload:WorkStatusCode::TEXT AS VARCHAR(255)) AS workstatuscode,
                CAST(data_payload:ReasonNotIndexDOFI::TEXT AS VARCHAR(255)) AS reasonnotindexdofi,
                CAST(data_payload:Adjustment_Required::TEXT AS VARCHAR(255)) AS adjustment_required,
                TO_TIMESTAMP_TZ(data_payload:COCEndDate::NUMBER/1000) AS cocenddate,
                CAST(data_payload:HasMedicalOther::TEXT AS VARCHAR(255)) AS hasmedicalother,
                data_payload:NumberofPeriodsIndexed::NUMBER AS numberofperiodsindexed,
                CAST(data_payload:LiabilityStatus::TEXT AS VARCHAR(255)) AS liabilitystatus,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                CAST(data_payload:PICReviewWeeklyPaymentImpact::TEXT AS VARCHAR(255)) AS picreviewweeklypaymentimpact,
                TO_TIMESTAMP_TZ(data_payload:RetirementCessationDateWeekly::NUMBER/1000) AS retirementcessationdateweekly,
                TO_TIMESTAMP_TZ(data_payload:ComplianceDate::NUMBER/1000) AS compliancedate,
                data_payload:WPIPercentage::NUMBER AS wpipercentage,
                CAST(data_payload:WageLoss::TEXT AS VARCHAR(255)) AS wageloss,
                data_payload:WeeksPaid::NUMBER AS weekspaid,
                CAST(data_payload:HasWeeklyBenefitsIndemnity::TEXT AS VARCHAR(255)) AS hasweeklybenefitsindemnity,
                CAST(data_payload:WCDType::TEXT AS VARCHAR(255)) AS wcdtype,
                TO_TIMESTAMP_TZ(data_payload:WeeklyBenefitEndDate::NUMBER/1000) AS weeklybenefitenddate,
                CAST(data_payload:PICReviewStatus::TEXT AS VARCHAR(255)) AS picreviewstatus,
                TO_TIMESTAMP_TZ(data_payload:EffectiveDate::NUMBER/1000) AS effectivedate,
                TO_TIMESTAMP_TZ(data_payload:PICReviewDecisionEffectiveDate::NUMBER/1000) AS picreviewdecisioneffectivedate,
                CAST(data_payload:IRStatus::TEXT AS VARCHAR(255)) AS irstatus,
                CAST(data_payload:ReasonNoWBPaid::TEXT AS VARCHAR(255)) AS reasonnowbpaid,
                TO_TIMESTAMP_TZ(data_payload:ReportDate::NUMBER/1000) AS reportdate,
                CAST(data_payload:NonComplianceType::TEXT AS VARCHAR(255)) AS noncompliancetype,
                CAST(data_payload:ReasonNoMissingPoints::TEXT AS VARCHAR(255)) AS reasonnomissingpoints,
                TO_TIMESTAMP_TZ(data_payload:DateOfFirstIncapacity::NUMBER/1000) AS dateoffirstincapacity,
                TO_TIMESTAMP_TZ(data_payload:SettlementPaymentIssueDate::NUMBER/1000) AS settlementpaymentissuedate,
                CAST(data_payload:CaseOwnerTeamName::TEXT AS VARCHAR(255)) AS caseownerteamname,
                CAST(data_payload:WeeklyPaymentImpact::TEXT AS VARCHAR(255)) AS weeklypaymentimpact,
                CAST(data_payload:ReasonNotWQ3AC03Decrease::TEXT AS VARCHAR(255)) AS reasonnotwq3ac03decrease,
                CAST(data_payload:StatutoryMaximumRateApplies::TEXT AS VARCHAR(255)) AS statutorymaximumrateapplies,
                TO_TIMESTAMP_TZ(data_payload:IRDecisionEffectiveDate::NUMBER/1000) AS irdecisioneffectivedate,
                CAST(data_payload:InsuredName::TEXT AS VARCHAR(255)) AS insuredname,
                TO_TIMESTAMP_TZ(data_payload:DatePaidTo::NUMBER/1000) AS datepaidto,
                CAST(data_payload:S38Eligibility::TEXT AS VARCHAR(255)) AS s38eligibility,
                TO_TIMESTAMP_TZ(data_payload:COCStartDate::NUMBER/1000) AS cocstartdate,
                TO_TIMESTAMP_TZ(data_payload:DecisionEffectiveDate::NUMBER/1000) AS decisioneffectivedate,
                TO_TIMESTAMP_TZ(data_payload:NonComplianceCessationDate::NUMBER/1000) AS noncompliancecessationdate,
                CAST(data_payload:ICDCodeAndDescription::TEXT AS VARCHAR(255)) AS icdcodeanddescription,
                CAST(data_payload:WCDRefNo::TEXT AS VARCHAR(255)) AS wcdrefno,
                TO_TIMESTAMP_TZ(data_payload:EarliestIndexationPointWQ3::NUMBER/1000) AS earliestindexationpointwq3,
                CAST(data_payload:S38RefNo::TEXT AS VARCHAR(255)) AS s38refno,
                CAST(data_payload:DoesClaimFlowToWq1OrWq2::TEXT AS VARCHAR(255)) AS doesclaimflowtowq1orwq2,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwcc', 'ccx_piaweindexremreport_ext') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                CAST($1:latestwq3indexedperiod::TEXT AS VARCHAR(255)) AS latestwq3indexedperiod,
                $1:s38eligibilityeffectivedate::TIMESTAMP_TZ AS s38eligibilityeffectivedate,
                $1:earliestwbpaidfromdate::TIMESTAMP_TZ AS earliestwbpaidfromdate,
                $1:weeklybenefitscessationdate::TIMESTAMP_TZ AS weeklybenefitscessationdate,
                CAST($1:claimnumber::TEXT AS VARCHAR(255)) AS claimnumber,
                CAST($1:caseownername::TEXT AS VARCHAR(255)) AS caseownername,
                CAST($1:piawetype::TEXT AS VARCHAR(255)) AS piawetype,
                CAST($1:cocfitness::TEXT AS VARCHAR(255)) AS cocfitness,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:id::NUMBER AS id,
                $1:createuserid::NUMBER AS createuserid,
                CAST($1:irweeklypaymentimpact::TEXT AS VARCHAR(255)) AS irweeklypaymentimpact,
                CAST($1:mename::TEXT AS VARCHAR(255)) AS mename,
                $1:retirementdate::TIMESTAMP_TZ AS retirementdate,
                $1:beanversion::NUMBER AS beanversion,
                $1:dateofloss::TIMESTAMP_TZ AS dateofloss,
                $1:retired::NUMBER AS retired,
                CAST($1:wcddetails::TEXT AS VARCHAR(16777216)) AS wcddetails,
                CAST($1:claimant::TEXT AS VARCHAR(255)) AS claimant,
                CAST($1:resultofinjury::TEXT AS VARCHAR(255)) AS resultofinjury,
                CAST($1:didtheclaimindexinwq3::TEXT AS VARCHAR(255)) AS didtheclaimindexinwq3,
                $1:workstatusstartdate::TIMESTAMP_TZ AS workstatusstartdate,
                $1:noncomplianceeffectivedate::TIMESTAMP_TZ AS noncomplianceeffectivedate,
                CAST($1:piaweamount::TEXT AS VARCHAR(255)) AS piaweamount,
                $1:cocconsultationdate::TIMESTAMP_TZ AS cocconsultationdate,
                CAST($1:claimstatus::TEXT AS VARCHAR(255)) AS claimstatus,
                $1:updateuserid::NUMBER AS updateuserid,
                CAST($1:workstatuscode::TEXT AS VARCHAR(255)) AS workstatuscode,
                CAST($1:reasonnotindexdofi::TEXT AS VARCHAR(255)) AS reasonnotindexdofi,
                CAST($1:adjustment_required::TEXT AS VARCHAR(255)) AS adjustment_required,
                $1:cocenddate::TIMESTAMP_TZ AS cocenddate,
                CAST($1:hasmedicalother::TEXT AS VARCHAR(255)) AS hasmedicalother,
                $1:numberofperiodsindexed::NUMBER AS numberofperiodsindexed,
                CAST($1:liabilitystatus::TEXT AS VARCHAR(255)) AS liabilitystatus,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                CAST($1:picreviewweeklypaymentimpact::TEXT AS VARCHAR(255)) AS picreviewweeklypaymentimpact,
                $1:retirementcessationdateweekly::TIMESTAMP_TZ AS retirementcessationdateweekly,
                $1:compliancedate::TIMESTAMP_TZ AS compliancedate,
                $1:wpipercentage::NUMBER AS wpipercentage,
                CAST($1:wageloss::TEXT AS VARCHAR(255)) AS wageloss,
                $1:weekspaid::NUMBER AS weekspaid,
                CAST($1:hasweeklybenefitsindemnity::TEXT AS VARCHAR(255)) AS hasweeklybenefitsindemnity,
                CAST($1:wcdtype::TEXT AS VARCHAR(255)) AS wcdtype,
                $1:weeklybenefitenddate::TIMESTAMP_TZ AS weeklybenefitenddate,
                CAST($1:picreviewstatus::TEXT AS VARCHAR(255)) AS picreviewstatus,
                $1:effectivedate::TIMESTAMP_TZ AS effectivedate,
                $1:picreviewdecisioneffectivedate::TIMESTAMP_TZ AS picreviewdecisioneffectivedate,
                CAST($1:irstatus::TEXT AS VARCHAR(255)) AS irstatus,
                CAST($1:reasonnowbpaid::TEXT AS VARCHAR(255)) AS reasonnowbpaid,
                $1:reportdate::TIMESTAMP_TZ AS reportdate,
                CAST($1:noncompliancetype::TEXT AS VARCHAR(255)) AS noncompliancetype,
                CAST($1:reasonnomissingpoints::TEXT AS VARCHAR(255)) AS reasonnomissingpoints,
                $1:dateoffirstincapacity::TIMESTAMP_TZ AS dateoffirstincapacity,
                $1:settlementpaymentissuedate::TIMESTAMP_TZ AS settlementpaymentissuedate,
                CAST($1:caseownerteamname::TEXT AS VARCHAR(255)) AS caseownerteamname,
                CAST($1:weeklypaymentimpact::TEXT AS VARCHAR(255)) AS weeklypaymentimpact,
                CAST($1:reasonnotwq3ac03decrease::TEXT AS VARCHAR(255)) AS reasonnotwq3ac03decrease,
                CAST($1:statutorymaximumrateapplies::TEXT AS VARCHAR(255)) AS statutorymaximumrateapplies,
                $1:irdecisioneffectivedate::TIMESTAMP_TZ AS irdecisioneffectivedate,
                CAST($1:insuredname::TEXT AS VARCHAR(255)) AS insuredname,
                $1:datepaidto::TIMESTAMP_TZ AS datepaidto,
                CAST($1:s38eligibility::TEXT AS VARCHAR(255)) AS s38eligibility,
                $1:cocstartdate::TIMESTAMP_TZ AS cocstartdate,
                $1:decisioneffectivedate::TIMESTAMP_TZ AS decisioneffectivedate,
                $1:noncompliancecessationdate::TIMESTAMP_TZ AS noncompliancecessationdate,
                CAST($1:icdcodeanddescription::TEXT AS VARCHAR(255)) AS icdcodeanddescription,
                CAST($1:wcdrefno::TEXT AS VARCHAR(255)) AS wcdrefno,
                $1:earliestindexationpointwq3::TIMESTAMP_TZ AS earliestindexationpointwq3,
                CAST($1:s38refno::TEXT AS VARCHAR(255)) AS s38refno,
                CAST($1:doesclaimflowtowq1orwq2::TEXT AS VARCHAR(255)) AS doesclaimflowtowq1orwq2,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwcc', 'ccx_piaweindexremreport_ext') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS piaweindexremreport_ext_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'latestwq3indexedperiod',
                        's38eligibilityeffectivedate',
                        'earliestwbpaidfromdate',
                        'weeklybenefitscessationdate',
                        'claimnumber',
                        'caseownername',
                        'piawetype',
                        'cocfitness',
                        'updatetime',
                        'createuserid',
                        'irweeklypaymentimpact',
                        'mename',
                        'retirementdate',
                        'beanversion',
                        'dateofloss',
                        'retired',
                        'wcddetails',
                        'claimant',
                        'resultofinjury',
                        'didtheclaimindexinwq3',
                        'workstatusstartdate',
                        'noncomplianceeffectivedate',
                        'piaweamount',
                        'cocconsultationdate',
                        'claimstatus',
                        'updateuserid',
                        'workstatuscode',
                        'reasonnotindexdofi',
                        'adjustment_required',
                        'cocenddate',
                        'hasmedicalother',
                        'numberofperiodsindexed',
                        'liabilitystatus',
                        'publicid',
                        'createtime',
                        'picreviewweeklypaymentimpact',
                        'retirementcessationdateweekly',
                        'compliancedate',
                        'wpipercentage',
                        'wageloss',
                        'weekspaid',
                        'hasweeklybenefitsindemnity',
                        'wcdtype',
                        'weeklybenefitenddate',
                        'picreviewstatus',
                        'effectivedate',
                        'picreviewdecisioneffectivedate',
                        'irstatus',
                        'reasonnowbpaid',
                        'reportdate',
                        'noncompliancetype',
                        'reasonnomissingpoints',
                        'dateoffirstincapacity',
                        'settlementpaymentissuedate',
                        'caseownerteamname',
                        'weeklypaymentimpact',
                        'reasonnotwq3ac03decrease',
                        'statutorymaximumrateapplies',
                        'irdecisioneffectivedate',
                        'insuredname',
                        'datepaidto',
                        's38eligibility',
                        'cocstartdate',
                        'decisioneffectivedate',
                        'noncompliancecessationdate',
                        'icdcodeanddescription',
                        'wcdrefno',
                        'earliestindexationpointwq3',
                        's38refno',
                        'doesclaimflowtowq1orwq2'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) AS dbt_updated_at
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}