{#-

Project: Data Uplift Program
Project Description/Purpose: Data Uplift Program

Date            Version         Author          Description of Change
2026-01-01      0.0                             Incremental model for Acodoca reference data.
-#}
{{
    config(
        materialized='incremental',
        unique_key='acdoca_sk',
        on_schema_change='append_new_columns',
        cluster_by = ['posting_date'],  
        incremental_strategy = 'merge',
        tags=['sap','business_critical']

    )
}}

with cte_source as
(
SELECT 
       CAST(acdoca_sk AS VARCHAR(150))     as acdoca_sk,
       CAST(rldnr AS VARCHAR(2))           AS ledger,
       CAST(rbukrs AS VARCHAR(4))          AS company_code,
       CAST(gjahr AS VARCHAR(4))           AS fiscal_year,
       CAST(belnr AS VARCHAR(10))          AS document_number,
       CAST(docln AS VARCHAR(6))           AS line_itemdocln,
       CAST(ryear AS VARCHAR(4))           AS g_l_fiscal_year,
       CAST(rmvct AS VARCHAR(3))           AS transaction_type,
       CAST(vorgn AS VARCHAR(4))           AS g_l_transaction_type,
       CAST(vrgng AS VARCHAR(4))           AS business_transaction,
       CAST(bttype AS VARCHAR(4))          AS bus_transac_type,
       CAST(awtyp AS VARCHAR(5))           AS reference_procedure,
       CAST(aworg AS VARCHAR(10))          AS reference_org_unit,
       CAST(awref AS VARCHAR(10))          AS reference_document,
       CAST(awitem AS VARCHAR(6))          AS ref_doc_line_item,
       CAST(awitgrp AS VARCHAR(6))         AS ref_doc_item_group,
       CAST(subta AS VARCHAR(6))           AS sub_transaction,
       CAST(xreversing AS VARCHAR(1))      AS is_reversing_another_item,
       CAST(xreversed AS VARCHAR(1))       AS is_reversed,
       CAST(xtruerev AS VARCHAR(1))        AS is_true_reversal,
       CAST(awtyp_rev AS VARCHAR(5))       AS reversal_ref_transcn,
       CAST(aworg_rev AS VARCHAR(10))      AS reversal_organizatn,
       CAST(awref_rev AS VARCHAR(10))      AS reversal_referen_no,
       CAST(rtcur AS VARCHAR(5))           AS transaction_currency,
       CAST(rwcur AS VARCHAR(5))           AS or_transctn_currency,
       CAST(rhcur AS VARCHAR(5))           AS local_currency,
       CAST(rkcur AS VARCHAR(5))           AS co_area_currency,
       CAST(rco_ocur AS VARCHAR(5))        AS object_currency,
       CAST(runit AS VARCHAR(3))           AS base_unit_of_measure,
       CAST(racct AS VARCHAR(10))          AS account_number,
       CAST(rcntr AS VARCHAR(10))          AS cost_center,
       CAST(prctr AS VARCHAR(10))          AS profit_center,
       CAST(kokrs AS VARCHAR(4))           AS controlling_area,
       CAST(scntr AS VARCHAR(10))          AS sender_cost_center,
       CAST(pprctr AS VARCHAR(10))         AS partner_profit_ctr,
       CAST(rassc AS VARCHAR(6))           AS trading_partner,
       CAST(tsl AS NUMBER(17, 3))          AS amount_in_trans_crcy,
       CAST(wsl AS NUMBER(13))             AS amnt_in_origtrnscrcy,
       CAST(hsl AS NUMBER(17, 3))          AS amount_in_local_crcy,
       CAST(ksl AS NUMBER(17, 3))          AS amount_in_group_crcy,
       CAST(co_osl AS NUMBER(17, 3))       AS value_in_object_crcy,
       CAST(msl AS NUMBER(17, 3))          AS quantity,
       CAST(drcrk AS VARCHAR(1))           AS debit_credit_ind,
       CAST(poper AS VARCHAR(3))           AS posting_period,
       CAST(periv AS VARCHAR(2))           AS fiscal_year_variant,
       CAST(fiscyearper AS VARCHAR(7))     AS period_year,
       CAST(budat AS DATE)                 AS posting_date,
       CAST(bldat AS  DATE)                AS document_date,
       CAST(blart AS VARCHAR(2))           AS document_type,
       CAST(buzei AS VARCHAR(3))           AS line_itembuzei,
       CAST(zuonr AS VARCHAR(18))          AS assignment,
       CAST(bschl AS VARCHAR(2))           AS posting_key,
       CAST(bstat AS VARCHAR(1))           AS doc_status,
       CAST(linetype AS VARCHAR(5))        AS item_category,
       CAST(ktosl AS VARCHAR(3))           AS transaction_key,
       CAST(slalittype AS VARCHAR(5))      AS sla_line_item_type,
       CAST(xsplitmod AS VARCHAR(1))       AS changed_doc_split,
       CAST(usnam AS VARCHAR(12))          AS user_name,
       CAST(timestamp AS VARCHAR(19))      AS time_stamp,
       CAST(eprctr AS VARCHAR(10))         AS elimination_prctr,
       CAST(rhoart AS VARCHAR(2))          AS origin_object,
       CAST(glaccount_type AS VARCHAR(1))  AS g_l_account_type,
       CAST(ktopl AS VARCHAR(4))           AS chart_of_accounts,
       CAST(ebeln AS VARCHAR(10))          AS purchasing_document,
       CAST(ebelp AS VARCHAR(50))          AS text,
       CAST(sgtxt AS VARCHAR(4))           AS plant,
       CAST(werks AS VARCHAR(10))          AS vendor,
       CAST(lifnr AS VARCHAR(10))          AS customer,
       CAST(kunnr AS VARCHAR(1))           AS account_type,
       CAST(koart AS VARCHAR(2))           AS tax_code,
       CAST(mwskz AS VARCHAR(5))           AS house_bank,
       CAST(hbkid AS VARCHAR(5))           AS account_id,
       CAST(hktid AS VARCHAR(1))           AS open_item_management,
       CAST(xopvw AS  DATE)                 AS clearing_date,
       CAST(augdt AS VARCHAR(10))          AS clearing_document,
       CAST(augbl AS VARCHAR(4))           AS clearing_fiscal_year,
       CAST(auggj AS VARCHAR(2))           AS depreciation_area,
       CAST(afabe AS VARCHAR(12))          AS asset,
       CAST(anln1 AS VARCHAR(4))           AS sub_number,
       CAST(anln2 AS DATE)                  AS asset_value_date,
       CAST(bzdat AS VARCHAR(3))           AS asset_transaction_type,
       CAST(anbwa AS VARCHAR(2))           AS trans_type_category,
       CAST(movcat AS VARCHAR(3))          AS depreciation_period,
       CAST(depr_period AS VARCHAR(12))    AS group_asset,
       CAST(anlgr AS VARCHAR(4))           AS subnumber,
       CAST(anlgr2 AS VARCHAR(3))          AS dist_rule_group,
       CAST(settlement_rule AS VARCHAR(4)) AS valuation_area,
       CAST(bwkey AS VARCHAR(22))          AS object_number,
       CAST(objnr AS VARCHAR(14))          AS co_subkey,
       CAST(hrkft AS VARCHAR(4))           AS origin_group,
       CAST(hkgrp AS VARCHAR(22))          AS partner_object,
       CAST(parob1 AS VARCHAR(1))          AS partner_obj_source,
       CAST(parobsrc AS VARCHAR(22))       AS source_object,
       CAST(uspob AS VARCHAR(1))           AS dr_cr_indicator_co,
       CAST(co_belkz AS VARCHAR(1))        AS dr_cr_ind__origin,
       CAST(co_beknz AS VARCHAR(1))        AS debit_type,
       CAST(beltp AS VARCHAR(1))           AS quantity_is_incomplete,
       CAST(muvflg AS VARCHAR(10))         AS offsetting_account_number,
       CAST(gkont AS VARCHAR(1))           AS offsetting_account_type,
       CAST(gkoar AS VARCHAR(2))           AS object_class,
       CAST(scope AS VARCHAR(4))           AS company_code_of_partner,
       CAST(pbukrs AS VARCHAR(2))          AS partner_object_class,
       CAST(pscope AS VARCHAR(10))         AS origin_cost_center,
       CAST(aufnr_org AS VARCHAR(30))      AS sener_account_assignment,
       CAST(ukostl AS VARCHAR(2))          AS object_type,
       CAST(accas AS VARCHAR(12))          AS order_num,
       CAST(acCASTy AS VARCHAR(30))        AS partner_account_assignment,
       CAST(aufnr AS VARCHAR(2))           AS partner_object_type,
       CAST(paccas AS VARCHAR(10))         AS co_document_number,
       CAST(pacCASTy AS VARCHAR(3))        AS posting_row,
       CAST(co_belnr AS VARCHAR(3))        AS posting_row_of_reference_document,
       CAST(co_buzei AS VARCHAR(6))        AS channel,
       CAST(co_refbz AS VARCHAR(6))        AS product,
       CAST(zzchannel AS VARCHAR(4))       AS underwriting_year,
       CAST(zzproduct AS VARCHAR(4))       AS accident_year,
       CAST(zzuwyear AS VARCHAR(30))       AS claim_number,
       CAST(zzaccyear AS VARCHAR(30))      AS policy_number,
       CAST(zzclaimno AS VARCHAR(100))     AS authorised_provider,
       CAST(zzpolicyno AS VARCHAR(50))     AS package_key,
       CAST(zzdebtorname AS VARCHAR(16))   AS unit_price,
       CAST(zzcounterp AS VARCHAR(30))     AS account,
       CAST(zzunitprc AS VARCHAR(20))      AS prime_number,
       CAST(zzaccount AS VARCHAR(20))      AS invoice_number,
       CAST(zzprimeno AS VARCHAR(10))      AS zzriskdt,
       CAST(zzinvno AS VARCHAR(10))        AS policy_end_date,
       CAST(zzriskdt AS VARCHAR(20))       AS guidewire_file_id,
       CAST(zzpolenddt AS VARCHAR(20))     AS guidewire_transaction_number,
       CAST(zzgwid AS VARCHAR(1))          AS
       source_of_a_migrated_journal_entry_item,
       CAST(zztranno AS VARCHAR(6))        AS item_id_of_migrated_g_l_line_item,
       metadata_file_name,
       file_ingestion_timestamp
FROM   
        {{ref('acdoca_snapshot')}} 
{% if is_incremental() %}
    where file_ingestion_timestamp >= (select max(file_ingestion_timestamp) from {{ this }})
 {% endif %}
)

SELECT 
    *
FROM cte_source