{#-
  Project: Data Uplift Program
  Project Description/Purpose: Data Uplift Program
  Date        Version  Author  Description of Change
  2026-01-01  0.0              Incremental model for MON Balance.
-#}

{{
  config(
    materialized='incremental',
    unique_key='mon_bal_sk',
    on_schema_change='append_new_columns',
    incremental_strategy='merge',
    tags=['sap','business_critical']

  )
}}

with cte_source as (
SELECT 
    cast(mon_bal_sk as varchar(64)) as mon_bal_sk, 
    cast(ryear as varchar(4)) as fiscal_year,
    cast(drcrk as varchar(1)) as debit_credit_ind,
    cast(rpmax as varchar(3)) as period,
    cast(activ as varchar(4)) as transaction_key,
    cast(rmvct as varchar(3)) as transaction_type,
    cast(rtcur as varchar(5)) as transaction_currency,
    cast(runit as varchar(3)) as base_unit_of_measure,
    cast(awtyp as varchar(5)) as reference_procedure,
    cast(rldnr as varchar(2)) as ledger,
    cast(rrcty as varchar(1)) as record_type,
    cast(rvers as varchar(3)) as version,
    cast(racct as varchar(10)) as account_number,
    cast(cost_elem as varchar(10)) as cost_element,
    cast(rbukrs as varchar(4)) as company_code,
    cast(rcntr as varchar(10)) as cost_center,
    cast(prctr as varchar(10)) as profit_center,
    cast(rfarea as varchar(16)) as functional_area,
    cast(rbusa as varchar(4)) as business_area,
    cast(kokrs as varchar(4)) as controlling_area,
    cast(segment as varchar(10)) as segment,
    cast(scntr as varchar(10)) as sender_cost_center,
    cast(pprctr as varchar(10)) as partner_profit_ctr,
    cast(sfarea as varchar(16)) as partner_func_area,
    cast(sbusa as varchar(4)) as trading_part_ba,
    cast(rassc as varchar(6)) as trading_partner,
    cast(psegment as varchar(10)) as partner_segment,
    cast(replace(replace(replace(tslvt, ',', ''), '$', ''), ' ', '') as number(18,2)) as BAL_C_F_TC,
    cast(replace(replace(replace(tsl01, ',', ''), '$', ''), ' ', '') as number(18,2)) as tsl01,
    cast(replace(replace(replace(tsl02, ',', ''), '$', ''), ' ', '') as number(18,2)) as tsl02,
    cast(replace(replace(replace(tsl03, ',', ''), '$', ''), ' ', '') as number(18,2)) as tsl03,
    cast(replace(replace(replace(tsl04, ',', ''), '$', ''), ' ', '') as number(18,2)) as tsl04,
    cast(replace(replace(replace(tsl05, ',', ''), '$', ''), ' ', '') as number(18,2)) as tsl05,
    cast(replace(replace(replace(tsl06, ',', ''), '$', ''), ' ', '') as number(18,2)) as tsl06,
    cast(replace(replace(replace(tsl07, ',', ''), '$', ''), ' ', '') as number(18,2)) as tsl07,
    cast(replace(replace(replace(tsl08, ',', ''), '$', ''), ' ', '') as number(18,2)) as tsl08,
    cast(replace(replace(replace(tsl09, ',', ''), '$', ''), ' ', '') as number(18,2)) as tsl09,
    cast(replace(replace(replace(tsl10, ',', ''), '$', ''), ' ', '') as number(18,2)) as tsl10,
    cast(replace(replace(replace(tsl11, ',', ''), '$', ''), ' ', '') as number(18,2)) as tsl11,
    cast(replace(replace(replace(tsl12, ',', ''), '$', ''), ' ', '') as number(18,2)) as tsl12,
    cast(replace(replace(replace(tsl13, ',', ''), '$', ''), ' ', '') as number(18,2)) as tsl13,
    cast(replace(replace(replace(tsl14, ',', ''), '$', ''), ' ', '') as number(18,2)) as tsl14,
    cast(replace(replace(replace(tsl15, ',', ''), '$', ''), ' ', '') as number(18,2)) as tsl15,
    cast(replace(replace(replace(tsl16, ',', ''), '$', ''), ' ', '') as number(18,2)) as tsl16,
    cast(replace(replace(replace(hslvt, ',', ''), '$', ''), ' ', '') as number(18,2)) as bal_c_f_lc,
    cast(replace(replace(replace(hsl01, ',', ''), '$', ''), ' ', '') as number(18,2)) as hsl01,
    cast(replace(replace(replace(hsl02, ',', ''), '$', ''), ' ', '') as number(18,2)) as hsl02,
    cast(replace(replace(replace(hsl03, ',', ''), '$', ''), ' ', '') as number(18,2)) as hsl03,
    cast(replace(replace(replace(hsl04, ',', ''), '$', ''), ' ', '') as number(18,2)) as hsl04,
    cast(replace(replace(replace(hsl05, ',', ''), '$', ''), ' ', '') as number(18,2)) as hsl05,
    cast(replace(replace(replace(hsl06, ',', ''), '$', ''), ' ', '') as number(18,2)) as hsl06,
    cast(replace(replace(replace(hsl07, ',', ''), '$', ''), ' ', '') as number(18,2)) as hsl07,
    cast(replace(replace(replace(hsl08, ',', ''), '$', ''), ' ', '') as number(18,2)) as hsl08,
    cast(replace(replace(replace(hsl09, ',', ''), '$', ''), ' ', '') as number(18,2)) as hsl09,
    cast(replace(replace(replace(hsl10, ',', ''), '$', ''), ' ', '') as number(18,2)) as hsl10,
    cast(replace(replace(replace(hsl11, ',', ''), '$', ''), ' ', '') as number(18,2)) as hsl11,
    cast(replace(replace(replace(hsl12, ',', ''), '$', ''), ' ', '') as number(18,2)) as hsl12,
    cast(replace(replace(replace(hsl13, ',', ''), '$', ''), ' ', '') as number(18,2)) as hsl13,
    cast(replace(replace(replace(hsl14, ',', ''), '$', ''), ' ', '') as number(18,2)) as hsl14,
    cast(replace(replace(replace(hsl15, ',', ''), '$', ''), ' ', '') as number(18,2)) as hsl15,
    cast(replace(replace(replace(hsl16, ',', ''), '$', ''), ' ', '') as number(18,2)) as hsl16,
    metadata_file_name,
    file_ingestion_timestamp
    from {{ ref('mon_bal_snapshot') }}
    where dbt_valid_to is null

    {% if is_incremental() %}
        and file_ingestion_timestamp >= (select max(file_ingestion_timestamp) from {{ this }})
    {% endif %}
)

    SELECT 
            mon_bal_sk,
            fiscal_year,
            debit_credit_ind,
            period,
            transaction_key,
            transaction_type,
            transaction_currency,
            base_unit_of_measure,
            reference_procedure,
            ledger,
            record_type,
            version,
            account_number,
            cost_element,
            company_code,
            cost_center,
            profit_center,
            functional_area,
            business_area,
            controlling_area,
            segment,
            sender_cost_center,
            partner_profit_ctr,
            partner_func_area,
            trading_part_ba,
            trading_partner,
            partner_segment,
            bal_c_f_tc,
            tsl01,
            tsl02,
            tsl03,
            tsl04,
            tsl05,
            tsl06,
            tsl07,
            tsl08,
            tsl09,
            tsl10,
            tsl11,
            tsl12,
            tsl13,
            tsl14,
            tsl15,
            tsl16,
            bal_c_f_lc,
            hsl01,
            hsl02,
            hsl03,
            hsl04,
            hsl05,
            hsl06,
            hsl07,
            hsl08,
            hsl09,
            hsl10,
            hsl11,
            hsl12,
            hsl13,
            hsl14,
            hsl15,
            hsl16,
            metadata_file_name,
            file_ingestion_timestamp
    from cte_source                
            
