{#-
  Project: Data Uplift Program
  Project Description/Purpose: Data Uplift Program
  Date        Version  Author  Description of Change
  2026-01-01  0.0              Incremental model for Procurement.
-#}

{{
  config(
    materialized='incremental',
    unique_key='procurement_sk',
    on_schema_change='append_new_columns',
    incremental_strategy='merge',
    tags=['sap','business_critical']

  )
}}

with cte_source as (

    select
        cast(procurement_sk as varchar(64)) as procurement_sk,
        cast(ebeln as varchar(10)) as purchasing_document,
        cast(ebelp as varchar(5)) as item,
        cast(aedat as varchar(12)) as created_on,
        cast(txz01 as varchar(40)) as short_text,
        cast(bukrs as varchar(4)) as company_code,
        cast(werks as varchar(4)) as plant,
        cast(matkl as varchar(9)) as material_group,
        cast(ktmng as number(16,4)) as target_quantity,
        cast(menge as number(16,4)) as quantity,
        cast(meins as varchar(3)) as order_unit,
        cast(bprme as varchar(3)) as order_price_unit,
        cast(bpumz as varchar(5)) as quantity_conversion_numerator,
        cast(bpumn as varchar(5)) as quantity_conversion_denominator_denomin,
        cast(umrez as varchar(5)) as equal_to,
        cast(umren as varchar(5)) as denominator,
        cast(replace(replace(replace(netpr, ',', ''), '$', ''), ' ', '') as number(18,2)) as net_price_in_purchasing_document,
        cast(replace(replace(replace(peinh, ',', ''), '$', ''), ' ', '') as number(18,2)) as price_unit,
        cast(replace(replace(replace(netwr, ',', ''), '$', ''), ' ', '') as number(18,2)) as net_order_value_in_po_currency,
        cast(replace(replace(replace(brtwr, ',', ''), '$', ''), ' ', '') as number(18,2)) as gross_order_value_in_po_currency,
        cast(mwskz as varchar(2)) as tax_code,
        cast(pstyp as varchar(1)) as item_category_in_purchasing_document,
        cast(knttp as varchar(1)) as account_assignment_category,
        cast(kzvbr as varchar(1)) as consumption,
        cast(vrtkz as varchar(1)) as distribut_indicator,
        cast(twrkz as varchar(1)) as partial_invoice,
        cast(wepos as varchar(1)) as goods_receiptweposwepos,
        cast(weunb as varchar(1)) as goods_receipt,
        cast(repos as varchar(1)) as invoice_receipt,
        cast(prdat as varchar(12)) as price_date,
        cast(bstyp as varchar(1)) as purch_doc_category,
        cast(effwr as number(16,4)) as effective_value_of_item,
        cast(xoblr as varchar(1)) as affects_commitments,
        cast(replace(replace(replace(kzwi1, ',', ''), '$', ''), ' ', '') as number(18,2)) as subtotal_1,
        cast(replace(replace(replace(kzwi2, ',', ''), '$', ''), ' ', '') as number(18,2)) as subtotal_2,
        cast(replace(replace(replace(kzwi3, ',', ''), '$', ''), ' ', '') as number(18,2)) as subtotal_3,
        cast(replace(replace(replace(kzwi4, ',', ''), '$', ''), ' ', '') as number(18,2)) as subtotal_4,
        cast(replace(replace(replace(kzwi5, ',', ''), '$', ''), ' ', '') as number(18,2)) as subtotal_5,
        cast(replace(replace(replace(kzwi5, ',', ''), '$', ''), ' ', '') as number(18,2)) as subtotal_6,
        cast(replace(replace(replace(bonba, ',', ''), '$', ''), ' ', '') as number(18,2)) as rebate_basis_1,
        cast(afnam as varchar(12)) as requisitioner,
        cast(tzonrc as varchar(6)) as time_zone_of_recipient_location,
        cast(bsart as varchar(4)) as purchasing_doc_type,
        cast(bsakz as varchar(1)) as control_indicator,
        cast(loekz as varchar(1)) as deletion_indicator,
        cast(statu as varchar(1)) as status,
        cast(aedat as varchar(12)) as purchasing_document_item_change_date,
        cast(ernam as varchar(12)) as created_by,
        cast(pincr as varchar(5)) as item_number_interval,
        cast(lponr as number(16,4)) as last_item,
        cast(lifnr as varchar(10)) as vendor,
        cast(spras as varchar(1)) as language_key,
        cast(zterm as varchar(4)) as terms_of_payment,
        cast(zbd1t as varchar(3)) as payment_in,
        cast(zbd2t as varchar(3)) as payment_in_2,
        cast(zbd3t as varchar(3)) as payment_in_3,
        cast(zbd1p as varchar(9)) as disc_percent_1,
        cast(zbd2p as varchar(9)) as disc_percent_2,
        cast(ekorg as varchar(4)) as purch_organization,
        cast(ekgrp as varchar(3)) as purchasing_group,
        cast(waers as varchar(5)) as currency,
        cast(wkurs as varchar(14)) as exchange_rate,
        cast(kufix as varchar(1)) as exchange_rate_fixed,
        cast(bedat as varchar(12)) as document_date,
        cast(ihrez as varchar(12)) as your_reference,
        cast(replace(replace(replace(ktwrt, ',', ''), '$', ''), ' ', '') as number(18,2)) as target_value,
        cast(knumv as varchar(10)) as doc_condition_no,
        cast(kalsm as varchar(6)) as pricing_procedure,
        cast(stafo as varchar(6)) as update_group_stats,
        cast(lifre as varchar(10)) as invoicing_party,
        cast(upinc as varchar(5)) as subitem_interval,
        cast(lands as varchar(3)) as cntry_for_tax_return,
        cast(stceg as varchar(30)) as country_sls_tax_no,
        cast(stceg as varchar(30)) as vat_registration_no,
        cast(absgr as varchar(2)) as reason_for_canc,
        cast(procstat as varchar(2)) as purch_doc_proc_state,
        cast(replace(replace(replace(rlwrt, ',', ''), '$', ''), ' ', '') as number(18,2)) as total_val_upon_release,
        metadata_file_name,
        file_ingestion_timestamp
    from {{ ref('procurement_snapshot') }}
    where dbt_valid_to is null

    {% if is_incremental() %}
        and file_ingestion_timestamp >= (select max(file_ingestion_timestamp) from {{ this }})
    {% endif %}

)

select
    procurement_sk,
    purchasing_document,
    item,
    created_on,
    short_text,
    company_code,
    plant,
    material_group,
    target_quantity,
    quantity,
    order_unit,
    order_price_unit,
    quantity_conversion_numerator,
    quantity_conversion_denominator_denomin,
    equal_to,
    denominator,
    net_price_in_purchasing_document,
    price_unit,
    net_order_value_in_po_currency,
    gross_order_value_in_po_currency,
    tax_code,
    item_category_in_purchasing_document,
    account_assignment_category,
    consumption,
    distribut_indicator,
    partial_invoice,
    goods_receiptweposwepos,
    goods_receipt,
    invoice_receipt,
    price_date,
    purch_doc_category,
    effective_value_of_item,
    affects_commitments,
    subtotal_1,
    subtotal_2,
    subtotal_3,
    subtotal_4,
    subtotal_5,
    subtotal_6,
    rebate_basis_1,
    requisitioner,
    time_zone_of_recipient_location,
    purchasing_doc_type,
    control_indicator,
    deletion_indicator,
    status,
    purchasing_document_item_change_date,
    created_by,
    item_number_interval,
    last_item,
    vendor,
    language_key,
    terms_of_payment,
    payment_in,
    payment_in_2,
    payment_in_3,
    disc_percent_1,
    disc_percent_2,
    purch_organization,
    purchasing_group,
    currency,
    exchange_rate,
    exchange_rate_fixed,
    document_date,
    your_reference,
    target_value,
    doc_condition_no,
    pricing_procedure,
    update_group_stats,
    invoicing_party,
    subitem_interval,
    cntry_for_tax_return,
    country_sls_tax_no,
    vat_registration_no,
    reason_for_canc,
    purch_doc_proc_state,
    total_val_upon_release,
    metadata_file_name,
    file_ingestion_timestamp
from cte_source