{#-

Project: Data Uplift Program 
Project Description/Purpose: Data Uplift Program 

Date            Version         Author          Description of Change           
2026-01-01      0.0                             Incremental staging model for bc_policyperiod.
                                                policyperiod_sk: Entity identity surrogate key on PK ('id')
                                                hash_key: State change detection surrogate key on all business cols excluding PK
                                                dbt_updated_at: COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp)
                                                Uniform across AVRO and PARQUET - no code change when CDC goes live
                                                UNION ALL for BackFill of Data i.e. Incase of Rebuild of Upstream Model 
-#}   

{{ config(
    materialized='incremental',
    transient=True,
    unique_key='id',
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=["landing", "gwbc", "billing_centre", "business_critical", "bc_policyperiod"]
) }}


WITH cte_source_data AS 
(

            SELECT
                data_payload:LoadCommandID::NUMBER AS loadcommandid,
                data_payload:HeldForInvoiceSending::BOOLEAN AS heldforinvoicesending,
                data_payload:UnderAudit::BOOLEAN AS underaudit,
                data_payload:SecurityZoneID::NUMBER AS securityzoneid,
                TO_TIMESTAMP_TZ(data_payload:PolicyPerEffDate::NUMBER/1000) AS policypereffdate,
                data_payload:PaymentPlanID::NUMBER AS paymentplanid,
                data_payload:ArchiveState::NUMBER AS archivestate,
                data_payload:ArchiveSchemaInfo::NUMBER AS archiveschemainfo,
                data_payload:Currency::NUMBER AS currency,
                TO_TIMESTAMP_TZ(data_payload:UpdateTime::NUMBER/1000) AS updatetime,
                data_payload:HiddenTAccountContainerID::NUMBER AS hiddentaccountcontainerid,
                data_payload:ID::NUMBER AS id,
                data_payload:UWCompany::NUMBER AS uwcompany,
                data_payload:HoldInvoicingWhenDelinquent::BOOLEAN AS holdinvoicingwhendelinquent,
                data_payload:BillingMethod::NUMBER AS billingmethod,
                data_payload:OverridingPayerAccountID::NUMBER AS overridingpayeraccountid,
                data_payload:AssignedRisk::BOOLEAN AS assignedrisk,
                CAST(data_payload:ExcludeReason::TEXT AS VARCHAR(255)) AS excludereason,
                CAST(data_payload:MinPremiumApplicable_icare AS NUMBER(18,2)) AS minpremiumapplicable_icare,
                data_payload:OverridingInvoiceStreamID::NUMBER AS overridinginvoicestreamid,
                data_payload:CreateUserID::NUMBER AS createuserid,
                data_payload:ArchiveFailureID::NUMBER AS archivefailureid,
                CAST(data_payload:DBA::TEXT AS VARCHAR(255)) AS dba,
                TO_TIMESTAMP_TZ(data_payload:FullPayDiscountUntil::NUMBER/1000) AS fullpaydiscountuntil,
                data_payload:PolicyPeriodDelinquencyPlanID::NUMBER AS policyperioddelinquencyplanid,
                CAST(data_payload:OfferNumber::TEXT AS VARCHAR(255)) AS offernumber,
                data_payload:EquityWarningsEnabled::BOOLEAN AS equitywarningsenabled,
                TO_TIMESTAMP_TZ(data_payload:CloseDate::NUMBER/1000) AS closedate,
                TO_TIMESTAMP_TZ(data_payload:NextArchiveCheckDate::NUMBER/1000) AS nextarchivecheckdate,
                data_payload:BeanVersion::NUMBER AS beanversion,
                data_payload:EligibleForFullPayDiscount::BOOLEAN AS eligibleforfullpaydiscount,
                data_payload:Retrieved::BOOLEAN AS retrieved,
                data_payload:Retired::NUMBER AS retired,
                TO_TIMESTAMP_TZ(data_payload:BoundDate::NUMBER/1000) AS bounddate,
                data_payload:IsLegacy_icare::BOOLEAN AS islegacy_icare,
                data_payload:UpdateUserID::NUMBER AS updateuserid,
                data_payload:EmployerType_icare::NUMBER AS employertype_icare,
                data_payload:FullPayDiscountEvaluated::BOOLEAN AS fullpaydiscountevaluated,
                data_payload:BTPAmount_icare_cur::NUMBER AS btpamount_icare_cur,
                data_payload:WesternMethod::BOOLEAN AS westernmethod,
                data_payload:TermNumber::NUMBER AS termnumber,
                data_payload:ArchiveTAcctContainerID::NUMBER AS archivetacctcontainerid,
                data_payload:PendingRemainingBalanceFix::BOOLEAN AS pendingremainingbalancefix,
                CAST(data_payload:BTPAmount_icare_amt AS NUMBER(18,2)) AS btpamount_icare_amt,
                data_payload:OfferingType_icare::NUMBER AS offeringtype_icare,
                data_payload:CancellationType::NUMBER AS cancellationtype,
                CAST(data_payload:CancelReason::TEXT AS VARCHAR(255)) AS cancelreason,
                CAST(data_payload:LegacyPolicyNumber_icare::TEXT AS VARCHAR(60)) AS legacypolicynumber_icare,
                CAST(data_payload:PublicID::TEXT AS VARCHAR(64)) AS publicid,
                CAST(data_payload:PriorPolicyNumber::TEXT AS VARCHAR(40)) AS priorpolicynumber,
                data_payload:EquityBuffer::NUMBER AS equitybuffer,
                CAST(data_payload:DiscountedPaymentThreshold AS NUMBER(18,2)) AS discountedpaymentthreshold,
                data_payload:DiscountedPaymentThreshold_cur::NUMBER AS discountedpaymentthreshold_cur,
                TO_TIMESTAMP_TZ(data_payload:CreateTime::NUMBER/1000) AS createtime,
                CAST(data_payload:Underwriter::TEXT AS VARCHAR(255)) AS underwriter,
                data_payload:PolicyID::NUMBER AS policyid,
                data_payload:ExcludedFromArchive::BOOLEAN AS excludedfromarchive,
                data_payload:TotalPremium_icare_cur::NUMBER AS totalpremium_icare_cur,
                data_payload:RiskJurisdiction::NUMBER AS riskjurisdiction,
                CAST(data_payload:SubmissionNumber_icare::TEXT AS VARCHAR(60)) AS submissionnumber_icare,
                data_payload:ArchiveFailureDetailsID::NUMBER AS archivefailuredetailsid,
                CAST(data_payload:TotalPremium_icare_amt AS NUMBER(18,2)) AS totalpremium_icare_amt,
                data_payload:SubTermType_icare::NUMBER AS subtermtype_icare,
                data_payload:ArchivePartition::NUMBER AS archivepartition,
                TO_TIMESTAMP_TZ(data_payload:PolicyPerExpirDate::NUMBER/1000) AS policyperexpirdate,
                data_payload:ChargeHeld::BOOLEAN AS chargeheld,
                data_payload:ReturnPremiumPlanID::NUMBER AS returnpremiumplanid,
                data_payload:CancelStatus::NUMBER AS cancelstatus,
                data_payload:ClosureStatus::NUMBER AS closurestatus,
                TO_TIMESTAMP_TZ(data_payload:ArchiveDate::NUMBER/1000) AS archivedate,
                data_payload:ConfirmationNotificationState::NUMBER AS confirmationnotificationstate,
                data_payload:TermConfirmed::BOOLEAN AS termconfirmed,
                CAST(data_payload:PolicyNumberLongDenorm::TEXT AS VARCHAR(255)) AS policynumberlongdenorm,
                data_payload:PolicyGroupInfo_icare::NUMBER AS policygroupinfo_icare,
                CAST(data_payload:PolicyNumberLong::TEXT AS VARCHAR(255)) AS policynumberlong,
                data_payload:PaymentDistributionEnabled::BOOLEAN AS paymentdistributionenabled,
                CAST(data_payload:PolicyNumberDenorm::TEXT AS VARCHAR(40)) AS policynumberdenorm,
                CAST(data_payload:PolicyNumber::TEXT AS VARCHAR(40)) AS policynumber,
                data_payload:PaymentProfile_icare::NUMBER AS paymentprofile_icare,
                data_payload:ReferredToLegal_icare::BOOLEAN AS referredtolegal_icare,
                data_payload:isRolledUpDelin_icare::BOOLEAN AS isrolledupdelin_icare,
                data_payload:reinstateCount_icare::NUMBER AS reinstatecount_icare,
                data_payload:IsLPRApplication_icare::BOOLEAN AS islprapplication_icare,
                data_payload:DelinquencyRiskProfile_icare::NUMBER AS delinquencyriskprofile_icare,
                CAST(data_payload:paymentPlan_icare::TEXT AS VARCHAR(100)) AS paymentplan_icare,
                CAST(data_payload:UpdatedPaymentPlan_icare::TEXT AS VARCHAR(255)) AS updatedpaymentplan_icare,
                data_payload:DoubtfulDebitTotal_icare_cur::NUMBER AS doubtfuldebittotal_icare_cur,
                CAST(data_payload:DoubtfulDebitTotal_icare_amt AS NUMBER(18,2)) AS doubtfuldebittotal_icare_amt,
                CAST(data_payload:ClaimsMgr_SchemeAgent_icare::TEXT AS VARCHAR(100)) AS claimsmgr_schemeagent_icare,
                data_payload:IsSMSEvent_icare::BOOLEAN AS issmsevent_icare,
                data_payload:PolicyType_icare::NUMBER AS policytype_icare,
                data_payload:LPRProductOption_icare::NUMBER AS lprproductoption_icare,
                data_payload:IsCancelOnExpiry_icare::BOOLEAN AS iscancelonexpiry_icare,
                data_payload:CRIFBillingOption_icare::NUMBER AS crifbillingoption_icare,
                TO_TIMESTAMP_TZ(data_payload:ConfirmationDate_icare::NUMBER/1000) AS confirmationdate_icare,
                data_payload:RenewalState_icare::NUMBER AS renewalstate_icare,
                TO_TIMESTAMP_TZ(data_payload:FPDEligibleToDate_icare::NUMBER/1000) AS fpdeligibletodate_icare,
                data_payload:IsPlanChangedAtDel_icare::BOOLEAN AS isplanchangedatdel_icare,
                CAST(data_payload:EligibleFPDAmount_icare AS NUMBER(18,2)) AS eligiblefpdamount_icare,
                data_payload:EligibleFPDAmount_icare_cur::NUMBER AS eligiblefpdamount_icare_cur,
                data_payload:HoldLPF_Ext::BOOLEAN AS holdlpf_ext,
                data_payload:CollapseInstalmentCount_Ext::NUMBER AS collapseinstalmentcount_ext,
                TO_TIMESTAMP_TZ(data_payload:InstalmentCollapsedDate_Ext::NUMBER/1000) AS instalmentcollapseddate_ext,
                TO_TIMESTAMP_TZ(data_payload:InstalmentReinstatedDate_Ext::NUMBER/1000) AS instalmentreinstateddate_ext,
                TO_TIMESTAMP_TZ(data_payload:InstalmentDefaultedDate_Ext::NUMBER/1000) AS instalmentdefaulteddate_ext,
                data_payload:FranchiseDeductible_Ext::NUMBER AS franchisedeductible_ext,
                data_payload:Contribution_Ext::NUMBER AS contribution_ext,
                CAST(data_payload:ITCEntitlement_Ext::TEXT AS VARCHAR(255)) AS itcentitlement_ext,
                data_payload:BudgetNonBudget_Ext::BOOLEAN AS budgetnonbudget_ext,
                data_payload:PolicyCategory_Ext::NUMBER AS policycategory_ext,
                CAST(data_payload:PolicyName_Ext::TEXT AS VARCHAR(255)) AS policyname_ext,
                data_payload:DeclarationForm_Ext::NUMBER AS declarationform_ext,
                data_payload:GSTRegistration_Ext::BOOLEAN AS gstregistration_ext,
                data_payload:WCLabourHireCode_Ext::NUMBER AS wclabourhirecode_ext,
                TO_TIMESTAMP_TZ(data_payload:CommencementDate_Ext::NUMBER/1000) AS commencementdate_ext,
                CAST(data_payload:FranchiseDeductibleLimit_Ext AS NUMBER(18,2)) AS franchisedeductiblelimit_ext,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_connector_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_lsn,
                CAST(NULL AS NUMBER) as gwcbi_operation,
                CAST(NULL AS TIMESTAMP_LTZ) as gwcbi_payload_ts_ms,
                CAST(NULL AS NUMBER) as gwcbi_seqval,
                CAST(NULL AS STRING) as gwcbi_seqval_hex,
                CAST(NULL AS NUMBER) as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'AVRO' file_type
            FROM {{ source('gwbc', 'bc_policyperiod') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'avro'
            UNION ALL 
            SELECT
                $1:loadcommandid::NUMBER AS loadcommandid,
                $1:heldforinvoicesending::BOOLEAN AS heldforinvoicesending,
                $1:underaudit::BOOLEAN AS underaudit,
                $1:securityzoneid::NUMBER AS securityzoneid,
                $1:policypereffdate::TIMESTAMP_TZ AS policypereffdate,
                $1:paymentplanid::NUMBER AS paymentplanid,
                $1:archivestate::NUMBER AS archivestate,
                $1:archiveschemainfo::NUMBER AS archiveschemainfo,
                $1:currency::NUMBER AS currency,
                $1:updatetime::TIMESTAMP_TZ AS updatetime,
                $1:hiddentaccountcontainerid::NUMBER AS hiddentaccountcontainerid,
                $1:id::NUMBER AS id,
                $1:uwcompany::NUMBER AS uwcompany,
                $1:holdinvoicingwhendelinquent::BOOLEAN AS holdinvoicingwhendelinquent,
                $1:billingmethod::NUMBER AS billingmethod,
                $1:overridingpayeraccountid::NUMBER AS overridingpayeraccountid,
                $1:assignedrisk::BOOLEAN AS assignedrisk,
                CAST($1:excludereason::TEXT AS VARCHAR(255)) AS excludereason,
                CAST($1:minpremiumapplicable_icare AS NUMBER(18,2)) AS minpremiumapplicable_icare,
                $1:overridinginvoicestreamid::NUMBER AS overridinginvoicestreamid,
                $1:createuserid::NUMBER AS createuserid,
                $1:archivefailureid::NUMBER AS archivefailureid,
                CAST($1:dba::TEXT AS VARCHAR(255)) AS dba,
                $1:fullpaydiscountuntil::TIMESTAMP_TZ AS fullpaydiscountuntil,
                $1:policyperioddelinquencyplanid::NUMBER AS policyperioddelinquencyplanid,
                CAST($1:offernumber::TEXT AS VARCHAR(255)) AS offernumber,
                $1:equitywarningsenabled::BOOLEAN AS equitywarningsenabled,
                $1:closedate::TIMESTAMP_TZ AS closedate,
                $1:nextarchivecheckdate::TIMESTAMP_TZ AS nextarchivecheckdate,
                $1:beanversion::NUMBER AS beanversion,
                $1:eligibleforfullpaydiscount::BOOLEAN AS eligibleforfullpaydiscount,
                $1:retrieved::BOOLEAN AS retrieved,
                $1:retired::NUMBER AS retired,
                $1:bounddate::TIMESTAMP_TZ AS bounddate,
                $1:islegacy_icare::BOOLEAN AS islegacy_icare,
                $1:updateuserid::NUMBER AS updateuserid,
                $1:employertype_icare::NUMBER AS employertype_icare,
                $1:fullpaydiscountevaluated::BOOLEAN AS fullpaydiscountevaluated,
                $1:btpamount_icare_cur::NUMBER AS btpamount_icare_cur,
                $1:westernmethod::BOOLEAN AS westernmethod,
                $1:termnumber::NUMBER AS termnumber,
                $1:archivetacctcontainerid::NUMBER AS archivetacctcontainerid,
                $1:pendingremainingbalancefix::BOOLEAN AS pendingremainingbalancefix,
                CAST($1:btpamount_icare_amt AS NUMBER(18,2)) AS btpamount_icare_amt,
                $1:offeringtype_icare::NUMBER AS offeringtype_icare,
                $1:cancellationtype::NUMBER AS cancellationtype,
                CAST($1:cancelreason::TEXT AS VARCHAR(255)) AS cancelreason,
                CAST($1:legacypolicynumber_icare::TEXT AS VARCHAR(60)) AS legacypolicynumber_icare,
                CAST($1:publicid::TEXT AS VARCHAR(64)) AS publicid,
                CAST($1:priorpolicynumber::TEXT AS VARCHAR(40)) AS priorpolicynumber,
                $1:equitybuffer::NUMBER AS equitybuffer,
                CAST($1:discountedpaymentthreshold AS NUMBER(18,2)) AS discountedpaymentthreshold,
                $1:discountedpaymentthreshold_cur::NUMBER AS discountedpaymentthreshold_cur,
                $1:createtime::TIMESTAMP_TZ AS createtime,
                CAST($1:underwriter::TEXT AS VARCHAR(255)) AS underwriter,
                $1:policyid::NUMBER AS policyid,
                $1:excludedfromarchive::BOOLEAN AS excludedfromarchive,
                $1:totalpremium_icare_cur::NUMBER AS totalpremium_icare_cur,
                $1:riskjurisdiction::NUMBER AS riskjurisdiction,
                CAST($1:submissionnumber_icare::TEXT AS VARCHAR(60)) AS submissionnumber_icare,
                $1:archivefailuredetailsid::NUMBER AS archivefailuredetailsid,
                CAST($1:totalpremium_icare_amt AS NUMBER(18,2)) AS totalpremium_icare_amt,
                $1:subtermtype_icare::NUMBER AS subtermtype_icare,
                $1:archivepartition::NUMBER AS archivepartition,
                $1:policyperexpirdate::TIMESTAMP_TZ AS policyperexpirdate,
                $1:chargeheld::BOOLEAN AS chargeheld,
                $1:returnpremiumplanid::NUMBER AS returnpremiumplanid,
                $1:cancelstatus::NUMBER AS cancelstatus,
                $1:closurestatus::NUMBER AS closurestatus,
                $1:archivedate::TIMESTAMP_TZ AS archivedate,
                $1:confirmationnotificationstate::NUMBER AS confirmationnotificationstate,
                $1:termconfirmed::BOOLEAN AS termconfirmed,
                CAST($1:policynumberlongdenorm::TEXT AS VARCHAR(255)) AS policynumberlongdenorm,
                $1:policygroupinfo_icare::NUMBER AS policygroupinfo_icare,
                CAST($1:policynumberlong::TEXT AS VARCHAR(255)) AS policynumberlong,
                $1:paymentdistributionenabled::BOOLEAN AS paymentdistributionenabled,
                CAST($1:policynumberdenorm::TEXT AS VARCHAR(40)) AS policynumberdenorm,
                CAST($1:policynumber::TEXT AS VARCHAR(40)) AS policynumber,
                $1:paymentprofile_icare::NUMBER AS paymentprofile_icare,
                $1:referredtolegal_icare::BOOLEAN AS referredtolegal_icare,
                $1:isrolledupdelin_icare::BOOLEAN AS isrolledupdelin_icare,
                $1:reinstatecount_icare::NUMBER AS reinstatecount_icare,
                $1:islprapplication_icare::BOOLEAN AS islprapplication_icare,
                $1:delinquencyriskprofile_icare::NUMBER AS delinquencyriskprofile_icare,
                CAST($1:paymentplan_icare::TEXT AS VARCHAR(100)) AS paymentplan_icare,
                CAST($1:updatedpaymentplan_icare::TEXT AS VARCHAR(255)) AS updatedpaymentplan_icare,
                $1:doubtfuldebittotal_icare_cur::NUMBER AS doubtfuldebittotal_icare_cur,
                CAST($1:doubtfuldebittotal_icare_amt AS NUMBER(18,2)) AS doubtfuldebittotal_icare_amt,
                CAST($1:claimsmgr_schemeagent_icare::TEXT AS VARCHAR(100)) AS claimsmgr_schemeagent_icare,
                $1:issmsevent_icare::BOOLEAN AS issmsevent_icare,
                $1:policytype_icare::NUMBER AS policytype_icare,
                $1:lprproductoption_icare::NUMBER AS lprproductoption_icare,
                $1:iscancelonexpiry_icare::BOOLEAN AS iscancelonexpiry_icare,
                $1:crifbillingoption_icare::NUMBER AS crifbillingoption_icare,
                $1:confirmationdate_icare::TIMESTAMP_TZ AS confirmationdate_icare,
                $1:renewalstate_icare::NUMBER AS renewalstate_icare,
                $1:fpdeligibletodate_icare::TIMESTAMP_TZ AS fpdeligibletodate_icare,
                $1:isplanchangedatdel_icare::BOOLEAN AS isplanchangedatdel_icare,
                CAST($1:eligiblefpdamount_icare AS NUMBER(18,2)) AS eligiblefpdamount_icare,
                $1:eligiblefpdamount_icare_cur::NUMBER AS eligiblefpdamount_icare_cur,
                $1:holdlpf_ext::BOOLEAN AS holdlpf_ext,
                $1:collapseinstalmentcount_ext::NUMBER AS collapseinstalmentcount_ext,
                $1:instalmentcollapseddate_ext::TIMESTAMP_TZ AS instalmentcollapseddate_ext,
                $1:instalmentreinstateddate_ext::TIMESTAMP_TZ AS instalmentreinstateddate_ext,
                $1:instalmentdefaulteddate_ext::TIMESTAMP_TZ AS instalmentdefaulteddate_ext,
                $1:franchisedeductible_ext::NUMBER AS franchisedeductible_ext,
                $1:contribution_ext::NUMBER AS contribution_ext,
                CAST($1:itcentitlement_ext::TEXT AS VARCHAR(255)) AS itcentitlement_ext,
                $1:budgetnonbudget_ext::BOOLEAN AS budgetnonbudget_ext,
                $1:policycategory_ext::NUMBER AS policycategory_ext,
                CAST($1:policyname_ext::TEXT AS VARCHAR(255)) AS policyname_ext,
                $1:declarationform_ext::NUMBER AS declarationform_ext,
                $1:gstregistration_ext::BOOLEAN AS gstregistration_ext,
                $1:wclabourhirecode_ext::NUMBER AS wclabourhirecode_ext,
                $1:commencementdate_ext::TIMESTAMP_TZ AS commencementdate_ext,
                CAST($1:franchisedeductiblelimit_ext AS NUMBER(18,2)) AS franchisedeductiblelimit_ext,
                TO_TIMESTAMP($1:gwcbi___connector_ts_ms::NUMBER / 1000) as gwcbi_connector_ts_ms,
                $1:gwcbi___lsn::NUMBER as gwcbi_lsn,
                $1:gwcbi___operation::NUMBER as gwcbi_operation,
                TO_TIMESTAMP($1:gwcbi___payload_ts_ms::NUMBER / 1000) as gwcbi_payload_ts_ms,
                $1:gwcbi___seqval::NUMBER as gwcbi_seqval,
                $1:gwcbi___seqval_hex::STRING as gwcbi_seqval_hex,
                $1:gwcbi___tx_id::NUMBER as gwcbi_tx_id,
                metadata_file_name,
                file_ingestion_timestamp,
                'PARQUET' file_type
            FROM {{ source('gwbc', 'bc_policyperiod') }}
            WHERE REGEXP_SUBSTR(metadata_file_name, '[^.]+$') = 'parquet'
            
),

cte_transformed AS (
    SELECT
        *,
        CAST({{ dbt_utils.generate_surrogate_key([
            'id'
        ]) }} AS VARCHAR(150)) AS policyperiod_sk,
        CAST({{ dbt_utils.generate_surrogate_key([
                        'loadcommandid',
                        'heldforinvoicesending',
                        'underaudit',
                        'securityzoneid',
                        'policypereffdate',
                        'paymentplanid',
                        'archivestate',
                        'archiveschemainfo',
                        'currency',
                        'updatetime',
                        'hiddentaccountcontainerid',
                        'uwcompany',
                        'holdinvoicingwhendelinquent',
                        'billingmethod',
                        'overridingpayeraccountid',
                        'assignedrisk',
                        'excludereason',
                        'minpremiumapplicable_icare',
                        'overridinginvoicestreamid',
                        'createuserid',
                        'archivefailureid',
                        'dba',
                        'fullpaydiscountuntil',
                        'policyperioddelinquencyplanid',
                        'offernumber',
                        'equitywarningsenabled',
                        'closedate',
                        'nextarchivecheckdate',
                        'beanversion',
                        'eligibleforfullpaydiscount',
                        'retrieved',
                        'retired',
                        'bounddate',
                        'islegacy_icare',
                        'updateuserid',
                        'employertype_icare',
                        'fullpaydiscountevaluated',
                        'btpamount_icare_cur',
                        'westernmethod',
                        'termnumber',
                        'archivetacctcontainerid',
                        'pendingremainingbalancefix',
                        'btpamount_icare_amt',
                        'offeringtype_icare',
                        'cancellationtype',
                        'cancelreason',
                        'legacypolicynumber_icare',
                        'publicid',
                        'priorpolicynumber',
                        'equitybuffer',
                        'discountedpaymentthreshold',
                        'discountedpaymentthreshold_cur',
                        'createtime',
                        'underwriter',
                        'policyid',
                        'excludedfromarchive',
                        'totalpremium_icare_cur',
                        'riskjurisdiction',
                        'submissionnumber_icare',
                        'archivefailuredetailsid',
                        'totalpremium_icare_amt',
                        'subtermtype_icare',
                        'archivepartition',
                        'policyperexpirdate',
                        'chargeheld',
                        'returnpremiumplanid',
                        'cancelstatus',
                        'closurestatus',
                        'archivedate',
                        'confirmationnotificationstate',
                        'termconfirmed',
                        'policynumberlongdenorm',
                        'policygroupinfo_icare',
                        'policynumberlong',
                        'paymentdistributionenabled',
                        'policynumberdenorm',
                        'policynumber',
                        'paymentprofile_icare',
                        'referredtolegal_icare',
                        'isrolledupdelin_icare',
                        'reinstatecount_icare',
                        'islprapplication_icare',
                        'delinquencyriskprofile_icare',
                        'paymentplan_icare',
                        'updatedpaymentplan_icare',
                        'doubtfuldebittotal_icare_cur',
                        'doubtfuldebittotal_icare_amt',
                        'claimsmgr_schemeagent_icare',
                        'issmsevent_icare',
                        'policytype_icare',
                        'lprproductoption_icare',
                        'iscancelonexpiry_icare',
                        'crifbillingoption_icare',
                        'confirmationdate_icare',
                        'renewalstate_icare',
                        'fpdeligibletodate_icare',
                        'isplanchangedatdel_icare',
                        'eligiblefpdamount_icare',
                        'eligiblefpdamount_icare_cur',
                        'holdlpf_ext',
                        'collapseinstalmentcount_ext',
                        'instalmentcollapseddate_ext',
                        'instalmentreinstateddate_ext',
                        'instalmentdefaulteddate_ext',
                        'franchisedeductible_ext',
                        'contribution_ext',
                        'itcentitlement_ext',
                        'budgetnonbudget_ext',
                        'policycategory_ext',
                        'policyname_ext',
                        'declarationform_ext',
                        'gstregistration_ext',
                        'wclabourhirecode_ext',
                        'commencementdate_ext',
                        'franchisedeductiblelimit_ext'
        ]) }} AS VARCHAR(150)) AS hash_key,
        COALESCE(gwcbi_payload_ts_ms, file_ingestion_timestamp) as record_insertion_date
    FROM cte_source_data
)

SELECT * FROM cte_transformed
{% if is_incremental() %}
WHERE file_ingestion_timestamp > (SELECT COALESCE(MAX(file_ingestion_timestamp), '1900-01-01'::TIMESTAMP_NTZ) FROM {{ this }})
{% endif %}